emqx/emqx

- rel/files/acl.config
The structure of $SYS is pretty well known or can be guessed and can contain non-public information and therefore should be protected.
> Prevent ALL access to $SYS from outside localhost.

- include/emqttd.hrl
- src/emqttd_protocol.erl
- src/emqttd_ws_client.erl
Add all headers from the initial websocket request to `mqtt_client`, enabling all authentication and access control plugins to use `Cookie`, `Origin`, `Authorization` and any other custom headers as necessary.
> Add headers to mqtt_client

- src/emqttd.app.src
Adds missing runtime dependencies on gproc and esockd to `src/emqttd.app.src`
> Add runtime deps on gproc and esockd

- docs/source/cluster.rst
There is no word "forard". Change it to "forward".
> fix typo in docs: "*forward* the message" but not "forard"

- src/emqttd_client.erl
This allows rate limits on a client to be queried
and changed dynamically (possibly by plugins), by
exposing additional apis.
`set_rate_limit/2` expects a Ratelimit tuple module of
the form `{module, record}` where module implements
`check(NumBytes, RlTuple) -> {TimeToPause, NewRlTuple}`
It is recommended that the rate limit module also
implement `new` to allow creating new RateLimit records.
See `esockd_ratelimit` for a reference implementation.
> enhance emqttd_client ratelimit handling

- src/emqttd_protocol.erl
Client unsubscribe hook does not handle 'stop' value. 
Insert a statement to prevent calling emqttd_session:unsubscribe() if hook returns stop.
> Hook 'client.unsubscribe' need to handle 'stop'

- README.md
Updated README, changed broken url with correct one(there was a typo) for emq_modules plugin
> Fixed broken emq_modules plugin URL on README

- Makefile
- etc/emq.conf
- priv/emq.schema
- src/emqttd.app.src
- src/emqttd_client.erl
- src/emqttd_protocol.erl
- src/emqttd_ws.erl
- src/emqttd_ws_client.erl
- test/emqttd_SUITE.erl
1. Fixed test cases for emqttd_router_SUITE;
2. Compatible with esockd 4.x;
3. Shutdown the connection if an error occurred when sending data;
4. Add send_timeout, send_timeout_close options.
> Version 2.3.2

- src/emqttd_session.erl
The dup flag is not set when re-delivering the PUBLISH messages for QoS1 and QoS2
> fix #1562 dup flag not set when re-deliver

- src/emqttd_cli.erl
- src/emqttd_plugins.erl
CLI `users` should not be loaded in `emqttd_cli.erl`, we load it in emq-auth-username instead.
> fix emqttd_ctl crashed when emq_auth_usename doesn't exist

- src/emqx_client.erl
Would you mind adding a new field to incoming messages?
When a controlling process starts multiple clients that make multiple
subscriptions it may be desirable to identify from which client a
message is coming from. The topic id may not be sufficient.
> Send client_pid to distinguish multiple clients

- include/emqx.hrl
- src/emqx_banned.erl
- test/emqx_banned_SUITE.erl
Use `mnesia:foldl` to traverse mnesia rather than `mnesia:first` and
`mnesia:next`, as a badarg exception would occur if the record was
deleted while traversing the whole table.
> Update for banned API

- .gitignore
- Makefile
- test/emqx_ct_broker_helpers.erl
- test/emqx_listeners_SUITE.erl
- vars
Prior to this change, the template file etc/emqx.conf is used
directly in testing, as a result, mustache dir:s are created
In this change, Makefile steps are added to download bbmustach
and load the template input then replace with variableds defined
in 'vars' file, saved to etc/gen.emqx.conf for testing
> Generate a config file for testing

- src/emqx_protocol.erl
Prior to this change, it assume that topic_alias exists defaultly
which may cause the unexpected bug
This change fix this bug above
> Add pattern match for topic alias

- test/emqx_access_SUITE.erl
- test/emqx_listeners_SUITE.erl
Prior to this change, listeners test suites did not start cowboy which
is responsible for websocket connections. and access suites start
duplicated processes and these actions are wrong
This change fix the problem states above.
> fix listerners and access suites

- src/emqx_message.erl
- test/emqx_message_SUITE.erl
Prior to this change, emqx did not update message expiry interval and
there are duplicated functions to verify whether the message is expired.
This change delete the duplicated functions and add update action for
unexpired message.
> Update message expiry interval

- etc/emqx.conf
Hi
I experienced a problem when I was trying to load plugins via `emqx_ctl`. 
It clearly doesn't see my `etc/plugins/emqx_auth_pgsql.conf` file because in error logs I see default values not mine.
Adding space before `plugins.etc_dir` in emqx.conf helped immediately.
I have almost zero knowledge about erlang and cuttlefish library but it seems like this space is required. Feel free to reject if I am wrong
> Add space before plugins.etc_dir in emqx.conf

- Makefile
- priv/emqx.schema
- src/emqx_shared_sub.erl
- test/emqx_mock_client.erl
- test/emqx_session_SUITE.erl
- test/emqx_shared_sub_SUITE.erl
Fixes #1467 #1486 
'random' was already there before this change
Added three new strategies: 'sticky', 'round_robin', and 'hash'
'round_robin' is made default
and 'sticky' is the cheapest
> Add new shared subscription dispatch strategy

- src/emqx_shared_sub.erl
Prior to this change, if a producer session produces to two
or more shared subscriber groups, the previously picked subscriber
for sticky strategy may not be a valid member for the next group.
This fix is to key the picked subscriber pid with group ID.
> Shared subscriber should be keyed by group ID

- priv/emqx.schema
- src/emqx_connection.erl
- src/emqx_misc.erl
- src/emqx_session.erl
- test/emqx_misc_tests.erl
The `max_heap_size` process flag can be used to limit total heap size of a process, and it gives much more detailed crash log if the limit is hit.
> Change from customized total heap size check to set process flag

- src/emqx_packet.erl
Prior to this change, the validation for the mqtt5.0 publish packet
which both contains zero-length topic name and topic alias is wrong
This change fix this bug.
> Fix topic_name validation bug

- src/emqx_packet.erl
- src/emqx_protocol.erl
- src/emqx_session.erl
The Server delays publishing the Client’s Will Message until the Will Delay Interval has passed or the Session ends, whichever happens first. If a new Network Connection to this Session is made before the Will Delay Interval has passed, the Server MUST NOT send the Will Message.
> Improve will message

- src/emqx_client.erl
- test/emqx_client_SUITE.erl
Prior to this change emqx_client:request APIs need
to make several gen_statem calls in order to get the request/response
topic prefix stored in client state data.
This commit tries to:
1. make less gen_statem call to get topic prefix
2. move the gen_statem call to a separate call
so make the topic construction functions side-effect free
> Refine request & response topic prefix handeling

- etc/acl.conf
Prior to this change, the refered wiki link in acl.conf has been
deprecated.
Replace the deprecated link with the doc link in the official site.
> Fix the bad link to ACL doc

- src/emqx_protocol.erl
Prior to this change, there is no log for unauthorized subscribe, it is
difficult to debug the problem when subscription error occurred.
> Add warning logs for unauthorized  subscribe

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_protocol.erl
- test/emqx_protocol_tests.erl
Prior to this change, you can just use CN or EN field from the client
certificate as username.
This change add a new option to allow user to use Certificate directly as
username.
> Support use certificate as username

- etc/emqx.conf
The descriptions of ACL cache in emqx.conf should be updated.
> Fix config descriptions of ACL cache

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_bridge.erl
- src/emqx_client.erl
- src/emqx_client_sock.erl
- test/emqx_client_SUITE.erl
- Convert the retry-interval to milliseconds in schema.
- Sort the config options before pass them to `lists:ukeymerge/3`.
- Add an extra option to control if ssl is enabled.
- Before connecting to remote broker, using `ssl:cipher_suites(all, TlsVerion)` to fetch all the supported ciphers to include RSA key exchange ciphers. This is important if we're using the default RSA key in `etc/certs/`.
Prior to this change, emqx_client:start_link does 2 works in one call:
- init an erlang process for emqx_client
- send MQTT CONNECT to remote broker
But this solution have some drawbacks:
- the return value of `start_link` compiles the return values of the 2
works: {ok, Pid, MqttResult}. It is inconsistent with the return value
of `gen_statem:start_link`, may causes confusions.
- the return mode of …
> MQTT bridge via TLS

- src/emqx_mqtt_props.erl
There is no User-Property type but UTF8-String-Pair. At the moment it is impossible to publish message that includes User-Property for that reason.
> Fix type validation for User-Property

- include/logger.hrl
- priv/emqx.schema
- src/emqx_connection.erl
- src/emqx_logger.erl
- src/emqx_protocol.erl
- src/emqx_ws_connection.erl
Formatting variables and then passing them into the logger functions leads
to performance issues. i.e.
```erlang
logger:debug("RECV ~s", [emqx_packet:format(Packet)])
```
Above message will only be printed when the current log level set to
`debug`, but the function emqx_packet:format/1 will always be evaluated no
matter what the current log level is.
OTP 21 provides a special meta-data named `report_cb`, which can be used
for lazy evaluation. The fun is only evaluated if the primary/handler log level
check passes, and is therefore recommended if it is expensive to generate
the message.
> Lazy evaluation when logging messages

- etc/emqx.conf
- include/emqx.hrl
- priv/emqx.schema
- src/emqx_packet.erl
- src/emqx_session.erl
- src/emqx_shared_sub.erl
- src/emqx_sm.erl
- test/emqx_broker_SUITE.erl
- test/emqx_mock_client.erl
- test/emqx_session_SUITE.erl
- test/emqx_shared_sub_SUITE.erl
For QoS0 messages, no acking
For QoS1/2 messages, 'ACK' if any:
- ACK when QoS is downgraded to 0
- Message is sent to connection process
'NACK' if any:
- There is no alive connection process for the receiving session
- Message queue is full and the receiving session starts to drop old messages
- The receiving session crash
Upon 'NACK', messages are dispatched to the 'next' subscriber in the group,
depending on the shared subscription dispatch strategy.
> Add acking mechamism for shared dispatch

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_protocol.erl
- test/emqx_protocol_SUITE.erl
https://github.com/emqx/emqx/issues/1737
> Use username replace id(issue#1737)

- Makefile
Prior to this change, this project support to be built with rebar3 and
erlang.mk meanwhile but when we want to make distclean, this project
would execute rebar-clean which would get dependencies via rebar3, it
slow down the procedure of distclean.
> Do no execute rebar-clean before distclean

- priv/emqx.schema
The simple logger handler is not removed if we set the `log.to=file` in
emqx.conf.
```
{18-11-28 20:18}EMQ:~/code/emqx30/_rel/emqx@emqx30✗✗✗✗✗✗ emqer%
➜  ./bin/emqx_ctl log handlers list
LogHandler(id=file, level=error, destination=log/emqx.log)
LogHandler(id=simple, level=all, destination=unknown)
```
This might be an issue of OTP logger:
https://bugs.erlang.org/browse/ERL-788
I set the error_logger to silent as a workaround.
> Remove simple log handler at startup

- Makefile
- etc/emqx.conf
- etc/vm.args.cloud
- etc/vm.args.edge
- priv/emqx.schema
- rebar.config
I added a new vm.args file in PR https://github.com/emqx/emqx-rel/pull/280.
The vm configs in emqx.conf will be merged into that vm.args at emqx startup.
> Move extra vm args to file vm.args

- test/emqx_client_SUITE.erl
- test/emqx_cm_SUITE.erl
- test/emqx_sm_SUITE.erl
Prior to this change, the test case in sm and cm is messed and difficult to maintain.
This change fix this problem.
> Standardize the test case sm and cm

- etc/vm.args.edge
> Add +L vm args for reducing some memory

- src/emqx_logger.erl
for turtle and Gilbert-wong :-)
1> emqx_logger:set_overall_log_level(debug).
ok
> Logger level in one command

- priv/emqx.schema
This PR removes lager handlers and the `crash.log`, in case of some dependencies or plugins of emqx use lager.
> Disable lager

- src/emqx_protocol.erl
- src/emqx_session.erl
- test/emqx_connection_SUITE.erl
- test/emqx_protocol_SUITE.erl
- test/emqx_ws_connection_SUITE.erl
Solve the problem that EMQ still sends will message when the client sends DISCONNECT packet with reason code 0
> Fix will msg

- src/emqx_protocol.erl
Prior to this change, if the acl check of will topic failed, it would
return unspecifed error code.
This change change the reason code to not authorized code.
> Change the reason code in will topic acl check

- src/emqx_session.erl
- src/emqx_shared_sub.erl
- test/emqx_shared_sub_SUITE.erl
Fixes #2143 
Before this change, when shared dispatch ack is enabled (in config)
in case all subscribers are offline (all sessions gave negative ack)
the message is simply discarded.
In this change, it is ensured to have one session picked according to
configured dispatch strategy when no subscriber is online.
The messages dispatched in such scenario are then queued in session state.
> Improve shared sub dispatch implementation.

- src/emqx_sys.erl
Fix broker.sys_interval not working. Use `broker_sys_interval` instead of `sys_interval`
Change code:
`application:get_env(?APP, broker_sys_interval, 60000).`
> Fix broker.sys_interval not working

- test/emqx_alarm_handler_SUITE.erl
Prior to this change, emqx_alarm_handler_SUITE read emqx.conf rather
gen.emqx.conf which would trigger unexpected errors
This change fix this issue.
> Fix emqx_alarm_handler_SUITE

- etc/emqx.conf
- include/emqx_client.hrl
- priv/emqx.schema
- rebar.config
- src/emqx_client.erl
- src/emqx_protocol.erl
- test/emqx_client_SUITE.erl
- test/emqx_protocol_SUITE.erl
- test/emqx_request_handler.erl
- test/emqx_request_response_SUITE.erl
- test/emqx_request_sender.erl
The implementation before this PR is overly Intrusive for emqx_client module, 
because request-response is a client-to-client protocol,
also, emqx_client isn't a end-user client (but just a bridging tool).
Request-response for broker: the only thing that requires support is the
'Response-Information' message property field in CONNACK,
the field is optional according to spec, (and can be disregarded by clients if I understand correctly).
I have put a comment in where 'Response-Information' should go
in case we want to add it back in the future.
> Move request response out of emqx client

- src/emqx.erl
- src/emqx_alarm_handler.erl
- src/emqx_app.erl
emqx_alarm_handler publishes mqtt messages,
having it running while plugins are shutdown triggered some
annoying crashes
> Unload emqx_alarm_handler before unloading plugins when shuting down

- src/emqx_broker.erl
- src/emqx_rpc.erl
https://github.com/emqx/emqx/issues/2290
There are two reasons for `gen_rpc:call() `'s failure, One is `bad_rpc`,and  `bad_tcp`, So add `bad_tcp` clause to handle `gen_rpc:call()`
```erlang
filter_result(Delivery) ->
case Delivery of 
{badrpc, Reason} -> {badrpc, Reason};
{badtcp, Reason} -> {badrpc, Reason};
Delivery1        -> Delivery1
end.
```
> Add badtcp clause to handle gen_rpc

- src/emqx_connection.erl
- test/emqx_protocol_SUITE.erl
To fix #2303 
It will report the following error, when a connection sends a TCP frame contained many of MQTT packet and followed a split MQTT packet.
```
(emqx@127.0.0.1)1> 2019-03-19 15:04:07.929 [error] someclientid@127.0.0.1:54311 Parse failed for function_clause
Stacktrace:[{emqx_frame,parse_utf8_string,
[<<48,48,48,48,95,49,52,48,111,0,9,107,97,108,97,47,
107,97,108,97,48,48,48,48,48,48,48,48,48,48,48,48,
48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48>>],
[{file,"src/emqx_frame.erl"},{line,354}]},
{emqx_frame,parse_packet,3,
[{file,"src/emqx_frame.erl"},{line,163}]},
{emqx_frame,parse_frame,4,
[{file,"src/emqx_frame.erl"},{line,104}]},
{emqx_connection,process_incoming,3,
[{file,"src/emqx_connection.erl"},{line,371}]},
{gen_statem,call_state_function,5, …
```
> Fix followed packet parse failure

- src/emqx_mod_acl_internal.erl
Fix badmatch for `reload_acl()`, The return value of `load_rules_form_file` is maps not `ok`
``` erlang
_ ->
emqx_logger:info("Reload acl_file ~s successfully", [acl_file()]),
ok;
```
> Fix badmatch bug for reload_acl

- src/emqx_os_mon.erl
- src/emqx_vm_mon.erl
Broker can set cpu and process alarm repeatedly, but only clear the alarm if it has already been set.
> Fix alarm report bug

- src/emqx_session.erl
To fix #2336, `badmatch` crashing error will take place at:
```erlang
%% emqx_session.erl#L895
batch_process(Msgs, State) ->
{ok, Publishes, NState} = process_msgs(Msgs, [], State),
%% true will be returned when gen_rpc:cast called
ok = batch_deliver(Publishes, NState),          
maybe_gc(msg_cnt(Msgs), NState).
```
>  Fix badmatch error in the batch_process of session

- src/emqx_access_control.erl
- src/emqx_acl_cache.erl
- src/emqx_mod_acl_internal.erl
The original `reload_acl` function only parse the ACL file, not compile and rehook to 'client.check_acl'
> Fix reload ACL failed

- src/emqx_access_control.erl
EMQ should allow the anonymous connection if the allow_anonymous option is true, although it has one or more auth plugins started.
> Fix allow_anonymous behavoir error

- Makefile
- etc/emqx.conf
- priv/emqx.schema
- rebar.config
- src/emqx_ws_connection.erl
Prior to this change, emqx_ws_connection does not support compress websocket message. This change implement this feature.
> Support to pass ws compressing options

- src/emqx_message.erl
- test/emqx_bridge_SUITE.erl
`bin_key_map/1` is not necessary and has to be removed from this module.
> Remove bin_key_map/1

- src/emqx_mqueue.erl
- src/emqx_session.erl
Prior to this change, when store_qos0 option is set to false, the hook
`message.dropped` would not be triggered. It is wrong design and when
the ignore_loop is enabled or nl is set to 1, the hook
`message.dropped` also would not be triggered.
> Fix message dropped

- src/emqx_client.erl
Prior to this change, the arguments passed to gen_statem:reply is bad
args, first arg should be a tuple, but it is a pid. So it would
trigger crash.
This change fix this bug.
> Fix gen_statem:reply/2 bug in emqx_client module

- src/emqx_bridge.erl
The status api can be called via bridge id, not only bridge pid.
> Extend status api of emqx_bridge

- .gitignore
- Makefile
- rebar.config
- test/emqx_listeners_SUITE.erl
- vars
Starting from ct-helpers v1.1, config file template is rendered in init suite steps.
So now we can stop rendering template before `make ct`
> Pin emqx-ct-helpers v1.1

- etc/emqx.conf
Set default max-queue-len to 10000, and default max-heap-size to 1024MB.
> Enable force_shutdown_policy by default #2494

- etc/emqx.conf
- priv/emqx.schema
The default chars_limit 1024 is not large enough for crash logs. Change it to 8192.
@johnfwhitmore
> Enlarge chars_limit to 8192

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_ws_connection.erl
The erlang:process_flag(max_heap_size, MaxHeapSize) can only set a MaxHeapSize of `small integer`, which is smaller than 2^59 on 64-bit systems, and 2^27 on 32-bit systems.
> Force shutdown

- etc/emqx.conf
According to the [Token Bucket](https://en.wikipedia.org/wiki/Token_bucket) algorithm, the process will be paused if the requested Tokens large than the burst or remaining tokens.
if we set the burst value to 4096 by default, this process will always be blocked.
So, the reasonable default value should be `(max_packet_size * active_n) / 2`
Unfortunately, the `ws/wss` don't implement the `rate_limit` mechanism. so the `listener.ws.external.rate_limit` is not work now.
> Enlarger burst value of rate_limit

- src/emqx_access_control.erl
- src/emqx_types.erl
Revert the #2355.
The `emqx_access_control` module can pass all authentication credentials to 'Authentication chain'
- The `emqx_access_control` don't care whether the username/password in the credential is empty
- Each auth plugin should return `{ok, Credentials#{anonymous => false,  auth_result => success}` after authenticating successfully
> Revert the PR #2355

- rebar.config
- test/emqx_shared_sub_SUITE.erl
in case compiled in emqx-rel test profile, erl_opts is not respected
> Delete APPLICATION macro from erl-opts in rebar.config

- src/emqx_app.erl
Fix the following issue when stopping the erlang vm.
```
2019-05-28 16:51:09.687 [error] [Broker] Publish error: badarg
{message,<<0,5,137,238,196,39,86,239,244,67,0,0,5,182,0,0>>,
0,emqx_alarm_handler,
#{dup => false,sys => true},
#{'Content-Type' => <<"application/json">>},
<<"$SYS/brokers/emqx@127.0.0.1/alarms/system_memory_high_watermark/clear">>,
<<>>,
{1559,33469,687553}}
[{ets,lookup,[emqx_hooks,'message.publish'],[]},
{emqx_hooks,lookup,1,
[{file,"/Users/emqer/code/emqx-enterprise-rel/_build/emqx/lib/emqx_backend_mongo/_build/default/lib/emqx/src/emqx_hooks.erl"}
```
> Stop alarm before emqx stops

- src/emqx_ws_connection.erl
Prior to this change, websocket connection would be closed directly
without sending connack packet when acl check fails.
This change fix this bug.
> Fix websocket bug.

- etc/emqx.conf
- priv/emqx.schema
Some times the crash logs is too long to print it out, if the chars_limit defaults to 8192:
```
** Reason for termination == 
** ...
```
> No chars limit by default

- Makefile
- include/emqx_mqtt.hrl
- src/emqx_channel.erl
- src/emqx_client.erl
- src/emqx_frame.erl
- src/emqx_listeners.erl
- src/emqx_protocol.erl
- src/emqx_session.erl
- src/emqx_ws_channel.erl
- test/emqx_SUITE.erl
- test/emqx_alarm_handler_SUITE.erl
- test/emqx_channel_SUITE.erl
- test/emqx_frame_SUITE.erl
- test/emqx_protocol_SUITE.erl
- test/emqx_ws_channel_SUITE.erl
- Rename the `emqx_connection` module to `emqx_channel`
- Rename the `emqx_wx_connecton` module to `emqx_ws_channel`
- Improve the `emqx_frame:parse/2` function to return the new parse state
> Improve the emqx_connection, emqx_ws_connection and emqx_frame modules

- src/emqx_ws_channel.erl
- test/emqx_ws_channel_SUITE.erl
Prior to this change, the websocket connection would not be disconnected
when the dataframe type is the other frame type. However, in the mqtt spec, it
should be disconnected.
Here is the [mqtt 5.0 spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901285)
This change fixes this inconsistent behavior with the mqtt 5.0 spec
> Fix issue#2619

- Makefile
Prior to this change, if user's computer has no `~/.config/rebar3`
path, `make run` would fail and report enoent error.
This change fix the problem I described above.
> Fix enoent error in run_setup rule of the makefile

- src/emqx_session.erl
```erlang
handle_dispatch(Msgs, State = #state{inflight = Inflight,            % [1, 2, 3]
client_id = ClientId,
username = Username,
subscriptions = SubMap}) ->
SessProps = #{client_id => ClientId, username => Username},
%% Drain the mailbox and batch deliver
Msgs1 = drain_m(batch_n(Inflight), Msgs),                        % [3, 2, 1, 4, 5, 6]
%% Ack the messages for shared subscription
Msgs2 = maybe_ack_shared(Msgs1, State),
%% Process suboptions
Msgs3 = lists:foldr(
fun({Topic, Msg}, Acc) ->
SubOpts = find_subopts(Topic, SubMap),
case process_subopts(SubOpts, Msg, State) of
{ok, Msg1} -> [Msg1|Acc];
ignore ->
emqx_hooks:run('message.dropped', [SessProps, Msg]),
Acc
end
end, [], Msgs2),
NState = batch_process(Msgs3, State),
noreply(ensure_stats_timer(NState)).
drain_m(Cnt, Msgs) when …
```
> Fix the massages order when batch dispatching

- README.md
The location of built folder of emqx is `_build/emqx/rel/emqx` in the current version, updated the **readme** to reflect the same.
> updated the location of built emqx

- src/emqx_kernel_sup.erl
- src/emqx_tracer.erl
- test/emqx_tracer_SUITE.erl
Remove the emqx_tracer process as the trace-handlers stored in state would be lost in case of crash.
> Make emqx_tracer more reliable

- include/logger.hrl
- src/emqx_tracer.erl
Add mfa to the meta data to support the Erlang Logger's per module / per app filtering
For more details, see the note here:
http://erlang.org/doc/man/logger.html#set_module_level-2
> Add support for logger per module filtering

- src/emqx_banned.erl
- src/emqx_channel.erl
- src/emqx_flapping.erl
- src/emqx_zone.erl
- Remove the 'is_enabled/1' function of 'emqx_banned' module
- Remove the 'is_enabled/1' function of 'emqx_flapping' module
- Add 'enable_acl/1', 'enable_banned/1' and 'enable_flapping_detect/1'
> Fix the test cases for emqx_banned, emqx_flapping modules

- src/emqx_channel.erl
- src/emqx_connection.erl
- src/emqx_metrics.erl
- src/emqx_mqtt_props.erl
- src/emqx_packet.erl
- src/emqx_protocol.erl
- src/emqx_ws_connection.erl
- test/emqx_channel_SUITE.erl
- test/emqx_packet_SUITE.erl
- test/emqx_protocol_SUITE.erl
Fix invalid QoS and protocol name, fix handling for Topic-Alias-Maximum and Maximum-Packet-Size, and send DISCONNECT Packet to client when the session is taken over.
> Fix handling for MQTT spec

- src/emqx_channel.erl
- src/emqx_connection.erl
- src/emqx_message.erl
- src/emqx_misc.erl
- src/emqx_packet.erl
- src/emqx_ws_connection.erl
- src/emqx_zone.erl
- test/emqx_message_SUITE.erl
- test/emqx_packet_SUITE.erl
Rewrite the `emqx_packet` module and improve the modules:
- emqx_zone: Add use_username_as_clientid/1 function
- emqx_misc: Improve function 'pipeline/3'
- emqx_message: Add 'to_packet/2' function
- emqx_connection: Rename the info key 'connection' to 'conninfo'
> Rewrite the emqx_packet module and improve channel pipeline

- src/emqx_broker.erl
- src/emqx_channel.erl
- src/emqx_message.erl
- src/emqx_types.erl
- test/emqx_channel_SUITE.erl
- test/emqx_message_SUITE.erl
- test/emqx_mqtt_caps_SUITE.erl
- test/emqx_packet_SUITE.erl
- test/emqx_session_SUITE.erl
- test/emqx_shared_sub_SUITE.erl
- Add 'emqx_message:clean_dup/1' function
- Clean dup flag before publishing a message
- Add more test cases for emqx_message module
> Improve the emqx_message module and add more test cases

- src/emqx_access_control.erl
- src/emqx_broker.erl
- src/emqx_channel.erl
- src/emqx_connection.erl
- src/emqx_message.erl
- src/emqx_metrics.erl
- src/emqx_mqueue.erl
- src/emqx_session.erl
- src/emqx_ws_connection.erl
- test/emqx_channel_SUITE.erl
- test/emqx_message_SUITE.erl
- test/emqx_mqueue_SUITE.erl
- test/emqx_session_SUITE.erl
- messages.dropped.expired
- messages.dropped.no_subscribers
- messages.forward
- messages.delayed
- delivery.dropped
- delivery.dropped.no_local
- delivery.dropped.too_large
- delivery.dropped.qos0_msg
- delivery.dropped.queue_full
- delivery.dropped.expired
- client.connected
- client.authenticate
- client.auth.anonymous
- client.check_acl
- client.subscribe
- client.unsubscribe
- client.disconnected
- session.created
- session.resumed
- session.takeovered
- session.discarded
- session.terminated
- channel.gc
- messages.qos2.expired
- messages.qos2.dropped
- auth.mqtt.anonymous
> Add more metrics and improve the 'channel', 'session' modules

- src/emqx_access_control.erl
- src/emqx_broker.erl
- src/emqx_channel.erl
- src/emqx_cm.erl
- src/emqx_mod_presence.erl
- src/emqx_mod_subscription.erl
- src/emqx_session.erl
- test/emqx_connection_SUITE.erl
- test/emqx_session_SUITE.erl
- client.connect: MQTT CONNECT Packet Received
- client.connack: MQTT CONNACK Packet Sent
- client.connected: The MQTT Client is connected
- client.disconnected: The MQTT Client is disconnected
- client.authenticate: Authenticate the MQTT Client
- client.check_acl: Check Pub/Sub ACL
- client.subscribe: MQTT SUBSCRIBE Packet Received
- client.unsubscribe: MQTT UNSUBSCRIBE Packet Received
session.created: A new session is created
session.subscribed: After session subscribed a topic
session.unsubscribed: After session unsubscribed a topic
session.resumed: A session is resumed
session.takeovered: A session is takeovered
session.discarded: A session is discarded
session.terminated:  A session is terminated
message.publish:  A message is published
message.delivered: A message is delivered …
> Breaking Change: Add new hooks for client and session lifecircle

- etc/emqx.conf
- priv/emqx.schema
32 is too many for the default number of rpc connections. The number of TCP connections would grow too high when the node-number increases. And also the CPU usages would go high because of lots of rpc client process.
Change it to number-of-schedulers / 2.
> Reduce default tcp client nums to schedulers/2

- src/emqx_global_gc.erl
- test/mqtt_protocol_v5_SUITE.erl
According to erlang docs:
```
{type, 'major' | 'minor'}
Triggers garbage collection of requested type. Default value is 'major', 
which would trigger a fullsweep GC. The option 'minor' is considered
a hint and may lead to either minor or major GC run.
```
The `major` mode is better than `minor` for a lots of `SSL Connection`
> Change global_gc to major mode

- rebar.config
esockd: avoid the `ssl_close_timeout` send to channel
> chore(deps): upgrade esockd to 5.6.2

- include/emqx.hrl
- include/emqx_mqtt.hrl
- src/emqx_alarm_handler.erl
- src/emqx_channel.erl
- src/emqx_frame.erl
- src/emqx_message.erl
- src/emqx_packet.erl
- src/emqx_session.erl
- src/emqx_types.erl
- test/emqx_channel_SUITE.erl
- test/emqx_frame_SUITE.erl
- test/emqx_listeners_SUITE.erl
- test/emqx_message_SUITE.erl
- test/emqx_packet_SUITE.erl
- test/emqx_session_SUITE.erl
- test/emqx_ws_connection_SUITE.erl
1. Add MQTT5.0 properties when invoking the hooks.
- Add a new key `properties` into the message header:
We used to put all of the properties into the `#message.headers`:
```erlang
#message{headers = #{'User-Property' => {<<"reason">>,<<"normal">>},
'Message-Expiry-Interval' => 60,
allow_publish => true}
```
I put them instead under a single key:
```erlang
#message{headers = #{properties =>
#{'User-Property' => {<<"reason">>,<<"normal">>},
'Message-Expiry-Interval' => 60},
allow_publish => true}
```
Note that the column `properties` may contain all the properties for
Publish and Will messages.
- Add `disconn_props` into the `Channel.conninfo`
- Add `puback_props` also into the message header:
```erlang
#message{headers = #{puback_props =>
#{'User-Property' => {<<"reason">>,<<"normal">>}}, …
```
> feature(properties): add properties in message header

- src/emqx_json.erl
- test/props/prop_emqx_json.erl
In the previous implementation, the `emqx_json` module will cover the duplicated key's value, and disturb the order of the keys. E.g: 
```erlang
> emqx_json:encode([{a, 1}, {a,2}, {b, 3}]).
<<"{\"b\":3,\"a\":2}">>
```
This commit tries to fix it to get the correct result, E.g:
```erlang
<<"{\"a\":1,\"a\":2,\"b\":3}">>
```
> fix(json): convert a proplists to ejson instead of map

- src/emqx.appup.src
- src/emqx_channel.erl
- test/emqx_channel_SUITE.erl
In the emqx_types.erl, we defined the ws_cookie attribute for the ws client, but didn't set it:
https://github.com/emqx/emqx/blob/fa31062a5ed673ddbd0ffcdd4b829c3dba2a911d/src/emqx_types.erl#L138
see: https://github.com/emqx/emqx/issues/3747#issuecomment-702268570
> fix(ws): take ws_cookie to clientinfo

- rebar.config
- src/emqx.appup.src
- src/emqx_json.erl
- test/emqx_json_SUITE.erl
In the previous version (v4.0 - v4.2.1), there is an ambiguity here, and it is not possible to distinguish between empty objects and arrays:
``` erlang
1> emqx_json:decode("{\"k\": {}}").
[{<<"k">>,[]}]
2> emqx_json:decode("{\"k\": []}").
[{<<"k">>,[]}]
```
After this fix:
``` erlang
1> emqx_json:decode("{\"k\": {}}").
[{<<"k">>,[{}]}]
```
> fix(json): fix decoding/encoding empty object error

- src/emqx.appup.src
- src/emqx_metrics.erl
**Motivation:**
In some scenarios, we find that the metrics `messages.dropped` is much larger than `messages.received`.
Therefore, we should count messages received at other locations as well.
**Related PR:** 
https://github.com/emqx/emqx-rule-engine/pull/193
https://github.com/emqx/emqx-management/pull/284
> feat(emqx_metrics): add new functions to count message received

- rebar.config
- rebar.config.erl
Since plugins are compile as default profile, the parse_transform
provided by relup_helper may not present when compiling other plugins
> chore(build): mod_vsn parse_transform is not for default profile

- README.md
Rebar3 version 3.14.3-emqx-4 fixed an issue where apps dir
is full-copy to _buid/test/lib/emqx/apps when running
ct with --dir apps/xxx or --suite apps/xxx/test/yyy_SUITE
This behaviour is confusing because there could be multpile
beam files for the same module in the same profile.
e.g.
_build/test/lib/xxx/test/yyy_SUITE
_build/test/lib/emqx/apps/xxx/test/yyy_SUITE
> chore(build): upgrade rebar3 to fix ct

- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_rule_engine/src/emqx_rule_utils.erl
- apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl
- Make client format function durable. In the previous codes, It will be crashed on maps:get/2 if some client info do not have the session field.
- Support to conveniently handle the SQL values string
> Refactor some functions

- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/templates/service.yaml
- deploy/charts/emqx/values.yaml
- The https port is disabled by default
- When setting the **emqxConfig.EMQX_DASHBOARD__LISTENER__HTTPS** value, the https listener is initialized and enabled in the statefulset
- When configuring the value **service.dashboardtls** is enabled in the service
PR moved from: https://github.com/emqx/emqx-rel/pull/630
> feat(helm_chart): TLS support for dashboard

- apps/emqx_auth_http/etc/emqx_auth_http.conf
- apps/emqx_auth_http/src/emqx_auth_http_cli.erl
- apps/emqx_auth_http/test/emqx_auth_http_SUITE.erl
- src/emqx_types.erl
This PR is taken from https://github.com/emqx/emqx-auth-http/pull/225
Sorry, @gerad I can't leave your commits to this PR since we merged the code repositories together in v4.3.0, it's two code repositories.
> feat(auth_http): support for getting websocket cookies

- apps/emqx_exhook/rebar.config
- apps/emqx_exproto/README.md
- apps/emqx_exproto/docs/design-cn.md
- apps/emqx_exproto/priv/protos/exproto.proto
- apps/emqx_exproto/rebar.config
- apps/emqx_exproto/src/emqx_exproto_channel.erl
- apps/emqx_exproto/src/emqx_exproto_gcli.erl
- apps/emqx_exproto/src/emqx_exproto_gsvr.erl
- apps/emqx_exproto/test/emqx_exproto_SUITE.erl
- apps/emqx_exproto/test/emqx_exproto_echo_svr.erl
- Use the gRPC client streaming APIs to improve the
ConnectionHandler server performance.
- Change the 'conn' field type to term binary
> feat(exproto): use client streaming APIs for handler

- rebar.config
Before ekka 0.7.6, when epmd is not used, ekka_dist would calculate
a port number from node name. This does not work for remote consoles
because a remsh node name is like remsh81random0-<target-node>
i.e. the calculated port number is always the same
as the target node.
The fix in 0.7.6 allows remsh prefixed nodes to use a range of ports
to listen.
> fix(ekka): Upgrade to 0.7.6 to allow remsh

- rebar.config
Before ekka 0.8.0, when epmd is not used, ekka_dist would calculate
a port number from node name. This does not work for remote consoles
because a remsh node name is like remsh81random0-<target-node>
i.e. the calculated port number is always the same as the target node.
The fix in 0.8.0 allows remsh prefixed nodes to use a range of
ports to listen.
> fix(ekka): Upgrade to 0.8.0 to allow remsh

- rebar.config
To better support hot upgrades, in esockd 5.8.0 we
avoid saving anonymous functions in state.
> perf(esockd): upgrade esockd to 5.8.0

- apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl
- rebar.config
- rebar.config.erl
- src/emqx_alarm.erl
Usually, we can't detect some unused variables, functions, and type declarations in time for review, so we should set the `wanrings_as_errors` compiler option to help us.
This is also a way to improve the quality of our code
> chore(style): set warnings_as_errors compile option

- .ci/build_packages/tests.sh
- .ci/fvt_tests/docker-compose.yaml
- bin/emqx
- bin/emqx_ctl
- deploy/packages/rpm/init.script
with this change, the system monitoring tools such as `ps`, `top` and `netstat`
will display the node name instead of `beam.smp` as process name in the outputs.
e.g.
```
ps -ef | grep -E '\-progname\s.*emqx\s'
zaiming+   25832    4652  0 14:16 pts/5    00:00:08 emqx -P 2097152 -Q 1048576 -e 256000 -spp true -A 4 -IOt 4 -SDio 8 -- -root ................
```
and
```
01-28 14:05:09 ~> netstat -lnpt | grep emqx
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      25832/emqx
tcp        0      0 0.0.0.0:4370            0.0.0.0:*               LISTEN      25832/emqx
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      25832/emqx
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      25832/emqx
tcp        0      0 …
```
> chore(boot): change beam.smp to node name

- .ci/apps_tests/docker-compose.yaml
- .github/workflows/run_test_cases.yaml
- Makefile
- apps/emqx_web_hook/test/props/prop_webhook_hooks.erl
- rebar.config
- rebar.config.erl
1. Use `emqx/coveralls-erl ` to send coverage information to coveralls.io. and use `rebar.config.erl:coveralls/0` to add its necessary configuration to it.
2. In order to get the necessary compilation information, we cannot set deterministic to all applications under `apps/*`
3. In Addition, this PR also adds proptest to the makefile so that subsequent versions can add it to the CI.
> chore(cover): add coverall back

- rebar.config
cowboy prints a large number of extraneous logs when load-balance continually invokes health checks to emqx.
Related PR: https://github.com/emqx/cowboy/pull/5
> chore(deps): upgrade cowboy to 2.8.2

- lib-opensource/emqx_management/src/emqx_mgmt.erl
- lib-opensource/emqx_management/src/emqx_mgmt_api_clients.erl
Since the formatting function emqx_mgmt:item/2 is executed separately after the completion of the query list.
So, when the formatting is executed, and the client is already offline, it will crash here.
see: https://github.com/emqx/emqx/issues/3868
> fix(mgmt): fix client formating crash

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_channel.erl
pem is base64 encoded instead of binary crt
md5 is md5 hash of crt
peer_cert_as_clientid is like peer_cert_as_username
existing `peer_cert_as_username` options are unaffected
peer_cert_as_username=crt breaks exhook proto utf8 parsing of username
crt cannot be used in a topic name due to being invalid utf8
pem cannot be used in a topic name due to having slashes
peer_cert_as_clientid = md5 allows to e.g. subscribe to "t/%c" with ACL
My actual use case involves both …
> feat(peer_cert_as_clientid): peer_cert_as_clientid = cn | dn | crt | pem | md5

- apps/emqx_coap/src/emqx_coap_server.erl
- apps/emqx_exproto/src/emqx_exproto.erl
- apps/emqx_lwm2m/src/emqx_lwm2m_coap_server.erl
- apps/emqx_sn/src/emqx_sn_app.erl
- apps/emqx_stomp/src/emqx_stomp.erl
- bin/nodetool
- lib-opensource/emqx_management/src/emqx_mgmt.erl
- lib-opensource/emqx_management/src/emqx_mgmt_cli.erl
- lib-opensource/emqx_management/test/emqx_mgmt_SUITE.erl
- priv/emqx.schema
- rebar.config.erl
- src/emqx_listeners.erl
Listeners are internally identifiered by the listen-on tuple
which is not UI friendly when we have to find a listener by this
'signature'.
The listeners are actually named in configs, but the names are
discarded in the parsing functions.
In this PR, the configured names are kept and passed to emqx
internal for more user-friendly lookups.
The `emqx_ctl listeners` print out has been refactored to
display the identifier in format `<Protocol>[:<Transport>]:<Name>`.
e.g. `http:management` and `mqtt:tcp:internal`.
And the `emqx_ctl listeners stop` interface has been updated to
use the identifier as input.
For users, this PR only changes mqtt listeners' print-out …
> feat(listeners): Add identifier to listeners

- lib-opensource/emqx_management/src/emqx_mgmt.erl
- lib-opensource/emqx_management/src/emqx_mgmt_api_listeners.erl
- lib-opensource/emqx_management/src/emqx_mgmt_cli.erl
- lib-opensource/emqx_management/test/emqx_mgmt_SUITE.erl
- src/emqx_listeners.erl
example:
```
emqx_ctl listener restart mqtt:ssl:external
```
or
```
PUT /api/v4/listeners/mqtt:ssl:external/restart
```
thank you @zmstone for providing the listener-identifier apis :)
originally coming from here: https://github.com/emqx/emqx-management/pull/307
Fixes #4013 
existing `emqx_ctl listeners ...` commands are unaffected, as is `/api/v4/listeners`.
When listener is restarted, `clientsca` and other cert files' caches are invalidated, allows for "loading" new certs. See #4013
> feature(mgmt) restart a listener

- apps/emqx_rule_engine/include/rule_engine.hrl
- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/src/emqx_rule_registry.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
https://github.com/emqx/emqx/issues/4143
HexStrings
Converting a Secret from HexString to Binary:
```
SELECT
hexstr2bin('31323334353637383930313233343536') as secret,
schema_decode('foo', 'encrypted-text', secret)
```
Term Encode/Decode
Encoding an Erlang term to binary so that it can be sent to next rule:
```
SELECT
term_encode(payload) as encoded_payload
```
Above is necessary because the payload might be converted to a JSON string before sending to the next rule or another MQTT broker, and all the binary values are converted to UTF-8 encoded strings, which is probably not what we want...
And in another rule we can decode it before processing it:
```
SELECT
term_decode(payload) as decoded_payload
```
Key-Value Stores
To save and then read a state in the current session (conn process) …
> feat(rule): add more sql functions

- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
Migrate code from enterprise emqx-rule-engine, the code of branch `enterprise-dev/e4.3.0` is copied from https://github.com/emqx/emqx-rule-engine/tree/copy-dev/e4.3.0.
Also see https://github.com/emqx/emqx-rule-engine/pull/237.
> chore(rule): migrate rule-engine from enterprise version

- apps/emqx_telemetry/src/emqx_telemetry.erl
- apps/emqx_telemetry/test/emqx_telemetry_SUITE.erl
Now only the data telemetry function will be enabled in the official version
> fix(telemtry): report only in official version

- apps/emqx_coap/rebar.config
The 0.3.2 fixes some redundant log printing in a DTLS
connection
> chore(coap): upgrade gen_coap to v0.3.2

- apps/emqx_management/src/emqx_mgmt.erl
Currently, the `{topic, Topic}` pattern is not used for management.
Moreover it will casue a `function_caluse` while the previous caluse not
matched
> fix(mgmt): remove the useless match

- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_actions.erl
We have several reasons to remove this feature:
1. The design does not make sense. A rule engine resource should
not have an impact on the system's messages directly after it is created.
This mqtt_sub actually conflicts with any design concept of the rules engine.
2. The implementation is incorrect. mqtt_sub uses a client pool to establish
a subscription relationship to an MQTT Broker. This causes a message to be
sent repeatedly to EMQ X. Unless a shared subscription is used,
or a Pool Size of 1 is configured.
3. The emqx-bridge-mqtt supports all the features of mqtt_sub.
This feature introduced by https://github.com/emqx/emqx-bridge-mqtt/pull/78.
And it released to v4.2.0 (NOT WORK), v4.2.1-v4.2.7 (FIXED)
Incompatibility
> revert(bride-mqtt): remove the mqtt_sub resource

- bin/emqx
Fixes two issues
1. when start in daemon mode (`start` command), it recursively uses the `console` command, added a flag to by pass the overrride
2. Do not override user provided `MEQX_LOG__TO`
> fix(config): use config value default log.to for daemon mode

- apps/emqx_auth_mnesia/test/emqx_acl_mnesia_SUITE.erl
- apps/emqx_coap/src/emqx_coap_ps_resource.erl
- src/emqx_http_lib.erl
- test/emqx_http_lib_tests.erl
So far the lib has only `uri_encode` and `uri_decode` APIs
The code is copied from http_uri.erl (in OTP's inets app) which has been deprecated since OTP-23
The recommended replacement `uri_string` function is not quite equivalent
and not backward compatible.
> refactor(http-lib): Add emqx_http_lib

- rebar.config.erl
It causes macro redefine error for plugin compilation.
> chore(compile): do not pass down EMQX_ENTERPRISE macro to deps

- apps/emqx_auth_http/src/emqx_auth_http_app.erl
- apps/emqx_rule_engine/src/emqx_rule_utils.erl
- apps/emqx_web_hook/src/emqx_web_hook_actions.erl
- apps/emqx_web_hook/src/emqx_web_hook_app.erl
- src/emqx_http_lib.erl
- test/emqx_http_lib_tests.erl
This abstraction is need for enterprise to compile because we still have code calling the deprecated (by OTP) http_url module there.
And there was a bug in the old code.
in `uri_string:uri_map()`, the port field might be missing, and it could be `undefined` too
we have code to handle the 'missing' but not `undefined`.
> Refactor http lib add uri parse

- src/emqx_message.erl
- test/emqx_message_SUITE.erl
Allow extra plugins to play with message without importing `emqx.hrl`.
Example:
```
on_message_publish(Message, _Env) ->
MMessage = emqx_message:to_map(Message),
case maps:get(topic, MMessage) of
<<"$SYS/", _/binary>> ->
{ok, Message};
_ ->
NewMessage = emqx_message:to_message(MMessage#{from => <<"overwritten">>}),
io:format("Publish ~s~n", [emqx_message:format(NewMessage)]),
{ok, NewMessage}
end.
```
> feat(emqx_message): add from_map

- rebar.config.erl
Due to a bug (to be investigated) in rebar3, having plugins in test profile significantly slows down `rebar3 eunit` and `rebar3 ct` runs.
> chore(build): Do not use test profile dedicated plugins

- src/emqx_app.erl
This fixes a problem when emqx is built as a dependency of emqtt (CT build).
> Get rel vsn fallback

- etc/emqx.conf
- priv/emqx.schema
revert: fix(config): delete peer_cert_as_username and peer_cert_as_clientid in tcp listener
This reverts commit: 4bf0ad1bafd573bbb4d7590b8ea34e053b3467b7
> revert: fix(config): delete needless config

- .gitattributes
fix file classification.
```
error: Your local changes to the following files would be overwritten by checkout:
apps/emqx_bridge_mqtt/docs/images/bridge.png
apps/emqx_coap/docs/rfc7049.pdf
apps/emqx_coap/docs/rfc7252.pdf
apps/emqx_exproto/docs/images/exproto-arch.jpg
Please commit your changes or stash them before you switch branches.
Aborting
```
> chore(gitattributes): fix file classification.

- src/emqx_connection.erl
- src/emqx_ws_connection.erl
- test/emqx_connection_SUITE.erl
- test/emqx_ws_connection_SUITE.erl
> fix(emqx): deny pingreq when mqtt not connected #4370

- .github/workflows/build_packages.yaml
- rebar.config.erl
Port compiler bug in v1.11.0:
In windows builds, cl.exe produces .obj files
link.exe looks for .o files to link.
> chore(build): pin port_compiler v1.11.1

- apps/emqx_exhook/src/emqx_exhook_handler.erl
- apps/emqx_exproto/src/emqx_exproto_channel.erl
- apps/emqx_lwm2m/src/emqx_lwm2m_cmd_handler.erl
- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- src/emqx_guid.erl
- src/emqx_misc.erl
- src/emqx_tracer.erl
Binary to hexstr:
| -     | Times per second |
| ----- | ---------------- |
| Older | 14 k/s           |
| Now   | 256 k/s          |
Hexstr to binary:
| -     | Times per second |
| ----- | ---------------- |
| Older | 15.77 k/s        |
| Now   | 243.90 k/s       |
> refactor: improve the speed of hexstr and binary conversions

- bin/emqx
- bin/emqx_ctl
- bin/nodetool
For node name and cookie overriden from environment variable
the only way to find it from another shell is to inspect
the vm.args file.
For node boot commands, the vm.args file may not have been created
yet, so we need to inspect node name in emqx.conf
> fix(scripts): Finds node name and cookie from vm.args

- priv/emqx.schema
Convert IP addr str to tuple to please ranch.
Other types of listeners seem me to be happy with the tuple format as well.
Fixes: #4426
> fix(cuttlefish-schema): parse IP addr for SSL listeners.

- lib-ce/emqx_modules/src/emqx_modules_api.erl
Fix http.500 error when loading page:http://127.0.0.1:18083/#/modules on
a emqx cluster.
> fix(cluster-webui): export emqx_modules_api:list_modules/1

- Makefile
- include/emqx_mqtt.hrl
- priv/emqx.schema
- src/emqx_channel.erl
- src/emqx_session.erl
- test/emqx_channel_SUITE.erl
Packet IDs are wrapped around to 1 after 65535.
Allowing a larger inflight limit will only increase the chance of inflight packet ID clash.
> Fix config max inflight overflow

- apps/emqx_coap/TODO
- apps/emqx_coap/src/emqx_coap_app.erl
- apps/emqx_coap/src/emqx_coap_pubsub_resource.erl
- apps/emqx_coap/src/emqx_coap_pubsub_topics.erl
- apps/emqx_coap/src/emqx_coap_sup.erl
- apps/emqx_coap/test/emqx_coap_pubsub_SUITE.erl
Just rename modules `emqx_coap_ps_*` -> `emqx_coap_pubsub_*`.
> refactor(emqx_coap): rename ps to pubsub

- README-CN.md
I have updated the README-CN.md by referring to the `README.md`.
But for the README-JP, we may need Yudai's help @z8674558 :)
> docs(README-CN): fix outdated compile guide

- lib-extra/README.md
Clarify that the user's plugins must include the attribute `-emqx_plugin(xxx)`, otherwise, the `emqx_ctl plugins` command will not find the changed plugins.
see:
https://github.com/emqx/emqx/blob/61c677423e57378618d9e14112d38f6282e23354/src/emqx_plugins.erl#L125-L133
> chore(extra-plugin): statement plugin tag

- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.erl
- apps/emqx_bridge_mqtt/src/emqx_bridge_worker.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_stub_conn.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_worker_SUITE.erl
- src/emqx_app.erl
- src/emqx_listeners.erl
- test/emqx_connection_SUITE.erl
Fixes #3629 
Prior to this change, the inflight batches are referenced
by the last packet ID for non-QoS-0 messages, other packet
IDs sent back from downstream causes an error log:
"Can't be found from the inflight"
Even worse, the batch is appended back to the queue for retry.
> fix(bridge_mqtt): fix inflight reference booking

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_alarm.erl
- src/emqx_congestion.erl
- src/emqx_connection.erl
I'd like to remove the "too_many_publish" alarm as it seems unnecessary, and it is almost always triggered together with the "congestion" alarm in the production.
The only user for this alarm now is SANY and we could change the rule SQL for them if they upgrades to 4.3.0 later. 
Fixes https://github.com/emqx/emqx/issues/4398
> refactor(emqx): the congestion alarm

- Makefile
This rebar3 version has two fixes comparing to 3.14.3-emqx-5
1. For elixir plugin build, ensure vsn in app info
2. Error details in rebar3 exception if .app is not found
when generating release
> chore(build): upgrade to rebar3 3.14.3-emqx-6

- apps/emqx_bridge_mqtt/src/emqx_bridge_worker.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_stub_conn.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_worker_SUITE.erl
This bug is likely the cause of packet ID mismatch reported in #3629
> fix(emqx_bridge_mqtt): fix retry_inflight

- Makefile
- scripts/find-apps.sh
- scripts/find-props.sh
- scripts/find-suites.sh
1. Support `make emqx-ct`
2. Support proper checking targets for each application. E.g: `make apps/emqx_web_hook-prop` or `make emqx-prop`
> Enrich the targets for common tests and proper checking

- apps/emqx_sn/src/emqx_sn_gateway.erl
- apps/emqx_sn/src/emqx_sn_registry.erl
There is race condition when discarding emqx_sn gateway processes, such as unregistering/registering the topic-id.
The solution here is to use the PID as the key of the ETS tables, rather than the ClientID.
> fix(emqx_sn): race_condition when discarding

- apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl
- apps/emqx_exproto/src/emqx_exproto_conn.erl
- apps/emqx_lwm2m/src/emqx_lwm2m_protocol.erl
- apps/emqx_sn/src/emqx_sn_gateway.erl
Some of the connection module also need the call/3 function to be exported.
> fix(export): Mod:call/3 not exported

- apps/emqx_auth_http/etc/emqx_auth_http.conf
- apps/emqx_auth_http/priv/emqx_auth_http.schema
- apps/emqx_auth_http/test/emqx_auth_http_SUITE.erl
- rebar.config
- src/emqx_hooks.erl
Fixes #4602 
to be backward compatible to 4.2.x
cuttlefish 3.3.3 includes a fix to handle empty string
environment variable translated to 'undefined', but not `""`
> fix(config): pin cuttlefish 3.3.3

- rebar.config
Fixes https://github.com/emqx/emqx/issues/4647
The changes in gen_rpc: https://github.com/emqx/gen_rpc/pull/13.
> fix(gen_rpc): the port discovery not working on a large offset

- priv/emqx.schema
- src/emqx_broker.erl
- src/emqx_router.erl
- src/emqx_router_sup.erl
- src/emqx_trie.erl
Fixes #2985 attempt 3
Use cluster global lock to reduce the mnesia remote lock overhead and lock conflicts in a emqx cluster.
Tested locally, get roughly 10X performance gain for deep level wildcard topics.
Also, get good feedback from the community: 
https://github.com/emqx/emqx/issues/2985#issuecomment-822391161
> fix: issue 2985 attempt 3

- deploy/docker/Dockerfile
> chore(docker): manual port setting for gen_rpc when start in docker

- apps/emqx_coap/test/emqx_coap_SUITE.erl
- include/emqx.hrl
- priv/emqx.schema
- src/emqx_app.erl
- src/emqx_router.erl
- src/emqx_trie.erl
- test/emqx_trie_SUITE.erl
This PR refactors `emqx_trie` implementation with mainly two changes
1. Deleted the edge table.
In the old implementation, trie consist of nodes and edges.
e.g. for topic 'a/b/+/d', node 'a' with edge 'b'
points to node 'a/b' and so on.
However, edges can be computed at runtime,
so there is no need to store them in a table.
2. (made configurable) Wildcard topics are split to compact segments. 
In the old (and new but non-compact) implementation, wildcard topics are split
into as many levels as it has. e.g. a/b/+/d
is split to 'a', 'a/b', 'a/b/+' and 'a/b/+/d'.
in the new implementation, there are only
`N+1` levels where `N` is the number of '+' (single levels
wildcard) levels.
e.g. `a/b/+d` is split into 2 levels
`a/b/+` (prefix) and `a/b/+/d` (topic)
e.g. `a/+/b/+/c/#` is split into 3 …
> refactor emqx_trie

- apps/emqx_exhook/priv/emqx_exhook.schema
Under HTTPS, the plugin will not start correctly if the certificate is absent
> fix(exhook): allow certificate options absent

- .github/workflows/run_test_cases.yaml
Coveralls is an optional 3rd party service, it should not fail our builds
> chore(ci): Don't fail builds when coveralls is misbehaving

- apps/emqx_auth_http/src/emqx_auth_http_app.erl
- apps/emqx_auth_http/test/emqx_auth_http_SUITE.erl
- apps/emqx_rule_engine/src/emqx_rule_utils.erl
- apps/emqx_web_hook/src/emqx_web_hook_actions.erl
- apps/emqx_web_hook/src/emqx_web_hook_app.erl
- src/emqx_http_lib.erl
- src/emqx_misc.erl
- src/emqx_vm.erl
- test/emqx_http_lib_tests.erl
prior to this PR:
Ipv6 support in `emqx_auth_http` uses `emqx_web_hook` a static ipv6 resolution during start/restart.
which is: if the target hostname has a ipv6 DNS resolution, then the apps will try to use ipv6 for the rest of its lifecycle.
this could be problematic if a host supports dual-stack but the services is only listening on an ipv4 interface.
after this PR:
`ipv6_probe` option is added to `gen_tcp:connect` option, 
so it tries to reach the service on ipv6 (if it has a ipv6 from DNS resolution)
if it succeeds, everyone is happy, otherwise fallback to the default `gen_tcp:connect` behaviour.
NOTE: `ipv6_probe` is only available in EMQ's otp.git fork.
see: https://github.com/emqx/otp/commit/18c07d55ab1615a59b5dd2f081c98e6fc330d30f
> Ipv6 probe runtime detection

- priv/emqx.schema
by default, when primary log level is set to debug or info
application controller prints supervisor progress info.
this new config make use of logger's built-in filters
for progress report
> feat(logging): make supervisor progress configurable

- src/emqx_trie.erl
emqx_trie table is a ordered_set, with write_concurrency set to
true, the counter is not centrialsed, the ets:info/2 call to
check size == 0 is very expensive
> perf(trie): do not call ets:info/2 to check if table is empty

- apps/emqx_management/src/emqx_mgmt_data_backup.erl
Fixes 
```
apps/emqx_management/src/emqx_mgmt_data_backup.erl
653: Expression produces a value of type 'ok' | [], but this value is unmatched
654: Expression produces a value of type 'ok' | [{'ok',{_,_,_,_,_,_,_}}], but this value is unmatched
```
> Fix dialyzer error on the enterprise version

- bin/emqx
- bin/nodetool
- data/emqx_vars
Prioro to this change, ekka lib dir was added by inspecting
the ekka lib version in persisted RELEASES file.
However, this file may not be the true version if a hot
upgrade failed in the middle.
In this fix, it reads the per-version emqx.rel file
content to load lib paths.
> chore(nodetool) ensure correct lib dirs

- apps/emqx_retainer/src/emqx_retainer.app.src
- apps/emqx_retainer/src/emqx_retainer.appup.src
- apps/emqx_retainer/src/emqx_retainer.erl
- lib-ce/emqx_modules/src/emqx_mod_delayed.erl
- lib-ce/emqx_modules/src/emqx_modules.app.src
- lib-ce/emqx_modules/src/emqx_modules.appup.src
- src/emqx.appup.src
- src/emqx_metrics.erl
The metrics for messages.* should show the number of times such kinds of messages are received. It should be a `counter` type rather than a `gauge`
Finally, these metrics and statistics are used by emqx_prometheus. We fix these indicator types to be more conducive to using them in Prometheus.
> Use `emqx_stats` to record the size of the retained/delayed tables instead of `emqx_metrics`

- src/emqx_connection.erl
- src/emqx_frame.erl
piror to this change, binary concatenation eats most of the CPU
Fixes  #4787
> fix(emqx_frame): poor large frame concatenation performance

- src/emqx.appup.src
- src/emqx_connection.erl
`inet:setopt(Sock, [{active, N}])` returns `{error, einval}` if the socket is already closed.
this is a very common situation when the client closed socket while the connection process is still processing its events
> fix(emqx_connection): do not log einval error

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_management.appup.src
- src/emqx.appup.src
- src/emqx_cm.erl
- test/emqx_cm_SUITE.erl
Fixes #4831 
when a node requests another to discard a session (takeover),
if the session process is already gone by the time it receives the discard call,
the `noproc` exception happens. (i.e. a race condition)
this exception is discarded for tcp connection clients as they emit `exit : {noproc, {gen_server, call, ...}}`
for websocket clients however, the error reason is just `noproc` (not a tuple),
which does not match any of the exception handler's `catch` clauses.
> fix(emqx_cm): do not log noproc as error

- .github/workflows/build_slim_packages.yaml
- src/emqx.appup.src
- src/emqx_frame.erl
- test/emqx_frame_SUITE.erl
fixes #4857 
Prior to this commit, there was a bug in emqx_frame:split/2
the tail number of bytes was used for header number of bytes
whens split. As a result, if the tail happens to be longer
then haeder, the parsing state becomes invalid and it crashes
when the next packet arrives
The split was a over-engineered micro-optimization, so it
has been deleted instead of fixed
> fix(emqx_frame): no need to split incoming bytes

- apps/emqx_lwm2m/src/emqx_lwm2m.app.src
- apps/emqx_lwm2m/src/emqx_lwm2m.appup.src
- apps/emqx_lwm2m/src/emqx_lwm2m_message.erl
- apps/emqx_lwm2m/test/emqx_lwm2m_SUITE.erl
When a resource of type `Opaque` is uploading data, emqx-lwm2m will encode it directly using base64. The event is then serialized as a JSON and published to a topic.
https://github.com/emqx/emqx/blob/1098df815a91420a46c3155f94a49a1c79d5906e/apps/emqx_lwm2m/src/emqx_lwm2m_message.erl#L141-L143
But in the opposite direction, emqx-lwm2m deserializes a JSON into a data message for the LWM2M protocol without performing base64:decode/1 on an Opaque type of data.
> fix(lwm2m): base64 decode for opaque value

- bin/emqx
- bin/nodetool
- rebar.config.erl
nodetool has all lib paths set up correctly by reading the
persisted RELEASES file
calling hocon escript directly has two problems:
1. it may not be able to find the beams compiled
2. if we use ERL_LIBS, it may find the version after hot beam upgrade
> refactor(bin/emqx): invoke hocon_cli from nodetool

- bin/nodetool
Just learned that some of the erts distributions implicitly add paths, some don't.
call code:add_patha to ensure overrides whatever implicitly added paths.
> fix(nodetool): add_pathz -> add_patha

- apps/emqx_lwm2m/rebar.config
Wait for the predecessor PR merge to complete https://github.com/emqx/lwm2m-coap/pull/16
> chore: upgrade lwm2m_coap to 1.1.4

- apps/emqx_lwm2m/rebar.config
v2.0.0 has emqx_http_lib added as a rebar dependency
v1.* is for emqx v4.3.*
> chore(emqx_lwm2m): pin lwm2m-coap v2.0.0

- apps/emqx/src/emqx_app.erl
- build
- rebar.config.erl
We have an assertion in code, allowing user to override
will compile but not run.
> build: do not allow user override PKG_VSN

- apps/emqx/rebar.config
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_quic_stream.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- rebar.config
- Bump quic to 0.0.5
- Bump emqtt to 1.4.1
- Support active_n socket opt
- Add tests for mqtt over quic
> QUIC support PART 2

- .github/workflows/build_packages.yaml
@turtleDeng @tigercl @zmstone @qzhuyan @wivwiv 
Quic does not support 32-bit builds, do we still need to continue to support 32-bit docker images ?
> chore(CI): cancel build of 32-bit docker

- lib-ce/emqx_modules/src/emqx_mod_presence.erl
- lib-ce/emqx_modules/src/emqx_modules.app.src
- lib-ce/emqx_modules/src/emqx_modules.appup.src
In the previous version,  the `disconnected` events miss some important fields to show a connection infos. i.e: `proto_name`, `proto_ver`
N/A
Docs PR: https://github.com/emqx/emqx-docs/pull/812
> chore(presence): more fields for disconnected event

- .ci/build_packages/tests.sh
- .github/workflows/build_packages.yaml
- apps/emqx/rebar.config
- apps/emqx/rebar.config.script
- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_app.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_schema.erl
- rebar.config
- rebar.config.erl
This PR address the build issue in ci: build-package.
- conditionally quicer build
- Skip quic listener in test of arm platform
- skip quicer build on cento6 due to too old header files.
- env vars to control Quicer build
1. set `EMQX_NO_QUIC` to disable the start of quic listener
Left TODOs:
Disable NIF compiling in quicker project instead.
Investigate why open quic port failed with qemu emulator.
> ci(quic): conditionally quicer build

- apps/emqx/etc/emqx.conf
> fix(emqx.conf): default wss max_connection from 16 to 102400

- deploy/charts/emqx/Chart.yaml
- deploy/charts/emqx/README.md
- deploy/charts/emqx/templates/service.yaml
- deploy/charts/emqx/values.yaml
Let `externalIPs` be configurable in the Helm chart
> feat(helm): add externalIPs to chart

- apps/emqx/rebar.config
- rebar.config
- scripts/check-deps-integrity.escript
Hi, All
I don't think we should introduce branch dependencies in master, which can make the project unstable, and we can use tags or commit ids to indicate dependencies
> chore(deps): deps in rebar must not be use branch

- apps/emqx_retainer/etc/emqx_retainer.conf
- apps/emqx_retainer/include/emqx_retainer.hrl
- apps/emqx_retainer/src/emqx_retainer.erl
- apps/emqx_retainer/src/emqx_retainer_app.erl
- apps/emqx_retainer/src/emqx_retainer_cli.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/src/emqx_retainer_pool.erl
- apps/emqx_retainer/src/emqx_retainer_schema.erl
- apps/emqx_retainer/src/emqx_retainer_sup.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl
- apps/emqx_retainer/test/mqtt_protocol_v5_SUITE.erl
1. emqx_retainer as driver and api layer
2. emqx_retainer_storage as bridge layer
3. emqx_retainer_storage_xxx is the backend
backend only need implementation emqx_retainer_storage behavior
> feat(eqmx_retainer): let emqx_retainer be extended to support other databases

- apps/emqx/rebar.config
- apps/emqx/src/emqx_schema.erl
- rebar.config
Pin `hocon` version `0.10.4` which has the `atom_key` option fixed:
After this change `atom_key` only affects struct fields,
but not fields inside a non-type-safe `map()`.
Also, `hocon` version `0.10.4` uses `$hc` prefixed atoms for
`richmap`'s meta-fields names, this makes possible for us to use
`value`, `metadata` and `type` in both rich-map and plain-map
without clashing with `hocon`.
> fix(emqx_schema): call new hocon_schema API to get field value

- src/emqx_app.erl
Application:stop is call after the root supervisor is stopped,
in our case, prior to this fix, emqx_sup is stopped before
the listeners (hence the emqx_connection processes).
This causes shutdown to emit a lot of error logs
e.g. emqx_broker pool is down, but emqx_connection process is still
trying to call the pool
> fix(emqx_app): stop listeners in application prep_stop callback

- apps/emqx/src/emqx_schema.erl
- bin/emqx
- bin/emqx_ctl
- bin/nodetool
Prior to this change, there are code to support starting short Erlang node names (boot with `-sname`),
but did not work properly.
This PR makes `-sname` work again.
Next steps are to make EMQ X boot with short name by default.
Reasons why we want to promote short name:
1. default node name emqx@127.0.0.1 is causes trouble when a user want to create cluster after experimenting with single node
2. it gives an impression for our users that the node name has to include an IP address
3. because of 2), it's not quite nice to deploy emqx in containers where IP address tend to change at each re-deployment
> feat: support short node name (sname)

- apps/emqx/src/emqx_schema.erl
- extension_schemas.config
- rebar.config.erl
We read the root field names and schema modules from extension_schemas.config, and assign it to the macro `EMQX_EXT_SCHEMAS`.
> feat(config): read schemas for apps from file at build time

- apps/emqx/src/emqx_schema.erl
the only lib used lager was amqp client which is now updated
with lager droped from its dependencies
> chore(config): delete lager config

- apps/emqx/src/emqx_alarm.erl
- apps/emqx/src/emqx_app.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_config_handler.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_map_lib.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_SUITE.erl
- apps/emqx/test/emqx_mqtt_caps_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_SUITE.erl
- apps/emqx_authz/test/emqx_authz_http_SUITE.erl
- apps/emqx_authz/test/emqx_authz_mongo_SUITE.erl
- apps/emqx_authz/test/emqx_authz_mysql_SUITE.erl
- apps/emqx_authz/test/emqx_authz_pgsql_SUITE.erl
- apps/emqx_authz/test/emqx_authz_redis_SUITE.erl
- apps/emqx_resource/src/emqx_resource_instance.erl
This is to allow putting configs with different scopes (root names)
so we can start emqx app independently (without all merged configs)
> refactor(emqx_config): store configs per root name

- bin/emqx
prior to this fix the logger message (syslog) has the name and pid
missing.
with this change, the programe name, and its boot command is logged
to syslog, so the console boot is cleaner
> fix(bin/emqx): fix boot log

- bin/emqx
- deploy/docker/docker-entrypoint.sh
Starting from v5, we are going to support only EMQX_NODE_NAME
> chore: delete EMQX_NAME and EMQX_HOST env variables

- apps/emqx_lwm2m/src/emqx_lwm2m.app.src
- apps/emqx_lwm2m/src/emqx_lwm2m.appup.src
- apps/emqx_lwm2m/src/emqx_lwm2m_message.erl
- apps/emqx_lwm2m/test/emqx_lwm2m_SUITE.erl
- apps/emqx_lwm2m/test/emqx_lwm2m_message_tests.erl
Fix https://github.com/emqx/emqx/issues/4989
We should always write a signed integer to the device, no matter it is a positive or negative integer.
> fix(lwm2m): write incorrect integer to device

- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_config_handler.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/src/emqx_mgmt_http.erl
I'd like to add a general config updating API for all the config map:
**PATH:**  /api/v5/configs?conf_path=<config-paths>
Examples:
```
HTTP GET /api/v5/configs?conf_path=.
HTTP GET /api/v5/configs?conf_path=.alarm
HTTP PUT /api/v5/configs?conf_path=.alarm
{"actions": ["log", "publish"],
"size_limit": 1000,
"validity_period": "12h"
}
HTTP PUT /api/v5/configs?conf_path=.alarm. validity_period
12h
HTTP DELETE /api/v5/configs/alarm?conf_path=size_limit
```
1. I'd prefer using query string parameter `conf_path` rather than put it into the request body, because some "RESTful" HTTP clients might not allow to have HTTP body for `DELETE` method.
2. The `conf_path` is the path to the config entry, and it's of [jq](https://stedolan.github.io/jq/manual/) syntax.
3. The `DELETE` API removes the …
> APIs for config hot update

- apps/emqx_exhook/rebar.config
- apps/emqx_exproto/rebar.config
- apps/emqx_exproto/src/emqx_exproto.app.src
- apps/emqx_exproto/src/emqx_exproto.appup.src
- apps/emqx_exproto/src/emqx_exproto_channel.erl
- apps/emqx_exproto/src/emqx_exproto_gcli.erl
After the stream held by emqx_exproto_gcli is closed, it is not working to initiate grpc requests to the backend service. 
This would cause all client processing fail.
> Retry the closed stream

- apps/emqx_exhook/etc/emqx_exhook.conf
- apps/emqx_exhook/priv/emqx_exhook.schema
- apps/emqx_exhook/src/emqx_exhook.app.src
- apps/emqx_exhook/src/emqx_exhook.appup.src
- apps/emqx_exhook/src/emqx_exhook.erl
- apps/emqx_exhook/src/emqx_exhook_app.erl
- apps/emqx_exhook/src/emqx_exhook_cli.erl
- apps/emqx_exhook/src/emqx_exhook_mngr.erl
- apps/emqx_exhook/src/emqx_exhook_server.erl
- apps/emqx_exhook/src/emqx_exhook_sup.erl
- apps/emqx_exhook/test/emqx_exhook_SUITE.erl
In this PR, we have enhanced the exhook experience:
1. we have added a retry mechanism to allow grpc-server to be started and stopped at any time.
2. A new `request_failed_action` option has been added. It allows customizing the result of a failed request to the grpc-server. For example, return authentication failure, or ignore the request.
> Add a retry mechanism for exhook

- apps/emqx_machine/src/emqx_machine.erl
- rebar.config.erl
the `erlc_options` option for mix project doesn't works with `d` good, make it static to unblock the mix
> feat: make EMQX_DEPS_APPS static

- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/templates/service.yaml
Having an internal MQTT service on a pod doesn't have many use cases but by exposing it on a cluster we can connect our internal services to the MQTT without ACL or authentication. In this PR users can enable this service by setting the following variable:
```
EMQX_LISTENER__TCP__INTERNAL: 11883
```
just like the other environment variables.
> Expose Internal MQTT Service

- etc/emqx.conf
- priv/emqx.schema
- src/emqx.app.src
- src/emqx.appup.src
- src/emqx_alarm_handler.erl
- src/emqx_misc.erl
This fix changes the `kill` option of `erlang:process_flag(max_heap_size, Opt)` to `true`, and changes the `max_heap_size` for force kill to `1.2 * ForceShutdown`.
**This only solves the situation if the heap_size is too large, but the process can never have a chance** to inspect the current heap size, might because of too many queued messages in the process mailbox to be handled.
But for the situation that if all the (binary) messages are stored in the binary referenced heap, and the current heap_size is small, this fix won't help, because in this case the full-sweep GC on the process won't be triggered, so the process won't be killed (by the garbage collector). We have a periodically global GC, run every 15mins by default (can be configured by setting `node.global_gc_interval`), which …
> The connection process cannot suicide

- apps/emqx_authn/src/emqx_authn_app.erl
- apps/emqx_gateway/src/emqx_gateway.app.src
This PR makes sure that the shards are initialized before usage
> fix(rlog): Ensure the correct order of table initalization

- deploy/charts/emqx/templates/StatefulSet.yaml
emqx pods try to write a config file in the `/opt/emqx/data/configs/` path during the startup, which fails on Openshift clusters, since users are restricted to run containers with writable filesystems (which indeed is a good security practice).
So the pod goes into CrashLoopBackOff state with the following errors in logs:
```
2021-08-12T11:26:56.505718+00:00 [error] Error writing /opt/emqx/data/configs/app.2021.08.12.11.26.38.config: permission denied
2021-08-12T11:26:56.505907+00:00 [error] Error writing /opt/emqx/data/configs/vm.2021.08.12.11.26.38.args: permission denied
```
This PR mounts an emptyDir volume in `/opt/emqx/data/configs/` path which mitigates this issue.
Tested on Openshift 4.7
> fix: Running on Openshift clusters with restricted writable filesystem containers

- deploy/charts/emqx/Chart.yaml
This is a fancy feature recommends by `helm lint` and for example causes the EMQX logo to show on the Openshift panel as follows. I am using the Github logo so it uses the latest logo from EMQX's Github organization.
> Add Chart Icon

- apps/emqx/src/emqx.erl
- apps/emqx/src/emqx_alarm.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_config_handler.erl
- apps/emqx/test/emqx_alarm_SUITE.erl
- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_authz/src/emqx_authz_api.erl
- apps/emqx_authz/test/emqx_authz_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_SUITE.erl
- apps/emqx_authz/test/emqx_authz_http_SUITE.erl
- apps/emqx_authz/test/emqx_authz_mongo_SUITE.erl
- apps/emqx_authz/test/emqx_authz_mysql_SUITE.erl
- apps/emqx_authz/test/emqx_authz_pgsql_SUITE.erl
- apps/emqx_authz/test/emqx_authz_redis_SUITE.erl
- apps/emqx_data_bridge/src/emqx_data_bridge.erl
- apps/emqx_data_bridge/src/emqx_data_bridge_api.erl
- apps/emqx_data_bridge/src/emqx_data_bridge_app.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_modules/src/emqx_rewrite.erl
- apps/emqx_modules/src/emqx_rewrite_api.erl
- apps/emqx_prometheus/src/emqx_prometheus_api.erl
- apps/emqx_statsd/src/emqx_statsd_api.erl
- remove the circular dependency between emqx_config and emqx_config_handler
- refactor the return values of emqx:update_config/2,3, to make sure the return value contains sufficient information about:
1. if success, the return values of `Handler:post_config_update/3` all the config handlers
2. if failed, either the reason of the failure, such as written to disk failed or the hocon_schema validation failed; or the error returned by the `Handler:pre_config_update/3` and `Handler:post_config_update/3` all the config handlers
- add one more callback function `Handler:config_update_failed/3` to give each handler a chance to do some clean works.
> Refactor return values of config update

- apps/emqx/etc/emqx.conf
- apps/emqx/test/emqx_plugins_SUITE_data/emqx_hocon_plugin/etc/emqx_hocon_plugin.conf
- apps/emqx_authn/etc/emqx_authn.conf
- apps/emqx_authz/etc/emqx_authz.conf
- apps/emqx_bridge_mqtt/etc/emqx_bridge_mqtt.conf
- apps/emqx_dashboard/etc/emqx_dashboard.conf
- apps/emqx_data_bridge/etc/emqx_data_bridge.conf
- apps/emqx_exhook/etc/emqx_exhook.conf
- apps/emqx_gateway/etc/emqx_gateway.conf
- apps/emqx_machine/etc/emqx_machine.conf
- apps/emqx_management/etc/emqx_management.conf
- apps/emqx_modules/etc/emqx_modules.conf
- apps/emqx_prometheus/etc/emqx_prometheus.conf
- apps/emqx_retainer/etc/emqx_retainer.conf
- apps/emqx_rule_engine/etc/emqx_rule_engine.conf
- apps/emqx_statsd/etc/emqx_statsd.conf
This is the first step to configuration structure change: using '=' instead of ':' in the *.conf files.
> refactor(config): replace all ':' with '=' in the *.conf

- apps/emqx/src/emqx_logger_textfmt.erl
```
(emqx@127.0.0.1)1> logger:error("abc").
ok
2021-08-20T18:10:01.180622+08:00 error: FORMATTER CRASH: {string,"abc"}
```
> fix(log): text formatter crash

- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_config_handler.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_map_lib.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/src/emqx_mgmt_api_listeners.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- apps/emqx_management/test/emqx_mgmt_listeners_api_SUITE.erl
- refactor the code of HTTP APIs for starting/stoping listeners.
- add the APIs for updating/creating/deleting configs of listeners.
> refactor(listener): GET /listeners API returns full config of listeners

- deploy/charts/emqx/templates/service.yaml
fixs: #5254
The dist port behind headless svc should to be accessible during emqx
cluster boot.
Endpoints of headless SVC is not in 'ready' state that prevents nodes to talk to
each other, this issue only happens when K8s host node is restarted and
all emqx nodes are deployed on the same host.
> Backport: fix(helm-chart): force headless svc ready while pod is not ready

- deploy/charts/emqx/templates/service.yaml
fixs: #5254
The dist port behind headless svc should to be accessible during emqx
cluster boot.
Endpoints of headless SVC is not in 'ready' state that prevents nodes to talk to
each other, this issue only happens when K8s host node is restarted and
all emqx nodes are deployed on the same host.
> fix(helm-chart): force headless svc ready while pod is not ready

- apps/emqx_auth_http/etc/emqx_auth_http.conf
I think we don't need superuser to be enabled by default but these default configurations cause superuser request be enabled by default acorrding the following code:
```erl
case application:get_env(?APP, super_req) of
undefined ->
emqx_hooks:put('client.authenticate', {emqx_auth_http, check, [#{auth => maps:from_list(AuthReq),
super => undefined}]});
{ok, SuperReq} ->
PoolOpts1 = proplists:get_value(pool_opts, SuperReq),
PoolName1 = proplists:get_value(pool_name, SuperReq),
{ok, _} = ehttpc_sup:start_pool(PoolName1, PoolOpts1),
emqx_hooks:put('client.authenticate', {emqx_auth_http, check, [#{auth => maps:from_list(AuthReq),
super => maps:from_list(SuperReq)}]})
end
```
also by using environment variables there is no way to disable them.
> Disable Superuser Request by Defualt

- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/check_deps_integrity.yaml
- .github/workflows/run_api_tests.yaml
- .github/workflows/run_emqx_app_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_relup_tests.yaml
- .github/workflows/run_test_cases.yaml
- deploy/docker/Dockerfile
+ Now we use [this repository](https://github.com/emqx/emqx-builder-helper) to build the image and push it to [ghcr](https://github.com/emqx/emqx-builder-helper/pkgs/container/emqx-builder-helper), the `emqx/build-env` image will not be updated afterwards
+ `emqx-builder-helper` distinguish between compiling different `emqx` versions [using release](https://github.com/emqx/emqx-builder-helper/releases/tag/5.0).
> chore(CI): use ghcr

- apps/emqx_bridge/etc/emqx_bridge.conf
- apps/emqx_bridge/src/emqx_bridge_schema.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_mod.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_msg.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
- If the MQTT Bridge is started along (without using the rule engine), it can forward local message to the remote broker, and vice versa.
- And the MQTT Bridge may be configured not to subscribe local topics, or not to send messages (from remote broker) to local broker. In this case the bridge can be used as a data-source or data-sink of rules.
> Use MQTT Bridge as Data Source or Data Sink of Rules

- apps/emqx_modules/src/emqx_delayed.erl
- When current stored messaged in the ETS table equals to `max_delayed_messages`, the table should be `full`.
> Fix max_delayed_messages not working

- include/emqx_mqtt.hrl
- src/emqx.appup.src
- src/emqx_access_rule.erl
- src/emqx_channel.erl
- src/emqx_cm.erl
- src/emqx_connection.erl
- src/emqx_ws_connection.erl
- test/emqx_cm_SUITE.erl
- test/mqtt_protocol_v5_SUITE.erl
1. Export `emqx_channel:ensure_keepalive/2`, `emqx_channel:clear_keepalive` for `emqx-sn` plugin
2. Safer `emqx_connection:call/3` for `emqx_cm` module
3. Support `ipaddrs` for acl.conf
> Backport 4.3

- bin/emqx
this is to add some debug info output when fail to stop.
in bin/emqx:
`ps -p $PID` indicated the pid is still around.
but in ci script:
`ps -ef | grep ...` can not find it any more.
> chore(bin/emqx): print pid info if failed to stop

- .github/workflows/run_fvt_tests.yaml
- lib-ce/emqx_dashboard/src/emqx_dashboard.app.src
- lib-ce/emqx_dashboard/src/emqx_dashboard.appup.src
- lib-ce/emqx_dashboard/src/emqx_dashboard_admin.erl
- lib-ce/emqx_dashboard/test/emqx_dashboard_SUITE.erl
Make messages not differ when authenticating with an invalid password and invalid username.
Closes: #5563
> fix(dashboard rest api): improve auth method security

- .ci/fvt_tests/local_relup_test_run.sh
- .ci/fvt_tests/relup.lux
- .github/workflows/run_fvt_tests.yaml
Relup tests are rather complicated and tricky to debug. Also, they run for ages. So I made an effort to tidy them up a bit.
What I did:
* Removed some completely unused steps. Neither Python nor Paho things are used in relup tests.
* Introduced a [container](https://github.com/savonarola/emqx-relup-env) with prebuilt Lux and MQTT Bench. They are built from scratch each time, but there is no need to do this since the test already runs in a container. We may add them once to a container.
* Separated job into three: `plan` ➡️ `build emqx` ➡️ `run relup tests`. 
* This straightens the logic: currently steps are coupled. For example, downloaded packages are used both for building EMQX and for further testing. This makes unobvious dependencies between steps.
* This allows each relup test to …
> chore(relup tests): refactored relup tests

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_management.appup.src
- apps/emqx_management/src/emqx_mgmt_api_pubsub.erl
- apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
To provide a reasonable error message and avoid crashes resulting in 500 HTTP errors.
Resolves #5737
> Add validations to mgmt api

- src/emqx.app.src
- src/emqx.appup.src
app 4.3.9 was release as a part of enterprise e4.3.4
but opensource v4.3.9 is not releasd yet, but we have
to bump app version to 4.3.10 to make appup work for the next
release (either opensource or enterprise).
> chore(emqx.app): bump emqx app to vsn 4.3.10

- apps/emqx/src/emqx_authentication_config.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx_authn/src/emqx_authn_api.erl
- apps/emqx_authn/src/emqx_authn_schema.erl
- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- apps/emqx_authn/test/emqx_authn_test_lib.erl
- apps/emqx_dashboard/src/emqx_dashboard_api.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl
- apps/emqx_dashboard/test/emqx_swagger_requestBody_SUITE.erl
- apps/emqx_modules/src/emqx_rewrite_api.erl
Here we reuse config schemas for validations and preserve existing examples.
**Important** Although this PR specifies existing config schemas for responses too, this does not break functionality of returning ids added to authenticator configs in responses. This is because currently response schemas are used for documentation, but not for validation. 
We probably should
* Add more examples, for actions and parameters not represented in configs;
* Test all methods at least on builtin database.
> refactor(authn api): use config schemas for request validations

- apps/emqx/rebar.config
- rebar.config
hocon had a bug prior to 0.20.6, the translation result was discarded in case of 'richmap' in use (the default option when generating app.<time>.config file.
as a result, the `"emqx_tls_psk:lookup"` string was not translated to `{fun emqx_tls_psk:lookup/3, undefined}` causing invalid options for ekka etcd clustering config.
> [v5.0] fix(config): pin hocon 0.20.6

- .github/workflows/code_style_check.yaml
- scripts/elvis-check.sh
In order NOT to force style changes in all files, this fixed action only checks changed files.
the script to check newline at EOF is not used so far.
> build: fix elvis check and ensure newline at EOF

- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
t_commit_ok_apply_fail_on_other_node_then_recover occasionally fails.
if we commit the transaction successfully on a node several times in quick succession, multiple mnesia_event will occur to other nodes, and then other nodes will catch_up immediately after receiving it, here the retry time of other nodes is not the standard 1 second.
The original case assumes a strict retry time of 1 second.
So I change the case.
> fix(test): cluster_rpc retry interval incorrect

- src/emqx_channel.erl
- src/emqx_cm.erl
- src/emqx_connection.erl
- src/emqx_stats.erl
- test/emqx_broker_SUITE.erl
- test/emqx_channel_SUITE.erl
- test/emqx_connection_SUITE.erl
- test/emqx_mqueue_SUITE.erl
- test/emqx_ws_connection_SUITE.erl
In order to correctly display the number of _connected_ clients in our monitor dashboard, we need to track those connections that are actually connected to clients, not considering connections from persistent sessions that are disconnected. Today, the `connections.count` that is displayed in the dashboards considers those disconnected persistent sessions as well.
The new statistics can be found in the [`emqx_management`](https://github.com/emqx/emqx/tree/main-v4.4/apps/emqx_management) plugin, under `/api/v4/stats`, in the keys `live_connections.{max,count}`.
```sh
curl -su admin:public http://localhost:18083/api/v4/stats | jq .
```
```json
{
"data": [
{
"stats": {
"topics.max": 0,
"topics.count": 0,
"subscriptions.shared.max": 0,
"subscriptions.shared.count": 0,
"subscriptions.max": 0, …
```
> Track connected client count

- .github/workflows/run_fvt_tests.yaml
A few FVT tests are very flaky when run in rlog core+replicant cluster
configuration (for instance `V5/test_publish.py::test_topic`). We are
disabling this test configuration temporarily while we investigate
further and mitigate it.
> fix(ci): temporarily disable rlog FVT tests (flakiness)

- apps/emqx/rebar.config
- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_stats.erl
- apps/emqx/test/emqx_broker_SUITE.erl
- apps/emqx/test/emqx_channel_SUITE.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx/test/emqx_ws_connection_SUITE.erl
- rebar.config
Track connected client count
In order to correctly display the number of _connected_ clients in our monitor dashboard, we need to track those connections that are actually connected to clients, not considering connections from persistent sessions that are disconnected. Today, the
`connections.count` that is displayed in the dashboards considers those disconnected persistent sessions as well.
The new statistics can be found in the [`emqx_management`](https://github.com/emqx/emqx/tree/main-v4.4/apps/emqx_management) plugin, under `/api/v4/stats`, in the keys `live_connections.{max,count}`.
Ported from #6056 .
> feat(stats): track live channel / client count

- apps/emqx_authn/test/data/user-credentials-malformed-0.json
- apps/emqx_authn/test/data/user-credentials-malformed-1.json
- apps/emqx_authn/test/data/user-credentials-malformed.csv
- apps/emqx_authn/test/emqx_authn_mnesia_SUITE.erl
The tests that had been commented out and were using `emqx_authentication` module now belong to its own tests.
> chore(authn mnesia): reimplement emqx_authn_mnesia provider tests

- apps/emqx_plugin_libs/src/emqx_st_statistics/emqx_st_statistics.erl
- etc/emqx.conf
- priv/emqx.schema
- src/emqx_session.erl
allows not to process the message before the session is created
to solve the problem caused by clean session = false
> fix(eqmx_st_statistics): add ignore_before_create in config

- bin/emqx
There is no way for that cookie file to get used without setting the `HOME` environment variable to data dir.
> chre(bin/emqx): delete unused cookie file chown

- pkg-vsn.sh
We sometime forget to bump RELEASE version before we tag a new release.
This change is to ensure that when tagging a new release, the RELEASE version has been updated.
> build: ensure git tag matches release version

- deploy/packages/rpm/Makefile
- deploy/packages/rpm/emqx.spec
We'll start using the full version number for example: `4.4.0-alpha.1-1ced42d3` for the RPM version string.
And OTP version number as the release. `otp23.3.4.9-3`.
However, RPM does not allow `-` in version and release numbers, so replaced by `_`.
```
==========================================================================================================================================================================================================
Package                              Architecture                           Version                                                                   Repository                                    Size
================================================================================================================================================ …
```
> build: Move otp version number to RPM's release part

- Makefile
- build
- deploy/docker/Dockerfile.testing
The defulat docker build (e.g. `make emqx-docker`) is based on alpine
image and it builds EMQ X from source code.
This is not flexible enough when we want to quickly run some tests
in a docker container.
The new docker build (e.g. `make emqx-docker-testing`) by default takes
the built zip package, and extract it in a very primitive base image
such as ubuntu:20.04 and centos:8
> feat(docker): add flexible docker build

- apps/emqx/test/emqx_persistent_session_SUITE.erl
Make sure that the connection process dies before terminating the
snabbkaffe trace.
> test(persistent_session_SUITE): fix another flaky test

- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
ordered_set is compatible to set in all the existing APIs
and in addition, it provides a more deterministic traversing
cursor in case we want to change the current dirty_select
based "select ALL" implementation
> [5.0] refactor(retainer): use ordered_set Mnesia table type

- Makefile
In CI, the source code is downloaded with make deps-all
zipped and uploaded as an GitHub action artifact to be
downloaded in later steps to build packages
The symlinks are abs paths, meaning it might be broken
when unziped (inside docker containers)
This fix adds a `make clean` step after the deps-all target
and the `clean` target also removes rebar.lock and symlinks
> build: ensure symlinks in _build dir are deleted after fetching deps

- .github/workflows/git_sync.yaml
- .tool-versions
- rebar.config.erl
This marks the first commit for disclosing EE code to this repo.
future steps (for 5.0, current `master` branch):
* EE code will reside in `lib-ee` in THIS repo's `master` branch
* EE code will be under license "EMQ Business Source License 1.0"
* CE package should never be polluted with EE code
* Upgrade to EE from CE with a zip package extraction + node restart
> Prepare to disclose EE code under EMQ BSL 1.0

- .ci/docker-compose-file/docker-compose-emqx-cluster-rlog.override.yaml
- .github/workflows/run_fvt_tests.yaml
The RLOG DB backend tests in FVT were temporarily disabled due to some
paho tests being specially flaky in CI.
In particular, those tests had the common pattern of subscribing to a
topic, immediately publishing to that topic and then waiting for the
response.  When in CI and using RLOG, there seems to be more delays in
replication of data, and often this pattern would fail in the
constraint testing enviroment.
> test(rlog): reenable RLOG FVT tests

- apps/emqx/src/emqx_authentication.erl
- apps/emqx/test/emqx_authentication_SUITE.erl
- apps/emqx_authn/src/emqx_authn_app.erl
To preserve configuration after emqx_authentication crashes.
> fix(authn): transfer chain tab to emqx_authentication_sup

- Makefile
- build
prior to this change, the OTP_VSN varaible was taken from
the docker host's OTP version which may differ from the
desired OTP version for the docker builder image.
> build: define default builder docker image tag

- .ci/build_packages/Dockerfile
- .ci/docker-compose-file/docker-compose.yaml
- .ci/fvt_tests/local_relup_test_run.sh
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/check_deps_integrity.yaml
- .github/workflows/run_acl_migration_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_test_cases.yaml
- deploy/docker/Dockerfile
- docker.mk
There was a typo fix in ssl app for ecdsa_secp512r1_sha512
to ecdsa_secp521r1_sha512.
Hot-beam upgrade is supported when upgrading from OTP 23.2.7.2-emqx-2
just a 'ssl_cipher' module reload.
> build: upgrade to otp sed 23.2.7.2-emqx-3

- apps/emqx/src/emqx_sys_mon.erl
- apps/emqx/src/emqx_vm.erl
- apps/emqx/test/emqx_sys_mon_SUITE.erl
This adds the information from `proc_lib:initial_call/1` and the
current stacktrace from the process info to `emqx_sys_mon:procinfo/1`
to aid in debugging some warnings with no context such as the
following:
```
2021-11-23T12:33:59.387818+00:00 [warning] info: [{old_heap_block_size,45988046},{heap_block_size,22177879},{mbuf_size,0},{stack_size,40},{old_heap_size,22354134},{heap_size,7106339}], line: 130, mfa: emqx_sys_mon:handle_info/2, msg: large_heap, procinfo: [{pid,<0.2667.0>},{memory,579763664},{total_heap_size,68510672},{heap_size,22177879},{stack_size,40},{min_heap_size,233},{initial_call,{proc_lib,init_p,5}},{current_function,{gen,do_call,4}},{registered_name,[]},{status,running},{message_queue_len,360945},{group_leader,<0.1660.0>},{priority,normal},{trap_exit,false},{reductions,16 …
```
> feat(sys_mon): Add proc_lib:initial_call/1 and current_stacktrace

- scripts/update_appup.escript
- Fixes clause error on `create_stub/1`.
- Small optimization: do not download the same file multiple times
with `wget`.
- Fix: remove old file extension (`.app.src`) and preserve dirname 
when creating stubs for apps.
> chore(appup): minor fixes to update_appup.escript

- scripts/update_appup.escript
- Fixes clause error on `create_stub/1`.
- Small optimization: do not download the same file multiple times
with `wget`.
- Fix: remove old file extension (`.app.src`) and preserve dirname
when creating stubs for apps.
> chore(appup): minor fixes to update_appup.escript (5.0)

- apps/emqx_gateway/test/emqx_exproto_echo_svr.erl
- apps/emqx_gateway/test/emqx_sn_protocol_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
Currently, when tests fail, it's a bit tedious to scroll and find actual errors.
> chore(ct): remove verbose output during tests

- apps/emqx/test/emqx_trace_handler_SUITE.erl
- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf.erl
- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
- apps/emqx_gateway/src/emqx_gateway_conf.erl
- apps/emqx_modules/src/emqx_modules_app.erl
- apps/emqx_modules/test/emqx_rewrite_SUITE.erl
1. fix emqx_conf return nest error(`{error, {error, term()}}`).
2. add `emqx_cluster_rpc:fast_forward_to_commit/2` api.
3. add `emqx_ctl cluster_call` command.
> feat: support eqmx_ctl cluster_call command.

- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_channel_SUITE.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx/test/emqx_session_SUITE.erl
`emqx_listeners:{current,max}_conns` were matching on type `tcl`.
However, this type doesn't exist (it's not defined in
`?TYPES_STRING`). Therefore, this clause would never match.  It seems
that the intention was that it shouldbe `tcp`.
> fix(listeners): fix typo in listener type

- rebar.config
We're doing this to remove some missing change warnings when updating
emqx v4.3.10.  Ekka's appup was updated in emqx/ekka#140 .
<details>
<summary> `update_appup.escript` output after update (running against 4.3.10) </summary>
```
Found the previous appup file: _build/emqx/rel/emqx/lib/ekka-0.8.1.6/ebin/ekka.appup
INFO: Application 'ekka' has been updated: "0.8.1.4" -> "0.8.1.6"
... elided ...
ERROR: Appup file for the external dependency 'ehttpc' is not complete.
Missing changes: #{down =>
[{"0.1.10",
[{load_module,ehttpc_pool,brutal_purge,soft_purge,[]},
{load_module,ehttpc,brutal_purge,soft_purge,[]}]},
{<<"0\\.1\\.0">>,
[{load_module,ehttpc_pool,brutal_purge,soft_purge,[]},
{load_module,ehttpc,brutal_purge,soft_purge,[]}]},
{<<"0\\.1\\.[1-7]">>, …
```
> chore(ekka): bump ekka to 0.8.1.6

- apps/emqx_plugin_libs/src/emqx_trace/emqx_trace.erl
- apps/emqx_plugin_libs/src/emqx_trace/emqx_trace_api.erl
- apps/emqx_plugin_libs/test/emqx_trace_SUITE.erl
- test/emqx_trace_handler_SUITE.erl
1. ensure trace name be `[A-Za-z0-9-_]`,
2. if the start time is set earlier than the current time, it will cause the handler to not be created when the user views the trace file, so keep waiting until it is created successfully for one second.
3. find trace_file name not by string:prefix/2, to fix name crash
```erlang
021-12-06T14:39:44.703624+08:00 [error] GET /api/v4/trace/cluster_client_id/log error: 
{case_clause,{badrpc,{'EXIT',{{case_clause,["trace_cluster_client_id_2021-12-06.log",
"trace_cluster_client_id_122_2021-12-06.log"]},
[{emqx_trace_api,read_trace_file,3,[{file,"emqx_trace_api.erl"},{line,172}]}]}}}}, stacktrace:, 
```
> fix: trace_name format [A-Za-z0-9-_];retry if trace_file not find

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_metrics.erl
- apps/emqx/src/emqx_session.erl
- apps/emqx/test/emqx_channel_SUITE.erl
- apps/emqx_exhook/docs/design-cn.md
- apps/emqx_exhook/include/emqx_exhook.hrl
- apps/emqx_exhook/priv/protos/exhook.proto
- apps/emqx_exhook/src/emqx_exhook_handler.erl
- apps/emqx_exhook/src/emqx_exhook_server.erl
- apps/emqx_exhook/test/emqx_exhook_demo_svr.erl
- apps/emqx_exhook/test/props/prop_exhook_hooks.erl
- apps/emqx_gateway/src/mqttsn/emqx_sn_channel.erl
- apps/emqx_gateway/src/stomp/emqx_stomp_channel.erl
- apps/emqx_management/src/emqx_mgmt_api_metrics.erl
- apps/emqx_prometheus/src/emqx_prometheus.erl
This breaks compatibility for the plugins which hooks to the old name `session.takeovered`
> fix: typo takeovered -> takenover

- apps/emqx/src/emqx_channel.erl
Sessions must not enqueue messages when another process is taking over
the client id, since it already passed on the message queue in the
session state.
Without this fix, messages arriving after `{takeover, 'begin'} to a
channel with no connection (i.e., a persistent session) would be lost.
> fix(emqx_channel): fix race condition in session takeover

- apps/emqx_gateway/etc/emqx_gateway.conf.example
- apps/emqx_gateway/include/emqx_gateway_http.hrl
- apps/emqx_gateway/src/coap/emqx_coap_api.erl
- apps/emqx_gateway/src/emqx_gateway_api.erl
- apps/emqx_gateway/src/emqx_gateway_api_authn.erl
- apps/emqx_gateway/src/emqx_gateway_api_clients.erl
- apps/emqx_gateway/src/emqx_gateway_api_listeners.erl
- apps/emqx_gateway/src/emqx_gateway_conf.erl
- apps/emqx_gateway/src/emqx_gateway_http.erl
- apps/emqx_gateway/src/emqx_gateway_schema.erl
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_api.erl
- apps/emqx_gateway/test/emqx_coap_api_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_conf_SUITE.erl
- apps/emqx_gateway/test/emqx_lwm2m_api_SUITE.erl
Refactored the implementation of Gateway HTTP APIs:
1. Modify the coap/lwm2m API path from `/gateway/lwm2m/{clientid}` to `/gateway/lwm2m/clients/{clientid}`
2. Return the resource created/updated result
3. Rewrites the implementation of the swagger api using emqx_dasbhoard_swagger
> [Gateway] Standardize HTTP-APIs return value and Status/Error Code

- src/emqx_channel.erl
- src/emqx_cm.erl
- test/emqx_broker_SUITE.erl
When multiple clients try to connect concurrently using the same
client ID, they all call `emqx_channel:ensure_connected`, increasing
the live connection count, but only one will successfully acquire the
lock for that client ID.  This means that all other clients that
increased the live connection count will not get to call neither
`emqx_channel:ensure_disconnected` nor be monitored for `DOWN`
messages, effectively causing a count leak.
By moving the increment to `emqx_cm:register_channel`, which is only
called inside the lock, we can remove this leakage.
Also, during the handling of `DOWN` messages, we now iterate over all
channel PIDs returned by `eqmx_misc:drain_down`, since it could be
that one or more PIDs are not contained in the `pmon` state.
> fix(live_conn): fix live connection count on race condition

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/test/emqx_broker_SUITE.erl
Port from #6406 to 5.0.
When multiple clients try to connect concurrently using the same
client ID, they all call `emqx_channel:ensure_connected`, increasing
the live connection count, but only one will successfully acquire the
lock for that client ID.  This means that all other clients that
increased the live connection count will not get to call neither
`emqx_channel:ensure_disconnected` nor be monitored for `DOWN`
messages, effectively causing a count leak.
By moving the increment to `emqx_cm:register_channel`, which is only
called inside the lock, we can remove this leakage.
Also, during the handling of `DOWN` messages, we now iterate over all
channel PIDs returned by `eqmx_misc:drain_down`, since it could be
that one or more PIDs are not contained in the `pmon` state.
> fix(live_conn): fix live connection count on race condition (5.0)

- apps/emqx_bridge/etc/emqx_bridge.conf
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_app.erl
- apps/emqx_bridge/src/emqx_bridge_http_schema.erl
- apps/emqx_bridge/src/emqx_bridge_mqtt_schema.erl
- apps/emqx_bridge/src/emqx_bridge_schema.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_connector/src/emqx_connector_api.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/emqx_connector_schema.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
> Improve bridge and connector APIs

- scripts/update_appup.escript
Same as #6307 .
Currently, the update_appup.escript outputs as an error the full appup
file for external dependencies, even if all the changes are already
contained in the depency. Here, we make it only output the missing
actions to be inserted, to aid in seeing what are the differences.
> chore(appup): make update_appup.escript output only differences for external dependencies [5.0]

- deploy/charts/emqx/templates/ingress.yaml
Hi, I think main-v4.3 has not adapted to different kubectl version, here is the changes.
> chore: fix main-v4.3 support for networking.k8s.io/v1

- apps/emqx/rebar.config
- apps/emqx/test/emqx_listeners_SUITE.erl
- rebar.config
Do not merge, we'll change `savonarola/cowboy` to `emqx/cowboy` before merge.
> [5.0] fix(wss): update cowboy & ranch for OTP24 compatibility

- apps/emqx_authn/src/emqx_authn_schema.erl
- apps/emqx_connector/src/emqx_connector_http.erl
* simplify authn root type doc.
The `authentication` root config is an array, when it's a single-element array, the wrapping `[]` can be omitted,
so schema was `union([union([...]), array(union[...]))`, which makes the generated doc quite bloated with repeated information. This PR has the wrapping union removed, so it always appears to be an array in the config doc.
The special rule for single-element array is explained in the description
* the `request` root key now has a namespace: `connector-http:request`, just for documentation purpose.
> docs: better config doc

- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
<module> is treated as an HTML tag
> docs: change <module> to {module} so markdown render will not crash

- apps/emqx_lwm2m/rebar.config
- rebar.config.erl
`ssl:ssl_accept/1,2` is removed by OTP 24
> OTP 24 warnings ssl

- apps/emqx_authz/include/emqx_authz.hrl
- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_authz/src/emqx_authz_api_mnesia.erl
- apps/emqx_authz/src/emqx_authz_app.erl
- apps/emqx_authz/src/emqx_authz_http.erl
- apps/emqx_authz/src/emqx_authz_mnesia.erl
- apps/emqx_authz/src/emqx_authz_rule.erl
- apps/emqx_authz/test/emqx_authz_api_mnesia_SUITE.erl
- apps/emqx_authz/test/emqx_authz_mnesia_SUITE.erl
* Eliminate type and record sharing through `emqx_authz.hrl`.
* Hide all mria/mnesia interactions inside mnesia authz backend.
> refactor(authz): hide mnesia authz implementation details

- apps/emqx/src/emqx_config.erl
- apps/emqx_dashboard/src/emqx_dashboard_admin.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_api_SUITE.erl
If the rpc in `emqx_dashboard_monitor_api:get_collect/1` fails, an
empty map is return.  But the current function expects a 4-tuple,
which results in a 500 error returned on such occasions.
```
curl -su admin:public localhost:8888/api/v5/monitor/current | jq .
{
"code": "INTERNAL_ERROR",
"message": "error, function_clause, [{emqx_dashboard_monitor_api,format_current_metrics,[[#{},{0,0,0,0},{0,0,0,0}],{0,0,0,0}],[{file,\"emqx_dashboard_monitor_api.erl\"},{line,179}]},{emqx_dashboard_monitor_api,current_counters,2,[{file,\"emqx_dashboard_monitor_api.erl\"},{line,167}]},{minirest_handler,apply_callback,3,[{file,\"minirest_handler.erl\"},{line,112}]},{minirest_handler,init,2,[{file,\"minirest_handler.erl\"},{line,38}]},{cowboy_handler,execute,2,[{file,\"cowboy_handler.erl\"},{line,41}]},{cowbo …
```
> fix(monitor): fix return value on badrpc

- apps/emqx/test/emqx_misc_SUITE.erl
Fix:
```bash
%%% emqx_misc_SUITE ==> t_drain_down: FAILED
%%% emqx_misc_SUITE ==> 
Failure/Error: ?assertEqual([<0.30740.1>,<0.30741.1>], emqx_misc : drain_down ( 2 ))
expected: [<0.30740.1>,<0.30741.1>]
got: [<0.30741.1>,<0.30740.1>]
line: 110
```
> fix: misc_SUITE:t_drain_down sometimes fails

- apps/emqx_bridge/etc/emqx_bridge.conf
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_http_schema.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_connector/src/emqx_connector_api.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_mod.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_msg.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_rule_engine/include/rule_engine.hrl
- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
```
type = ingress
{
name = "foo"
connector = "mqtt:my_mqtt_connector"
direction = ingress
remote_topic = "t/#"
remote_qos = 1
local_topic = "from_aws/${topic}"
local_qos = 1
retain = true
payload = "${payload}"
}
type = egress
{
name = "foo"
connector = "mqtt:my_mqtt_connector"
direction = egress
local_topic = "emqx/#"
remote_topic = "from_emqx/${topic}"
remote_qos = 1
retain = true
payload = "${payload}"
}
```
> fix(connector): add type and name in repsonse of GET /connectors

- apps/emqx_bridge/etc/emqx_bridge.conf
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_app.erl
- apps/emqx_bridge/src/emqx_bridge_http_schema.erl
- apps/emqx_bridge/src/emqx_bridge_mqtt_schema.erl
- apps/emqx_bridge/src/emqx_bridge_schema.erl
- apps/emqx_connector/src/emqx_connector_api.erl
- apps/emqx_connector/src/emqx_connector_http.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_mod.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_instance.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- apps/emqx_rule_engine/include/rule_engine.hrl
- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
> fix(connector): some desc for connector APIs

- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_gateway/src/emqx_gateway_api_listeners.erl
- apps/emqx_management/src/emqx_mgmt_api_banned.erl
fix ban utf8 clientid crash by 500 response.
swagger support form-data(file upload).
> fix(banned): create banned with utf8 failed by 500 response

- rebar.config
Diff: https://github.com/k32/system_monitor/commit/3b4b381bf9503695cd764ecf22067ac6542cee89
EMQX is expexted to have millions of processes, so this warning makes little sense. Also removed the other warning from the list, we can add it back if needed.
> fix(system_monitor): Fix warning spam

- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
> Fix rule api swagger

- apps/emqx/src/emqx_channel.erl
- apps/emqx/test/emqx_channel_SUITE.erl
As described in the 5.0 specification, we should disconnect clients that
exceed the receive-maximum limit.
> If it receives more than Receive Maximum QoS 1 and QoS 2 PUBLISH packets
where it has not sent a PUBACK or PUBCOMP in response, **the Server uses a
DISCONNECT packet with Reason Code 0x9**
fix: #6447
> fix: disconnect the client due to exceed receive-maximum packets

- bin/emqx
This PR include fixes for following 2 issues:
**1. Starting emqx fails with `unbound variable` error:**
```
[root@xmeter-controler emqx]# ./bin/emqx start
./bin/emqx: line 207: LD_LIBRARY_PATH: unbound variable
```
The emqx is installed from a zip ball, and openssl-1.1.1 is not installed on the node.
Only emqx-5.0 has this issue, because we set the `-u` option (treat unset variables as errors) at the beginning of the boot script `./bin/emqx`. But in previous versions, `-u` is not set.
**2. Starting emqx fails but it shows `EMQ X Community Edition 5.0-beta.2-7faf2512 is started successfully!` (After I fixed the above problem)**
```
[root@xmeter-controler emqx]# ./bin/emqx start
EMQ X Community Edition 5.0-beta.2-7faf2512 is started successfully!
[root@xmeter-controler emqx]# ./bin/emqx …
```
> fix(boot_script): LD_LIBRARY_PATH: unbound variable

- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_authz/src/emqx_authz_file.erl
- apps/emqx_authz/src/emqx_authz_http.erl
- apps/emqx_authz/src/emqx_authz_mnesia.erl
- apps/emqx_authz/src/emqx_authz_schema.erl
- apps/emqx_authz/test/emqx_authz_SUITE.erl
- apps/emqx_authz/test/emqx_authz_file_SUITE.erl
- apps/emqx_authz/test/emqx_authz_http_SUITE.erl
- apps/emqx_authz/test/emqx_authz_http_test_server.erl
- apps/emqx_authz/test/emqx_authz_mnesia_SUITE.erl
- apps/emqx_authz/test/emqx_authz_mysql_SUITE.erl
- apps/emqx_authz/test/emqx_authz_postgresql_SUITE.erl
- apps/emqx_authz/test/emqx_authz_redis_SUITE.erl
- apps/emqx_authz/test/emqx_authz_test_lib.erl
* HTTP authorization url parameter is split into base_url, path and query parameters. This is needed because previously used emqx_http_lib:uri_parse/1 cannot parse template strings, like http://domain.com/${username}?clientid=${clientid}. Tests with real backend added to cover the logic.
* Test file-based authorization.
* Test mnesia authz with more examples.
> Test HTTP, Mria, File authorization

- scripts/update_appup.escript
It is suggested to the review to read this PR by commit.
This change makes the `update_appup.escript` check whether the new
version of an application (the _current_ one) is already contained in
entries in the _new_ .appup file for that application if such .appup
file contains regexes.
NOTE: this does not cover the case in which we calculate the
difference between _old_ and _new_ appup entries, and those consist of
regexes.  In such case, we would need to check if one regex is
"contained" in the other, which is not currently supported by this
patch.
Since the appup instruction `restart_application` already loads all
modules of a given application, there is no need to introduce those
instructions if a restart is already present.
To avoid losing comments and/or manual indentation in appup …
> chore(update_appup): Improve `update_appup.escript`

- bin/install_upgrade.escript
The `install_upgrade.escript` depended on being able to retrieve the
`vm_args` argument from `init`, but that options has been removed
recently.  Since this backup was unused, we also remove it here.
Also, the `cuttlefish` script reference is removed, since it is no longer 
present in the release.
> fix(bin_emqx): remove `vm_args` backup in `install`

- scripts/update_appup.escript
Port of #6480 .
* Make the script regex-aware
This change makes the `update_appup.escript` check whether the new
version of an application (the _current_ one) is already contained in
entries in the _new_ .appup file for that application if such .appup
file contains regexes.
* Do not use `load_module` instructions if `restart_application` is present
Since the appup instruction `restart_application` already loads all
modules of a given application, there is no need to introduce those
instructions if a restart is already present.
* Do not force `.appup.src` render if contents are the same
To avoid losing comments and/or manual indentation in appup files that
are already up to date, we now check whether the contents have the
exact same terms as those we are about to write to an existint …
> chore(update_appup): Improve `update_appup.escript` (5.0)

- apps/emqx/src/emqx_schema.erl
Currently, there's [code](https://github.com/emqx/emqx/blob/048afa6d2d693f6c53e8103fa132362c5915e641/apps/emqx/src/emqx_shared_sub.erl#L270-L279) and tests that expect the possibility of
values `sticky`, `hash_topic` and `hash_clientid` in the
`node.shared_subscritpion_strategy` configuration, but the schema enum
does not contain those constructors.
There's also a `hash` constructor expected, but apparently it's just for backwards compatibility (same as `hash_clientid`), so maybe we can skip it in 5.0
> fix(config): add missing enum constructors for `shared_subscription_strategy`

- .github/stale.yml
This adds configuration for
[stalebot](https://github.com/probot/stale) to track our stale issues.
https://github.com/apps/stale
> ci(stalebot): stalebot initial configuration

- .ci/build_packages/tests.sh
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- scripts/buildx.sh
Two changes
1. The package test script tests.sh is refactored to accept arguments to know which exact package to test
instead of finding ALL packages in `_packages/$EMQX_NAME` directory,
because when testing locally, it's very much the case that the _packages directory is not clean
1. `scripts/buildx.sh` was added in previous PR in order to make it easier to test cross-platform builds elsewhere (not just in github CI). This PR is to make use of this script in CI too
> build: ci tests.sh test specific package

- .github/workflows/stale.yaml
We are interested in using stale actions only for issues, and
currently there's no clear/clean way of making it not enumerate pull
requests.  As a workaround, we attempt to minimize the number of
operations spent on pull requests by making it run only on pull
requests which have an inexistent tag, thus skipping all PRs.
> ci(stale): avoid spending operations on pull requests

- Makefile
'compile' is implict dependent step for 'release'
> build: remove 'compile' step before 'release'

- .ci/docker-compose-file/scripts/run-emqx.sh
- bin/emqx
- pkg-vsn.sh
- scripts/find-props.sh
- scripts/find-suites.sh
- scripts/shellcheck.sh
Since we started to use the portable shebang style for our scripts, we
need to update the pattern used to find scripts for Shellcheck to
check.
> fix(ci): fix shellcheck file pattern

- NOTICE
- apps/emqx/NOTICE
- apps/emqx_exhook/priv/protos/exhook.proto
- apps/emqx_gateway/src/exproto/protos/exproto.proto
- apps/emqx_rule_engine/README.md
- scripts/update-copyright-years.sh
* Fixed the match pattern from `"%% Copyright.."` to `".*Copyright..."` to include proto files and NOTICE
* Refactored the fix function to accept any file as input so we can fix NOTICE
> chore: fix copyright update script to include more files

- .github/workflows/elixir_release.yml
- apps/emqx/include/emqx_release.hrl
- apps/emqx_authn/rebar.config
- apps/emqx_authz/rebar.config
- apps/emqx_prometheus/rebar.config
- apps/emqx_statsd/rebar.config
Elixir requires that we use version of the form `Major.Minor.Patch`.
Also, Mix requires dependecies to be declared in `rebar.config` so it
can include the header files correctly.
> fix(elixir): put Patch in version and add missing deps

- apps/emqx_exhook/src/emqx_exhook_mgr.erl
Warning during release build:
```
===> Assembling release emqx-5.0.0-beta.2-f68d574a...
===> There are missing function calls in the release.
===> Make sure all applications needed at runtime are included in the release.
===> emqx_exhook_mgr:pre_config_update/3 calls undefined function ct:pal/2
```
> fix: rm unknown call (`ct:pal`)

- bin/emqx
This is to make it behave the same as older versions
> chore: emqx stop prints ok after stop

- apps/emqx_management/test/emqx_mgmt_api_alarms_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_app_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_banned_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_metrics_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_nodes_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_routes_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_stats_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
In order to match the source file and SUITE file:
such as 
`emqx_mgmt_api_banned.erl`'s SUITE should be `emqx_mgmt_api_banned_SUITE.erl` instead of `emqx_mgmt_banned_api_SUITE.erl`
> chore(test): rename mgmt_xxx_api_SUITE to mgmt_api_xxx_SUITE

- .github/workflows/run_fvt_tests.yaml
Edge edition is running as single node.
> ci: exclude edge + rlog test

- rebar.config
backported from 5.0
race_condition check is very RAM demanding
> ci: skip dialyzer race_condition checks

- .ci/build_packages/tests.sh
NOTE: this typo did not cause anything other than a false message
about a missing file.
> ci: fix a typo in tests.sh

- bin/emqx
* refine usage print
* deleted restart command, as it only works for daemon mode.
e.g. if EMQ X is started in 'foreground' mode the 'restart'
command will make it start in daemon mode
* some commands such as ertspath does not requre RPC
New usage
```
Usage: emqx COMMAND [help]
Commonly used COMMANDs:
start:      Start EMQ X in daemon mode
console:    Start EMQ X in an interactive Erlang or Elixir shell
foreground: Start EMQ X in foreground mode without an interactive shell
stop:       Stop the running EMQ X node
ctl:        Administration commands, execute 'emqx ctl help' for more details
More:
Shell attach:  remote_console | attach
Up/Down-grade: upgrade | downgrade | install | uninstall
Install info:  ertspath | root_dir | versions | root_dir
Runtime info:  pid | ping | versions …
```
> refactor(bin/emqx): refine help info

- .github/workflows/build_packages.yaml
- The docker img use os: alpine, it is unliked to hit a cache.
- The build cache method casue the tag get overwritten among multi
arch builds
> ci(cross-build-package): revert build cache for docker img

- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
only cache otp installation instead of the entire kerl dir to save cache spaces.
reduce cache size from 259M to 44M
with cache hit, mac build time is reduced from 24mins to 8mins
> ci(mac): cache otp install only

- .ci/build_packages/tests.sh
- .ci/fvt_tests/relup.lux
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/run_api_tests.yaml
- .github/workflows/run_relup_tests.yaml
- Makefile
- bin/emqx
- bin/install_upgrade.escript
- build
- deploy/packages/deb/debian/control
- deploy/packages/rpm/emqx.spec
- scripts/buildx.sh
- scripts/update_appup.escript
the reason why EMQ X packages were released in .zip but not .tar.gz is lost.
maybe it was Windows, now that `tar` command comes natively in Windows, it's no longer a strong argument.
due to the .zip legacy, we had to re-pack the .tar.gz package generated by rebar release to .zip when releasing
and when upgrading, we had to re-pack .zip to .tar.gz because OTP release handler does not work with .zip
starting from 5.0, we'll aim to release .tar.gz packages instead.
> refactor: build tar gz instead of zip

- apps/emqx/include/logger.hrl
- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
- apps/emqx/src/emqx_trace/emqx_trace_handler.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_jwks_connector.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_mongodb.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_mysql.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_pgsql.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl
- apps/emqx_authz/src/emqx_authz_mongodb.erl
- apps/emqx_authz/src/emqx_authz_mysql.erl
- apps/emqx_authz/src/emqx_authz_postgresql.erl
- apps/emqx_authz/src/emqx_authz_redis.erl
1. Add more detail log when authn/authz query error(locate the problem faster).
2. Don't log error when authn_redis query result is empty.
3. Always debug when tracing.
> Improve authn/authz error log when query failed.

- Makefile
- build
With dashboard version 0.18.0, the config doc markdown file can be rendered in the dashboard page
The rendering is still very primitive for now.
More CSS will be added by @ysfscream in future iterations of the dashboard
In-page references are not working for now. will be fixed.
preview:
> feat: show config doc in dashboard

- .github/workflows/run_fvt_tests.yaml
- build
- The command `find _upgrade_base -maxdepth 1 -name "*$PROFILE-otp${OTP_VSN}-$SYSTEM*-$ARCH.zip" -type f` failed to find the zip balls, because the format of the filename should be `${PROFILE}-${PKG_VSN}-otp${OTP_VSN}-${SYSTEM}-${ARCH}.zip`.
- Run `make emqx-zip` multiple times will fail because `cp -r -n` returns 1 if one of the target files already exists.
> fix(build): make emqx-zip failed on making relup file

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_data_backup.erl
- apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE.erl
Auth ACL data have different data structures in different versions:
It is difficult to confirm the data's format of the specific version, 
so it is better for the code not to determine what the data structure is by version, 
but to import different formats according to the different data structures.
```
```
> fix(auth_mnesia): import auth acls data according to different data format

- Makefile
- scripts/ensure-rebar3.sh
The defination of `#application{}` record in systools.hrl is changed in OTP 24.
So we need a rebar3 binary compiled with OTP 24.
> fix(build): relup for otp24 failed

- .github/workflows/build_packages.yaml
`git tag -l "v$pre_vsn.[0-9]"` only matches 1 digit 
the new build has:
`OLD_VSNS: v4.3.0 v4.3.1 v4.3.10 v4.3.11 v4.3.2 v4.3.3 v4.3.4 v4.3.5 v4.3.6 v4.3.7 v4.3.8 v4.3.9`
> ci: fix base version match pattern

- .ci/build_packages/tests.sh
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/run_broker_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_relup_tests.yaml
- Makefile
- apps/emqx/include/emqx_release.hrl
- apps/emqx/src/emqx_release.erl
- build
- mix.exs
- pkg-vsn.sh
- rebar.config.erl
- scripts/buildx.sh
We'll likely have to release CE and EE with different git tag schemes (on the same branch).
The least we want is to create another branch for EE release (which would mean there is essentially no difference comparing to the old time when we had two repos), because that's when the code base starts to diverge and becomes hard to trace the changes.
e.g.
`v5.0.0` for CE
`e5.0.0` for EE
> build: parameterise package vsn

- apps/emqx_authn/src/emqx_authn_utils.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_http.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_mongodb.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_mysql.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_pgsql.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl
- apps/emqx_authn/test/emqx_authn_pgsql_SUITE.erl
- apps/emqx_authz/src/emqx_authz_api_sources.erl
- apps/emqx_authz/src/emqx_authz_http.erl
- apps/emqx_authz/src/emqx_authz_mongodb.erl
- apps/emqx_authz/src/emqx_authz_mysql.erl
- apps/emqx_authz/src/emqx_authz_postgresql.erl
- apps/emqx_authz/src/emqx_authz_redis.erl
- apps/emqx_authz/src/emqx_authz_utils.erl
- apps/emqx_authz/test/emqx_authz_http_SUITE.erl
- apps/emqx_authz/test/emqx_authz_redis_SUITE.erl
- apps/emqx_plugin_libs/src/emqx_placeholder.erl
- apps/emqx_plugin_libs/test/emqx_placeholder_SUITE.erl
Almost each authn/authz backend reimplements placeholder substitution. This eliminates code duplication.
> refactor(authn,authz): unify variable interpolation

- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.erl
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia_cli.erl
- src/emqx_os_mon.erl
- src/emqx_vm_mon.erl
Watermark use `>` `<` to check condition.
the `sysmem_high_watermark` is checked with `>` `<` https://github.com/erlang/otp/blob/master/lib/os_mon/src/memsup.erl#L392-L396
Need to unify the watermark check standard, PS: the dashboard UI also use > <
```bash
os_mon.cpu_high_watermark = 80%
os_mon.cpu_low_watermark = 60%
os_mon.sysmem_high_watermark = 70%
os_mon.procmem_high_watermark = 5%
vm_mon.process_high_watermark = 80%
vm_mon.process_low_watermark = 60%
```
> fix(alarm): watermark replace >= =< with > <

- .github/workflows/run_api_tests.yaml
- apps/emqx_modules/etc/emqx_modules.conf
- apps/emqx_modules/src/emqx_event_message.erl
- apps/emqx_modules/src/emqx_modules_schema.erl
- apps/emqx_modules/test/emqx_event_message_SUITE.erl
Dollar sign is used for map types.
Doc will be confusing
> refactor: remove dollar sign from config fields

- .ci/build_packages/tests.sh
build_packages.yaml
-name: build emqx packages
```
creating: emqx/dynlibs/
3741
inflating: emqx/dynlibs/libtinfo.so.6  
3742
inflating: emqx/dynlibs/libcrypto.so.1.1  
3743
+ ./emqx/bin/emqx start
3744
+ ./emqx/bin/emqx_ctl status
3745
EMQ X Enterprise 4.4.0 is started successfully!
3746
Node 'emqx@127.0.0.1' 4.4.0 is started
3747
+ ./emqx/bin/emqx versions
3748
Installed versions:
3749
* 4.4.0	permanent
3750
3751
+ cp '/emqx/_packages/emqx-ee/emqx-ee-*-4.4.0-a6d2367f-amd64.zip' ./emqx/releases
3752
cp: cannot stat '/emqx/_packages/emqx-ee/emqx-ee-*-4.4.0-a6d2367f-amd64.zip': No such file or directory
3753
Error: Process completed with exit code 1.
```
> fix(CI): build packages failed on release upgrade testing

- apps/emqx_dashboard/etc/emqx_dashboard.conf
- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_dashboard/src/emqx_dashboard_app.erl
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
- apps/emqx_prometheus/rebar.config
- mix.exs
- rebar.config
Fix the: https://github.com/emqx/emqx/pull/5198
Allow to configure listening address in dashboard.
> feat(dashboard): support bind specific ip(port or ip:port).

- .github/workflows/build_slim_packages.yaml
- .github/workflows/check_deps_integrity.yaml
- .github/workflows/elixir_apps_check.yaml
- .github/workflows/elixir_deps_check.yaml
- .github/workflows/run_api_tests.yaml
- .github/workflows/run_broker_tests.yaml
- .github/workflows/run_emqx_app_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_relup_tests.yaml
- .github/workflows/run_test_cases.yaml
- .github/workflows/shellcheck.yaml
- Secure tests on master branch after merge.
- Improve build cache hit rates
Due to security reason, github only allow reuse cache from
- same branch
- base branch
- default branch
Branch Feature-A could not reuse the cache from Feature-B
- Developers could run the workflow in their own forked repo before make the PR, this could relieve the runners on upstream repo
> ci: enable ci tests on pushes.

- .github/workflows/elixir_release.yml
- .github/workflows/run_fvt_tests.yaml
- Makefile
- build
- deploy/docker/Dockerfile
- mix.exs
- rebar.config.erl
- scripts/check-elixir-applications.exs
Instead of reading some enviroment variables to define the build profile for the Elixir build, we use the MIX_ENV value to emulate Rebar3's profiles.  Also, that makes the build output directory more similar to EMQ X's current scheme.
> chore(mix): use MIX_ENV to define build profile and edition

- .github/workflows/build_packages.yaml
- scripts/buildx.sh
- scripts/docker-create-push-manifests.sh
- use self-hosted aws arm64 runners in cross build jobs
- don't build raspbian10 for arm64 since base image is arm32
- create docker image manifest locally for multi-arch image and push to docker hub
- rocksdb/quicer build cache for docker image build
> ci: use aws arm64 runner in cross build jobs

- .github/workflows/build_packages.yaml
- build
- scripts/get-distro.sh
> ci: remove centos8 support

- .github/workflows/run_fvt_tests.yaml
Often, the Helm FVT tests would start while the listener was not ready, resulting in a spurious failure.
> fix(flaky_test): improve helm test preparation check

- .ci/docker-compose-file/python/pytest.sh
After a major version release (7.0.0), our current FVT tests all
failed due to some change in the lib.  Our pytest version in CI was
not pinned, and picked this update up.
> ci(pytest): pin pytest version at 6.2.5

- build
Currently, `emqx_release.erl` depends on the `erl_opts` option
`compile_info` being set by Rebar3 to include `{emqx_vsn, $PKG_VSN}`
to report the version, for instance, in `emqx ctl status`.
Since Mix does not provide a simple way to pass `erl_opts` to Rebar3
dependencies without creating a `mix.exs` file, the workaround is to
set the environment variable `ERL_COMPILER_OPTIONS` to include that
value before invoking the Erlang compiler on the Rebar3 dependencies.
> fix(mix): set `emqx_vsn` compile info

- .ci/docker-compose-file/python/pytest.sh
Port: https://github.com/emqx/emqx/pull/6920/
> ci(pytest): pin pytest version at 6.2.5.

- apps/emqx/etc/emqx_cloud/vm.args
- apps/emqx/etc/emqx_edge/vm.args
- apps/emqx/src/emqx_listeners.erl
- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_machine/src/emqx_machine_app.erl
- apps/emqx_machine/src/emqx_restricted_shell.erl
- apps/emqx_machine/src/user_default.erl
- apps/emqx_machine/test/emqx_restricted_shell_SUITE.erl
1. Add `user_default.erl` to import record defined from `*hrl`.
2. Don't allow danger function execute in shell, such as `init:stop,q, halt`
3. Add log when shell process's heap_size/args_size is too huge.
4. update dashboard listener prompt.
```shell
Listener quic:default on :14567 started.
Listener ssl:default on :8883 started.
Listener tcp:default on :1883 started.
Listener ws:default on :8083 started.
Listener wss:default on :8084 started.
Start listener dashboard:http:18083 on :18083 successfully.
```
```erlang
log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:8] [async-threads:4] [jit]
Listener quic:default on 0.0.0.0:14567 started.
Listener ssl:default on 0.0.0.0:8883 started.
Listener tcp:default …
```
> feat(shell): add restricted shell and user_default

- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
Tests decoupled by performing proper setup during test suites.
Fixed some typos.
Changed the default usernames per test suite so there is no accidental coupling between tests in the future.
> fix: decouple suite tests

- apps/emqx/src/emqx_ctl.erl
- apps/emqx/test/emqx_ctl_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_cli_SUITE.erl
Without passing an empty argument list to `emqx_ctl:print`, formatting
instructions like `~n` are being printed literally.
```
Ignore.~nJoin the cluster successfully.~nCluster status: #{running_nodes =>
['emqx@emqx-0.int.thalesmg','emqx@emqx-1.int.thalesmg',
'emqx@emqx-2.int.thalesmg','emqx@emqx-3.int.thalesmg',
'emqx@emqx-4.int.thalesmg'],
stopped_nodes => []}
```
> fix(ctl): fix formatting when printing messages without arguments

- src/emqx_message.erl
The log message after this change:
```
2022-02-10T10:14:53.325313+08:00 [warning] abc@127.0.0.1:57923 [Session] Dropped msg due to mqueue is full: Message(Id=0005D7A083FD3D11F443000007C10001, QoS=0, Topic=t/1, From=<<"123">>, Flags=[nl], Headers=#{peerhost => {127,0,0,1}, properties => #{},proto_ver => 4,protocol => mqtt,username => <<"123">>})
```
> fix(log): format the message id to hexstring before printing

- CHANGES-4.3.md
- rebar.config
print client status before killing due to holding lock for too long
> [4.3] Upgrade to ekka 0.8.1.8

- apps/emqx/src/emqx_channel.erl
- apps/emqx/test/emqx_channel_SUITE.erl
> fix(channel): wrong case clause when alias is inexistent (5.0)

- apps/emqx/src/emqx_config_handler.erl
- apps/emqx/src/emqx_misc.erl
- apps/emqx_authz/src/emqx_authz_file.erl
- apps/emqx_authz/test/emqx_authz_file_SUITE.erl
- apps/emqx_conf/include/emqx_conf.hrl
- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf_cli.erl
- lib-ee/emqx_license/src/emqx_license.erl
- lib-ee/emqx_license/src/emqx_license_parser.erl
- lib-ee/emqx_license/src/emqx_license_parser_v20220101.erl
- lib-ee/emqx_license/test/emqx_license_SUITE.erl
- lib-ee/emqx_license/test/emqx_license_parser_SUITE.erl
- scripts/buildx.sh
* Simplified emqx_license parser error list return value
* Catch badmatch exception and turn it into an error return so the license key is not logged
* Treat config change `throw`s as `{error, Reason}` returns, no need to log stacktrace
* `cluster_rpc` should not log arguments as it might contain senstive information
* Deleted `cluster_rpc` alarm description because it's duplicated information as in metadata
license update error log example:
```
2022-02-08T19:31:35.673205+01:00 [error] entrypoint: <<"emqx:update_config/3">>, line: 384, mfa: emqx_cluster_rpc:log_and_alarm/3, msg: cluster_rpc_apply_failed, result: {error,[{emqx_license_parser_v20220101,bad_license_format}]}, tnx_id: 7
2022-02-08T19:31:35.673959+01:00 [warning] line: 338, message: <<"cluster_rpc_apply_failed=7">>, mfa: …
```
> refactor: treat throw exception as `{error, Reason}` return

- .github/workflows/build_packages.yaml
for some reason Get-FileHash (or maybe later piped tools) produced
non-text content
> ci: fix sha256sum in windows

- .github/workflows/build_packages.yaml
include is unconditional, as a result, it brins in emqx profile
to enterprise repo
> ci: use exclude instead of include for build matrix

- apps/emqx/src/emqx_os_mon.erl
- apps/emqx/src/emqx_vm_mon.erl
- apps/emqx/test/emqx_os_mon_SUITE.erl
Fix high memory alarm sometimes not activate when reboot.
Port from v4.3: https://github.com/emqx/emqx/pull/6883
> fix(watermark): watermark should use > instead of >=

- .github/workflows/build_packages.yaml
- build
- scripts/get-distro.sh
e.g. `emqx-4.4.0-otp24.1.5-3-el7-amd64.zip`
background: we have previously renamed `centos` to `rhel` when we replaced the centos8 build with rockylinux8.
reason for this change: rh is short for 'redhat', although it's rhel used internally in the etc/*-release files, it seems more common to name packages with `el7` and `el8`.
> build: rename distro from 'rhel' to 'el'

- apps/emqx_modules/src/emqx_event_message.erl
port from v4.3: https://github.com/emqx/emqx/pull/6822
> feat(event): add `connected_at` into client_disconnected event

- CHANGES-4.3.md
- src/emqx.app.src
- src/emqx.appup.src
- src/emqx_channel.erl
- test/emqx_channel_SUITE.erl
> fix(channel): wrong case clause when alias is inexistent

- pkg-vsn.sh
- scripts/find-props.sh
- scripts/find-suites.sh
- scripts/relup-base-packages.sh
- scripts/relup-base-vsns.sh
- scripts/shellcheck.sh
changed from
`../scripts/relup-base-vsns.sh community`
to
`../scripts/relup-base-vsns.sh $EDITION`
also some shellcheck fixes.
> 4.3 fix upgrade base package download

- scripts/get-otp-vsn.sh
This script got `W` as the OTP_VSN, I suspect it is because the script is evaluated using a shell other than bash.
```
#!/usr/bin/env escript
%% Rebar3 3.18.0-emqx-1
/c/Program Files/erl-23.0/bin/rebar3
OTP_VSN: W
rebar3 3.18.0-emqx-1 already exists
escript: exception error: undefined function rebar3:main/1
in function  escript:run/2 (escript.erl, line 758)
in call from escript:start/1 (escript.erl, line 277)
in call from init:start_em/1 (init.erl, line [112](https://github.com/emqx/emqx/runs/5226132461?check_suite_focus=true#step:6:112)3)
in call from init:do_boot/3 (init.erl, line 831)
mingw32-make: *** [Makefile:81: emqx] Error 127
```
> fix(build): change header of shell script to "#!/usr/bin/env bash"

- apps/emqx_management/src/emqx_mgmt_api_nodes.erl
This PR removes the `config_path` node info from management API response.
it's not displayed on the dashboard, and it's wrong info because log dir is not always relative to `file:get_cwd`
also some rephrasing for other fields.
> Refactor: mgmt api node info

- bin/install_upgrade.escript
for remsh prefixed nodes, ekka pick a random port to listen on
instead of following the conventional port mapping rule:
ekka listens on 4370 for emqx or emqx0 and 4371 for
emqx1 and so on
> chore: ensure remsh node name prefix for upgrader

- bin/install_upgrade.escript
for remsh prefixed nodes, ekka pick a random port to listen on
instead of following the conventional port mapping rule:
ekka listens on 4370 for emqx or emqx0 and 4371 for emqx1 and so on
> chore: ensure remsh prefix for remote nodes

- .ci/build_packages/tests.sh
- .gitattributes
- .github/workflows/build_packages.yaml
- Makefile
- bin/install_upgrade.escript
- build
- deploy/packages/deb/Makefile
- deploy/packages/rpm/Makefile
- include/emqx_release.hrl
- lib-ce/emqx_dashboard/src/emqx_dashboard.app.src
- scripts/ensure-rebar3.sh
- scripts/find-apps.sh
- scripts/get-distro.sh
- scripts/pkg-full-vsn.sh
* fix various issues for windows build
- find command clash with window's find
- zip command not found, changed to use 7z so we do not have use powershell apis
- absolute paths are tricky to work with in windows, so the make_zip is changed to use relative path 
* added a `scripts/get-full-vsn.sh` to print out the full version string like `4.4.0-otp24.1.5-4-el8-amd64`.
* fixed windows upload artifacts upload group
* changed to create .sha256 immediately when building packages
> build: fix windows build

- Makefile
- build
- scripts/find-apps.sh
windows has its own find command
This PR is based on tag `v4.3.12`, so it can be forward-merged to `v4.4.0` for fixing windows build
> build: fix find command for windows

- bin/node_dump
> fix(node_dump): Don't collect information about modules

- apps/emqx/rebar.config.script
- rebar.config.erl
Some dependencies, like `bcrypt` and `quic`, have their references
declared as `branch`, yet there are no branches with those names, but
tags.  Despite rebar3 managing somehow to handle that, if a project
managed by Mix tries to declare EMQX as its dependency, it's not able
to fetch those dependencies.
```
$ mix deps.get
* Updating emqx (https://github.com/emqx/emqx - v5.0-beta.3)
* Updating lc (https://github.com/qzhuyan/lc.git - 0.1.2)
* Updating gproc (https://github.com/uwiger/gproc - 0.8.0)
* Updating typerefl (https://github.com/k32/typerefl - 0.8.6)
* Updating jiffy (https://github.com/emqx/jiffy - 1.0.5)
* Updating cowboy (https://github.com/emqx/cowboy - 2.9.0)
* Updating esockd (https://github.com/emqx/esockd - 5.9.0)
* Updating ekka (https://github.com/emqx/ekka - 0.11.1)
* …
```
> fix(deps): use tags for dependencies

- apps/emqx/test/emqx_hooks_SUITE.erl
Failing when duplicate elements were being generated.
```
An exception was raised: error:{assertEqual,
[{module,emqx_hooks_SUITE},
{line,65},
{expression,"Order"},
{expected,
[{5,'',''},
{5,'',''},
{4,'\223',''},
{2,'}Ijrµ\036',''}]},
{value,
[{5,'',''},
{4,'\223',''},
{2,'}Ijrµ\036',''}]}]}.
```
> test(fix): fix flaky prop

- .ci/fvt_tests/relup.lux
- CHANGES-4.3.md
- bin/install_upgrade.escript
```
./bin/emqx install 4.4.1
unzip ["releases/emqx-ee-4.4.1-otp23.2.5-macos12-amd64.zip"]
escript: exception error: no case clause matching {error,eexist}
```
> fix(relup): release upgrade failed on symlink already exists

- apps/emqx/src/emqx_os_mon.erl
- apps/emqx/src/emqx_sys.erl
1. Refactor uptime/0 function: no longer dependent on emqx_sys process.
Possible problems with previous implementations: if emqx_sys process restarts, the uptime is incorrect.
2. Don't cache version in emqx_sys process, otherwise, the version is incorrect after the upgrade.
3. fix wrong usage of `memsup:get_memory_data/0`
Port: https://github.com/emqx/emqx/pull/7137 and https://github.com/emqx/emqx/pull/7117
> Improve uptime/0

- apps/emqx/src/emqx_sys_mon.erl
- apps/emqx/test/emqx_sys_mon_SUITE.erl
Sometimes, the `emqx_sys_mon:procinfo/1` might be called with
something that is not a port, like `[]`.  Not sure on the conditions
for this to happen.
```
2022-02-18T20:05:02.671592+00:00 [error] Generic server emqx_sys_mon terminating. Reason: {badarg,[{erlang,port_info,[[]],[{error_info,#{module => erl_erts_errors}}]},{emqx_sys_mon,portinfo,1,[{file,"/emqx/apps/emqx/src/emqx_sys_mon.erl"},{line,205}]},{emqx_sys_mon,'-handle_info/2-fun-5-',2,[{file,"/emqx/apps/emqx/src/emqx_sys_mon.erl"},{line,150}]},{emqx_sys_mon,suppress,3,[{file,"/emqx/apps/emqx/src/emqx_sys_mon.erl"},{line,184}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,695}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,771}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}. Last message: …
```
> fix(sys_mon): guard before calling `erlang:port_info`

- scripts/relup-base-packages.sh
because we do not support relup for windows for now
> chore: skip downloading upgrade base images for windows

- apps/emqx/rebar.config
- apps/emqx_prometheus/rebar.config
- mix.exs
- rebar.config
0.26.0 had a bug where 'mapping' field is encoded as a integerx- list
> chore: pin hocon 0.26.1

- .github/workflows/build_packages.yaml
- Makefile
the latest build commands create sha256 sum right after the build
e.g. command `make emqx-zip` creates two files:
- emqx-\<version>.zip
- emqx-\<version>.zip.sha256
> ci: delete duplicated sha256 file creation

- .github/workflows/build_slim_packages.yaml
- Makefile
- apps/emqx/src/emqx_vm.erl
- apps/emqx_management/src/emqx_mgmt.erl
- bin/emqx
- build
- deploy/docker/Dockerfile
- deploy/packages/deb/Makefile
- deploy/packages/rpm/Makefile
- lib-ee/emqx_license/src/emqx_license_schema.erl
- mix.exs
- rebar.config.erl
- rel/BUILD_INFO
- rel/BUILT_ON
this information will be used to report in telemetry 
e.g.
```
arch: "x86_64-pc-linux-gnu"
wordsize: 64
os: "ubuntu20.04"
erlang: "24.2.1-1"
elixir: none
relform: "deb"
```
> build: more structured build info

- apps/emqx/src/emqx_session.erl
- apps/emqx/test/emqx_session_SUITE.erl
- apps/emqx_gateway/src/emqx_gateway_cm.erl
- apps/emqx_gateway/src/mqttsn/emqx_sn_channel.erl
- apps/emqx_gateway/src/mqttsn/emqx_sn_frame.erl
- apps/emqx_gateway/src/mqttsn/include/emqx_sn.hrl
- apps/emqx_gateway/src/proto/emqx_gateway_cm_proto_v1.erl
- apps/emqx_gateway/test/emqx_gateway_cm_SUITE.erl
- apps/emqx_gateway/test/emqx_sn_protocol_SUITE.erl
- Session takeover has been implemented now
- Pretty the format string for MQTT-SN frame 
- GW can register the unknown topic-name to the client
- > A GW sends a REGISTER message to a client if it wants to inform that client about the topic name and the assigned topic id that it will use later on when sending PUBLISH messages of the corresponding topic name. [6.5]
Port from https://github.com/emqx/emqx/pull/6970
> MQTT-SN Gateway Enhancement

- Makefile
For installing Hex/Rebar and downloading dependencies on a fresh
clone.
> fix(elixir): add common target dependencies for `%-elixir-pkg`

- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/run_automate_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- Makefile
- scripts/get-dashboard.sh
since EE dashboard repo is now [opensource](https://github.com/emqx/emqx-dashboard-web)
there is no need for the `git-token` file
> ci: simplify dashboard download

- apps/emqx/etc/emqx.conf
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_sys.erl
- apps/emqx/test/emqx_config_SUITE.erl
- apps/emqx/test/emqx_sys_SUITE.erl
- apps/emqx/test/props/prop_emqx_sys.erl
- apps/emqx_exhook/test/emqx_exhook_SUITE.erl
Early in 5.0 development, we deleted the client presence module and refactor it to Event Message. However, it changed the presence topic from `$SYS/brokers/<broker>/clients/<clientid>/connected` to `$event/client_connected`.
It is a huge incompatible refactoring. So, in this PR, we add the client’s presence topic back and put all of the client events notifications into the `sys_event_messages` option
> Refactor `event_messages` with `sys_topics`

- README.md
It makes sense to provide information about the default username and
password in the README file together with the information about how
to reach the web dashboard. New users reading the "Quick Start"
section would otherwise get struck wondering how to log in.
> Add info about default dashboard user name and password to README.md file

- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
When creating a JWT authenticator using the HTTP-API, the JWT Public-Key cannot be stored as a file. So here we need to make compatibility to handle its public key
> fix(authn-jwt): accept the pem conntet to create jwk authenticator

- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_zone_schema.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
1. prev qos need convertor function, the **raw**_config will store as string.
```erlang
emqx:get_raw_config([mqtt, <<"max_qos_allowed">>]).
<<"0">>
```
after change it will be integer:
```erlang
emqx:get_raw_config([mqtt, <<"max_qos_allowed">>]).
0
```
2. add `/configs/global_zones` HTTP API to describe the global_zone in `emqx_zone_schema`
> feat: Hot conf global zone

- Makefile
- apps/emqx/include/http_api.hrl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_mod.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_plugin_libs/src/emqx_plugin_libs_metrics.erl
- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- Add `server` field to the events of the MQTT Bridge source.
- Fix the issue that POST `rule_test` crashes.
> Fix HTTP APIs for getting rule events and testing rule SQLs

- apps/emqx_conf/etc/emqx_conf.conf
- apps/emqx_conf/src/emqx_conf_schema.erl
- bin/emqx
- deploy/packages/emqx.service
- deploy/packages/rpm/emqx.service
This PR includes two changes.
1. Start EMQX in foreground mode in systemd (`simple` type instead of `fork`)
3. Support `EMQX_LOG__TO` for backward compatibility 
* If `EMQX_LOG__TO=default`, EMQX respects the config file
* if `MEQX_LOG__TO` is set to `console`, `file` or `both`, environment variable overrides will effect
* In `foreground` mode, EMQX logs to console by default (as if `EMQX_LOG__TO=console`)
start log:
```
Mar 11 10:00:27 ip-10-0-1-35 systemd[1]: Started emqx daemon.
Mar 11 10:00:32 ip-10-0-1-35 emqx[5644]: EXEC: /usr/lib/emqx/erts-12.2.1/bin/erlexec -noshell -noinput +Bd -boot /usr/lib/emqx/releases/5.0.0-beta.3-1cf24248/start -mode embedded -boot_var ERTS_LIB_DIR />
Mar 11 10:00:34 ip-10-0-1-35 emqx[5417]: Listener quic:default on :14567 started.
Mar 11 10:00:34 …
```
> Start EMQX in foreground mode in systemd

- scripts/format_app.py
This added script file, which can be run from the root emqx directory or the scripts directory, aids in applying erlfmt formatting to an application.
It can be used on the first formatting, in which case it will add the required rebar3 plugin declaration to the `rebar.config` file, or on any subsequent formatting attempts.
Should be idempotent, and be able to be executed on any given application as many times as desired without adverse outcomes. So if you run into a case where there is an error during formatting, as will be the case in I think two of our sub apps due to the way we do some macros, you can fix the spots where there are errors and safely rerun the script and it should just work.
Result of calling the file with the `-h` option:
```
/bin/python3.9 scripts/format_app.py -h …
```
> feat: add file to assist in formatting application

- CHANGES-4.3.md
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- src/emqx_channel.erl
Passing it through querystring is a string.
if passed through body, it is an integer
add doc:https://github.com/emqx/emqx-docs/pull/1075
> feat: Support set keepalive via queryString & Body HTTP API.

- apps/emqx_authn/src/emqx_authn_api.erl
- apps/emqx_authn/src/emqx_authn_schema.erl
- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- apps/emqx_authz/src/emqx_authz_api_sources.erl
- apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
authn, authz get resource status.
add api：
/authentication/:id/status
/authentication/:id/authentication/:id/status
/authorization/sources/:type/status
status example
```erlang
#{ metrics => #{  matched => 0,
success => 0,
failed => 0,
rate => 0.0,
rate_last5m => 0.0,
rate_max => 0.0
},
node_metrics => [ #{node => node(),
metrics => #{  matched => 0,
success => 0,
failed => 0,
rate => 0.0,
rate_last5m => 0.0,
rate_max => 0.0
}
}
],
status => connected,
node_status => [ #{node => node(),
status => connected
}
]
}
```
> feat: add authn, authz status api

- apps/emqx_retainer/src/emqx_retainer_api.erl
The front-end expects to get the raw config content, not the translated one
> fix(retainer): don't translate config content, keep it in raw

- deploy/charts/emqx/templates/StatefulSet.yaml
As discussed, the specific helm chart issue and how to fix it:
--
The root of the issue is that StatefulSet.yaml > volumeClaimTemplates has:
[helm.sh/chart:](http://helm.sh/chart:) {{ include "emqx.chart" . }}
Which is not allowed, since a statefulset's volumeClaimTemplates template cannot change (and it will change when an upgrade is performed).
--
How to fix:
In the file SatefulSet.yaml > spec > volumeClaimTemplates > metadata > labels, the following line must be deleted:
[helm.sh/chart:](http://helm.sh/chart:) {{ include "emqx.chart" . }}
--
> fix(helm): delete needless labels for support helm upgrade

- apps/emqx_bridge/src/emqx_bridge_http_schema.erl
- apps/emqx_bridge/src/emqx_bridge_schema.erl
the `config` struct without a proper namespace at root level is very much confusing.
> chore: add namespace to bridge schema

- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_authz/src/emqx_authz_api_schema.erl
- apps/emqx_authz/src/emqx_authz_api_sources.erl
- apps/emqx_authz/src/emqx_authz_schema.erl
- apps/emqx_authz/test/emqx_authz_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_mnesia_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
- apps/emqx_authz/test/emqx_authz_file_SUITE.erl
The acl file and cert file should be writen after EMQX sync config to all nodes.
Rather than at the node that received the API request.
Otherwise other nodes will get an empty path with no specific content.
> fix authz cluster update config

- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE_data/BUILD_INFO
On macOS, apparently symlinks can cause problems when rebar3 tries to
copy files to the `_build` directory.  So we now use a copy of
`rel/BUILD_INFO`.  Unfortunately, this has the downside of this copy
possibly going stale over time.
Please run `rm _build/test/lib/emqx_modules/test/emqx_telemetry_SUITE_data/BUILD_INFO` if the following error is encountered:
```
+ env LOGLEVEL=debug make ct-suite SUITE=apps/emqx_modules/test/emqx_telemetry_SUITE
/home/thales/dev/emqx/emqx/rebar3 ct -v --readable=false --name 'test@127.0.0.1' --suite apps/emqx_modules/test/emqx_telemetry_SUITE
===> Plugin er_coap_client does not export init/1. It will not be used.
===> Verifying dependencies...
cp: not writing through dangling symlink '/home/thales/dev/emqx/emqx/_build/test/lib/emqx_modules/test/emqx_telemet …
```
> fix(test): use a real copy of BUILD_INFO for testing

- apps/emqx_conf/etc/emqx_conf.conf
- apps/emqx_conf/src/emqx_conf_schema.erl
- deploy/docker/Dockerfile
- deploy/docker/README.md
Although 4.x supports using EPMD, but we really have not tested it for years.
Starting from 5.0, we'll always use `ekka` for Erlang distribution protocol.
> chore: delete epmd related ports and settings

- .github/workflows/apps_version_check.yaml
- scripts/apps-version-check.sh
- scripts/update-appup.sh
Reasons
* OTP version might be different in developer's env and build env
* For some tags, we do not build release. e.g. rel-v4.4.X
> chore: update-appup.sh always rebuild baseline

- apps/emqx/rebar.config
- apps/emqx/src/emqx_metrics.erl
- apps/emqx/src/emqx_stats.erl
- apps/emqx/test/emqx_stats_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- apps/emqx_prometheus/rebar.config
- mix.exs
- rebar.config
```erlang
5.0.0-beta.4-a2559631(emqx@127.0.0.1)1> 2022-03-22T10:49:19.585313+01:00 [error] Generic server emqx_dashboard_monitor terminating. Reason: {function_clause,[{emqx_dashboard_monitor,cal_rate,
[{emqx_monit,1647942559585,#{connections => 0,dropped => 0,received => 0,received_bytes => 0,routes => 0,sent => 
0,sent_bytes => 0,subscriptions => 0}},undefined],[{file,"emqx_dashboard_monitor.erl"},{line,245}]},
{emqx_dashboard_monitor,handle_call,3,[{file,"emqx_dashboard_monitor.erl"},{line,154}]},{gen_server,try_handle_call,4,
[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}. Last message: current_rate. State: {state,undefined}. Client
<0.2639.0> stacktrace: …
```
> fix: dashboard_monitor crash

- apps/emqx_connector/src/emqx_connector.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
Return all available values, including the defaults, to the HTTP APIs:
GET /connectors
GET /connectors/:id
Without this, the connector dashboard UI cannot see anything about the values that was "not set" but have default values, such as the `retry_interval` and `reconnect_interval`.
> fix: list connectors with default values

- Makefile
On a fresh clone, this will setup rebar, the dashboard and merge the
configs.
> fix: add common dependencies to `%-pkg` target in makefile

- apps/emqx_modules/src/emqx_telemetry.erl
`available_memory` seems to be a linux specific concept (smwt like `free` + `cache`).
On e.g. macos we do not have such a key:
Linux:
```
5.0.0-rc.1-7b6a71c1(emqx@127.0.0.1)1> memsup:get_system_memory_data().
[{available_memory,6347300864},
{buffered_memory,514732032},
{cached_memory,4329361408},
{free_memory,2232246272},
{free_swap,1073737728},
{system_total_memory,8597819392},
{total_memory,8597819392},
{total_swap,1073737728}]
```
Mac Os:
```
5.0.0-rc.1-e9ce91b6(emqx@127.0.0.1)1> memsup:get_system_memory_data().
[{free_memory,105984000},
{system_total_memory,17179869184},
{total_memory,17179869184}]
```
> fix(emqx_telemety): use total_memory memsup key

- .github/workflows/build_packages.yaml
This should hopefully fix some of the libcrypto DLL issues.
The windows build has been tested in a manually started cross-build CI job.
> ci: upgrade erlang for windows

- apps/emqx/include/emqx_mqtt.hrl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_pmon.erl
- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_frame_SUITE.erl
- apps/emqx/test/emqx_pmon_SUITE.erl
`demonitor(Ref, [flush])` often will not be be able to get optimised
by the compiler hence fallback to a full mailbox scan to drain
the `DOWN` message.
This commit tries to avoid the 'flush' when it's for sure
that there is no `DOWN` message sent.
> perf: improve demonitor performance

- rebar.config
0.2.1 contains a minior fix to avoid flag process getting
force killed if beam file force purged
> chore: upgrade app lc from 0.2.0 to 0.2.1

- apps/emqx_gateway/src/emqx_gateway.erl
- apps/emqx_gateway/test/emqx_gateway_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_SUITE_data/lwm2m.conf
- apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_cm_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_cm_registry_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_conf_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- apps/emqx_modules/src/emqx_telemetry.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_tests.erl
Example data:
```json
"gateway": {
"lwm2m": {
"num_clients": 0,
"authn": "password-based:mysql",
"listeners": [
{
"type": "tcp", // tcp | ssl | udp | dtls
"authn": "password-based:mysql"
}
]
}
},
```
> feat(telemetry): add gateway info to reported data

- apps/emqx/src/emqx_logger_textfmt.erl
Fix following "FORMAT ERROR"
logger:warning(["line1\n", "line2\n","line3\n"]).
2022-04-06T18:44:07.412131+02:00 [warning] FORMAT ERROR: "~ts " - ["line1\n","line2\n","line3\n"]
ok
> fix: text logger

- apps/emqx_exhook/src/emqx_exhook.erl
- apps/emqx_exhook/test/emqx_exhook_SUITE.erl
- apps/emqx_modules/src/emqx_telemetry.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
Example output:
```json
"exhook": {
"num_servers": 1
"servers": [
{ "driver": "grpc",  // the only type now, maybe will add erlport 
"hooks": ["client.authenticate", "message.publish"]  // the hooks enabled
}
]
}
```
>  feat(telemetry): report basic exhook usage

- apps/emqx/src/emqx_pmon.erl
As it turns out to be a false assumption from old time investigation in OTP code.
> chore: no need for erlang:demonitor optimisation

- rebar.config
In ehttpc v0.2.0, we have optimized the implementation for request collection
to reduce resource consumption. see: https://github.com/emqx/ehttpc/pull/31
> Upgrade ehttpc to 0.2.0

- bin/emqx
Adds a check to `bin/emqx` to see if the OTP version being used has
support for `mnesia_hook`, which is required by Mria for using the
RLOG backend.  If OTP is not compatible and the user tries to use
RLOG, a warning is printed during startup and the configuration falls
back to using the Mnesia backend.
> feat(db): check if OTP has mnesia_hook, otherwise fallback to mnesia

- apps/emqx_rule_engine/src/emqx_rule_maps.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_maps_SUITE.erl
When the selection field does not exist, it should output `#{Field => undefined}`, not an empty map().
SQL:
```
SELECT  somefield
FROM
"t/#"
```
Input:
```
{"msg": "hello"}
```
Before this fix, the output was:
```
{}
```
After this change, the output becomes:
```
{
"somefield": "undefined"
}
```
> fix: behavior of rule-engine when selection field does not exist

- apps/emqx/src/emqx_config_handler.erl
fix: `./bin/emqx stop`
```erlang
2022-04-14T13:36:17.765414+08:00 [error] Supervisor: {local,emqx_kernel_sup}. Context: shutdown_error. 
Reason: killed. Offender: id=emqx_config_handler,pid=<0.2010.0>.
```
> fix: can't shutdown emqx_config_handler process.

- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl
- apps/emqx_dashboard/test/emqx_swagger_requestBody_SUITE.erl
- apps/emqx_dashboard/test/emqx_swagger_response_SUITE.erl
If you don't provide an example for the primary type, use the default value instead of generating a meaningless example yourself.
such as "binary-example",  "string-example", "atom-example".
> chore: Don't display primary example, we should show default if no example found

- apps/emqx_exhook/src/emqx_exhook_api.erl
- apps/emqx_exhook/src/emqx_exhook_mgr.erl
- apps/emqx_exhook/src/emqx_exhook_server.erl
1. change ExHook status from (stopped, waiting, running) to (disable, connecting, connected, unconnected)
2. ignore the Exhook server load error when config update
> fix(exhook):  refine the status of the exhook callback server 

- apps/emqx_dashboard/etc/emqx_dashboard.conf
- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
- apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
- apps/emqx_dashboard/test/emqx_dashboard_api_test_helpers.erl
Don't use arrays in the config path to make it easier to change
configs via environments varibles.
> refactor: change confs for dashboard listeners from array to map

- apps/emqx_authn/src/simple_authn/emqx_authn_jwks_client.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_jwks_connector.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_authn/test/emqx_authn_jwt_SUITE.erl
- apps/emqx_resource/test/emqx_test_resource.erl
Currently, `emqx_authn_jwks_connector` is a `gen_server` that makes http requests and is `start_link`'ed in `emqx_authn_jwt` provider directly.
So, if it crashes for some reason
* the whole `emqx_authentication` crashes too;
* after `emqx_authentication` restart (whatever the reason is), `emqx_authn_jwt` configuration with dead pid remains active, and `emqx_authn_jwks_connector` never gets restarted.
In this PR `emqx_authn_jwks_connector` is made an `emqx_resourse`, like MySQL/Redis/... connections. It is run under `ecpool` supervisor and always remains valid and accessible via `ResourseId`.
> chore(emqx_authn_jwt): wrap JWKS connector into emqx_resourse

- apps/emqx_modules/src/emqx_telemetry.erl
- apps/emqx_modules/src/proto/emqx_telemetry_proto_v1.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
- apps/emqx_modules/test/emqx_telemetry_api_SUITE.erl
Each node already has its own UUID, and now we want to add a cluster UUID that is the same for all nodes.
> feat(telemetry): add cluster uuid

- apps/emqx/src/emqx_rpc.erl
- apps/emqx_conf/etc/emqx_conf.conf
- apps/emqx_conf/src/emqx_conf_schema.erl
From: https://github.com/emqx/emqx/pull/6554
> feat: use gen_rpc ordered cast for `emqx_rpc:cast/5`

- apps/emqx/src/emqx_passwd.erl
- apps/emqx/test/emqx_passwd_SUITE.erl
- apps/emqx_authn/src/emqx_authn_password_hashing.erl
- apps/emqx_authn/test/emqx_authn_password_hashing_SUITE.erl
- apps/emqx_authn/test/emqx_authn_redis_SUITE.erl
In 4.x, it is optional for Password Hash to contain Salt or not. So, we need to make it compatible in 5.0
> feat(authn): support disable salt

- apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl
the space in name field will make some problems in frontend
> fix(limiter): change 'bucket name' to 'bucket_name'

- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx_rpc.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx/test/emqx_config_handler_SUITE.erl
- apps/emqx_retainer/include/emqx_retainer.hrl
- apps/emqx_retainer/src/emqx_retainer_dispatcher.erl
- apps/emqx_retainer/src/emqx_retainer_index.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia_cli.erl
- apps/emqx_retainer/src/emqx_retainer_schema.erl
- apps/emqx_retainer/src/proto/emqx_retainer_proto_v1.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_cli_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_index_SUITE.erl
This the first variant of optimized retainer.
This introduces:
* The concept of "topic index": an ascending sequence of topic segment indexes.
* `emqx_retainer_index` module, that consist of some clean functions that helps to rearrange topic segments according to the index.
* Extending `emqx_retainer_mnesia` so that it stores not only messages by topics, but keeps track of rearranged topics too.
* Refactoring `emqx_retainer_mnesia` to using `qlc` interfaces. This allows to use index scans and full scans in a uniform manner.
Assume we have `[2, 3]` index. 
When a retained message arrives for topic `a/b/c/d/e`, we store it in the index table by key `{[b,c], [a,d,e]}`: indexed and unindexed segments.
When a subscription `a/b/+/d/#` arrives, we detect that some first indexed segments are …
> feat(retainer): add topic indexing

- apps/emqx_conf/src/emqx_conf_schema.erl
- bin/emqx
- bin/emqx.cmd
- build
The main slow-down is the overheads of booting up beam with the
'start_clean' boot file (which loads all modules).
Prior to this change, beam is started multiple times in order to
resolve configuration values.
After this change:
* For boot commands such as 'start', 'console' and
'foreground', it starts beam twice:
- 1st is to check platform compatibility
- 2nd is to resolve all configs required for boot in a batch
* For non-boot commands, such as 'ctl' and 'ping', it does not
require to start beam for config resolution at all
> refactor(bin/emqx): speed up boot

- Makefile
- apps/emqx/i18n/emqx_schema_i18n.conf
- apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx_authz/i18n/emqx_authz_api_cache_i18n.conf
- apps/emqx_authz/i18n/emqx_authz_api_settings_i18n.conf
- apps/emqx_authz/i18n/emqx_authz_schema_i18n.conf
- apps/emqx_conf/src/emqx_conf_app.erl
- apps/emqx_dashboard/i18n/emqx_dashboard_schema.conf
- apps/emqx_gateway/i18n/emqx_coap_api_i18n.conf
- apps/emqx_gateway/i18n/emqx_gateway_schema_i18n.conf
fix:
```
[error] failed: [], line: 61, mfa: emqx_conf_app:copy_override_conf_from_core_node/0, msg: 
copy_overide_conf_from_core_node_failed, nodes: ['emqx@node1.emqx.io'], not_ready: [{error,#{msg => 
"init_conf_load_not_done",node => 'emqx@node1.emqx.io'}}]
[node2.emqx.io](http://node2.emqx.io/) | 2022-03-16T02:11:56.285025+00:00 [error] crasher: initial call: 
application_master:init/4, pid: <0.2025.0>, registered_name: [], exit: {{bad_return,{{emqx_conf_app,start,[normal,[]]},
{'EXIT',{{badmatch,{error,"core node not ready"}},[{emqx_conf_app,init_conf,0,[{file,"emqx_conf_app.erl"},{line,36}]},
{emqx_conf_app,start,2,[{file,"emqx_conf_app.erl"},{line,28}]},{application_master,start_it_old,4,
[{file,"application_master.erl"},{line,293}]}]}}}},[{application_master,init,4,[{file,"applicati …
```
> fix: swagger crash/ copy conf failed from core node

- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx/test/emqx_config_handler_SUITE.erl
- apps/emqx_modules/src/emqx_modules_conf.erl
- apps/emqx_modules/src/emqx_telemetry.erl
- apps/emqx_modules/src/emqx_telemetry_api.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
- apps/emqx_modules/test/emqx_telemetry_api_SUITE.erl
- Makes telemetry enabled by default on official versions.
- Allow enabling/disabling telemetry even on non-official versions.
> feat(telemetry): enable/disable even in non-official versions

- bin/emqx
The CLI emqx_ctl fails:
```
./bin/emqx_ctl status
Node not initialized?
Generated config file vm.*.args is not found for command 'ctl'
in config dir: /Users/liuxy/code/emqx50/_build/emqx/rel/emqx/-emqx_data_dir /Users/liuxy/code/emqx50/_build/emqx/rel/emqx/data --/configs
In case the file has been deleted while the node is running,
set environment variable 'EMQX_NODE__NAME' to continue
```
> fix: ./bin/emqx_ctl status failed

- bin/node_dump
`emqx_vars` requires `RUNNER_ROOT_DIR` to be defined before being
sourced.
> fix(node_dump): define `RUNNER_ROOT_DIR` before sourcing vars

- src/emqx_channel.erl
`appup.src` already updated in #7087
> fix(channel): update conninfo when start keepaliver timer

- apps/emqx_dashboard/include/emqx_dashboard.hrl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
Rename the following fields:
- received_rate -> received_msg_rate
- sent_rate -> sent_msg_rate
- dropped_rate -> dropped_msg_rate
Remove:
- received_bytes_rate
- sent_bytes_rate
> fix(dashboard): rename fields  for monitor_current APIs

- CHANGES-4.3.md
- apps/emqx_management/src/emqx_mgmt_auth.erl
prior to this change, app secrets are uuids which is not
completely random.
> fix(emqx_mgmt_auth): randomise all bytes in app secret

- apps/emqx_modules/src/emqx_telemetry.erl
To stop the "Authenticity is not established by certificate path
validation", Reason: "Option {verify, verify_peer} and
cacertfile/cacerts is missing" warning message
> fix(telemetry): add verify_none ssl option

- apps/emqx/src/emqx_schema.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_connector/src/emqx_connector_schema.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
- apps/emqx_psk/src/emqx_psk_schema.erl
fix: Chaotic document ordering if multi schema's namespace is undefined.
https://github.com/emqx/hocon/pull/195
> fix: add namespace to schema

- apps/emqx_management/src/emqx_mgmt_auth.erl
change from timestamp seeded hash (uuid) to crypto:strong_rand_bytes
> fix(emqx_mgmt_auth): better randomisation of app secrets

- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_modules/src/emqx_telemetry.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
- Avoid crashing telemetry app if it tries to report data when the bridge app is not ready yet.
- Avoid hanging `emqx_module` app initialization by deferring the first report after a few seconds, instead of being synchronous.
> fix: avoid crashing telemetry if bridge app is not ready

- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_manager_sup.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
The API is the same, and for the most part the behaviors are the same. The biggest difference is that there is no ETS entry to look up when the state is not connected. This removes a little bit of visibility when trying to do a query because we cannot provide as fine grained detail as to why the query cannot be made.
> feat: isolate resource manager processes

- apps/emqx/src/emqx_alarm_handler.erl
- apps/emqx/src/emqx_app.erl
- apps/emqx/src/emqx_os_mon.erl
Uniformly report high_system_memory_usage event by gen_event:notify/2 to
ensure generate a same alarm structure.
In the previous implement, the `ensure_system_memory_alarm/1` will generate a un-format alarm:
> fix(alarm): use gen_event:noifty/2 to generate alarm event

- lib-ce/emqx_dashboard/src/emqx_dashboard_admin.erl
Clarification:
This is a least-effort attempt to avoid brutal forcing without external dependencies.
elegant solutions are
* 2FA (or multi FA) -- this is something already solved by SSO solutions
* Prove of work from clients -- not sure how many people are using it
by default, there are 512 concurrent connections limit to management APIs,
so a malicious client may technically eat up all the connections by starting a lot of http clients concurrently.
however, at the current stage, there is no DDoS protection implemented in EMQX itself anyway,
so we'll consider that a different issue and maybe follow up in a different thread.
> fix: add 2 seconds delay penalty for bad logins

- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_ws_connection.erl
https://github.com/rabbitmq/rabbitmq-web-mqtt/issues/28#issuecomment-380833296
> In Cowboy it's only used to limit the number of HTTP connections. As soon as an HTTP connection becomes a Websocket connection, the connection is no longer counted and so you can have 1024 as a limit and still have 10k Websocket connections.
so we need to check max_connection by ourselves. otherwise the ws/wss's max_connection is not work as we expect.
> fix: websocket's max_connection not work

- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf_app.erl
- apps/emqx_conf/test/emqx_conf_app_SUITE.erl
Depending on the order that a cluster of core nodes might be stopped
and then restarted, there might be a deadlock or crash during the
configuration loading.  The nodes try to check with each other which
has the latest cluster overrides and copy that info.  However, in some
cases, Mnesia on node A might still think that it needs to consult
another node C that is still down, so that this node proceeds with its
boot sequence but `mnesia:wait_for_tables` in `emqx_cluster_rpc` is
stuck.  Meanwhile, a node B can come up, try to copy from the sole
online node A, and fail because it's not ready yet.
> fix(emqx_conf): avoid crash/deadlock depending on node startup order

- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_tls_lib.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
- apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl
For ssl options, the `sni` should be an atom `'disable'` or string for hostname.
See [type-sni](https://www.erlang.org/doc/man/ssl.html#type-sni)
And code style fmt fixed here: https://github.com/emqx/emqx/pull/7772
> fix ssl options

- .github/workflows/build_packages.yaml
- scripts/buildx.sh
cross build is running in container
can not run docker in dokcer
> ci: get OS from builder image name

- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_authn/test/emqx_authn_jwt_SUITE.erl
An empty claim_name has not a real meaning and will result in a
syntax error cluster_override.conf. i.e:
```
authentication {
mechanism = "jwt"
verify_claims { = "22"}
...
}
```
> fix(authn-jwt): avoid to save empty claim name

- deploy/charts/emqx/templates/StatefulSet.yaml
The previous code was ignoring `.Values.image.tag` and always using
`.Char.AppVersion`.
> fix(helm): use tag if defined

- .github/workflows/elixir_apps_check.yaml
- .github/workflows/elixir_deps_check.yaml
- Makefile
- scripts/ensure-rebar3.sh
```
===> Analyzing applications...
===> Compiling emqx
===> Running cross reference analysis...
escript: exception error: no match of right hand side value 
[{attribute,0,compile,{nowarn_unused_record,[[chain]]}},
{attribute,
{1,1},
file,
{"/__w/emqx/emqx/apps/emqx/src/emqx_authentication.erl",1}},
{attribute,{21,2},module,emqx_authentication},
{attribute,{23,2},behaviour,gen_server},
{attribute,
{1,1},
file,
{"/__w/emqx/emqx/apps/emqx/_build/default/lib/emqx/include/emqx.hrl",
1}},
{...}|...]
in function  rebar_prv_xref:find_function_source_in_abstract_code/3 (rebar_prv_xref.erl, line 306)
in call from rebar_prv_xref:format_mfa_source/1 (rebar_prv_xref.erl, line 265)
in call from rebar_prv_xref:'-display_xref_result_fun/1-fun-0-'/2 (rebar_prv_xref.erl, line 228)
in call from lists:map/2 …
```
> chore: port ensure-rebar3.sh from 4.x

- apps/emqx_authn/i18n/emqx_authn_http_i18n.conf
- apps/emqx_authn/src/simple_authn/emqx_authn_http.erl
- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- apps/emqx_authz/i18n/emqx_authz_api_schema_i18n.conf
- apps/emqx_authz/i18n/emqx_authz_schema_i18n.conf
- apps/emqx_authz/src/emqx_authz_api_schema.erl
- apps/emqx_authz/src/emqx_authz_http.erl
- apps/emqx_authz/src/emqx_authz_schema.erl
- apps/emqx_authz/src/emqx_authz_utils.erl
- apps/emqx_authz/test/emqx_authz_http_SUITE.erl
`authn`/`authz` HTTP should support placeholder in both HTTP 'path' and HTTP 'query string'.
i.e.
`URL` configured as `http://127.0.0.1:8080/${username}?${clientid}`, and HTTP method as `GET`
And the username of client is `user name`, the clientid is `client id`
The HTTP request should like:
`GET http://127.0.0.1:8080/user%20name?client%20id`
etc:
`URL` configure should be literal. URL percent encoding will be handled automatically.
> fix auth http

- apps/emqx/src/emqx_access_control.erl
- apps/emqx/src/emqx_metrics.erl
- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_authz/test/emqx_authz_jwt_SUITE.erl
In the current implementation:
```
Authz checking times = client.authorize + client.authorization.cache_hit
= client.authorization.allow + client.authorization.deny
client.authorize means how many times the `client.authorize` hook has been executed.
client.authorize = client.authorize.matched.allow +
client.authorize.matched.deny +
client.authorize.nomatch
```
> feat(metrics): refactor authz metrics name

- scripts/update-appup.sh
Since the script copies the current workdir into the temporary
directory for the previous build, when we latter try to clean the
directory, `git clean -fdx` refuses to clean the folders of some
dependencies:
```
+ git clean -fdx
Skipping repository _build/default/lib/lc
```
So, if the branch contains a dependency with changed version, it'll
not be picked up by the script, as both versions will be identical and
hence have no `.appup` difference.
> fix(update_appup): clean untracked nested git directories

- apps/emqx/etc/emqx_cloud/vm.args
- apps/emqx/etc/emqx_edge/vm.args
- bin/emqx
if the install dir is "emqx test", crash on startup:
_crasher: initial call: application_master:init/4, pid: <0.1981.0>, registered_name: [], exit: {{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,enoent}},[{emqx_bpapi,announce,1,[{file,"emqx_bpapi.erl"},{line,79}]},{emqx_app,start,2,[{file,"emqx_app.erl"},{line,46}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.1980.0>], message_queue_len: 1, messages: [{'EXIT',<0.1982.0>,normal}], links: [<0.1980.0>,<0.1648.0>], dictionary: [], trap_exit: true, status: running, heap_size: 46422, stack_size: 29, reductions: 219; neighbours:_ …
> fix: can't get emqx's priv_dir when whitespace in install path

- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_connector/src/emqx_connector_ssl.erl
Before this fix, testing the connector using a already created SSL cert file (file path), the file is deleted after testing!
> fix: don't drop input ssl options even if invalid

- apps/emqx/rebar.config
- mix.exs
- rebar.config
Improves autocluster resilience against split-brain during startup.
https://github.com/emqx/ekka/pull/160
> chore(ekka): bump ekka -> 0.12.5

- CHANGES-4.3.md
- rebar.config
Improves autocluster resilience against split-brain during startup.
https://github.com/emqx/ekka/pull/158
> chore(ekka): bump ekka -> 0.8.1.10

- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_tls_lib.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_connector/src/emqx_connector_ssl.erl
- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_dashboard/src/emqx_dashboard_app.erl
- apps/emqx_dashboard/src/emqx_dashboard_listener.erl
- apps/emqx_dashboard/src/emqx_dashboard_middleware.erl
- apps/emqx_dashboard/src/emqx_dashboard_sup.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
- mix.exs
- rebar.config
The dashboard start_listeners is slowing down due to too much API router(dispatch) generation.
we need to update ranch's dispatch async.
https://github.com/emqx/minirest/pull/90
https://github.com/emqx/minirest/pull/91
> feat: start dashboard listener asynchronously

- apps/emqx/i18n/emqx_schema_i18n.conf
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
if we choose ssl listener(emqx as server), we always enable ssl options.
if we use tls option to connect others(emqx as client), then we should have this enable in client_ssl_opts_schema.
> fix: remove enable from server_ssl_opts_schema

- apps/emqx_conf/i18n/emqx_conf_schema.conf
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- mix.exs
- rebar.config
1. Display ref's desc in schema.json.
2. Bump minirest(1.3.3) to force generate dispatch rule.
> fix: show ref's desc in hot-config-schema.json

- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_authn/test/emqx_authn_jwt_SUITE.erl
- apps/emqx_authz/src/emqx_authz_jwt.erl
- apps/emqx_authz/test/emqx_authz_jwt_SUITE.erl
* Handle string values for `iat`, `nbf` and `exp` claims.
* Require `exp` claim for authn & authz
> fix(jwt auth): improve JWT handling

- rebar.config.erl
1.14.1 was a typo, (not released yet)
> build: fix port-compiler version tag to 1.14.0

- mix.exs
- rebar.config.erl
This PR makes jq compile error reporting better and avoids a crash when the program contains an include expression.
> fix: update jq to v0.2.1

- apps/emqx/rebar.config
- apps/emqx/src/emqx_alarm.erl
- apps/emqx/src/emqx_alarm_handler.erl
- apps/emqx/src/emqx_congestion.erl
- apps/emqx/src/emqx_os_mon.erl
- apps/emqx/src/emqx_sys_mon.erl
- apps/emqx/src/emqx_vm.erl
- apps/emqx/src/emqx_vm_mon.erl
- apps/emqx/test/emqx_os_mon_SUITE.erl
- apps/emqx_resource/src/emqx_resource_health_check.erl
- lib-ee/emqx_license/src/emqx_license_checker.erl
- lib-ee/emqx_license/src/emqx_license_resources.erl
- mix.exs
- rebar.config
The memsup triggered memory usage alert counts os cache as used.
this PR makes use of memory usage from `lc` lib,
and manages memory alarm outside of memsup
> pin lc 0.3.0 fix memory usage false alarm

- deploy/packages/rpm/Makefile
- deploy/packages/rpm/emqx.spec
- scripts/pkg-tests.sh
Failed to manage emqx by systemctl because of missing `emqx.service`.
It happened in every build_slim_package action, such as:
https://github.com/emqx/emqx/runs/6434020470?check_suite_focus=true
```
yum install -y /__w/emqx/emqx/_packages/emqx-edge/emqx-edge-5.0.0-rc.2-c92e4b4e-otp24.2.1-1-el8-amd64.rpm
Rocky Linux 8 - AppStream                        13 kB/s | 4.8 kB     00:00    
Rocky Linux 8 - AppStream                       8.9 MB/s |  10 MB     00:01    
Rocky Linux 8 - BaseOS                           19 kB/s | 4.3 kB     00:00    
Rocky Linux 8 - BaseOS                          8.0 MB/s | 7.7 MB     00:00    
Rocky Linux 8 - Extras                           11 kB/s | 3.5 kB     00:00    
Rocky Linux 8 - Extras                           21 kB/s |  12 kB     00:00    
Extra Packages …
```
> fix: emqx can't start with systemctl

- lib-ce/emqx_telemetry/src/emqx_telemetry.app.src
- lib-ce/emqx_telemetry/src/emqx_telemetry.appup.src
- lib-ce/emqx_telemetry/src/emqx_telemetry.erl
fixes: https://github.com/emqx/emqx/issues/7875
This issue was reported on 4.4 where the default OTP version had the warning introduced.
but the fix is applied to `main-v4.3`, which will be forward merged to `main-v4.4`
> fix(telemetry): Ensure verify_none for http client

- deploy/charts/emqx/Chart.yaml
- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/values.yaml
[persistent-volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of the storageClassName attribute. This annotation is still working; however, it will become fully deprecated in a future Kubernetes release.
> fix: use storageClassName instead of annotation

- apps/emqx_connector/test/emqx_connector_SUITE.erl
No matter how many times I run things locally I don't get any test failures. However I think the problem is the introduction of a same named connector in the `emqx_connector_SUITE`.
Hopefully this rename will prevent a race condition and there will be no problems with "already created connectors" in the future.
Why 42? Because it's the answer to everything...
> fix: change connector name to prevent race condition in tests

- apps/emqx/src/emqx_map_lib.erl
- apps/emqx/test/emqx_map_lib_tests.erl
prior to this fix, when merging two nested maps (metrics), the non-number values from the base map might be kept.
this may cause error in later data serialisation.
this fix adds a filter to drop non-number and non-map field values, making sure only numbers are kept.
> fix(emqx_map_lib): ignore non-number non-map values

- apps/emqx_management/src/emqx_mgmt_api_pubsub.erl
- apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
When an unsupported type value included in publish api params.
Such as integer/boolean/list/map/... as `User-Property` value will cause serialize packet error and crash, and then the clients who subscribed the target topic will disconnect.
e.g `10001`/`true`/`["v1", "v2"]`/`{"k1": "v1"}`
> fix pub api

- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_monitor.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/src/proto/emqx_bridge_proto_v1.erl
- apps/emqx_bridge/test/emqx_bridge_SUITE.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_connector/src/emqx_connector.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- Move some resource related APIs to a new module emqx_bridge_resource
- Add emqx_bridge:create/remove APIs for create and remove bridges, not only the resources but also the configs.
- This may also fix some test cases that failed with `ALREADY_EXISTS`.
> refactor: move some APIs to new module emqx_bridge_resource

- lib-ce/emqx_dashboard/priv/emqx_dashboard.schema
```
2022-05-19T10:47:34.262135-04:00 [error] Failed to start Ranch
listener 'https:dashboard' in ranch_ssl:listen <snip> for reason {options,{verify,"verify_none"}} (unknown POSIX error)
```
> fix(dashboard): use atom for `verify` tls option in dashboard listener

- bin/emqx
Before, if erlang is not satisfy with the openssl verison. only show a `undef` stacktrace.
```
[root]# ./erts-12.1.5/bin/erl -noshell -boot releases/4.4.3/start_clean -s crypto start -s init stop
Erlang/OTP 24 [erts-12.1.5] [emqx] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit]
{"init terminating in do_boot",{undef,[{crypto,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{crypto,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
Crash dump is being written to: erl_crash.dump...done
```
Then we delete `-noshell` option and replace `-s` with `-eval`. to show loading nif failed msg.
```
[root]# ./erts-12.1.5/bin/erl -boot releases/4.4.3/start_clean -eval "crypto:start(),halt()"
\Erlang/OTP 24 [erts-12.1.5] [emqx] [64-bit] [smp:1:1] …
```
> chore: show more error msg when check_erlang_start failed

- apps/emqx_rule_engine/etc/emqx_rule_engine.conf
- apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- mix.exs
- rebar.config.erl
- scripts/prepare-build-deps.sh
This PR adds a default timeout of 10 seconds to the rule engine's jq/2 function, and adds a new function jq/3 (where the last parameter is a timeout value). The default timeout can be configured with the setting "rule_engine.jq_function_default_timeout".
Having a timeout when executing jq code in the rule engine is important as jq code can potentially run forever. Also, the Erlang jq library limits the number of jq programs that can execute concurrently so a jq program that loops forever could potentially also prevent a "non-buggy" jq program from ever starting.
I'm not sure that rule_engine.jq_function_default_timeout is the right place for the setting so please let me know if there is a better place. Also, I would like help to translate the documentation strings to Chinese.
This PR is …
> feat(rule_engine): default timeout for jq/2 and jq/3 with timeout

- apps/emqx_management/priv/emqx_management.schema
When one tries to define the management http listener as, for example,
`172.25.0.2:8081`, ranch is given `{port, {"172.25.0.2",8081}}` and
breaks.
```sh
env EMQX_MANAGEMENT__LISTENER__HTTP=172.25.0.2:8081 make quickrun
```
```
2022-05-20T13:14:19.451272-03:00 [error] Supervisor: {<0.2485.0>,ranch_listener_sup}. Context: start_error. Reason: badarg. Offender: id=ranch_acceptors_sup,pid=undefined.
2022-05-20T13:14:19.451400-03:00 [error] crasher: initial call: supervisor:ranch_acceptors_sup/1, pid: <0.2487.0>, registered_name: [], exit: {badarg,[{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,166}]},{ranch_acceptors_sup,init,1,[{file,"ranch_acceptors_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,330}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen …
```
> fix(mgmt): allow binding to specific interface

- apps/emqx_auth_pgsql/src/emqx_auth_pgsql.appup.src
We have to restart the emqx_auth_pgsql because epgsql has upgraded 4.4.0 to 4.6.0
see: #8001
> chore(pgsql): restart emqx_auth_pgsql due to the egpsql upgraded

- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx_machine/src/emqx_machine_boot.erl
- apps/emqx_modules/src/emqx_telemetry.erl
- rebar.config.erl
1. Make some essential applications permanent, so the node doesn't remain in the zombie state if any of these apps crash (it may hide errors)
2. Make initialization of some non-essential applications async
3. Fix crash in `emqx_shared_sub` process that is unable to handle table schema change
> Improve EMQX startup sequence

- apps/emqx_bridge/etc/emqx_bridge.conf
- apps/emqx_bridge/i18n/emqx_bridge_http_schema.conf
- apps/emqx_bridge/i18n/emqx_bridge_schema.conf
- apps/emqx_bridge/i18n/emqx_bridge_webhook_schema.conf
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/src/emqx_bridge_schema.erl
- apps/emqx_bridge/src/emqx_bridge_webhook_schema.erl
- apps/emqx_bridge/test/emqx_bridge_SUITE.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_connector/i18n/emqx_connector_mqtt_schema.conf
- apps/emqx_connector/src/emqx_connector_schema.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
- apps/emqx_rule_engine/etc/emqx_rule_engine.conf
- apps/emqx_rule_engine/i18n/emqx_rule_api_schema.conf
- apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
- apps/emqx_rule_engine/include/rule_engine.hrl
- apps/emqx_rule_engine/src/emqx_rule_actions.erl
- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_SUITE.erl
- rename `output` -> `action` from all APIs, configs and codes (emqx_rule_engine).
- rename http_bridge to webhook, and rename the type of webhook bridge `http` -> `webhook` from all APIs, configs and codes (emqx_bridge).
> refactor(rule): rename outputs -> actions

- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/elixir_apps_check.yaml
- .github/workflows/release.yaml
- .github/workflows/run_fvt_tests.yaml
- Makefile
- apps/emqx/src/emqx_release.erl
- apps/emqx/test/emqx_pool_SUITE.erl
- apps/emqx_rule_engine/rebar.config
- build
- mix.exs
- rebar.config.erl
- scripts/buildx.sh
- scripts/check-elixir-applications.exs
- scripts/pkg-tests.sh
- scripts/relup-base-packages.sh
Prior to EMQX 5.0, the edge edition's main difference comaring
to standard edition are:
* Less number of plugins in the release (smaller package size)
* Smaller number is vm.args (for lower memory usage)
Starting from 5.0 most of the plugins are included as features,
the tuned vm.args arguments does not justify a special release edition.
Also as nanomq is getting mature,
EMQ's recommendtation for MQTT broker in edge is https://nanomq.io/
> refactor: stop releasing edge edition

- .github/workflows/build_packages.yaml
- scripts/buildx.sh
when 4.4 was created, OTP 24 was quite new and we were not entirely sure which one will be more stable,
so it was release on both 23 and 24.
now it's becoming clear that we'll not go back to OTP23, we can stop releasing the packages on it.
> ci: For 4.4, release package on OTP 24 only

- .github/workflows/elixir_apps_check.yaml
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
With the change to using `MIX_ENV` for choosing a profile, the CI
check became out of date.
> ci(elixir): use `MIX_ENV` profiles for machine boot checks

- apps/emqx_conf/src/emqx_cluster_rpc.erl
we already copy the config from core node, we need to keep the commit fresh too.
> fix: always commit to TargetTnxId when init

- scripts/pkg-tests.sh
quic listener is now not enabled by default
> ci: do not configure quic listener for arm

- apps/emqx_authn/src/simple_authn/emqx_authn_mongodb.erl
Since these fields are not required, it's reasonable to set defaults for them.
> chore(mongodb authn): add defaults for field names

- deploy/charts/emqx/templates/StatefulSet.yaml
As discussed, the specific helm chart issue and how to fix it:
--
The root of the issue is that StatefulSet.yaml > volumeClaimTemplates has:
[helm.sh/chart:](http://helm.sh/chart:) {{ include "emqx.chart" . }}
Which is not allowed, since a statefulset's volumeClaimTemplates template cannot change (and it will change when an upgrade is performed).
--
How to fix:
In the file SatefulSet.yaml > spec > volumeClaimTemplates > metadata > labels, the following line must be deleted:
[helm.sh/chart:](http://helm.sh/chart:) {{ include "emqx.chart" . }}
--
> fix(helm): delete needless labels for helm upgrade

- apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_authn/src/emqx_authn_schema.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_http.erl
- apps/emqx_authz/src/emqx_authz_schema.erl
- apps/emqx_authz/test/emqx_authz_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
- apps/emqx_auto_subscribe/src/emqx_auto_subscribe_schema.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_connector/src/emqx_connector_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_exhook/src/emqx_exhook_schema.erl
- apps/emqx_gateway/src/emqx_gateway_schema.erl
- apps/emqx_modules/src/emqx_modules_schema.erl
- apps/emqx_plugins/src/emqx_plugins_schema.erl
- apps/emqx_prometheus/src/emqx_prometheus_schema.erl
- apps/emqx_psk/src/emqx_psk_schema.erl
- apps/emqx_retainer/src/emqx_retainer_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- apps/emqx_slow_subs/src/emqx_slow_subs_schema.erl
1. Don't `-import(hoconsc, [mk/1, mk/2, ref/1, ref/2, array/1, enum/1]).` replace this with: macro https://github.com/emqx/hocon/pull/182
2. Add default/example for schema.
> fix: add default&example for schema

- .github/workflows/build_packages.yaml
- .github/workflows/run_fvt_tests.yaml
- Makefile
- build
- deploy/docker/Dockerfile.alpine
And add new tag for alpine image
1. The docker official image uses debian, and `emqx/emqx` can be unified with it
2. Debian has an advantage over alpine in terms of sysctl and daily toolsets
3. We have emqx debian zip package, so debian image can use hot upgrade
> build(docker): change docker base image to debian

- deploy/docker/docker-entrypoint.sh
Prior to this commit (also 4.x), the docker entrypoint script
sets default node name to $(hostname), which is typically a hash
like '6ec088117e14' and the erlang distribution port (ekka_epmd)
and gen_rpc port becomes non-deterministic.
After this commit, docker nodes start by default as name `emqx`,
so that the ports are static unless name is specifically set by
user. (4370 for erlang distribution and 5370 for gen_rpc)
> fix: run emqx in docker with 'emqx' as node name by default

- .github/workflows/apps_version_check.yaml
Often we have to remember to update both local tags and local
dependencies, and even so local results might differ from what the CI
check expects.  To help fixing expected appup file differences, we can
upload what CI produced to apply to our branch.
> ci(appup): upload appup files when ci check fails

- scripts/relup-base-packages.sh
We may get a redirect to a final 404.
> ci(relup): fix: follow URL redirects when checking for package existence

- Makefile
- rebar.config.erl
we don't have a frontend to display the example configs yet.
and having it in `emqx_dashboard` application's priv dir (and 3 level deeper) is not easy for uses to find.
This PR adds a copy of the generated files to EMQX's etc dir
> build: copy example config to etc dir

- apps/emqx/src/emqx_limiter/src/emqx_htb_limiter.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter_server.erl
- apps/emqx/test/emqx_ratelimiter_SUITE.erl
When the global rate is less than 1/s, the bad code produces a long period, this will make the rate not correct
> fix(limiter): fix precision issue

- Dockerfile.ubuntu20.04.runner
- Dockerfile.ubuntu20.04.runner.dockerignore
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_metrics_worker.erl
- apps/emqx/test/emqx_bpapi_static_checks.erl
- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf.erl
- apps/emqx_conf/src/proto/emqx_conf_proto_v1.erl
- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
- apps/emqx_connector/test/emqx_connector_SUITE.erl
- apps/emqx_gateway/src/emqx_gateway_http.erl
- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/src/proto/emqx_mgmt_api_plugins_proto_v1.erl
- apps/emqx_plugin_libs/src/emqx_plugin_libs_rule.erl
- apps/emqx_plugins/src/emqx_plugins.erl
- apps/emqx_plugins/test/emqx_plugins_tests.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/proto/emqx_resource_proto_v1.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/proto/emqx_rule_engine_proto_v1.erl
- scripts/make-docker-image-from-host-build.sh
- scripts/start-two-nodes-in-docker.sh
Avoid applying multiple cluster RPCs in one transaction, because
* Cluster RPC callbacks (MFAs) are not idempotent, the same call applies twice or more can become an error
* Due to the fact that there is a lack of rollback for MFA's side-effects
For instance, when two nodes try to add a cluster-singleton concurrently,
one of them will have to wait for the table lock,
then try to catch-up, then try to initiate the same multicall.
The catch-up will have the singleton created, but then doing the same multicall
will fail causing the cluster PRC's commit to rollback (in a transaction), but without 'undo'-ing the singleton.
Later, the retries of the catchups will fail indefinitely.
This fix is to avoid initiating a new transaction, return the failure immediately.
Ideally should be a 409, but …
> fix(cluster_rpc): config update race condition

- CHANGES-4.3.md
- src/emqx.app.src
- src/emqx.appup.src
- src/emqx_metrics.erl
- test/emqx_broker_SUITE.erl
Since MQTT 3.1 uses a different reason code for auth failures, it was
failing to increase the corresponding metric that works for MQTT 5.0.
> fix(metrics): inc `connack.auth_error` when using MQTT 3.1

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_management.appup.src
- scripts/update_appup.escript
prior to this fix. the script would scan _build dirs inside _build dir
> build: ignore _build sub-dir in release dir

- scripts/apps-version-check.sh
Often we forget that an app version is already bumped and end up bumping it twice.
> build: add strict-semver version bump check for apps

- apps/emqx/src/emqx_metrics.erl
- apps/emqx/test/emqx_broker_SUITE.erl
Since MQTT 3.1 uses a different reason code for auth failures, it was
failing to increase the corresponding metric that works for MQTT 5.0.
> fix(metrics): inc `connack.auth_error` when using MQTT 3.1 (5.0)

- apps/emqx/src/emqx_authentication.erl
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
When updating a config, It's hard to `stop` emqx_cluster_rpc from retrying on the replicate nodes, so the errors will be printed over and over again (in most cases the problem will never be solved without a human intervention).
For now, the only thing we can do is to slowdown the printing of error messages.
> Change the default retry_interval of cluster_rpc call to 1min

- deploy/charts/emqx/templates/StatefulSet.yaml
There is a risk that preStop will fail. When persistence is enabled, preStop failure can lead to inconsistent emqx cluster data
> chore(helm): delete preStop command

- apps/emqx_connector/include/emqx_connector.hrl
- apps/emqx_connector/src/emqx_connector_schema_lib.erl
The code was carefully crafted to catch all exceptions except that the `try xxxx of` does not catch exceptions in the clauses.
Also the wrapping tuple of `{error, Message}` is not necessary, `throw`s are caught by hocon and treated as a regular error reason.
> chore(connector): schema validator throw error messages directly

- apps/emqx_connector/src/emqx_connector_redis.erl
- apps/emqx_gateway/src/emqx_gateway_api_listeners.erl
- apps/emqx_gateway/src/emqx_gateway_insta_sup.erl
- apps/emqx_gateway/test/emqx_exproto_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_SUITE.erl
- apps/emqx_gateway/test/emqx_sn_protocol_SUITE.erl
- fix(redis): make sentinel required
- fix(gw): fix list listeners failed if gateway disabled
- feat(gw): keep authenticator resource after gateway disabled
- fix(gw): not updating the authenticator using re-creation
> Gateway restart won't make built-in-database data lost

- apps/emqx_conf/src/emqx_cluster_rpc.erl
The RPC initialisation failure should not trigger an alarm.
> fix(cluster_rpc): no alarm when failed to initiate RPC call

- apps/emqx/i18n/emqx_schema_i18n.conf
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/proto/emqx_broker_proto_v1.erl
- apps/emqx_management/src/emqx_mgmt_api_listeners.erl
- mix.exs
- rebar.config
We need to save the action status to enabled fields.
Before: if we stop listeners and reboot node,  the listener will start again.
After: the stopped listeners will not restart when the node reboot.
> feat: add enabled for listeners

- apps/emqx/include/emqx_hooks.hrl
- apps/emqx/src/emqx.erl
- apps/emqx/src/emqx_authentication.erl
- apps/emqx/src/emqx_hooks.erl
- apps/emqx/src/emqx_sys.erl
- apps/emqx/test/emqx_SUITE.erl
- apps/emqx/test/emqx_hooks_SUITE.erl
- apps/emqx/test/props/prop_emqx_sys.erl
- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_auto_subscribe/src/emqx_auto_subscribe.erl
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_exhook/src/emqx_exhook_mgr.erl
- apps/emqx_exhook/src/emqx_exhook_server.erl
- apps/emqx_gateway/test/emqx_coap_SUITE.erl
- apps/emqx_gateway/test/emqx_exproto_SUITE.erl
- apps/emqx_modules/src/emqx_delayed.erl
- apps/emqx_modules/src/emqx_rewrite.erl
- apps/emqx_modules/src/emqx_topic_metrics.erl
- apps/emqx_modules/test/emqx_delayed_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_SUITE.erl
- apps/emqx_psk/src/emqx_psk.erl
- apps/emqx_retainer/src/emqx_retainer.erl
- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_slow_subs/src/emqx_slow_subs.erl
- lib-ee/emqx_license/src/emqx_license.erl
```
%% Definitions for Hook Priorities
%% == Highest Priority
-define(HP_PSK, 1000).
-define(HP_REWRITE, 1000).
-define(HP_AUTHN, 990).
-define(HP_AUTHZ, 980).
-define(HP_SYS_MSGS, 960).
-define(HP_TOPIC_METRICS, 950).
-define(HP_RETAINER, 940).
-define(HP_AUTO_SUB, 930).
-define(HP_RULE_ENGINE, 900).
%% apps that can work with the republish action
-define(HP_SLOW_SUB, 980).
-define(HP_BRIDGE, 970).
-define(HP_DELAY_PUB, 960).
%% apps that can stop the hooks
-define(HP_EXHOOK, 100).
%% == Lowest Priority
```
> feat: fix the hook priorities

- apps/emqx/rebar.config
- apps/emqx_conf/i18n/emqx_conf_schema.conf
- apps/emqx_conf/src/emqx_conf_schema.erl
- deploy/charts/emqx/templates/StatefulSet.yaml
- mix.exs
- rebar.config
- scripts/make-docker-image-from-host-build.sh
- scripts/test-node-discovery-dns.sh
The configs `cluster.dns.app` and `cluster.k8s.app_name` were troublemakers.
It is runtime resolvable, however users are forced to set it and it has to match EMQX node name.
for example:
https://github.com/emqx/emqx/issues/8076
> Delete app name config for k8s and dns discovery

- apps/emqx_connector/src/emqx_connector_pgsql.erl
Once the pgsql client is configured with ssl, we should force ssl to be used to
avoid fallback to tcp connection.
> chore(pgsql): mapping ssl option from 'true' to 'required'

- apps/emqx/src/emqx_misc.erl
- apps/emqx/test/emqx_misc_SUITE.erl
'as much as possible' here means `try Expr catch _:_ ` will not be 100% safe, because `Expr` may spawn another linked process and get itself killed abnormally.
> fix(pmap): try not to exit abnormal as much as possible

- apps/emqx_dashboard/src/emqx_dashboard_sup.erl
- mix.exs
- rebar.config
1. https://github.com/emqx/minirest/pull/97 fix crash log if emqx_dashboard restart.
2. don't log emqx_dashboard_listener killed.  mute the blew log by update shutdown time to brutal_kill
```
2022-06-16T23:53:24.022827+08:00 [error] Supervisor: {local,emqx_dashboard_sup}. Context: shutdown_error. Reason: killed. Offender: id=emqx_dashboard_listener,pid=<0.2198.0>.
Stop listener dashboard:http:18083 on :18083 successfully.
```
> Restart dashboard crash

- apps/emqx/src/emqx_map_lib.erl
- apps/emqx_authn/src/emqx_authn_utils.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_connector/src/emqx_connector_mongo.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_manager_sup.erl
- apps/emqx_resource/src/proto/emqx_resource_proto_v1.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
After this change, the caller of emqx_resource can create a resource without get it started, by setting the option `mongo_auth_timeout => true`.
The caller can start the resource manually at any time after creating it.
> feat: add start_after_created option to resource:create/4

- apps/emqx_plugins/src/emqx_plugins.erl
- apps/emqx_plugins/test/emqx_plugins_tests.erl
2022-06-17T09:51:59.579406+08:00 [warning] exception: exit, line: 116, mfa: minirest_handler:apply_callback/3, path: /plugins/:name/:action, reason: {timeout,{gen_server,call,[emqx_cluster_rpc,{initiate,{emqx_mgmt_api_plugins,ensure_action,[<<"emqx_plugin_template-5.0-rc.1">>,start]}},10000]}}, stacktrace: [{gen_server,call,3,[{file,"gen_server.erl"},{line,247}]},{emqx_cluster_rpc,do_multicall,5,[{file,"emqx_cluster_rpc.erl"},{line,160}]},{emqx_cluster_rpc,multicall,5,[{file,"emqx_cluster_rpc.erl"},{line,133}]},{emqx_mgmt_api_plugins,update_plugin,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,378}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,111}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,44}]},{minirest_handler,init,2,[{file,"minirest_hand …
> fix: install plugins timeout by deadlock

- apps/emqx/test/emqx_ws_connection_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_listeners.erl
Since we bave defined
- `listeners/{listener_id}/authentication` in emqx_authn_api.erl
- and `listeners/{id}/{action}` in emqx_mgmt_api_listeners.erl
The HTTP Router always dispatch the `.../authentication` request to `listeners/{id}/{action}`,
which cause a no_union_member checking error.
In this PR, we make a workaround to avoid this dispatch error
> fix(mgmt): avoid to HTTP dispatch failure due to an URI defination conflict

- scripts/pkg-tests.sh
the upgrade pacakage can only be .tar.gz package
> ci: fix relup test for package build

- apps/emqx_authn/src/emqx_authn.app.src
- apps/emqx_authn/src/emqx_authn.appup.src
- apps/emqx_authn/src/emqx_authn_utils.erl
- apps/emqx_authz/src/emqx_authz.app.src
- apps/emqx_authz/src/emqx_authz.appup.src
- apps/emqx_authz/src/emqx_authz_utils.erl
Fix the issue that resources always be started at emqx startup, even though it has been disabled.
> fix: disabled resources for authz/authn started after emqx reboot

- CHANGES-4.3.md
- lib-ce/emqx_dashboard/src/emqx_dashboard_admin.erl
FIX: https://github.com/emqx/emqx/issues/8126
If we remove default_username/password from `emqx_dashboard.conf`, 
We should make sure the dashboard starts successfully.
> fix: can't start dashboard if default_username is missing

- apps/emqx_lua_hook/src/emqx_lua_script.erl
- apps/emqx_lua_hook/test/emqx_lua_hook_SUITE.erl
- src/emqx_channel.erl
- test/emqx_broker_SUITE.erl
Following https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901178
> fix(hooks): return error on hook-removed subscription rather than deleting it

- .github/workflows/run_test_cases.yaml
- apps/emqx_authn/src/emqx_authn.appup.src
- apps/emqx_authn/src/emqx_authn_utils.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl
- apps/emqx_authn/test/emqx_authn_http_SUITE.erl
- apps/emqx_authn/test/emqx_authn_redis_SUITE.erl
- feat(authn-redis): needs to compatible with 4.x auth data
- fix(authn): correct peerhost placeholder rendering
> Authn: backword compatibility for 4.x authn data

- scripts/update-appup.sh
This can make it simpler to ensure the same OTP version that builds
the current checkout will match the one that builds the appup base,
since one may change the version locally.
> chore: copy `.tool-versions` when calculating appups

- .github/workflows/run_relup_tests.yaml
- CHANGES-5.0.md
- apps/emqx/include/emqx_release.hrl
- apps/emqx/src/emqx.app.src
- pkg-vsn.sh
- scripts/apps-version-check.sh
- scripts/relup-build/download-base-packages.sh
Announcemnet: EMQX team has decided to stop supporting relup for opensouce edition.
Going forward, it will be an enterprise only feature.
Main reason: relup requires carefully crafted upgrade instructions from ALL previous versions.
For example, 4.3 is now at 4.3.16, we have `4.3.0->4.3.16`, `4.3.1->4.3.16`, ... 16 such upgrade paths in total to maintain.
This had been the biggest obstacle for EMQX team to act agile enought in deliverying enhancements and fixes.
> 0702 no relup for opensource edition

- deploy/docker/Dockerfile
Elixir wants to run under UTF-8 locales.  Since we changed the base
runner image to Debian, we have to set those variables for it to pick
them up.
> fix(elixir): set locale for docker images (docker)

- apps/emqx/include/emqx_release.hrl
- apps/emqx_dashboard/src/emqx_dashboard.app.src
- apps/emqx_dashboard/src/emqx_dashboard.erl
So we have one place to bump all versions
> chore: move emqx API version (in generated doc) to emqx_release.hrl

- apps/emqx/rebar.config
- apps/emqx_prometheus/rebar.config
- mix.exs
- rebar.config
https://github.com/emqx/hocon/pull/207
To fix:
```
022-07-07T03:05:59.583387+00:00 [error] line: 99, mfa: emqx_dashboard_listener:regenerate_minirest_dispatch/0,
msg: regenerate_minirest_dispatch_failed, reason: [{error,{emqx_gateway_api,timeout}}], stacktrace: 
[{minirest_trails,assert_module_api_specs,1,[{file,"minirest_trails.erl"},{line,201}]},{minirest_trails,trails_schemas,1,
[{file,"minirest_trails.erl"},{line,28}]},{minirest,update_dispatch,1,[{file,"minirest.erl"},{line,44}]},{lists,foreach,2,
[{file,"lists.erl"},{line,1342}]},{emqx_dashboard_listener,regenerate_minirest_dispatch,0,
[{file,"emqx_dashboard_listener.erl"},{line,85}]},{emqx_dashboard_listener,handle_continue,2,
[{file,"emqx_dashboard_listener.erl"},{line,52}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line …
```
> chore: upgrade hocon to 0.28.3 to speed up schema cache

- CHANGES-5.0.md
- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_config_handler.erl
- apps/emqx_authn/src/emqx_authn.app.src
- apps/emqx_authn/src/simple_authn/emqx_authn_jwks_connector.erl
- apps/emqx_authn/test/emqx_authn_enable_flag_SUITE.erl
- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/emqx_connector_http.erl
- apps/emqx_connector/src/emqx_connector_mongo.erl
- apps/emqx_connector/src/emqx_connector_mysql.erl
- apps/emqx_connector/src/emqx_connector_pgsql.erl
- apps/emqx_connector/src/emqx_connector_redis.erl
- apps/emqx_plugin_libs/src/emqx_plugin_libs.app.src
- apps/emqx_plugin_libs/src/emqx_plugin_libs_pool.erl
- apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
- apps/emqx_rule_engine/src/emqx_rule_engine.app.src
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- mix.exs
- rebar.config
- [the file cluster-override.conf is emptied to 0KB if hocon_pp:do/2 failed](https://github.com/emqx/emqx/commit/b6a76a5a42f716b001d4f0e3cf0b629c517617b5)
- [refactor: improve the health_check for webhook bridges](https://github.com/emqx/emqx/commit/6b45d2ea9fde6d3b4a5b007f7a8c5a1c573d141e)
- [fix(rule): create_at lost when save to config files](https://github.com/emqx/emqx/commit/5fc09e6b950c340243d7be627a0ce1700691221c)
> Fix some issues

- CHANGES-5.0.md
- mix.exs
- rebar.config.erl
This commit upgrades the jq library to a version that has fixed an issue that caused a crash when the port program had a space
in its path.
See: https://github.com/emqx/jq/commit/024719f3254ed944f0c208eba286e185ca4cca7b
> fix: upgrade jq lib to get rid of crash when space in path

- CHANGES-5.0.md
- apps/emqx/include/emqx_release.hrl
- apps/emqx_authz/src/emqx_authz.app.src
- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_authz/test/emqx_authz_file_SUITE.erl
> fix(authz): should apply no rule on superuser

- etc/emqx.conf
The default configuration had the `cacert` option for the
`ssl.external` listener commented out.  If one is to set `verify =
verify_peer` in that listener without noticing that `cacert` is
unspecified, all connections will fail with:
```
2022-07-11T11:48:28.540807-03:00 [error] supervisor: 'esockd_connection_sup - <0.3971.0>', errorContext: connection_shutdown, reason: {ssl_error,{options,{cacertfile,[]}}}, offender: [{pid,<0.8225.13>},{name,connection},{mfargs,{emqx_connection,start_link,[[{deflate_options,[]},{max_conn_rate,10000},{active_n,100},{zone,external},{proxy_address_header,<<>>},{proxy_port_header,<<>>},{supported_subprotocols,[]}]]}}]
```
> fix: default config should specify `cacert` file (4.3)

- .ci/docker-compose-file/Makefile.local
- .ci/docker-compose-file/docker-compose-redis-sentinel-tcp.yaml
- .ci/docker-compose-file/docker-compose-redis-sentinel-tls.yaml
- .ci/docker-compose-file/docker-compose-redis-single-tcp.yaml
- .ci/docker-compose-file/redis/redis.sh
- .github/workflows/run_test_cases.yaml
- CHANGES-5.0.md
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_connector/src/emqx_connector_redis.erl
- apps/emqx_connector/test/emqx_connector_redis_SUITE.erl
redis `sentinal` name should be required.
see [Redis configuring sentinel](https://redis.io/docs/manual/sentinel/#configuring-sentinel)
`jwks` ssl options using genernal fields schema in `emqx_schema`
> fix hocon required fields

- bin/emqx
- data/emqx_vars
Move all the ENV variables that not related to the compiled vars to `emqx` script.
> fix: emqx start failed after uninstalling old version

- CHANGES-5.0.md
- apps/emqx/src/emqx_listeners.erl
- apps/emqx_dashboard/src/emqx_dashboard.erl
Starting from 5.0, the dashboard listener only supports one listener port for each listener type. For example, HTTP can only be configured with 18083, and it no longer supports configuring multiple HTTP ports. So we remove the port information from the listener name. Keep the same format as the other listeners.
```
Listener ssl:default on 8883 started.
Listener tcp:default on 1883 started.
Listener ws:default on 8083 started.
Listener wss:default on 8084 started.
Listener http:dashboard on 18083 started.
```
```
Listener ssl:default on 127.0.0.1:8883 started.
Listener tcp:default on 127.0.0.1:1883 started.
Listener ws:default on 127.0.0.1:8083 started.
Listener wss:default on 127.0.0.1:8084 started.
Listener http:dashboard on 127.0.0.1:18083 started.
```
> chore: improve the dashboard listener startup log

- CHANGES-5.0.md
- apps/emqx_dashboard/src/emqx_dashboard.appup.src
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
1. Remove `/configs/listeners`, use `/listeners/` API instead. `/configs/listeners` is introduced by accident, and the design does not make sense. To be able to handle the listeners more effectively, you can use `/listeners`.
2. Restart the dashboard application in the emqx_dashboard's appup to generate the latest routing rules and swagger.
> chore: remove /configs/listeners, use /listeners/ API instead

- deploy/docker/README.md
I found a couple of typos when reading the README on Docker Hub. This change aims to improve the markdown and wording of that document.
To understand each change better, please inspect each commit individually. 👍
> Fix typos in Docker README

- rebar.config
wolff 1.5.6 requires replayq 0.3.4
> Fix inconsistent replayq version

- CHANGES-4.3.md
- bin/emqx
As a developer, I need to test the availability of the modified configuration with a test command via CLI to avoid EMQX reboot due to configuration error.
The test command is provided to check the legality of existing configuration files and configuration items, and the data type of the configuration before starting or at runtime.
```bash
> ./bin/emqx  check_conf
xxx/etc/emqx.conf is ok
```
or
```bash
> ./bin/emqx  check_conf
2022-07-14T17:23:10.364230+08:00 [error] Error generating configuration in phase transform_datatypes
2022-07-14T17:23:10.364353+08:00 [error] Error transforming datatype for: cluster.autoheal
2022-07-14T17:23:10.364608+08:00 [error] "o1n" is not a valid enum value, acceptable values are: on, off
```
> feat: add check_conf cli to check config format
