emqx/emqx

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx_management/src/emqx_mgmt.erl
- changes/ce/fix-12740.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12020
Add very bare-bones support for kicking out durable sessions. 
Missing features:
- Hooks won't run
- Will message won't be dispatched (proper fix depends on moving will message handling from channel to session)
> fix(sessds): Channel must destroy sessions that are kicked

- apps/emqx_gateway_ocpp/rebar.config
- apps/emqx_schema_registry/rebar.config
https://emqx.atlassian.net/browse/EMQX-11881
This is a follow up fix for the json schema feature.
jesse before 1.8 uses JSON schema draft-03 as default,
1.8.0 (newly tagged) uses draft-06 as default.
-- this default value aligns with the Javascript lib used in frontend.
> chore: upgrade to jesse 1.8.0 for draft-06 as default version

- apps/emqx/rebar.config
- apps/emqx/src/emqx_ds_schema.erl
- apps/emqx/src/emqx_message.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_rpc.erl
- apps/emqx/test/emqx_bpapi_static_checks.erl
- apps/emqx/test/emqx_persistent_messages_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds.erl
- apps/emqx_durable_storage/src/emqx_ds_bitmask_keymapper.erl
- apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.hrl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_shard.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_shard_allocator.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/src/emqx_durable_storage.app.src
- apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
- apps/emqx_machine/src/emqx_machine_boot.erl
- apps/emqx_utils/src/emqx_utils_stream.erl
- apps/emqx_utils/test/emqx_utils_stream_tests.erl
- mix.exs
- rebar.config
- rel/i18n/emqx_ds_schema.hocon
Fixes [EMQX-11756](https://emqx.atlassian.net/browse/EMQX-11756).
Uses Raft through https://github.com/rabbitmq/ra to replicate writes across nodes: each shard is now a Raft consensus group. Replicas are guaranteed to not diverge, therefore we're free to pick any replica to perform reads.
This is mostly out-of-scope for this PR (maybe except for first two), but good to have written down.
1. Measure performance impact.
Read performance shouldn't really suffer. Things to explore: issue `release_cursor` less often, make smarter assumptions about shard servers, do not waste cycles on constructing names / IDs.
2. Perform rest of shard-level operations through consensus.
Namely: adding generations. At first look it seems important because of snapshotting. Initially we could make it work …
> feat(ds): implement raft-based replication

- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_session_mem.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
Expose sequence numbers, number of streams, and session durability flag in the REST API. 
> feat(sessds): Expose relevant durable session info in the REST API

- apps/emqx/src/emqx_persistent_session_ds_router.erl
- apps/emqx_management/src/emqx_mgmt_api_topics.erl
- apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl
Fixes [EMQX-12050](https://emqx.atlassian.net/browse/EMQX-12050)
Before this PR, total count of topics was not estimated properly when a query produced partial results. This is fixed by including the number of persistent router topics in `count` when session persistence is enabled.
> fix(topics-api): respond with correct totals to paged queries

- apps/emqx_utils/src/emqx_utils.erl
- apps/emqx_utils/test/emqx_utils_SUITE.erl
- changes/ce/fix-12766.en.md
`mailbox_overflow` is consistent with the corresponding config parameter:
`force_shutdown.max_mailbox_size`
Fixes EMQX-12058
> chore: rename `message_queue_too_long` to `mailbox_overflow`

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_action_info.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_kafka_tests.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- changes/ee/fix-12767.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12064
> fix(kafka_producer): handle ancient v1 config when migrating to actions

- apps/emqx/src/bpapi/emqx_bpapi.erl
```
2024-03-22T05:58:01.793548+00:00 [notice] Application: emqx. Exited: {bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{aborted,{undef,[{emqx_bpapi,announce_fun,['emqx@10.42.0.53',[{emqx,1},{emqx,2},{emqx_authn,1},{emqx_authz,1},{emqx_bridge,1},{emqx_bridge,2},{emqx_bridge,3},{emqx_bridge,4},{emqx_bridge,5},{emqx_bridge,6},{emqx_broker,1},{emqx_cm,1},{emqx_cm,2},{emqx_conf,1},{emqx_conf,2},{emqx_conf,3},{emqx_connector,1},{emqx_dashboard,1},{emqx_delayed,1},{emqx_delayed,2},{emqx_delayed,3},{emqx_ds,1},{emqx_ds,2},{emqx_ds,3},{emqx_ds,4},{emqx_eviction_agent,1},{emqx_eviction_agent,2},{emqx_exhook,1},{emqx_ft_storage_exporter_fs,1},{emqx_ft_storage_fs,1},{emqx_ft_storage_fs_reader,1},{emqx_gateway_api_listeners,1},{emqx_gateway_cm,1},{emqx_gatewa …
```
> fix: bpapi undef on old node

- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds.hrl
- apps/emqx/src/emqx_persistent_session_ds_gc_worker.erl
- apps/emqx/src/emqx_persistent_session_ds_state.erl
- apps/emqx/src/emqx_session.erl
- apps/emqx/src/emqx_session_mem.erl
- apps/emqx/src/proto/emqx_cm_proto_v3.erl
- apps/emqx/test/emqx_channel_SUITE.erl
- apps/emqx/test/emqx_cm_SUITE.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx/test/emqx_cth_suite.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx/test/emqx_session_mem_SUITE.erl
- apps/emqx/test/emqx_takeover_SUITE.erl
- apps/emqx/test/emqx_ws_connection_SUITE.erl
- apps/emqx_eviction_agent/src/emqx_eviction_agent.app.src
- apps/emqx_eviction_agent/src/emqx_eviction_agent.erl
- apps/emqx_eviction_agent/src/emqx_eviction_agent_channel.erl
- apps/emqx_eviction_agent/src/proto/emqx_eviction_agent_proto_v2.erl
- apps/emqx_eviction_agent/src/proto/emqx_eviction_agent_proto_v3.erl
- apps/emqx_gateway_mqttsn/src/emqx_mqttsn_channel.erl
- apps/emqx_gateway_mqttsn/src/emqx_mqttsn_session.erl
Fixes https://emqx.atlassian.net/browse/EMQX-10431
> feat(ds): make durable sessions handle will messages

- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx_router.erl
- apps/emqx/src/proto/emqx_router_proto_v1.erl
- apps/emqx/test/emqx_routing_SUITE.erl
- changes/ce/fix-12768.en.md
Fixes [EMQX-12068](https://emqx.atlassian.net/browse/EMQX-12068).
When the cluster is empty (more precisely, routing tables are empty), try to additionally ask the cluster nodes for the routing schema in use, to make more informed decision about routing storage schema upon startup. This should make routing storage schema less likely to diverge across cluster nodes, especially when the cluster is composed of different versions of EMQX.
> fix(routing): add heuristic for routing schema in empty cluster

- apps/emqx/src/config/emqx_config_logger.erl
- apps/emqx/src/emqx_logger_jsonfmt.erl
- apps/emqx/src/emqx_logger_textfmt.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_conf_logger_SUITE.erl
- apps/emqx_conf/test/emqx_conf_schema_tests.erl
- apps/emqx_enterprise/test/emqx_enterprise_schema_SUITE.erl
- changes/ce/feat-12785.en.md
- rel/i18n/emqx_conf_schema.hocon
now logs can be configured to use 'epoch' or 'rfc3339' time format
> feat(log): configurable time format

- .github/workflows/green_master.yaml
- scripts/spellcheck/spellcheck.sh
Fixes some issues with "Keep master green" workflow:
- it tries to rerun itself too, and when it fails, it tries again
- do not fail the job if `rerun` API call failed
- only rerun workflows which failed, do not rerun cancelled one
> ci: in Keep master green workflow, do not try to rerun self

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
Port of #12755 to r56
Fixes https://emqx.atlassian.net/browse/EMQX-12049
Release version: e5.6.1
> fix(kafka-based bridges): avoid trying to get raw config for replayq dir

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_data_backup.erl
- apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl
- changes/ce/fix-12759.en.md
Port of https://github.com/emqx/emqx/pull/12759/files
Fixes EMQX-11808
> fix(emqx_mgmt_data_backup): remove an uploaded backup file if it's not valid (5.6.1 port)

- apps/emqx_utils/src/emqx_utils.app.src
- apps/emqx_utils/src/emqx_utils.erl
- apps/emqx_utils/test/emqx_utils_SUITE.erl
- changes/ce/fix-12766.en.md
5.6.1 port of: https://github.com/emqx/emqx/pull/12766  
`mailbox_overflow` is consistent with the corresponding config parameter:
'force_shutdown.max_mailbox_size'
Fixes EMQX-12058
> chore: rename `message_queue_too_long` error reason to `mailbox_overflow` (5.6.1 port)

- .github/workflows/green_master.yaml
Fixes an issue when this workflow sometimes causes legitimate runs being cancelled.
> ci(green_master): only trigger reruns for master branch

- apps/emqx/rebar.config
- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
- changes/ce/fix-12802.en.md
- mix.exs
- rebar.config
> prevent a left node from rejoining the same cluster

- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- changes/ce/fix-12814.en.md
1. The exit reason is expected to include gen_server `Location`:
`{{shutdown, OOMInfo}, Location}`.
2. Handle call client timeouts
Fixes EMQX-12124
> fix(emqx_mgmt): catch OOM shutdown exits properly when calling a conn procces

- .github/workflows/run_emqx_app_tests.yaml
```
Error when evaluating 'strategy' for job 'run_emqx_app_tests'. emqx/emqx/.github/workflows/run_emqx_app_tests.yaml@689347f60e5e2e5fc612aa0282c74c0eb26e8281 (Line: 65, Col: 9): Matrix must define at least one vector
```
> ci(fix): skip flow when there are no changes

- apps/emqx/test/emqx_persistent_messages_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_shard.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_shard_allocator.erl
- apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
Fixes [EMQX-12110](https://emqx.atlassian.net/browse/EMQX-12110).
Basic operation is `assign_db_sites/2` that could be employed in both lazy and transactional fashion, where the latter could be optimized for minimal set of membership changes.
> feat(dsrepl): add APIs to manage DB replication sites

- apps/emqx_bridge_cassandra/rebar.config
PR: https://github.com/emqx/ecql/pull/13
No functional changes, just switch gen_fsm to gen_statem.
Fixes [EMQX-7594](https://emqx.atlassian.net/browse/EMQX-7594)
> chore: bump ecql version to 0.7.0

- .ci/docker-compose-file/docker-compose-greptimedb.yaml
- apps/emqx_bridge_greptimedb/rebar.config
- apps/emqx_bridge_greptimedb/test/emqx_bridge_greptimedb_SUITE.erl
- mix.exs
* The `greptimedb-client-erl` was renamed into `greptimedb-ingester-erl`. This PR changes nothing but uses the latest version of `greptimedb-ingester-erl` and keeps backward compatibility.
* Updated the `greptimedb` image version in CI too.
> feat: update greptimedb client lib and ci version

- .github/workflows/run_docker_tests.yaml
- scripts/ui-tests/dashboard_test.py
- scripts/ui-tests/docker-compose.yaml
Fixes an issue when link to documentation in dashboard may not be up to date.
> ci: add selenium test for emqx docs link in dashboard

- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf.app.src
- changes/ce/fix-12843.en.md
Fixed an issue where `cluster_rpc_commit` tnx_id was not properly cleaned up on replicator nodes after using the 'cluster leave' command.
1. Deploy an EMQX core node and replication node in a cluster.
2. Use the 'emqx ctl cluster leave' command on the replicator node to remove it from the cluster.
3. Attempt to update configuration via dashboard on the core node.
> fix: clean self node's cluster commit when leave cluster

- apps/emqx/rebar.config
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
- mix.exs
- rebar.config
Follow-up fix for EMQX-11826 (unreleased yet).
Now, if the core node is manually removed from the cluster, other replicants will not join it: https://github.com/emqx/mria/pull/178
>  prevent replicants from rejoining a left core

- .ci/docker-compose-file/rocketmq/conf/plain_acl.yml
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq.app.src
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl
- apps/emqx_bridge_rocketmq/test/emqx_bridge_rocketmq_SUITE.erl
- changes/ee/fix-12882.en.md
This PR makes sure that a set of rocketmq workers are started for each topic. Before this commit all actions for a rocketmq connector used the same workers which all were bound to a single topic so all messages got delivered to that topic regardless of the action configuration.
We should have automatic tests to check that the messages actually go to different topics but this needs to go into another PR since we have to deliver the fix fast and the rocketmq library does not support reading from topics.
Fixes:
https://emqx.atlassian.net/browse/EEC-1006
Release version: e5.6.1
- [] …
> fix(rocketmq action): all actions used only one topic

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_client_SUITE.erl
- apps/emqx/test/emqx_config_SUITE.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_utils/src/emqx_variform.erl
- apps/emqx_utils/src/emqx_variform_bif.erl
- apps/emqx_utils/test/emqx_variform_bif_tests.erl
- apps/emqx_utils/test/emqx_variform_tests.erl
- changes/ce/feat-12750.en.md
- changes/ce/feat-12872.en.md
- rel/i18n/emqx_schema.hocon
- scripts/spellcheck/dicts/emqx.txt
Fixes [EMQX-11882](https://emqx.atlassian.net/browse/EMQX-11882)
This PR rewrites https://github.com/emqx/emqx/pull/12750 which is not released yet.
- Allow multiple `client_attrs` initial extractions
- Support using variform for `client_attrs` initial extraction
- Provide regexp based extraction as a variform function (so the config schema introduced in #12750 is rewritten)
[EMQX-11882]: https://emqx.atlassian.net/browse/EMQX-11882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 0412 use variform for client_attrs

- apps/emqx_eviction_agent/src/emqx_eviction_agent.app.src
- apps/emqx_node_rebalance/src/emqx_node_rebalance.app.src
- apps/emqx_node_rebalance/src/emqx_node_rebalance_api.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_SUITE.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_agent_SUITE.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_api_SUITE.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_cli_SUITE.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_evacuation_SUITE.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_purge_SUITE.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_status_SUITE.erl
- changes/ee/fix-12871.en.md
- mix.exs
- rebar.config.erl
Fixes [EMQX-12184](https://emqx.atlassian.net/browse/EMQX-12184)
- [na] Changed lines covered in coverage report
[EMQX-12184]: https://emqx.atlassian.net/browse/EMQX-12184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(rebalance): fix start order of rebalance applications

- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds.hrl
- apps/emqx/src/emqx_persistent_session_ds_state.erl
- apps/emqx/src/emqx_persistent_session_ds_stream_scheduler.erl
- apps/emqx/src/emqx_persistent_session_ds_subs.erl
- apps/emqx/src/emqx_session.erl
- apps/emqx/test/emqx_persistent_session_ds_state_tests.erl
- apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_SUITE.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
- apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl
- apps/emqx_bridge_pgsql/test/emqx_bridge_pgsql_SUITE.erl
- apps/emqx_durable_storage/README.md
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
- apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- changes/ce/fix-12874.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12030 https://emqx.atlassian.net/browse/EMQX-12032 https://emqx.atlassian.net/browse/EMQX-12200
- Track PacketIDs of unacked QoS2 PUBLISH messages received from the client
- Add REST API for listing the durable subscriptions
- Fix inconsistent behavior in regard to overlapping subscriptions
- Separate subscription object from the immutable subscription state object
- Improve REST API response for offline durable sessions
> API for durable subscriptions

- apps/emqx/include/emqx_trace.hrl
- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx/src/emqx_trace/emqx_trace_handler.erl
- apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
- apps/emqx/test/emqx_trace_SUITE.erl
- apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
- apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_trace.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl
- changes/ce/feat-12863.en.md
- rel/i18n/emqx_mgmt_api_trace.hocon
This PR makes it possible to select the JSON trace log entry formatter when crating a trace pattern. This will make it easier for the dashboard and automatic tests to parse the log entries.
Fixes: EMQX-12025 (partly)
> feat(emqx_trace): add JSON trace log entry formatter

- apps/emqx/rebar.config
- changes/ee/fix-12909.en.md
- mix.exs
- rebar.config
https://github.com/emqx/esockd/pull/187
> fix: bump escokd to 5.11.2 to handle udp_error/closed message

- apps/emqx/include/logger.hrl
> refactor: avoid evaluating Data more than once in SLOG_THROTTE macro

- deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
- deploy/charts/emqx/templates/StatefulSet.yaml
Fixes 
Add the latest optional features of the [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to the Helm Charts under the `topologySpreadConstraints` key. 
> feat(charts): extend pod topology spread constraints

- apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
- apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl
- changes/ce/fix-12932.en.md
Previously, if a HTTP action request received a 503 (Service Unavailable) status, it was marked as a failure without retrying. This has now been fixed so that the request is retried a configurable number of times.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12217
https://github.com/emqx/emqx/issues/12869 (partly)
> fix(HTTP connector): retry on 503 Service Unavailable response

- apps/emqx/priv/bpapi.versions
- apps/emqx_dashboard_sso/src/emqx_dashboard_sso_saml.erl
- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/src/proto/emqx_mgmt_api_plugins_proto_v2.erl
- apps/emqx_management/src/proto/emqx_mgmt_api_plugins_proto_v3.erl
- apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl
- apps/emqx_plugins/include/emqx_plugins.hrl
- apps/emqx_plugins/rebar.config
- apps/emqx_plugins/src/emqx_plugins.app.src
- apps/emqx_plugins/src/emqx_plugins.erl
- apps/emqx_plugins/src/emqx_plugins_serde.erl
- apps/emqx_plugins/src/emqx_plugins_sup.erl
- apps/emqx_plugins/test/emqx_plugins_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_tests.erl
- changes/feat-12910.en.md
Fixes [EMQX-12187](https://emqx.atlassian.net/browse/EMQX-12187)
[EMQX-12187]: https://emqx.atlassian.net/browse/EMQX-12187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(plugin): avro config schema store and encode/decode

- mix.exs
- rebar.config
a minor enhancement: rule SQL without WHERE or FROM will
return "Missing FROM or WHERE" instead of "syntax error before {SELECT"
see also: https://github.com/emqx/rulesql/pull/13
> chore: upgrade to rulesql 0.2.1 (from 0.2.0)

- apps/emqx/src/emqx_tls_lib.erl
- apps/emqx/test/emqx_tls_lib_tests.erl
- changes/ce/fix-12962.en.md
Fixes [EMQX-12214](https://emqx.atlassian.net/browse/EMQX-12214)
Support wildcard certificates.
Tested manually with testing wildcard certificate issued to `*.local.net`.
[EMQX-12214]: https://emqx.atlassian.net/browse/EMQX-12214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ssl-clients): allow wildcard certificates by default

- apps/emqx/include/emqx_trace.hrl
- apps/emqx/src/emqx_logger_jsonfmt.erl
- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
- apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
- apps/emqx_bridge/test/emqx_bridge_testlib.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl
- apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
- apps/emqx_bridge_redis/src/emqx_bridge_redis_connector.erl
- apps/emqx_bridge_s3/src/emqx_bridge_s3_connector.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
- apps/emqx_postgresql/src/emqx_postgresql.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_rule_engine/src/emqx_rule_actions.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
* Better rule trace formatting for many trace entries
* The republish and console actions have got working stop after rendering functionality
* (bugfix): make sure we return something JSON compatible when calling the rule apply API
* (bugfix): trace should be working immediately after the API call to create it returns
Fixes:
https://emqx.atlassian.net/browse/EMQX-12275
https://emqx.atlassian.net/browse/EMQX-12276
> fix: rule trace formatting, republish and console stop after rendering

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- changes/ee/feat-12959.en.md
- mix.exs
- rel/i18n/emqx_bridge_azure_event_hub.hocon
- rel/i18n/emqx_bridge_confluent_producer.hocon
- rel/i18n/emqx_bridge_kafka.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12241
This allows more accurate health checking for Kafka Producers.  Without a topic, it's not possible to actually probe the connection to partition leaders, so the connector might not be reported as `disconnected` without testing a concrete topic.
> feat(kafka producer): add health check topic option

- apps/emqx_dashboard/etc/emqx_dashboard.conf
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
- rel/config/examples/dashboard-with-https.conf.example
- rel/i18n/emqx_dashboard_schema.hocon
[EMQX-12292](https://emqx.atlassian.net/browse/EMQX-12292)
Refactor dashboard listener config.
Make it easier to enable `https` listener.
Also updated the example config. 
[EMQX-12292]: https://emqx.atlassian.net/browse/EMQX-12292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: simplify https listener config for dashboard

- apps/emqx_auth/src/emqx_auth.app.src
- apps/emqx_auth/src/emqx_auth_utils.erl
- apps/emqx_auth/src/emqx_authn/emqx_authn_utils.erl
- apps/emqx_auth_http/src/emqx_authn_http.erl
- apps/emqx_auth_http/src/emqx_authz_http.erl
- apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl
- apps/emqx_auth_http/test/emqx_authz_http_SUITE.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl
- apps/emqx_bridge_es/src/emqx_bridge_es_connector.erl
- apps/emqx_bridge_http/src/emqx_bridge_http_action_info.erl
- apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
- apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl
- apps/emqx_bridge_http/test/emqx_bridge_http_connector_tests.erl
- apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
- apps/emqx_connector/src/emqx_connector_resource.erl
- apps/emqx_utils/rebar.config
- apps/emqx_utils/src/emqx_utils.app.src
- apps/emqx_utils/src/emqx_utils_uri.erl
- changes/ce/fix-12971.en.md
Fixes [EMQX-12257](https://emqx.atlassian.net/browse/EMQX-12257)
This PR addresses three entangled problems.
---
The first one is directly described in the task above. We have templated URIs in many parts of the code, and URI templates cannot be parsed with the standard URI parser (`uri_string`). So, multiple ad-hoc simplified parses are created, which may be error-prone. 
**We solve this by introducing a single loose parser** `emqx_utils_uri`.
---
The second one comes from the fact that the path that forms a part of the URI and the path that forms the "request-target" in the corresponding HTTP request are different concepts. The former may not start with a slash, while the latter MUST be absolute.
For example, in the valid URI `http://example.com?q=x`, the path …
> fix(auth,http): improve URI handling

- apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
- apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra_connector.erl
- apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse_connector.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl
- apps/emqx_bridge_es/src/emqx_bridge_es_connector.erl
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl
- apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb_connector.erl
- apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl
- apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
- apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis_impl_producer.erl
- apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb_connector.erl
- apps/emqx_bridge_opents/src/emqx_bridge_opents_connector.erl
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl
- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector.erl
- apps/emqx_mysql/src/emqx_mysql.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_test_connector.erl
This PR contains three fixes:
* [fix(rule tracing): format result traces in a more structured way](https://github.com/emqx/emqx/commit/ca88f5731ba2c4b1b3bbe6edc65ed852eae209fd)
* [fix(rule tracing): clean up error tuple in the action_failed trace](https://github.com/emqx/emqx/commit/feecc36607e8b215188898d72de9e2b621e215ac)
* [fix(rule tracing): make sure that recoverable errors are traced](https://github.com/emqx/emqx/pull/12981/commits/09ee7ec0e22341ebfdc83c89f87e37c2b3e51d49)
Fixes:
https://emqx.atlassian.net/wiki/spaces/MP/pages/980516948/Acceptance+report#%E2%9D%8C-InfluxDB
- [] Added property-based tests for code which performs …
> Make formatting of action result trace entries better

- apps/emqx_message_validation/src/emqx_message_validation.erl
`load/0` and `unload/0` shouldn't call cluster operations.
> fix(message validation): don't call `emqx_conf:update` during boot

- apps/emqx_message_validation/src/emqx_message_validation.erl
- apps/emqx_message_validation/src/emqx_message_validation_schema.erl
- apps/emqx_message_validation/test/emqx_message_validation_http_api_SUITE.erl
- apps/emqx_message_validation/test/emqx_message_validation_tests.erl
- rel/i18n/emqx_message_validation_schema.hocon
On Product's behest, to make naming consistent with protobuf nomenclature.
https://protobuf.dev/programming-guides/proto3/#adding-types
> refactor(message validation): rename `message_name` to `message_type`

- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds_stream_scheduler.erl
Use milder log level for regular error conditions, especially when such events are emitted in (potentially) tight loops, i.e. pulling messages from iterators pointing to remote shards.
> fix(sessds): use milder log level for regular error conditions

- apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_connector.erl
- apps/emqx_bridge_syskeeper/test/emqx_bridge_syskeeper_SUITE.erl
- changes/ee/fix-13001.en.md
> fix(sysk): fix that the syskeeper forwarding never reconnecting

- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- apps/emqx_utils/src/emqx_variform_bif.erl
The rule engine unescape function should convert the escape sequence \a to the alarm bell symbol (ASCII 7). This bug was created as it was assumed that Erlang convert $\a to 7 but Erlang does not handle the \a escape sequence and instead convert it to 97 (ASCII code for a).
I think the unescape rule engine function (introduced in this PR from mars https://github.com/emqx/emqx/pull/12671) is not released so release notes should not be needed?
Fixes:
https://emqx.atlassian.net/browse/EMQX-12313
- [] Change log has been added to …
> fix: make rule engine unescape convert \a to the terminal alarm char

- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_listeners_update_SUITE.erl
- changes/ce/fix-13012.en.md
Previously when changing the access_rules configuration option of a listener to something that was not a valid rule, the listener would crash. This has now been fixed by the addition of a configuration validator that checks the access_rules field.
Additionally, a configuration option converter has been added to the access_rules field so that one can specify several rules in a single string by using "," (comma) as separator.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12315
- [] For internal contributor: there …
> fix: listener crash if access_rules config option is incorrect

- apps/emqx_gateway_jt808/src/emqx_gateway_jt808.app.src
- apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl
- apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl
- changes/ee/fix-13010.en.md
Fixes [EMQX-12343](https://emqx.atlassian.net/browse/EMQX-12343)
[EMQX-12343]: …
> fix(gw): jt808 REG_ACK failed due to faulty clientinfo

- apps/emqx/rebar.config
- apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
- apps/emqx_durable_storage/src/emqx_ds_builtin_metrics.erl
- apps/emqx_durable_storage/src/emqx_ds_builtin_sup.erl
- apps/emqx_durable_storage/src/emqx_ds_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.hrl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_shard.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/test/emqx_ds_replication_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl
- apps/emqx_utils/src/emqx_utils_stream.erl
- apps/emqx_utils/test/emqx_utils_stream_tests.erl
- mix.exs
- rebar.config
Fixes [EMQX-12198](https://emqx.atlassian.net/browse/EMQX-12198)
This PR fixes clock skew issues that could lead to the loss of messages during replay of the messages in the current epoch of LTS storage.
On the storage layer, this PR also separates preparation of the batch from committing it. 
[EMQX-12198]: https://emqx.atlassian.net/browse/EMQX-12198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use leader's clock when calculating LTS cutoff timestamp

- apps/emqx_auth/etc/acl.conf
- changes/ce/fix-13024.en.md
Fixes: https://emqx.atlassian.net/browse/EMQX-12362
Prior to this change, EMQX default ACL has a deny rule to reject subscribing to `#`.
For completeness, the default ACL should also deny `+/#` because they are essentially equivalent.
The eunit tests do not seem to cover default ACL rules, automation will be covered in QA env, here is a manual test result:
```
mqttx sub -t '+/#' -h 192.168.31.216 -p 1883
[5/13/2024] [9:34:54 AM] › …  Connecting...
[5/13/2024] [9:34:54 AM] › ✔  Connected
[5/13/2024] [9:34:54 AM] › …  Subscribing to +/#...
[5/13/2024] [9:34:54 AM] › ✔  Subscribed to +/#
[5/13/2024] [9:34:54 AM] › ✖  Subscription negated to +/# with code 135
```
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over …
> fix: deny subscribing to +/# by default ACL

- apps/emqx/src/emqx_persistent_message.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
Fixes [EMQX-12291](https://emqx.atlassian.net/browse/EMQX-12291).
Otherwise, persistent sessions will not be able to receive $SYS messages whatsoever.
[EMQX-12291]: https://emqx.atlassian.net/browse/EMQX-12291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(sessds): persist $SYS messages as well

- apps/emqx_postgresql/rebar.config
- changes/ee/fix-13018.en.md
- mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-12334
See also: https://github.com/emqx/epgsql/pull/10
> fix(postgres): reduce log spamming when connection goes down

- scripts/spellcheck/spellcheck.sh
Example:
```sh
ͳ scripts/spellcheck/spellcheck.sh -j 20 _build/docgen/emqx-enterprise/schema-en.json
Adding /dicts/emqx.txt
Starting LanguageTool server...
+ java -Xms256m -Xmx512m -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8010 --public --allow-origin '*' --config config.properties
Checking /schema.json with 20 processes...
Spellcheck OK
```
> ci: allow customizing number of jobs when running locally

- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl
- rel/i18n/emqx_rule_api_schema.hocon
Before this commit, the backend could not handle the test context for message_validation_failed events that could be sent from the dashboard since no handling code for this contexts existed in the backend. This has now been fixed by adding such handling code.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12354
- [] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link …
> fix: add handling of message_validation_failed ctx for rule testing

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
For Kafka that has its internal buffering the on_query_async callback is used both for sync and async queries (for sync queries the caller waits for a response directly after calling on_query_async). Therefore, before this commit, the trace included incorrect query type information. This has been fixed by removing the query type information from the trace. This should be okay since the query type is not essential information and can be derived from the configuration.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12363
- [] …
> fix(kafka trace): do not include query type in trace entry

- apps/emqx_auth_mongodb/test/emqx_authn_mongodb_SUITE.erl
- apps/emqx_auth_mongodb/test/emqx_authz_mongodb_SUITE.erl
This PR adds test cases that check that the authn and authz modules for MongoDB support the use_legacy_protocol configuration option.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12245
> test(mongodb authn, authz): add test cases for use_legacy_protocol

- apps/emqx/src/emqx_ds_schema.erl
This PR modifies the default values related to the replication.
> fix(ds): Change the default number of shards to 12

- apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_dummy.erl
- apps/emqx_utils/src/emqx_utils_stream.erl
- apps/emqx_utils/test/emqx_utils_stream_tests.erl
Fixes [EMQX-12367](https://emqx.atlassian.net/browse/EMQX-12367)
Release version: v5.8.0/e5.8.0
- [na] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
[EMQX-12367]: https://emqx.atlassian.net/browse/EMQX-12367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Get rid of qlc in retainer

- apps/emqx/include/emqx_persistent_message.hrl
- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/src/emqx_persistent_message.erl
- apps/emqx/src/emqx_persistent_message_ds_gc_worker.erl
- apps/emqx/src/emqx_persistent_session_bookkeeper.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds.hrl
- apps/emqx/src/emqx_persistent_session_ds_gc_worker.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_zone_schema.erl
- apps/emqx/test/emqx_config_SUITE.erl
- apps/emqx/test/emqx_persistent_messages_SUITE.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx/test/emqx_persistent_session_ds_router_SUITE.erl
- apps/emqx/test/emqx_takeover_SUITE.erl
- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds_builtin_metrics.erl
- apps/emqx_management/src/emqx_mgmt_api_ds.erl
- apps/emqx_management/src/emqx_mgmt_data_backup.erl
- apps/emqx_management/test/emqx_mgmt_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_ds_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl
- changes/ce/feat-12739.en.md
- changes/ce/fix-13060.en.md
- rel/i18n/emqx_schema.hocon
Fixes [EMQX-12397](https://emqx.atlassian.net/browse/EMQX-12397) 
- Change name of the message durable storage to just `messages`
- Change configuration root from `session_persistence` to `durable_sessions`
[EMQX-12397]: https://emqx.atlassian.net/browse/EMQX-12397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Better naming of DS database and configuration

- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_schema_validation/src/emqx_schema_validation.erl
- apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl
- apps/emqx_utils/src/emqx_utils.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12346
From discussions with Product, when importing a schema validation backup:
* Existing validations (identified by `name') are left untouched.
* No validations are removed.
* New validations are appended to the existing list.
* Existing validations are not reordered.
> feat(schema validation): implement backup restore

- apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_shard_allocator.erl
- apps/emqx_management/src/emqx_mgmt_api_ds.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
Fixes [EMQX-12365](https://emqx.atlassian.net/browse/EMQX-12365).
Attempt to bring together the DS's view of the cluster with mria/ekka's view and related operations, e.g. leave and force-leave.
[EMQX-12365]: https://emqx.atlassian.net/browse/EMQX-12365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dsrepl): anticipate and handle nodes leaving the cluster

- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds_gc_worker.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_config_SUITE.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx/test/emqx_takeover_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_SUITE.erl
- changes/ce/fix-13062.en.md
Fixes [EMQX-12398](https://emqx.atlassian.net/browse/EMQX-12398)
Rename configuration parameter `durable_sessions.last_alive_update_interval` to `durable_sessions.heartbeat_interval`
[EMQX-12398]: https://emqx.atlassian.net/browse/EMQX-12398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(sessds): Rename last_alive_update_interval -> heartbeat_interval

- apps/emqx_auth_http/src/emqx_auth_http.app.src
- scripts/apps-version-check.sh
A release has been cut in emqx-platform.git between `e5.6.1` and current `HEAD` of release-57.
> chore: bump emqx_auth_http app vsn

- apps/emqx_management/src/emqx_mgmt_api_clients.erl
Since it's not yet ready for production, we'll hide it from the API docs.
> docs: hide `/clients_v2` from swagger api docs

- apps/emqx/src/emqx_logger_jsonfmt.erl
- apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra_connector.erl
- apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb_connector.erl
- apps/emqx_bridge_redis/src/emqx_bridge_redis_connector.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
- apps/emqx_mysql/src/emqx_mysql.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
This PR includes fixes for two small action trace issues:
* [fix: remove query mode from redis action trace as it only supports sync](https://github.com/emqx/emqx/commit/c72682d81b175194490ddbae691c0553bc0e8799)
* [fix: make mysql action rendered trace include parameters](https://github.com/emqx/emqx/commit/246bce85eca6fb14ec174028f987de99875022e0)
Fixes:
https://emqx.atlassian.net/browse/EMQX-12336
https://emqx.atlassian.net/browse/EMQX-12335
- [] Change log has been added to …
> Fix small action trace issues

- apps/emqx_bridge_s3/src/emqx_bridge_s3_upload.erl
- apps/emqx_bridge_s3/test/emqx_bridge_s3_aggreg_upload_SUITE.erl
- apps/emqx_s3/src/emqx_s3_schema.erl
Fixes [EMQX-12422](https://emqx.atlassian.net/browse/EMQX-12422).
Report inconsistent `min_part_size` / `max_part_size` configuration parameters as a validation error.
[EMQX-12422]: https://emqx.atlassian.net/browse/EMQX-12422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(s3-bridge): report inconsistent `min/max_part_size` option

- apps/emqx/src/emqx_ds_schema.erl
- apps/emqx_durable_storage/README.md
- apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_shard.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/src/proto/emqx_ds_proto_v4.erl
- apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_replication_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_SUITE.erl
- changes/ce/fix-13072.en.md
- rel/i18n/emqx_ds_schema.hocon
Fixes [EMQX-12402](https://emqx.atlassian.net/browse/EMQX-12402)
Various small, but important fixes.
- Add an option to execute read operations on the leader.
- `drop_generation` operation can be replayed multiple times by the replication layer, but it's not idempotent. This PR adds a workaround that avoids a crash when `drop_generation` doesn't succeed. In the future, however, we want to make `drop_generation` idempotent in a nicer way.
- Wrap storage layer events in a small structure containing the generation ID, to make sure events are handled by the same layout CBM & context that produced them. 
- Fix crash when storage event arrives to the dropped generation (there was a bug in `storage_layer:generation_at` function, which has been removed for good).
- …
> Idempotent drop_generation

- apps/emqx_gateway_gbt32960/test/emqx_gbt32960_parser_SUITE.erl
Fixing the typo [here](https://github.com/emqx/emqx/commit/bb3c66638c43d245b21f554e66ea3ad93d707e40) increased the payload size, and that was not updated in the test assertion.
> test: fix broken test

- apps/emqx_bridge_s3/src/emqx_bridge_s3_upload.erl
- scripts/conf-test/old-confs/e5.6.1.conf
Fixes [EMQX-12437](https://emqx.atlassian.net/browse/EMQX-12437).
Recently introduced `mode` required field broke older configurations, this PR brings back backward compatibility.
[EMQX-12437]: https://emqx.atlassian.net/browse/EMQX-12437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(s3-bridge): restore backward config compatibility

- apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- changes/ce/fix-13077.en.md
Before this commit the following happened sometimes:
1. action status is connected
2. action config is updated to something that should change the status to disconnected
3. action status is still connected and the old config is being used by the connector even though the config has been correctly updated.
The reason for this bug is that the post_config_hook runs before the global EMQX config is updated. The post config hook is adding the new config to the connector. Since the new config causes the action to get status disconnected, the adding of the action to the connector is retried when the health check runs but this time the config will be loaded from the global config which could cause the old config to be loaded (this happens when the global config has not had time to get updated). …
> fix: action config update would sometimes not be reflected in connector

- apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
- apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
- apps/emqx_bridge_s3/src/emqx_bridge_s3_connector.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
Fixes:
https://emqx.atlassian.net/browse/EMQX-12429
Manually tested
> fix: add action rendered trace for s3 in aggregated mode

- apps/emqx/src/emqx_persistent_message.erl
- apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_shard_allocator.erl
- apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_stats_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_status_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
Fixes [EMQX-12415](https://emqx.atlassian.net/browse/EMQX-12415).
As evidenced by the linked bug report, it's possible for shard allocator to reach a weird state where it stays idle even when there are pending shard transitions affecting local site. At the moment, there's no reliable repro, thus this brute bugfix: trigger any pending transitions on timeout when idling.
[EMQX-12415]: https://emqx.atlassian.net/browse/EMQX-12415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dsrepl): trigger "last-resort" pending transitions handler when idle

- Makefile
- apps/emqx_bridge_s3/src/emqx_bridge_s3_upload.erl
~It's just a temporary workaround fixing to avoid the following crash log:~
```
2024-05-24T02:41:46.285172+00:00 [error] tag: ERROR, msg: resource_exception, info: #{error => {error,{case_clause,#{mode => direct,key => [<<"test">>],content => [{var,[],[]}],bucket => [<<"emqx-file-transfer">>],upload_options => #{acl => private}}}},id => <<"action:s3:bad48af88a52468888782920b5c6206c:connector:s3:71ef671d06da4d0fa5bcc19305a29a14">>,name => call_batch_query,request => [{query,{fun emqx_rule_runtime:inc_action_metrics/2,[#{clientid => <<"c_emqx">>,rule_id => <<"72f87f5ba3b440b08af93b9c1e09fade">>,action_id => {bridge_v2,s3,bad48af88a52468888782920b5c6206c},rule_trigger_ts => [1716518499603]}],#{reply_dropped => true}},{<<"action:s3:bad48af88a52468888782920b5c6206c:connector:s3:71ef671d06da4d0f …
```
> Fix(s3): change the batch_size to 1 for direct mode

- apps/emqx_dashboard/include/emqx_dashboard.hrl
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
Essentially in the same manner as they are currently reflected in the current metrics.
Fixes [EMQX-12440](https://emqx.atlassian.net/browse/EMQX-12440)
[EMQX-12440]: https://emqx.atlassian.net/browse/EMQX-12440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(monitor): reflect durable subscriptions in historical metrics

- apps/emqx_management/src/emqx_mgmt_api_ds.erl
Fixes [EMQX-12356](https://emqx.atlassian.net/browse/EMQX-12356)
Check status of the site via Mria API instead of Erlang node API to be consistent with the output of `emqx_ctl ds info` command.
[EMQX-12356]: https://emqx.atlassian.net/browse/EMQX-12356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dsapi): Check status of the node via Mria

- apps/emqx/src/emqx_logger_jsonfmt.erl
- apps/emqx_oracle/src/emqx_oracle.app.src
- apps/emqx_oracle/src/emqx_oracle.erl
- changes/ee/fix-13136.en.md
This forces the parameters to the database statement to be rendered as a JSON array in JSON traces instead of being rendered as a string when the parameters are interpreted as IO data.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12433
> fix(oracle action trace): parameters should not be rendered as IO Data

- apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
- changes/ce/fix-13140.en.md
Fixes:
https://emqx.atlassian.net/browse/EMQX-12474
> fix: trace formatter should not crash when given a non-binary payload

- apps/emqx_schema_registry/src/emqx_schema_registry.app.src
- apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl
- changes/ee/fix-13147.en.md
Before this commit the user would see a cryptic warning log including function_clause when decoding a message failed. This commit improves this by removing function_caluse as well as some other cryptic words from the message and adding a description describing what went wrong.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12453
- [] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if …
> fix: make protobuf schema decode error reported to user less cryptic

- apps/emqx_bridge_redis/src/emqx_bridge_redis.app.src
- apps/emqx_bridge_redis/src/emqx_bridge_redis_connector.erl
- changes/ee/fix-13130.en.md
Logger will transform data that looks like IO data into a string which made redis batch traces look like the spaces had been removed from the strings. To prevent this, we render the batched commands into binary string separated by spaces and semicolon. The components of a single command is separated by spaces and the commands in a batch are separated by semicolons.
Fixes:
https://emqx.atlassian.net/browse/EMQX-12428
- [] Created PR to …
> fix(redis trace): add separators in redis batch action trace

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_license/test/emqx_license_http_api_SUITE.erl
- changes/ee/fix-13070.en.md
- dev
Fixes [EMQX-12403](https://emqx.atlassian.net/browse/EMQX-12403)
Example log when Kafka's advertised listener is unreachable.
2024-05-18T19:13:48.412913+02:00 [warning] msg: add_channel_failed, id: <<"connector:kafka_producer:k1">>, reason: #{cause => "no_connected_partition_leader",kafka_topic => "test-topic-2",kafka_client => <<"connector:kafka_producer:k1">>,first_error => {1,{down,#{reason => unresolvable_hostname,host => <<"localhostx:9092">>}}},total_errors => 2}, channel_id: <<"action:kafka_producer:k1:connector:kafka_producer:k1">>
[EMQX-12403]: https://emqx.atlassian.net/browse/EMQX-12403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> 0518 improve kafka connection error logs

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- changes/ee/fix-13079.en.md
- mix.exs
Fixes [EMQX-12382](https://emqx.atlassian.net/browse/EMQX-12382)
wolff-1.10.4 handles message_too_large error code from Kafka. It tries to split the too-large batch into single-call batches (for EMQX, one call batch is always one message), and retry. In case a single-call batch is too large, EMQX should increment a failure counter.
[EMQX-12382]: https://emqx.atlassian.net/browse/EMQX-12382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: upgrade kafka producer lib wolff to 1.10.4 handle `message_too_large`

- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/emqx_connector_api.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource_manager.erl
- changes/ce/fix-13148.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12251
After fix:
> fix(connector api): handle `timeout` when waiting for connector status

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- changes/ee/fix-13093.en.md
- mix.exs
Fixes [EMQX-12438](https://emqx.atlassian.net/browse/EMQX-12438)
`brod` 3.18 included a bug fix which handles Kafka consumer group coordinator connection loss correctly so the group can reach balance sooner. Also result in less process crash logs.
[EMQX-12438]: https://emqx.atlassian.net/browse/EMQX-12438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: upgrade to brod 3.18.0

- apps/emqx_bridge_redis/src/emqx_bridge_redis_connector.erl
- apps/emqx_bridge_redis/test/emqx_bridge_v2_redis_SUITE.erl
- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- apps/emqx_utils/src/emqx_placeholder.erl
- apps/emqx_utils/src/emqx_utils.app.src
- changes/ee/feat-13172.en.md
Fixes [12510](https://emqx.atlassian.net/browse/EMQX-12510)
When data is already structured with a trusted schema, having to enumerate all possible data fields is low efficiency for both configuring EMQX action and template rendering.
Below is a IRL case.  
```
command_template = [
HMSET,
"NS:2",
f1,  "${payload.f1}",
f2,  "${payload.f2}",
...
f50000, "${payload.f50000}"
]
```
This PR introduces a new function named 'map_to_redis_hset_args'
it can be used to format a map's key-value pairs into redis HSET (or HMSET) arg list.
This new function is dedicated for redis to avoid abuse for other data integrations.
With the help of this function, the rule can be written as:
```
SELECT  map_to_redis_hset_args(payload) as hset_fields FROM  "t/#"
```
Then the template can …
> feat(redis): add a rule function to help formatting redis args

- bin/emqx
- bin/nodetool
Prior to this change, the command used to check installation and os compatibility is done by starting a 'erl' process using default flags. it might be unnecessarily expensive in large VM instances.
In this change, we have added small enough `+S`, `+P` and `+Q` number to lower the cost.
> chore: improve emqx boot script's compatibility check

- apps/emqx_auth_postgresql/test/emqx_authn_postgresql_SUITE.erl
- apps/emqx_auth_postgresql/test/emqx_authz_postgresql_SUITE.erl
- apps/emqx_bridge_matrix/src/emqx_bridge_matrix.app.src
- apps/emqx_bridge_matrix/src/emqx_bridge_matrix_action_info.erl
- apps/emqx_bridge_pgsql/src/emqx_bridge_pgsql.app.src
- apps/emqx_bridge_pgsql/src/emqx_bridge_pgsql.erl
- apps/emqx_bridge_pgsql/src/emqx_bridge_pgsql_action_info.erl
- apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl
- apps/emqx_bridge_timescale/src/emqx_bridge_timescale.app.src
- apps/emqx_bridge_timescale/src/emqx_bridge_timescale_action_info.erl
- apps/emqx_postgresql/src/emqx_postgresql.app.src
- apps/emqx_postgresql/src/emqx_postgresql.erl
- apps/emqx_postgresql/src/schema/emqx_postgresql_connector_schema.erl
- changes/ce/feat-13175.en.md
- rel/i18n/emqx_postgresql.hocon
- scripts/spellcheck/dicts/emqx.txt
Fixes https://emqx.atlassian.net/browse/EMQX-12496
Some Postgres connections, such ones made to [PGBouncer](https://www.pgbouncer.org/) or [Supabase in Transaction Mode](https://supabase.com/), do not support some session features like prepared statements.
> feat(postgres): add `disable_prepared_statements` option

- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- apps/emqx_utils/test/emqx_utils_agent.erl
- changes/ce/fix-13181.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12357
The original issue originated when the connector process (`emqx_resource_manager`) was stuck trying to start, and an API call to remove the action/source would arrive, timing out in a `gen_statem:call`.  
Now, the recommended workaround in such situations is to first stop the connector before disabling/removing the action/source.  Now, when stopping a connector, if the stop call times out, we forcefully kill the process.
> fix(resource manager): force kill process if stuck when stopping/removing

- .github/workflows/green_master.yaml
In order to receive comments from coveralls on PRs, we need to keep base branch builds green.
See [coverallsapp/github-action/issues/212](https://github.com/coverallsapp/github-action/issues/212) for more details.
> ci: trigger reruns of failed checks on release-57 branch as well as master

- apps/emqx_bridge_s3/src/emqx_bridge_s3.app.src
- apps/emqx_bridge_s3/src/emqx_bridge_s3.erl
- apps/emqx_connector/src/emqx_connector.erl
- changes/ee/fix-13197.en.md
Fixes [EMQX-12522](https://emqx.atlassian.net/browse/EMQX-12522).
Release version: e5.7.
Regular mechanism has not been working because S3 Bridge schema structured differently.
[EMQX-12522]: https://emqx.atlassian.net/browse/EMQX-12522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(bridge-s3): pass SSL options through `convert_certs/2`

- mix.exs
- rebar.config
Upgrade system_monitor app from 3.0.3 to 3.0.5
This change has no impact on EMQX users because system_monitor is a disabled app by default (so far only used in performance tests).
> 0609 upgrade system monitor

- apps/emqx_resource/src/emqx_resource_manager.erl
Since `emqx_resource_manager:channel_health_check` already does a base resource health check, the call was repeated.
Fixes [EMQX-12521](https://emqx.atlassian.net/browse/EMQX-12521)
[EMQX-12521]: https://emqx.atlassian.net/browse/EMQX-12521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: remove redundant health check call

- apps/emqx_bridge_pgsql/test/emqx_bridge_pgsql_SUITE.erl
- apps/emqx_postgresql/src/emqx_postgresql.app.src
- apps/emqx_postgresql/src/emqx_postgresql.erl
In a user's log file it was found that that the pgsql driver can end up in a situation where the prepared statement for a channel/action is not properly removed before a channel with the same name as the prepared statement is added to the connector. This commit handles this by attempting to remove the old prepared statement if one already exists when adding channel.
Related issue:
https://emqx.atlassian.net/browse/EEC-1036
-  [] Added property-based tests for code which performs user input validation
-  [] Created PR to …
> fix(pgsql connector): handle prepared statement already exists

- apps/emqx_bridge_s3/src/emqx_bridge_s3_connector.erl
- apps/emqx_bridge_s3/src/emqx_bridge_s3_upload.erl
- apps/emqx_connector_aggregator/src/emqx_connector_aggregator.app.src
- apps/emqx_connector_aggregator/src/emqx_connector_aggregator.erl
- apps/emqx_utils/src/emqx_template.erl
- apps/emqx_utils/test/emqx_template_SUITE.erl
- changes/ee/fix-13227.en.md
Fixes [EMQX-12533](https://emqx.atlassian.net/browse/EMQX-12533).
Otherwise, invalid template will cause a storm of crashes that will eventually lead to the `emqx_bridge_s3`'s root supervisor giving up and terminating.
[EMQX-12533]: https://emqx.atlassian.net/browse/EMQX-12533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(bridge-s3): validate aggreg key template before adding a channel

- apps/emqx_bridge_azure_blob_storage/rebar.config
- apps/emqx_bridge_azure_blob_storage/src/emqx_bridge_azure_blob_storage_connector.erl
- apps/emqx_bridge_azure_blob_storage/test/emqx_bridge_azure_blob_storage_SUITE.erl
Depends on https://github.com/dkataskin/erlazure/pull/43 being merged and then synced to
our fork.
> chore: refactor azure blob connector to use new `erlazure` without `gen_server`

- apps/emqx/include/emqx_placeholder.hrl
- apps/emqx/src/emqx_channel.erl
- apps/emqx_auth/src/emqx_authn/emqx_authn_utils.erl
- apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl
Fixes  [EMQX-12538](https://emqx.atlassian.net/browse/EMQX-12538)
Support `${cert_pem}` placeholder in authn templates.
[EMQX-12538]: https://emqx.atlassian.net/browse/EMQX-12538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(authn): support `${cert_pem}` placeholder

- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_quic_stream.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx_gateway/src/bhvrs/emqx_gateway_conn.erl
- apps/emqx_gateway/src/emqx_gateway.app.src
- changes/ce/feat-13180.en.md
Fixes [EMQX-12515](https://emqx.atlassian.net/browse/EMQX-12515)
In a stress test environment, when alarm is enabled, there were
a lot of long_schedule warnings with the stacktrace pointing to
congestion alarm based inet:getstat function.
When alarm is disabled, the one single client is able to
hold 40,000 QoS 1 messages per second (inflight=32) throughput.
When alarm is enabled, its mqueue overflows.
Now that EMQX is on OTP 26 by default, the fake inet_reply
message when the send call returns ok only adds overhead.
For TCP (gen_tcp module), OTP 26 no longer supports direct port_command
so we had to swith to gen_tcp:send, then fake an async reply:
see https://github.com/emqx/esockd/pull/181
For TLS (ssl module), it has never supported async send anyway.
This …
> 0604 optimize tcp ssl connection data send performance

- apps/emqx/include/logger.hrl
- apps/emqx/src/config/emqx_config_logger.erl
- apps/emqx/src/emqx_logger_jsonfmt.erl
- apps/emqx/src/emqx_logger_textfmt.erl
- apps/emqx/src/emqx_vm.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_conf_schema_tests.erl
- apps/emqx_utils/src/emqx_utils.erl
revert this : https://github.com/emqx/emqx/pull/12590 
Add a hidden option to add mfa into log.
```
log.console.with_mfa= true
```
EMQX_LOG__CONSOLE__WITH_MFA=true
It is hidden from users and only available to developers.
> feat: add hidden option to record MFA and line in the log 

- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
A function added to variform was missed exporting from rule engine.
> fix(emqx_rule_funcs): expose regex_extract function to rule engine

- apps/emqx/rebar.config
- apps/emqx/src/emqx_schema.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- changes/ce/feat-13250.en.md
- mix.exs
- rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-12493
```
2024-06-13T20:05:41.000850+00:00 [error] #{reason => integrity_validation_failure,result => {error,<<"cluster discovery strategy must be 'singleton' when durable storage backend is builtin_local">>},kind => validation_error,validation_name => validate_durable_sessions_strategy}
```
> feat: enforce singleton discovery strategy when using DS `builtin_local` backend

- apps/emqx_machine/priv/reboot_lists.eterm
Otherwise, it's unconditionally started as a permanent application instead of being controlled by `emqx_machine`.
```sh
ͳ rg start_boot _build/emqx-enterprise/rel/emqx/releases/5.7.0-g4e6be8a6/start.script | rg emqx_s3
{apply,{application,start_boot,[emqx_s3,permanent]}},
```
> fix: add `emqx_s3` to `reboot_lists.eterm`

- apps/emqx_durable_storage/src/emqx_ds_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/src/emqx_durable_storage.app.src
- apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
- changes/ce/fix-13276.en.md
Before this commit, inherited trie was actually only kept in memory cache.
Also simplify storage backend behaviour around inheriting previous generation's legacy.
> fix(dsstore): persist inherited LTS trie

- apps/emqx_plugins/src/emqx_plugins.erl
- mix.exs
On one hand, Elixir plugins might include Elixir itself, when targetting a non-Elixir EMQX release.  If, on the other hand, the EMQX release already includes Elixir, we shouldn't stop Elixir nor IEx, or the running IEx shell will break.
~- [ ] Added tests for the changes~ Tested manually
> fix(plugins): do not stop Elixir protected apps

- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12542
This is a follow-up fix for PR #13172 
> fix(redis): json decode if arg for map_to_redis_hset_args is string

- apps/emqx/rebar.config
- changes/ce/fix-13307.en.md
- mix.exs
- rebar.config
mria 0.8.8 heals a network partition once majority of core nodes are alive. Previously, the auto-heal worked only when all core nodes were reachable.
Fixes EMQX-10974
> chore: upgrade ekka to 0.19.5 (mria 0.8.8)

- scripts/test/start-two-nodes-in-docker.sh
Unable to find image 'public.ecr.aws/docker/library/haproxy:2.4' locally
[51](https://github.com/emqx/emqx/actions/runs/9594332475/job/26457097093?pr=13304#step:6:52)
docker: Error response from daemon: toomanyrequests: Rate exceeded.
> ci: pull haproxy image from ghcr

- apps/emqx/src/emqx_frame.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_frame_SUITE.erl
- changes/ce/fix-13222.en.md
Fixes [EMQX-12503](https://emqx.atlassian.net/browse/EMQX-12503)
[EMQX-12503]: …
> fix: check willretain and willqos when WillFlag set to `true`

- apps/emqx_auth_ext/src/emqx_auth_ext_tls_const_v1.erl
- apps/emqx_auth_ext/src/emqx_auth_ext_tls_lib.erl
- apps/emqx_auth_ext/test/emqx_auth_ext_schema_SUITE.erl
Fixes [EMQX-12566](https://emqx.atlassian.net/browse/EMQX-12566)
Previously, if `partial_chain` is set to `false` we omit it in ssl_options following OTP default.
This PR force inject `partial_chain` (using default root_fun if set to false) into ssl_options so hot config won't miss it. 
[EMQX-12566]: https://emqx.atlassian.net/browse/EMQX-12566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(tls): disable partial_chain in hot config

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_keepalive.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_config_SUITE.erl
- apps/emqx/test/emqx_keepalive_SUITE.erl
- apps/emqx_gateway_coap/src/emqx_coap_channel.erl
- apps/emqx_gateway_coap/src/emqx_coap_schema.erl
- apps/emqx_gateway_coap/src/emqx_gateway_coap.app.src
- apps/emqx_gateway_coap/test/emqx_coap_SUITE.erl
- apps/emqx_gateway_exproto/src/emqx_exproto_channel.erl
- apps/emqx_gateway_exproto/src/emqx_gateway_exproto.app.src
- apps/emqx_gateway_gbt32960/src/emqx_gateway_gbt32960.app.src
- apps/emqx_gateway_gbt32960/src/emqx_gbt32960_channel.erl
- apps/emqx_gateway_jt808/src/emqx_gateway_jt808.app.src
- apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl
- apps/emqx_gateway_mqttsn/src/emqx_gateway_mqttsn.app.src
- apps/emqx_gateway_mqttsn/src/emqx_mqttsn_channel.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- rel/i18n/emqx_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-11151
https://github.com/emqx/emqx/issues/11685
Add a new keepalive config: mqtt.keepalive_check_interval(default is 30s)
The time interval to check for mqtt packets.
range is `[1s, Interval(in connect packet) div 2 s]`.
So the time to determine if a timeout is needed is:
- min:   interval * multiplier 
- max:  interval * multiplier + 1 * check_interval
eg:
interval = 60s, multiplier = 1.5, check_interval = 30s
should be keepalive_timeout between `90s(60*1.5) and 120s(60*1.5+30)`
If the user expects to reduce this section. You can reduce the factor:
interval = 60s, multiplier = 1.5, check_interval = 10s
should be keepalive_timeout between `90s(60 * 1.5) and 100s(60 * 1.5+10)`
Please convert it to a draft if any of the …
> feat: improve keepalive_multiplier and keepalive_check_interval

- .github/workflows/build_and_push_docker_images.yaml
- Makefile
- deploy/docker/Dockerfile
latest version of 12-slim as of today is configured to fetch i386 packages
```
docker run -it --rm --platform linux/amd64 public.ecr.aws/debian/debian:12-slim
Unable to find image 'public.ecr.aws/debian/debian:12-slim' locally
12-slim: Pulling from debian/debian
0e7ee8520e07: Pull complete
Digest: sha256:465c9569a7fd7f28a7f263a6407307c0294e9f037b65035d3cbeacb737288215
Status: Downloaded newer image for public.ecr.aws/debian/debian:12-slim
root@7277eab43d64:/# apt-get update
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main i386 Packages [8679 kB]
Get:5 …
```
> build: pin base docker image to stable-20240612-slim

- apps/emqx_bridge_s3/src/emqx_bridge_s3_connector.erl
- apps/emqx_bridge_s3/src/emqx_bridge_s3_upload.erl
- apps/emqx_bridge_s3/test/emqx_bridge_s3_SUITE.erl
- apps/emqx_bridge_s3/test/emqx_bridge_s3_aggreg_upload_SUITE.erl
- apps/emqx_utils/src/emqx_utils.erl
- changes/ee/breaking-13332.en.md
Fixes [EMQX-12571](https://emqx.atlassian.net/browse/EMQX-12571).
Key template validation is lifted into a schema-level validator, so broken key template will result in config / request validation error now, as opposed to bridge-level channel errors that resulted in failed healthchecks before.
[EMQX-12571]: https://emqx.atlassian.net/browse/EMQX-12571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(bridge-s3): provide more meaningful error details in status

- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/test/emqx_cth_cluster.erl
- apps/emqx/test/emqx_cth_peer.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_shard.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_snapshot.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds_buffer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl
- apps/emqx_utils/src/emqx_utils_stream.erl
- mix.exs
- rebar.config
Fixes [EMQX-12468](https://emqx.atlassian.net/browse/EMQX-12468).
Release version: v5.8
Depends on https://github.com/emqx/erlang-rocksdb/pull/33.
Use WAL-less write mode in `emqx_ds_storage_layer` backends, which should be safe because `ra` keeps the Raft log anyway, assuming `ra` has good correctness / durability guarantees in regards to its own WAL and log segment writes.
Safety is achieved through following mechanisms.
1. The implementation of `ra_machine` from time to time asks Ra to release _all_ log entries up to the current Ra index.
2. According to internal logic, Ra often satisfies that request by taking a snapshot at the current Ra index.
3. Taking the snapshot involves flushing _all yet unflushed_ column families to disk at the storage layer.
4. Once this is done, and snapshot …
> feat(dsrepl): enable WAL-less batch writes

- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_gc.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx/test/emqx_ws_connection_SUITE.erl
- apps/emqx_gateway/src/bhvrs/emqx_gateway_conn.erl
- apps/emqx_gateway_ocpp/src/emqx_gateway_ocpp.app.src
- apps/emqx_gateway_ocpp/src/emqx_ocpp_connection.erl
```
2024-06-27T03:03:08.764259+00:00 [debug] clientid: test, msg: check_oom, peername: 172.100.239.1:42259, username: emqx_u1, policy: #{max_heap_size => 4194304,enable => true,max_mailbox_size => 1000}
```
The log is missing essential information, and 'active_n (100)' is alternately printed in the trace log. Adding 'incoming_pubs', 'incoming_bytes', and result meta fields to enhance readability.
```
2024-06-27T03:49:49.578308+00:00 [debug] clientid: test, msg: check_oom_ok, mfa: emqx_connection:check_oom/3(1104), peername: 172.100.239.1:42293, username: emqx_u1, result: ok, incoming_bytes: 33, incoming_pubs: 1, policy: #{max_heap_size => 4194304,enable => true,max_mailbox_size => 1000}
```
Please convert it to a draft if any of the …
> chore: log shutdown reason for check_oom trace log

- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src
- apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl
- apps/emqx_auth_mnesia/src/emqx_authn_mnesia_schema.erl
- apps/emqx_auth_mnesia/test/emqx_authn_mnesia_SUITE.erl
- changes/ce/feat-13336.en.md
- rel/i18n/emqx_authn_mnesia_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12593
close #8714, #9148
This feature needs to be used before enabling built_in_database authn,
so it makes sense to add configuration items to it.
Use the same template for initialization as for importing users:
Import data only on build-in-dabase create.
Support for JSON, CSV files.
```
authentication = [
{
backend = built_in_database
mechanism = password_based
password_hash_algorithm {name = sha256, salt_position = suffix}
user_id_type = username
bootstrap_file = "/opt/init_user.json"
bootstrap_type = hash | plain
}
]
```
> feat: support bootstrap_file on authentication for build-in-database

- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_azure_event_hub/test/emqx_bridge_azure_event_hub_v2_SUITE.erl
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_confluent/test/emqx_bridge_confluent_producer_SUITE.erl
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl
- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.app.src
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- changes/ee/breaking-13327.en.md
- changes/ee/fix-13327.en.md
- mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-12592
Fixes https://emqx.atlassian.net/browse/EMQX-12585
> fix(kafka and derivatives): add `alias` config to avoid clashes with same topic

- .github/actions/prepare-jmeter/action.yaml
- .github/workflows/_pr_entrypoint.yaml
- .github/workflows/_push-entrypoint.yaml
- .github/workflows/build_and_push_docker_images.yaml
- .github/workflows/build_docker_for_test.yaml
- .github/workflows/build_packages_cron.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/codeql.yaml
- .github/workflows/run_docker_tests.yaml
- .github/workflows/run_helm_tests.yaml
- .github/workflows/run_jmeter_tests.yaml
- .github/workflows/run_test_cases.yaml
- .github/workflows/static_checks.yaml
- Makefile
- build
- env.sh
- scripts/buildx.sh
- scripts/pr-sanity-checks.sh
- scripts/relup-test/start-relup-test-cluster.sh
Reference runs for workflows triggered on push
- [Cross build packages](https://github.com/emqx/emqx/actions/runs/9739317954)
- [Build and push docker images](https://github.com/emqx/emqx/actions/runs/9739257474)
> build: add env.sh to manage builder version in one place

- apps/emqx_dashboard/src/emqx_dashboard.app.src
- apps/emqx_dashboard/src/emqx_dashboard_admin.erl
- apps/emqx_dashboard/test/emqx_dashboard_admin_SUITE.erl
This can happen at least in tests, when nodes boot concurrently.
> fix(dashboard): handle add default user race condition

- changes/ce/fix-13382.en.md
- mix.exs
- rebar.config
Fixes [EMQX-12421](https://emqx.atlassian.net/browse/EMQX-12421).
Release version: v5.7.2
Emqtt 0.4.14 includes a fix that prevents `emqtt_pool` from reusing existing pools in an inconsistent state.
[EMQX-12421]: https://emqx.atlassian.net/browse/EMQX-12421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: bump `ehttpc` to 0.4.14

- apps/emqx/test/emqx_authz_cache_SUITE.erl
Hypothesis: some race condition involving the previous test case, which uses the same clientid.
```
Testing apps.emqx.emqx_authz_cache_SUITE: *** FAILED test case 3 of 3 ***
%%% emqx_authz_cache_SUITE ==> t_drain_authz_cache: FAILED
%%% emqx_authz_cache_SUITE ==>
Failure/Error: ?assertEqual([], list_cache ( ClientPid ))
expected: []
got: [{{#{qos => 0,action_type => publish,retain => false},<<"t1">>},
{allow,1719599365019}}]
line: 72
```
> test(authz cache): attempt to fix flaky test

- apps/emqx_auth/src/emqx_authn/emqx_authn_password_hashing.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz_rule_raw.erl
- changes/ce/fix-13389.en.md
1. the `Derived Key Length` for `pbkdf2` should be a positive integer.
2. fix topics in the authorization rules might be parsed incorrectly
Fixes EMQX-11414 EMQX-10583
> fix: fix two minor issues of bulti-in authn/authz

- apps/emqx/include/emqx.hrl
- apps/emqx/src/emqx.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_config_handler.erl
- apps/emqx/test/emqx_config_handler_SUITE.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_api_cluster_SUITE.erl
- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
When updating the configuration, if it has succeeded on the first node, the configuration must be saved successfully on the other nodes even if it has failed. So for both pre_config_update and post_config_update callbacks,  need to support check where they are from, whether it's initiate or replicate.
PS: Previously we only handled post_config_update failed, but now we handle it in pre_config_update as well.
close https://github.com/emqx/emqx/pull/13303
> feat: do not fail on other nodes when the RPC succeeds on the first node

- apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz_rule_raw.erl
- apps/emqx_auth_http/src/emqx_auth_http.app.src
- apps/emqx_auth_http/src/emqx_authn_http.erl
- apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl
- apps/emqx_auth_jwt/src/emqx_auth_jwt.app.src
- apps/emqx_auth_jwt/src/emqx_authn_jwt.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12569
Release version: v/e5.7.2 (announce in v5.8)
Support HTTP authentication response to return :
- ACL, a JSON property named `acl` should contain a list of ACL rules for this one specific client
- Expiry, a JSON property named `expire_at` (epoch seconds) should cause the client to reconnect (hence re-authenticate)
- [n/a] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
will add changelog when merge to `master`
> feat(auth): support HTTP authn return ACL rules

- deploy/docker/Dockerfile
- See also: https://docs.docker.com/reference/build-checks/from-as-casing/
```log
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 8)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 15)
```
```bash
$ docker buildx version
github.com/docker/buildx 0.15.1 1c1dbb2e4cb5363110f42102744a08d034c2300d
```
> build: avoid warnings during docker build

- apps/emqx/priv/bpapi.versions
- apps/emqx_conf/include/emqx_conf.hrl
- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_cluster_rpc_cleaner.erl
- apps/emqx_conf/src/emqx_conf.erl
- apps/emqx_conf/src/emqx_conf_app.erl
- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_conf/src/proto/emqx_conf_proto_v3.erl
- apps/emqx_conf/src/proto/emqx_conf_proto_v4.erl
- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
- apps/emqx_conf/test/emqx_conf_cluster_sync_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
- changes/ce/feat-13202.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12523
Initially, the original `cluster_sync status` only provided the `tnx_id` status for each node, which was not easily understood by the user. Moreover, there was no guidance on restoring the normal state. 
The updated `cluster_sync status` now detects all the diff configurations in the cluster, excluding the read-only configuration. 
Additionally, a new command, `cluster_sync fix`, has been introduced to address cluster inconsistencies. This command synchronizes the raw configuration of the node with the largest `tnx_id` to all nodes.
```
EMQX_NODE__NAME=emqx@127.0.0.1 ./bin/emqx ctl conf cluster_sync status
-----------------------------------------------
emqx1@127.0.0.1(73)'s listeners has been updated, but the …
```
> feat: add cluster fix command

- apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl
- apps/emqx/test/emqx_ratelimiter_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
- changes/ce/fix-13375.en.md
Before this PR the default value for the fields `max_conn_rate`, `messages_rate` and `bytes_rate` were not set. This is fixed by setting the default value to infinity. This breaks the corresponding dashboard fields (they can not be edited) so the dashboard also needs to be updated.
This change is according to @zmstone's suggestion in the JIRA ticket (https://emqx.atlassian.net/browse/EMQX-12514?focusedCommentId=41414)
Fixes:
https://emqx.atlassian.net/browse/EMQX-12514
- [] Created PR to …
> fix: default value for max_conn_rate etc should be set to infinity

- apps/emqx_resource/src/emqx_resource_manager.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12442
e.g.:
```
2024-05-23T08:52:39.811845+00:00 [error] Supervisor: {local,emqx_resource_manager_sup}. Context: shutdown_error. Reason: noproc. Offender: id=<<99, 101, 110, 115, 111, 114, 101, 100>>,pid=<0.7752.1030>.
```
It could be just a race condition, as it seems to be the case for resource manager: i) a call is made to the process to stop it; ii) the call times out; iii) the after clause ends up calling supervisor:terminate_child; iv) while the supervisor is finding the child to terminate, the process actually finishes terminating, and the supervisor receives a noproc reason back.
> chore: attempt to reduce race condition supervisor noproc shutdown error logs

- apps/emqx_connector/src/emqx_connector_resource.erl
- changes/ce/fix-13503.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12738
- ~[ ] Added tests for the changes~ checked manually
> fix(connector resource): use configuration `resource_opts` for health check interval when starting up

- bin/emqx
> feat(bin/emqx): add `-init_debug` system arg when `DEBUG=2`

- apps/emqx/src/emqx_exclusive_subscription.erl
- apps/emqx/test/emqx_exclusive_sub_SUITE.erl
- changes/ce/fix-13515.en.md
> fix(exclusive): allow the same client to resubscribe to an existing exclusive topic

- .ci/docker-compose-file/openldap/README.md
- apps/emqx_auth_ldap/test/emqx_authn_ldap_SUITE.erl
- apps/emqx_auth_ldap/test/emqx_authz_ldap_SUITE.erl
- apps/emqx_ldap/src/emqx_ldap.erl
- changes/ce/feat-13521.en.md
- rel/config/ee-examples/ldap-authn.conf
Fixes [EMQX-12758](https://emqx.atlassian.net/browse/EMQX-12758)
In case a LDAP query timed out, the socket may enter an unusable state, so it must be reconnected.
This PR forces a restart of eldap process when socket closed or socket error.
[EMQX-12758]: https://emqx.atlassian.net/browse/EMQX-12758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 0725 add ldap reconnect on timeout

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
Should have gone into https://github.com/emqx/emqx/pull/13518, which was merged too soon.
Fixes https://emqx.atlassian.net/browse/EMQX-12656
> feat: attempt to automatically decode `payload` similar to key and message templates

- apps/emqx_utils/src/emqx_variform_bif.erl
- apps/emqx_utils/test/emqx_variform_bif_tests.erl
- changes/ce/feat-13507.en.md
follow-up fix for PR https://github.com/emqx/emqx/pull/13507
> refactor: force getenv to access only OS env with prefix EMQXVAR_

- .github/workflows/build_and_push_docker_images.yaml
/etc/docker/daemon.json requires root for read access
Fixes "out of disk space" issue when building docker images.
> ci: fix docker images build

- apps/emqx_plugins/src/emqx_plugins.erl
- changes/ce/fix-13552.en.md
Fixes [EMQX-12795](https://emqx.atlassian.net/browse/EMQX-12795)
[EMQX-12795]: https://emqx.atlassian.net/browse/EMQX-12795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add a startup timeout limit for the plugin application

- apps/emqx_connector/src/emqx_connector_resource.erl
If a resource is created in a bad（broken） state, then the alarm should be activated rather than deactivated.
> fix: deactivate alarm before create resource

- apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl
- apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.hrl
- apps/emqx_durable_storage/src/emqx_ds.erl
- apps/emqx_durable_storage/src/emqx_ds_buffer.erl
- apps/emqx_durable_storage/src/emqx_ds_precondition.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_layout_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl
Support recent `emqx_ds` API changes in `emqx_ds_builtin_raft` backend, storage layer and all 3 storage layouts.
Note: preconditions support in `emqx_ds_builtin_raft` is not robust and production-grade. Due to a slight mismatch between concepts of _snapshot_ in `ra` and _snapshot_ in the storage layer, there's a small risk of diverging replicas. This will be fixed in a followup PR.
For details see individual commits.
Prerequisite for #13542.
> feat(dsraft): support atomic batches + preconditions

- apps/emqx/rebar.config
- mix.exs
- rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-11197
After this change, SSL listeners will be failed to get started if any SSL options invalid.
> chore: update esockd to 5.12.0

- apps/emqx_management/src/emqx_mgmt_cli.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12824
Since the check for `singleton` strategy lives in ekka but we were calling mria directly, nodes could still join.
Now, it fails with the expected reason:
```sh
root@0d5258031ac9:/emqx# bin/emqx ctl cluster join emqx@emqxtmp0.emqx.net
Failed to join the cluster: singleton
```
> fix: use ekka when performing `emqx ctl cluster *`

- .github/workflows/_push-entrypoint.yaml
`RUN_FROM` was using builder image and the final docker image size was > 1GB.
The image has been rebuilt and updated, this is to ensure it stays this way in case we need to release another one 5.7.x.
Release version: v/e5.7.*
> ci: fix RUN_FROM for the docker image

- apps/emqx_auth_jwt/src/emqx_authn_jwt.erl
- apps/emqx_auth_jwt/test/emqx_authn_jwt_SUITE.erl
iat means "issued at", which is the unix epoch to record the time when the token was issued.
previously, iat is not allowed to be in the future. this cause some trouble for tokens issued in a host which does not have clock synchronized.
given that the most important (security wise) claims are nbf (not before) and exp (expire), iat validation has been removed.
> fix: do not validate JWT iat

- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx/test/emqx_config_SUITE.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- changes/ce/feat-13525.en.md
- rel/i18n/emqx_schema.hocon
Add new configuration item `shared_subscription_initial_sticky_pick` for choosing the strategy for the initial pick when `shared_subscription_strategy` is `sticky`.
Related to https://github.com/emqx/emqx/pull/12676
> feat: Add new configuration item shared_subscription_initial_sticky_pick

- .github/workflows/_push-entrypoint.yaml
> ci: fix push_entrypoint workflow

- .github/workflows/codeql.yaml
CodeQL analysis for cpp does not work when we build in container, but run analyze on host.
> ci: use build container in codeql workflow

- apps/emqx_management/src/emqx_mgmt_api_relup.erl
- apps/emqx_management/src/proto/emqx_mgmt_api_relup_proto_v1.erl
- rebar.config.erl
- Relup failed due to get incorrect target vsn. We don't need target vsn anymore because we have only one tarball in the relup-plugin.
- Speed up package info reading by appending hash str to the unpacked dir name.
https://emqx.atlassian.net/browse/EMQX-12897
Release version: e5.8.0
> fix: got incorrect target version when relup

- apps/emqx_message_transformation/src/emqx_message_transformation.erl
- apps/emqx_message_transformation/src/emqx_message_transformation_http_api.erl
- apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12849
Fixes https://emqx.atlassian.net/browse/EMQX-12853
> fix(message transformation): increment failures when final payload is not a binary, and handle variform eval crashes

- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_management/src/emqx_mgmt_data_backup.erl
`emqx.git` as dependency for `emqtt` fails on OTP 25.
Not dialyzer check fail, but compile failure.
```
_build/test/lib/emqx/apps/emqx/src/emqx_listeners.erl:67:2: unknown dialyzer warning option: no_unknown
```
> 0816 no unknown dialyzer option otp 26 or later

- apps/emqx/src/emqx_broker.erl
- apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl
- apps/emqx_rule_engine/src/emqx_rule_actions.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl
- apps/emqx_utils/src/emqx_variform_bif.erl
- changes/ce/feat-13516.en.md
- rel/i18n/emqx_rule_engine_schema.hocon
Fixes https://github.com/emqx/emqx/issues/13511
The republish action triggers `message.publish` hook which then triggers the republish action itself again. i.e. dead-loop
This PR adds a new option named `direct_dispatch` to the republish action so it can skip running the `message.pubhsh` hook again.
This should allow forwarding messages mutually (without topic name-space) between two clusters without looping.
Example config:
```
rule_engine {
ignore_sys_message = true
jq_function_default_timeout = "10s"
rules {
brdige-unmount {
actions = [
{
args {
direct_dispatch = true
mqtt_properties {}
payload = "${payload}"
qos = 0
retain = false
topic = "${newtopic}"
user_properties = ""
}
function = republish
}
]
description = ""
enable = true
metadata {created_at = …
```
> feat: make republish action possible run without dead-loop

- apps/emqx_auth_http/test/emqx_authn_scram_restapi_SUITE.erl
- apps/emqx_auth_kerberos/rebar.config
- apps/emqx_auth_mnesia/mix.exs
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src
- apps/emqx_auth_mnesia/src/emqx_authn_scram_mnesia.erl
- apps/emqx_auth_mnesia/test/emqx_authn_scram_mnesia_SUITE.erl
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_machine/priv/reboot_lists.eterm
- apps/emqx_utils/src/emqx_utils_scram.erl
- mix.exs
- rebar.config
`sasl_auth-2.3.0` added the scram implementation so there is no need for the `esasl` lib any more.
- [n/a] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [n/a] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
> refactor: remove esasl from deps, use sasl_auth 2.3.0

- apps/emqx_auth_kerberos/src/emqx_authn_kerberos.erl
- apps/emqx_auth_kerberos/test/emqx_authn_kerberos_SUITE.erl
EMQX should allow HTTP APIs to send authenticator create request without keytab_file.
- [~ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
a fixup for feature not released yet.
no changes
> fix(authn/kerberos): allow keytab_file missing in create request

- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx/src/emqx_trace/emqx_trace_dl.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
Prior to this fix, the start_at provided when creating the trace is overriden if it's earlier than the current system time.
it's not necessary to ensure `start_at` is always the latest second because the exact start time might be delayed anyway (due to the async nature of the trace start/stop being triggered by message passing and timer events).
This is unnecessary, and leads to test cases being flaky.
> fix(trace): respect trace start_at time as is

- apps/emqx_auth/src/emqx_authn/emqx_authn_api.erl
- apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_api_SUITE.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_chains_SUITE.erl
- changes/ce/fix-13678.en.md
Prior to this fix, if a authenticator is failed to get initialized when node boots up, it will be displayed on dashboard in "disconnected" state.
But when we try to delete it from dashboard, a "not found" error is returned.
This is because although the config exists, it was not actually added to the chain (failed to init).
After this fix, the deletion in from the chain is made idempotent, i.e. allow delete even if it's not on the chain already.
> fix(authn): allow deleting an authenticator which failed to initialize

- Makefile
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
The last fix did not work because the flag was read at init time when `global` starts.
This is an attempt to fix test flakiness 
```
'global' at node 'test@127.0.0.1' requested disconnect from node 't_crash_stop_recover2@127.0.0.1' in order to prevent overlapping partitions
```
> test: ensure prevent_overlapping_partitions from ERL_FLAGS

- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
- apps/emqx_conf/test/emqx_conf_cluster_sync_SUITE.erl
Fixes:
1. Keep cores always ahead of replicants.
2. Keep the original node order when `tnxid` is the same（the order was reversed before fixing）.
This PR ensure that we find the right config leader.
> fix: ensure that cores are always positioned ahead of replicants

- mix.exs
- rebar.config
```
1.7.5
Fix crash when mnesia table with external copies. Which mnesia:table_info(TabName, storage_type) returns tuple {ext, _, _}
Correct the order of the application information; the items Memory and Reductions have been switched.
1.7.4
fix crash when ets:info/1 return undefined.
1.7.3
fix system pane exception by ps command.
1.7.2
Fix error when inspecting process that monitors via {RegName, Node}.
```
> chore: bump observer_cli from 1.7.1 to 1.7.5

- apps/emqx_enterprise/src/emqx_enterprise.app.src
- apps/emqx_enterprise/src/emqx_enterprise_schema.erl
- apps/emqx_enterprise/test/emqx_enterprise_schema_tests.erl
- apps/emqx_oracle/src/emqx_oracle.app.src
- apps/emqx_oracle/src/emqx_oracle_schema.erl
The idea is to only use this new macro for introducing extra schema modules that are idiosyncratic to the repo itself, thus avoiding missing some schema modules when overridding `?EE_SCHEMA_MODULES` as is done today.
> refactor: introduce extra macro to be overridden in different repos

- apps/emqx_auth_kerberos/rebar.config
- apps/emqx_bridge_azure_event_hub/mix.exs
- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/mix.exs
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/mix.exs
- apps/emqx_bridge_kafka/rebar.config
- mix.exs
- rebar.config
Upgrade libs:
`brod_gssapi-0.1.3`: `sasl_auth:client_done` was previously missing, maybe causing mem leak, but unsure
`sasl_auth-2.3.1`: changed to use `MEMORY` (previously `FILE`) type credentials cache, should fix the flaky tests
> 0829 upgrade kerberos auth libs

- apps/emqx/src/emqx_broker_sup.erl
- apps/emqx/src/emqx_exclusive_subscription.erl
- changes/ce/fix-13702.en.md
> fix(exclusive): clean-up exclusive subscriptions when a node is down

- apps/emqx/src/emqx_tls_lib.erl
- apps/emqx/test/emqx_listeners_update_SUITE.erl
- apps/emqx/test/emqx_ocsp_cache_SUITE.erl
- apps/emqx/test/emqx_tls_lib_tests.erl
- apps/emqx_auth/src/emqx_auth.app.src
- apps/emqx_auth/src/emqx_authn/emqx_authn_api.erl
- apps/emqx_connector/src/emqx_connector_ssl.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard.app.src
- apps/emqx_dashboard/src/emqx_dashboard_listener.erl
- apps/emqx_gateway/src/emqx_gateway.app.src
- apps/emqx_gateway/src/emqx_gateway_http.erl
- changes/ce/fix-13733.en.md
- scripts/test/start-two-nodes-in-docker.sh
It's not common for dashboard to verify client certs.
- Make cacertfile optional for dashboard https listener
- The pem files being missing seems to be a common error to happen. This PR also refines the output of the key paths in logs.
> cacertfile should be optional for dashboard https listener

- apps/emqx/test/emqx_proper_types.erl
- apps/emqx_ft/test/props/prop_emqx_ft_assembly.erl
This should likely help to avoid proptest instances where seconds need to be spent on `emqx_proper_types:generate/2` of segments list.
> test(ft): make proptest scaling less aggressive

- apps/emqx/src/emqx_base62.erl
- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_guid.erl
- apps/emqx/test/emqx_guid_SUITE.erl
- apps/emqx/test/props/prop_emqx_base62.erl
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq.app.src
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl
- apps/emqx_ft/test/emqx_ft_conf_SUITE.erl
- apps/emqx_gateway_coap/src/emqx_coap_channel.erl
- apps/emqx_gateway_coap/src/emqx_gateway_coap.app.src
- apps/emqx_gateway_mqttsn/src/emqx_gateway_mqttsn.app.src
- apps/emqx_gateway_mqttsn/src/emqx_mqttsn_channel.erl
- apps/emqx_gateway_stomp/src/emqx_gateway_stomp.app.src
- apps/emqx_gateway_stomp/src/emqx_stomp_channel.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- apps/emqx_utils/src/emqx_utils.app.src
- apps/emqx_utils/src/emqx_utils.erl
- changes/ce/fix-13756.en.md
The new algorithm has a fixed length of 16 random bytes `a-zA-Z0-9` with first char guaranteed to be `a-zA-Z`.
The old algorithm is perhaps random enough, but the impl looks rather like a bug by bloating 22 bytes to 47 bytes.
> refactor: more-random bytes for broker assigned IDs

- apps/emqx/test/emqx_takeover_SUITE.erl
For MQTT5, we need session expire > 0 to ensure session didn't get discarded when DS session is enabled.
Case were passed due to session takeover happens in the same millisec window.
> test: fix flaky takeover_willmsg when persistent enabled

- apps/emqx_bridge_http/src/emqx_bridge_http.app.src
- apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
- apps/emqx_bridge_http/test/emqx_bridge_http_v2_SUITE.erl
This is only an internal fix for duplicated headers sent to the http client lib.
No user impact.
- [n/a] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
> fix: http headers merge action on connector

- apps/emqx_bridge_http/src/emqx_bridge_http.app.src
- apps/emqx_schema_registry/src/emqx_schema_registry.app.src
- apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl
> fix(schema_registry): added OTP version into the cache key for a mixed cluster

- apps/emqx/src/emqx_schema.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
No impact to users.
It's a server-only option, should not have been added to client opts.
> chore: deprecate user_lookup_fun for client SSL option

- apps/emqx/rebar.config
- mix.exs
- rebar.config
Upgrade hocon to 0.43.4 https://github.com/emqx/hocon/pull/300
Prior to this fix, if an http action is named `webhook` it would cause a crash.
> chore: upgrade hocon to 0.43.4

- apps/emqx_auth_kerberos/rebar.config
- mix.exs
- rebar.config
remove -flat_namespace flag from linker flags on Darwin
Fixes Homebrew emqx formula.
> chore: bump sasl_auth to 2.3.2

- apps/emqx_auth_http/src/emqx_auth_http.app.src
- apps/emqx_auth_http/src/emqx_authn_http.erl
Fixes https://askemq.com/t/topic/9369/2
- ~Change log has been …
> fix(autn_http): log an error when `content_type` is unsupported

- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl
- changes/ce/fix-13790.en.md
Depending on different cloud vendors, the TCP idle limit can vary from 3 ~  5 minutes.
Meaning, after idling for 3 ~ 5 minutes, the TCP link is silently dropped by the gateway/firewall/load-balancer whatsoever.
Prior to this change, the default PING interval (keepalive) for MQTT connector is 300s (5m) which is doomed to fail.
This PR changes default to 160.
- ~[ ] Created PR to …
> fix: change default hearbeat interval to 160s for mqtt connector

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.app.src
- apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.erl
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_confluent/src/emqx_bridge_confluent.app.src
- apps/emqx_bridge_confluent/src/emqx_bridge_confluent_producer.erl
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- changes/ee/feat-13783.en.md
- mix.exs
- rel/i18n/emqx_bridge_azure_event_hub.hocon
- rel/i18n/emqx_bridge_confluent_producer.hocon
- rel/i18n/emqx_bridge_kafka.hocon
The async reply context can be minimized to a very static term.
- no need to track `buffer_worker` pid when it's not sent through a buffer worker
- no need to add `request_ref` if it's not sent through a buffer worker
- only `simple_query` option is needed in reply context, so the `query_opts` can be replayed with `simple_query => true | false`
before:
```
{fun emqx_bridge_kafka_impl_producer:on_kafka_ack/3,
[{fun emqx_resource_buffer_worker:handle_async_reply/2,
[#{resource_id =>
<<"action:kafka_producer:a:connector:kafka_producer:a">>,
inflight_tid => undefined,worker_index => undefined,
buffer_worker => <0.5178.0>,
query_opts =>
#{timeout => infinity,
reply_to =>
{fun emqx_rule_runtime:inc_action_metrics/2,
[#{action_id => {bridge_v2,kafka_producer,a},
rule_id …
```
> perf: minimize rule action async reply context

- .ci/docker-compose-file/docker-compose-kdc.yaml
- .ci/docker-compose-file/docker-compose.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/performance_test.yaml
- .github/workflows/release.yaml
- deploy/docker/Dockerfile
- env.sh
- scripts/buildx.sh
CS says we need to keep el7 for now.
> fix: release el7 packages again

- .github/workflows/_push-entrypoint.yaml
other jobs which depend on it only run on releases
> ci: always run compile job in push entrypoint

- .ci/docker-compose-file/confluent-schema-registry/jaas.conf
- .ci/docker-compose-file/confluent-schema-registry/password-file
- .ci/docker-compose-file/docker-compose-confluent-schema-registry.yaml
- apps/emqx/src/emqx_schema.erl
- apps/emqx_bridge_azure_blob_storage/src/emqx_bridge_azure_blob_storage_action_schema.erl
- apps/emqx_bridge_s3/src/emqx_bridge_s3.app.src
- apps/emqx_bridge_s3/src/emqx_bridge_s3_upload.erl
- apps/emqx_mix_utils/lib/mix/tasks/emqx.eunit.ex
- apps/emqx_schema_registry/docker-ct
- apps/emqx_schema_registry/mix.exs
- apps/emqx_schema_registry/rebar.config
- apps/emqx_schema_registry/src/emqx_schema_registry.app.src
- apps/emqx_schema_registry/src/emqx_schema_registry.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_app.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_config.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_external.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_schema.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_sup.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_serde_SUITE.erl
- changes/ee/feat-13804.en.md
- mix.exs
- rel/i18n/emqx_schema_registry_http_api.hocon
- rel/i18n/emqx_schema_registry_schema.hocon
- scripts/ct/run.sh
Fixes https://emqx.atlassian.net/browse/EMQX-12800
- Implement config import support for `schema_registry.external`. 
> feat(schema registry): add external schema registry support

- apps/emqx_auth/include/emqx_authn.hrl
- apps/emqx_auth/src/emqx_authn/emqx_authn_schema.erl
- apps/emqx_auth_cinfo/BSL.txt
- apps/emqx_auth_cinfo/README.md
- apps/emqx_auth_cinfo/include/emqx_auth_cinfo.hrl
- apps/emqx_auth_cinfo/mix.exs
- apps/emqx_auth_cinfo/rebar.config
- apps/emqx_auth_cinfo/src/emqx_auth_cinfo.app.src
- apps/emqx_auth_cinfo/src/emqx_auth_cinfo_app.erl
- apps/emqx_auth_cinfo/src/emqx_auth_cinfo_sup.erl
- apps/emqx_auth_cinfo/src/emqx_authn_cinfo.erl
- apps/emqx_auth_cinfo/src/emqx_authn_cinfo_schema.erl
- apps/emqx_auth_cinfo/test/emqx_authn_cinfo_SUITE.erl
- apps/emqx_auth_cinfo/test/emqx_authn_cinfo_int_SUITE.erl
- apps/emqx_auth_ext/src/emqx_auth_ext.app.src
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema_inject.erl
- apps/emqx_machine/priv/reboot_lists.eterm
- apps/emqx_utils/src/emqx_utils.erl
- apps/emqx_utils/src/emqx_variform.erl
- apps/emqx_utils/src/emqx_variform_bif.erl
- apps/emqx_utils/src/emqx_variform_parser.yrl
- apps/emqx_utils/src/emqx_variform_scan.xrl
- apps/emqx_utils/test/emqx_variform_tests.erl
- changes/ee/feat-13810.en.md
- mix.exs
- rebar.config.erl
- rel/config/ee-examples/cinfo-authn.conf
- rel/i18n/emqx_authn_cinfo_schema.hocon
https://emqx.atlassian.net/browse/EMQX-12626
ClientInfo based authentication is a light-weight rule-based authentication mechanism.
It is useful in below cases.
- As a fencing mechanism for invalid/intrusive clients.
For example, if valid clients should all start with a prefix, there should be no need to check other authenticators (which are usually heavier)
- As an extended validation for client misconfiguration.
For example, after client certificate is validated (mTLS), it might be enough to check if the client ID is the same as certificate common name.
- A secret algorithm or a secret to validate password.
For example, `password = sha256(clientid + secret)`
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over …
> Clientinfo authentication

- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
- apps/emqx_connector/src/emqx_connector.erl
- apps/emqx_connector/src/emqx_connector_api.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
Only a internal refactoring, no interface changes.
This is to prepare for another refactoring which can help to reduce the number of ets copies unless absolutely necessary.
> refactor: add is_exist API for resource existence check

- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_broker_sup.erl
- apps/emqx/src/emqx_pool_sup.erl
Fixes [EMQX-13127](https://emqx.atlassian.net/browse/EMQX-13127)
Fix ownership of the emqx_broker's runtime tables. Fix restart strategy for `emqx_broker`.
[EMQX-13127]: https://emqx.atlassian.net/browse/EMQX-13127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(broker): Fix ownership of subopt table

- apps/emqx_bridge_snowflake/docs/user-guide.md
Since the payload column type is `string` and snowflake doesn't handle double quote escaping correctly by default, we need to tell it to consider escaped CSV columns.
> docs(snowflake): minor fix

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_keepalive.erl
- apps/emqx/src/emqx_quic_connection.erl
- apps/emqx/src/emqx_quic_data_stream.erl
- apps/emqx/test/emqx_quic_multistreams_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- changes/ce/feat-13814.en.md
Fixes [EMQX-13134](https://emqx.atlassian.net/browse/EMQX-13134)
Intro a new feature for MQTT over QUIC multi-stream, called connection scope keepalive
We used to require the client to send MQTT.PINGREQ on idle control stream to keep the connection alive even when the data stream is active, this PR intro a conn shared state which has counters could be bumped by all the streams in the same connection, so the keepalive  could read this shared counters to judge if conn is still alive. 
This hopefully could further mitigate the keepalive timeout due to HOL blocking.
[EMQX-13134]: …
> feat(quic): conn scope keepalive

- Makefile
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_producer_SUITE.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- apps/emqx_connector/src/emqx_connector_resource.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/include/emqx_resource_runtime.hrl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/src/emqx_resource_cache.erl
- apps/emqx_resource/src/emqx_resource_cache_cleaner.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_sup.erl
- apps/emqx_resource/test/emqx_resource_tests.erl
- scripts/git-hook-pre-commit.sh
Fixes: https://emqx.atlassian.net/browse/EMQX-11308
Prior to this fix, resource manager state data is cached in ets table (via grpoc).
It's quite a bloated map to copy for each and every message to send,
it's especially expensive when there are multiple channels added to one connector.
This PR breaks up the cache into 3 parts.
- Connector `status`, `error` and `config` are cached in ets table `emqx_resource_cache`,
since `status` and `error` tend to change often, it makes less sense to cache in persistent-term. 
Also,`status` and `error` are grouped into the same record field of the cached tuple, so it can be looked-up with `ets:lookup_element` to avoid copying the full record (`config` can be large).
- Connector's channels (actions) are cached in the same ets …
> perf: optimize resource status/state/error cache

- apps/emqx/src/emqx.erl
- apps/emqx_auth/etc/acl.conf
- apps/emqx_auth/src/emqx_auth_utils.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_file_SUITE.erl
- changes/ce/feat-13863.en.md
- Allow `${cert_common_name}` in raw ACL rule templates.
> feat: allow TLS cert common name in file authz templates

- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- changes/ce/feat-13873.en.md
Partially fixes [EMQX-12962](https://emqx.atlassian.net/browse/EMQX-12962)
The old downsample implementation was not recursive.
So it only does reduce once, from maximum 60480 -> 30240, then that's it.
When the table is full (`60480` records), the latency of `/api/v5/monitor?latest=604800` call is:
- Baseline: `2.5s` (single node)
- After downsample algorithm fix: `500ms` (single node)
- Wall-clock aligned timestamps: `260ms` (single node)
- No sorting: `230ms` (single node, and the same for two-node cluster).
Evaluate below expression in `remote_console` to generate random data points.
```
D = #{dropped => 0,sent => 1,connections => 1000,topics => 0,
persisted => 0,received => 0,live_connections => 1000,
disconnected_durable_sessions => 0,
subscriptions_durable …
```
> perf: dashboard monitor downsample algorithm

- .ci/docker-compose-file/.env
- .ci/docker-compose-file/docker-compose-sqlserver.yaml
- .ci/docker-compose-file/docker-compose-toxiproxy.yaml
- .ci/docker-compose-file/docker-compose.yaml
- .ci/docker-compose-file/odbc/odbcinst.ini
- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl
- deploy/docker/Dockerfile.msodbc
- scripts/install-msodbc-driver.sh
v17 package is no longer available in the Microsoft repository
Fixes [EMQX-13210](https://emqx.atlassian.net/browse/EMQX-13210)
[EMQX-13210]: https://emqx.atlassian.net/browse/EMQX-13210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use MS SQL Server ODBC driver v18 by default

- apps/emqx_cluster_link/src/emqx_cluster_link_schema.erl
- apps/emqx_cluster_link/test/emqx_cluster_link_api_SUITE.erl
- changes/ee/fix-13888.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13183
> fix(cluster link api): clientid is not required when updating

- apps/emqx/src/proto/emqx_proto_v1.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_metrics.erl
- apps/emqx_management/test/emqx_mgmt_api_metrics_SUITE.erl
Fixes [EMQX-13177](https://emqx.atlassian.net/browse/EMQX-13177)
For `/api/v5/monitor_current` and `/api/v5/metrics` APIs, perform queries in parallel towards running nodes.
[EMQX-13177]: https://emqx.atlassian.net/browse/EMQX-13177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> perf: concurrent nodes query for `/monitor_current` and `/metrics` api

- apps/emqx/test/emqx_bpapi_static_checks.erl
- apps/emqx_machine/src/emqx_machine.erl
- apps/emqx_machine/src/emqx_machine_replicant_health_probe.erl
- apps/emqx_machine/src/emqx_machine_sup.erl
- changes/ce/feat-13903.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12103
> feat(machine): print warning when there are no core nodes at same version

- apps/emqx/src/emqx_packet.erl
- apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
- apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
- apps/emqx/test/emqx_packet_tests.erl
- apps/emqx/test/emqx_trace_SUITE.erl
- changes/ce/fix-13909.en.md
```
2024-08-30T11:06:12.595771+02:00 [debug] msg: SEND_Data, packet: 
[[80,85,66,76,73,83,72,40,81,"0",44,32,82,"0",44,32,68,"0"],", ",
[[84,111,112,105,99,61,"$LINK/cluster/route/zmd",44,32,80,97,99,107,101,116,73,100,61,"undefined"],", ",
["Payload=",{error,[],<<131,116,0,0,0,3,97,10,109,0,0,0,14,101,109,113,120,64,49,50,55,
46,48,46,48,46,49,97,11,110,6,0,160,97,136,162,145,1,119,3,36,111,112,109,0,0,0,9,104,101,
97,114,116,98,101,97,116>>}]],")"], socket: #Port<0.87>
```
> Fix mqtt payload formatter error

- apps/emqx_utils/src/emqx_utils_redact.erl
- apps/emqx_utils/test/emqx_utils_redact_tests.erl
- apps/emqx_utils/test/emqx_utils_tests.erl
It's kinda silly to render a template var ref as `******` for the dashboard.
This PR make it 'smarter' but risking at clashing an authentic sensitive string value.
e.g. if one sets password as `${looks_like_a_var_but_not_really}`, then nobody except for themselves will should sorry.
> chore: do not obfuscate vars in templates

- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- changes/ce/fix-13916.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13107
> fix(rule engine metrics): bump `failed` metric when its sub-counters are bumped

- apps/emqx/include/emqx_placeholder.hrl
- apps/emqx/src/emqx_mountpoint.erl
- apps/emqx_auth/include/emqx_authn.hrl
- apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_file_SUITE.erl
- apps/emqx_auth_mongodb/src/emqx_auth_mongodb.app.src
- apps/emqx_auth_mongodb/src/emqx_authz_mongodb.erl
- apps/emqx_auth_mysql/src/emqx_auth_mysql.app.src
- apps/emqx_auth_mysql/src/emqx_authz_mysql.erl
- apps/emqx_auth_postgresql/src/emqx_auth_postgresql.app.src
- apps/emqx_auth_postgresql/src/emqx_authz_postgresql.erl
- apps/emqx_auth_redis/src/emqx_auth_redis.app.src
- apps/emqx_auth_redis/src/emqx_authz_redis.erl
- changes/ce/feat-13923.en.md
Added `zone` to authentication, authorization and mountpoint template.
Prior to this change, if one wants to use `zone` name in authentication or authorization rules, they would have to use `client_attrs`.
Now `${zone}` can be used directly in authentication and authentication.
As an example, here is an ACL rule making use of `zone`: `{allow, all, all, ["${zone}/${username}/#"]}`.
> Support zone in authn authz templates

- apps/emqx/src/emqx_crl_cache.erl
- apps/emqx/src/emqx_ssl_crl_cache.erl
- apps/emqx/test/emqx_crl_cache_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- changes/ce/fix-13922.en.md
Fixes [EMQX-12996](https://emqx.atlassian.net/browse/EMQX-12996)
Prior to this fix, CRL is cached with the path part of a URL, it leads to clash when two DPs happen to share the same path.
[EMQX-12996]: https://emqx.atlassian.net/browse/EMQX-12996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: cache CRL with full distribution point URL

- apps/emqx/src/emqx_broker.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_router_bootstrap.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_router_syncer.erl
- changes/ee/fix-13927.en.md
Provide dedicated `emqx_broker` API to "fold" over unique topics. Without it, cluster link bootstrap process relied on scanning `?SUBSCRIBER` table, and was likely to crash on internal "shard" records in this table. This slipped through tests because a cluster needs A LOT of subscribers for a single topic for those records to appear in the table.
> fix(cluster-link): provide `emqx_broker` API to fold over topics

- apps/emqx_cluster_link/src/emqx_cluster_link_app.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_config.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_extrouter_gc.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_router_syncer.erl
- apps/emqx_cluster_link/test/emqx_cluster_link_api_SUITE.erl
- changes/ee/fix-13928.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13098
One of the original issues is that handling heartbeats from an upstream agent rely on the message hook from cluster link app being in place.  Before this patch, after disabling the last link in a cluster, the message hook would be removed, and thus heartbeats from upstream agents would no longer be handled.  This led to live agents being garbage collected.  After the link is re-enabled, the agent state is already lost and does not recover.
The reason for it not recovering is the second issue (not handled here): even though `assert_current_incarnation` would crash while running the re-enabled hook, this crash is caught by `emqx_hooks:run_fold`, and the connection would not be closed.  Disconnecting the agent would …
> fix(cluster link): don't remove message publish hook if disabling the last link

- apps/emqx_gateway_ocpp/rebar.config
- apps/emqx_schema_registry/rebar.config
- mix.exs
- rebar.config
Fixes [EMQX-13219](https://emqx.atlassian.net/browse/EMQX-13219)
Also got rid of indirect dependency rfc3339
[EMQX-13219]: https://emqx.atlassian.net/browse/EMQX-13219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Upgrade jesse from 1.8.0.1 to 1.8.1.1

- apps/emqx_dashboard/include/emqx_dashboard.hrl
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
Fixes [EMQX-12962](https://emqx.atlassian.net/browse/EMQX-12962)
Followup PR https://github.com/emqx/emqx/pull/13873
[EMQX-12962]: https://emqx.atlassian.net/browse/EMQX-12962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Perf: in-place downsample monitor metrics

- apps/emqx_mysql/mix.exs
- apps/emqx_mysql/rebar.config
mysql client 1.7.4.2 added more context in the init failure error returns.
See PR: https://github.com/emqx/mysql-otp/pull/10
When there are more than one set of MySQL configs, it's quite hard to tell which one is for which.
before: `timeout`
after: `#{cause => timeout,port => 3306,user => <<"root">>,host => "1.1.1.1",database => <<"test">>}`
e.g.
2024-10-07T07:12:52.857393+00:00 [error] crasher: initial call: mysql_conn:init/1, pid: <0.6494.0>, registered_name: [], exit: {#{cause => timeout,port => 3306,user => <<"root">>,host => "1.1.1.1",database => <<"test">>},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,961}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}, ancestors: [<0.6493.0>,<0.6492.0>,<0.6490.0>,ecpool_sup,<0.4205.0>], …
> chore: upgrade mysql client from 1.7.4.1 to 1.7.4.2

- apps/emqx_cluster_link/src/emqx_cluster_link.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_extrouter_gc.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_mqtt.erl
- apps/emqx_cluster_link/src/emqx_cluster_link_router_syncer.erl
- apps/emqx_cluster_link/test/emqx_cluster_link_SUITE.erl
- apps/emqx_cluster_link/test/emqx_cluster_link_api_SUITE.erl
- changes/ee/fix-13929.en.md
See https://github.com/emqx/emqx/pull/13928
- Previously, even if an exception occurred (such as `assert_current_incarnation` failing, for example), the agent would stay connected instead of letting it crash and recover.
- `auto_reconnect` was not set for the `ecpool` used for the forwarding resource.  So, if connection was lost and workers died, they would stay dead.
- Publish result was not handled for async queries.  So, if `{error, ecpool_empty}` was returned while the pool was empty, the message would not be retried and lost.
> fix(cluster link): trigger agent disconnection on exceptions and resource fixes

- changes/ce/feat-13942.en.md
- mix.exs
- rebar.config
En enhancement to auto-recover: https://github.com/emqx/emqx/issues/12974
ehttpc-0.6.0 introduced zombie connection detection.
see https://github.com/emqx/ehttpc/pull/57
by default, if a http connection is inactive for more than 10s after the last sent request has been expired, it will try to reconnect.
Before the connection is force restarted, an `error` level log with message `force_reconnecting_zombie_http_connection` is written.
> chore: upgrade ehttpc from 0.5.0 to 0.6.0

- apps/emqx/src/emqx_ds_schema.erl
- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs.erl
- apps/emqx/src/emqx_types.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_api.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_group_sm.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_proto_format.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_queue.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_schema.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_store.erl
- apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_SUITE.erl
- apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_api_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
Fixes [EMQX-12588](https://emqx.atlassian.net/browse/EMQX-12588).
Since `dqleader` storage layout is now mostly fixed and controlled by the application itself, `layout` setting won't take any effect.
[EMQX-12588]: https://emqx.atlassian.net/browse/EMQX-12588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(dssubs): add facilities to iterate through the store

- apps/emqx_auth_cinfo/README.md
- apps/emqx_auth_cinfo/src/emqx_authn_cinfo.erl
- apps/emqx_auth_cinfo/test/emqx_authn_cinfo_SUITE.erl
- apps/emqx_utils/src/emqx_variform_bif.erl
- apps/emqx_utils/test/emqx_variform_bif_tests.erl
- changes/ee/feat-13810.en.md
- rel/config/ee-examples/cinfo-authn.conf
- rel/i18n/emqx_authn_cinfo_schema.hocon
Fixes [EMQX-13163](https://emqx.atlassian.net/browse/EMQX-13163) and [EMQX-13168](https://emqx.atlassian.net/browse/EMQX-13168)
[EMQX-13163]: https://emqx.atlassian.net/browse/EMQX-13163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-13168]: https://emqx.atlassian.net/browse/EMQX-13168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
> 1008 fix peerhost format for cinfo auth

- .github/workflows/_push-entrypoint.yaml
- .github/workflows/performance_test.yaml
Fixes [EMQX-13182](https://emqx.atlassian.net/browse/EMQX-13182)
Example test run: https://github.com/emqx/emqx/actions/runs/11237098542
Rewrote `performance_test` workflow.
Now it will be called when a release tag is pushed (incl. alpha, beta and rc), and will run a set of predefined performance tests (for now it's just `tests/ci/pubsub-2x2c4g-10k-20k-tps`).
The job will be considered successful if all of the conditions below are met:
- initial RAM usage on EMQX nodes are within the predefined boundaries
- CPU and RAM usage on EMQX nodes during load test are within the predefined boundaries
- average message rate during test run is within the predefined boundaries
The job can be triggered manually for specified EMQX version.
Related PRs:
- …
> update perf test

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- changes/ee/fix-13971.en.md
- mix.exs
Fixes [EMQX-13137](https://emqx.atlassian.net/browse/EMQX-13137)
This upgrade fixes two issues.
1. A bug in wolff-4.0.0 which is not released in EMQX Enterprise 5.8.1 yet, causing the producer process to crash when buffer overflow happens while there are inflight requests sent towards Kafka. 
Example exception: `#{cause => unexpected_id,max => 1728471879846415,min => 1728471879846415,got => 1728471879846430}`
2. A bug since wolff-3.0.0 which was released in EMQX Enterprise 5.8.0. In some corner cases, if the producer failed to fetch metadata for an existing topic, it may crash with this exception: `{{badmap,{not_initialized,1,failed_to_fetch_metadata}},[{maps,merge,[#{},{not_initialized,1,failed_
to_fetch_metadata}],[{error_info,#{module => …
> fix: upgrade wolff from 4.0.0 to 4.0.2

- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- changes/ee/fix-13973.en.md
before this patch emqx would log a few errors each time connector is stopped
fixes [EMQX-13224](https://emqx.atlassian.net/browse/EMQX-13224)
[EMQX-13224]: https://emqx.atlassian.net/browse/EMQX-13224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: call odbc:disconnect/1 when sqlserver pool worker is terminated

- apps/emqx_retainer/src/emqx_retainer.erl
- apps/emqx_retainer/src/emqx_retainer_gc.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/src/emqx_retainer_schema.erl
- apps/emqx_retainer/src/emqx_retainer_sup.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_dummy.erl
- apps/emqx_retainer/test/emqx_retainer_gc_SUITE.erl
- apps/emqx_utils/src/emqx_utils_stream.erl
- apps/emqx_utils/test/emqx_utils_stream_tests.erl
- rel/i18n/emqx_retainer_schema.hocon
Fixes [EMQX-13213](https://emqx.atlassian.net/browse/EMQX-13213).
[EMQX-13213]: https://emqx.atlassian.net/browse/EMQX-13213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(retainer): clean expired messages in separate process

- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_api.erl
- apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_api_SUITE.erl
Fixes [EMQX-13253](https://emqx.atlassian.net/browse/EMQX-13253).
Fixes [EMQX-13254](https://emqx.atlassian.net/browse/EMQX-13254).
[EMQX-13253]: https://emqx.atlassian.net/browse/EMQX-13253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-13254]: https://emqx.atlassian.net/browse/EMQX-13254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dssubs): disable API as well if durable queues are disabled

- .github/workflows/performance_test.yaml
When calling workflow, the event comes from the parent workflow.
Using negative match instead to decide if we need to download artifact.
> ci: update condition for downloading artifact in perf test workflow

- bin/emqx
Now the user is able to use epmd mode by setting the EPMD_ARGS manually:
```
EPMD_ARGS="-start_epmd=true" _build/emqx-enterprise/rel/emqx/bin/emqx console
```
This is useful when a developer wants to connect a temporary Erlang node to the EMQX node. For example, the developer may want to enable the observer tool in another Erlang shell to debug a remote EMQX node:
```
erl -name test@127.0.0.1 -setcookie emqxsecretcookie
(test@127.0.0.1)2> observer:start().
```
> feat: supports user-defined EPMD_ARGS environment variable

- apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_connector_aggregator/src/emqx_connector_aggregator.app.src
- apps/emqx_connector_aggregator/src/emqx_connector_aggregator.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13302
1) First allocated buffer gets 3 records, its delivery is started and completes just fine.
2) As the 3rd record from the first batch is pushed, it triggers the allocation of a
second buffer.
3) After delivery is completed, 3 more records are pushed into this 2nd buffer.
4) As the 3rd record from the second batch is pushed, it triggers the allocation of a
3rd buffer.  This time, however, no delivery process is started.
5) Seconds later, probably due to a ~tick~ timeout, delivery of this 3rd, empty buffer is
started and completed, indeed reporting to be empty.  Delivery of the 2nd buffer is
never started.
Albeit the causing sequence of events causing the race condition is not yet exactly determined,
this is an …
> fix(connector aggregator): use `{continue, _}` instead of 0 timeout

- apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.app.src
- apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.erl
- apps/emqx_bridge_azure_event_hub/test/emqx_bridge_azure_event_hub_v2_SUITE.erl
- apps/emqx_bridge_confluent/src/emqx_bridge_confluent.app.src
- apps/emqx_bridge_confluent/src/emqx_bridge_confluent_producer.erl
- apps/emqx_bridge_confluent/test/emqx_bridge_confluent_producer_SUITE.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- apps/emqx_resource/src/emqx_resource.app.src
- changes/ee/breaking-14015.en.md
- changes/ee/fix-14015.en.md
- mix.exs
- rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-13242
Fixes https://emqx.atlassian.net/browse/EMQX-13248
> fix(kafka producer): kick off recovery from disk for fixed topics, migrate old replayq directories

- apps/emqx/rebar.config
- mix.exs
- rebar.config
🎉 https://github.com/zhongwencool/observer_cli/releases/tag/1.8.0 
- Now we can  see the number of bytes in the output distribution queue in **System** view
- **Process Label Display**: Now shows the process's label when set using proc_lib:set_label(Label).
> chore: observer_cli support show process's label/node's dist queue size

- apps/emqx/src/emqx_logger_textfmt.erl
- apps/emqx/src/emqx_packet.erl
- apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
- apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
- apps/emqx/test/emqx_packet_tests.erl
Fix the incorrect format when printing MQTT packets:
```
2024-10-21T13:53:58.024182+08:00 [debug] tag: MQTT, clientid: emqx1, msg: mqtt_packet_received, peername: 127.0.0.1:58863, username: emqx1, packet: [[80,85,66,76,73,83,72,40,81,"1",44,32,82,"0",44,32,68,"0"],", ",[[84,111,112,105,99,61,"t/1",44,32,80,97,99,107,101,116,73,100,61,"13152"],", ",["Payload=",<<"{\"Artist\": \"a\",\"SongTitle\": \"a\"}">>]],")"]
```
This issue was probably introduced by https://github.com/emqx/emqx/pull/13909
After the fix,
text:
```
2024-10-21T15:16:06.614214+08:00 [debug] tag: MQTT, clientid: emqx1, msg: mqtt_packet_received, peername: 127.0.0.1:49418, username: emqx1, packet: PUBLISH(Q1, R0, D0, Topic=t/1, PacketId=21863, Payload(text)={"Artist": "a","SongTitle": "a"})
``` …
> fix: incorrect format when printing packets in log

- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- changes/ce/fix-14023.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13262
When compacting or downsampling data for local node only, since data points are repeated snapshots until a change is recorded, we need to keep the latest values instead of summing them up.
https://github.com/user-attachments/assets/3e3152ed-0575-46e4-ba97-abb0b2ccec13
https://github.com/user-attachments/assets/f899b21d-d36b-4d0a-bbd0-86657f3af249
> fix(dashboard monitor): don't sum data for local aggregation

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- changes/ee/feat-14048.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13338
> feat(kafka producer): do not consider action disconnected once created

- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx_gateway/src/emqx_gateway_utils.erl
- apps/emqx_gateway_ocpp/src/emqx_gateway_ocpp.app.src
- apps/emqx_gateway_ocpp/src/emqx_ocpp_connection.erl
- changes/ce/feat-14047.en.md
See commit message.
Test results:
https://emqx.atlassian.net/wiki/spaces/QA/pages/1297843647/EMQX+e5.8.1+Performance+Testing#7.-Active-N
> 241009 lower default active_n from 100 to 10

- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_meta.erl
- changes/ee/fix-14057.en.md
Durable-sessions-enabled EMQX 5.7.x persists DB config that is missing `force_monotonic_timestamps` key (i.e. `append_only` DB option), but the logic incorrectly relied on it being always present, even in preexisting DBs.
> fix(dsraft): ensure DB config compat with earlier releases

- apps/emqx_bridge/include/emqx_bridge.hrl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
- apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl
- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/src/emqx_resource_metrics.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- changes/ce/feat-14065.en.md
- mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-13074
N.B.: Pulsar Producers have internal buffering, and thus they'll need to implement support for reporting such metrics separately.
> feat(buffer worker): report queued bytes as a metric

- apps/emqx/src/emqx_cm.erl
- changes/ce/fix-14061.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13324
Change the following log messages to debug level:
```
action: discard, file: emqx_cm.erl, line: 367, mfa: {emqx_cm,request_stepdown,3}, msg: session_stepdown_request_exception, pid: <70941.11186.7732>, reason: {killed,{gen_server,call,[<70941.3614.1870>,discard,5000]}}, stacktrace: [{gen_server,call,3,[{file,"gen_server.erl"},{line,247}]},{emqx_cm,request_stepdown,3,[{file,"emqx_cm.erl"},{line,342}]},{erpc,execute_call,4,[{file,"erpc.erl"},{line,392}]}], stale_channel: undefined, stale_pid: <70941.3614.1870>
```
```
action: discard, file: emqx_cm.erl, line: 360, mfa: {emqx_cm,request_stepdown,3}, msg: session_stepdown_request_exception, pid: <0.20910.1677>, reason: normal, stacktrace: …
```
> fix: improve logs for emqx_cm:request_stepdown/3

- bin/emqx
- changes/ce/breaking-14063.en.md
User now must set envvar RUN_EMQX_UNSAFE="I_AGREE" to load dynlibs in the package.
I also suggest remove the dynlib from the package. 
> dont silently load insecure dynlibs

- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_subs.erl
- apps/emqx/test/emqx_persistent_session_ds_SUITE.erl
- changes/ce/fix-14042.en.md
Fixes: #14039
Properly handle change of the subscription parameters in the durable sessions.
> fix(sessds): Fix crash resulting from subscription state update

- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_client.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_producer_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12945
> fix(gcp pubsub): massage error reason when an invalid private key is in service account json

- apps/emqx_retainer/src/emqx_retainer.erl
- changes/ce/fix-14090.en.md
fix: https://askemq.com/t/topic/9875
> fix: don't crash retainer api when retainer is disabled

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_action_info.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_schema.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl
- changes/ee/feat-14079.en.md
- changes/ee/fix-14079.en.md
- mix.exs
- rel/i18n/emqx_bridge_kafka.hocon
- rel/i18n/emqx_bridge_kafka_consumer_schema.hocon
This PR upgrades blow Kafka client libs:
brod: from 3.18.0 to 4.3.1, for consumer latency optimization, for more details, see:
https://github.com/kafka4beam/brod/blob/master/CHANGELOG.md 
kafka_protocol: from 4.1.8 to 4.1.9 for Erlang/OTP 27
snappyer: from 1.2.9 to 1.2.10 for Erlang/OTP 27
To verify Kafka consumer latency:
- Create a Kafka topic with the number of partitions greater than the number of nodes in Kafka cluster
- Create a Kafka consumer data integration, republish the message to a MQTT topic
- Start a MQTT subscriber to monitor the latency of message end-to-end latency
- Inspect the Kafka partition leaders, find two partitions which share the same Kafka broker as the partition leader
- Send messages to only one of the partitions
Expected observation: …
> chore: upgrade Kafka client libs

- apps/emqx_bridge_datalayers/test/emqx_bridge_datalayers_SUITE.erl
- apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl
- apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_SUITE.erl
- changes/ee/fix-14091.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13324
A simple fix that removes `function_clause` from the log message if the user has provided an unsupported write syntax:
```
weather,location=us-midwest,season=summer temperature=82 ${timestamp}u
```
The error log before this fix:
```
pid: <0.558392.0>, info: {"stacktrace":["{emqx_bridge_influxdb_connector,parse_timestamp,[[1719350482910000000,<<\"u\">>]],[{file,\"emqx_bridge_influxdb_connector.erl\"},{line,692}]}","{emqx_bridge_influxdb_connector,lines_to_points,4,[{file,\"emqx_bridge_influxdb_connector.erl\"},{line,678}]}","{emqx_bridge_influxdb_connector,on_query_async,4,[{file,\"emqx_bridge_influxdb_connector.erl\"},{line,173}]}","{emqx_resource_buffer_worker,apply_query_fun,9,[{file,\"emqx_resource_buffer_worke …
```
> fix(influxdb): unsupported write syntax for timestamp field

- apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_api_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds_lts.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_layout_SUITE.erl
There are a couple of advantages doing it on such a low level:
1. It's possible to avoid scanning whole streams.
2. Topic is already matched against (compressed) topic filter on the layout level anyway, so it would be wasteful to add one more step of matching and filtering on higher levels.
> fix(ds-lts): respect special topic matching rules in LTS-based layouts

- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl.erl
- apps/emqx_utils/src/emqx_utils.erl
- rel/i18n/emqx_bridge_kafka.hocon
- rel/i18n/emqx_schema.hocon
So other bridges can make use of it soon.
> Refactor: Move TCP Keepalive config schema to schema module

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_frame.erl
- apps/emqx/src/emqx_quic_data_stream.erl
- apps/emqx/src/emqx_ws_connection.erl
- changes/ce/fix-14099.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13328
1. Fix the issue that esockd prints a supervisor report on exit:
```
{"time":"2024-10-11T06:05:07.610048+00:00","level":"error","msg":"supervisor: {esockd_connection_sup,0.53591191.0}, errorContext: connection_shutdown, reason: #{cause => invalid_topic,reason => malformed_utf8_string_length}, offender: [{pid,0.53591191.0},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => #{client => #{messages => #{low_watermark => 0,initial => 0,rate => 150.0,burst => 0,max_retry_time => 3600000,failure_strategy => force,divisible => true}},connection => #{initial => 0,rate => 100.0,burst => 0}},enable_authn => true,zone => default}]}}]","domain":["supervisor_report"],"pid":"0.5121.0"," …
```
> fix: dont log supervisor_report for malformed_utf8_string_length

- apps/emqx_bridge/src/emqx_bridge_lib.erl
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- changes/ce/fix-14101.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13250
Delete action failed if a source exists with the same name.
> fix: remove action failed with name_clash_action_source

- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl
- changes/ee/breaking-14106.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13389
Currently, brod treats a consumer process to a specific topic as a singleton (per client id / connector), meaning that the first subscriber to a given topic will define the consumer options for all other consumers, and those options persist even after the original consumer group is terminated.  We enforce that, if the user wants to consume multiple times from the same topic, then they must create a different connector.
> fix(kafka consumer): ensure no repeated topics in the same connector

- apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse_connector.erl
- apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl
- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_mysql/src/emqx_mysql.app.src
- apps/emqx_mysql/src/emqx_mysql.erl
- apps/emqx_utils/src/emqx_template_sql.erl
- apps/emqx_utils/src/emqx_utils_sql.erl
- apps/emqx_utils/test/emqx_utils_sql_SUITE.erl
- changes/ee/feat-14118.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13325
Support the `on duplicate key update` clauses in the mysql integration:
```
INSERT INTO t1 (a,b,c) VALUES (1,2,3) ON DUPLICATE KEY UPDATE c=c+1;
```
**NOTE:** placeholders (${var}) cannot be used as the table name or in the `on duplicate key update` clause
> feat: support on duplicate clause in mysql

- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl
- changes/ee/fix-14120.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13402
`pulsar_client:get_status` call actually exits with `{timeout, _}` rather than raising an error.
```
2024-10-31T12:41:41.014678+00:00 [error] tag: CONNECTOR/PULSAR, msg: health_check_exception, reason: #{reason => {timeout,{gen_server,call,[<0.5877.0>,get_status,5000]}},stacktrace => [{gen_server,call,3,[{file,"gen_server.erl"},{line,419}]},{emqx_bridge_pulsar_connector,on_get_status,2,[{file,"src/emqx_bridge_pulsar_connector.erl"},{line,174}]},{emqx_resource,call_health_check,3,[{file,"src/emqx_resource.erl"},{line,550}]},{emqx_resource_manager,worker_resource_health_check,1,[{file,"src/emqx_resource_manager.erl"},{line,1149}]}],exception => exit}, resource_id: <<"connector:pulsar:a">>
```
After the fix, no such …
> fix(pulsar): correctly handle timeout during health check

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_schema.erl
- changes/ee/fix-14121.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13401
This field was accidentally added to the consumer schema because it was added to the shared, v1 field in the shared schema module.  It never worked for the consumer connector, as it uses a different library for interfacing with Kafka that does not need a topic to health check.
> fix(kafka consumer): deprecate `health_check_topic`

- apps/emqx/src/emqx_config.erl
- changes/ce/fix-14116.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13249
Looks like it was introduced by https://github.com/zmstone/emqx/commit/a03f2dd64bd2f9115d3ef0e59d35e120d7d8bae6
Before this fix, once the emqx apps were restarted (e.g., the node joined a cluster), the generated retainer's default configuration was incorrect:
```
bin/emqx remote_console
> DefaultRetainer1 = emqx_conf:get([retainer]).
> emqx_machine_boot:stop_apps(), emqx_machine_boot:ensure_apps_started().
> DefaultRetainer1 =:= emqx_conf:get([retainer]).
false
```
- …
> fix: the default values of retainer schema do not take effect

- apps/emqx_dashboard/src/emqx_dashboard_not_found.erl
Improve the log messages on API path not_found:
- Change to `notice` level;
- Minimize the fields to be printed;
- Change log-msg from `unexpected_api_access` to `api_path_not_found`
Here is a log example before this PR:
```
2024-11-04T10:57:16.984927+08:00 [warning] msg: unexpected_api_access, request: #{pid => <0.4764.0>,port => 18083,scheme => <<"http">>,version => 'HTTP/1.1',path => <<"/api/v5/abc">>,host => <<"localhost">>,peer => {{127,0,0,1},49988},sock => {{127,0,0,1},18083},bindings => #{},ref => 'http:dashboard',cert => undefined,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:18083">>,<<"user-agent">> => <<"curl/7.79.1">>},method => <<"GET">>,body_length => 0,path_info => undefined,qs => <<>>,streamid => 1,has_body => false,host_info …
```
> chore: improve the log msg when API path not_found

- rel/config/examples/dashboard-with-http.conf.example
- rel/config/examples/dashboard-with-https.conf.example
- rel/config/examples/listeners.quic.conf.example
- rel/config/examples/listeners.ssl.conf.example
- rel/config/examples/listeners.tcp.conf.example
- rel/config/examples/listeners.ws.conf.example
- rel/config/examples/listeners.wss.conf.example
Release: v/e5.8.3
`bind=0` to disable listener only applicable to dashboard listeners.
For MQTT listeners, `bind=0` will lead to a random port number, no intention to change this behavior nor document this behavior for now.
> docs: remove '0 means disable' comment from example configs

- apps/emqx/etc/vm.args.cloud
- dev
The `-pa data/patches` init args was not working due to the `cache_boot_paths` feature. See the OTP changes here https://github.com/erlang/otp/pull/6729
I'd like to disable the feature as it may causes more problems than we know. One of other solutions is to run `code:set_path("data/patches", nocache)` on emqx boot.
> The data/patches dir not work

- apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_source_worker.erl
- apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl
- changes/ee/feat-14176.en.md
includes the `queue`, `exchange`, `routing_key`
Fixes EMQX-13413
> feat(rabbitmq): expose some meta info into the rule engine for the source action

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_session_mem.erl
- apps/emqx/test/emqx_mqtt_test_client.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx_auth_http/test/emqx_authn_scram_restapi_SUITE.erl
- apps/emqx_auth_mnesia/test/emqx_authn_scram_mnesia_SUITE.erl
- apps/emqx_gateway_mqttsn/src/emqx_mqttsn_channel.erl
- apps/emqx_gateway_mqttsn/test/emqx_sn_protocol_SUITE.erl
- changes/ce/fix-14122.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-9314
Fixes https://github.com/emqx/emqx/issues/10215
> fix: handle clients replying with `PUBREC`/`PUBCOMP` / `PUBACK` when QoS is 1 / 2

- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_cluster_SUITE.erl
- changes/ce/fix-14178.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13427
As long as a rule is deleted simultaneously on different nodes, the following error will occur. What's more serious is that this will prevent the submission of emqx_cluster_rpc, leading to inconsistent configurations on one of the nodes.
```
{"time":1729062791671111,"level":"error","msg":"change_config_crashed","mfa":"emqx_config_handler:handle_update_request/5(246)","update_req":"{remove,#{override_to => cluster}}","stacktrace":["{emqx_rule_engine,post_config_update,5,[{file,\"emqx_rule_engine.erl\"},{line,165}]}","{emqx_config_handler,call_proper_post_config_update,1,[{file,\"emqx_config_handler.erl\"},{line,608}]}","{emqx_config_handler,call_post_config_update,1,[{file,\"emqx_config_handler.erl\"},{line,587}]}" …
```
> fix: 500 error caused by deleting rule IDs on different nodes at the same time

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- changes/ee/fix-14181.en.md
- mix.exs
- rebar.config
Release version: e5.8.3
- replayq from 0.3.9 to 0.3.10, v0.3.10 tolerates corrupted COMMIT file
- kafka_protocol from 4.1.9 to 4.1.10, to fix a rare timeout issue
only happens when 5s is not long enough to discover partition lader
and then connect
- wolff from 4.0.3 to 4.0.4 only to keep the versions consistent
> chore: upgrade replayq from 0.3.9 to 0.3.10

- apps/emqx_resource/src/emqx_resource_cache_cleaner.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- changes/ce/fix-14172.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13079
There's race condition where a dry run request takes too long, and the HTTP API request
process is then forcefully killed by `cowboy_children` before it has the chance to
properly cleanup and remove the dry run/probe resource.  This leaves a dry run resource
instance running that is never cleaned up.
> fix(resource manager): avoid zombie resource after HTTP API request is forcefully killed

- apps/emqx/src/emqx_channel.erl
- apps/emqx_auth/src/emqx_authz/sources/emqx_authz_client_info.erl
- apps/emqx_auth_jwt/test/emqx_authn_jwt_expire_SUITE.erl
- apps/emqx_cluster_link/test/emqx_cluster_link_SUITE.erl
- changes/ce/fix-14192.en.md
Fixes [EMQX-12708](https://emqx.atlassian.net/browse/EMQX-12708)
The problem description is quite simple:
* JWT authenticator provides both **authentication** and **authorization rules** that we put into the `clientinfo`.
* They both have the same expiration deadline (the exp of JWT).
* We schedule a disconnect timer for the connection after the successful JWT auth, so that client is kicked when its auth expires.
* We kick the client, and its will message cannot pass the authz checks because they have just expired (together with the auth).
A straightforward solution is to add some thresholds to authz expiration deadline to give the will message a chance to pass authorization. However, since the disconnection is triggered by a timer, the event may be arbitrarily …
> feat(jwt_auth): make will msg be sent in case of disconnetion on auth expire

- apps/emqx_management/src/emqx_mgmt_api_clients.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13387
Durable session missing its metadata: possibly a race condition, such as the client being kicked while the API is enumerating clients.  There's nothing much to do, we just return an empty map to avoid crashing this function.  The client may just retry listing in such cases.
> fix(clients mgmt api): handle potential race condition when formatting/fetching kicked clients

- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs.erl
- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs_agent.erl
- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs_null_agent.erl
- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_stream_scheduler.erl
- apps/emqx/src/emqx_persistent_session_ds/session_internals.hrl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub.app.src
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_agent.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_group_sm.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_proto.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_proto.hrl
- apps/emqx_ds_shared_sub/src/proto/emqx_ds_shared_sub_proto_v2.erl
- apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_SUITE.erl
Fixes
[EMQX-13472](https://emqx.atlassian.net/browse/EMQX-13472)
[EMQX-13473](https://emqx.atlassian.net/browse/EMQX-13473)
Release version: e5.8.3
The major changes are:
* The stream renewal for shared subs does not require external `renew_streams` call anymore, it is done in `on_info` callback just after the stream lease events are received from the leader. This is an internal change of the shared subs.
* The `on_replay` callback (that reports progress) is called from the two places of the DS session:
* on seqno release when the iterator span was completely consumed;
* on stream enqueue (needed only for qos0).
This change required little changes to the scheduler's interface: we need to catch moments when a stream is fully acked.
* Internal shared subs module refactoring: We eliminate …
> Consistently update progress for durable shared subscriptions

- apps/emqx/rebar.config
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_gateway/src/emqx_gateway.app.src
- apps/emqx_gateway/src/emqx_gateway_utils.erl
- apps/emqx_management/src/emqx_mgmt.erl
- changes/ce/feat-14219.en.md
- mix.exs
- rebar.config
- rel/i18n/emqx_schema.hocon
Fixes https://github.com/emqx/emqx/issues/14145
Fixes [EMQX-13498](https://emqx.atlassian.net/browse/EMQX-13498)
Enhanced connection rate limiter for improved system resilience.
Enhanced the connection rate limiter to improve system stability and responsiveness under high connection loads.
Previously, listener acceptors would ignore new connection attempts when the rate limit was exceeded,
potentially resulting in an unrecoverable state if a large number of clients connected or reconnected frequently within a short period.
Listeners now accept pending connections but immediately close them if the rate limit is reached,
reducing resource strain and increasing system resilience during peak loads.
In addition, a new listener option, `nolinger`, has been introduced. …
> 241113 upgrade to esockd 5.13.0

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_client_SUITE.erl
- apps/emqx/test/emqx_config_SUITE.erl
- changes/ce/feat-14195.en.md
- rel/i18n/emqx_schema.hocon
Fixes https://github.com/emqx/emqx/discussions/13995
This small feature should allow us to provide better multi-tenancy support before 5.9.
e.g.
```
listeners.tcp.default.mountpoint="${username}/"
mqtt.clientid_ovrride = "concat([username, '-', clientid])"
```
TODO(Enterprise only multi-tenancy features):
- `client_attrs.tns` as the conventional multi-tenancy activation attribute, when this attribute exists:
- automatic mount topic prefix
- automatic override client ID
- ClientID index from `tns` to `[clientid]`
- per-tenant client count
- per-tenant client count limit
- per-tenant message rate limit
> feat: add clientid override

- apps/emqx/src/emqx_persistent_session_ds.erl
Cleanup timer to allow it be rescheduled.
The platform has the corresponding failing tests.
> fix(sessds): cleanup renew streams timer

- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
Fixes [EMQX-12848](https://emqx.atlassian.net/browse/EMQX-12848).
Release version: e5.8.3
Before this commit, failed preconditions might have become positive on replay, e.g. when preconditionless batches later in the log made conditions trueish.
[EMQX-12848]: https://emqx.atlassian.net/browse/EMQX-12848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dsraft): always persist raftidx on batches with preconditions

- apps/emqx/src/emqx_frame.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_ws_connection_SUITE.erl
- changes/ce/fix-14223.en.md
https://askemq.com/t/topic/10040
cowboy_websocket's close reason must be an atom to avoid crashing the sender process, ensure the cause is atom
https://github.com/emqx/cowboy/blob/master/src/cowboy_websocket.erl#L639-L658
```
2024-11-13T03:28:02.055764+00:00 [error] crasher: initial call: cowboy_clear:connection_process/4, pid: <0.147756968.3>, registered_name: [], error: {{case_clause,#{invalid_property_code => 51}},[{cowboy_websocket,websocket_send_close,2,[{file,"cowboy_websocket.erl"},{line,640}]},{cowboy_websocket,websocket_close,3,[{file,"cowboy_websocket.erl"},{line,623}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, ancestors: [<0.7416.0>,<0.7415.0>,ranch_sup,<0.6954.0>], message_queue_len: 1, messages: …
```
> fix: ensure websocket close reason is atom to avoid crash

- apps/emqx_management/src/emqx_mgmt_api_status.erl
- changes/ce/feat-14254.en.md
The status API does not require authentication.
This will help dashboard to display cluster name before login.
> feat: return cluster name in /status HTTP ednpoint

- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl
- changes/ce/fix-14265.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13563
See the error log:
```
2024-11-22T13:57:14.140177+08:00 [warning] tag: CONNECTOR/MQTT, msg: remove_channel_failed, reason: #{reason => {badkey,<<"source:mqtt:source-mqtt-act:connector:mqtt:mqtt-conn">>},stacktrace => [{erlang,map_get,[<<"source:mqtt:source-mqtt-act:connector:mqtt:mqtt-conn">>,#{}],[{error_info,#{module => erl_erts_errors}}]},{emqx_bridge_mqtt_connector,on_remove_channel,3,[{file,"emqx_bridge_mqtt_connector.erl"},{line,178}]},{emqx_resource,call_remove_channel,4,[{file,"emqx_resource.erl"},{line,579}]},{emqx_resource_manager,remove_channels_in_list,3,[{file,"emqx_resource_manager.erl"},{line,948}]},{emqx_resource_manager,stop_resource,1,[{file,"emqx_resource_manager.erl"},{line,910}]},{emqx_resourc …
```
> mqtt-source-bridge-stop-error

- bin/nodetool
```bash
$ emqx eval 'emqx:get_config([logs]).'
escript: exception error: no case clause matching {error,{config_not_found,[logs]}}
in function  nodetool__escript__1732__246864__885259__2:do/1 {FILE_PATH}
in call from escript:start/1 (escript.erl, line 277)
in call from init:start_em/1 
in call from init:do_boot/3 
```
> fix: bin/nodetool eval rpc case clause

- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- apps/emqx/test/emqx_ws_connection_SUITE.erl
- changes/ce/fix-14268.en.md
Fixes [EMQX-13533](https://emqx.atlassian.net/browse/EMQX-13533).
Release version: v5.8.3 (?)
Otherwise, in exceptional situations `emit_stats` timeout may arrive earlier than `idle_timeout` and crash the connection.
Also a bug was fixed, see individual commits for details.
Followup of #14260 but for WebSocket connections.
[EMQX-13533]: https://emqx.atlassian.net/browse/EMQX-13533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(wsconn): avoid arming stats timer before CONNECT is processed

- apps/emqx_auto_subscribe/src/emqx_auto_subscribe.app.src
- apps/emqx_auto_subscribe/src/emqx_auto_subscribe.erl
- apps/emqx_auto_subscribe/test/emqx_auto_subscribe_SUITE.erl
- changes/ce/fix-14272.en.md
Fix: auto_subscribe configuration loaded via CLI shows success but fails to take effect(ADD TO HOOKS).
```
cat auto_subscribe.conf
auto_subscribe.topics = [{topic = "cmd/${clientid}/zbsend", qos = 0, rh = 0, rap = 0, nl = 0},{topic = "cmd/${clientid}/#", qos = 0,rh = 0, rap = 0, nl = 0}]
```
```
./bin/emqx ctl conf load auto_subscribe.conf
load auto_subscribe on cluster ok
```
1. Connect an MQTT client with username and client ID
2. Verify the client is automatically subscribed to the configured topics
3. Check the subscription list matches the expected topics
4. Disconnect the client cleanly
> fix: load auto_subscribe from cli failed

- apps/emqx/src/emqx_config.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_plugins/src/emqx_plugins.app.src
- apps/emqx_plugins/src/emqx_plugins.erl
- apps/emqx_utils/src/emqx_utils_calendar.erl
- changes/ce/feat-14264.en.md
- rel/i18n/emqx_conf_schema.hocon
Add a timestamp to the crash_dump file to ensure that it is not overwritten by the next crash dump.
**NOTE:** crash_dump_file is hidden configuration.
```
./bin/emqx eval "emqx_config:get([node,crash_dump_file])."
"/emqx/_build/emqx/rel/emqx/log/erl_crash.2024.11.22.08.17.24.dump"
```
```
cat data/configs/vm.2024.11.22.08.17.23.args
...
-env ERL_CRASH_DUMP_BYTES 104857600
-env ERL_CRASH_DUMP_SECONDS 30
-env ERL_CRASH_DUMP /emqx/_build/emqx/rel/emqx/log/erl_crash.2024.11.22.08.17.24.dump
...
```
> feat: add a timestamp to the crash_dump file 

- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_schema_secret.erl
- apps/emqx/src/emqx_secret_loader.erl
- apps/emqx/test/emqx_secret_tests.erl
- apps/emqx_utils/src/emqx_utils_redact.erl
- apps/emqx_utils/test/emqx_utils_redact_tests.erl
- changes/ce/fix-14267.en.md
> fix: do not redact secret value when it is file path

- apps/emqx/priv/bpapi.versions
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- apps/emqx_dashboard/src/proto/emqx_dashboard_proto_v1.erl
- apps/emqx_dashboard/src/proto/emqx_dashboard_proto_v2.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl
- changes/ce/feat-13739.en.md
- rel/i18n/emqx_dashboard_monitor_api.hocon
Feature: https://github.com/emqx/emqx/issues/10246
Need dashboard support delete /monitor API 
> feat: clear monitor data using the HTTP API

- apps/emqx/src/emqx_config.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx/test/emqx_config_SUITE.erl
- apps/emqx_conf/etc/base.hocon
- apps/emqx_conf/etc/emqx_conf.conf
- bin/emqx
- changes/ce/feat-14269.en.md
- dev
- mix.exs
- rebar.config.erl
- scripts/test/emqx-boot.bats
Added `etc/base.hocon` config file.
In this release, we introduced a new configuration file, `etc/base.hocon`, to enhance configuration management and clarity.
Previously, since emqx.conf was the only place for manually crafted configurations, and because it sits at the top-most layer
of the configuration override system, it caused some confusion.
While mutable (not read-only) configurations set in `emqx.conf` could be changed through the UI, API, or CLI and take effect immediately,
those changes would not persist after a node restart — leading to inconsistent behavior.
To address this, we’ve added etc/base.hocon as a foundational configuration layer.
The updated configuration precedence order, from top to bottom, is as follows:
1. Environment variables
2. …
> feat: add etc/base.hocon

- mix.exs
- scripts/buildx.sh
Add `--flavor` to the buildx.sh script.
> feat: add --flavor in buildx.sh

- apps/emqx_gateway_jt808/src/emqx_jt808_frame.erl
- apps/emqx_gateway_jt808/test/emqx_jt808_parser_SUITE.erl
- changes/ee/fix-14276.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13530
Before this fix:
```
{"time":"2024-11-25T05:45:47.255611+00:00","level":"error","msg":"supervisor: {esockd_connection_sup,<0.43610.0>}, errorContext: connection_crashed, reason: #{context => {invalid_ejson,{error,invalid_message}},stacktrace => [{jiffy,encode,2,[{file,\"jiffy.erl\"},{line,100}]},{emqx_utils_json,encode,1,[{file,\"emqx_utils_json.erl\"},{line,68}]},{emqx_jt808_channel,do_publish,2,[{file,\"emqx_jt808_channel.erl\"},{line,348}]},{emqx_jt808_channel,do_handle_in,2,[{file,\"emqx_jt808_channel.erl\"},{line,333}]},{emqx_gateway_conn,with_channel,3,[{file,\"emqx_gateway_conn.erl\"},{line,790}]},{emqx_gateway_conn,process_msg,2,[{file,\"emqx_gateway_conn.erl\"},{line,427}]},{emqx_gateway_conn,process_msg, …
```
> JT/T808: Fixed a json encode error

- apps/emqx/rebar.config.script
- changes/ce/feat-14283.en.md
- mix.exs
- rebar.config.erl
Various updates for QUIC transport
notable changes: 
- remote stream process is now monitored by NIF, free the stream resource earlier.
- added a few more APIs for debugging.
https://github.com/emqx/quic/compare/0.1.6...0.1.9
> feat(quic): bump to quicer 0.1.9

- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_quic_stream.erl
- changes/ce/fix-14258.en.md
Fixes:
[EMQX-13214](https://emqx.atlassian.net/browse/EMQX-13214)
[EMQX-13437](https://emqx.atlassian.net/browse/EMQX-13437)
To mitigate the loggings:
```
[warning] msg: session_stepdown_request_timeout, action: discard ...
[{status,running},{message_queue_len,1},{current_stacktrace,[{quicer,shutdown_stream,4,[{file,"quicer.erl"}
```
- kick: 1s
- others: 3s
[EMQX-13214]: https://emqx.atlassian.net/browse/EMQX-13214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-13437]: https://emqx.atlassian.net/browse/EMQX-13437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> fix: lower kick shutdown timeout

- apps/emqx_connector/test/emqx_connector_SUITE.erl
- apps/emqx_resource/src/emqx_resource_cache_cleaner.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_manager_sup.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13583
Removal is now done asynchronously by the cache cleaner. If the resource process is stuck and not responding to calls, doing the removal synchronously here would take more time than the defined timeout, possibly timing out HTTP API requests.
> fix(resource): remove dry run resources asynchronously

- .ci/docker-compose-file/toxiproxy.json
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_bridge/src/emqx_bridge.app.src
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_greptimedb/test/emqx_bridge_greptimedb_SUITE.erl
- apps/emqx_bridge_mongodb/docker-ct
- apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.app.src
- apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb_connector.erl
- apps/emqx_bridge_mongodb/test/emqx_bridge_v2_mongodb_SUITE.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_metrics.erl
- apps/emqx_utils/src/emqx_metrics_worker.erl
- apps/emqx_utils/test/emqx_metrics_worker_SUITE.erl
- changes/ce/fix-14226.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13496
If for whatever reason handling a "hot" metric such as `matched` breaks, it's likely that logs will be flooded with identical messages.
For still unknown reasons (e.g.: `emqx_metrics_worker` process might die?), metrics
might be lost for a running resource, and future attempts to bump them result in
errors.  As mitigation, we ensure such metrics are created here so that restarting
the resource or resetting its metrics can recreate them.
> fix(resource metrics): throttle resource metrics handling error message, ensure metrics when restarting or resetting metrics

- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_db_sup.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
- changes/ee/fix-14298.en.md
Fixes [EMQX-13577](https://emqx.atlassian.net/browse/EMQX-13577).
Release version: e5.8.4 (?)
Also make it slightly more robust by introducing a trivial "sentinel" process as the last of the supervisor children.
[EMQX-13577]: https://emqx.atlassian.net/browse/EMQX-13577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dsraft): tolerate transient failures when polling shards

- apps/emqx_bridge_pulsar/mix.exs
- apps/emqx_bridge_pulsar/rebar.config
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl
- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_connector_SUITE.erl
- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl
- changes/ee/feat-14110.en.md
- changes/ee/fix-14291.en.md
Port of #14110 and #14291 to e5.8.4
Release version: e5.8.4
- Add `telemetry` support to pulsar driver and action.
- Fixed handling of `Redirect` `LookupType` responses in pulsar producer driver.
> chore(pulsar): port #14110 and #14291 to e5.8.4

- apps/emqx_bridge_http/src/emqx_bridge_http.app.src
- apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
- changes/ce/fix-14318.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13608
Due to incorrect state initialization, a function clause that was supposed to match incoming messages fails, and later, after the message is transformed according to the wrong clauses, it leads to a cryptic function_clause error.
Adding more context:
```
2024-12-02T16:49:15.039945+00:00 [warning] msg: retrying_inflight_sync, where: {emqx_resource_buffer_worker,482,'emqx@127.0.0.1',<0.5531.0>}, query: {query,{fun emqx_rule_runtime:inc_action_metrics/2,[#{action_id => {bridge_v2,http,a},rule_id => <<"rule_zqm3">>}],#{reply_dropped => true}},{<<"action:http:a:connector:http:a">>,#{flags => #{dup => false,retain => false},id => <<"0006284C5426FF2AF4450000175B0169">>,node => 'emqx@127.0.0.1',timestamp => …
```
> fix(http action): correctly initialize resource state

- .github/workflows/bump-dashboard-version.yaml
With this change CI checks will start automatically as soon as PR is created.
> ci: use GitHub App token to create dashboard version bump PRs

- scripts/rel/macos-sign-binaries.sh
Fixes an issue with notarization of macOS packages.
> ci: sign libquicer_nif.dylib for macOS

- apps/emqx_management/src/emqx_mgmt_api.erl
- changes/ce/fix-14317.en.md
Release version: v5.8.4 (?)
This will make paging accumulation work in more general cases (as shown by the proptest). Before this commit, feeding node-query results containing more than `Limit` number of rows produced incorrect results. However, there is no evidence this incorrect codepath was ever active.
> fix(mgmt): drop incorrect but inactive clause in paging accumulation

- .github/workflows/_push-entrypoint.yaml
- .github/workflows/performance_test.yaml
- .github/workflows/release.yaml
- .github/workflows/rerun-apps-version-check.yaml
1. Fix some issues in perf test workflow, and detach it from push entrypoint, so that it does not fail when performance test fails
2. Move rerun-apps-version-check to a separate workflow so that it does not fail release workflow.
> detach perf test and rerun apps version check workflows

- apps/emqx/src/emqx_reason_codes.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_SUITE.erl
- changes/ce/feat-14341.en.md
This will allow multi-tenancy feature to support per-namespace session count limit.
Multi-tenancy session count limit cannot be done before client-attributes are initialized, hence cannot do it in the `client.connect` hook callback like license checks.
~~- [ ] Added property-based tests for code which performs user input validation~~
~~- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket~~
~~- [ ] Schema changes are backward compatible~~
> feat: support authentication hook callback to check connection quota

- apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.app.src
- apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_durable_storage/src/emqx_ds.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_layout_SUITE.erl
Followup to #14064.
Release version: v5.9 (?)
Storage layout `create/6` callback now accepts a small subset of DB-wide options (namely, `append_only` and `atomic_batches`). Those options should help storage layout to choose safe defaults for parameters. For example, skipstream-lts layout uses them to pick non-zero `master_hash_bytes` by default in non-append-only contexts.
> feat(ds): choose safe storage layout defaults in non-append-only DBs

- rebar.config.erl
This adds retries for when coveralls returns 520, as it sometimes does.
> chore: bump coveralls-erl

- bin/emqx
- changes/ce/fix-14357.en.md
- scripts/pkg-tests.sh
Fixes [EMQX-13611](https://emqx.atlassian.net/browse/EMQX-13611)
Define `usage` function before called.
Also change to use `$0` in help prints instead of relying on the variable `$REL_NAME`.
See individual commit diffs for clarity.
[EMQX-13611]: https://emqx.atlassian.net/browse/EMQX-13611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 241206 fix emqx usage print

- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
- apps/emqx_prometheus/src/emqx_prometheus_cluster.erl
- apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl
- apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl
- changes/ce/breaking-14360.en.md
- changes/ce/feat-14360.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13170
<details>
<summary> Sample output in Prometheus format: </summary>
```
ͳ curl -s http://127.0.0.1:18083/api/v5/prometheus/stats\?mode\=node  | rg emqx_client_disconnected_reason
\# TYPE emqx_client_disconnected_reason counter
\# HELP emqx_client_disconnected_reason
emqx_client_disconnected_reason{listener_type="tcp",listener_name="default",reason="kicked"} 1
emqx_client_disconnected_reason{listener_type="tcp",listener_name="default",reason="takenover"} 1
ͳ curl -s http://127.0.0.1:18083/api/v5/prometheus/stats\?mode\=all_nodes_unaggregated  | rg emqx_client_disconnected_reason
\# TYPE emqx_client_disconnected_reason counter
\# HELP emqx_client_disconnected_reason …
```
> feat(prometheus): add listener shutdown counts by reason

- apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl
- apps/emqx_utils/src/emqx_variform.erl
- apps/emqx_utils/test/emqx_variform_tests.erl
- changes/ce/fix-14371.en.md
Fixes [EMQX-13540](https://emqx.atlassian.net/browse/EMQX-13540)
when variable is bound but bound as 'undefined' or 'null', it is now rendered as empty string, but not "undefined" or "null"
[EMQX-13540]: https://emqx.atlassian.net/browse/EMQX-13540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variform): intermediate variable reference to undefined or null

- apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src
- apps/emqx_opentelemetry/src/emqx_otel_trace.erl
Override the `message.qos` attribute when msg delivered.
The real QoS might different from the raw message's. 
QoS upgrade: enabled `mqtt.upgrade_qos`
QoS downgrade: client subscribed lower qos than message's
> fix(otel): override sub qos upgrade/downgrade

- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_conf_schema_tests.erl
- changes/ce/fix-14376.en.md
Fixes [EMQX-13652](https://emqx.atlassian.net/browse/EMQX-13652)
[EMQX-13652]: https://emqx.atlassian.net/browse/EMQX-13652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(config): force convert non-existing log dir path to default

- apps/emqx/test/emqx_crl_cache_SUITE.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl
- scripts/ct/run.sh
```
=== === Reason: {assertException,
[{unexpected_exception,
{error,connack_timeout,
[{emqx_listeners_SUITE,emqtt_connect,
[#{ssl => true,
hosts => [{"127.0.0.1",32857}],
connect_timeout => 1,
ssl_opts =>
[{cacertfile,
"/__w/emqx-platform/emqx-platform/apps/emqx/_build/standalone_test+test/logs/ct_run.test@127.0.0.1.2024-12-11_13.52.31/lib.emqx.emqx_listeners_SUITE.logs/run.2024-12-11_13.54.19/log_private/ca-next.pem"},
{verify,verify_peer},
{customize_hostname_check,
[{match_fun,
#Fun<emqx_listeners_SUITE.10.13838054>}]}]}],
```
Also, there's a bug in `cth_readable 1.5.1` in `cth_readable_helpers`:
```
Call to CTH failed: error:{{badmatch,
["[","{","error",[],"{","ssl_error",[],
"_Socket",[],"{","tls_alert",[],"{",
"certificate_required",[],"_","}","}","}","}", …
```
> test: fix flaky tests

- apps/emqx_durable_storage/src/emqx_ds_msg_serializer.erl
- apps/emqx_durable_storage/src/emqx_durable_storage.app.src
During deserialization, the `properties` key may be still missing from the headers.
Ex:
```
Error: -11T13:57:04.835972+00:00 [error] Generic server <0.460010.0> terminating. Reason: {{badkey,properties},[{maps,update_with,[properties,#Fun<emqx_ds_msg_serializer.6.27087686>,#{}],[{file,"maps.erl"},{line,283}]},{emqx_ds_msg_serializer,'-asn1_deserialize_misc/2-fun-2-',2,[{file,"/emqx/apps/emqx_durable_storage/src/emqx_ds_msg_serializer.erl"},{line,369}]},{lists,foldl,3,[{file,"lists.erl"},{line,1594}]},{emqx_ds_fdb_layout_skipstream_v1,'-scan_stream/6-fun-0-',2,[{file,"/emqx/apps/emqx_ds_fdb_backend/src/emqx_ds_fdb_layout_skipstream_v1.erl"},{line,282}]},{lists,map,2,[{file,"lists.erl"},{line,1559}]},{emqx_ds_fdb_layout_skipstream_v1,scan_stream,6,[{file,"/emqx/apps/emqx_ds_fdb_backend/src/e …
```
> fix(ds msg serializer): handle missing properties when deserializing

- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_schema_tests.erl
- changes/ce/fix-14405.en.md
- rel/i18n/emqx_bridge_http_schema.hocon
Fixes #14400
For 4-bytes var-length integer, the maximum value is
`127 + (127 x 128) + (127 x 128^2) + (127 x 128^3) = 268,435,455`
> 241212 max packet size in valid range

- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver.app.src
- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- apps/emqx_utils/src/emqx_placeholder.erl
- apps/emqx_utils/src/emqx_utils_sql.erl
- apps/emqx_utils/test/emqx_placeholder_SUITE.erl
- changes/feat-14409.en.md
Fixes [EMQX-13661](https://emqx.atlassian.net/browse/EMQX-13661)
[EMQX-13661]: https://emqx.atlassian.net/browse/EMQX-13661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: rule func `str_utf16_le/1` and `sqlserver_bin2hexstr/1`

- apps/emqx_dashboard/src/emqx_dashboard_admin.erl
- apps/emqx_dashboard/test/emqx_dashboard_admin_SUITE.erl
Fixes EMQX-13506
This should have been committed in [the previous PR](https://github.com/emqx/emqx/pull/14255), but forgotten.
> fix(dashboard): update the timestamp when the password is updated

- apps/emqx_plugins/src/emqx_plugins.app.src
- apps/emqx_plugins/src/emqx_plugins_cli.erl
- apps/emqx_plugins/test/emqx_plugins_SUITE.erl
Before:
```
./bin/emqx ctl plugins list
{
}
```
After:
```
./bin/emqx ctl plugins list
[]
```
> fix(cli): plugins list cli should return empty plugins as [] not {}

- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_router_helper.erl
- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx/test/emqx_router_helper_SUITE.erl
- changes/ce/fix-14248.en.md
Fixes [EMQX-11852](https://emqx.atlassian.net/browse/EMQX-11852).
Release version: v5.8.4
Tolerate transient connectivity issues. It's now assumed that receiving a `{node, down, ...}` event does not mean that the node in question is dead, but that it has experienced connectivity loss.
Now, the router helper:
* Cleans any leftover routes from previous incarnations upon restart.
* Consequently, expects cluster nodes to clean up themselves upon restart.
* Cleans routes of a cluster node that decided to leave upon receiving such event.
* Cleans routes of cluster nodes that are down for more than 1 hour.
Notable consequences of these changes are:
* Global routing table will hold offline nodes' entries for a while, instead of cleaning them up as soon as node is considered offline.
* Node …
> feat(router): require node to cleanup routes on restart

- apps/emqx_bridge_iotdb/mix.exs
This affects only the new mix build.  No changes for any released version.
> fix(new mix build): update iotdb driver version

- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- apps/emqx_utils/src/emqx_utils_conv.erl
- changes/fix-14423.en.md
> fix: str_utf8/1 and str_utf16_le/1 should only convert str as binary

- apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl
Ex:
```
%%% emqx_bridge_sqlserver_SUITE ==> async.without_batch.init_per_group: FAILED
%%% emqx_bridge_sqlserver_SUITE ==> timeout
Error: -18T18:57:34.508735+00:00 [error] Generic server <0.411239.0> terminating. Reason: {stopped,{'EXIT',<0.410524.0>,{#Ref<0.4002057353.419692545.65779>,5044239,{'EXIT',timeout},[{odbc,call,1030},{emqx_bridge_sqlserver_SUITE,connect_and_create_db_and_table,642},{emqx_bridge_sqlserver_SUITE,common_init,464},{test_server,ts_tc,1793},{test_server,run_test_case_eval1,1390},{test_server,run_test_case_eval,1234}],[]}}}. Last message: {'DOWN',#Ref<0.4002057353.419168258.187269>,process,<0.410524.0>,{#Ref<0.4002057353.419692545.65779>,5044239,{'EXIT',timeout},[{odbc,call,1030},{emqx_bridge_sqlserver_SUITE,connect_and_create_db_and_table,642},{emqx_bridge_sqlserver_S …
```
> test(sqlserver): fix flaky test

- apps/emqx/src/emqx_schema.erl
- apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl
- apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
- apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl
Fixes EMQX-13531
1. Enhances error reporting
2. Handling `Device ID` or `Timestamp` exceptions
3. Validate the data template  at setup time, it can no longer be empty
prior this fix, this is a soft limit and just warning at runtime, but it is not a good way, users may try to do everything they can, and confuse with the result
> fix(iotdb): Enhanced error handling for invalid data

- apps/emqx_gateway_jt808/src/emqx_gateway_jt808.app.src
- apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl
- apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl
- changes/ee/fix-14445.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13602
Before this fix, the connection process will be crashed once it received an invalid message
```
2024-12-02T07:19:12.404064+00:00 [error] crasher: initial call: emqx_gateway_conn:init/6, pid: <0.82884.0>, registered_name: [], exit: {#{context => function_clause,stacktrace => [{emqx_jt808_channel,msgid,[#{<<"msg">> => <<"hello">>}],[{file,"emqx_jt808_channel.erl"},{line,846}]},{emqx_jt808_channel,'-msgs2frame/2-fun-0-',2,[{file,"emqx_jt808_channel.erl"},{line,401}]},{lists,filtermap_1,2,[{file,"lists.erl"},{line,1661}]},{emqx_jt808_channel,handle_deliver,2,[{file,"emqx_jt808_channel.erl"},{line,380}]},{emqx_gateway_conn,with_channel,3,[{file,"emqx_gateway_conn.erl"},{line,772}]},{emqx_gateway_conn,process_msg,2,[{fi …
```
> fix(jt808): avoid funcation_clause error

- apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse_connector.erl
- apps/emqx_bridge_clickhouse/test/emqx_bridge_clickhouse_SUITE.erl
Even though sql templates ending with `;` may sometimes fail to work. they should be bug-to-bug compatible.
Fixes [EMQX-13521](https://emqx.atlassian.net/browse/EMQX-13521)
- ~[ ] Change log has been added to `changes/` dir …
> fix: sql split re

- apps/emqx_bridge_tablestore/mix.exs
- mix.exs
```
===> Analyzing applications...
===> Compiling ots_erl
Unchecked dependencies for environment emqx-enterprise-test:
* tablestore (https://github.com/emqx/ots_erl.git - 0.2.2)
could not find an app file at "_build/emqx-enterprise-test/lib/tablestore/ebin/tablestore.app". Another app file was found in the same directory "_build/emqx-enterprise-test/lib/tablestore/ebin/ots_erl.app", try changing the dependency name to :ots_erl
** (Mix) Can't continue due to errors on dependencies
```
> fix(mix): use correct dependency application name

- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_purge_SUITE.erl
- apps/emqx_retainer/include/emqx_retainer.hrl
- apps/emqx_retainer/src/emqx_retainer.app.src
- apps/emqx_retainer/src/emqx_retainer.erl
- apps/emqx_retainer/src/emqx_retainer_app.erl
- apps/emqx_retainer/src/emqx_retainer_dispatcher.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/src/emqx_retainer_publisher.erl
- apps/emqx_retainer/src/emqx_retainer_schema.erl
- apps/emqx_retainer/src/emqx_retainer_sup.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- apps/emqx_telemetry/test/emqx_telemetry_SUITE.erl
- changes/ce/feat-14454.en.md
- rel/i18n/emqx_retainer_schema.hocon
Fixes [EMQX-13690](https://emqx.atlassian.net/browse/EMQX-13690)
In this PR, we just add a limiter dropping write operations if the limits are exceeded.
We also
* Remove some unnecessary code.
* Use the backend state (`Context`) in a more orderly manner. Previously,
* it was set and used from two different places (hook arguments and management gen_server state).
* its lifetime was not strictly respected: e.g., the dispatcher pool could still use `Context` even after it was closed.
[EMQX-13690]: …
> feat(retainer): add rate limiter for publishing retained messages

- apps/emqx_bridge/src/emqx_bridge.app.src
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/include/emqx_resource_buffer_worker_internal.hrl
- apps/emqx_resource/include/emqx_resource_runtime.hrl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/src/emqx_resource_cache.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
Part of https://emqx.atlassian.net/browse/EMQX-12966
These are several internal refactoring that will be used for implementing Action Fallbacks.
The changes herein do not affect the current behavior of bridges.
This PR targets `release-58`, since this is an internal refactoring and doesn't affect behavior, to minimize divergence between branches.
- [na] ~~Added tests for the changes~~ internal refactoring only.
- [na] ~~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~
> refactor: prepare for action fallbacks (r58)

- apps/emqx/include/emqx_cm.hrl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_cm_SUITE.erl
- apps/emqx_eviction_agent/src/emqx_eviction_agent.app.src
- apps/emqx_eviction_agent/src/emqx_eviction_agent.erl
Client ID as key was never needed in the `CHAN_CONN_TAB` table.
It is now stored in the table as a value field (for use in the next PR).
- [~] Added property-based tests for code which performs user input validation
This does not impact user experience. Will add a changelog in the next PR.
> 250109 refactor emqx_cm connection module register with pid

- deploy/docker/Dockerfile
Add cURL back to the docker image.
NOTE: adding 5MB to the image size.
> feat: add cURL to docker image

- .github/workflows/run_helm_tests.yaml
The exact reason is not yet fully understood, but adding this flag may help reduce the
need to repeat this workflow.
> ci: attempt to reduce flakiness

- apps/emqx/src/emqx_broker_helper.erl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/test/emqx_broker_SUITE.erl
- apps/emqx/test/emqx_broker_helper_SUITE.erl
- apps/emqx/test/emqx_cm_registry_keeper_SUITE.erl
- apps/emqx_auth_ext/README.md
- changes/ce/fix-14508.en.md
Fixes #14482
Prior to this change, `emqx_utils:drain_down(?BATCH_SIZE)` might repeatedly scan process mailbox to drain the `DOWN` messages in `emqx_broker_helper` and `emqx_cm`.
This PR changes the receive loop to always collect the head of the first `BATCH_SIZE` messages in the mailbox including both register requests and `DOWN` messages.
Also, `BATCH_SIZE` is change from `100,000` to `1000` for smaller term collection.
> Perf: emqx_cm and emqx_broker_helper 

- apps/emqx/rebar.config
- changes/ce/fix-14536.en.md
- mix.exs
- rebar.config
Fixes [EMQX-13588](https://emqx.atlassian.net/browse/EMQX-13588).
Includes emqx/mria#184.
Makes global lock guarding `mria:join/1` operations stricter. Otherwise, concurrent joins can ruin each other's lives and make any further cluster operations impossible. This can happen, for example, when a concurrent join stops the entire `mnesia` system while another join is running schema transactions.
[EMQX-13588]: https://emqx.atlassian.net/browse/EMQX-13588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: bump `ekka` to 0.19.8

- .ci/docker-compose-file/docker-compose-kdc.yaml
- .ci/docker-compose-file/docker-compose.yaml
- .github/workflows/build_packages.yaml
- .tool-versions
- changes/ce/fix-14548.en.md
- deploy/docker/Dockerfile
- env.sh
- scripts/buildx.sh
Fixes [EMQX-12290](https://emqx.atlassian.net/browse/EMQX-12290)
Fix OTP for the crash like below:
> ** FATAL ** Failed to merge schema: {aborted,function_clause}
See also: https://github.com/emqx/otp/pull/66
[EMQX-12290]: https://emqx.atlassian.net/browse/EMQX-12290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: OTP from 26.2.5.2-1 to 26.2.5.2-3

- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_ingress.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_subscriber_SUITE.erl
- changes/ce/fix-14555.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13827
Previously, there was a mismatch in the treatment given to the topic that was inserted in the topic index and the one being unsubscribed from, leaving dangling shared subscriptions in the index.
> fix(mqtt source): unsubscribe shared topics

- apps/emqx/src/emqx_access_control.erl
- apps/emqx/test/emqx_access_control_SUITE.erl
- apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_chains_SUITE.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_init_SUITE.erl
- changes/ce/fix-14556.en.md
Fixes [EMQX-13816](https://emqx.atlassian.net/issues/EMQX-13816)
Currently, we have quite a fragile authentication convention. If there are no hooks (or if all hooks fail), we allow (anonymous) authentication. This is convenient for using the `emqx` app without a release, e.g., in tests. But this leads to actual and potential security issues. If, for some reason, `emqx_auth`'s hook fails or is absent (`emqx_auth` app starts, stops, crashes, etc.), then we allow everyone to connect. This proved to happen in practice on a slow node (see the related task).
We change the convention and logic:
* if, for a listener, `enable_authn` is not `false` (default is true), than we **deny authentication if no hooks are installed** or no hooks handled the authentication (e.g. …
> feat(authn): do not allow authentication if auth enabled but no hooks handled auth

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl
- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- changes/ee/fix-14563.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13828
> fix(rule metrics): increase `failed` rule metric when internal buffer actions drop messages

- apps/emqx_bridge_s3/src/emqx_bridge_s3.app.src
- apps/emqx_bridge_s3/src/emqx_bridge_s3_connector.erl
- changes/ee/fix-14567.en.md
`emqx_s3_client_http` now uses `hackney`.
> fix(s3 connector): stop hackney pool

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
- changes/ee/feat-14572.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13789
> chore(kafka producer): change default of `memory_overload_protection` to `true`

- apps/emqx/rebar.config.script
- apps/emqx/src/emqx_schema.erl
- changes/ce/feat-14583.en.md
- mix.exs
- rebar.config.erl
- rel/i18n/emqx_schema.hocon
QUIC listener now supports SSLKEYLOGFILE for traffic decryption. 
Fixes [EMQX-13833](https://emqx.atlassian.net/browse/EMQX-13833)
[EMQX-13833]: https://emqx.atlassian.net/browse/EMQX-13833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(quic): bump quicer-0.1.11 and support SSLKEYLOGFILE

- rel/i18n/emqx_bridge_azure_event_hub.hocon
- rel/i18n/emqx_bridge_confluent_producer.hocon
- rel/i18n/emqx_bridge_kafka.hocon
- rel/i18n/emqx_bridge_pulsar.hocon
The config `sysmon.os.sysmem_high_watermark` is only relevant for alarms but not to Kafka/Pulsar producers
> docs: fix config doc for Kafka/Pulsar producer high mem threshold

- rebar.config.erl
... To retry any 5xx error.
See https://github.com/emqx/coveralls-erl/pull/6
> ci: bump `coveralls-erl` -> v2.2.0-emqx-5

- apps/emqx/test/emqx_cth_cluster.erl
- apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_data_backup_SUITE.erl
```
Testing lib.emqx_management.emqx_mgmt_api_data_backup_SUITE: *** SKIPPED test case 7 of 11 ***
...
%%% emqx_mgmt_api_data_backup_SUITE ==> t_import_ce_backup: SKIPPED
%%% emqx_mgmt_api_data_backup_SUITE ==> {tc_auto_skip,
{failed,
{emqx_mgmt_api_data_backup_SUITE,init_per_testcase,
{timeout,
[{emqx_utils,nolink_apply,2,
[{file,"/emqx/apps/emqx_utils/src/emqx_utils.erl"},
{line,534}]},
{emqx_cth_cluster,perform,2,
[{file,"/emqx/apps/emqx/test/emqx_cth_cluster.erl"},
{line,133}]},
{emqx_mgmt_api_data_backup_SUITE,do_init_per_testcase,2,
[{file,
"/emqx/apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl"},
{line,168}]},
{test_server,do_init_per_testcase,2,
[{file,"test_server.erl"},{line,1563}]},
{test_server,run_test_case_eval1,6,
[{file,"test_server.erl"},{line,1264}]}, …
```
> test: attempt to fix flaky test

- apps/emqx_message_transformation/src/emqx_message_transformation_registry.erl
- apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl
- apps/emqx_schema_validation/src/emqx_schema_validation_registry.erl
- apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl
- changes/ee/fix-14622.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13859
Fixes bug introduced by https://github.com/emqx/emqx/pull/13199/commits/5629fe60c12d0d7e94f3e95a6c05ee8b6a99ad55
> fix(message transformation & schema validation): use correct order when finding matches

- apps/emqx/src/emqx_passwd.erl
- apps/emqx/test/emqx_passwd_SUITE.erl
- apps/emqx_auth/src/emqx_authn/emqx_authn_password_hashing.erl
- changes/ce/fix-14585.en.md
Port of #14585.
Release version: v5.8.5.
> fix(emqx): ignore case in hexadecimal password hash comparisons

- .github/actions/package-macos/action.yaml
- Makefile
- changes/ce/fix-14624.en.md
- env.sh
Fixes [EMQX-13740](https://emqx.atlassian.net/browse/EMQX-13740)
[EMQX-13740]: https://emqx.atlassian.net/browse/EMQX-13740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci(macOS): quicer disable dynamic link libcrypto

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.erl
- changes/ee/feat-14626.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13852
> chore: lower default per-partition buffer limit to 256 MB for Kafka/Pulsar actions

- apps/emqx/src/emqx_alarm.erl
- apps/emqx/src/emqx_hookpoints.erl
- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_events_SUITE.erl
- changes/ce/feat-14627.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13636
With this new event, it's possible for rules to be triggered by alarm toggling without the
need to set `rule_engine.ignore_sys_message = false` and using the existing
`$SYS/broker/+/alarms/+` topic filter.  Using this new event, the frontend may implement
an UX for tying webhooks to alarms.
> feat(rule engine): add `$events/alarm_{,de}activated`

- .ci/docker-compose-file/docker-compose-confluent-schema-registry.yaml
```
Error response from daemon: repository public.ecr.aws/ews-network/confluentinc/cp-schema-registry not found: name unknown: The repository with name 'confluentinc/cp-schema-registry' does not exist in the registry with id 'ews-network'
```
> ci: fix schema registry image that is gone

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- changes/ee/fix-14631.en.md
- mix.exs
- rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-13830
See also https://github.com/emqx/replayq/pull/20
- [na] ~~Added tests for the changes~~ only updated dependencies
> fix(kafka producer): drop data more aggresively when under high memory stress

- .ci/docker-compose-file/docker-compose-confluent-schema-registry.yaml
- apps/emqx/include/emqx_quic.hrl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_quic_stream.erl
- apps/emqx/src/emqx_types.erl
- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- changes/ce/perf-14597.en.md
Fixes [EMQX-13843](https://emqx.atlassian.net/browse/EMQX-13843)
[EMQX-13843]: https://emqx.atlassian.net/browse/EMQX-13843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> perf(quic): async abort read for takenover, discarded and kicked sess

- apps/emqx_gateway_stomp/src/emqx_stomp_heartbeat.erl
- apps/emqx_gateway_stomp/test/emqx_stomp_heartbeat_SUITE.erl
- changes/ce/fix-14653.en.md
Fixes https://github.com/emqx/emqx/issues/12911
prior to this fix, stomp connection heatbeat cannot keep the connection alive if the heartbeat packet is received slightly later than the check timer.
this commit makes it to tolerate some delay, on average one can expect the connection close to happen around 1.5x heartbeat interval
> fix(stomp): fix heartbeat reset

- apps/emqx_license/src/emqx_license.erl
- apps/emqx_license/test/emqx_license_SUITE.erl
- changes/ee/fix-14654.en.md
Fixes [EMQX-13705](https://emqx.atlassian.net/browse/EMQX-13705)
Allow clients to reconnect even if max_connection (session) limit is reached.
This can happen when a system is close to the license limit and large number of client reconnect concurrently.
[EMQX-13705]: https://emqx.atlassian.net/browse/EMQX-13705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(license): allow clients to reconnect even if max_clients reached

- mix.exs
- rebar.config
https://github.com/emqx/ehttpc/pull/62
https://github.com/zhongwencool/observer_cli/releases/tag/v1.8.2
> chore: bump ehttpc to 0.7.1 and observer_cli to 1.8.2

- apps/emqx/src/emqx_schema.erl
Fixes [EMQX-13874](https://emqx.atlassian.net/browse/EMQX-13874)
Dashboard does not like integer format for this config.
this is a follow up fix for PR https://github.com/emqx/emqx/pull/14405
[EMQX-13874]: https://emqx.atlassian.net/browse/EMQX-13874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 250207 fix mqtt.max_packet_size display

- apps/emqx_license/src/emqx_license_checker.erl
- apps/emqx_license/src/emqx_license_cli.erl
- apps/emqx_license/src/emqx_license_http_api.erl
- apps/emqx_license/test/emqx_license_checker_SUITE.erl
- apps/emqx_license/test/emqx_license_cli_SUITE.erl
- apps/emqx_license/test/emqx_license_http_api_SUITE.erl
Fixes [EMQX-13549](https://emqx.atlassian.net/browse/EMQX-13549)
A follow up for https://github.com/emqx/emqx/pull/14568.
This is a temporary fix for 5.8.5, a proper fix to change max_connections to max_sessions in all places will need some compatibility code for APIs which is more suitable for version 5.9
[EMQX-13549]: https://emqx.atlassian.net/browse/EMQX-13549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: max_connections -> max_sessions in licnse info ctl command output

- apps/emqx/src/bpapi/emqx_bpapi.erl
- apps/emqx/src/bpapi/emqx_bpapi.hrl
- apps/emqx/src/emqx_bpapi_replicant_checker.erl
- apps/emqx/src/emqx_kernel_sup.erl
- apps/emqx/test/emqx_bpapi_SUITE.erl
- changes/ce/fix-14662.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13879
1) Initially start a core node, and then a replicant that has that core as seed. 2) Wait until the replicant is fully started and functional.  At this point,
emqx_bpapi:supported_version works fine.
3) Stop the core node and wait until the replicant notices that.  The API still works at
this point.
4) Start a fresh core node with no record of the replicant and wait until the replicant
reconnects.  At this point, BPAPI for the replicant is broken.
> fix: reannounce BPAPIs when replicant join fresh core

- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- changes/ce/fix-14674.en.md
- elvis.config
Fixes EMQX-13851
Release version: v/e5.9
Prevent the RocksDB logs from growing out of control.
> fix(ds): Limit number and size of RocksDB info log files

- changes/ce/feat-13350.md
- changes/ce/feat-13862.md
- changes/ce/fix-12902.md
- changes/ce/fix-12976.md
- changes/e5.6.0.en.md
- changes/e5.7.0.en.md
- changes/e5.8.0.en.md
- changes/ee/feat-12417.md
- changes/ee/feat-13650.md
- changes/ee/feat-14034.md
- changes/ee/fix-12892.md
- changes/ee/fix-13755.md
- changes/ee/fix-13881.md
- changes/ee/fix-13964.md
- changes/ee/fix-14045.md
- changes/ee/fix-14149.md
- changes/ee/fix-14294.md
- changes/v5.6.0.en.md
- changes/v5.7.0.en.md
- changes/v5.8.2.en.md
A few changelog files were named wrong.
Add them to the compiled release notes and delete the original file.
> 250211 add missing changelogs

- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13915
Also improves error messages when it fails to find the event type.
- [na] ~~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~ new, unreleased feature
> fix(rule engine api): add missing schema for `alarm.{,de}activated`

- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13913
Previous value was being taken from `resource_data`, which actually corresponds to the connector state (enabled/disabled).
> fix(actions/sources api): use correct `enable` field to denote action/source state

- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_schema_tests.erl
- changes/ce/breaking-14703.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13901
See linked tickets and its comments for more context.
- [na] Schema changes are backward compatible: no, but it's unlikely anyone set this to more than 129 GB.
> fix: limit maximum allowed heap size

- apps/emqx_conf/etc/base.hocon
Fixes [EMQX-13749](https://emqx.atlassian.net/browse/EMQX-13749)
Otherwise the config may mask environment variable overrides when using alias.
e.g. `env EMQX_LOG__CONSOLE_HANDLER__LEVEL="info"` will not take effect because if a config value is found, it will not try to read alias.
`env EMQX_LOG__CONSOLE__LEVEL="info"` works fine even without this fix though.
[EMQX-13749]: https://emqx.atlassian.net/browse/EMQX-13749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(config): do not set default values in base.hocon

- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_egress.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl
- changes/ce/fix-14671.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13880
> fix(mqtt action): make `tcp_closed` and `closed` recoverable errors

- apps/emqx/src/emqx_frame.erl
- apps/emqx/test/emqx_frame_SUITE.erl
- changes/ce/fix-14707.en.md
Fixes [EMQX-13927](https://emqx.atlassian.net/browse/EMQX-13927)
Fixes #14688
[EMQX-13927]: https://emqx.atlassian.net/browse/EMQX-13927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> fix: qos2 PUBLISH packet should allow DUP=1

- apps/emqx_auth/src/emqx_authz/emqx_authz_source.erl
- apps/emqx_auth/src/emqx_authz/sources/emqx_authz_client_info.erl
- apps/emqx_auth/src/emqx_authz/sources/emqx_authz_file.erl
- apps/emqx_auth_http/src/emqx_authz_http.erl
- apps/emqx_auth_ldap/src/emqx_auth_ldap.app.src
- apps/emqx_auth_ldap/src/emqx_authz_ldap.erl
- apps/emqx_auth_ldap/src/emqx_authz_ldap_schema.erl
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src
- apps/emqx_auth_mnesia/src/emqx_authz_mnesia.erl
- apps/emqx_auth_mongodb/src/emqx_authz_mongodb.erl
- apps/emqx_auth_mysql/src/emqx_auth_mysql.app.src
- apps/emqx_auth_mysql/src/emqx_authz_mysql.erl
- apps/emqx_auth_postgresql/src/emqx_auth_postgresql.app.src
- apps/emqx_auth_postgresql/src/emqx_authz_postgresql.erl
- apps/emqx_auth_redis/src/emqx_auth_redis.app.src
- apps/emqx_auth_redis/src/emqx_authz_redis.erl
- rel/i18n/emqx_authz_ldap_schema.hocon
Release: v/e5.8.5
In anther task, I noticed that LDAP authz schema had a `desc` field provided by a callback, this made i18n complicated.
Then I realize that this callback is never called anywhere else, so I decided to remove it.
> refactor: delete unused callback from authz source behaviour

- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft.app.src
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_shard.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_ds.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_utils/src/emqx_utils.app.src
- apps/emqx_utils/src/emqx_utils_fmt.erl
- apps/emqx_utils/test/emqx_utils_fmt_tests.erl
- changes/ee/fix-14696.en.md
Part of [EMQX-13886](https://emqx.atlassian.net/browse/EMQX-13886).
This PR primarily addresses 2 shortcomings in DS Raft backend.
1. Shard membership changes now proceed in rare situations when the current shard replica set is comprised only of replicas located on "lost" sites, which correspond to the nodes that previously left the cluster. More complex disaster scenarios, for example where only majority of the replicas are "lost" but not all, will be addressed in followup PRs.
2. The _Forget site_ operation now includes additional safeguards and will fail if the site is part of active shard replica sets or if corresponding node remains in the cluster. This should guarantee that any unfinished transitions will have enough information to operate on Ra clusters.
See …
> fix(dsraft): avoid contacting lost servers during membership changes

- apps/emqx/rebar.config.script
- apps/emqx/src/emqx_quic_connection.erl
- changes/ce/feat-14431.en.md
- mix.exs
- rebar.config.erl
I have done my testing of quicer 0.2 branch. It is safe to bump it for EMQX 5.9 now.
Release version: v/e5.9
> feat: quicer 0.2.3

- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_schema_tests.erl
Fixes (again) https://emqx.atlassian.net/browse/EMQX-13901
> docs: return bytesize in max_heap validation error message

- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13937
Sometimes a `normal` error reason is returned by `ehttpc` when the HTTP connection times out before the request has been fully processed.
> fix(gcp pubsub action): retry `normal` error reasons

- apps/emqx_bridge/src/emqx_bridge_v2.erl
For some reason, CI passed just fine in the originating PR even without this feature enabled.
> fix(bridge v2): add missing feature toggle

- apps/emqx/src/emqx_schema.erl
- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl
- apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_tests.erl
- changes/ee/breaking-14765.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13954
Previously, we could not infer when the user furnished an explicit port for SQL Server, and always added the default port if not explicitly defined.
For Named Instances, we need to explicitly define a port to connect to when connecting with the ODBC driver.  And the driver happily connects to whatever instance is running on that port, completely ignoring the given Instance Name, if any.
Here, we demand that the port is explicitly defined when an instance name is given, and we also attempt to infer differences between desired and connected instance names during health checks.
- [na] ~~Schema changes are backward compatible~~  if anyone uses named instances without port, they'll fail the validation.
> fix(sqlserver): try to infer connected instance name

- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_raft_test_helpers.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_ds.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/test/emqx_mgmt_api_ds_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
- changes/ee/feat-14766.en.md
Fixes [EMQX-13910](https://emqx.atlassian.net/browse/EMQX-13910).
Partially addresses [EMQX-13909](https://emqx.atlassian.net/browse/EMQX-13909).
Release version: e5.9
[EMQX-13910]: https://emqx.atlassian.net/browse/EMQX-13910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-13909]: https://emqx.atlassian.net/browse/EMQX-13909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ctl): refuse to leave cluster if responsible for DS data

- apps/emqx/rebar.config.script
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- changes/ce/fix-14775.en.md
- mix.exs
- rebar.config.erl
bumps to quicer-0.2.4.
Enforce updating listener opts (listen opts, conn opts and stream opts) when reloading the quicer listener.
These configs are managed by quicer for efficiency.
Fixes [EMQX-13434](https://emqx.atlassian.net/browse/EMQX-13434)
Release version: v/e5.9
[EMQX-13434]: https://emqx.atlassian.net/browse/EMQX-13434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quic): reload listener also update conn opts and stream opts

- apps/emqx/rebar.config
- apps/emqx_retainer/rebar.config
- mix.exs
- rebar.config
fix flaky tests about client not recving MQTT.disconnect after connection graceful shutdown.
> chore: bump to emqtt 1.14.1

- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_channel.erl
- changes/ce/fix-14793.en.md
Fixes [EMQX-13972](https://emqx.atlassian.net/browse/EMQX-13972)
Add trace log for `protocol_error`.
Previously when client send invalid or unexpected packets to cause a `protocol_error` in EMQX, the detailed reason is not traced.
For example, if a client send two `CONNECT` packets, for the second one, EMQX may log `socket_force_closed` with `protocol_error`, but hard to tell why.
Now EMQX will log `unexpected_connect_packet` with `conn_satet=connected` before `socket_force_closed`.
```
[MQTT] actia@127.0.0.1:53490 msg: mqtt_packet_received, packet: CONNECT(Q0, R0, D0, ClientId=actia, ProtoName=MQTT, ProtoVsn=4, CleanStart=true, KeepAlive=60, Username=undefined, Password=)
[MQTT] actia@127.0.0.1:53490 msg: mqtt_packet_sent, packet: CONNACK(Q0, R0, D0, AckFlags=0, …
```
> fix: add trace logs for protocol_error

- .github/actions/package-macos/action.yaml
- Makefile
- changes/ce/fix-14797.en.md
- env.sh
fix: [EEC-1156](https://emqx.atlassian.net/browse/EEC-1156)
backport #14624 to release-58
[EEC-1156]: https://emqx.atlassian.net/browse/EEC-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Backport: macos quic use static link

- apps/emqx_bridge_pulsar/mix.exs
- apps/emqx_bridge_pulsar/rebar.config
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_pubsub_schema.erl
- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl
- changes/ee/fix-14796.en.md
- mix.exs
- rebar.config
- rel/i18n/emqx_bridge_pulsar.hocon
- rel/i18n/emqx_bridge_pulsar_pubsub_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13853
Release version: e5.8.6
Previously, this option didn't have any effects on the driver.
See also https://github.com/emqx/pulsar-client-erl/pull/75
- [na] ~~Added tests for the changes~~ tested manually
> fix(pulsar action): actually support `memory_overload_protection` option

- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_license/src/emqx_license.erl
- apps/emqx_license/src/emqx_license_checker.erl
- apps/emqx_license/src/emqx_license_cli.erl
- apps/emqx_license/src/emqx_license_http_api.erl
- apps/emqx_license/src/emqx_license_parser.erl
- apps/emqx_license/src/emqx_license_parser_v20220101.erl
- apps/emqx_license/src/emqx_license_resources.erl
- apps/emqx_license/src/emqx_license_schema.erl
- apps/emqx_license/test/emqx_license_SUITE.erl
- apps/emqx_license/test/emqx_license_checker_SUITE.erl
- apps/emqx_license/test/emqx_license_cli_SUITE.erl
- apps/emqx_license/test/emqx_license_http_api_SUITE.erl
- apps/emqx_license/test/emqx_license_parser_SUITE.erl
- apps/emqx_license/test/emqx_license_test_lib.erl
Release: e5.9.0
This is a follow up fix for the quick fix made into 5.8.5.
- Refactored internal APIs from `max_connections` to `max_sessions`.
- The config keys are not renamed, e.g. `connection_..._watermark ` and `dynamic_max_connections`.
- The PUT API for license settings is not changed, e.g. `connection_..._watermark ` and `dynamic_max_connections`.
- The GET API for license info retrieval has `max_connections` added alongside `max_sessions`.
> refactor(license): rename max_connections to max_sessions

- apps/emqx/src/emqx_session_events.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- changes/ce/fix-14800.en.md
`dropped_msg_due_to_mqueue_is_full` was changed to throttled log in 5.6.0
`dropped_qos0_msg` was not for unknown reason, looks like it was missed.
> fix: throttle wanring log dropped_qos0_msg,

- apps/emqx_mysql/mix.exs
- apps/emqx_mysql/rebar.config
This is to fix connectivity issue with oceanbase using MySQL protocol.
https://en.oceanbase.com/
see also: https://github.com/emqx/mysql-otp/pull/15
> fix: upgrade mysql driver from 1.8.0.0 to 1.8.0.1

- apps/emqx/rebar.config
- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- apps/emqx/test/emqx_quic_multistreams_SUITE.erl
- apps/emqx_retainer/rebar.config
- mix.exs
- rebar.config
Try fix flaky tests:
emqx_mqtt_protocol_v5_SUITE:t_connect_idle_timeout
emqx_mqtt_protocol_v5_SUITE:t_connect_clean_start_unresp_old_client
emqx_quic_multistreams_SUITE:t_conn_change_client_addr
and other flaky tests cased by emqtt (quic).
> try fix flaky test:  quic client addr change

- apps/emqx/priv/bpapi.versions
- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl
- apps/emqx_plugins/src/emqx_plugins.app.src
- apps/emqx_plugins/src/emqx_plugins.erl
- apps/emqx_plugins/src/emqx_plugins_cli.erl
- apps/emqx_plugins/src/proto/emqx_plugins_proto_v3.erl
- changes/ce/fix-14802.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13979
After discussions, the solution to the potential issue was to require explicit authorization to install a plugin (at specific version) via the CLI before HTTP API accepts the package.
> chore(plugins): require explicit CLI authorization to install packages

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- mix.exs
- rebar.config
fixes:[EMQX-13991](https://emqx.atlassian.net/browse/EMQX-13991)
this is a follow-up fix for
https://github.com/emqx/emqx/pull/14767
previously the messages in lost partitions are silently discarded, this fix makes sure the error counters are incremented
log example
```
2025-03-06T21:06:00.872345+01:00 [error] msg: stop_producers_for_lost_partitions, partitions: [3,4], producer_id: <<"action:kafka_producer:a:connector:kafka_producer:a">>
2025-03-06T21:06:00.873452+01:00 [error] tag: RESOURCE, msg: unrecoverable_resource_error, reason: partition_lost, resource_id: <<"action:kafka_producer:a:connector:kafka_producer:a">>
2025-03-06T21:06:00.873562+01:00 [error] tag: RESOURCE, msg: unrecoverable_resource_error, reason: partition_lost, resource_id: …
```
> fix: upgrade wolff to 4.0.9

- .github/workflows/build_and_push_docker_images.yaml
Fixes issue with arm64 docker images.
Port of docker build changes in #14825.
> ci: fix arm64 docker image upload

- apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl
- apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl
- changes/ee/fix-14756.en.md
Because most of devices can't parse the Register Ack packet with an empty auth code
Fixes https://emqx.atlassian.net/browse/EMQX-13945
Release version: v/e5.8.5 or e5.9.0
- ~Change log has been added to `changes/` dir …
> fix(jt808): send the default auth code in anonymous mode

- apps/emqx_gateway_jt808/src/emqx_gateway_jt808.app.src
- apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl
- apps/emqx_gateway_jt808/src/emqx_jt808_schema.erl
- apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl
- changes/ee/feat-14855.en.md
- changes/ee/fix-14756.en.md
- rel/i18n/emqx_jt808_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14000
Cherry-pick https://github.com/emqx/emqx/pull/14756 to 5.8.6
And add the `ignore_unsupported_frames` to avoid disconnecting JT/T 808 devices that have implemented with customized message typs
- ~If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual …
> Cherry-pick  #14756 and Add ignore_unsupported_frames option

- apps/emqx/test/emqx_bpapi_static_checks.erl
- apps/emqx_machine/mix.exs
- apps/emqx_mix_utils/lib/mix/tasks/emqx.dialyzer.ex
- mix.exs
Affects only new mix build.
```sh
ͳ env NEW_MIX_BUILD=1 PROFILE=emqx-enterprise mix dialyzer --mode incremental
Running dialyzer in incremental mode and PLT /emqx/emqx_dialyzer_26.2.5.2-1_plt_incremental
Ran incremental analysis in 74.837 s
Ok
ͳ env NEW_MIX_BUILD=1 PROFILE=emqx-enterprise mix dialyzer --mode incremental
Running dialyzer in incremental mode and PLT /emqx/emqx_dialyzer_26.2.5.2-1_plt_incremental
Ran incremental analysis in 2.082 s
Ok
```
Produces a PLT file that our static checks suite accepts (when run by `mix ct` and setting `BPAPI_BUILD_PROFILE` accordingly):
```sh
ͳ env NEW_MIX_BUILD=1 PROFILE=emqx-enterprise mix dialyzer --mode classic
Running dialyzer in classic mode and PLT /emqx/emqx_dialyzer_26.2.5.2-1_plt
Building initial PLT...
Built initial PLT in 61.451 s …
```
> feat(new mix build): add classic and incremental dialyzer support

- apps/emqx/test/emqx_cth_cluster.erl
- apps/emqx/test/emqx_cth_peer.erl
- apps/emqx_conf/test/emqx_conf_app_SUITE.erl
Port of test-only changes from https://github.com/emqx/emqx/pull/14778
Some cluster test suites expect node restarts.  If we don't give enough time for applications (in particular, `mnesia`) to shutdown gracefully, tests may fail when restarting the node with errors such as:
```
=ERROR REPORT==== 26-Feb-2025::10:57:39.847612 ===
Mnesia('emqx_conf_app_SUITE1@127.0.0.1'): ** ERROR ** (ignoring core) ** FATAL ** Cannot load table emqx_activated_alarm from disc: {not_loaded,
storage_unknown}
```
```
=ERROR REPORT==== 26-Feb-2025::09:17:12.062487 ===
Mnesia('emqx_conf_app_SUITE1@127.0.0.1'): ** ERROR ** (core dumped to file: "/__w/emqx/emqx/_build/test/logs/ct_run.test@127.0.0.1.2025-02-26_09.15.13/lib.emqx_conf.emqx_conf_app_SUITE.logs/run.2025-02-26_09.17.04/log_private/emqx_conf_app_SUITE_da …
```
> test(conf app suite): fix flaky test

- apps/emqx/src/emqx_ssl_crl_cache.erl
- apps/emqx/test/emqx_crl_cache_SUITE.erl
```
%%% emqx_crl_cache_SUITE ==> t_revoked: FAILED
%%% emqx_crl_cache_SUITE ==> {{case_clause,{error,connack_timeout}},
[{emqx_crl_cache_SUITE,t_revoked,1,
[{file,"/__w/emqx/emqx/apps/emqx/test/emqx_crl_cache_SUITE.erl"},
{line,899}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]}
```
> test(crl cache): attempt to fix flaky test

- apps/emqx_management/src/emqx_mgmt_cluster.erl
- changes/ce/fix-14863.en.md
Fixes [EMQX-14014](https://emqx.atlassian.net/browse/EMQX-14014)
"Async" cluster management API proxies requests through the leader. However, this is incorrect as mnesia leader may be down. This PR ensures that the node coordinating the join is alive. 
[EMQX-14014]: https://emqx.atlassian.net/browse/EMQX-14014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(mgmt_api_cluster): Send requests to node that is alive

- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
```
Testing lib.emqx.emqx_mqtt_protocol_v5_SUITE: *** FAILED test case 63 of 85 ***
%%% emqx_mqtt_protocol_v5_SUITE ==> quic.t_connect_clean_start_unresp_old_client: FAILED
%%% emqx_mqtt_protocol_v5_SUITE ==> {{got_another_message,{'EXIT',<0.140232.0>,normal}},
[{emqx_mqtt_protocol_v5_SUITE,waiting_client_process_exit,1,
[{file,"/__w/emqx/emqx/apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl"},
{line,143}]},
{emqx_mqtt_protocol_v5_SUITE,t_connect_clean_start_unresp_old_client,1,
[{file,"/__w/emqx/emqx/apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl"},
{line,245}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1793}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1302}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1234}]}]}
```
Also …
> test(mqtt v5 protocol): attempt to fix flaky test

- apps/emqx_auth_ldap/src/emqx_authn_ldap.erl
- apps/emqx_auth_ldap/src/emqx_authn_ldap_schema.erl
- apps/emqx_auth_ldap/test/emqx_authn_ldap_SUITE.erl
- changes/ee/breaking-14865.en.md
- rel/i18n/emqx_authn_ldap_schema.hocon
The `ldap_deprecated` was added in 5.4.0. Now it's deleted.
> refactor: delete deprecated ldap config schema

- Makefile
> chore: bump dashboard version to e1.8.6-beta.2

- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl
- changes/ce/feat-14869.en.md
In EMQX 5.8.4 Open Source:
System topics ($SYS/brokers/${node}/clients/connected/disconnected) include connected_at in disconnect events, but this field is missing in Rule Engine's $events/client_disconnected events.
When clients reconnect frequently due to poor networks, delayed disconnect events may overwrite newer connection statuses. Example sequence:
Disconnect event (1) contains old connected_at: 1740160813688
New connect event (3) has connected_at: 1740160856111
Without connected_at in disconnect events, business logic cannot determine which connection session the disconnect belongs to.
Root Cause:
Rule Engine's client_disconnected event payload does not include the connected_at timestamp from the original connection session, …
> feat: add connected_at field to events/client_disconnected payload

- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_producer_SUITE.erl
- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- scripts/install-msodbc-driver.sh
- scripts/install-snowflake-driver.sh
Fixes https://emqx.atlassian.net/browse/EMQX-14016
Now that we perform channel changes (add/remove) asynchronously during config updates,
there’s a chance that we may not reset the metrics when updating an action/source.
An example caught in CI:
https://github.com/emqx/emqx/actions/runs/13839069149/job/38722213036?pr=14860#step:4:680
```
%%% emqx_bridge_v2_kafka_producer_SUITE ==> t_overflow_rule_metrics: FAILED
%%% emqx_bridge_v2_kafka_producer_SUITE ==> 
Failure/Error: ?assertMatch(# { counters := # { dropped := 1 , 'dropped.queue_full' := 1 , 'dropped.expired' := 0 , 'dropped.other' := 0 , matched := 1 , success := 0 , failed := 0 , late_reply := 0 , retried := 0 } }, emqx_bridge_v2 : get_metrics ( Type , ActionName ))
expected: = # { counters := # { dropped …
```
> fix(resource manager): correctly handle channel updates

- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl
Port from https://github.com/emqx/emqx/pull/14867
```
%%% emqx_bridge_sqlserver_SUITE ==> sync.without_batch.t_write_failure: FAILED
%%% emqx_bridge_sqlserver_SUITE ==>
Failure/Error: ?assertMatch({ error , { resource_error , # { reason := timeout } } }, send_message ( Config , SentData ))
expected: = { error , { resource_error , # { reason := timeout } } }
got: {error,
{unrecoverable_error,
{invalid_request,
"[Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: Error code 0x2746[Microsoft][ODBC Driver 18 for SQL Server]Communication link failure SQLSTATE IS: 08S01"}}}
line: 326
```
See also:
https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/mssqlserver-17194-database-engine-error?view=sql-server-ver16
Release version: 5.8.6
> fix(sqlserver action): handle concurrent connection close during request

- apps/emqx/rebar.config
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx_retainer/rebar.config
- mix.exs
- rebar.config
Basically fixes flaky tests:
- https://github.com/emqx/emqx/pull/14861
- https://github.com/emqx/emqx/actions/runs/13928128336/job/38980458444?pr=14894#step:5:343
See also:
- https://github.com/emqx/emqtt/pull/279
- https://github.com/emqx/emqtt/pull/280
> chore: bump `emqtt` -> 1.14.4

- apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
- apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl
Release version: 5.8.6
This is a followup fix for https://github.com/emqx/emqx/pull/14880
Force odbc reconnect if `SELECT 1` query got unexpected result.
Cannot simulate such error with real server, so the test is done by injecting error with a mock.
> 250319 sqlserver reconnect if health check failed

- rel/i18n/emqx_schema.hocon
Some users mistakenly believe that setting it to  `none` will disable the tcp keepalive.
> docs: Set to 'none' to use OS default keepalive settings instead of override them

- apps/emqx_auth/src/emqx_authn/emqx_authn_utils.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz_utils.erl
- apps/emqx_auth_http/src/emqx_authn_http.erl
- apps/emqx_auth_http/src/emqx_authn_scram_restapi.erl
- apps/emqx_auth_http/src/emqx_authz_http.erl
- apps/emqx_auth_jwt/src/emqx_authn_jwt.erl
- apps/emqx_auth_ldap/src/emqx_authn_ldap.erl
- apps/emqx_auth_ldap/src/emqx_authz_ldap.erl
- apps/emqx_auth_ldap/test/emqx_authn_ldap_bind_SUITE.erl
- apps/emqx_auth_mongodb/src/emqx_authn_mongodb.erl
- apps/emqx_auth_mongodb/src/emqx_authz_mongodb.erl
- apps/emqx_auth_mysql/src/emqx_authn_mysql.erl
- apps/emqx_auth_mysql/src/emqx_authz_mysql.erl
- apps/emqx_auth_postgresql/src/emqx_authn_postgresql.erl
- apps/emqx_auth_postgresql/src/emqx_authz_postgresql.erl
- apps/emqx_auth_redis/src/emqx_authn_redis.erl
- apps/emqx_auth_redis/src/emqx_authz_redis.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
This is pure refactoring to improve logging data (in order to help AI to parse the log fields).
Previously the `resource_id` in the logs does not quite align with the authenticator ID (which is of format `MECHANISM:BACKEND`).
This PR changes the internal format of the resource ID to `authn:TYPE:NUMBER` such as `authn:postgres:1` and the `owner_id` to `MECHANISM:BACKEND` such as `password_based:postgres`.
Same for authz connectors.
- `authz:TYPE:NUMBER` for internal resource ID such as `auth:mysql:2`
- `TYPE` for `owner_id`, such as `mysql`.
> 250315 refactor resource id for authn authz

- apps/emqx/mix.exs
- apps/emqx/rebar.config
- changes/ce/fix-14906.en.md
- mix.exs
- rebar.config
Addresses #14541.
Release version: 5.8.6
This version uses "link-less" middleman processes, which helps to avoid polluting message queue of calling processes with `{'EXIT', ..., normal}` trapped exit messages.
> fix(emqx): bump `mria` to 0.8.12.1

- apps/emqx_auth/src/emqx_auth_cache.erl
this trace point does not seem to be used in tests, and this debug info isn't quite useful either.
> chore: remove a debug log

- apps/emqx_auth_ldap/test/emqx_authn_ldap_SUITE.erl
- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
- apps/emqx_bridge_mysql/test/emqx_bridge_v2_mysql_SUITE.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
Incited by investigating https://emqx.atlassian.net/browse/EMQX-14045
The original issue was already fixed by:
- https://github.com/emqx/emqx/pull/14740
- https://github.com/emqx/emqx/pull/14867
This patch improves the logic by preventing such cases from occurring even if manually (in
console) trying to provoke resource health checks.
Also fixes minor issue: https://emqx.atlassian.net/browse/EMQX-14047
See individual commits for clearer changes.
- [na] ~~Change log has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~ already fixed elsewhere; this only makes things more robust.
> fix(resource manager): do not start resource health checks when disconnected

- apps/emqx_opentelemetry/mix.exs
This only affects the new mix build.
> fix(new mix build): add missing dependency to `emqx_opentelemetry`

- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
- changes/ee/fix-14933.en.md
Part of [EMQX-13864](https://emqx.atlassian.net/browse/EMQX-13864).
Address an edge case in shard allocation: avoid allocating shards to lost sites. This is extremely unlikely to happen in practice, but occasionally manifests in emqx/emqx-operator#1123 test runs.
[EMQX-13864]: https://emqx.atlassian.net/browse/EMQX-13864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dsraft): avoid allocating shards on lost sites

- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_state.erl
- apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_stream_scheduler.erl
- apps/emqx/src/emqx_persistent_session_ds/session_internals.hrl
- apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl
- apps/emqx_ds_builtin_raft/src/proto/emqx_ds_proto_v4.erl
- apps/emqx_ds_builtin_raft/src/proto/emqx_ds_proto_v5.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader_rank_progress.erl
- apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_store.erl
- apps/emqx_durable_storage/src/emqx_ds.erl
- apps/emqx_durable_storage/src/emqx_ds_beamformer.erl
Fixes [EMQX-14054](https://emqx.atlassian.net/browse/EMQX-14054)
The abstraction of "rank" was a leaky one. This PR removes it and replaces it with concepts of shard and generation.
- First of all, there wasn't any real reason to hide the existence of shards from the user.
- When we want to use DS as a serializable storage for session data, this obscurity becomes a major obstacle: user code has no reliable way to handle errors
- It also leads to inefficiencies: when the user code has to iterate over data that belongs to a certain client ID, it should be able to do so over streams that belong to the specific shard instead of sending `get_streams` request to _all_ shards.   
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip …
> Expose concepts of shard and generation directly

- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl
- apps/emqx_plugins/src/emqx_plugins.erl
- apps/emqx_plugins/src/emqx_plugins_apps.erl
- apps/emqx_plugins/test/emqx_plugins_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_config_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_test_helpers.erl
- changes/ce/breaking-14957.en.md
Fixes [EMQX-14039](http://emqx.atlassian.net/browse/EMQX-14039)
The major changes are:
* We load plugin apps during the _installation_ of a plugin. We need this to call the `on_config_change` callback for stopped plugins.
* We introduce a new method for updating plugins' config and respect `on_config_change` result in it. 
**NOTE** This is obviously a breaking change, but only for new config updates coming from the dashboard. The callback result is still ignored for the configs already stored in the cluster. 
[EMQX-14039]: https://emqx.atlassian.net/browse/EMQX-14039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(emqx_plugins): respect plugin's `on_config_changed` callback response

- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl
- apps/emqx_plugins/src/emqx_plugins.erl
- apps/emqx_plugins/src/emqx_plugins_apps.erl
- apps/emqx_plugins/src/emqx_plugins_info.erl
- apps/emqx_plugins/test/emqx_plugins_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_config_SUITE.erl
- changes/ce/feat-14963.en.md
Fixes [EMQX-14040](https://emqx.atlassian.net/browse/EMQX-14040)
We add health status as a new field to the existing plugin info structure. This structure is used to get/list plugins via API/CLI.
[EMQX-14040]: https://emqx.atlassian.net/browse/EMQX-14040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(plugins): implement plugin health check

- apps/emqx/rebar.config
- apps/emqx/src/emqx_router_helper.erl
- apps/emqx/test/emqx_router_helper_SUITE.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
- changes/ce/fix-14936.en.md
- mix.exs
- rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-14055.
_Orphaned_ node here means a node that is marked as "routing node" in the respective table but cluster membership does not know about it.
Behavior is slightly changed, most notably:
* Nodes which are leaving / have left the cluster will be purged after 10 second delay, after cluster membership changes are completed.
* Nodes which have been "force-left" right after going down will be purged after 10 second delay, after cluster membership changes are completed; in other cases in ~1 minute during the next reconcile (same as before).
This also means that flapping cluster nodes may delay purges for considerable amount of time.
Please convert it to a draft if any of the following …
> fix(router): purge orphaned routing nodes during reconcile

- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_dashboard/src/emqx_dashboard_admin.erl
- apps/emqx_dashboard/src/emqx_dashboard_api.erl
- apps/emqx_dashboard/src/emqx_dashboard_app.erl
- apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
- changes/ee/feat-14966.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14053
This essentially allows one to rename the default admin user after a cluster is already started by creating a new admin and deleting the default one.
If there is at least one admin user other than the default one, we may delete the latter.
Also, since the `emqx_dashboard` application attempts to create the default user every time it starts, we use the same logic to avoid creating it.
> feat(dashboard api): allow deleting default admin when others exist

- apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl
- apps/emqx_auth/src/emqx_authn/emqx_authn_schema.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_chains_SUITE.erl
- apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl
- apps/emqx_conf/test/emqx_conf_cli_SUITE.erl
- apps/emqx_utils/src/emqx_variform.erl
- changes/ee/feat-14976.en.md
- rel/i18n/emqx_authn_schema.hocon
Fixes [EMQX-13883](https://emqx.atlassian.net/browse/EMQX-13883)
This will be useful when need to apply different auth mechanism based on client information.
As an example, if one wants to use HTTP auth for one listener, and MySQL auth for another, 
before 5.9, both authenticator will be called for clients from any of the listeners.
now it's possible to skip-over with a precondition like: `str_eq(listener, 'tcp:default')` -- which means invoke this authenticator only when listener is `tcp:default`.
Current auth chain on the left side, the new chain after this PR on the right side.
[EMQX-13883]: https://emqx.atlassian.net/browse/EMQX-13883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 250402 precondition for authn

- .github/workflows/build_and_push_docker_images.yaml
- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx_cluster.erl
- apps/emqx/src/proto/emqx_cluster_proto_v1.erl
- apps/emqx_license/include/emqx_license.hrl
- mix.exs
- scripts/test/cluster-smoke-test.sh
- scripts/test/start-two-nodes-in-docker.sh
Added a RPC call `emqx_cluster:can_i_join/1` to if peer node allows the requesting node to join cluster.
Previously (5.9, but not released yet), the check is done locally, as a result it was not possible to join cluster without adding a license first --- this was considered a bad user experience.
Now the new node can join cluster without a license added, then license will be fetched from peer node after joined.
- [~] For internal contributor: there is a jira ticket to track this change (this is a follow-up fix for https://github.com/emqx/emqx/pull/14803
- [~] Schema changes are backward compatible or intentionally breaking (describe the changes …
> 250404 refactor license take2

- apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_pubsub_schema.erl
- apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_connector_SUITE.erl
- apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_test_utils.erl
- apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl
- changes/ee/feat-14996.en.md
- rel/i18n/emqx_bridge_rabbitmq_connector_schema.hocon
Fixes [EMQX-14082](https://emqx.atlassian.net/browse/EMQX-14082)
Mark `exchange` field as non-required and default to `<<>>` to use default exchange
see also https://www.rabbitmq.com/docs/exchanges#default-exchange
[EMQX-14082]: https://emqx.atlassian.net/browse/EMQX-14082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: rabbitmq exchange as non-required to support default exchange

- apps/emqx_connector/src/emqx_connector_resource.erl
- apps/emqx_connector/test/emqx_connector_SUITE.erl
- changes/ce/fix-15010.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14090
Previously, the toggle check always failed because extra keys were being injected into the new configuration being compared to the old one.
> fix(connector): correctly detect toggle operation

- apps/emqx_bridge_pulsar/mix.exs
- apps/emqx_bridge_pulsar/rebar.config
Release: 5.9.0
Just to mute some compile warnings.
https://github.com/emqx/pulsar-client-erl/pull/77
> chore: upgrade pulsar client from 2.1.0 to 2.1.1 (compile warning)

- .ci/docker-compose-file/docker-compose-elastic-search-tls.yaml
- .ci/docker-compose-file/docker-compose-emqx-cluster-mnesia.override.yaml
- .ci/docker-compose-file/docker-compose-emqx-cluster-rlog.override.yaml
- .ci/docker-compose-file/docker-compose-emqx-cluster.yaml
- .ci/docker-compose-file/docker-compose-hstreamdb.yaml
- .ci/docker-compose-file/docker-compose-mongo-replicaset-tcp.yaml
- .ci/docker-compose-file/docker-compose-mongo-replicaset-tls.yaml
- .ci/docker-compose-file/docker-compose-mongo-sharded-tcp.yaml
- .ci/docker-compose-file/docker-compose-redis-sentinel-tcp.yaml
- .ci/docker-compose-file/docker-compose-redis-sentinel-tls.yaml
- .ci/docker-compose-file/scripts/run-emqx.sh
- .github/workflows/run_helm_tests.yaml
- apps/emqx/src/emqx_cluster.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_license/src/emqx_license.erl
- apps/emqx_license/src/emqx_license_app.erl
- apps/emqx_license/src/emqx_license_checker.erl
- apps/emqx_license/src/emqx_license_cli.erl
- apps/emqx_license/src/emqx_license_http_api.erl
- apps/emqx_license/src/emqx_license_parser.erl
- apps/emqx_license/src/emqx_license_sup.erl
- apps/emqx_license/test/emqx_license_SUITE.erl
- apps/emqx_license/test/emqx_license_cli_SUITE.erl
- apps/emqx_license/test/emqx_license_http_api_SUITE.erl
- apps/emqx_license/test/emqx_license_parser_SUITE.erl
- apps/emqx_machine/priv/reboot_lists.eterm
- apps/emqx_machine/src/emqx_machine_boot.erl
Fixes [EMQX-14092](https://emqx.atlassian.net/browse/EMQX-14092)
- Do not allow setting license key back to 'default' (or single-node license) if the node is already clustered.
- If auto cluster is configured (e.g. `static`, `dns` or `k8s` strategy), the `emqx_cluster:join/1` API is not called, clustering is completed by `ekka` -- for this case, `emqx_license` app would not boot if 1) it's currently clustered, 2) the taking-effect license is single-node.
[EMQX-14092]: …
> fix(license): do not allow single node license when already clustered

- apps/emqx_telemetry/src/emqx_telemetry.erl
Tiny fix to avoid log pollution with info messages:
```
2025-04-11T19:12:12.834731+03:00 [error]     msg: unexpected_info
info: {timeout,#Ref<0.1456251408.65536002.65347>,
time_to_report_telemetry_data}
2025-04-11T19:12:17.458594+03:00 [error]     msg: unexpected_info
info: {timeout,#Ref<0.1456251408.65536001.70515>,
time_to_report_telemetry_data}
...
```
> fix(telemetry): fix double timer scheduling

- apps/emqx/src/config/emqx_config_zones.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter.erl
- apps/emqx/test/emqx_limiter_SUITE.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_mt/test/emqx_mt_api_SUITE.erl
- changes/ce/fix-15037.en.md
Fixes [EMQX-14105](https://emqx.atlassian.net/browse/EMQX-14105)
Although this goes as a fix, it seems we never supported dynamic zone update for rate limiting. 
This was just revealed by more strict listener creation.
[EMQX-14105]: https://emqx.atlassian.net/browse/EMQX-14105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(limiter): handle dynamic zone update for limiters

- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14109
Previously, when the Action was marked as an "unhealthy target", the request would not even reach the buffering layer, where the fallback action triggering logic lives.
> fix(resource): trigger fallback actions when action is an "unhealthy target"

- apps/emqx_bridge_es/src/emqx_bridge_es.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14110
The previous schema module was using the wrong schema helper (declaring the action as a source instead of an action), so that prevented it from picking up the new `fallback_actions` field that comes from common action fields.
> fix(elasticsearch): fix bad schema

- apps/emqx_auth_redis/src/emqx_authn_redis.erl
- apps/emqx_auth_redis/test/emqx_authn_redis_SUITE.erl
- changes/ce/fix-15059.en.md
Fixes [EMQX-14137](https://emqx.atlassian.net/browse/EMQX-14137)
Legacy bug. The Redis resource crashed in the case of an update to the Redis authn config with values that did not pass validation.
[EMQX-14137]: https://emqx.atlassian.net/browse/EMQX-14137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(authn): fix redis config update

- apps/emqx_schema_registry/include/emqx_schema_registry.hrl
- apps/emqx_schema_registry/src/emqx_schema_registry_config.erl
- apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
Inspired by https://emqx.atlassian.net/browse/EMQX-14159, but doesn't fix it (seems to be a frontend issue).
The certificates were save directly to config, without being converted to files, which should be fine.  Those certificate contents were already being returned by the HTTP API, but frontend does not display them.
> fix(schema registry): convert SSL/TLS certificates for external http serde

- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
```
2025-04-22T21:13:37.514438+00:00 [critical] "check stage" failed: error, {unexpected_trace,[#{reason => {error,closed},msg => gcp_pubsub_request_failed,connector => ...
```
https://github.com/emqx/emqx/actions/runs/14604493674/job/40970793439#step:4:615
> test(gcp pubsub producer): fix flaky test

- apps/emqx_mix_utils/lib/emqx/mix/utils.ex
- apps/emqx_mix_utils/lib/mix/tasks/cover_index.html.eex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.cover.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.ct.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.eunit.ex
- mix.exs
This only affects the new mix build.
Running multiple tests in the same mix invocation is much faster, as cover compilations happens only once.
Only outputs HTML report at the moment.
Ex:
```sh
env NEW_MIX_BUILD=1 ENABLE_COVER_COMPILE=1 CLEAR_SCREEN=true PROFILE=emqx-enterprise-test mix do ct --suites apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl --cases t_smoke_test, eunit --cases emqx_schema_validation_tests:duplicated_check_test_ , cover 
Saving analysis index to /emqx/_build/emqx-enterprise-test/cover/index.html
Cover analysis done
```
> feat(new mix build): add cover analysis support

- apps/emqx_auth_http/src/emqx_authz_http.erl
- apps/emqx_auth_ldap/src/emqx_authn_ldap_bind.erl
- apps/emqx_auth_ldap/test/emqx_authn_ldap_bind_SUITE.erl
- apps/emqx_ldap/src/emqx_ldap.erl
Fixes [EMQX-14161](https://emqx.atlassian.net/browse/EMQX-14161)
this is a follow-up fix for https://github.com/emqx/emqx/pull/14979 (5.9.0, not released yet)
1. Missed `zone` for allowed vars in HTTP authz
2. Ensure ldap filter var allows atom values to render template
[EMQX-14161]: https://emqx.atlassian.net/browse/EMQX-14161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 250423 zone and listener for all backends

- apps/emqx/src/emqx_connection.erl
- changes/ce/fix-15106.en.md
Fixes [EMQX-14170](https://emqx.atlassian.net/browse/EMQX-14170).
In effect, this piece of code is now equivalent to `emqx_ws_connection`.
[EMQX-14170]: https://emqx.atlassian.net/browse/EMQX-14170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(conn): ensure events do not accidentally resurrect chaninfo

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- changes/ee/fix-15116.en.md
If Kafka has ACL control for clients, it may return topic_authorization_failed for the default health-check probing topic.
Allow this reason code.
> fix(kafka): allow `topic_authorization_failed` for probing topic

- apps/emqx_auth_cinfo/src/emqx_auth_cinfo.app.src
- apps/emqx_auth_cinfo/src/emqx_authn_cinfo.erl
- changes/ee/fix-15117.en.md
This PR fixes a `case_clause` warning level log in case cinfo auth expression failed to evaluate.
There will still be a warning level log, but will not appear like a crash.
```
2025-04-25T13:15:59.993395+00:00 [warning] tag: AUTHN, clientid: mqttx_a50058aa, msg: authenticator_error, peername: 127.0.0.1:60842, 
reason: {case_clause,{error,#{error => #{reason => var_unbound,var_name => <<"cert_common_name">>},
cause => "clientinfo_auth_expression_evaluation_error"}}}, 
stacktrace: [{emqx_authn_cinfo,do_check,2,[{file,"emqx_authn_cinfo.erl"},{line,94}]},{emqx_authn_cinfo,check,2,[{file,"emqx_authn_cinfo.erl"},{line,82}]},{emqx_authn_chains,authenticate_with_provider,2,...
```
New log looks like this
```
2025-04-25T15:46:50.748732+02:00 [warning] clientid: client1, …
```
> refactor: refine cinfo expression evaluation failure warning message

- apps/emqx_schema_registry/src/emqx_schema_registry.app.src
Attempt to fix https://emqx.atlassian.net/browse/EMQX-14166?focusedCommentId=54029
Could not reproduce this issue locally at all.  Only guessing what could be the issue: `emqx_resource` and/or `emqx_bridge_http` applications not starting before schema registry?
- [na] ~~The changes are covered with new or existing tests~~ could not reproduce the issue myself, and QA confirmed this build seems ok.
> fix(schema registry): attempt to fix reported issue

- apps/emqx/src/emqx_cm_registry.erl
- apps/emqx_dashboard/include/emqx_dashboard.hrl
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- changes/ee/feat-15119.en.md
- rel/i18n/emqx_dashboard_monitor_api.hocon
- rel/i18n/emqx_dashboard_schema.hocon
Fixes [EEC-1117](https://emqx.atlassian.net/browse/EEC-1117)
Expose session registry table size as a high-watermark metric and expose it to dashboard.
[EEC-1117]: https://emqx.atlassian.net/browse/EEC-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 250425 expose session hist count metric

- apps/emqx/src/emqx_cluster.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
Fixes [EMQX-14122](https://emqx.atlassian.net/browse/EMQX-14122)
When connecting an unreachable node, avoid crash logs, also keep the error backward compatible.
[EMQX-14122]: https://emqx.atlassian.net/browse/EMQX-14122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ctl): avoid crash 'emqx ctl cluster join' when node is unknown

- apps/emqx_exhook/src/emqx_exhook.erl
- apps/emqx_exhook/src/emqx_exhook_mgr.erl
- apps/emqx_exhook/src/emqx_exhook_server.erl
- apps/emqx_exhook/src/emqx_exhook_sup.erl
- apps/emqx_exhook/test/emqx_exhook_SUITE.erl
- changes/ee/fix-15108.en.md
- mix.exs
- rebar.config
Fixes: [EMQX-14048](https://emqx.atlassian.net/browse/EMQX-14048)
Bump `grpc-erl` vsn to `0.7.2` to add health check feature for ExHook.
The logic of health check and automatic reconnection working together:
- Server running and everything working.
- Do health check (C1), found it health, nothing happened.
- Stop server.
- Do health check (C2), found it unhealthy.
- Start a reload timer if the server configured `auto_reconnect`.
- Mark server `connecting` Aka status `R` here.
- Do health check (C3), found it still unhealthy.
- Ensure the reload timer. if was a timer here, do nothing.
- Mark server `disconnected`
- Do reload, (between C3 and C4)
- Still cann't connected to server.
- Ensure a reolad timer, old timer stopped here, start a new one.
- Mark `disconnected` …
> feat: exhook health checker

- apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_meta.erl
- apps/emqx_ds_builtin_raft/test/emqx_ds_builtin_raft_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
Fixes  EMQX-14193
Old behaviour casues race cond that, if other node just rejoin the cluster but get removed by this node, both are run in mria transaction but in different order.
> fix(raft): local node should not remove other node's presence.

- apps/emqx_ctl/src/emqx_ctl.erl
- apps/emqx_node_rebalance/src/emqx_node_rebalance_cli.erl
Fixes: [EMQX-14203](https://emqx.atlassian.net/browse/EMQX-14203)
Only cosmetic. After fix:
```
rebalance start --evacuation \            # Start current node evacuation with optional
[--wait-health-check Secs] \            # server redirect to the specified servers
[--redirect-to "Host1 Host2 .."] \      #
[--conn-evict-rate CountPerSec] \       #
[--migrate-to "emqx@h.1 emqx@h.2 .."] \ #
[--wait-takeover Secs] \                #
[--sess-evict-rate CountPerSec]         #
rebalance start \                         # Start rebalance on the specified nodes
[--nodes "eqmx@h.1 emqx@h.2 .."] \      # using the current node as the coordinator
[--wait-health-check Secs] \            #
[--conn-evict-rate ConnPerSec] \        #
[--conn-evict-rpc-timeout Secs] \       # …
```
> refactor(ctl): improve usage info for rebalance ctl command

- apps/emqx/src/emqx_cm_registry_keeper.erl
- apps/emqx/test/emqx_cm_registry_keeper_SUITE.erl
- changes/ee/fix-15143.en.md
Introduced in 5.8, the chunked cleanup of retained session history missed a timer restart, slipped due to lack of test coverage.
> 250430 fix cm retained info cleanup

- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
Release 5.9.0
Bug not released yet.
This was a bug introduced during some refactoring after manual tests.
And the CT case only tested one flush cycle, it take two to trigger the bug.
> fix(dashboard): compare with hwmark peak_value instead of current_value

- .github/workflows/build_and_push_docker_images.yaml
The [job for e5.9.0 tag push](https://github.com/emqx/emqx/actions/runs/14792592623) failed because docker smoke test has become more advanced, and 5 minutes for all tags is not enough anymore.
But we don't actually need to test each and every tag, since all of them point to the same image.
No need to retag, manually triggered docker build here: https://github.com/emqx/emqx/actions/runs/14792592623
> ci: fix docker smoke test

- .github/workflows/release.yaml
No need to retag, tested and uploaded packages manually.
> ci: fix snapcraft upload command

- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_conf/test/emqx_conf_cli_SUITE.erl
- changes/ee/feat-15158.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12895
See ticket for more context.
This (merging with old config) apparently is the expected behavior for conf load, despite the `--replace` flag.
https://github.com/emqx/emqx/blob/75dad16c9ac571908e9776a1abb68a3b7a628bc6/apps/emqx/src/emqx_config_handler.erl#L415-L419
> feat(conf cli): add command to delete config path

- apps/emqx_connector_aggregator/test/emqx_connector_aggregator_SUITE.erl
```
%%% emqx_connector_aggregator_SUITE ==> t_trigger_max_records: FAILED
%%% emqx_connector_aggregator_SUITE ==> {noproc,{gen_server,call,[snabbkaffe_collector,flush_trace,infinity]}}
```
https://github.com/emqx/emqx/actions/runs/14883981230/job/41799294818?pr=15159#step:5:351
> test(aggregator): attempt to fix flaky test

- .github/workflows/_push-entrypoint.yaml
Otherwise, codecov won't have a base to compare against.
> ci: run push workflow for `release-510`

- .ci/docker-compose-file/docker-compose-azurite.yaml
Apparently, microsoft decided to change some things in the already tagged image.... 🫠
- `curl` no longer exists in the image.
- `GET /` now seems to return a 400 error, which would make `curl -f` fail anyway.
> ci: fix azurite container health check

- apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
- changes/ee/fix-15224.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14280
> fix(external schema registry): deobfuscate passwords when updating

- apps/emqx_connector/src/emqx_connector_api.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14292
The problem was that, during an update, the type is an atom instead of a binary.
- [na] The changes are covered with new or existing tests (tested manually)
> fix(connectors api): focus on value when there's an update error

- apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl
- apps/emqx_postgresql/src/emqx_postgresql.app.src
- apps/emqx_postgresql/src/emqx_postgresql.erl
- changes/ee/fix-15274.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14321
> fix(postgres): reconnect after health check failures, return more info

- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
- changes/ee/fix-15334.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14363
> fix(rule api): make `/rules/:id/test` respond to legacy event topics in rule

- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_frame.erl
- apps/emqx/test/emqx_frame_SUITE.erl
- changes/ee/fix-15361.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14323
> fix(frame): handle malformed v5 user-property length for pair

- apps/emqx_bridge_mysql/test/emqx_bridge_v2_mysql_SUITE.erl
- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource_pool.erl
https://github.com/emqx/emqx/actions/runs/15634307273/job/44046132167?pr=15377#step:4:1326
```
%%% emqx_bridge_v2_mysql_SUITE ==> t_timeout_disconnected_then_recover: FAILED
%%% emqx_bridge_v2_mysql_SUITE ==> {{panic,
#{msg => "Unexpected result",
result =>
{run_stage_failed,error,
{assertMatch,
[{module,emqx_bridge_v2_mysql_SUITE},
{line,338},
{expression,"get_connector_api ( Config )"},
{pattern,
"{ 200 , # { << \"status\" >> := << \"connecting\" >> } }"},
{value,
{200,
#{<<"actions">> =>
[<<"t_timeout_disconnected_then_recover-576460752303399231">>],
<<"database">> => <<"mqtt">>,
<<"description">> => <<>>,<<"enable">> => true,
<<"name">> =>
<<"t_timeout_disconnected_then_recover-576460752303399231">>,
<<"node_status">> =>
[#{<<"node">> => …
```
> test: attempt to fix flaky test, improve returned error during HC call timeout

- apps/emqx_bridge_redis/test/emqx_bridge_redis_SUITE.erl
https://github.com/emqx/emqx/actions/runs/15684118558/job/44183627993?pr=15382#step:4:642
```
2025-06-16T15:02:32.343267+00:00 [critical] "check stage" failed: error, {panic,#{msg => "Causality violation",causes_without_effect => [],effects_without_cause => [#{mode => sync,msg => redis_bridge_connector_send_done,result => {ok,[{ok,<<"2">>},{ok,<<"3">>},{ok,<<"4">>},{ok,<<"5">>}]}, .....
```
> test(redis): attempt to fix flaky test

- apps/emqx_bridge_s3tables/test/emqx_bridge_s3tables_SUITE.erl
https://github.com/emqx/emqx/actions/runs/15688240390/job/44197310871?pr=15391#step:4:763
```
Testing lib.emqx_bridge_s3tables.emqx_bridge_s3tables_SUITE: *** SKIPPED test case 11 ***
%%% emqx_bridge_s3tables_SUITE ==> not_partitioned.t_multipart_upload: SKIPPED
%%% emqx_bridge_s3tables_SUITE ==> {tc_auto_skip,
{failed,
{emqx_bridge_s3tables_SUITE,init_per_testcase,
{{http_error,502,"Bad Gateway",
<<"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.27.5</center>\r\n</body>\r\n</html>\r\n">>,
[{"connection","keep-alive"},
{"content-length","157"},
{"content-type","text/html"},
{"date","Mon, 16 Jun 2025 18:10:36 GMT"},
{"server","nginx/1.27.5"}]},
[{emqx_bridge_s3tables_SUITE,ensure_namespace_created,2, …
```
> test(s3tables): attempt to stabilize flaky test

- mix.exs
- rebar.config
backport of #15332
Fixes [EMQX-14397](https://emqx.atlassian.net/browse/EMQX-14397)
Release version: 5.8.7, 5.9.1
[EMQX-14397]: https://emqx.atlassian.net/browse/EMQX-14397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: bump minirest to 1.4.8 to fix swagger css

- apps/emqx/priv/bpapi.versions
- apps/emqx/src/bpapi/emqx_bpapi.erl
- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
- apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl
- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_schema.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_consumer_SUITE.erl
- apps/emqx_bridge_kinesis/mix.exs
- apps/emqx_bridge_kinesis/rebar.config
- apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.app.src
- apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.erl
- apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis_connector_client.erl
- apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis_impl_producer.erl
- apps/emqx_bridge_kinesis/src/proto/emqx_bridge_kinesis_proto_v1.erl
- apps/emqx_bridge_kinesis/test/emqx_bridge_kinesis_v2_SUITE.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/schema/emqx_resource_schema.erl
- changes/ee/feat-15387.en.md
- rel/i18n/emqx_resource_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14359
AWS Kinesis APIs that are used for health checks in Kinesis producer are very rate limited: 5 TPS for connector HCs and 10 TPS for action HCs, per region per account, respectively.
To reduce the probability of triggering alerts and hitting such quotas, we introduce here limiters to adhere to such limits.  To make it work in a cluster, one core node is considered the coordinator, and holds the actual limiter that is consumed during HCs.  If a HC is rate limited, we wait for a bit and try again until either it succeeds or times out.  In the latter case, we repeat the last status of the connector/action instead of marking it as disconnected straight away.
> feat(kinesis producer): add rate limiter to reduce quota limit probability

- apps/emqx/rebar.config
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- changes/ee/fix-15416.en.md
- mix.exs
- rebar.config
Fixes [EMQX-14429](https://emqx.atlassian.net/browse/EMQX-14429).
Release version: 5.10.1?
emqx/cowboy#13 includes fixes for "crash-on-shutdown" bug in `cowboy_websocket_linger` logic.
No new testcases: existing tests (namely, `emqx_persistent_session_SUITE.persistence_disabled.ws` test group) are now free of crash reports and "unknown message" warnings.
[EMQX-14429]: https://emqx.atlassian.net/browse/EMQX-14429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(wsconn): update `cowboy` to 2.13.0-emqx-2

- .github/pull_request_template.md
- .github/workflows/build_packages_cron.yaml
- .github/workflows/codeql.yaml
- .github/workflows/green_master.yaml
- Makefile
- apps/emqx/include/emqx_release.hrl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_meta.erl
- apps/emqx_management/src/emqx_mgmt_data_backup.erl
- deploy/charts/emqx-enterprise/Chart.yaml
- scripts/get-dashboard.sh
- scripts/parse-git-ref.sh
- scripts/rel/cut.sh
- scripts/rel/sync-remotes.sh
- scripts/semver.sh
- scripts/shelltest/parse-git-ref.test
- Recognize release-60
- Add support for internal release tagging scheme
- Add release-58 back to the list of supported branches since 5.8 family is LTS
- Do not run ds raft migrations
- Support new versioning scheme for Dashboard
- Allow import of backups from v5 to v6
Release version: 6.0.0-M1.202507
> [6.0.0] support new releases

- apps/emqx/include/emqx_instr.hrl
- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_broker_helper.erl
- apps/emqx/src/emqx_broker_sup.erl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/test/emqx_broker_SUITE.erl
- apps/emqx/test/emqx_broker_helper_SUITE.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx_prometheus/src/emqx_prometheus.erl
- apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl
- apps/emqx_utils/mix.exs
- apps/emqx_utils/src/emqx_metrics_worker.erl
- apps/emqx_utils/src/emqx_utils.app.src
- mix.exs
- rebar.config.erl
Part of EMQX-14333.
Release version: 6.0?
Number of shards per topic is not limited now, and each shard will hold no more that 1024 (`emqx_broker_helper:shard_capacity/0`) subscribers.
Downside is: subscriber table may now hold more than 1024 + 32 * C entries per topic, where C is number of schedulers, but in the general case number of entries now scales better with number of subscribers.
Also instrument core dispatch/delivery hot-paths with few latency metrics, disabled by default to have zero runtime impact.
> perf(broker): try to minimize number of subscriber shards

- apps/emqx/test/emqx_hooks_SUITE.erl
`end_per_testcase` was not being called, and cases could crash randomly if the process didn't stop in time before the next case.
> test(hooks): fix wrong ct callback

- apps/emqx/include/emqx.hrl
- apps/emqx/src/emqx.erl
- apps/emqx/src/emqx_app.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_config_handler.erl
- apps/emqx/src/emqx_corrupt_namespace_config_checker.erl
- apps/emqx/src/emqx_sys_sup.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx/test/emqx_config_handler_SUITE.erl
- apps/emqx/test/emqx_cth_cluster.erl
- apps/emqx/test/emqx_cth_suite.erl
- apps/emqx/test/emqx_tls_certfile_gc_SUITE.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz.erl
- apps/emqx_bridge_s3/src/emqx_bridge_s3.erl
- apps/emqx_conf/src/emqx_conf_app.erl
- apps/emqx_conf/test/emqx_conf_cluster_sync_SUITE.erl
- apps/emqx_conf/test/emqx_global_gc_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_cm_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_cm_registry_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_metrics_SUITE.erl
- apps/emqx_mt/src/emqx_mt_hookcb.erl
- apps/emqx_mt/test/emqx_mt_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14389
In order to support per-namespace user roles with scoped resources and permissions, we'll need to store namespaced configurations in mnesia.  Mnesia was chosen because we want to avoid generating large or multiple `cluster.hocon` files as the number of namespaces and their configs might be large.
Here, in order to persist the config changes in mnesia, one calls `emqx:update_config(KeyPath, Req, #{namespace => Namespace, ...}).`, where `Namespace` is the binary name for the namespace.  This config will use the existing `emqx_config_handler` machinery (i.e., type check, call pre/post config update hooks), but read and write configs to mnesia instead of persistent term and/or `cluster.hocon`.
Later, for this milestone, …
> feat(config handler): allow saving namespaced configs in mnesia

- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_broker_sup.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_stats.erl
- apps/emqx/test/emqx_broker_SUITE.erl
- apps/emqx/test/emqx_config_SUITE.erl
- rel/i18n/emqx_schema.hocon
Part of EMQX-14333.
Release version: 6.0?
On top of #15407.
Add feature flag that enables dispatching of subscriber shards through the broker pool. This feature is hidden and disabled by default.
* Impact on high-fanout performance varies, see [report](https://emqx.atlassian.net/wiki/spaces/HOTPOT/pages/1815413979/In-mem+Fanout+Performance).
* No decisive negative impact on 1-to-1 performance, however it proved to be very hard to measure. Work in progress.
> feat(broker): allow async shard dispatch through broker pool

- .github/workflows/bump-dashboard-version.yaml
release-60 is higher than release-510.
Logic: take first 2 digits, add '.' between them, and use this as a primary sorting key. Then also sort on full release branch name.
> ci: fix base branch detection in bump dashboard version workflow

- apps/emqx_bridge_s3tables/test/emqx_bridge_s3tables_SUITE.erl
Even though now the retry/restart workarounds seem to be working properly, this test case is still very flaky and may fail 5 times in a row in CI.  I believe we have a net gain disabling it, even though we'll stop testing this very particular scenario.
e.g.:
https://github.com/emqx/emqx/actions/runs/16274083953/job/45949204895?pr=15490
> test(s3tables): disable flaky scenario

- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_broker_helper.erl
- apps/emqx/src/emqx_broker_sup.erl
- apps/emqx/src/emqx_router_helper.erl
- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx/test/emqx_router_helper_SUITE.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- changes/ee/fix-15518.en.md
Fixes [EMQX-14477](https://emqx.atlassian.net/browse/EMQX-14477).
Release version: 6.0.0-M1.202507
Prior to these changes, multiple EMQX nodes could in general react simultaneously to a single shared subscriber going down. If, due to load skew, remote node reacted to this event earlier than local node, leftover state started to accumulate. This would have eventually manifested in global routing table inconsistencies.
This PR changes `emqx_shared_sub` such that there's no monitoring of subscribers anymore. Local node is the only node responsible for cleaning up after local subscribers going down, as signaled by `emqx_broker_helper` that is now the component responsible for monitoring subcribers. In case whole node goes down, responsibility for cleaning up is shifted to `emqx_router_helper` …
> fix(shared-sub): stop monitoring remote subscribers to avoid races

- apps/emqx_ds_builtin_raft/test/emqx_ds_builtin_raft_SUITE.erl
These two test cases (`t_rebalance`, `t_crash_restart_recover`) have been failing a lot in CI.
Having a proper fix for the cause of their flakiness is obviously the ideal correct solution.  However, until that happens, we could reduce the time that is wasted re-running CI by retrying only them a bit instead of the whole workflow run, which is quite slow.
Ex: https://github.com/emqx/emqx/actions/runs/16377217654/job/46282627060#step:5:5939
> test(raft): mark test cases as flaky

- apps/emqx_bridge_dynamo/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kinesis/rebar.config
- apps/emqx_s3/rebar.config
- changes/ee/feat-15542.en.md
- mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-14526
Mainly to get https://github.com/erlcloud/erlcloud/pull/755
Allows using S3 connector without specifying access key id & secret access key
https://github.com/user-attachments/assets/26dbcd20-e3a1-4145-83dc-9e56e833a561
> chore: bump erlcloud -> 3.8.3.0

- .github/workflows/_pr_entrypoint.yaml
- .github/workflows/run_helm_tests.yaml
- changes/ee/fix-15553.en.md
- deploy/charts/emqx-enterprise/values.yaml
- deploy/charts/emqx/values.yaml
clustered setup requires a license
Fixes an issue when all nodes except one will be crashing if a user deployes helm chart as is.
Release version: 5.9.2, 5.10.1, 6.0.0-M2.202508, 6.0.0
> use single replica by default in helm chart

- apps/emqx/src/emqx_congestion.erl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_frame.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_quic_data_stream.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_socket_connection.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_client_SUITE.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx/test/emqx_cth_broker.erl
- apps/emqx/test/emqx_cth_listener.erl
- apps/emqx/test/emqx_frame_SUITE.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx/test/emqx_listeners_update_SUITE.erl
- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- apps/emqx/test/emqx_mqtt_test_client.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- apps/emqx_eviction_agent/mix.exs
- apps/emqx_eviction_agent/src/emqx_eviction_agent.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- apps/emqx_telemetry/test/emqx_telemetry_SUITE.erl
- changes/ee/perf-15451.en.md
- mix.exs
- rel/i18n/emqx_schema.hocon
Part of EMQX-14333.
This PR introduces `tcp_backend` listener option, exclusively to TCP listeners, and employs emqx/esockd#204 with a separate connection module named `emqx_socket_connection` when `tcp_backend` is `socket`. This shows consistently better wide-fanout performance, especially when combined with async shard dispatch introduced in emqx/emqx#15421, see [report](https://emqx.atlassian.net/wiki/spaces/HOTPOT/pages/1815413979/In-mem+Fanout+Performance).
This new connection module is identical to `emqx_connection` module in most of aspects, but made separate primarily because of:
* Socket-based connections use substantially different connection loop, and integrating it into `emqx_connection` might have made the latter too bloated, harder to test and reason …
> feat(socket): implement `esockd_socket` connection module

- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx/src/emqx_trace/emqx_trace_handler.erl
- apps/emqx/test/emqx_trace_SUITE.erl
- apps/emqx/test/emqx_trace_handler_SUITE.erl
- changes/ee/feat-15556.en.md
- rel/i18n/emqx_schema.hocon
Fixes [EMQX-14467](https://emqx.atlassian.net/browse/EMQX-14467).
This PR exposes trace file size limit as a configuration option, with 512 MiB preserved as a default.
Now that it's possible for the user to set much lower limits, risk of hitting this limit is increased. Currently, because tracing is implemented on top of `logger` subsystem components, there's no direct feedback: active trace does not know that the limit is hit. Instead, messages like these are printed to stdout / stderr:
```
Logger - error: {disk_log,'trace_topic_CLI-trace_max_file_size','trace_topic_CLI-trace_max_file_size',full}
Logger - error: {'trace_topic_CLI-trace_max_file_size',log,#{type=>halt,file=>"tmp/trace_max_file_size.log",max_no_bytes=>5120,max_no_files=>undefined},{error,{full,'trace_ …
```
> feat(trace): expose max trace file size limit as config option

- .ci/docker-compose-file/docker-compose-kdc.yaml
- .ci/docker-compose-file/docker-compose.yaml
- .github/workflows/build_packages.yaml
- .tool-versions
- apps/emqx_auth_ext/test/emqx_auth_ext_listener_tls_verify_keyusage_SUITE.erl
- changes/ee/fix-15581.en.md
- deploy/docker/Dockerfile
- env.sh
- scripts/buildx.sh
Fixies the issue reported in a discussion: https://github.com/emqx/emqx/discussions/14924
5.8.7
> ci: bump OTP version to 26.2.5.14-1

- scripts/elvis-check.sh
- scripts/elvis-check1.sh
On a particular branch with 68 changed files:
Serial execution:
```
ͳ time scripts/elvis-check.sh release-60
scripts/elvis-check.sh release-60  89.40s user 17.57s system 348% cpu 30.702 total
```
Parallel execution:
```
ͳ time scripts/elvis-check.sh release-60
scripts/elvis-check.sh release-60  74.21s user 15.78s system 1202% cpu 7.486 total
```
> ci: parallelize elvis check if gnu parallel is available

- apps/emqx_mix_utils/lib/mix/tasks/emqx.ct.ex
Without this change, Elixir's `Logger` silences [crash](https://github.com/elixir-lang/elixir/blob/7b20c281d521aa7aa2ad2baa1e9ae6c579d79d0c/lib/logger/lib/logger/utils.ex#L8) and [supervisor](https://github.com/elixir-lang/elixir/blob/7b20c281d521aa7aa2ad2baa1e9ae6c579d79d0c/lib/logger/lib/logger/utils.ex#L9) reports, which makes debugging efforts a bit more cumbersome.
> chore(mix): ensure crash reports are visible in CT logs

- apps/emqx/include/emqx_trace.hrl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx/src/emqx_trace/emqx_trace_dl.erl
- apps/emqx/src/emqx_trace/emqx_trace_freelist.erl
- apps/emqx/src/emqx_trace/emqx_trace_handler.erl
- apps/emqx/test/emqx_trace_SUITE.erl
- apps/emqx/test/emqx_trace_handler_SUITE.erl
- apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_trace.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
- changes/ee/feat-15594.en.md
- rel/i18n/emqx_schema.hocon
Fixes [EMQX-14467](https://emqx.atlassian.net/browse/EMQX-14467).
This PR also includes:
* Refactoring effort to make core, data layer and API concerns slightly better separated into their own modules.
* Attempt to avoid unconstrained atom creation through reusing integer "slots" for `logger`-level handler IDs.
Notably, the latter _does not_ cover Traces CLI.
[EMQX-14467]: https://emqx.atlassian.net/browse/EMQX-14467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(trace): expose "max number of traces" as config option

- apps/emqx_bridge_snowflake/docs/user-guide.md
- apps/emqx_bridge_snowflake/mix.exs
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake.hrl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_aggregated_action_info.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_aggregated_action_schema.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_aggregated_connector_info.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_aggregated_connector_schema.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_aggregated_impl.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_channel_client.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_lib.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_streaming_action_info.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_streaming_action_schema.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_streaming_connector_info.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_streaming_connector_schema.erl
- apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_streaming_impl.erl
- apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_aggregated_SUITE.erl
- apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_streaming_SUITE.erl
- apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_tests.erl
- apps/emqx_conf/src/emqx_conf_schema_inject.erl
- apps/emqx_gen_bridge/src/emqx_action_info.erl
- apps/emqx_gen_bridge/src/emqx_connector_info.erl
- apps/emqx_s3/test/emqx_s3_profile_conf_SUITE.erl
- rel/i18n/emqx_bridge_snowflake_aggregated_action_schema.hocon
- rel/i18n/emqx_bridge_snowflake_aggregated_connector_schema.hocon
- rel/i18n/emqx_bridge_snowflake_streaming_action_schema.hocon
- rel/i18n/emqx_bridge_snowflake_streaming_connector_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14523
The new Snowflake Snowpipe Streaming APIs do not require ODBC connections, which simplify the setup required to use Snowflake integration.  Since the connection is so different from the aggregated mode from existing integration, it's cleaner to make a new connector type than to graft streaming as an Action mode onto the old connector.
The previously added Streaming Action mode was only released in 6.0.0-M1, an internal release.  So, although this is a breaking schema change (we're dropping `mode = streaming` from `snowflake` Action type), it should be fine, as it's not publicly released.
A couple common functions used in both connectors are moved to `emqx_bridge_snowflake_lib` for shared usage.
- [na] …
> feat(snowflake): detach streaming mode to separate connector type

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- changes/ee/fix-15616.en.md
Port https://github.com/emqx/emqx/pull/15116 to 5.8
> fix(kafka): allow topic_authorization_failed for probing topic

- changes/ee/feat-15594.en.md
Part of [EMQX-14467](https://emqx.atlassian.net/browse/EMQX-14467).
Corrects changelog entry wording.
[EMQX-14467]: https://emqx.atlassian.net/browse/EMQX-14467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: correct changelog entry wording

- apps/emqx/test/emqx_shared_sub_SUITE.erl
https://github.com/emqx/emqx/actions/runs/16756740480/job/47441963112?pr=15629#step:5:127
```
%%% emqx_shared_sub_SUITE ==> t_session_takeover: FAILED
%%% emqx_shared_sub_SUITE ==> {{badmatch,<<"not yet?">>},
[{emqx_shared_sub_SUITE,t_session_takeover,1,
[{file,"test/emqx_shared_sub_SUITE.erl"},{line,974}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]}
```
> test(shared sub): attempt to stabilize flaky test

- apps/emqx_mix_utils/lib/mix/tasks/emqx.ct.ex
Fixes [EMQX-14568](https://emqx.atlassian.net/browse/EMQX-14568)
Add `--repeat` option to `mix ct` task.
[EMQX-14568]: https://emqx.atlassian.net/browse/EMQX-14568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(mix): Add --repeat option to `ct` task

- apps/emqx/include/emqx_metrics.hrl
- apps/emqx/src/emqx_metrics.erl
- apps/emqx/test/emqx_metrics_SUITE.erl
- changes/ce/fix-15639.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14455
Release version: e5.8.8
- ~Schema changes are backward compatible or intentionally breaking (describe the changes and the reasoning in the summary)~
> Fix incorrect counting of the packets.subscribe.auth_error metric.

- apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl
- apps/emqx_postgresql/src/emqx_postgresql.erl
- changes/ee/fix-15693.en.md
Possibly fixes https://emqx.atlassian.net/browse/EMQX-14600
I could not reproduce the problem locally.  I suspect it might have been some kind of race while starting the pool, and the `close_connections` functions might have crashed or was not called.
> fix(postgres): use allocation apis to avoid leaking resource pool

- apps/emqx_conf/src/emqx_conf_app.erl
Only when syncing a recent change to `release-60` it was detected that the exit code when config fails to load is 0.
See:
- https://github.com/emqx/emqx/pull/15729
- https://github.com/emqx/emqx/actions/runs/17050064723/job/48336139780?pr=15729#step:7:11
> fix(conf app): return exit code 1 when config fails to load

- apps/emqx/src/emqx_channel.erl
- apps/emqx_auth/src/emqx_authn/emqx_authn_utils.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_chains_SUITE.erl
- apps/emqx_auth/test/emqx_authn/emqx_authn_test_lib.erl
- apps/emqx_auth_http/src/emqx_authn_http.erl
- apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl
- apps/emqx_auth_jwt/src/emqx_authn_jwt.erl
- apps/emqx_auth_jwt/test/emqx_authn_jwt_SUITE.erl
- apps/emqx_auth_ldap/src/emqx_authn_ldap_bind.erl
- apps/emqx_auth_ldap/src/emqx_authn_ldap_hash.erl
- apps/emqx_auth_ldap/src/emqx_authn_ldap_schema.erl
- apps/emqx_auth_ldap/test/emqx_authn_ldap_SUITE.erl
- apps/emqx_auth_ldap/test/emqx_authn_ldap_bind_SUITE.erl
- apps/emqx_auth_mongodb/src/emqx_authn_mongodb.erl
- apps/emqx_auth_mongodb/src/emqx_authn_mongodb_schema.erl
- apps/emqx_auth_mongodb/test/emqx_authn_mongodb_SUITE.erl
- apps/emqx_auth_mysql/src/emqx_authn_mysql.erl
- apps/emqx_auth_mysql/test/emqx_authn_mysql_SUITE.erl
- apps/emqx_auth_postgresql/src/emqx_authn_postgresql.erl
- apps/emqx_auth_postgresql/test/emqx_authn_postgresql_SUITE.erl
- apps/emqx_auth_redis/src/emqx_authn_redis.erl
- apps/emqx_auth_redis/test/emqx_authn_redis_SUITE.erl
- apps/emqx_ldap/test/data/emqx.io.ldif
- apps/emqx_ldap/test/data/emqx.schema
- changes/ee/feat-15730.en.md
- rel/i18n/emqx_authn_ldap_schema.hocon
- rel/i18n/emqx_authn_mongodb_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14293
Backends/methods supporting returning `clientid_override` in the successful authentication result to override clientid:
- HTTP
- JWT
- LDAP
- MongoDB
- MySQL
- Postgres
- Redis
> feat: support specifying `clientid_override` in authn results

- apps/emqx/src/emqx_limiter/src/emqx_limiter.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter_exclusive.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter_shared/emqx_limiter_shared.erl
- apps/emqx/test/emqx_limiter_exclusive_SUITE.erl
- apps/emqx/test/emqx_limiter_shared_SUITE.erl
- apps/emqx_mt/src/emqx_mt.app.src
- apps/emqx_mt/src/emqx_mt_limiter.erl
- changes/ee/breaking-15753.en.md
Fixes [EMQX-14614](https://emqx.atlassian.net/browse/EMQX-14614).
Release version: 5.9.2
This PR switches listeners to use a single shared connrate limiter per listener instead of an exclusive limiter per acceptor, thus restoring pre-5.9 behavior and config compatibility.
Backport of #15743 + #15718 + #15731.
Tests are excluded from backporting to avoid conflicts down the line. See #15743 for relevant testcases and their results.
[EMQX-14614]: https://emqx.atlassian.net/browse/EMQX-14614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(listener): switch to shared per-listener connrate limiters [r59]

- apps/emqx/src/emqx_limiter/src/emqx_limiter.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter_exclusive.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter_shared/emqx_limiter_shared.erl
- apps/emqx/test/emqx_limiter_exclusive_SUITE.erl
- apps/emqx/test/emqx_limiter_shared_SUITE.erl
- apps/emqx_mt/src/emqx_mt_limiter.erl
- changes/ee/breaking-15752.en.md
Fixes [EMQX-14614](https://emqx.atlassian.net/browse/EMQX-14614).
This PR switches listeners to use a single shared connrate limiter per listener instead of an exclusive limiter per acceptor, thus restoring pre-5.9 behavior and config compatibility.
Backport of #15743 + #15718 + #15731.
Tests are excluded from backporting to avoid conflicts down the line. See #15743 for relevant testcases and their results.
[EMQX-14614]: https://emqx.atlassian.net/browse/EMQX-14614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(listener): switch to shared per-listener connrate limiters [r510]

- apps/emqx/rebar.config
- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/src/emqx_cm_registry.erl
- apps/emqx/src/emqx_reason_codes.erl
- apps/emqx/test/emqx_cm_SUITE.erl
- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx/test/emqx_takeover_SUITE.erl
- apps/emqx_ft/test/emqx_ft_test_helpers.erl
- apps/emqx_retainer/rebar.config
- changes/ee/feat-15773.en.md
- mix.exs
- rebar.config
Fixes [EMQX-14648](https://emqx.atlassian.net/browse/EMQX-14648)
Throttle client ID registration during reconnects
Added throttling for client ID registration if the previous session cleanup is still in progress.
This prevents instability when clients reconnect aggressively with the same client ID.
Affected clients will receive reason code `137` (Server Busy) in `CONNACK` with Reason-String "THROTTLED".
Clients should retry after the previous session cleanup has completed.
Also fixed the reason code from `133` to `137` when there is another connection in the middle of registering the same client ID.
[EMQX-14648]: https://emqx.atlassian.net/browse/EMQX-14648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 250525 Throttle client ID registration

- apps/emqx_eviction_agent/test/emqx_eviction_agent_channel_SUITE.erl
The test become flaky after the client ID registration throttling.
> test: use per test case client ID

- apps/emqx/test/emqx_cm_SUITE.erl
>  https://github.com/emqx/emqx/actions/runs/17296676220/job/49097601680?pr=15783#step:5:88
Backport of #15792.
> test(cm): construct realistic conninfo with `expiry_interval` set [r58]

- apps/emqx/src/emqx_limiter/src/emqx_limiter.erl
- apps/emqx/src/emqx_limiter/src/emqx_limiter_shared/emqx_limiter_shared.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_limiter_SUITE.erl
- apps/emqx/test/emqx_listeners_limits_SUITE.erl
- changes/ee/fix-15783.en.md
Fixes [EMQX-14615](https://emqx.atlassian.net/browse/EMQX-14615).
This PR changes how listener configuration updates are handled when rate limits are changed: any changes to connection rate limits take effect as soon as listener update is complete.
[EMQX-14615]: https://emqx.atlassian.net/browse/EMQX-14615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(limiter): reset shared limiter buckets on update

- apps/emqx_gateway_ocpp/src/emqx_gateway_ocpp.app.src
- apps/emqx_gateway_ocpp/src/emqx_ocpp_connection.erl
- apps/emqx_gateway_ocpp/test/emqx_ocpp_SUITE.erl
- changes/ee/fix-15822.en.md
Fixes the follow crash logs
```
clientid: VN001001, peername: 36.43.27.143:35587, pid: <0.31957511.0>, line: 948, domain: ["otp","sasl"], error_logger: {"type":"crash_report","tag":"error_report"}, logger_formatter: {"title":"CRASH REPORT"}, msg: crasher: initial call: cowboy_clear:connection_process/4, pid: <0.31957511.0>, registered_name: [], error: {{badmatch,889},[{emqx_ocpp_connection,handle_outgoing,2,[{file,"emqx_ocpp_connection.erl"},{line,682}]},{emqx_ocpp_connection,websocket_info,2,[{file,"emqx_ocpp_connection.erl"},{line,821}]},{cowboy_websocket_linger,handler_call,6,[{file,"cowboy_websocket_linger.erl"},{line,582}]},{cowboy_http,loop,1,[{file,"cowboy_http.erl"},{line,279}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,329}]}]}, ancestors: …
```
> chore(ocpp): Fix conns crashs on reached the active_n

- .tool-versions
- apps/emqx/src/emqx_access_control.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_channel_SUITE.erl
- apps/emqx/test/emqx_cth_suite.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_file_SUITE.erl
- apps/emqx_auth_mnesia/test/emqx_authz_api_mnesia_SUITE.erl
- apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_SUITE.erl
- apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_api_SUITE.erl
- apps/emqx_ft/test/emqx_ft_SUITE.erl
- apps/emqx_ft/test/emqx_ft_request_SUITE.erl
- changes/ee/feat-15820.en.md
Fixes [EMQX-14667](https://emqx.atlassian.net/browse/EMQX-14667)
This PR changes the default config value for `authorization.no_match` from `allow` to `deny` for more secure defaults.
[EMQX-14667]: https://emqx.atlassian.net/browse/EMQX-14667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change authz `no_match` action default value to `deny`

- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_schema_tests.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl
- changes/ee/feat-15845.en.md
- rel/i18n/emqx_bridge_mqtt_connector_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14679
Release version: 5.8.9
Some servers require unique usernames for each clientid, hence the need to change the previous simple clientid into a clientid & username & password tuple.
> feat(mqtt connector): add static clientid & username & password tuples

- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- changes/ee/fix-15866.en.md
- mix.exs
Fixes [EEC-1237](https://emqx.atlassian.net/browse/EEC-1237)
Release version: 5.8.9/5.9.2/5.10.1
Upgrade Kafka producer lib wollf to 4.0.12 to improve handling of temporarily missing partitions in Kafka metadata responses.
In rare race conditions, Kafka may return an incomplete partition list.
Previously, this was only handled when a topic was recreated with fewer partitions, but not when partitions were temporarily missing.
This gap could cause the partition producer to stall and block shutdown indefinitely.
[EEC-1237]: https://emqx.atlassian.net/browse/EEC-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(kafka): upgrade Kafka producer lib to wolff-4.0.12

- apps/emqx_mix_utils/lib/mix/tasks/emqx.cover.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.ct.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.dialyzer.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.eunit.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.proper.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.static_checks.ex
- apps/emqx_mix_utils/lib/mix/tasks/emqx.xref.ex
So we can detect call errors more readily.
> ci(mix): make args parsing stricter

- apps/emqx_mq/src/emqx_mq_registry.erl
- apps/emqx_mq/test/emqx_mq_api_SUITE.erl
Fixes [EMQX-14692](https://emqx.atlassian.net/browse/EMQX-14692)
[EMQX-14692]: https://emqx.atlassian.net/browse/EMQX-14692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(mq): do not show hasnext on the last page of MQ list in API

- apps/emqx/src/emqx_frame.erl
- apps/emqx/src/emqx_listeners.erl
- changes/ee/perf-15907.en.md
Fixes [EMQX-14702](https://emqx.atlassian.net/browse/EMQX-14702) [EMQX-14703](https://emqx.atlassian.net/browse/EMQX-14703)
For 5.8.9 5.9.2: https://github.com/emqx/emqx/pull/15899 and https://github.com/emqx/emqx/pull/15900
Release version: 5.10.1 6.0.0
[EMQX-14702]: https://emqx.atlassian.net/browse/EMQX-14702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-14703]: https://emqx.atlassian.net/browse/EMQX-14703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 250912 perf optimize ram usage for r510

- apps/emqx/rebar.config
- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_broker_helper.erl
- apps/emqx/src/emqx_broker_sup.erl
- apps/emqx/src/emqx_router.erl
- apps/emqx/src/emqx_router_helper.erl
- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx/test/emqx_router_helper_SUITE.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- changes/ce/fix-15884.en.md
- mix.exs
- rebar.config
Fixes [EMQX-14718](https://emqx.atlassian.net/browse/EMQX-14718).
Release version: 5.8.9
Backports of #14936 + #15396 + #15518.
[EMQX-14477]: https://emqx.atlassian.net/browse/EMQX-14477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-14718]: https://emqx.atlassian.net/browse/EMQX-14718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(shared-sub): stop monitoring remote subscribers to avoid races [r58]

- .ci/docker-compose-file/docker-compose-kdc.yaml
- .ci/docker-compose-file/docker-compose.yaml
- .github/workflows/build_packages.yaml
- deploy/docker/Dockerfile
- env.sh
Release version: 5.8.9, 5.9.2, 6.0.0
See emqx/emqx-builder#138 and emqx/rebar3#24.
`emqx-builder:5.6-2` contains fix for OTP 27 and patch for rebar3 to fix an issue when fetching dependencies over SSL on CentOS7
> build: bump emqx-builder version to 5.6-2

- apps/emqx/src/emqx_frame.erl
- changes/ee/perf-15907.en.md
Fixes [EMQX-14703](https://emqx.atlassian.net/browse/EMQX-14703)
Ported from r510 PR: https://github.com/emqx/emqx/pull/15907
Release version: 5.9.2
Previously, UTF-8 fields parsed from MQTT packets (e.g. client ID, username, password, and especially topic) were sub-binaries of the original packet buffer. Because these values may live as long as the session (e.g. stored in caches), the entire packet binary could be kept alive unnecessarily, leading to excessive RAM usage.
This change ensures all parsed UTF-8 strings are copied into standalone binaries, allowing the original packet binary to be released promptly.
In dev environment, I tested with **10,000 clients**, each publishing once per second to a randomized (fixed-length) topic
with QoS 0.
- **Before patch**  
- beam.smp RES: ~3.2 GB …
> [r59] perf: copy strings to avoid retaining large packet binaries

- apps/emqx/src/config/emqx_config_zones.erl
- apps/emqx/src/emqx_frame.erl
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx/test/emqx_listeners_update_SUITE.erl
- apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl
- changes/ee/perf-15949.en.md
- rel/i18n/emqx_schema.hocon
Release version: 5.9.2, 5.10.2
The config was introduced since 5.9.
In a recent load test, with 64KB payload, with `parse_unit=frame`, CPU 40%; with `parse_unit=chunk`, CPU 70%
> chore: enable inet driver mqtt packet frame parser by default

- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_meta.erl
- apps/emqx_management/src/emqx_mgmt_api_ds.erl
- apps/emqx_management/test/emqx_mgmt_api_ds_SUITE.erl
Part of [EMQX-14740](https://emqx.atlassian.net/browse/EMQX-14740).
This PR exposes _forget site_ operation in DS API (in addition to CLI), to give `emqx-operator` more control over DS sites.
[EMQX-14740]: https://emqx.atlassian.net/browse/EMQX-14740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): expose "forget site" operation in DS API

- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_SUITE.erl
- apps/emqx_mt/src/emqx_mt_api.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14728
Fixes https://emqx.atlassian.net/browse/EMQX-14736
The wrong config update function was being used: it was altering only the local node...
Also, made an improvement to resource manager: when adding channels, we now add a trigger for channel health check, instead of waiting for connector health check to run (which might take a long time, depending on configuration) or manually kicking it off (like we do in `emqx_bridge_v2_api:wait_for_ready`).  This should improve feedback when importing configurations.
> fix(ns config): use cluster-wide config change when bulk importing configs

- .github/workflows/performance_test.yaml
Trigger performance test every night at 01:00 UTC, use packages from the latest run of `build_packages_cron.yaml`
> ci: run perf test nightly on cron packages

- changes/ee/fix-16025.en.md
- mix.exs
fixed mem leak of jq builtin function index
previously rules using jq function like '.keys | index("name")' would result in mem leak
> fix(jq): upgrade to 0.3.14

- apps/emqx/src/emqx_session.erl
- apps/emqx/src/emqx_session_mem.erl
- apps/emqx_mq/src/emqx_mq.erl
- apps/emqx_mq/src/emqx_mq_sub.erl
- apps/emqx_mq/src/emqx_mq_sub_registry.erl
- apps/emqx_mq/test/emqx_mq_durable_sessions_SUITE.erl
Fixes [EMQX-14770](https://emqx.atlassian.net/browse/EMQX-14770)
The original issue contains several symptoms of MQs not working properly with durable sessions. In the PR we disable MQs for such sessions.
The main commits are:
[f29e98ce8d01eb2f34fac920265b263059f854fa](https://github.com/emqx/emqx/pull/16038/commits/f29e98ce8d01eb2f34fac920265b263059f854fa) — here we ignore subscriptions to MQs for durable sessions. The reason is that durable sessions has little support for transient messages, e.g. it does not save them into the inflight buffer and passes a fake message to the deliver callback. So we are unable to ack Queue's messages.
[bf224f16802c9c2821b064cb283f828ea841966e](https://github.com/emqx/emqx/pull/16038/commits/bf224f16802c9c2821b064cb283f828ea841966e) …
> Disable MQs for durable sessions

- apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_db_sup.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_meta.erl
- apps/emqx_durable_storage/src/emqx_ds_optimistic_tx.erl
Part of
* [EMQX-14760](https://emqx.atlassian.net/browse/EMQX-14760)
* [EMQX-14766](https://emqx.atlassian.net/browse/EMQX-14766)
This PR:
* Moves responsibility for OTX leadership announcements to CBM implementations.
* Updates `emqx_ds_builtin_raft` to register OTX leaders under cluster-id-aware names, to make sure out-of-cluster nodes do not cause global name conflicts.
[EMQX-14760]: https://emqx.atlassian.net/browse/EMQX-14760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-14766]: https://emqx.atlassian.net/browse/EMQX-14766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ds-otx): make CBM responsible for locating OTX leaders

- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_db_lifecycle.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_db_sup.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_machine.erl
- apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_shard.erl
- changes/ee/feat-16040.en.md
Fixes [EMQX-14772](https://emqx.atlassian.net/browse/EMQX-14772).
[EMQX-14772]: https://emqx.atlassian.net/browse/EMQX-14772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dsraft): order shards to terminate in-parallel on DB shutdown

- mix.exs
See https://github.com/emqx/erlang-rocksdb/pull/45 and https://github.com/emqx/erlang-rocksdb/pull/48
Release version: 6.0.1, 6.1.0
> chore: bump `erlang-rocksdb` -> 1.8.0-emqx-10

- apps/emqx_resource/src/emqx_resource_manager.erl
The expected result type is `#{status := resource_status(), error := term()}`.
Release version: 5.8.9, 5.9.2, 5.10.2
> fix(resource manager): return consistent reply type when channel health check aborts (r58)

- apps/emqx/test/emqx_common_test_helpers.erl
I suspect the DB might not be ready, given this:
https://github.com/emqx/emqx/actions/runs/18204039165/job/51830843969?pr=16081#step:5:196
Also, managed to observe this locally, after asserting:
```
=== Location: [{emqx_common_test_helpers,start_cluster_ds,1589},
{test_server,ts_tc,1794},
{test_server,run_test_case_eval1,1391},
{test_server,run_test_case_eval,1235}]
=== === Reason: no match of right hand side value [{ok,timeout},{ok,timeout}]
in function  emqx_common_test_helpers:start_cluster_ds/3 (test/emqx_common_test_helpers.erl, line 1589)
in call from test_server:ts_tc/3 (test_server.erl, line 1794)
in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1391)
in call from test_server:run_test_case_eval/9 (test_server.erl, line 1235)
```
> test: assert ds readiness

- apps/emqx_mq/test/emqx_mq_test_utils.erl
https://github.com/emqx/emqx/actions/runs/18222744561/job/51887205034?pr=16088#step:5:89
```
%%% emqx_mq_cluster_SUITE ==> t_cluster_smoke: FAILED
%%% emqx_mq_cluster_SUITE ==> {{exception,
{badmatch,
{error,{failed_to_create_mq_state,{error,recoverable,leader_down}}}},
[{emqx_mq_test_utils,create_mq,1,
[{file,"test/emqx_mq_test_utils.erl"},{line,86}]}]},
[{erpc,call,5,[{file,"erpc.erl"},{line,1368}]},
{emqx_mq_cluster_SUITE,t_cluster_smoke,1,
[{file,"test/emqx_mq_cluster_SUITE.erl"},{line,59}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]}
```
> test: attempt to stabilize flaky helpers
