emqx/emqx

apps/emqx_s3/src/emqx_s3.app.src, apps/emqx_s3/src/emqx_s3_schema.erl
=> chore(s3): make schema fields with defaults optional

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12511
=> fix(client mgmt api): allow projecting `client_attrs` from client fields

apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.app.src, apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.erl, apps/emqx_bridge_mysql/src/emqx_bridge_mysql.app.src, apps/emqx_bridge_mysql/src/emqx_bridge_mysql.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12395
=> chore: change types of mysql and mongodb fields to `template()`

apps/emqx_eviction_agent/src/emqx_eviction_agent.app.src, apps/emqx_eviction_agent/src/emqx_eviction_agent.erl, apps/emqx_node_rebalance/src/emqx_node_rebalance.app.src, apps/emqx_node_rebalance/src/emqx_node_rebalance_purge.erl, apps/emqx_node_rebalance/test/emqx_node_rebalance_purge_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12405
=> feat: support purging durable sessions during cluster purge

apps/emqx_auth/src/emqx_authn/emqx_authn_api.erl, apps/emqx_auth/src/emqx_authz/emqx_authz_api_sources.erl, changes/ce/fix-13225.en.md
=> fix(auth): redact sensitive data for the authn/authz APIs

changes/ee/feat-13199.en.md
Addresses https://github.com/emqx/emqx/pull/13232#discussion_r1637889964
=> docs: minor changelog improvement

apps/emqx/src/emqx_schema.erl, apps/emqx_conf/src/emqx_conf_cli.erl, apps/emqx_management/src/emqx_mgmt_api_configs.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl, apps/emqx_modules/src/emqx_observer_cli.erl
Fixes https://emqx.atlassian.net/browse/EMQX-10950 https://emqx.atlassian.net/browse/EMQX-12004 https://emqx.atlassian.net/browse/EMQX-11686 https://emqx.atlassian.net/browse/EMQX-11122
=> fix: some minor bug fixes

apps/emqx_auth_mnesia/src/emqx_authz_api_mnesia.erl, apps/emqx_auth_mnesia/src/emqx_authz_mnesia_schema.erl, apps/emqx_auth_mnesia/test/emqx_authz_api_mnesia_SUITE.erl, changes/ce/fix-13196.en.md, rel/i18n/emqx_authz_mnesia_schema.hocon
=> fix(authz_mnesia): add a soft limit in the API for the length of ACL rules

apps/emqx_auth/src/emqx_auth.app.src, apps/emqx_auth/src/emqx_auth_utils.erl, apps/emqx_auth/src/emqx_authn/emqx_authn_utils.erl, apps/emqx_auth_http/src/emqx_authn_http.erl, apps/emqx_auth_http/src/emqx_authz_http.erl, apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl, apps/emqx_auth_http/test/emqx_authz_http_SUITE.erl, apps/emqx_bridge/src/emqx_bridge_resource.erl, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo.app.src, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl, apps/emqx_bridge_es/src/emqx_bridge_es.app.src, apps/emqx_bridge_es/src/emqx_bridge_es_connector.erl, apps/emqx_bridge_http/src/emqx_bridge_http.app.src, apps/emqx_bridge_http/src/emqx_bridge_http_action_info.erl, apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl, apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl, apps/emqx_bridge_http/test/emqx_bridge_http_connector_tests.erl, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, apps/emqx_connector/src/emqx_connector_resource.erl, apps/emqx_utils/rebar.config, apps/emqx_utils/src/emqx_utils.app.src, apps/emqx_utils/src/emqx_utils_uri.erl, changes/ce/fix-13273.en.md
Fixes [EMQX-12257](https://emqx.atlassian.net/browse/EMQX-12257)
Backport of https://github.com/emqx/emqx/pull/12971
[EMQX-12257]: https://emqx.atlassian.net/browse/EMQX-12257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(auth,http): improve URI handling

changes/ce/feat-13191.en.md
=> docs: add changelog for PR 13191

apps/emqx_message_transformation/src/emqx_message_transformation.app.src, apps/emqx_message_transformation/src/emqx_message_transformation.erl, apps/emqx_message_transformation/src/emqx_message_transformation_http_api.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl, apps/emqx_utils/src/emqx_variform.erl, rel/i18n/emqx_message_transformation_http_api.hocon
Follow up to https://github.com/emqx/emqx/pull/13199
Fixes https://emqx.atlassian.net/browse/EMQX-12517
=> feat(message transformation): implement dryrun endpoint

deploy/docker/README.md
=> docs(docker): sync README.md with the official image docs

apps/emqx_cluster_link/src/emqx_cluster_link_router_syncer.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_mgmt_data_backup_SUITE.erl
Fixes EMQX-12195 (followup fix)
=> cluster link conf backup

apps/emqx/include/emqx_release.hrl, apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb.app.src, apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb_connector.erl, apps/emqx_bridge_greptimedb/test/emqx_bridge_greptimedb_SUITE.erl, apps/emqx_conf/src/emqx_conf_schema_inject.erl, apps/emqx_resource/src/emqx_resource_manager.erl, apps/emqx_rule_engine/include/rule_engine.hrl, apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, changes/ce/fix-13290.en.md, deploy/charts/emqx/Chart.yaml, scripts/test/start-two-nodes-in-docker.sh
=> sync release-57 to master

apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
=> test: add more debug msg to flaky cluster_rpc SUITE

apps/emqx_management/src/emqx_mgmt_api_plugins.erl, apps/emqx_plugins/include/emqx_plugins.hrl, apps/emqx_plugins/src/emqx_plugins.erl, apps/emqx_plugins/test/emqx_plugins_SUITE.erl, apps/emqx_plugins/test/emqx_plugins_tests.erl
Fixes [EMQX-12452](https://emqx.atlassian.net/browse/EMQX-12452) [EMQX-12347](https://emqx.atlassian.net/browse/EMQX-12347)
- ~[ ] Schema changes are …
=> fix: mark fresh install to cp the default configuration file directly

apps/emqx_message_transformation/src/emqx_message_transformation.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12582
=> fix(message transformation): correctly read from user properties in context

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl
https://github.com/emqx/emqx/actions/runs/9614788348/job/26526973635?pr=13317#step:5:1463
```
%%% emqx_bridge_gcp_pubsub_consumer_SUITE ==> t_connection_down_before_starting: FAILED
%%% emqx_bridge_gcp_pubsub_consumer_SUITE ==> {{panic,
#{msg => "Unexpected result",
result =>
{run_stage_failed,error,
{assertMatch,
[{module,emqx_bridge_gcp_pubsub_consumer_SUITE},
{line,1451},
{expression,"health_check ( Config )"},
{pattern,"{ ok , connecting }"},
{value,{ok,disconnected}}]},
[{emqx_bridge_gcp_pubsub_consumer_SUITE,
'-t_connection_down_before_starting/1-fun-11-',4,
[{file,
"/emqx/apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl"},
{line,1451}]},
{emqx_bridge_gcp_pubsub_consumer_SUITE,
t_connection_down_before_starting,1,
[{file, …
```
=> test(gcp consumer): stabilize flaky test

apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
=> test(api-clients): refactor suite to isolate flakiness

Makefile, scripts/ui-tests/dashboard_test.py
=> chore(dashboard): bump dashboard version to v1.9.1 & e1.7.1

apps/emqx_utils/src/emqx_variform_bif.erl
Fixes [EMQX-12577](https://emqx.atlassian.net/browse/EMQX-12577)
[EMQX-12577]: https://emqx.atlassian.net/browse/EMQX-12577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: fix regex_extract function doc

apps/emqx/include/emqx_release.hrl, changes/e5.7.1.en.md, changes/v5.7.1.en.md, deploy/charts/emqx-enterprise/Chart.yaml, deploy/charts/emqx/Chart.yaml
=> 0626 release v5.7.1

apps/emqx_conf/src/emqx_conf.erl
```
Runtime terminating during boot ({{badmatch,{error,{already_loaded,wolff}}},[{emqx_conf,load,2,[{file,"emqx_conf.erl"},{line,167}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{emqx_conf,dump_schema,2,[{file,"emqx_conf.erl"},{line,150}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,746}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,494}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,136}]},{init,start_it,1,[]},{init,start_em,1,[]}]})
```
=> fix: don't crash if application is already loaded

.github/workflows/build_docker_for_test.yaml
=> ci: add debugging info when building for docker tests

apps/emqx_dashboard_sso/rebar.config, apps/emqx_dashboard_sso/src/emqx_dashboard_sso.app.src, apps/emqx_dashboard_sso/src/emqx_dashboard_sso.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_api.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_manager.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_api.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_session.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_saml.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_sup.erl, mix.exs, rel/i18n/emqx_dashboard_sso_oidc.hocon, rel/i18n/emqx_dashboard_sso_oidc_api.hocon, scripts/spellcheck/dicts/emqx.txt
=> feat(sso): add OIDC support 

apps/emqx/src/emqx_frame.erl, apps/emqx/test/emqx_frame_SUITE.erl, changes/ce/fix-13334.en.md
Fixes [EMQX-12500](https://emqx.atlassian.net/browse/EMQX-12500)
- ~[] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket~
- ~[] Schema changes are backward compatible~
- ~[] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)~
- ~[] Change log has been added to `changes/` dir for user-facing artifacts update~
[EMQX-12500]: https://emqx.atlassian.net/browse/EMQX-12500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mqtt): check password flag to respect protocol spec

scripts/ui-tests/docker-compose.yaml
=> ci: pin selenium docker image tag 1.0.0

apps/emqx_auth/src/emqx_auth.app.src, apps/emqx_auth/src/emqx_authz/emqx_authz.erl, apps/emqx_auth_http/test/emqx_authz_http_SUITE.erl, changes/ce/feat-13317.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12411
=> feat(authz): add `ignore` metric for each source type

apps/emqx_schema_registry/src/emqx_schema_registry.app.src, apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl, apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl, changes/ee/fix-13345.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-10958
=> fix(schema registry api): validate schema name when creating

apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl, apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
Relates to https://emqx.atlassian.net/browse/EMQX-10866
=> test(schema registry): add test asserting the behavior of empty message roundtrip

apps/emqx_gateway/src/emqx_gateway_cm_registry.erl, apps/emqx_license/src/emqx_license.app.src, apps/emqx_license/src/emqx_license_resources.erl, changes/ee/fix-13372.en.md
=> fix: limit gateway connections with license

apps/emqx_rule_engine/src/emqx_rule_engine.app.src, apps/emqx_rule_engine/src/emqx_rule_events.erl, changes/ce/fix-13358.en.md
=> fix(events): fixed the reason format of the `authn_complete_event`

apps/emqx_bridge_rocketmq/test/emqx_bridge_rocketmq_SUITE.erl, apps/emqx_bridge_s3/src/emqx_bridge_s3.erl, apps/emqx_connector/src/emqx_connector.app.src, apps/emqx_connector/src/emqx_connector.erl, apps/emqx_connector/src/emqx_connector_ssl.erl, apps/emqx_connector/test/emqx_connector_api_SUITE.erl, apps/emqx_ft/test/emqx_ft_conf_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12581
=> fix(connector api): handle bad tls config file conversion errors

apps/emqx_message_transformation/src/emqx_message_transformation.app.src, apps/emqx_message_transformation/src/emqx_message_transformation.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl
Port of https://github.com/emqx/emqx/pull/13316
Fixes https://emqx.atlassian.net/browse/EMQX-12582
=> fix(message transformation): correctly read from user properties in context (r57)

apps/emqx_bridge_http/src/emqx_bridge_http.app.src, apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12622
=> fix(http action): use correct return value for channel health check

apps/emqx/src/config/emqx_config_logger.erl, apps/emqx/src/emqx_logger_jsonfmt.erl, apps/emqx/src/emqx_logger_textfmt.erl, apps/emqx/test/emqx_logger_fmt_SUITE.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_conf/test/emqx_conf_schema_tests.erl, changes/ce/feat-13348.en.md
=> feat(log): allows custom the encoding of payload in the log

apps/emqx_auth/etc/auth-built-in-db-bootstrap.csv, apps/emqx_auth/test/data/user-credentials-plain_v2.csv, apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl, apps/emqx_auth_mnesia/src/emqx_authn_mnesia_schema.erl, apps/emqx_auth_mnesia/test/emqx_authn_mnesia_SUITE.erl, rebar.config.erl, rel/i18n/emqx_authn_mnesia_schema.hocon
This PR is part of https://github.com/emqx/emqx/pull/13336
=> fix: don't override authn users when import_user from authn.boostrap_file

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl, apps/emqx_eviction_agent/test/emqx_eviction_agent_SUITE.erl
=> test: attempts to stabilize flaky tests

apps/emqx_schema_registry/src/emqx_schema_registry.erl, apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12603
=> fix(schema registry): avoid atom leak

apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_connection.erl, apps/emqx/src/emqx_quic_stream.erl, apps/emqx/src/emqx_ws_connection.erl, apps/emqx/test/emqx_connection_SUITE.erl, apps/emqx/test/emqx_cth_listener.erl, apps/emqx/test/emqx_peersni_SUITE.erl, apps/emqx/test/emqx_ws_connection_SUITE.erl, changes/ce/feat-13350.md
Fixes https://emqx.atlassian.net/browse/EMQX-12600
=> feat: support to extract the client peersni field to clientinfo

apps/emqx_auth/src/emqx_authz/emqx_authz.erl, apps/emqx_auth_mnesia/test/emqx_authz_mnesia_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12630
https://github.com/emqx/emqx/discussions/13385#discussioncomment-9941273
=> fix: don't destory when authz'source unchanged

apps/emqx_management/src/emqx_mgmt_auth.erl
=> fix(api_keys): improved the error message when bootstrapping api_key

apps/emqx_machine/src/emqx_machine.app.src, apps/emqx_machine/src/emqx_machine_boot.erl, apps/emqx_plugins/src/emqx_plugins.app.src, apps/emqx_plugins/src/emqx_plugins.erl, apps/emqx_plugins/src/emqx_plugins_app.erl, apps/emqx_plugins/test/emqx_plugins_SUITE.erl, changes/ce/fix-13393.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12628 
Fixes https://github.com/emqx/emqx/issues/13378
=> fix(plugins): ensure plugin apps are restarted when restarting `emqx_plugins`

apps/emqx_message_transformation/src/emqx_message_transformation.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12583
=> feat(message transformation): add more read-only fields to context

apps/emqx_bridge_s3/test/emqx_bridge_s3_aggreg_upload_SUITE.erl
=> test(bridge-s3): correct assertions to get rid of flakiness

apps/emqx/src/emqx_persistent_session_ds.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_state.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_stream_scheduler.erl
Fixes [EMQX-12611](https://emqx.atlassian.net/browse/EMQX-12611).
[EMQX-12611]: https://emqx.atlassian.net/browse/EMQX-12611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> perf(sessds): rotate through streams with iterators when fetching

apps/emqx/rebar.config, apps/emqx_bridge/test/emqx_bridge_SUITE.erl, apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl, apps/emqx_bridge/test/emqx_bridge_v1_compatibility_layer_SUITE.erl, apps/emqx_connector/test/emqx_connector_SUITE.erl, apps/emqx_connector/test/emqx_connector_api_SUITE.erl, changes/ce/fix-13403.en.md, mix.exs, rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-12641
Also fxies: https://github.com/emqx/emqx-operator/issues/1060
=> 0703 upgrade hocon 0.43.1

apps/emqx_bridge_pgsql/test/emqx_bridge_pgsql_SUITE.erl
```
%%% emqx_bridge_pgsql_SUITE ==> tcp.sync.with_batch.t_table_removed: FAILED
%%% emqx_bridge_pgsql_SUITE ==> {{panic,
#{msg => "Unexpected result",
result =>
{run_stage_failed,exit,
{test_case_failed,
"unexpected result: {error,{recoverable_error,sync_required}}"},
[{emqx_bridge_pgsql_SUITE,'-t_table_removed/1-fun-3-',3,
[{file,
"/emqx/apps/emqx_bridge_pgsql/test/emqx_bridge_pgsql_SUITE.erl"},
{line,822}]},
```
```
Error: -03T17:52:54.046809+00:00 [error] Generic server <0.352770.0> terminating. Reason: {'module could not be loaded',[{undefined,handle_message,[90,<<"I">>,{state,ssl,{sslsocket,{gen_tcp,#Port<0.1671>,tls_connection,undefined},[<0.352774.0>,<0.352773.0>]},<<>>,{336,-2093820527},on_message,{codec,#{},[null,undefined],{oid_db,#{16 =>
...
2024-07-03T17:52:54.075446+00:00 …
```
=> test(postgres bridge): attempt to stabilize flaky test

apps/emqx_bridge_azure_blob_storage/mix.exs, apps/emqx_bridge_azure_blob_storage/test/emqx_bridge_azure_blob_storage_SUITE.erl, apps/emqx_cluster_link/mix.exs, apps/emqx_ds_backends/mix.exs, apps/emqx_ds_builtin_local/mix.exs, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl, apps/emqx_ds_builtin_local/test/emqx_ds_builtin_local_SUITE.erl, apps/emqx_ds_builtin_raft/mix.exs, apps/emqx_ds_shared_sub/mix.exs, mix.exs
=> chore: add missing mix files to new apps

apps/emqx_auth/src/emqx_authz/emqx_authz_api_sources.erl, apps/emqx_auth/src/emqx_authz/emqx_authz_schema.erl, apps/emqx_auth_http/test/emqx_authz_http_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, rel/i18n/emqx_authz_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12411
=> fix(authz api): add new `ignore` metric to status response

apps/emqx/src/emqx_passwd.erl, apps/emqx/test/emqx_passwd_SUITE.erl, changes/ce/fix-13398.en.md, changes/ce/fix-13408.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-10237
```
2024-06-01T02:17:21.375514+00:00 [warning] msg: authenticator_error, mfa: emqx_authentication:do_authenticate/3, line: 687, peername: 10.42.0.0:61697, clientid: emqx_NzI4NT, authenticator: <<"password_based:mongodb">>, exception: error, reason: function_clause, stacktrace: [{emqx_passwd,hash,[{sha256,false,suffix},<<"public">>],[{file,"emqx_passwd.erl"},{line,85}]},{emqx_passwd,do_check_pass,3,[{file,"emqx_passwd.erl"},{line,81}]},{emqx_authn_mongodb,check_password,3,[{file,"emqx_authn_mongodb.erl"},{line,240}]},{emqx_authn_mongodb,authenticate,2,[{file,"emqx_authn_mongodb.erl"},{line,184}]},{emqx_authentication,authenticate_with_provider,2,[{file,"emqx_authentication.erl"},{line,698}]},{emqx_authentication,do_authenticate,3,[{file,"em …
```
=> chore: improve auth error for invalid salt/password type

apps/emqx_utils/src/emqx_utils.erl, apps/emqx_utils/test/emqx_utils_SUITE.erl, changes/ce/fix-13422.en.md, rel/i18n/emqx_schema.hocon
Fixes https://github.com/emqx/emqx/issues/13417
Fixes https://emqx.atlassian.net/browse/EMQX-12659
=> fix: handle `max_heap_size` = 0

apps/emqx/src/emqx_schema.erl, apps/emqx_conf/src/emqx_conf_cli.erl, apps/emqx_management/src/emqx_mgmt_api_configs.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl, apps/emqx_modules/src/emqx_modules.app.src, apps/emqx_modules/src/emqx_observer_cli.erl, changes/ce/fix-13419.en.md
Fixes Port from master https://github.com/emqx/emqx/pull/13236
=> Port: some minor bug fixes from master

apps/emqx_plugins/test/emqx_plugins_SUITE.erl
Hypothesis is that both peer nodes were using the same directory and stepping on each other's toes.
=> test(plugins): fix flaky test

apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl
=> fix(ds builtin local): use `-include_lib` instead of relative path

deploy/charts/emqx-enterprise/templates/StatefulSet.yaml, deploy/charts/emqx-enterprise/templates/ingress.yaml, deploy/charts/emqx-enterprise/values.yaml, deploy/charts/emqx/templates/ingress.yaml, deploy/charts/emqx/values.yaml
Fixes #13309
Note that the checklist does not apply as it is neither a change to emqx itself nor the CI
---
=> new(helm): websocket ingress (fixes #13309)

apps/emqx/src/emqx_ds_schema.erl, apps/emqx/test/emqx_cth_suite.erl, apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl, apps/emqx_ds_builtin_raft/README.md, apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl, apps/emqx_durable_storage/README.md, apps/emqx_durable_storage/asn.1/DurableMessage.asn, apps/emqx_durable_storage/dev/storage_efficiency.erl, apps/emqx_durable_storage/gen_src/.gitignore, apps/emqx_durable_storage/include/emqx_ds_metrics.hrl, apps/emqx_durable_storage/rebar.config, apps/emqx_durable_storage/src/emqx_ds_builtin_metrics.erl, apps/emqx_durable_storage/src/emqx_ds_lts.erl, apps/emqx_durable_storage/src/emqx_ds_msg_serializer.erl, apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl, apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl, apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl, apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl, apps/emqx_durable_storage/test/emqx_ds_storage_layout_SUITE.erl, apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl, apps/emqx_prometheus/src/emqx_prometheus.erl, changes/ce/feat-13370.en.md, rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-12536
=> New durable storage layout with explicit index for LTS wildcards

apps/emqx/src/emqx_schema.erl, apps/emqx_auth_jwt/src/emqx_authn_jwks_client.erl, apps/emqx_auth_jwt/src/emqx_authn_jwt_schema.erl, apps/emqx_auth_jwt/test/emqx_authn_jwt_SUITE.erl, changes/ce/feat-13436.en.md, rel/i18n/emqx_authn_jwt_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12655
=> feat(jwks): allow specifying custom request headers

changes/ee/breaking-13420.en.md
Fixes https://github.com/emqx/emqx/pull/13420#issuecomment-2213957235
=> docs: add breaking change entry

apps/emqx_ds_backends/rebar.config.script, apps/emqx_ds_backends/src/emqx_ds_backends.app.src.script
=> chore(ds): Support platform profile

apps/emqx/src/emqx_rpc.erl, apps/emqx_conf/src/emqx_conf_schema.erl, changes/feat-13434.en.md, rel/i18n/emqx_conf_schema.hocon
Fixes https://github.com/emqx/emqx/discussions/13410
also https://emqx.atlassian.net/browse/EMQX-12671
=> 0704 refine rpc config

apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_session.erl
=> fix(oidc): Avoid crashes and avoid deleting jwks on update

scripts/ui-tests/dashboard_test.py, scripts/ui-tests/docker-compose.yaml
Fixes (🤞 ) very flacky ui-tests
=> ci: fix dashboard tests (again)

apps/emqx_schema_registry/src/emqx_schema_registry.erl, apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12692
=> fix(schema registry): handle large names during lookup

apps/emqx/src/emqx_schema.erl
=> fix: do not convert a empty file name to a empty list

apps/emqx_resource/src/emqx_resource_manager.erl, changes/ce/fix-13442.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12674
=> fix(resource manager): disentangle connector and channel health check frequencies

apps/emqx/src/emqx_connection.erl
Optimize `emqx_connection:process_msg` function by making it tail-recursive. Here's before/after comparison of a fan-out load test scenario: https://snapshots.raintank.io/dashboard/snapshot/znG26ci1F48DVBJ53p1mEb45EDerkzLq
=> fix(connection): Make process_msg function tail-recursive

apps/emqx/rebar.config, apps/emqx_gateway/src/bhvrs/emqx_gateway_conn.erl, apps/emqx_gateway/src/emqx_gateway.app.src, apps/emqx_gateway/src/emqx_gateway_schema.erl, apps/emqx_gateway/src/emqx_gateway_utils.erl, apps/emqx_gateway/test/emqx_gateway_authn_SUITE.erl, apps/emqx_gateway/test/emqx_gateway_authz_SUITE.erl, apps/emqx_gateway_coap/src/emqx_coap_channel.erl, apps/emqx_gateway_coap/src/emqx_coap_proxy_conn.erl, apps/emqx_gateway_coap/src/emqx_gateway_coap.erl, apps/emqx_gateway_coap/test/emqx_coap_SUITE.erl, apps/emqx_gateway_coap/test/emqx_coap_api_SUITE.erl, changes/ce/perf-13441.en.md, mix.exs, rebar.config, rel/i18n/emqx_gateway_schema.hocon
=> feat(coap): use content-sensitive udp proxy for coap

apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_meta.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_shard.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_shard_allocator.erl, apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
Fixes [EMQX-12698](https://emqx.atlassian.net/browse/EMQX-12698).
[EMQX-12698]: https://emqx.atlassian.net/browse/EMQX-12698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dsraft): preserve pending replica set transitions

apps/emqx_message_transformation/src/emqx_message_transformation.erl, apps/emqx_message_transformation/src/emqx_message_transformation_schema.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl, apps/emqx_message_transformation/test/emqx_message_transformation_tests.erl, apps/emqx_rule_engine/src/emqx_rule_api_schema.erl, apps/emqx_rule_engine/src/emqx_rule_sqltester.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl, apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl, apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl, apps/emqx_utils/src/emqx_variform_scan.xrl, apps/emqx_utils/test/emqx_variform_tests.erl, rel/i18n/emqx_rule_api_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12683
Fixes https://emqx.atlassian.net/browse/EMQX-12684
Fixes https://emqx.atlassian.net/browse/EMQX-12678
Fixes https://emqx.atlassian.net/browse/EMQX-12682
Fixes https://emqx.atlassian.net/browse/EMQX-12679
Fixes https://emqx.atlassian.net/browse/EMQX-12677
=> batch of message transformation fixes

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_producer_SUITE.erl, changes/ee/feat-13463.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12625
=> feat(gcp pubsub producer): retry on 502 and 503 http status code responses

apps/emqx/src/emqx_config.erl, apps/emqx_cluster_link/test/emqx_cluster_link_config_SUITE.erl, apps/emqx_conf/include/emqx_conf.hrl, apps/emqx_conf/src/emqx_conf_cli.erl, apps/emqx_conf/test/emqx_conf_cli_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
=> fix: update cluster.links via cli

apps/emqx_ds_builtin_raft/src/emqx_ds_replication_shard_allocator.erl, apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
=> test(dsraft): attempt to stabilize flaky testcases

apps/emqx_machine/mix.exs
=> chore(new mix build): fix app dependency for release

apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl, apps/emqx_auth/src/emqx_authz/emqx_authz_utils.erl, apps/emqx_auth_mysql/src/emqx_auth_mysql.app.src, apps/emqx_auth_mysql/src/emqx_authz_mysql.erl, apps/emqx_auth_postgresql/src/emqx_auth_postgresql.app.src, apps/emqx_auth_postgresql/src/emqx_authz_postgresql.erl, apps/emqx_auth_redis/src/emqx_auth_redis.app.src, apps/emqx_auth_redis/src/emqx_authz_redis.erl
=> chore: add authz tag to match_rule_error log

apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl
Iterators:
Previously iterators used timestamp of the *next* message. This won't work well for the upcoming beamformer/beamsplitter feature that will group iterators according to their last seen key. This commit changes the logic so iterators store timestamp of the last seen message.
Cooked batches:
Cooked batches no longer store index entries. Creation of indexes has been delegated to commit callback.
=> fix(ds): Improve logic of skipstream LTS layout

apps/emqx_bridge/include/emqx_bridge_resource.hrl, apps/emqx_bridge/src/emqx_bridge_resource.erl, apps/emqx_bridge/src/emqx_bridge_v2_api.erl, apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl, apps/emqx_bridge_hstreamdb/test/emqx_bridge_hstreamdb_SUITE.erl, apps/emqx_connector/src/emqx_connector_api.erl, apps/emqx_connector/test/emqx_connector_api_SUITE.erl, apps/emqx_rule_engine/src/emqx_rule_engine.erl, changes/ce/feat-13492.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12654 (2/3 requirements)
=> feat: return dependent entities in connectors/actions/sources API

apps/emqx_connector/src/emqx_connector_jwt.erl, apps/emqx_connector/test/emqx_connector_jwt_SUITE.erl
=> fix(jwt): fix grace period for renewal check

apps/emqx_rule_engine/src/emqx_rule_engine_api.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl, changes/ce/feat-13505.en.md, rel/i18n/emqx_rule_engine_api.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12654 (requirement 2)
=> feat(rule engine api): add filters options for action and source ids

apps/emqx_rule_engine/src/emqx_rule_funcs.erl, apps/emqx_utils/src/emqx_variform_bif.erl, apps/emqx_utils/test/emqx_variform_bif_tests.erl, changes/ce/feat-13507.en.md
=> feat(variform): add a builtin function to get env vars

apps/emqx_management/src/emqx_mgmt_cli.erl, apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl, changes/ce/feat-13524.en.md
=> feat(exclusive): added CLI interface for exclusive topics

apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_api.erl
=> fix(oidc): fixed update and callback errors for OIDC

apps/emqx_rule_engine/src/emqx_rule_sqltester.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl, changes/ce/fix-13527.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12762
=> fix(rule engine tester): fix message publish with bridge source in from clause

apps/emqx_bridge_azure_event_hub/mix.exs, apps/emqx_bridge_azure_event_hub/rebar.config, apps/emqx_bridge_azure_event_hub/test/emqx_bridge_azure_event_hub_v2_SUITE.erl, apps/emqx_bridge_confluent/mix.exs, apps/emqx_bridge_confluent/rebar.config, apps/emqx_bridge_confluent/test/emqx_bridge_confluent_producer_SUITE.erl, apps/emqx_bridge_kafka/mix.exs, apps/emqx_bridge_kafka/rebar.config, apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_producer_action_info.erl, apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl, changes/ee/feat-13452.en.md, mix.exs, rel/i18n/emqx_bridge_azure_event_hub.hocon, rel/i18n/emqx_bridge_confluent_producer.hocon, rel/i18n/emqx_bridge_kafka.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12656
=> feat(kafka producer): allow dynamic topics (mkIII)

apps/emqx/include/logger.hrl, apps/emqx/src/emqx_log_throttler.erl, apps/emqx/test/emqx_log_throttler_SUITE.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_resource/include/emqx_resource.hrl, apps/emqx_resource/src/emqx_resource_buffer_worker.erl, changes/ce/feat-13528.en.md
takeover: https://github.com/emqx/emqx/pull/13482
=> 0726 unrecoverable error limit

.github/workflows/run_docker_tests.yaml, apps/emqx/test/emqx_cth_suite.erl, apps/emqx/test/emqx_persistent_messages_SUITE.erl, apps/emqx/test/emqx_routing_SUITE.erl, apps/emqx_auth/test/emqx_authz/emqx_authz_api_cluster_SUITE.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_conf/src/emqx_conf_schema_inject.erl, apps/emqx_conf/test/emqx_conf_app_SUITE.erl, apps/emqx_conf/test/emqx_conf_schema_tests.erl, apps/emqx_enterprise/src/emqx_enterprise.app.src, apps/emqx_enterprise/src/emqx_enterprise_schema.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_cluster_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl, apps/emqx_management/test/emqx_mgmt_data_backup_SUITE.erl, apps/emqx_opentelemetry/test/emqx_otel_trace_SUITE.erl, changes/ce/breaking-13526.en.md, rel/config/examples/node.conf.example
Fixes https://emqx.atlassian.net/browse/EMQX-12601
=> fix(mria): Reserve replicant role for EE only

apps/emqx_auth/src/emqx_authz/emqx_authz.erl, apps/emqx_auth/test/emqx_authz/emqx_authz_SUITE.erl, changes/ce/feat-13534.en.md
Fixes [EMQX-12778](https://emqx.atlassian.net/browse/EMQX-12778)
- ~[] Schema changes are backward compatible~
[EMQX-12778]: https://emqx.atlassian.net/browse/EMQX-12778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add authz skipped trace for superuser

apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
https://github.com/emqx/emqx/actions/runs/10161391242/job/28101183920#step:6:331
=> test(clients v2 api): attempt to reduce flakiness

apps/emqx/rebar.config
=> chore(emqx): Remove ra from the list of EMQX dependencies

apps/emqx_plugins/src/emqx_plugins.erl, changes/ce/feat-13548.en.md
Fixes [EMQX-12293](https://emqx.atlassian.net/browse/EMQX-12293)
[EMQX-12293]: https://emqx.atlassian.net/browse/EMQX-12293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> feat: call plugin's app module `on_config_changed/2` callback

apps/emqx_conf/src/emqx_conf_cli.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12587
=> fix(sessds): Expose durable sessions in the config API

apps/emqx_management/src/emqx_mgmt_api_ds.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12579
=> fix(mgmt): Return 404 for /ds/ API endpoints when DS is disabled

apps/emqx/src/emqx_listeners.erl, apps/emqx/src/emqx_tls_lib.erl, apps/emqx/test/emqx_crl_cache_SUITE.erl, changes/ce/fix-13541.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12785
=> fix(crl): force remove CRL fields from SSL opts after listener update

apps/emqx_schema_registry/include/emqx_schema_registry.hrl, apps/emqx_schema_registry/src/emqx_schema_registry.erl, apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl, apps/emqx_schema_registry/test/emqx_schema_registry_serde_SUITE.erl, changes/ee/fix-13543.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12789
=> fix(schema registry): clear protobuf code cache when deleting/updating serdes

apps/emqx/include/logger.hrl, apps/emqx/src/emqx_logger_jsonfmt.erl, apps/emqx/src/emqx_logger_textfmt.erl, apps/emqx/src/emqx_packet.erl, apps/emqx/src/emqx_trace/emqx_trace_formatter.erl, apps/emqx/src/emqx_ws_connection.erl, apps/emqx/test/emqx_packet_SUITE.erl
=> fix(log): respect payload encoding settings when formatting packets

apps/emqx/include/emqx_mqtt.hrl, apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_connection.erl, apps/emqx/src/emqx_frame.erl, apps/emqx/src/emqx_quic_connection.erl, apps/emqx/src/emqx_ws_connection.erl, apps/emqx/test/emqx_channel_SUITE.erl, apps/emqx/test/emqx_frame_SUITE.erl, changes/ce/fix-13357.en.md, elvis.config
Fixes [EMQX-12594](https://emqx.atlassian.net/browse/EMQX-12594)
[EMQX-12594]: https://emqx.atlassian.net/browse/EMQX-12594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: send CONNACK packet for MQTT-v5 clients

apps/emqx_management/src/emqx_mgmt_app.erl, apps/emqx_management/src/emqx_mgmt_auth.erl, apps/emqx_management/test/emqx_mgmt_api_api_keys_SUITE.erl
=> fix(api_key): do not crash boot when the bootstrap file is not exists

.github/workflows/build_packages_cron.yaml, .github/workflows/codeql.yaml, .github/workflows/green_master.yaml, apps/emqx/include/emqx_release.hrl, deploy/charts/emqx-enterprise/Chart.yaml, deploy/charts/emqx/Chart.yaml, scripts/rel/cut.sh, scripts/rel/sync-remotes.sh
We can ignore failing UI tests for now.
=> chore: prepare 5.8.0-alpha.1

apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_ingress.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_SUITE.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_subscriber_SUITE.erl, changes/ce/fix-13425.en.md
Fixes:
https://emqx.atlassian.net/browse/EMQX-12555
https://emqx.atlassian.net/browse/EMQX-12657
=> fix: make MQTT connector error log messages easier to understand

Makefile, scripts/ui-tests/dashboard_test.py
=> chore(dashboard): bump dashboard version to e1.7.2-beta.7

Makefile
=> chore(dashboard): bump dashboard version to v1.9.2 & e1.7.2

Makefile, scripts/ui-tests/dashboard_test.py
=> chore(dashboard): bump dashboard version to v1.10.0-beta.1 & e1.8.0-beta.1

apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
=> test: attempt to reduce test flakiness

apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.hrl, apps/emqx_durable_storage/src/emqx_ds.erl, apps/emqx_durable_storage/src/emqx_ds_buffer.erl, apps/emqx_durable_storage/src/emqx_ds_precondition.erl, apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl, apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl, apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl, apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl, apps/emqx_durable_storage/test/emqx_ds_storage_layout_SUITE.erl, apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl
Port of https://github.com/emqx/emqx/pull/13559 to `release-58`
=> feat(dsraft): support atomic batches + preconditions (release-58)

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_agent.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_group_sm.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader_rank_progress.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_proto.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_proto.hrl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_proto_format.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_registry.erl, apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_SUITE.erl
Fixes [EMQX-12806](https://emqx.atlassian.net/browse/EMQX-12806)
Release version: e5.8.0
- [na] Added tests for the changes
[EMQX-12806]: https://emqx.atlassian.net/browse/EMQX-12806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reduce size of shared sub protocol structures

apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_shard.erl, apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
=> fix(dsraft): use shard readiness as criterion for reads availability

apps/emqx_schema_registry/src/emqx_schema_registry.erl, apps/emqx_schema_registry/test/emqx_schema_registry_serde_SUITE.erl
=> test: reduce inter-case flakiness

apps/emqx/rebar.config, apps/emqx/src/emqx_config.erl, apps/emqx_rule_engine/src/emqx_rule_engine_api.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl, changes/ce/fix-13589.en.md, mix.exs, rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-12838
=> fix(rule engine api): check that user provided id is valid

apps/emqx_rule_engine/src/emqx_rule_events.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, changes/ce/feat-13573.en.md
=> feat(ruleengine): expose client_attrs to rule-engine

apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local_batch_serializer.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local_db_sup.erl, apps/emqx_durable_storage/src/emqx_ds.erl
Prerequisite for https://emqx.atlassian.net/browse/EMQX-12527
=> feat(ds builtin local): add basic support for atomic batches + preconditions

apps/emqx_message_transformation/src/emqx_message_transformation_schema.erl, rel/config/ee-examples/message-transformation.conf.example
=> docs: change message transformation 'enable' flag to no-doc

apps/emqx_rule_engine/src/emqx_rule_events.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, changes/ce/feat-13573.en.md
=> fix(ruleengine): adjusted the scope of `client_attrs` in the rule engine

apps/emqx_bridge/src/emqx_bridge_api.erl, apps/emqx_bridge/src/emqx_bridge_v2_api.erl, apps/emqx_cluster_link/src/emqx_cluster_link_api.erl, apps/emqx_cluster_link/test/emqx_cluster_link_api_SUITE.erl, apps/emqx_connector/src/emqx_connector_api.erl, apps/emqx_utils/src/emqx_utils_maps.erl
Fixes [EMQX-12851](https://emqx.atlassian.net/browse/EMQX-12851)
Fixes [EMQX-12854](https://emqx.atlassian.net/browse/EMQX-12854)
Fixes [EMQX-12855](https://emqx.atlassian.net/browse/EMQX-12855)
Fixes [EMQX-12856](https://emqx.atlassian.net/browse/EMQX-12856)
[EMQX-12851]: https://emqx.atlassian.net/browse/EMQX-12851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-12854]: https://emqx.atlassian.net/browse/EMQX-12854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMQX-12855]: https://emqx.atlassian.net/browse/EMQX-12855?atlOrigin=eyJpIjo …
=> fix cluster link issues

apps/emqx_gateway_coap/include/emqx_coap.hrl, apps/emqx_gateway_coap/src/emqx_coap_channel.erl, apps/emqx_gateway_coap/src/emqx_coap_observe_res.erl, apps/emqx_gateway_coap/src/emqx_coap_pubsub_handler.erl, apps/emqx_gateway_coap/src/emqx_coap_session.erl, changes/ce/fix-13607.en.md
=> fix(coap): Fixed that incorrect sub-options were displayed in CoAP gateways

apps/emqx_cluster_link/src/emqx_cluster_link_api.erl, apps/emqx_cluster_link/test/emqx_cluster_link_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12870
=> fix(cluster link api): redact and deobsfucate secrets

apps/emqx_bridge/src/emqx_bridge_api.erl, apps/emqx_bridge/src/emqx_bridge_v2_api.erl, apps/emqx_cluster_link/src/emqx_cluster_link_api.erl, apps/emqx_connector/src/emqx_connector_api.erl, apps/emqx_utils/src/emqx_utils_api.erl, apps/emqx_utils/src/emqx_utils_maps.erl, scripts/dev-cluster-host.sh
=> cluster link followup

apps/emqx_bridge_azure_blob_storage/mix.exs, apps/emqx_bridge_azure_blob_storage/rebar.config
Fixes EMQX-12906
https://github.com/emqx/erlazure/pull/12
=> fix: azure connector, bump erlazure to 0.4.0.1

apps/emqx_postgresql/src/emqx_postgresql.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12826
=> chore(postgres): change debug log to trace with `QUERY` tag

apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_schema.erl, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl, apps/emqx_bridge_kafka/test/emqx_bridge_kafka_tests.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12882
Release: e5.8
=> chore(kafka consumer): treat provided empty string as absent group id

Makefile
Fixes [EMQX-12906](https://emqx.atlassian.net/browse/EMQX-12906)
[EMQX-12906]: https://emqx.atlassian.net/browse/EMQX-12906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump ee dashboard version to e1.8.0-beta.2

apps/emqx/src/emqx_listeners.erl, apps/emqx/src/emqx_tls_lib.erl, apps/emqx/test/emqx_tls_certfile_gc_SUITE.erl, apps/emqx/test/emqx_tls_lib_tests.erl, apps/emqx_auth/src/emqx_authn/emqx_authn_config.erl, apps/emqx_auth/src/emqx_authz/emqx_authz.erl, apps/emqx_cluster_link/src/emqx_cluster_link_config.erl, apps/emqx_connector/src/emqx_connector_ssl.erl, apps/emqx_dashboard/src/emqx_dashboard_listener.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_ldap.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_saml.erl, apps/emqx_exhook/src/emqx_exhook_mgr.erl, apps/emqx_gateway/src/emqx_gateway_conf.erl, apps/emqx_opentelemetry/src/emqx_otel_config.erl, apps/emqx_plugins/src/emqx_plugins.erl, changes/ce/feat-13597.en.md, changes/ce/fix-13552.en.md
Fixes [EMQX-12834](https://emqx.atlassian.net/browse/EMQX-12834)
[EMQX-12834]: https://emqx.atlassian.net/browse/EMQX-12834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: store certs not in mutable dir

apps/emqx/src/emqx_banned.erl, apps/emqx/src/emqx_cm.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_conf/test/emqx_conf_logger_SUITE.erl, apps/emqx_enterprise/test/emqx_enterprise_schema_SUITE.erl
=> fix(log): two minor logging related fixes

apps/emqx_auth_mnesia/src/emqx_authz_api_mnesia.erl, apps/emqx_auth_mnesia/test/emqx_authz_api_mnesia_SUITE.erl, changes/ce/fix-13624.en.md
=> fix(authz): respect `max_rules` when updating rules of an client/user

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12873
Fixes https://emqx.atlassian.net/browse/EMQX-12353
=> fix(clients v2 mgmt api): support exact username filtering and remove `hasnext` from responses

apps/emqx_rule_engine/src/emqx_rule_events.erl
=> fix(rule): added example of `client_attrs` for rule engine

apps/emqx/test/emqx_takeover_SUITE.erl, apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl, apps/emqx_ds_backends/src/emqx_ds_backends.app.src.script
It has been actually testing with `emqx_session_mem` implementation.
=> 0814 flaky test

apps/emqx_bridge_couchbase/src/emqx_bridge_couchbase_action_schema.erl
Fixes [EMQX-12911](https://emqx.atlassian.net/browse/EMQX-12911)
[EMQX-12911]: https://emqx.atlassian.net/browse/EMQX-12911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(couchbase): initialize max_retries to 3 by default in action state

apps/emqx/src/emqx_broker.erl, apps/emqx/src/emqx_types.erl, apps/emqx_rule_engine/src/emqx_rule_actions.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12917
=> chore: distinguish between hook prohibition and no routes when publishing

apps/emqx/etc/vm.args.cloud
Fixes [EMQX-12918](https://emqx.atlassian.net/browse/EMQX-12918)
[EMQX-12918]: https://emqx.atlassian.net/browse/EMQX-12918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: explicit exposure of +c in vm.args

apps/emqx_auth_kerberos/mix.exs
=> chore(mix): add missing `mix.exs` file for `emqx_auth_kerberos`

apps/emqx_auth/src/emqx_authz/emqx_authz_schema.erl, apps/emqx_auth/src/emqx_authz/sources/emqx_authz_file_schema.erl, apps/emqx_auth_http/src/emqx_authz_http_schema.erl, apps/emqx_auth_ldap/src/emqx_auth_ldap.app.src, apps/emqx_auth_ldap/src/emqx_authz_ldap_schema.erl, apps/emqx_auth_mnesia/src/emqx_authz_mnesia_schema.erl, apps/emqx_auth_mongodb/src/emqx_authz_mongodb_schema.erl, apps/emqx_auth_mysql/src/emqx_authz_mysql_schema.erl, apps/emqx_auth_postgresql/src/emqx_authz_postgresql_schema.erl, apps/emqx_auth_redis/src/emqx_authz_redis_schema.erl, changes/ce/fix-13618.en.md
=> fix(authz): enhanced type spec for the `authorization/sources` endpoint

.ci/docker-compose-file/docker-compose-iotdb.yaml, .ci/docker-compose-file/toxiproxy.json, apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge/test/emqx_bridge_v2_tests.erl, apps/emqx_bridge_iotdb/include/emqx_bridge_iotdb.hrl, apps/emqx_bridge_iotdb/mix.exs, apps/emqx_bridge_iotdb/rebar.config, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_action_info.erl, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector_info.erl, apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl, apps/emqx_connector/src/schema/emqx_connector_schema.erl, apps/emqx_resource/src/emqx_resource.erl, apps/emqx_resource/src/emqx_resource_manager.erl, changes/ee/feat-13560.en.md, rel/i18n/emqx_bridge_iotdb_connector.hocon
=> feat(iotdb): introduced a thrift driver for IotDB connector

apps/emqx_bridge_iotdb/mix.exs
=> fix(mix): use distinct module name for iotdb bridge's mix.exs

apps/emqx_cluster_link/src/emqx_cluster_link_router_syncer.erl
Fixes [EMQX-12868](https://emqx.atlassian.net/browse/EMQX-12868)
If initial configuration for cluster link is incorrect, and local cluster fails to establish a connection, an actor would crash on startup which will lead to app supervisor crash, and removing of cluster link config handler. This will make it impossible to remove or update erroneous cluster link configuration.
Release version: e5.8.0
[EMQX-12868]: https://emqx.atlassian.net/browse/EMQX-12868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ensure cluster link app can recover from init failure

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12926
=> chore(clients v2 mgmt api): return prettier errors when user furnishes bad values

apps/emqx_management/src/emqx_mgmt_cli.erl
=> fix(cli): added more clauses to cover situations of the `enable`

apps/emqx_rule_engine/src/emqx_rule_events.erl
=> fix(rule): fix typo of example

apps/emqx_message_transformation/src/emqx_message_transformation_http_api.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12932
=> feat(message transformation dry run): add more input fields

apps/emqx_management/src/emqx_mgmt_api_relup.erl, apps/emqx_management/src/proto/emqx_mgmt_api_relup_proto_v1.erl
Fixes [EMQX-12933](https://emqx.atlassian.net/browse/EMQX-12933)
[EMQX-12933]: https://emqx.atlassian.net/browse/EMQX-12933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: got relup status from stale nodes

apps/emqx_prometheus/src/emqx_prometheus_data_integration.erl, apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl, changes/ce/feat-13665.en.md
Fixes [EMQX-12463](https://emqx.atlassian.net/browse/EMQX-12463)
[EMQX-12463]: https://emqx.atlassian.net/browse/EMQX-12463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: actions count in prometheus data integration endpoint

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_agent.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_group_sm.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader.erl
Update some loggings that I think should be debug level.
=> chore(ds-shared-sub): lower log level

bin/emqx
Fixes https://emqx.atlassian.net/browse/EMQX-12935
=> fix: the emqx ctl command not working after relup

apps/emqx_cluster_link/test/emqx_cluster_link_config_SUITE.erl
=> chore(ds): clean ds workdir for emqx_cluster_link_config_SUITE

apps/emqx/src/emqx_exclusive_subscription.erl, apps/emqx_management/src/emqx_mgmt_cli.erl
=> fix(exclusive): totally remove subscriptions when calling `exclusive delete`

scripts/buildx.sh
=> build: relup tar.gz for specific os dist by builder

.github/workflows/bump-dashboard-version.yaml
Successful run: https://github.com/emqx/emqx/actions/runs/10526054002
PR: https://github.com/emqx/emqx/pull/13685
=> ci: fix bump-dashboard-version workflow

apps/emqx_cluster_link/src/emqx_cluster_link.erl
Fixes [EMQX-12968](https://emqx.atlassian.net/browse/EMQX-12968)
[EMQX-12968]: https://emqx.atlassian.net/browse/EMQX-12968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(cluster-link): ignore actor heartbeat during initialization

apps/emqx_auth_kerberos/src/emqx_authn_kerberos.erl, apps/emqx_auth_kerberos/test/emqx_authn_kerberos_SUITE.erl, apps/emqx_durable_storage/src/emqx_ds_precondition.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12976
- [n/a] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
=> fix(authn/kerberos): allow disable without check

apps/emqx_management/src/emqx_mgmt_api_status.erl
=> fix: fix typo in management status endpoint

apps/emqx_enterprise/src/emqx_enterprise_schema.erl
=> fix: add EXTRA_SCHEMA_MODULES in ee_roots

apps/emqx_enterprise/src/emqx_enterprise_schema.erl, apps/emqx_enterprise/test/emqx_enterprise_schema_tests.erl, apps/emqx_machine/src/emqx_machine.app.src, apps/emqx_machine/src/emqx_machine_boot.erl
=> test: fix schema test

scripts/test/start-two-nodes-in-host.sh
In response to:
https://www.reddit.com/r/emqx/comments/1f3cdg4/run_emqx_on_localhost/
=> test: make test script more portable

apps/emqx_enterprise/test/emqx_enterprise_schema_tests.erl, apps/emqx_s3/src/emqx_s3.app.src, apps/emqx_s3/src/emqx_s3_schema.erl
=> test(schema): handle single atom roots

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_connector/src/emqx_connector.app.src, apps/emqx_message_transformation/src/emqx_message_transformation.app.src, apps/emqx_message_transformation/src/emqx_message_transformation.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl, apps/emqx_resource/src/emqx_resource.app.src, changes/ee/fix-13735.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12931
=> fix(message transformation): improve error messages when payload to decode is not binary

apps/emqx_cluster_link/test/emqx_cluster_link_config_SUITE.erl
=> chore(cluster-link): reduce test disk footprints

apps/emqx_bridge_azure_blob_storage/src/emqx_bridge_azure_blob_storage.app.src, apps/emqx_bridge_azure_blob_storage/src/emqx_bridge_azure_blob_storage_connector.erl, apps/emqx_bridge_azure_blob_storage/src/emqx_bridge_azure_blob_storage_connector_schema.erl, apps/emqx_bridge_azure_blob_storage/test/emqx_bridge_azure_blob_storage_SUITE.erl, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_connector/src/emqx_connector.app.src, apps/emqx_resource/src/emqx_resource.app.src, changes/ee/fix-13734.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12924
=> fix(azure blob storage connector): improve error messages

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_connector/src/emqx_connector.app.src, apps/emqx_connector_aggregator/mix.exs, apps/emqx_connector_aggregator/src/emqx_connector_aggregator.app.src, apps/emqx_connector_aggregator/src/emqx_connector_aggregator.erl, apps/emqx_connector_aggregator/test/emqx_connector_aggregator_SUITE.erl, apps/emqx_resource/src/emqx_resource.app.src, changes/ee/fix-13724.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12927
=> chore(connector aggregator): trigger delivery when max records is pushed

apps/emqx_bridge_azure_event_hub/mix.exs, apps/emqx_bridge_confluent/mix.exs, apps/emqx_bridge_kafka/mix.exs, apps/emqx_mix_utils/lib/mix/tasks/emqx.ct.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.eunit.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.proper.ex, mix.exs
=> chore(mix): sync some mix-only updates

apps/emqx_gateway/src/emqx_gateway.app.src, apps/emqx_gateway/src/emqx_gateway_insta_sup.erl, apps/emqx_gateway_gbt32960/src/emqx_gateway_gbt32960.app.src, apps/emqx_gateway_gbt32960/src/emqx_gbt32960_channel.erl, apps/emqx_gateway_gbt32960/src/emqx_gbt32960_frame.erl
=> fix: typo in log

apps/emqx_retainer/src/emqx_retainer.app.src, apps/emqx_retainer/src/emqx_retainer_dispatcher.erl, apps/emqx_retainer/test/emqx_retainer_SUITE.erl, changes/ce/fix-13742.en.md
Fixes [EMQX-12499](https://emqx.atlassian.net/browse/EMQX-12499)
[EMQX-12499]: https://emqx.atlassian.net/browse/EMQX-12499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: topic matching when deliver retainer msg

apps/emqx/src/emqx_ws_connection.erl, changes/ce/fix-13754.en.md
=> fix(ws): websocket connection crash when stats are sent to $SYS topic

apps/emqx_license/src/emqx_license.app.src, apps/emqx_license/src/emqx_license_cli.erl
=> docs: update help for emqx ctl license command

apps/emqx_bridge_pulsar/mix.exs, mix.exs
=> chore(mix): some fixes to new mix build

apps/emqx_gateway_ocpp/mix.exs, apps/emqx_gateway_ocpp/rebar.config, apps/emqx_plugins/mix.exs, apps/emqx_schema_registry/mix.exs, apps/emqx_schema_registry/rebar.config, changes/ee/fix-13769.en.md, mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-12017
=> fix(json schema): update `jesse` -> 1.8.0.1

apps/emqx/src/emqx_exclusive_subscription.erl
=> fix: compatible with the old schema of exclusive for rolling upgrade

apps/emqx_bridge_datalayers/src/emqx_bridge_datalayers.app.src, apps/emqx_bridge_datalayers/src/emqx_bridge_datalayers_connector.erl, apps/emqx_bridge_datalayers/test/emqx_bridge_datalayers_SUITE.erl, apps/emqx_bridge_datalayers/test/emqx_bridge_datalayers_connector_SUITE.erl, changes/ee/fix-13755.md, rel/i18n/emqx_bridge_datalayers_connector.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12936
=> Refactor datalayers impl

apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_app.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_config.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_registry.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_schema.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_sup.erl, apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_SUITE.erl, apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_api_SUITE.erl, changes/ee/feat-13788.en.md
Fixes [EMQX-13054](https://emqx.atlassian.net/browse/EMQX-13054)
[EMQX-13054]: https://emqx.atlassian.net/browse/EMQX-13054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(dssubs): make startup sequence dynamic + run only if enabled

apps/emqx_ds_builtin_raft/rebar.config, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_shard.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_snapshot.erl, apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl, apps/emqx_durable_storage/mix.exs, mix.exs, rebar.config
=> fix(dsraft): switch to emqx/ra v2.14.0-emqx-1 with proposed bugfix

changes/ce/perf-13634.en.md
=> chore(sessds): Add changelog for #13634

apps/emqx/include/emqx.hrl, apps/emqx/src/emqx_banned.erl, apps/emqx/test/emqx_banned_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api.erl, apps/emqx_management/src/emqx_mgmt_api_banned.erl, apps/emqx_management/test/emqx_mgmt_api_banned_SUITE.erl, changes/ce/feat-13792.en.md, rel/i18n/emqx_mgmt_api_banned.hocon
=> feat(banned): supports querying the banned with filters

.github/workflows/run_test_cases.yaml
=> ci: don't fail if there's no crashdump

apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_action_schema.erl, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector_schema.erl, apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl, apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_tests.erl, apps/emqx_connector_aggregator/src/emqx_connector_aggreg_delivery.erl, apps/emqx_connector_aggregator/src/emqx_connector_aggregator.erl, apps/emqx_utils/src/emqx_utils_redact.erl
Fixes:
- https://emqx.atlassian.net/browse/EMQX-13111
- https://emqx.atlassian.net/browse/EMQX-13112
- https://emqx.atlassian.net/browse/EMQX-13113
- https://emqx.atlassian.net/browse/EMQX-13114
- https://emqx.atlassian.net/browse/EMQX-13087 (azure blob storage, but conflicts with / same as 1st item)
- https://emqx.atlassian.net/browse/EMQX-13122
=> snowflake action fixes

apps/emqx_auth_kerberos/rebar.config, mix.exs, rebar.config
https://github.com/kafka4beam/sasl_auth/commit/9b170f7f09e55aadca088e8f3cd1b903aefba4a2
=> build: fix LDFLAGS for sasl_auth in macos build

apps/emqx/src/emqx_session.erl
Fixes N/A
- ~For internal contributor: there is a jira ticket to track this change~
- ~If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) …
=> Add missing functions to the emqx_session behavior

apps/emqx_management/src/emqx_mgmt_cli.erl
=> fix(mgmt): plugin cli usage typo

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_state.erl, apps/emqx/test/emqx_persistent_session_ds_state_tests.erl, apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader_store.erl, apps/emqx_durable_storage/src/emqx_ds.erl, apps/emqx_durable_storage/test/emqx_ds_storage_layout_SUITE.erl
Fixes [EMQX-13058](https://emqx.atlassian.net/issues/EMQX-13058)
Release version: v/e5.9
=> fix(ds): Rename force_monotonic_timestamps to append_only

.github/workflows/_push-entrypoint.yaml
also switch to using self hosted runners in forks
=> ci: do not run emqx app tests on release

apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13117
=> fix(snowflake action): URI encode pipe path when quoted

apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_resource/src/emqx_resource_pool.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13143
=> fix(resource pool): attempt to restart pool if `already_present`

apps/emqx_durable_storage/src/emqx_ds_lib.erl
Fix bogus warnings produced by durable sessions. 
=> fix(ds): Don't link timeout worker process to the caller

apps/emqx_auth_cinfo/mix.exs
=> ci(new mix build): add missing compile dependency

README-CN.md, README-RU.md, README.md
=> docs(readme): update resource link

rebar.config.erl
https://github.com/emqx/coveralls-erl/pull/4
=> ci: bump coveralls-erl -> v2.2.0-emqx-3

apps/emqx_cluster_link/src/emqx_cluster_link_api.erl, apps/emqx_cluster_link/src/emqx_cluster_link_metrics.erl, apps/emqx_cluster_link/test/emqx_cluster_link_api_SUITE.erl, changes/ee/feat-13835.en.md
Part of https://emqx.atlassian.net/browse/EMQX-12942
=> feat(cluster link api): add metrics reset endpoint

apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_SUITE.erl
```
2024-07-03T19:18:10.018529+00:00 [critical] "check stage" failed: error, {assertMatch,[{module,emqx_bridge_cassandra_SUITE},{line,659},{expression,"Trace"},{pattern,"[ # { result := { ok , _Pid } } ]"},{value,[]}]}, Stacktrace: [{emqx_bridge_cassandra_SUITE,'-t_missing_data/1-fun-3-',1,[{file,"/emqx/apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_SUITE.erl"},{line,659}]},{emqx_bridge_cassandra_SUITE,t_missing_data,1,[{file,"/emqx/apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_SUITE.erl"},{line,646}]}]
2024-07-03T19:18:10.025693+00:00 [critical] Check stage failed. Trace dump: "/emqx/_build/test/logs/ct_run.test@127.0.0.1.2024-07-03_19.17.17/snabbkaffe/1720034290018875982.log"
%%% emqx_bridge_cassandra_SUITE ==> tcp.sync.with_batch.t_missing_data: FAILED
%%% …
```
=> test(cassandra): attempt to stabilize flaky test

apps/emqx/src/emqx_frame.erl, changes/ce/fix-13842.en.md
=> fix(frame): fixed an optimized the UTF8 validation for MQTT packets

apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_sup.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer_meta.erl, apps/emqx_management/src/emqx_mgmt_api_ds.erl, apps/emqx_management/test/emqx_mgmt_api_ds_SUITE.erl
=> feat(mgmt): allow to manage any DS database through API / CLI

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector_info.erl, changes/ce/fix-13851.en.md
=> fix(iotdb): fixed an exception of `Test connectivity` with IotDB

apps/emqx/rebar.config.script, apps/emqx_conf/src/emqx_conf.app.src, apps/emqx_conf/src/emqx_conf_schema.erl, mix.exs, rebar.config.erl, rel/i18n/emqx_conf_schema.hocon
Fixes [EMQX-13145](https://emqx.atlassian.net/browse/EMQX-13145)
[EMQX-13145]: https://emqx.atlassian.net/browse/EMQX-13145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump to quicer 0.1.0

apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_conf/test/emqx_conf_schema_tests.erl
Refine error message when running `replicant` role on opensource edition.
=> refine error message for unsupported node.role

apps/emqx/test/emqx_common_test_helpers.erl
To mark flaky tests in a suite, simply add the callback:
```erlang
flaky_tests() ->
#{t_my_flaky_test => 3  %% The maximum number of attempts this test will be attempted
}.
```
=> test: introduce facility to declare flaky tests

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge_azure_blob_storage/src/emqx_bridge_azure_blob_storage_connector.erl, apps/emqx_bridge_azure_blob_storage/src/emqx_bridge_azure_blob_storage_connector_schema.erl, apps/emqx_bridge_azure_blob_storage/test/emqx_bridge_azure_blob_storage_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13154
=> fix(azure blob storage connector): handle obfuscated account key

apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
Partially fix [EMQX-12962](https://emqx.atlassian.net/browse/EMQX-12962)
Prior to this fix, the old metrics data is cleared after the system is started for at least 1 hour.
If a system is frequently restarted, every 1h, the old metrics will not have a chance to get deleted.
This PR makes the clean-up happen immediately after booted.
Also changes the clean-up interval to 10m
Also fix a bug of potential timer leak (if `clean_expired` signal is not triggered by a timer), then it would result in an extra timer started.
[EMQX-12962]: https://emqx.atlassian.net/browse/EMQX-12962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> fix: immediate cleanup dashboard monitor after each restart

apps/emqx_machine/src/emqx_machine_signal_handler.erl
log to both stderr and a critical level log
=> chore: optimize terminate signal log

apps/emqx_connector/mix.exs, apps/emqx_redis/mix.exs, apps/emqx_redis/rebar.config
Fixes https://emqx.atlassian.net/browse/EEC-1084
=> chore: update ereids_cluster to 0.8.5

.github/workflows/build_and_push_docker_images.yaml, build, deploy/docker/Dockerfile, deploy/docker/Dockerfile.sfodbc, rebar.config.erl, scripts/install-snowflake-driver.sh, scripts/rel/cleanup-release-package.sh, scripts/rel/macos-notarize-package.sh, scripts/rel/macos-sign-binaries.sh
- automatically publish a version of enterprise docker image with Snowflake ODBC driver preinstalled
- fixes [EMQX-13146](https://emqx.atlassian.net/browse/EMQX-13146)
[EMQX-13146]: https://emqx.atlassian.net/browse/EMQX-13146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix some issues with packages

.ci/docker-compose-file/openldap/Dockerfile, .ci/docker-compose-file/openldap/entrypoint, .ci/docker-compose-file/openldap/slapd.conf, apps/emqx_auth_ldap/test/emqx_authn_ldap_SUITE.erl, apps/emqx_ldap/src/emqx_ldap.app.src, apps/emqx_ldap/src/emqx_ldap_filter_lexer.xrl, apps/emqx_ldap/src/emqx_ldap_filter_parser.yrl, apps/emqx_ldap/test/data/emqx.groups.ldif, apps/emqx_ldap/test/emqx_ldap_filter_SUITE.erl, changes/ce/feat-13864.en.md
Fixes EMQX-12804
FIxes #13710 
=> feat(ldap): supported the `memberOf` syntax in query filters

apps/emqx/rebar.config.script, apps/emqx_conf/src/emqx_conf_schema.erl, mix.exs, rebar.config.erl, rel/i18n/emqx_conf_schema.hocon
=> quicer 0.1.0 for release58

apps/emqx/src/emqx_config_handler.erl, apps/emqx_auth/src/emqx_authz/emqx_authz.erl, apps/emqx_bridge/src/emqx_bridge_app.erl, apps/emqx_bridge/src/schema/emqx_bridge_schema.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_utils/src/emqx_utils.erl, apps/emqx_utils/src/emqx_variform.erl
Fix a config load performance regression (which is not released yet). So there is no change log for this one.
=> perf: avoid calling zero arity Module:module_info

apps/emqx/rebar.config, mix.exs, rebar.config
This includes an error log message enhancement. 
https://github.com/emqx/mria/pull/182
=> chore: upgrade ekka from 0.19.5 to 0.19.6

apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver.app.src, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl, changes/ce/fix-13876.md
Fixes https://emqx.atlassian.net/browse/EMQX-13186
=> Fix the issue of data loss when enabling bulk writing in SQL Server Sink

.ci/docker-compose-file/openldap/Dockerfile
=> test(ldap): optimized the Dockerfile for CI

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, rel/i18n/emqx_bridge_iotdb_connector.hocon
=> fix(iotdb): set the default timeout for the Thrift driver to avoid getting stuck

deploy/charts/emqx-enterprise/templates/StatefulSet.yaml, deploy/charts/emqx/templates/StatefulSet.yaml
Fixes https://github.com/emqx/emqx/discussions/13784
Release version: both
=> fix(helm): fix EMQX_HOST error when singleton

changes/ee/fix-13897.en.md
=> chore: add changelog for #13897

apps/emqx_bridge_pulsar/mix.exs, apps/emqx_bridge_pulsar/rebar.config, changes/ee/fix-13896.en.md
Fixes [EEC-518](https://emqx.atlassian.net/browse/ECC-518)
[EEC-518]: https://emqx.atlassian.net/browse/EEC-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(pulsar): upgrade client from 0.8.3 to 0.8.4

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
Fixes https://github.com/emqx/emqx/pull/13814
=> fix(mgmt_api_clients):  remove conn_shared_state from conninfo

apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl, apps/emqx_postgresql/rebar.config, apps/emqx_postgresql/src/emqx_postgresql.app.src, apps/emqx_postgresql/src/emqx_postgresql.erl, changes/ee/fix-13901.en.md, mix.exs, rebar.config
Fixes [EEC-1097](https://emqx.atlassian.net/browse/EEC-1097)
[EEC-1097]: https://emqx.atlassian.net/browse/EEC-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 0930 fix posgres prepared statement name clash

apps/emqx_cluster_link/test/emqx_cluster_link_api_SUITE.erl
Ex: https://github.com/emqx/emqx/actions/runs/11107654407/job/30859313603?pr=13888#step:6:400
=> test(cluster link api): fix flaky test

apps/emqx_bridge_oracle/test/emqx_bridge_oracle_SUITE.erl
Ex: https://github.com/emqx/emqx/actions/runs/11113577939/job/30878620421?pr=13903#step:5:374
=> test(oracle): attempt to fix flaky test

apps/emqx/src/emqx_persistent_session_ds.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_state.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_stream_scheduler.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub.app.src, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_agent.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_api.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_elector.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_group_sm.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_queue.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_registry.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_store.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_sup.erl, apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_SUITE.erl, apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_api_SUITE.erl, apps/emqx_ds_shared_sub/test/emqx_ds_shared_sub_mgmt_api_subscription_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl, apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl, rel/i18n/emqx_ds_shared_sub_api.hocon
Fixes [EMQX-12153](https://emqx.atlassian.net/browse/EMQX-12153).
API Schema has changed slightly.
[EMQX-12153]: https://emqx.atlassian.net/browse/EMQX-12153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(dssubs): implement explicit queue declare + provide APIs

apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge/src/emqx_bridge_v2_api.erl, apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl, changes/ce/fix-13913.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13153
=> fix(action/source api): return thrown messages

apps/emqx_bridge_mysql/src/emqx_bridge_mysql.app.src, apps/emqx_bridge_mysql/src/emqx_bridge_mysql_connector.erl, apps/emqx_bridge_mysql/test/emqx_bridge_v2_mysql_SUITE.erl, apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl, apps/emqx_mysql/src/emqx_mysql.app.src, apps/emqx_mysql/src/emqx_mysql.erl, changes/ee/fix-13902.en.md
Fixes [EEC-1097](https://emqx.atlassian.net/browse/EEC-1097)
Same as https://github.com/emqx/emqx/pull/13906, but for MySQL
[EEC-1097]: https://emqx.atlassian.net/browse/EEC-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 0930 fix prepared statement for mysql

apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
```
19:50:56.497 [warning] [msg: ~c"failed_to_sample_current_rate", errors: []]
```
=> fix(dashboard monitor): don't log absence of errors

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
Ex: https://github.com/emqx/emqx/actions/runs/11133084269/job/30938735205?pr=13913#step:5:448
=> test(gcp pubsub producer): fix flaky test

apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_pubsub_schema.erl, apps/emqx_resource/src/emqx_resource.erl, changes/ee/fix-13921.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13215
=> fix(pulsar action): use `sync_timeout` for simple sync query timeout

apps/emqx_auth_jwt/src/emqx_auth_jwt.app.src, apps/emqx_auth_jwt/src/emqx_authn_jwt.erl, changes/ce/fix-13924.en.md
Fixes [EMQX-12825](https://emqx.atlassian.net/browse/EMQX-12825)
- [na] Added tests for the changes
- [na] Changed lines covered in coverage report
[EMQX-12825]: https://emqx.atlassian.net/browse/EMQX-12825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(authn): do not log JWK in redis auth

apps/emqx/rebar.config, changes/ce/fix-13931.en.md, mix.exs, rebar.config
=> chore(gen_rpc): Bump version to 3.4.1

apps/emqx_cluster_link/test/emqx_cluster_link_config_SUITE.erl
=> test(cluster-link): simplify config test suite

apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl, apps/emqx_auth/src/emqx_authn/emqx_authn_user_import_api.erl, apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src, apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl, apps/emqx_auth_mnesia/test/emqx_authn_api_mnesia_SUITE.erl, apps/emqx_auth_mnesia/test/emqx_authn_mnesia_SUITE.erl, apps/emqx_gateway/src/emqx_gateway_api.erl, apps/emqx_gateway/src/emqx_gateway_api_authn_user_import.erl, apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl, changes/ce/feat-13862.md, rel/i18n/emqx_authn_user_import_api.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-11989
=> feat: returns user imported details

apps/emqx_management/src/emqx_mgmt_api_ds.erl, apps/emqx_management/src/emqx_mgmt_cli.erl
Related to [EMQX-12752](https://emqx.atlassian.net/browse/EMQX-12752).
Followup to #13844.
[EMQX-12752]: https://emqx.atlassian.net/browse/EMQX-12752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ctl-ds): use identical to DS API "enabled" criterion

apps/emqx_management/src/emqx_mgmt_api_banned.erl, apps/emqx_management/test/emqx_mgmt_api_banned_SUITE.erl, rel/i18n/emqx_mgmt_api_banned.hocon
=> fix(banned): validate the filter for fuzzy query

apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl
=> fix(snowflake action): delete cached jwt when deleting/stopping action

apps/emqx_bridge_pulsar/mix.exs, apps/emqx_bridge_pulsar/rebar.config, changes/ee/fix-13959.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13230
=> fix(pulsar producer): bump pulsar-client-erl -> 0.8.5

apps/emqx_connector/mix.exs, apps/emqx_redis/mix.exs, apps/emqx_redis/rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-13220
=> chore: update eredis-cluster to 0.8.6

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
=> fix(iotdb): normalized the timeout configs of the Thrift driver

apps/emqx_management/src/emqx_mgmt_api_metrics.erl
```
12:49:06.177 [warning] [msg: ~c"failed_to_fetch_metrics", errors: []]
```
=> fix(mgmt metrics api): don't log absence of errors

apps/emqx_bridge_snowflake/docs/dev-quick-ref.md, apps/emqx_bridge_snowflake/docs/user-guide.md, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl, apps/emqx_connector_aggregator/src/emqx_connector_aggregator.erl
```
2024-10-08T20:46:00.723858+00:00 [warning] msg: snowflake_check_snowpipe_user_permission_error, pool: <<"action:snowflake:a:connector:snowflake:a">>, body: #{<<"code">> => <<"390144">>,<<"data">> => null,<<"headers">> => null,<<"message">> => <<"JWT token is invalid. [4cb8e42d-759a-48da-99b4-0c6a009a5191]">>,<<"success">> => false}, request_id: <<"afd39ac0-aebd-4c7d-9d1a-477f3a6766f2">>, failure_details: #{<<"clientIP">> => <<"201.92.214.62">>,<<"clientType">> => <<"OTHER">>,<<"clientVersion">> => <<>>,<<"errorCode">> => <<"JWT_TOKEN_INVALID_ISSUE_TIME">>,<<"timestamp">> => 1728420344,<<"username">> => <<"SNOWPIPEUSER">>}
```
If the user lacks the privilege or another error occurs while trying to get more details:
```
2024-10-08T20:46:52.677514+00:00 [warning] …
```
=> feat(snowflake): attempt to provide extra details when JWT is considered invalid

apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl, apps/emqx_resource/src/emqx_resource_buffer_worker.erl
=> fix(kafka producer action): set query timeout using non-conventional parameter schema

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
=> fix(iotdb): fixed function clause error in batch mode

apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl, apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse.app.src, apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse.erl, apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse_connector.erl, apps/emqx_bridge_clickhouse/test/emqx_bridge_clickhouse_SUITE.erl, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo.app.src, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo.erl, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl, apps/emqx_bridge_dynamo/test/emqx_bridge_dynamo_SUITE.erl, apps/emqx_bridge_mysql/src/emqx_bridge_mysql.app.src, apps/emqx_bridge_mysql/src/emqx_bridge_mysql.erl, apps/emqx_bridge_mysql/src/emqx_bridge_mysql_connector.erl, apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver.app.src, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver.erl, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl, apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl, apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine.app.src, apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine.erl, apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector.erl, apps/emqx_bridge_tdengine/test/emqx_bridge_tdengine_SUITE.erl, apps/emqx_mysql/src/emqx_mysql.app.src, apps/emqx_mysql/src/emqx_mysql.erl, apps/emqx_rule_engine/src/emqx_rule_funcs.erl, apps/emqx_utils/src/emqx_placeholder.erl, changes/ee/feat-13861.en.md, rel/i18n/emqx_bridge_v2_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-12816
=> Undefined vars as null

apps/emqx_audit/src/emqx_audit.app.src, apps/emqx_audit/src/emqx_audit.erl, apps/emqx_dashboard/src/emqx_dashboard.erl, apps/emqx_dashboard/src/emqx_dashboard_api.erl, apps/emqx_dashboard/src/emqx_dashboard_audit.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso.app.src, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_api.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_api.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_saml.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_saml_api.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_publish.erl, changes/ee/fix-13963.en.md, mix.exs, rebar.config
=> fix(audit): correctly handle SSO related events

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_stream_scheduler.erl
Fixes [EMQX-13251](https://emqx.atlassian.net/browse/EMQX-13251)
The problem with `end_of_stream` seemed to be the following:
* stream gets `end_of_stream`
* it gets last seqno's set to first seqnos https://github.com/emqx/emqx/blob/fa319268fda17488dacd4ee8675cf7f19af60d58/apps/emqx/src/emqx_persistent_session_ds.erl#L1192
* then it gets into `to_U`
* `to_U` deletes keys from blocked sets by those last seqnos, thus removing other stream's data
* this other stream falls out of the state machine
[EMQX-13251]: https://emqx.atlassian.net/browse/EMQX-13251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> feat(dssess): fix end of stream handling

apps/emqx/src/emqx.app.src, apps/emqx/src/emqx_persistent_session_ds.erl, apps/emqx_ds_backends/rebar.config.script, apps/emqx_ds_backends/src/emqx_ds_backends.app.src.script, apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.app.src, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft.app.src, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_layer.erl, apps/emqx_durable_storage/include/emqx_ds_metrics.hrl, apps/emqx_durable_storage/src/emqx_ds_beamformer.erl, apps/emqx_durable_storage/src/emqx_ds_builtin_metrics.erl, apps/emqx_durable_storage/src/emqx_ds_msg_serializer.erl, apps/emqx_durable_storage/src/emqx_durable_storage.app.src, apps/emqx_machine/src/emqx_machine.app.src, apps/emqx_machine/src/emqx_machine_boot.erl, apps/emqx_prometheus/src/emqx_prometheus.app.src, apps/emqx_prometheus/src/emqx_prometheus.erl, apps/emqx_utils/src/emqx_metrics_worker.erl, apps/emqx_utils/src/emqx_utils.app.src, mix.exs, rebar.config.erl, scripts/ct/run.sh
Fixes [EMQX-12829](https://emqx.atlassian.net/issues/EMQX-12829)
[EMQX-12829]: https://emqx.atlassian.net/browse/EMQX-12829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(dsfdb): introduce new fdb backend

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_shared_subs.erl, apps/emqx_ds_shared_sub/src/emqx_ds_shared_sub_leader.erl
Fixes [EMQX-12575](https://emqx.atlassian.net/browse/EMQX-12575)
- [na] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
[EMQX-12575]: https://emqx.atlassian.net/browse/EMQX-12575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(dssubs): improve stream distribution algorithm

apps/emqx_conf/src/emqx_conf.app.src, apps/emqx_dashboard_sso/src/emqx_dashboard_sso.app.src, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_session.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_sup.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_sup.erl, changes/ee/fix-13998.en.md
avoid invalid configuration crash the SSO feature
Fixes EMQX-13274
=> fix(sso): isolates OIDC workers and the SSO manager

apps/emqx_bridge_iotdb/rebar.config, changes/ee/fix-14005.en.md
=> chore: upgrade the IotDB driver

changes/ce/fix-14001.en.md
Fixes https://github.com/emqx/emqx/pull/14001#discussion_r1804759229
=> docs: add phrase to changelog

changes/ce/fix-13969.en.md
Part of [EMQX-13213](https://emqx.atlassian.net/browse/EMQX-13213).
[EMQX-13213]: https://emqx.atlassian.net/browse/EMQX-13213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add #13969 changelog entry

apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl, apps/emqx_conf/src/emqx_conf.app.src, apps/emqx_connector_aggregator/src/emqx_connector_aggregator.app.src, apps/emqx_connector_aggregator/src/emqx_connector_aggregator.erl
=> test: testing race in ci

apps/emqx_mongodb/src/emqx_mongodb.app.src, apps/emqx_mongodb/src/emqx_mongodb.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13257
=> perf: reduce the mongodb topology poolsize

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_gc_worker.erl
Fixes [EMQX-12706](https://emqx.atlassian.net/browse/EMQX-12706).
Because it leads to an unintuitive behavior where sessions are collected much later than they are supposed to be collected, from looking at the durable sessions settings.
[EMQX-12706]: https://emqx.atlassian.net/browse/EMQX-12706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(sessds): stop using huge safety margin in session GC

apps/emqx_durable_storage/include/emqx_ds_metrics.hrl, apps/emqx_durable_storage/src/emqx_ds_buffer.erl, apps/emqx_durable_storage/src/emqx_ds_builtin_metrics.erl, apps/emqx_prometheus/src/emqx_prometheus.erl
Some improvements for the DS buffer
- Custom callback for getting configuration
- Report latency induced by buffering
=> DS buffer improvements

apps/emqx_durable_storage/src/emqx_dsx.erl
=> feat(dsx): Introduce EMQX durable storage explorer

changes/ee/fix-14008.en.md
=> docs: add changelog for #14008

apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl
- Don't assume reference layout
- Remove some obsolete tests
- Add timeouts
=> Simplify emqx_ds_backends_SUITE

apps/emqx/src/emqx_ds_schema.erl, apps/emqx/src/emqx_schema.erl, apps/emqx_durable_storage/src/emqx_ds_buffer.erl, rel/i18n/emqx_schema.hocon
=> docs(sessds): Expose durable session in the HOCON schema

apps/emqx_gateway_gbt32960/src/emqx_gateway_gbt32960.app.src, apps/emqx_gateway_gbt32960/src/emqx_gbt32960_frame.erl, apps/emqx_gateway_gbt32960/test/emqx_gbt32960_parser_SUITE.erl, changes/ee/feat-14017.md
Fixes https://emqx.atlassian.net/browse/EMQX-13318
=> feat(gbt32960): support to parse the custom type of Info fields

apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl, apps/emqx_durable_storage/src/emqx_ds_beamformer.erl, apps/emqx_durable_storage/src/emqx_ds_buffer.erl
=> Handle errors in beamformer:unpack_iterator

apps/emqx/rebar.config, changes/ce/fix-14037.en.md, mix.exs, rebar.config
Fixes [EMQX-13309](https://emqx.atlassian.net/browse/EMQX-13309).
[EMQX-13309]: https://emqx.atlassian.net/browse/EMQX-13309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(cluster): ensure join succeeds if cluster goes offline in the process

apps/emqx/test/emqx_cth_cluster.erl
Contrary to clean startup, restart should ideally be performed in parallel for each node, because mria needs alive cluster peers upon restart.
=> feat(cth): support proper multi-node restart

apps/emqx/rebar.config.script, apps/emqx/src/emqx_quic_connection.erl, apps/emqx/test/emqx_listeners_SUITE.erl, changes/ce/feat-13984.en.md, env.sh, mix.exs, rebar.config.erl
Fixes [EMQX-13340](https://emqx.atlassian.net/browse/EMQX-13340)
[EMQX-13340]: https://emqx.atlassian.net/browse/EMQX-13340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: quic link sys crypto

apps/emqx_ds_builtin_raft/rebar.config, mix.exs, rebar.config
=> chore: switch back to upstream ra 2.15.0

apps/emqx_bridge_iotdb/rebar.config, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl, changes/ee/feat-14044.en.md
=> feat(iotdb): the Thrift driver supports multi-address

apps/emqx/test/emqx_cth_cluster.erl
=> test: restore accidentally deleted helper

apps/emqx_management/src/emqx_mgmt_api_data_backup.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, apps/emqx_management/test/emqx_mgmt_data_backup_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12908
=> feat: implement data export with limited scope for cloud

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl, changes/ce/fix-14055.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13265
Fixes https://emqx.atlassian.net/browse/EMQX-13266
=> fix(client_api): apply query to search results

apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl
Optimize creation of skipstream_lts batches. Previous implementation relied on a higher-order function that would create more garbage and slow down publishing.  
=> fix(ds): Use tail-recursive functions to prepare batch

apps/emqx_bridge_datalayers/src/emqx_bridge_datalayers.app.src, apps/emqx_bridge_datalayers/src/emqx_bridge_datalayers.erl, apps/emqx_bridge_datalayers/src/emqx_bridge_datalayers_connector.erl, apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb.app.src, apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb.erl, apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl, changes/ee/feat-14034.md, rel/i18n/emqx_bridge_datalayers_connector.hocon, rel/i18n/emqx_bridge_influxdb_connector.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13321
=> feat: expose the pool_size for influxdb and datalayers connector

apps/emqx_gateway/src/bhvrs/emqx_gateway_conn.erl, apps/emqx_gateway_coap/src/emqx_coap_channel.erl, apps/emqx_gateway_coap/src/emqx_gateway_coap.app.src, apps/emqx_gateway_exproto/src/emqx_exproto_channel.erl, apps/emqx_gateway_exproto/src/emqx_gateway_exproto.app.src, apps/emqx_gateway_gbt32960/src/emqx_gateway_gbt32960.app.src, apps/emqx_gateway_gbt32960/src/emqx_gbt32960_channel.erl, apps/emqx_gateway_jt808/src/emqx_gateway_jt808.app.src, apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl, apps/emqx_gateway_lwm2m/src/emqx_gateway_lwm2m.app.src, apps/emqx_gateway_lwm2m/src/emqx_lwm2m_channel.erl, apps/emqx_gateway_mqttsn/src/emqx_gateway_mqttsn.app.src, apps/emqx_gateway_mqttsn/src/emqx_mqttsn_channel.erl, apps/emqx_gateway_ocpp/src/emqx_gateway_ocpp.app.src, apps/emqx_gateway_ocpp/src/emqx_ocpp_channel.erl, apps/emqx_gateway_ocpp/src/emqx_ocpp_frame.erl, apps/emqx_gateway_stomp/src/emqx_gateway_stomp.app.src, apps/emqx_gateway_stomp/src/emqx_stomp_channel.erl, changes/ce/fix-14068.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13324
Add handle_frame_error/2 to all gateway implementations. The log msg before this improvement:
```
peername: 165.154.187.159:33277, pid: <0.6272732.0>, mfa: {proc_lib,crash_report,4}, line: 584, domain: ["otp","sasl"], error_logger: {"type":"crash_report","tag":"error_report"}, logger_formatter: {"title":"CRASH REPORT"}, msg: crasher: initial call: emqx_gateway_conn:init/6, pid: <0.6272732.0>, registered_name: [], exit: {#{context => function_clause,stacktrace => [{emqx_coap_tm,handle_response,[{frame_error,{case_clause,<<119,15,15,50,114,49,58,121,49,58,113,101>>}},#{seq_id => 1,next_msg_id => 46596}],[{file,"emqx_coap_tm.erl"},{line,107}]},{emqx_coap_session,call_transport_manager,3,[{file,"emqx_coap_session.erl" …
```
=> fix: add handle_frame_error/2 to all gateway implementations

rel/i18n/emqx_conf_schema.hocon, rel/i18n/emqx_mgmt_api_banned.hocon
Changed "banned objects" to "banning rules" according to the correction in https://github.com/emqx/emqx-i18n.
=> docs: Update emqx_mgmt_api_banned.hocon

apps/emqx_bridge/test/emqx_bridge_testlib.erl, apps/emqx_bridge_cassandra/mix.exs, apps/emqx_bridge_cassandra/rebar.config, apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra.app.src, apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra_connector.erl, apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_SUITE.erl, changes/ee/fix-14069.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13218
=> fix(cassandra): fix the prepared query cannot be modified

apps/emqx/etc/vm.args.cloud, apps/emqx_utils/src/emqx_utils.erl, apps/emqx_utils/test/emqx_utils_tests.erl, changes/ce/feat-14072.en.md, scripts/ensure-rebar3.sh
Fixes https://emqx.atlassian.net/browse/EMQX-13115
See also: https://github.com/emqx/rebar3/pull/20
=> feat: set printable characters range to unicode

apps/emqx/src/emqx_config_handler.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13366
=> chore: reformat the code style of emqx_config_handler

mix.exs, rebar.config
=> chore: bump `telemetry` -> 1.3.0

bin/emqx, changes/ce/breaking-14063.en.md
=> Revert "dont silently load insecure dynlibs"

apps/emqx_dashboard_sso/src/emqx_dashboard_sso_api.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc_session.erl, changes/ee/14094.en.md
=> fix(OIDC): return error when login with an OIDC provider which does not work

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl
=> test(kafka consumer): fix flaky test

apps/emqx/src/emqx_schema.erl, apps/emqx/src/emqx_tls_lib.erl, apps/emqx/test/emqx_tls_lib_tests.erl, changes/ce/feat-14102.en.md
=> feat: support file:///path/to/secret/file as SSL private key passphrase

apps/emqx/src/bhvrs/emqx_db_backup.erl, apps/emqx/src/emqx_banned.erl, apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl, apps/emqx_auth_mnesia/src/emqx_authn_scram_mnesia.erl, apps/emqx_auth_mnesia/src/emqx_authz_mnesia.erl, apps/emqx_dashboard/src/emqx_dashboard_admin.erl, apps/emqx_management/src/emqx_mgmt_api_data_backup.erl, apps/emqx_management/src/emqx_mgmt_auth.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, apps/emqx_management/test/emqx_mgmt_data_backup_SUITE.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl, apps/emqx_psk/src/emqx_psk.app.src, apps/emqx_psk/src/emqx_psk.erl, apps/emqx_retainer/src/emqx_retainer_mnesia.erl, apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13381
=> feat: make `/data/export` parameterizable, remove `/data/export_cloud`

apps/emqx_conf/src/emqx_cluster_rpc.erl, apps/emqx_prometheus/src/emqx_prometheus.erl, apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl, changes/ce/feat-14096.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13323
=> feat: expose tnx_id of cluster_rpc for prometheus

apps/emqx_dashboard/src/emqx_dashboard_api.erl, changes/ce/fix-14117.en.md
=> fix(api): `users` endpoints do not support basic authentication

apps/emqx_bridge_pulsar/mix.exs, apps/emqx_bridge_pulsar/rebar.config, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl, apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl, changes/ee/feat-14110.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13365
=> feat(pulsar producer): add telemetry support

.github/workflows/run_emqx_app_tests.yaml
[Example of successful upload](https://github.com/emqx/emqx/actions/runs/11630688444/job/32390583434#step:6:1).
=> ci: compress and upload standalone test logs

apps/emqx_bridge_oracle/test/emqx_bridge_oracle_SUITE.erl, apps/emqx_oracle/src/emqx_oracle.app.src, apps/emqx_oracle/src/emqx_oracle.erl, changes/ee/fix-14126.en.md
=> fix: prepared statement for oracle

apps/emqx/src/emqx_connection.erl, apps/emqx/src/emqx_listeners.erl, apps/emqx/src/emqx_quic_connection.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/test/emqx_common_test_helpers.erl, changes/ce/feat-14112.en.md
Fixes [EMQX-13410](https://emqx.atlassian.net/browse/EMQX-13410)
[EMQX-13410]: https://emqx.atlassian.net/browse/EMQX-13410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(quic): support QUIC streams process hibernation

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl, changes/ee/fix-14125.en.md
=> fix(iotdb): return error if set up a Thrift driver in async mode

apps/emqx/src/emqx_mountpoint.erl, apps/emqx/test/emqx_mountpoint_SUITE.erl
Fixes [EMQX-13352](https://emqx.atlassian.net/browse/EMQX-13352)
A follow-up fix for PR https://github.com/emqx/emqx/pull/13923
[EMQX-13352]: https://emqx.atlassian.net/browse/EMQX-13352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(moutpoint): allow zone to render moutpoint template

apps/emqx/priv/bpapi.versions, apps/emqx/src/emqx_persistent_session_ds.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_stream_scheduler.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_subs.erl, apps/emqx/test/emqx_cth_suite.erl, apps/emqx/test/emqx_persistent_session_ds_SUITE.erl, apps/emqx_durable_storage/include/emqx_ds.hrl, apps/emqx_durable_storage/src/emqx_ds_beamformer.erl, apps/emqx_durable_storage/src/emqx_ds_lts.erl, apps/emqx_durable_storage/src/emqx_ds_new_streams.erl, apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl, apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl, apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl, apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl, apps/emqx_durable_storage/src/emqx_ds_sup.erl, apps/emqx_durable_storage/src/proto/emqx_ds_new_streams_proto_v1.erl, apps/emqx_durable_storage/test/emqx_ds_new_streams_SUITE.erl, changes/ce/feat-14130.en.md
=> Use event-based mechanism for stream discovery

rel/i18n/emqx_retainer_schema.hocon
=> docs: add more details about retained message expiry override

apps/emqx_bridge_iotdb/rebar.config
=> fix(iotdb): upgrade the Thrift driver

apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse.app.src, apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse.erl, apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse_action_info.erl, changes/ee/fix-14149.md
Fixes https://emqx.atlassian.net/browse/EMQX-13428
=> Creating Clickhouse bridge failed using the old bridge API

apps/emqx_retainer/src/emqx_retainer_mnesia.erl, apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13399
Previously, we used to show such topics in the API.  Alternatively, we would need special handling when computing the total number of retained messages when returning the total count in the API, if we were to start hiding those.
=> fix(retainer): show `$SYS` topics when iterating over all topics

build, changes/ce/feat-13984.en.md
=> build(el7): workaround for QUIC transport

apps/emqx_durable_storage/src/emqx_ds_storage_skipstream_lts.erl, apps/emqx_durable_storage/src/emqx_dsx.erl
=> Backport #14026 to release-583

apps/emqx_durable_storage/src/emqx_ds_lts.erl
=> Export some types from DS trie module

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl, changes/ce/fix-14151.en.md
Fixes [EMQX-13384](https://emqx.atlassian.net/browse/EMQX-13384)
[EMQX-13384]: https://emqx.atlassian.net/browse/EMQX-13384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(client_api): correctly apply conn_state selector in search queries

apps/emqx_bridge_oracle/test/emqx_bridge_oracle_SUITE.erl, apps/emqx_dashboard/src/emqx_dashboard_api.erl, apps/emqx_oracle/src/emqx_oracle.app.src, apps/emqx_oracle/src/emqx_oracle.erl, changes/ce/fix-14117.en.md, changes/ee/fix-14126.en.md
=> chore: port from the master

apps/emqx_ldap/src/emqx_ldap.app.src, apps/emqx_ldap/src/emqx_ldap_filter_parser.yrl, apps/emqx_ldap/test/emqx_ldap_filter_SUITE.erl, changes/ce/feat-14147.en.md
=> feat(ldap): supported the `memberOf` syntax in the extensible match filter

apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq.app.src, apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_connector.erl, apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_pubsub_schema.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl, changes/ee/feat-14166.en.md, rel/i18n/emqx_bridge_rabbitmq_connector_schema.hocon, rel/i18n/emqx_bridge_rabbitmq_pubsub_schema.hocon
=> feat(rabbitmq): supports dynamic exchange and routing key

apps/emqx_cluster_link/src/emqx_cluster_link.erl, apps/emqx_cluster_link/src/emqx_cluster_link_router_syncer.erl, apps/emqx_cluster_link/test/emqx_cluster_link_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13350
=> fix(cluster link): restart connection if actor init fails

apps/emqx_machine/src/user_default.erl
So it works in remote console too.
=> fix(shell): print debug trace logs to default group leader

apps/emqx_retainer/src/emqx_retainer_cli.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13452
=> fix(retainer cli): list all topics

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_bookkeeper.erl, changes/ce/fix-14184.en.md
Fixes [EMQX-13453](https://emqx.atlassian.net/browse/EMQX-13453)
[EMQX-13453]: https://emqx.atlassian.net/browse/EMQX-13453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dashboard): fix slow fetching of persistent session stats

apps/emqx/src/emqx_persistent_session_ds.erl
=> fix(sessds): Trigger stream renewal after encountering end of stream

apps/emqx_utils/src/emqx_variform.erl, apps/emqx_utils/src/emqx_variform_bif.erl, apps/emqx_utils/test/emqx_variform_tests.erl, changes/ce/fix-14180.en.md
=> 241107 fix variform expression when value is 'undefined'

apps/emqx_dashboard/etc/emqx_dashboard.conf
Simplify the default config template.
=> docs: simplify dashboard listener config comments

apps/emqx/src/emqx_tls_lib.erl, apps/emqx/test/emqx_test_tls_certs_helper.erl, apps/emqx/test/emqx_tls_lib_tests.erl, apps/emqx_auth/test/emqx_authn/emqx_authn_listeners_SUITE.erl, apps/emqx_ft/test/emqx_ft_api_SUITE.erl, apps/emqx_ft/test/emqx_ft_conf_SUITE.erl, apps/emqx_ft/test/emqx_ft_test_helpers.erl
Fixes https://emqx.atlassian.net/browse/EMQX-10210
=> feat: validate certfiles and keyfiles

apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl
=> test(auth-http): fix flaky authn testcase

apps/emqx_retainer/src/emqx_retainer.erl, apps/emqx_retainer/test/emqx_retainer_SUITE.erl, changes/ce/fix-14215.en.md
=> fix(retainer): ensure API call is safe when disabled the retainer

apps/emqx_retainer/test/emqx_retainer_SUITE.erl, apps/emqx_schema_registry/src/emqx_schema_registry.app.src, apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl, changes/ee/fix-14217.en.md
=> fix: fix errors in the examples of schema registry endpoints

apps/emqx_gateway/test/emqx_gateway_test_utils.erl, apps/emqx_gateway_coap/test/emqx_coap_SUITE.erl, apps/emqx_gateway_exproto/src/emqx_exproto_channel.erl, apps/emqx_gateway_exproto/src/emqx_gateway_exproto.app.src, apps/emqx_gateway_exproto/test/emqx_exproto_SUITE.erl, apps/emqx_gateway_gbt32960/src/emqx_gateway_gbt32960.app.src, apps/emqx_gateway_gbt32960/src/emqx_gbt32960_channel.erl, apps/emqx_gateway_gbt32960/test/emqx_gbt32960_SUITE.erl, apps/emqx_gateway_jt808/src/emqx_gateway_jt808.app.src, apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl, apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl, apps/emqx_gateway_lwm2m/test/emqx_lwm2m_SUITE.erl, apps/emqx_gateway_mqttsn/test/emqx_sn_protocol_SUITE.erl, apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl, changes/ce/fix-14243.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13485
=> fix: ensure all gateways call the client.connect hook

apps/emqx_gateway_jt808/src/emqx_gateway_jt808.app.src, apps/emqx_gateway_jt808/src/emqx_jt808_frame.erl, apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13530
- ~For internal contributor: there is a jira ticket to track this change~
- ~Change log has been added to `changes/` dir for user-facing …
=> JT/T808 Gateway: remove the tail zero bytes when parsing model, id, dev_id fileds

apps/emqx/src/emqx_release.erl, apps/emqx/test/emqx_release_tests.erl, changes/ee/feat-14251.en.md, mix.exs, rebar.config.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13414
=> Support emqx flavor

apps/emqx/src/emqx_persistent_session_ds/shared_subs_agent.hrl
=> fix(queue): enable queues for EE

apps/emqx/include/emqx.hrl, apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_logger.erl, apps/emqx/src/emqx_logger_textfmt.erl, apps/emqx/src/emqx_trace/emqx_trace_formatter.erl, apps/emqx/src/emqx_types.erl, apps/emqx/test/emqx_channel_tests.erl, apps/emqx/test/emqx_trace_formatter_tests.erl, changes/ce/feat-14247.en.md
Fixes [EMQX-13448](https://emqx.atlassian.net/browse/EMQX-13448)
[EMQX-13448]: https://emqx.atlassian.net/browse/EMQX-13448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 241119 ga multi-tenancy m1 logging metadata

apps/emqx/src/emqx_connection.erl, apps/emqx/test/emqx_connection_SUITE.erl, apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl, changes/ce/fix-14260.en.md
Fixes [EMQX-13533](https://emqx.atlassian.net/browse/EMQX-13533).
Release version: v5.8.3.
[EMQX-13533]: https://emqx.atlassian.net/browse/EMQX-13533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(conn): better tolerate not-yet-known ClientID when emitting stats

apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_producer_SUITE.erl, apps/emqx_dashboard/src/emqx_dashboard_admin.erl, apps/emqx_dashboard/src/emqx_dashboard_api.erl, apps/emqx_dashboard/src/emqx_dashboard_schema.erl, apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl, apps/emqx_dashboard/test/emqx_dashboard_admin_SUITE.erl, apps/emqx_dashboard/test/emqx_dashboard_api_test_helpers.erl, apps/emqx_dashboard/test/emqx_dashboard_haproxy_SUITE.erl, apps/emqx_dashboard_rbac/test/emqx_dashboard_rbac_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, changes/ce/feat-14255.en.md, rel/i18n/emqx_dashboard_api.hocon, rel/i18n/emqx_dashboard_schema.hocon
=> feat(dashboard): introduced password expiration for the Dashboard

apps/emqx/test/emqx_test_tls_certs_helper.erl
In CI, apparently this might take longer due to the constrained environment.
=> test: reduce test flakiness

apps/emqx/src/emqx_channel.erl, apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl
Release version: v5.9
Followup to #14211.
=> test(authn): drop artifical test-related expire delay

apps/emqx/rebar.config, apps/emqx/test/emqx_listeners_SUITE.erl, apps/emqx/test/emqx_mqtt_protocol_v5_SUITE.erl, apps/emqx/test/emqx_persistent_session_SUITE.erl, apps/emqx/test/emqx_takeover_SUITE.erl, apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl, apps/emqx_eviction_agent/test/emqx_eviction_agent_SUITE.erl, apps/emqx_node_rebalance/test/emqx_node_rebalance_evacuation_SUITE.erl, apps/emqx_retainer/rebar.config, changes/ce/fix-14266.en.md, mix.exs, rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-13415
=> chore: update emqtt to 1.13.5

apps/emqx/src/config/emqx_config_logger.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_conf/test/emqx_conf_schema_tests.erl, apps/emqx_enterprise/src/emqx_enterprise.app.src, apps/emqx_enterprise/src/emqx_enterprise_schema.erl, apps/emqx_enterprise/test/emqx_enterprise_schema_SUITE.erl, changes/ce/fix-14289.en.md
Fixes [EEC-1118](https://emqx.atlassian.net/browse/EEC-1118)
[EEC-1118]: https://emqx.atlassian.net/browse/EEC-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(config): do not resolve EMQX_LOG_DIR in config converter

apps/emqx_mysql/mix.exs, apps/emqx_mysql/rebar.config, changes/ee/fix-14294.md
Fixes https://emqx.atlassian.net/browse/EMQX-13587
Suppress OTP crash reports
=> fix: update mysql to 1.7.4.3

apps/emqx_resource/src/emqx_resource_pool.erl, changes/ce/fix-14296.en.md, mix.exs, rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-13586
=> chore: update ecpool to 0.5.12

apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_state.erl, apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
Fixes [EMQX-13555](https://emqx.atlassian.net/browse/EMQX-13555)
Unfortunately, in this branch the new test is no-op since keeping sessions in DS is still disabled with a compile flag.
But it will check the fixed code once we finally merge keeping sessions in the DS. 
I also checked the test & the code in the branch with that feature.
- [na] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files — no need, the feature is unreleased.
[EMQX-13555]: https://emqx.atlassian.net/browse/EMQX-13555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix subscription listing for DS-backed session state

apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_cm.erl, apps/emqx/src/emqx_external_trace.erl, apps/emqx_opentelemetry/include/emqx_otel_trace.hrl, apps/emqx_opentelemetry/src/emqx_otel_trace.erl, apps/emqx_opentelemetry/src/sampler/emqx_otel_sampler.erl
Fixes [EMQX-13600](https://emqx.atlassian.net/browse/EMQX-13600)
[EMQX-13600]: https://emqx.atlassian.net/browse/EMQX-13600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: trace broker send disconnect to clients

apps/emqx_bridge_pulsar/mix.exs, apps/emqx_bridge_pulsar/rebar.config, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl, apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_connector_SUITE.erl, apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl
See https://github.com/emqx/pulsar-client-erl/pull/68
Fixes https://emqx.atlassian.net/browse/EMQX-13572
Release version: e5.9
=> fix(pulsar): handle `Redirect` in `LookupTopicResponse`

apps/emqx_management/src/emqx_mgmt_auth.erl, changes/ce/fix-14313.en.md
=> fix(api_keys): only load bootstrap file on `core` node

apps/emqx/test/emqx_release_tests.erl
Unused testcase for emqx flavor.
=> fix: unused testcase for emqx flavor

apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl, apps/emqx_bridge_oracle/test/emqx_bridge_oracle_SUITE.erl, apps/emqx_bridge_pgsql/test/emqx_bridge_pgsql_SUITE.erl, apps/emqx_resource/src/emqx_resource_buffer_worker.erl, apps/emqx_resource/src/emqx_resource_manager.erl, changes/ce/fix-14319.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13599
Fixes https://github.com/emqx/emqx/issues/13979
- [na] ~Added tests for the changes~ relying on vast array of existing bridge tests
=> fix(resource manager): break "remove channels when disconnected" invariant from state machine

changes/v5.8.3.en.md
Sync with https://github.com/emqx/emqx-docs/pull/2754
=> docs: update changelog for 5.8.3

apps/emqx/src/emqx_cm.erl, apps/emqx/src/emqx_cm_registry.erl, apps/emqx/test/emqx_connection_conninfo_SUITE.erl, apps/emqx_eviction_agent/src/emqx_eviction_agent.app.src, apps/emqx_eviction_agent/src/emqx_eviction_agent.erl, apps/emqx_eviction_agent/test/emqx_eviction_agent_SUITE.erl, changes/ce/feat-14353.en.md
Fixes [EMQX-13628](https://emqx.atlassian.net/browse/EMQX-13628)
[EMQX-13628]: https://emqx.atlassian.net/browse/EMQX-13628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a workaround for eviction of sessions lost from `emqx_cm_registry`

apps/emqx_rule_engine/src/emqx_rule_engine.app.src, apps/emqx_rule_engine/src/emqx_rule_funcs.erl, apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl, changes/ce/feat-14369.en.md
=> feat(rule_engin): add two size-related functions

.ci/docker-compose-file/docker-compose-kafka.yaml, .ci/docker-compose-file/kafka/jaas2.conf, .ci/docker-compose-file/kafka/kafka-entrypoint.sh, .ci/docker-compose-file/kerberos/run.sh, .ci/docker-compose-file/toxiproxy.json, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl, apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl, changes/ee/fix-14375.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13643
Release version: e5.8.4
After the fix:
=> feat(kafka consumer): expose more error details when doing health checks / dry runs

changes/ce/feat-14360.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13660
=> docs: update changelog with known limitations

apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl
=> test(rabbitmq): fix flaky test case

rel/i18n/emqx_bridge_http_schema.hocon
Fixes https://askemq.com/t/topic/10345
=> docs: bad placeholder format

apps/emqx_opentelemetry/src/emqx_otel_trace.erl
=> fix(otel): message.qos override only for PUBLISH packet

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl, apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl
Fixes [<issue-or-jira-number>](https://emqx.atlassian.net/browse/ED-1701)
=> fix(iotdb): fix the schema errors of IoTDB template configuration

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_client.erl, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_consumer.erl, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_producer_SUITE.erl, changes/ee/fix-14427.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13692
=> fix(gcp pubsub producer): return pretty error messages on health check failures

apps/emqx_bridge_iotdb/rebar.config
=> chore: upgrade thrift driver

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl
=> fix(iotdb): handle unexpected payload format

apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl, apps/emqx_resource/src/emqx_resource_buffer_worker.erl, apps/emqx_rule_engine/src/emqx_rule_runtime.erl, changes/ce/fix-14429.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13699
=> fix(rule metrics): fix handling of `actions.failed.out_of_service` counters

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_schema_tests.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_subscriber_SUITE.erl, apps/emqx_resource/src/emqx_resource_manager.erl, changes/ce/feat-14404.en.md, rel/i18n/emqx_bridge_mqtt_connector_schema.hocon, scripts/spellcheck/dicts/emqx.txt
Fixes https://emqx.atlassian.net/browse/EMQX-12341
Fixes https://github.com/emqx/emqx/issues/8498
=> feat(mqtt connector): add support for specifying static clientids

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13653
See also: https://github.com/emqx/emqx-docs/pull/2781
=> test(mqtt action): add case asserting user property forwarding and manipulation

apps/emqx_bridge_clickhouse/src/emqx_bridge_clickhouse_connector.erl, apps/emqx_bridge_clickhouse/test/emqx_bridge_clickhouse_SUITE.erl, changes/fix-14419.en.md
Fixes [EMQX-13521](https://emqx.atlassian.net/browse/EMQX-13521)
[EMQX-13521]: …
=> fix: clickhouse split sql re

apps/emqx/src/emqx_exclusive_subscription.erl, changes/ce/fix-14424.en.md
=> fix(exclusive_sub): do not log membership message as unexpected

apps/emqx_bridge_tablestore/src/emqx_bridge_tablestore.erl
Fixes 
Release version: e5.8.4
=> fix: set "fields" as a required config

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_ingress.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_pubsub_action_info.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_pubsub_schema.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_subscriber_SUITE.erl, changes/ce/feat-14450.en.md, rel/i18n/emqx_bridge_mqtt_pubsub_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13594
Fixes https://github.com/emqx/emqx/issues/4545
=> feat(mqtt source): add support for no-local flag

apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl, apps/emqx_postgresql/rebar.config, apps/emqx_postgresql/src/emqx_postgresql.erl, changes/ee/fix-14451.en.md, mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-13306
See: https://github.com/emqx/epgsql/pull/12
=> fix(postgres action): handle bad timestamp params more gracefully

rel/i18n/emqx_bridge_iotdb.hocon
=> chore: fix schema descriptions of IoTDB

apps/emqx/src/emqx_broker_mon.erl, apps/emqx/src/emqx_broker_sup.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/src/emqx_sys_sup.erl, apps/emqx/test/emqx_broker_mon_SUITE.erl, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl, apps/emqx_prometheus/src/emqx_prometheus.erl, apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl, changes/ce/feat-14437.en.md, rel/i18n/emqx_schema.hocon, scripts/spellcheck/dicts/emqx.txt
Fixes https://emqx.atlassian.net/browse/EMQX-13681
=> feat: add new mailbox metrics to prometheus

apps/emqx_license/include/emqx_license.hrl, apps/emqx_license/src/emqx_license.app.src
=> chore: refine evaluation license warning message

apps/emqx/src/emqx_router_helper.erl, apps/emqx/src/emqx_router_sup.erl
Fixes [EMQX-11852](https://emqx.atlassian.net/browse/EMQX-11852)
Release version: v5.8.4
Followup to #14248.
[EMQX-11852]: https://emqx.atlassian.net/browse/EMQX-11852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(router): purge this node routes only during node startup

apps/emqx_gateway_exproto/src/emqx_gateway_exproto.app.src, apps/emqx_gateway_exproto/src/emqx_gateway_exproto.erl, apps/emqx_gateway_exproto/test/emqx_exproto_SUITE.erl, changes/ce/fix-14484.en.md
Fixes #14361 
Fixes EMQX-13651
=> fix(exproto): fixed hostname not be supported in the server endpoint

apps/emqx_gateway/include/emqx_gateway.hrl, apps/emqx_gateway/src/emqx_gateway.app.src, apps/emqx_gateway/src/emqx_gateway.erl, apps/emqx_gateway/src/emqx_gateway_http.erl, apps/emqx_gateway/src/emqx_gateway_sup.erl, apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl, changes/ce/fix-14489.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-10409
- ~Changed lines covered in coverage report
=> fix(gateway): avoid HTTP API access crashes when the gateway app is not started

.github/workflows/build_and_push_docker_images.yaml
=> ci: do not build -sf docker image version in CI

apps/emqx_management/src/emqx_mgmt_api_data_backup.erl, apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, changes/ce/feat-14496.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13769
- [na] ~~Schema changes are backward compatible~~  API is stricter now,
=> feat(data export api): validate root keys exist

apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src, apps/emqx_opentelemetry/src/emqx_otel_schema.erl, apps/emqx_opentelemetry/src/sampler/emqx_otel_sampler.erl, apps/emqx_opentelemetry/src/sampler/emqx_otel_sampler_api.erl, changes/fix-14466.en.md, rel/i18n/emqx_otel_schema.hocon
Fixes
[EMQX-13612](https://emqx.atlassian.net/browse/EMQX-13612)
[EMQX-13615](https://emqx.atlassian.net/browse/EMQX-13615)
[EMQX-13622](https://emqx.atlassian.net/browse/EMQX-13622)
[EMQX-13624](https://emqx.atlassian.net/browse/EMQX-13624)
- ~[ ] Change log has been added to `changes/` dir for …
=> fix: event option should always take effect before the ratio option

apps/emqx_gateway/src/emqx_gateway.app.src, apps/emqx_gateway/src/emqx_gateway_api_clients.erl, apps/emqx_gateway_coap/src/emqx_coap_channel.erl, apps/emqx_gateway_coap/src/emqx_gateway_coap.app.src, apps/emqx_gateway_coap/test/emqx_coap_SUITE.erl, apps/emqx_gateway_lwm2m/test/emqx_lwm2m_SUITE.erl, apps/emqx_gateway_mqttsn/test/emqx_sn_protocol_SUITE.erl, apps/emqx_gateway_stomp/src/emqx_gateway_stomp.app.src, apps/emqx_gateway_stomp/src/emqx_stomp_channel.erl, apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl, changes/ce/fix-14501.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13520
=> fix(gw): return correct keepalive value

apps/emqx_utils/test/emqx_utils_SUITE.erl
https://github.com/emqx/emqx/actions/runs/12709522509/job/35430539783
=> test(utils): stop assuming natural PID order

apps/emqx_bridge_couchbase/src/emqx_bridge_couchbase.app.src, apps/emqx_bridge_couchbase/src/emqx_bridge_couchbase_connector.erl, changes/ee/feat-14524.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13724
- [na] ~~Added tests for the changes~~ tested manually, see screenshots above.
=> feat(couchbase connector): return health check failure reasons

bin/emqx_fw, changes/ce/feat-14456.en.md, mix.exs, rebar.config.erl
Fixes EMQX-13735
tested manually in CDK. 
=> add emqx fw script

apps/emqx_prometheus/src/emqx_prometheus.erl, apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl, changes/ce/fix-14544.en.md
=> fix(prometheus): do not crash on disabled listeners

apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl, apps/emqx_conf/src/emqx_conf_cli.erl, apps/emqx_connector/src/emqx_connector.app.src, apps/emqx_connector/src/emqx_connector.erl, apps/emqx_connector/test/emqx_connector_SUITE.erl, apps/emqx_resource/src/emqx_resource_manager.erl, changes/ce/fix-14518.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13786
=> feat(connector config load): start connectors asynchronously when importing configurations

apps/emqx_gateway/src/emqx_gateway_api.erl, apps/emqx_gateway/src/emqx_gateway_conf.erl, apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl, changes/ce/fix-14503.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11426
=> fix(gw):  return empty list instead of 404 errors if no listeners existed

apps/emqx_gateway_stomp/src/emqx_gateway_stomp.app.src, apps/emqx_gateway_stomp/src/emqx_stomp_channel.erl, apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl, changes/ce/fix-14511.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-10465
=> fix(stomp): avoid printing unnecessary logs when authentication fails

apps/emqx_bridge_iotdb/mix.exs, apps/emqx_bridge_iotdb/rebar.config
=> chore: update IoTDB dependencies

apps/emqx/include/emqx_external_trace.hrl, apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_external_trace.erl, apps/emqx_auth/src/emqx_auth.app.src, apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl, apps/emqx_auth/src/emqx_authz/emqx_authz.erl, apps/emqx_opentelemetry/include/emqx_otel_trace.hrl, apps/emqx_opentelemetry/src/emqx_otel_trace.erl
Fixes [EMQX-13806](https://emqx.atlassian.net/browse/EMQX-13806)
- ~[ ] …
=> feat(e2e): authn/authz backend trace

apps/emqx_auth/src/emqx_auth.app.src, apps/emqx_auth/src/emqx_auth_utils.erl, apps/emqx_auth_http/src/emqx_auth_http.app.src, apps/emqx_auth_http/src/emqx_authn_http.erl, apps/emqx_auth_http/src/emqx_authz_http.erl, apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl, apps/emqx_auth_http/test/emqx_authz_http_SUITE.erl, changes/ce/feat-14570.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13208
=> feat: support placeholders in HTTP headers for http authz and authn

apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq.app.src, apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_connector.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_test_utils.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl, changes/ce/fix-14545.en.md
Fixes [EMQX-13747](https://emqx.atlassian.net/browse/EMQX-13747)
[EMQX-13747]: https://emqx.atlassian.net/browse/EMQX-13747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(rabbitmq): fix action termination in case channel is not responsive

apps/emqx/src/emqx_cm.erl, apps/emqx_license/src/emqx_license.app.src, apps/emqx_license/src/emqx_license_resources.erl, apps/emqx_license/test/emqx_license_SUITE.erl, apps/emqx_license/test/emqx_license_resources_SUITE.erl, changes/ee/fix-14568.en.md
Fixes [EMQX-13544](https://emqx.atlassian.net/browse/EMQX-13544)
[EMQX-13544]: https://emqx.atlassian.net/browse/EMQX-13544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(license): count sessions instead of connections

apps/emqx_bridge/src/emqx_action_info.erl, apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge/src/emqx_bridge_v2_api.erl, apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl, apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_action_info.erl, apps/emqx_bridge_hstreamdb/src/emqx_bridge_hstreamdb_action_info.erl, apps/emqx_bridge_http/src/emqx_bridge_http_action_info.erl, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_action_info.erl, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_producer_action_info.erl, apps/emqx_bridge_redis/src/emqx_bridge_redis_action_info.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl, apps/emqx_management/test/emqx_mgmt_data_backup_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13831
- add created_at to actions/sources and expose it in the summary API
- rename enabled to enable
- add description to the api response
- [na] ~~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~ this is a new, unreleased API.
=> chore: adjustments to actions/sources summary APIs

apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_ds_schema.erl, apps/emqx/src/emqx_persistent_message.erl, apps/emqx/src/emqx_persistent_session_ds.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_state.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/src/emqx_schema_hooks.erl, apps/emqx/test/emqx_common_test_helpers.erl, apps/emqx/test/emqx_cth_suite.erl, apps/emqx/test/emqx_log_throttler_SUITE.erl, apps/emqx/test/emqx_persistent_messages_SUITE.erl, apps/emqx/test/emqx_persistent_session_SUITE.erl, apps/emqx/test/emqx_persistent_session_ds_SUITE.erl, apps/emqx/test/emqx_persistent_session_ds_router_SUITE.erl, apps/emqx/test/emqx_persistent_session_ds_state_tests.erl, apps/emqx/test/emqx_takeover_SUITE.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl, apps/emqx_durable_storage/src/emqx_ds.erl, apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl, apps/emqx_management/test/emqx_mgmt_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_ds_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl, apps/emqx_retainer/src/emqx_retainer_schema.erl, scripts/ct/run.sh
Part of https://emqx.atlassian.net/browse/EMQX-11841
- [na] ~~Added tests for the changes~~ relies on existing tests being run on downstream repo.
- [na] ~~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~ This will only have an observable effect in the downstream repo.  It does not affect CE and EE builds.
=> feat(sessions in ds upstream): upstream changes for storing sessions in ds

apps/emqx/include/logger.hrl, apps/emqx/src/emqx_log_throttler.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_message_transformation/src/emqx_message_transformation.app.src, apps/emqx_message_transformation/src/emqx_message_transformation.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl, apps/emqx_schema_validation/src/emqx_schema_validation.app.src, apps/emqx_schema_validation/src/emqx_schema_validation.erl, changes/ee/feat-14589.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13812
=> Support more msgs in log throttling

apps/emqx_retainer/src/emqx_retainer.erl, apps/emqx_retainer/src/emqx_retainer_cli.erl, apps/emqx_retainer/src/emqx_retainer_mnesia.erl, apps/emqx_retainer/src/emqx_retainer_schema.erl, apps/emqx_retainer/test/emqx_retainer_SUITE.erl, apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl, apps/emqx_retainer/test/emqx_retainer_backend_SUITE.erl, apps/emqx_retainer/test/emqx_retainer_cli_SUITE.erl, apps/emqx_retainer/test/emqx_retainer_mqtt_v5_SUITE.erl, changes/ce/feat-14595.en.md
Fixes [EMQX-13519](https://emqx.atlassian.net/browse/EMQX-13519)
[EMQX-13519]: https://emqx.atlassian.net/browse/EMQX-13519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(retainer): deprecate retainer.enable flag

apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_license/include/emqx_license.hrl, apps/emqx_license/src/emqx_license.app.src, apps/emqx_license/src/emqx_license.erl, apps/emqx_license/src/emqx_license_checker.erl, apps/emqx_license/src/emqx_license_parser.erl, apps/emqx_license/src/emqx_license_parser_v20220101.erl, apps/emqx_license/test/emqx_license_SUITE.erl, apps/emqx_license/test/emqx_license_checker_SUITE.erl, apps/emqx_license/test/emqx_license_parser_SUITE.erl, changes/ee/feat-14590.en.md
Fixes [EMQX-13802](https://emqx.atlassian.net/browse/EMQX-13802)
[EMQX-13802]: https://emqx.atlassian.net/browse/EMQX-13802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(license): limit uptime to 1 month for evaluation license

apps/emqx_dashboard/src/emqx_dashboard.app.src, apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
close https://github.com/emqx/emqx/issues/14601
=> fix: use round instead of div for monitor_current rate calculation

apps/emqx_auth/include/emqx_authz.hrl, apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl, apps/emqx_auth/src/emqx_authz/emqx_authz_rule_raw.erl, apps/emqx_auth/src/emqx_authz/emqx_authz_utils.erl, apps/emqx_auth/test/emqx_authz/emqx_authz_rule_raw_SUITE.erl, apps/emqx_auth_mnesia/src/emqx_authz_api_mnesia.erl, apps/emqx_auth_mnesia/src/emqx_authz_mnesia.erl, apps/emqx_auth_mnesia/test/emqx_authz_api_mnesia_SUITE.erl, apps/emqx_auth_mnesia/test/emqx_authz_mnesia_SUITE.erl, apps/emqx_auth_mongodb/src/emqx_authz_mongodb.erl, changes/ce/feat-14610.en.md, rel/i18n/emqx_authz_api_mnesia.hocon
Fixes [EMQX-12247](https://emqx.atlassian.net/browse/EMQX-12247)
[EMQX-12247]: https://emqx.atlassian.net/browse/EMQX-12247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(authz): allow who filters in raw authz rules

apps/emqx/src/emqx_session_mem.erl, apps/emqx/test/emqx_session_mem_SUITE.erl, changes/ce/fix-14608.en.md
=> fix: ensure FIFO strategy in session_mem on full  mqueue

apps/emqx/include/emqx_external_trace.hrl, apps/emqx/src/emqx_broker.erl, apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_connection.erl, apps/emqx/src/emqx_external_trace.erl, apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl, apps/emqx_auth/src/emqx_authz/emqx_authz.erl, apps/emqx_opentelemetry/src/emqx_otel_trace.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl, apps/emqx_opentelemetry/test/emqx_otel_trace_SUITE.erl
Fixes Part1 of [EMQX-13846](https://emqx.atlassian.net/browse/EMQX-13846) …
=> test(otel): add e2e mode traces cases

apps/emqx_auth_http/test/emqx_authn_http_SUITE.erl, apps/emqx_auth_http/test/emqx_authn_scram_restapi_SUITE.erl, apps/emqx_auth_http/test/emqx_authz_http_SUITE.erl, apps/emqx_bridge_couchbase/src/emqx_bridge_couchbase_connector.erl, apps/emqx_bridge_couchbase/src/emqx_bridge_couchbase_connector_schema.erl, apps/emqx_bridge_couchbase/test/emqx_bridge_couchbase_SUITE.erl, apps/emqx_bridge_datalayers/src/emqx_bridge_datalayers.app.src, apps/emqx_bridge_datalayers/src/emqx_bridge_datalayers_connector.erl, apps/emqx_bridge_datalayers/test/emqx_bridge_datalayers_SUITE.erl, apps/emqx_bridge_es/src/emqx_bridge_es.app.src, apps/emqx_bridge_es/src/emqx_bridge_es_connector.erl, apps/emqx_bridge_es/test/emqx_bridge_es_SUITE.erl, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.erl, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_client.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_consumer_SUITE.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_producer_SUITE.erl, apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl, apps/emqx_bridge_http/test/emqx_bridge_http_v2_SUITE.erl, apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl, apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_connector_SUITE.erl, apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_action_schema.erl, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl, apps/emqx_connector/src/schema/emqx_connector_schema.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl, changes/ce/feat-14615.en.md, rel/i18n/emqx_connector_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13238
=> feat: add schema support for configuring `max_inactive` for ehttpc

apps/emqx/src/emqx_os_mon.erl, apps/emqx/test/emqx_olp_SUITE.erl, apps/emqx/test/emqx_os_mon_SUITE.erl, changes/ce/fix-14609.en.md, rel/i18n/emqx_bridge_azure_event_hub.hocon, rel/i18n/emqx_bridge_confluent_producer.hocon, rel/i18n/emqx_bridge_kafka.hocon, rel/i18n/emqx_bridge_pulsar.hocon
Fixes [EMQX-13857](https://emqx.atlassian.net/browse/EMQX-13857)
[EMQX-13857]: https://emqx.atlassian.net/browse/EMQX-13857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix olp memory protect threshold

.github/workflows/build_packages.yaml, .github/workflows/release.yaml, deploy/snap/snapcraft.yaml
Fixes [EMQX-13597](https://emqx.atlassian.net/browse/EMQX-13597)
Reference build_packages run: https://github.com/emqx/emqx/actions/runs/13034417569
[EMQX-13597]: https://emqx.atlassian.net/browse/EMQX-13597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Publish EMQX packages to SnapStore

apps/emqx_dashboard/src/emqx_dashboard_admin.erl, apps/emqx_dashboard/src/emqx_dashboard_schema.erl, apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl, changes/ce/feat-14638.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13863
=> feat(dashboard): support file secret for default password

.github/workflows/build_packages.yaml, .github/workflows/run_relup_tests.yaml, .tool-versions, apps/emqx_connector_aggregator/test/emqx_connector_aggreg_json_lines_tests.erl, changes/ce/feat-14639.md
Fixes EMQX-13447.
Release version: v5.9
=> chore: switch rest of workflows to use Erlang/OTP 27

apps/emqx_oracle/src/emqx_oracle.app.src, apps/emqx_oracle/src/emqx_oracle.erl, apps/emqx_oracle/src/emqx_oracle_schema.erl, changes/ee/fix-14560.en.md, rel/i18n/emqx_oracle.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13829
=> fix(oracle): fix oracle action health checks always failing in some cases

apps/emqx_gateway_stomp/README.md, apps/emqx_gateway_stomp/src/emqx_stomp_channel.erl, apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl
=> docs: fix stomp doc link

apps/emqx_opentelemetry/src/emqx_otel_schema.erl, apps/emqx_opentelemetry/src/emqx_otel_trace.erl, apps/emqx_opentelemetry/src/sampler/emqx_otel_sampler.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl, changes/ee/feat-14479.en.md, changes/ee/feat-14644.en.md, rel/i18n/emqx_otel_schema.hocon, scripts/spellcheck/dicts/emqx.txt
Fixes [EMQX-13869](https://emqx.atlassian.net/browse/EMQX-13869)
[EMQX-13869]: https://emqx.atlassian.net/browse/EMQX-13869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(otel): e2e trace follow traceparent

apps/emqx_connector/mix.exs, apps/emqx_redis/mix.exs, apps/emqx_redis/rebar.config, changes/ce/fix-14650.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13868
=> chore: update eredis_cluster to 0.8.8

apps/emqx_bridge/src/emqx_action_info.erl, apps/emqx_bridge_azure_blob_storage/test/emqx_bridge_azure_blob_storage_SUITE.erl, apps/emqx_bridge_disk_log/BSL.txt, apps/emqx_bridge_disk_log/README.md, apps/emqx_bridge_disk_log/mix.exs, apps/emqx_bridge_disk_log/rebar.config, apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log.app.src, apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log.hrl, apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log_action_info.erl, apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log_action_schema.erl, apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log_connector.erl, apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log_connector_info.erl, apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log_connector_schema.erl, apps/emqx_bridge_disk_log/test/emqx_bridge_disk_log_SUITE.erl, apps/emqx_bridge_s3/test/emqx_bridge_s3_aggreg_upload_SUITE.erl, apps/emqx_conf/src/emqx_conf_schema_inject.erl, apps/emqx_connector/src/emqx_connector_info.erl, apps/emqx_connector/src/schema/emqx_connector_schema.erl, apps/emqx_connector_aggregator/test/emqx_connector_aggreg_json_lines_test_utils.erl, apps/emqx_connector_aggregator/test/emqx_connector_aggreg_json_lines_tests.erl, apps/emqx_machine/priv/reboot_lists.eterm, changes/ee/feat-14642.en.md, mix.exs, rebar.config.erl, rel/i18n/emqx_bridge_disk_log_action_schema.hocon, rel/i18n/emqx_bridge_disk_log_connector_schema.hocon, scripts/elvis-check.sh
Fixes https://emqx.atlassian.net/browse/EMQX-13866
=> feat: add disk log connector and action

apps/emqx_gateway/src/emqx_gateway_api.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13867
=> chore: add swagger example for jt808

apps/emqx/test/emqx_persistent_session_SUITE.erl
Port of https://github.com/emqx/emqx/pull/14617
=> fix flaky test

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13873
=> docs(mqtt connector): add api example

apps/emqx_opentelemetry/src/sampler/emqx_otel_sampler.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl, changes/ee/feat-14657.en.md
Fixes [EMQX-13884](https://emqx.atlassian.net/browse/EMQX-13884)
[EMQX-13884]: https://emqx.atlassian.net/browse/EMQX-13884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: sampling the broker.publish by whitelist or ratio

apps/emqx_opentelemetry/src/emqx_otel_api.erl, apps/emqx_opentelemetry/src/emqx_otel_schema.erl, changes/ee/fix-14666.en.md
Fixes [EMQX-13905](https://emqx.atlassian.net/browse/EMQX-13905)
[EMQX-13905]: https://emqx.atlassian.net/browse/EMQX-13905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> fix: expose config entry opentelemetry.traces.max_queue_size

scripts/rel/delete-old-changelog.sh
use `git merge-base --is-ancestor`
=> chore: fix script delete-old-changelog.sh

apps/emqx_auth/src/emqx_auth_cache.erl
=> fix: lower auth cache update_state/cleanup log level to debug

.github/actions/package-macos/action.yaml, .github/actions/prepare-jmeter/action.yaml, .github/workflows/_pr_entrypoint.yaml, .github/workflows/_push-entrypoint.yaml, .github/workflows/build_and_push_docker_images.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_packages_cron.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/bump-dashboard-version.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/codeql.yaml, .github/workflows/green_master.yaml, .github/workflows/performance_test.yaml, .github/workflows/release.yaml, .github/workflows/rerun-apps-version-check.yaml, .github/workflows/run_conf_tests.yaml, .github/workflows/run_docker_tests.yaml, .github/workflows/run_emqx_app_tests.yaml, .github/workflows/run_helm_tests.yaml, .github/workflows/run_jmeter_tests.yaml, .github/workflows/run_relup_tests.yaml, .github/workflows/run_test_cases.yaml, .github/workflows/scorecard.yaml, .github/workflows/stale.yaml, .github/workflows/static_checks.yaml, .github/workflows/sync-release-branch.yaml, .github/workflows/update-emqx-docs.yaml, .github/workflows/upload-helm-charts.yaml
Fixes deprecated actions versions warning.
=> ci: bump actions versions

apps/emqx_auth/etc/acl.conf, apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl, apps/emqx_auth/test/emqx_authz/emqx_authz_rule_SUITE.erl, changes/ce/feat-14665.en.md
[EMQX-13881](https://emqx.atlassian.net/browse/EMQX-13881)
[EMQX-13881]: https://emqx.atlassian.net/browse/EMQX-13881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: support client attribute in ACL who() match condition

apps/emqx_exhook/priv/protos/exhook.proto, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/src/emqx_exhook_server.erl, apps/emqx_exhook/test/emqx_exhook_SUITE.erl, apps/emqx_exhook/test/emqx_exhook_demo_svr.erl, apps/emqx_exhook/test/props/prop_exhook_hooks.erl, changes/ce/feat-14679.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13469
=> feat: expose the User-Property to exhook server

apps/emqx/src/emqx_log_throttler.erl, apps/emqx_conf/src/emqx_conf_schema.erl, changes/ee/feat-14689.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13900
=> feat: throttle all msg types for msg transformation/validation

apps/emqx_management/src/emqx_mgmt_api_data_backup.erl, apps/emqx_management/src/emqx_mgmt_cli.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, changes/ce/feat-14691.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13914
=> feat(ctl): add root key and table set filters to cli data export

apps/emqx_connector/src/emqx_connector_api.erl, apps/emqx_connector/test/emqx_connector_api_SUITE.erl, changes/ce/fix-14695.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13887
=> fix(connector api): improve error validation error messages when updating

apps/emqx_bridge/src/emqx_bridge_lib.erl, apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl, changes/ce/fix-14697.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13889
=> fix(actions/sources): don't mix action/source dependencies when deleting

apps/emqx_rule_engine/src/emqx_rule_runtime.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13918
=> fix(rule metrics): don't attempt to increase inexistent metric

apps/emqx/src/emqx_ds_schema.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/src/emqx_schema_hooks.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_conf/src/emqx_conf_schema_inject.erl, apps/emqx_connector/src/schema/emqx_connector_schema.erl, apps/emqx_retainer/src/emqx_retainer_schema.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13888
- [na] ~~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~ unreleased feature
=> fix(mqtt connector): globally validate static clientid uniqueness

apps/emqx/src/emqx_alarm.erl, apps/emqx/test/emqx_alarm_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13917
=> fix(alarm): run hooks in a temporary process

apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13926
- [na] ~~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~ unreleased feature
=> fix: don't change modification and creation dates when replicating configs

apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl, changes/ee/fix-14705.en.md
Fixes [EMQX-13541](https://emqx.atlassian.net/browse/EMQX-13541)
[EMQX-13541]: https://emqx.atlassian.net/browse/EMQX-13541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kafka): improve connectivity check

apps/emqx_bridge_oracle/test/emqx_bridge_oracle_SUITE.erl, apps/emqx_oracle/src/emqx_oracle.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13907
- ~Change log has been added to `changes/` dir …
=> fix: correct handling of null and compatibility with more health checking errors

apps/emqx/test/emqx_cth_suite.erl, apps/emqx_connector/src/emqx_connector_api.erl, apps/emqx_connector/test/emqx_connector_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13929
=> fix(connector api): reduce value size when root validator fails

apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_subscriber_SUITE.erl, changes/ce/feat-14722.en.md, rel/i18n/emqx_bridge_mqtt_connector_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13930
=> fix(mqtt connector): allow customizing connect timeout

apps/emqx/src/emqx_schema_hooks.erl, apps/emqx/test/emqx_common_test_helpers.erl, apps/emqx_auth_cinfo/test/emqx_authn_cinfo_SUITE.erl, apps/emqx_bridge_azure_event_hub/test/emqx_bridge_azure_event_hub_tests.erl, apps/emqx_bridge_confluent/test/emqx_bridge_confluent_tests.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_tests.erl, apps/emqx_bridge_mongodb/test/emqx_bridge_mongodb_SUITE.erl, apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_connector_SUITE.erl, apps/emqx_enterprise/test/emqx_enterprise_schema_tests.erl, apps/emqx_telemetry/test/emqx_telemetry_SUITE.erl, apps/emqx_utils/src/emqx_utils.erl, bin/emqx, dev, scripts/merge-i18n.escript
Release v/e5.8.5
The performance issue is introduced in 5.8.5 dev commits, not released yet
=> perf: do not call Module:module_info/0 in hot path

apps/emqx_prometheus/src/emqx_prometheus.erl, apps/emqx_prometheus/src/emqx_prometheus_api.erl, apps/emqx_prometheus/src/emqx_prometheus_schema.erl, apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl, changes/ce/feat-14723.en.md, rel/i18n/emqx_prometheus_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13925
A follow-up fix for https://github.com/emqx/emqx/pull/14656.
- ~If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) …
=> fix(prometheus): add method option to support put opertaion to pushgateway

apps/emqx_management/src/emqx_mgmt_cli.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13932
Fixes https://emqx.atlassian.net/browse/EMQX-13931
- Adds missing root keys validation.
- Restores printing progress to CLI.
- Improves error message formatting.
- Adds new feature to allow specifying output dir for backup.
=> feat: data export improvements and fixes

apps/emqx/src/emqx_config_handler.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13938
- ~Added tests for the changes~ Just a refactor/performance-improvement. It's already covered by current tests
- ~If changed package build workflow, pass [this …
=> perf: do not fill useless roots

apps/emqx_schema_registry/src/emqx_schema_registry.app.src, apps/emqx_schema_registry/src/emqx_schema_registry_config.erl, apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl, changes/ee/fix-14736.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13943
=> fix(schema registry backup): merge new configs with old

apps/emqx_cluster_link/src/emqx_cluster_link.app.src, apps/emqx_cluster_link/src/emqx_cluster_link_app.erl, apps/emqx_cluster_link/src/emqx_cluster_link_router_syncer.erl, apps/emqx_cluster_link/test/emqx_cluster_link_SUITE.erl, changes/ee/fix-14738.en.md
Fixes [EMQX-13939](https://emqx.atlassian.net/browse/EMQX-13939).
[EMQX-13939]: https://emqx.atlassian.net/browse/EMQX-13939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(clink): foolproof routerepl actor's MQTT connection setup

apps/emqx/src/emqx_shared_sub.erl, apps/emqx/test/emqx_shared_sub_SUITE.erl, changes/ce/feat-14750.en.md
Fixes [EMQX-13923](https://emqx.atlassian.net/browse/EMQX-13923)
[EMQX-13923]: https://emqx.atlassian.net/browse/EMQX-13923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(shared_subs): fix statistics update

apps/emqx_durable_storage/src/emqx_ds_beamformer.erl, apps/emqx_durable_storage/src/emqx_ds_beamformer.hrl, apps/emqx_durable_storage/src/emqx_ds_beamformer_catchup.erl, apps/emqx_durable_storage/src/emqx_ds_beamformer_rt.erl
=> perf(dsbeamformer): Make handover between workers non-blocking

apps/emqx_bridge/src/emqx_bridge_v2_api.erl
Fixes https://emqx.atlassian.net/browse/EMQX-13946
=> docs: change returned message

apps/emqx/test/emqx_listeners_SUITE.erl
Prompted by https://emqx.atlassian.net/browse/EMQX-13858
=> test(listeners): add case using symlinks for certificates/keys

apps/emqx_modules/src/emqx_delayed.erl, apps/emqx_modules/src/emqx_modules.app.src, apps/emqx_modules/test/emqx_delayed_SUITE.erl, changes/ce/feat-14721.en.md
Fixes https://github.com/emqx/emqx/issues/14095 and [EMQX-13467](https://emqx.atlassian.net/browse/EMQX-13467)
[EMQX-13467]: https://emqx.atlassian.net/browse/EMQX-13467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: change delayed-publish interval limit from 49.7 days to 497 days

apps/emqx/priv/bpapi.versions, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/proto/emqx_mgmt_api_clients_proto_v1.erl, apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl, changes/ce/fix-14771.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13942
=> fix(list clients v2 api): return result set following desired batch size more strictly

apps/emqx_auth_jwt/src/emqx_authn_jwt.erl, apps/emqx_auth_jwt/test/emqx_authn_jwt_SUITE.erl, changes/ce/fix-14777.en.md
Fixes [EMQX-13961](https://emqx.atlassian.net/browse/EMQX-13961)
[EMQX-13961]: https://emqx.atlassian.net/browse/EMQX-13961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(jwt): correctly update configuration of jwt auth settings

apps/emqx/test/emqx_cth_cluster.erl, apps/emqx/test/emqx_cth_suite.erl, apps/emqx/test/emqx_quic_multistreams_SUITE.erl, apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft.app.src, apps/emqx_ds_builtin_raft/src/emqx_ds_replication_shard_allocator.erl, apps/emqx_ds_builtin_raft/test/emqx_ds_replication_SUITE.erl
=> test(dsraft): reduce "lost-quorum-rebalance" testcase flakiness

apps/emqx/test/emqx_cth_cluster.erl, apps/emqx/test/emqx_cth_peer.erl, apps/emqx_conf/src/emqx_conf_app.erl, apps/emqx_conf/test/emqx_conf_app_SUITE.erl, changes/ce/fix-14778.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13962
=> fix(conf app): don't attempt to sync bad files

apps/emqx/src/emqx_channel.erl, apps/emqx/test/emqx_channel_await_rel_expire_SUITE.erl, apps/emqx/test/emqx_mqtt_test_client.erl, changes/ce/fix-14815.en.md
Fixes [EMQX-13973](https://emqx.atlassian.net/browse/EMQX-13973)
Backport of https://github.com/emqx/emqx/pull/14814
[EMQX-13973]: https://emqx.atlassian.net/browse/EMQX-13973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(channel): fix expiration of awaiting rels 

scripts/ui-tests/dashboard_test.py
=> ci: update test after dashboard loading policy change

apps/emqx/src/emqx_ws_connection.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl, changes/ee/fix-14813.en.md
Fixes [EMQX-13971](https://emqx.atlassian.net/browse/EMQX-13971)
[EMQX-13971]: …
=> fix: e2e not traced for ws clients

.github/workflows/build-marketplace-ami.yaml
Need this workflow in master to be able to test changes in release branches.
=> ci: add build-marketplace-ami workflow

apps/emqx_management/src/emqx_mgmt_api_data_backup.erl, apps/emqx_management/src/proto/emqx_mgmt_data_backup_proto_v1.erl, apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, changes/ce/fix-14834.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13992
=> fix(data backup api): fix return type when downloading files

apps/emqx_auth_jwt/src/emqx_authn_jwks_client.erl, apps/emqx_auth_jwt/src/emqx_authn_jwt.erl, apps/emqx_auth_jwt/test/emqx_authn_jwt_SUITE.erl, changes/ce/fix-14847.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13996
Fixes https://github.com/emqx/emqx/issues/14842
=> fix(jwks authn): set correct `customize_hostname_check` SSL option for client

apps/emqx_rule_engine/src/emqx_rule_sqltester.erl, changes/ce/fix-14849.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13995
=> fix(sql rule tester): remove internal fields before applying rule

Makefile
=> chore: bump dashboard version to e1.8.6-beta.1

apps/emqx/mix.exs, apps/emqx_bridge_pulsar/mix.exs, apps/emqx_dashboard_sso/mix.exs, apps/emqx_oracle/mix.exs
=> build(new mix build): remove `Logger` from release

apps/emqx/include/emqx_release.hrl, deploy/charts/emqx-enterprise/Chart.yaml, deploy/charts/emqx/Chart.yaml, scripts/rel/cut.sh, scripts/rel/sync-remotes.sh
* update release scripts
* prepate for tagging 5.9.0-beta.1
=> chore: 5.9.0-beta.1

apps/emqx_exhook/src/emqx_exhook.erl, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/test/props/prop_exhook_hooks.erl, changes/ce/fix-14826.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11572
=> fix(exhook): fixed the return value of "IGNORE" was not taking effect

apps/emqx/rebar.config, apps/emqx_gateway/src/emqx_gateway_gw_sup.erl, apps/emqx_gateway/src/emqx_gateway_utils.erl, apps/emqx_gateway/test/emqx_gateway_authn_SUITE.erl, apps/emqx_gateway/test/emqx_gateway_conf_SUITE.erl, apps/emqx_gateway_coap/src/emqx_gateway_coap.erl, apps/emqx_gateway_coap/test/emqx_coap_SUITE.erl, apps/emqx_gateway_exproto/src/emqx_gateway_exproto.erl, apps/emqx_gateway_exproto/test/emqx_exproto_SUITE.erl, apps/emqx_gateway_gbt32960/src/emqx_gateway_gbt32960.erl, apps/emqx_gateway_gbt32960/test/emqx_gbt32960_SUITE.erl, apps/emqx_gateway_jt808/src/emqx_gateway_jt808.erl, apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl, apps/emqx_gateway_lwm2m/src/emqx_gateway_lwm2m.erl, apps/emqx_gateway_lwm2m/test/emqx_lwm2m_SUITE.erl, apps/emqx_gateway_mqttsn/src/emqx_gateway_mqttsn.erl, apps/emqx_gateway_mqttsn/test/emqx_sn_protocol_SUITE.erl, apps/emqx_gateway_ocpp/src/emqx_gateway_ocpp.erl, apps/emqx_gateway_ocpp/test/emqx_ocpp_SUITE.erl, apps/emqx_gateway_stomp/src/emqx_gateway_stomp.erl, apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl, changes/ee/feat-14845.en.md, mix.exs, rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-11612
Upgrade esockd to support options update for UDP listener: https://github.com/emqx/esockd/pull/201
- ~ Changed lines covered in coverage report~
- ~Change log has been added to `changes/` …
=> feat(gateway): Prevent unnecessary listener restarts during the gateway configuration update

apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/test/emqx_limiter_schema_SUITE.erl, apps/emqx/test/emqx_proper_types.erl, apps/emqx/test/props/prop_emqx_schema.erl, apps/emqx_conf/src/emqx_conf_schema_inject.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, apps/emqx_mt/src/emqx_mt.erl, apps/emqx_mt/src/emqx_mt_api.erl, apps/emqx_mt/src/emqx_mt_app.erl, apps/emqx_mt/src/emqx_mt_config.erl, apps/emqx_mt/src/emqx_mt_hookcb.erl, apps/emqx_mt/src/emqx_mt_limiter.erl, apps/emqx_mt/src/emqx_mt_state.erl, apps/emqx_mt/test/emqx_mt_api_SUITE.erl, apps/emqx_utils/src/emqx_utils_maps.erl, changes/ee/feat-14840.en.md, rel/i18n/emqx_mt_api.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13820
=> feat: multi-tenancy limiters

apps/emqx/src/emqx_schema.erl, rel/i18n/emqx_schema.hocon
=> docs: add listeners root doc

apps/emqx_gateway_jt808/src/emqx_jt808_schema.erl
A follow  up fixes for https://github.com/emqx/emqx/pull/14855
=> chore: correct the parameter type

apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_producer_SUITE.erl, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver.app.src, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl, changes/ee/fix-14880.en.md
Improve SQL Server health-check failure reason logging.
=> 250317 improve sqlserver connector healthcheck failure log 586

rel/i18n/emqx_jt808_schema.hocon
Follow-up for https://github.com/emqx/emqx/pull/14855/files
=> chore(jt808): fix docs

apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
=> fix(sqlserver): handle channel health-check result

apps/emqx/rebar.config, apps/emqx_management/src/emqx_mgmt_cli.erl, changes/ee/feat-14892.en.md, mix.exs, rebar.config
Fixes [EMQX-14032](https://emqx.atlassian.net/browse/EMQX-14032)
[EMQX-14032]: https://emqx.atlassian.net/browse/EMQX-14032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mria): Rebalance replicants/core nodes

apps/emqx/priv/bpapi.versions, apps/emqx/src/emqx_limiter/src/emqx_limiter_client_container.erl, apps/emqx_mt/src/emqx_mt.erl, apps/emqx_mt/src/emqx_mt_api.erl, apps/emqx_mt/src/emqx_mt_config.erl, apps/emqx_mt/src/emqx_mt_hookcb.erl, apps/emqx_mt/src/emqx_mt_limiter.erl, apps/emqx_mt/src/emqx_mt_schema.erl, apps/emqx_mt/src/emqx_mt_state.erl, apps/emqx_mt/src/proto/emqx_mt_config_proto_v1.erl, apps/emqx_mt/test/emqx_mt_SUITE.erl, apps/emqx_mt/test/emqx_mt_api_SUITE.erl, changes/ee/feat-14884.en.md, rel/i18n/emqx_mt_api.hocon, rel/i18n/emqx_mt_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-13821
Fixes https://emqx.atlassian.net/browse/EMQX-13822
=> feat(mt): add APIs to manage explicit namespaces

apps/emqx/src/emqx_cm.erl, apps/emqx/test/emqx_connection_conninfo_SUITE.erl, apps/emqx_eviction_agent/src/emqx_eviction_agent.erl, apps/emqx_eviction_agent/test/emqx_eviction_agent_SUITE.erl, apps/emqx_eviction_agent/test/emqx_eviction_agent_test_helpers.erl, changes/ce/feat-14907.en.md
Fixes [EMQX-14043](https://emqx.atlassian.net/browse/EMQX-14043)
[EMQX-14043]: https://emqx.atlassian.net/browse/EMQX-14043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(eviction): more aggressively discard invalid channels during eviction

apps/emqx/include/emqx_external_trace.hrl, apps/emqx/src/emqx_external_trace.erl, apps/emqx/src/emqx_topic.erl, apps/emqx_opentelemetry/include/emqx_otel_trace.hrl, apps/emqx_opentelemetry/src/emqx_otel_schema.erl, apps/emqx_opentelemetry/src/emqx_otel_trace.erl, apps/emqx_opentelemetry/src/sampler/emqx_otel_sampler.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl, apps/emqx_resource/src/emqx_resource_buffer_worker.erl, apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_events.erl, apps/emqx_rule_engine/src/emqx_rule_runtime.erl, apps/emqx_rule_engine/src/emqx_rule_sqltester.erl, changes/ee/feat-14876.en.md, rel/i18n/emqx_otel_schema.hocon
Fixes [EMQX-13994](https://emqx.atlassian.net/browse/EMQX-13994)
[EMQX-13994]: https://emqx.atlassian.net/browse/EMQX-13994?atlOrigin=eyJpIjo …
=> feat: rule engine e2e trace

.github/actions/package-macos/action.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_packages_cron.yaml, .github/workflows/build_slim_packages.yaml, changes/ee/feat-14930.en.md, scripts/rel/macos-sign-binaries.sh
Fixes [EMQX-13919](https://emqx.atlassian.net/browse/EMQX-13919)
Corresponding Build packages run: https://github.com/emqx/emqx/actions/runs/14088915291
[EMQX-13919]: https://emqx.atlassian.net/browse/EMQX-13919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: build macos-15 packages, simplify macos action

apps/emqx/src/emqx_sys.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_ingress.erl, apps/emqx_rule_engine/src/emqx_rule_events.erl, apps/emqx_rule_engine/test/emqx_rule_events_SUITE.erl, apps/emqx_utils/src/emqx_utils.app.src, apps/emqx_utils/src/emqx_utils_maps.erl, apps/emqx_utils/test/emqx_utils_maps_tests.erl
Release version: v5.9.0
- rule_event(connected) has `conn_prop/receive_maximum/client_attrs`, but sys_topic don't have.
- rule_event(disconnected) has `disconn_prop/client_attrs`, but sys_topic don't have.
- rename `emqx_rule_event:printable_maps/1` to `emqx_utils_maps:printable_props/1`
=> feat: add disconn_props/conn_props into sys topic

apps/emqx_conf/src/emqx_conf_cli.erl, changes/ee/fix-14977.en.md
Fixes [EMQX-13347](https://emqx.atlassian.net/browse/EMQX-13347)
[EMQX-13347]: https://emqx.atlassian.net/browse/EMQX-13347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ctl): display order

apps/emqx_management/src/emqx_mgmt_api_plugins.erl, apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl, apps/emqx_plugins/src/emqx_plugins.erl, apps/emqx_plugins/src/emqx_plugins_apps.erl, apps/emqx_plugins/test/emqx_plugins_SUITE.erl, changes/ce/feat-14972.en.md
Fixes [EMQX-14041](https://emqx.atlassian.net/browse/EMQX-14041)
[EMQX-14041]: https://emqx.atlassian.net/browse/EMQX-14041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(plugins): implement config upload/download

scripts/dev-cluster-host.sh
fix dev-cluster-host.sh for Linux which seems to be macOS only.
=> fix: dev cluster script for linux

apps/emqx_management/src/emqx_mgmt_api_plugins.erl, apps/emqx_management/src/proto/emqx_mgmt_api_plugins_proto_v4.erl, apps/emqx_plugins/src/emqx_plugins.erl, apps/emqx_plugins/src/emqx_plugins_fs.erl, apps/emqx_plugins/src/emqx_plugins_utils.erl, apps/emqx_plugins/test/emqx_plugins_SUITE.erl, changes/ce/fix-14774.en.md
Fixes [EMQX-10080](https://emqx.atlassian.net/browse/EMQX-10080)
- ~[ ] Added tests for the changes~ 
- another pr for cluster plugin sync tests …
=> Fix plugin cluster sync

apps/emqx/src/emqx_trace/emqx_trace.erl, apps/emqx_management/src/emqx_mgmt_api_trace.erl
Follow-up fixes: for https://github.com/emqx/emqx/pull/14794
=> chore(trace): Return the payload_limit in the trace info

.github/workflows/build_packages_cron.yaml
=> ci: update cron job to build release-59 branch

apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl
~Release version: 5.?~
reduce case groups to avoid executing redundant test cases.
cases run **210** -> **54**
=> test: reduce otel suite groups

apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.app.src, apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis_connector_client.erl, apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis_impl_producer.erl, apps/emqx_bridge_kinesis/test/emqx_bridge_kinesis_impl_producer_SUITE.erl, apps/emqx_resource/src/emqx_resource_pool.erl, changes/ee/fix-14989.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14071
=> fix(kinesis): reduce number of API calls during initialization and health checks

apps/emqx/src/emqx_channel.erl, apps/emqx/test/emqx_channel_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14073
=> fix(metrics): increase `messages.dropped` when bumping `messages.dropped.quota_exceeded`

apps/emqx_bridge_disk_log/src/emqx_bridge_disk_log_connector.erl, apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb.app.src, apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb_connector.erl, apps/emqx_bridge_http/test/emqx_bridge_http_connector_tests.erl, apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl, apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl, apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src, apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl, apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq.app.src, apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl, apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_proxy_server.erl, apps/emqx_cluster_link/src/emqx_cluster_link_mqtt.erl, apps/emqx_ldap/src/emqx_ldap.app.src, apps/emqx_ldap/src/emqx_ldap_bind_worker.erl, apps/emqx_redis/src/emqx_redis.app.src, apps/emqx_redis/src/emqx_redis.erl, apps/emqx_resource/src/emqx_resource.erl, apps/emqx_resource/src/emqx_resource_manager.erl, apps/emqx_resource/test/emqx_connector_demo.erl, apps/emqx_resource/test/emqx_resource_SUITE.erl, changes/ce/fix-14992.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14070
=> fix(resource manager): fix potential leak due to race

apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl, apps/emqx_connector/src/emqx_connector_resource.erl, apps/emqx_resource/src/emqx_resource_manager.erl, changes/ce/fix-15000.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14084
See individual commits and their messages.
- Avoid injecting "strange" keys into configurations.
- Ignore stale periodic channel health checks.
- Avoid always touching last modified at when updating root keys
=> various fixes for resource manager / connectors / actions / sources

.github/workflows/_pr_entrypoint.yaml, .github/workflows/run_docker_tests.yaml, .github/workflows/run_jmeter_tests.yaml, scripts/test/cluster-smoke-test.sh, scripts/test/start-two-nodes-in-docker.sh
A few tests were deleted by accident in https://github.com/emqx/emqx/pull/14785
=> ci: add back github action workflows deleted by accident

apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl, apps/emqx/test/emqx_proper_types.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14072
=> feat(limiter): support bytes (`B`) unit for rates

apps/emqx_exhook/src/emqx_exhook_mgr.erl, apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, changes/ee/fix-15018.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14099
=> fix(exhook): return non-list-wrapped root key

.github/workflows/run_jmeter_tests.yaml
the tests are rather opaque and hard to troubleshoot if they fail.
for the auth tests, i value their coverage with different database versions.
=> ci: delete advanced mqtt features tests using jmeter

apps/emqx_dashboard/src/emqx_dashboard_admin.erl, apps/emqx_dashboard/src/emqx_dashboard_api.erl, apps/emqx_dashboard/src/emqx_dashboard_app.erl, apps/emqx_dashboard/src/emqx_dashboard_login_lock.erl, apps/emqx_dashboard/src/emqx_dashboard_schema.erl, apps/emqx_dashboard/src/emqx_dashboard_sup.erl, apps/emqx_dashboard/test/emqx_dashboard_login_lock_SUITE.erl, changes/ce/feat-15014.en.md, rel/i18n/emqx_dashboard_schema.hocon
Fixes [EMQX-14093](https://emqx.atlassian.net/browse/EMQX-14093)
[EMQX-14093]: https://emqx.atlassian.net/browse/EMQX-14093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(dashboard): lock login after several unsuccessful attempts

deploy/packages/rpm/emqx.spec
Fixes "Build packages" https://github.com/emqx/emqx/actions/runs/14405269952/job/40400250433#step:4:513
```
rpmbuild -v -bb \
--define "_package_name emqx-enterprise" \
--define "_name emqx" \
--define "_topdir /tmp/emqx" \
--define "_version 5.9.0_beta.3" \
--define "_reldir /tmp/emqx/5.9.0-beta.3" \
--define "_post_addition %systemd_post %{_name}.service" \
--define "_preun_addition %systemd_preun %{_name}.service" \
--define "_sharedstatedir /var/lib" \
--define "_service_src /emqx/deploy/packages/rpm/emqx.service" \
--define "_service_dst %{_unitdir}/emqx.service" \
emqx.spec
error: License field must be present in package: (main package)
```
Successful run: https://github.com/emqx/emqx/actions/runs/14439343361
=> rpm packages require License field

.github/actions/package-macos/action.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_slim_packages.yaml
Backport workflow changes from release-59.
=> ci: fix macos build

scripts/test/cluster-smoke-test.sh, scripts/test/start-two-nodes-in-docker.sh
- fix environment variables names for LICENSE_KEY1,2
- make sure the script works correctly on slower machines
=> test: fix cluster-smoke-test

.github/workflows/build_packages_cron.yaml, scripts/rel/macos-sign-binaries.sh
follow up for #15005, add missing pieces from #14930
=> ci: fix macos sign binaries script

apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl, apps/emqx_schema_validation/src/emqx_schema_validation.app.src, apps/emqx_schema_validation/src/emqx_schema_validation_schema.erl, apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl, rel/i18n/emqx_schema_validation_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14127
=> feat(schema validation): add support for external http serde

apps/emqx/include/emqx_release.hrl, apps/emqx_license/include/emqx_license.hrl, deploy/charts/emqx-enterprise/Chart.yaml, deploy/charts/emqx/Chart.yaml
Fixes [EMQX-14134](https://emqx.atlassian.net/browse/EMQX-14134)
Also bump version to 5.9.0-beta.4
[EMQX-14134]: https://emqx.atlassian.net/browse/EMQX-14134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update community license banner

apps/emqx_mt/src/emqx_mt_api.erl, apps/emqx_mt/src/emqx_mt_client_kicker.erl, apps/emqx_mt/src/emqx_mt_state.erl, apps/emqx_mt/test/emqx_mt_api_SUITE.erl, rel/i18n/emqx_mt_api.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14147
=> feat(mt): delete implicit namespaces too

apps/emqx_connector_aggregator/src/emqx_connector_aggreg_delivery.erl
=> fix(connector aggregator): fix argument order after receiving unknown message

apps/emqx_rule_engine/src/emqx_rule_maps.erl, apps/emqx_rule_engine/src/emqx_rule_runtime.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, changes/ee/fix-15056.en.md
Fixes [EMQX-14141](https://emqx.atlassian.net/browse/EMQX-14141)
[EMQX-14141]: https://emqx.atlassian.net/browse/EMQX-14141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: rulesql foreach statement should try decode payload

rel/i18n/emqx_limiter_schema.hocon
Followup to https://github.com/emqx/emqx/pull/14773
- [na] The changes are covered with new or existing tests
=> chore(limiter): update schema field descriptions

apps/emqx/src/emqx_external_trace.erl, apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
follow #14876 
The feature havn't released, no changelog needed.
Since rule-test executing don't have few fields like `trigger`, `matched`, in `RichedRule`, and no `updated_at` in `Rule` 
=> fix: otel trace rulesql test executing

apps/emqx_bridge_tdengine/mix.exs, apps/emqx_bridge_tdengine/rebar.config, apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine.app.src, apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector.erl, apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector_info.erl, apps/emqx_bridge_tdengine/test/emqx_bridge_tdengine_SUITE.erl, changes/ee/fix-15051.en.md
Fixes
- https://emqx.atlassian.net/browse/EMQX-14100
- https://emqx.atlassian.net/browse/EMQX-14131
=> fix(tdengine): improve the error description

deploy/charts/emqx/templates/StatefulSet.yaml, deploy/charts/emqx/values.yaml
helmchart - add StatefulSet additionalAnnotations funcionality
=> feat: helmchart additional annotations for StatefulSet

.github/workflows/_push-entrypoint.yaml, changes/ce/breaking-14957.en.md
a manually trigged job for ref: https://github.com/emqx/emqx-i18n/pull/78
=> ci: update i18n auto-tranlation trigger job

changes/ce/feat-14791.en.md
=> chore: add changelog entry for #14791

rel/i18n/emqx_limiter_schema.hocon
Fixes [EMQX-14160](https://emqx.atlassian.net/browse/EMQX-14160).
[EMQX-14160]: https://emqx.atlassian.net/browse/EMQX-14160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(limiter): refine limiter schema descriptions

.github/actions/package-macos/action.yaml, .github/actions/prepare-jmeter/action.yaml, .github/workflows/_pr_entrypoint.yaml, .github/workflows/_push-entrypoint.yaml, .github/workflows/build_and_push_docker_images.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_packages_cron.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/bump-dashboard-version.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/performance_test.yaml, .github/workflows/run_conf_tests.yaml, .github/workflows/run_docker_tests.yaml, .github/workflows/run_emqx_app_tests.yaml, .github/workflows/run_helm_tests.yaml, .github/workflows/run_jmeter_tests.yaml, .github/workflows/run_relup_tests.yaml, .github/workflows/run_test_cases.yaml, .github/workflows/scorecard.yaml, .github/workflows/spellcheck.yaml, .github/workflows/static_checks.yaml, .github/workflows/sync-release-branch.yaml, .github/workflows/update-emqx-docs.yaml, scripts/bump-actions-versions.sh
=> Fix GitHub token usage in workflows

deploy/charts/emqx/values.yaml
=> fix(helm): make empty defaults consistent with examples

apps/emqx_auth_http/src/emqx_authz_http.erl
Fixes [EMQX-14140](https://emqx.atlassian.net/browse/EMQX-14140)
This is a followup fix for PR https://github.com/emqx/emqx/pull/14885 (5.9.0)
[EMQX-14140]: https://emqx.atlassian.net/browse/EMQX-14140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(http/authz): fix resource type typo

apps/emqx/rebar.config, changes/ee/fix-15087.en.md, mix.exs, rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-14157
See https://github.com/emqx/hocon/pull/307
=> fix(hocon): bump hocon -> 0.45.3

apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14163
- [na] ~~The changes are covered with new or existing tests~~ cannot test named instances in CI, tested manually
=> fix(sqlserver): fix instance name comparison

Makefile, build
Fixes [EMQX-8654](https://emqx.atlassian.net/browse/EMQX-8654)
[EMQX-8654]: https://emqx.atlassian.net/browse/EMQX-8654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> deny relup on macOS

.github/workflows/_pr_entrypoint.yaml, .github/workflows/run_boot_tests.yaml, scripts/test/emqx-boot.bats
Fixes [EMQX-9596](https://emqx.atlassian.net/browse/EMQX-9596)
[EMQX-9596]: https://emqx.atlassian.net/browse/EMQX-9596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add boot tests in CI

apps/emqx/src/emqx_external_trace.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl
Fixes [EMQX-14172](https://emqx.atlassian.net/browse/EMQX-14172)
introduced by #14840
[`emqx_channel:authentication_pipeline/2`](https://github.com/emqx/emqx/pull/14840/files#diff-27c0844d0e2116cd96569c34369a4b485d68529f0d21cb075c19f8bc5a59f477R2262-R2286)
havn't released, no change log needed.
=> fix: otel authn attrs function caluse

apps/emqx_mt/include/emqx_mt.hrl, apps/emqx_mt/include/emqx_mt_internal.hrl, apps/emqx_mt/src/emqx_mt_config.erl, apps/emqx_mt/src/emqx_mt_schema.erl, apps/emqx_mt/src/emqx_mt_state.erl, apps/emqx_mt/test/emqx_mt_SUITE.erl, apps/emqx_mt/test/emqx_mt_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14153
=> feat(mt): support backup export/import

.github/workflows/_push-entrypoint.yaml
=> ci(codecov): inherit secrets in the right job

apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl, apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl, changes/ee/fix-15109.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14171
=> fix(sqlserver): try to infer table not found error

.ci/docker-compose-file/docker-compose-kdc.yaml, .ci/docker-compose-file/docker-compose.yaml, .github/workflows/build_packages.yaml, .tool-versions, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl, bin/emqx, changes/ee/fix-15048.en.md, deploy/docker/Dockerfile, env.sh, scripts/buildx.sh, scripts/ct/run.sh
Fixes https://emqx.atlassian.net/browse/EMQX-14123
=> fix(odbc): avoid password leak during rare timeouts

apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl, apps/emqx_ds_builtin_local/src/emqx_ds_builtin_local.erl, apps/emqx_durable_storage/include/emqx_ds_metrics.hrl, apps/emqx_durable_storage/src/emqx_ds_beamformer.erl, apps/emqx_durable_storage/src/emqx_ds_beamformer_catchup.erl, apps/emqx_durable_storage/src/emqx_ds_beamformer_rt.erl, apps/emqx_durable_storage/src/emqx_ds_beamformer_waitq.erl, apps/emqx_durable_storage/src/emqx_ds_builtin_metrics.erl, apps/emqx_durable_storage/src/emqx_ds_lib.erl
Fixes [EMQX-14179](https://emqx.atlassian.net/browse/EMQX-14179)
[EMQX-14179]: https://emqx.atlassian.net/browse/EMQX-14179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ds): Optimize subscription hand-over in beamformer

apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14180
Follow up after https://github.com/emqx/emqx/pull/14849
One place where the test is called from was not patched in previous fix.
- [na] ~~The changes are covered with new or existing tests~~ tested manually
=> fix(sql tester): remove internal fields before running test

apps/emqx_dashboard_sso/src/emqx_dashboard_sso_saml_api.erl
=> fix: saml acs content type validation

apps/emqx_durable_storage/src/emqx_ds_builtin_metrics.erl, apps/emqx_prometheus/src/emqx_prometheus.erl
Fixes [EMQX-14199](https://emqx.atlassian.net/browse/EMQX-14199)
Add forgotten metrics to the prometheus collection callback. 
[EMQX-14199]: https://emqx.atlassian.net/browse/EMQX-14199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ds): Fix prometheus metric collection

apps/emqx/rebar.config.script, mix.exs, rebar.config.erl
~~Fixes <issue-or-jira-number>~~
build fix no functional changes.
=> quicer 0.2.5

apps/emqx_dashboard/src/emqx_dashboard_monitor.erl, apps/emqx_dashboard/src/emqx_dashboard_schema.erl, apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl, rel/i18n/emqx_dashboard_schema.hocon
Fixes [EMQX-14196](https://emqx.atlassian.net/browse/EMQX-14196)
[EMQX-14196]: https://emqx.atlassian.net/browse/EMQX-14196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 250429 take cluster max for hwmark value

apps/emqx_bridge_azure_blob_storage/README.md, apps/emqx_bridge_couchbase/README.md, apps/emqx_bridge_disk_log/README.md, apps/emqx_bridge_es/README.md, apps/emqx_bridge_greptimedb/README.md, apps/emqx_bridge_iotdb/README.md, apps/emqx_bridge_oracle/README.md, apps/emqx_bridge_s3/README.md, apps/emqx_bridge_snowflake/README.md, apps/emqx_connector_aggregator/README.md, apps/emqx_dashboard_rbac/README.md, apps/emqx_dashboard_sso/README.md, apps/emqx_gateway/README.md, apps/emqx_ldap/README.md, apps/emqx_mysql/README.md, apps/emqx_oracle/README.md, apps/emqx_postgresql/README.md, apps/emqx_redis/README.md, apps/emqx_retainer/README.md
Followup to https://github.com/emqx/emqx/pull/14953
Missed some occurrences in the previous cleanup 🙈 
Now checked with a script
```shell
../emqx-pre-commit-hooks/emqx_pre_commit_hooks/check_local_links.py apps/**/*.md
```
https://github.com/savonarola/emqx-pre-commit-hooks/blob/main/emqx_pre_commit_hooks/check_local_links.py
=> feat(license): remove dangling references to the licenses in READMEs

apps/emqx_connector_aggregator/src/emqx_connector_aggregator.app.src, apps/emqx_connector_aggregator/src/emqx_connector_aggregator.erl, apps/emqx_connector_aggregator/test/emqx_connector_aggregator_SUITE.erl, changes/ee/fix-15154.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14204
=> fix(aggregator): handle concurrent `close_buffer` and `next_buffer` events

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge_couchbase/src/emqx_bridge_couchbase.app.src, apps/emqx_bridge_couchbase/src/emqx_bridge_couchbase_connector.erl, apps/emqx_bridge_couchbase/test/emqx_bridge_couchbase_SUITE.erl, apps/emqx_bridge_datalayers/test/emqx_bridge_datalayers_SUITE.erl, apps/emqx_bridge_disk_log/test/emqx_bridge_disk_log_SUITE.erl, apps/emqx_bridge_dynamo/test/emqx_bridge_dynamo_SUITE.erl, apps/emqx_bridge_es/test/emqx_bridge_es_SUITE.erl, apps/emqx_bridge_http/test/emqx_bridge_http_v2_SUITE.erl, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl, apps/emqx_bridge_mysql/test/emqx_bridge_v2_mysql_SUITE.erl, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake.app.src, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl, apps/emqx_bridge_syskeeper/test/emqx_bridge_syskeeper_SUITE.erl, changes/ee/fix-15147.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14206
=> fix(actions): add missing template rendered trace invocations

apps/emqx_dashboard_sso/src/emqx_dashboard_sso.app.src, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc.erl, apps/emqx_dashboard_sso/test/emqx_dashboard_sso_oidc_tests.erl, apps/emqx_retainer/src/emqx_retainer.app.src, changes/ee/breaking-15156.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-12894
Previous crash after importing bogus config:
```
2025-05-02T19:07:37.496358+00:00 [error] Generic server emqx_dashboard_sso_oidc terminating. Reason: {badarg,[{unicode,characters_to_list,[{error,invalid_scheme,[]}],[{file,"unicode.erl"},{line,1219},{error_info,#{module => erl_stdlib_errors}}]},{httpc,normalize_and_parse_url,1,[{file,"httpc.erl"},{line,1151}]},{httpc,do_request,5,[{file,"httpc.erl"},{line,482}]},{oidcc_http_util,'-request/4-fun-0-',5,[{file,"/emqx/deps/oidcc/src/oidcc_http_util.erl"},{line,109}]},{telemetry,span,3,[{file,"/emqx/deps/telemetry/src/telemetry.erl"},{line,324}]},{oidcc_provider_configuration,load_configuration,2,[{file,"/emqx/deps/oidcc/src/oidcc_provider_configuration.erl"},{line,217}]}, …
```
=> fix(oidc): validate issuer is an URL

apps/emqx_mt/src/emqx_mt.app.src, apps/emqx_mt/src/emqx_mt_api.erl, apps/emqx_mt/test/emqx_mt_api_SUITE.erl, changes/ee/feat-15160.en.md, rel/i18n/emqx_mt_api.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14158
=> feat(mt): add bulk delete namespaces API

README-CN.md, README-RU.md, README.md
also remove docker pulls badge for emqx/emqx image
=> docs: remove openssf scorecard

apps/emqx_management/src/emqx_mgmt_api_listeners.erl, rel/i18n/emqx_mgmt_api_listeners.hocon
=> i18n vol4: add desc docs for listeners API

apps/emqx_connector_aggregator/test/emqx_connector_aggregator_SUITE.erl
Continuation of https://github.com/emqx/emqx/pull/15173#issuecomment-2864141800
=> test(aggregator): another attempt to fix flaky test

apps/emqx_rule_engine/src/emqx_rule_engine.app.src, apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_events.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_events_SUITE.erl, changes/ee/feat-15175.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13920
=> feat(rule engine): support matching event topics with wildcards

apps/emqx/src/emqx_banned.erl, apps/emqx_management/src/emqx_mgmt_api_banned.erl, apps/emqx_management/test/emqx_mgmt_api_banned_SUITE.erl, changes/ee/fix-15184.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14213
Release version: 5.9.1 or 5.10.0
=> fix(banned): Enhance the error message formating

.github/workflows/build_packages_cron.yaml, .github/workflows/bump-dashboard-version.yaml, .github/workflows/codeql.yaml, .github/workflows/green_master.yaml, .github/workflows/update-emqx-docs.yaml, Makefile, apps/emqx/include/emqx_release.hrl, apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft.app.src, apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft_meta.erl, deploy/charts/emqx-enterprise/Chart.yaml, scripts/pre-compile.sh, scripts/rel/cut.sh, scripts/rel/sync-remotes.sh
=> fix workflow syntax and prepare for 5.10.0-alpha.1

apps/emqx_bridge_dynamo/test/emqx_bridge_dynamo_SUITE.erl
https://github.com/emqx/emqx/actions/runs/14981477616/job/42086976701#step:4:380
=> test(dynamo): attempt to fix flaky test

apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_events.erl, apps/emqx_rule_engine/src/emqx_rule_sqltester.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_events_SUITE.erl, changes/ee/feat-15188.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-13922
=> feat(rule events): namespaced events

apps/emqx_ai_completion/src/emqx_ai_completion_client.erl, apps/emqx_ai_completion/src/emqx_ai_completion_config.erl, apps/emqx_ai_completion/src/emqx_ai_completion_schema.erl, apps/emqx_ai_completion/src/emqx_ai_completions/emqx_ai_completion_anthropic.erl, apps/emqx_ai_completion/src/emqx_ai_completions/emqx_ai_completion_openai.erl, apps/emqx_ai_completion/test/emqx_ai_completion_SUITE.erl, apps/emqx_ai_completion/test/emqx_ai_completion_api_SUITE.erl, apps/emqx_ai_completion/test/emqx_ai_completion_provider_mock.erl, apps/emqx_bridge_http/src/emqx_bridge_http.app.src, apps/emqx_bridge_http/src/emqx_bridge_http_action_info.erl, apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, apps/emqx_utils/src/emqx_utils_uri.erl, changes/ee/feat-15201.en.md, rel/i18n/emqx_ai_completion_schema.hocon
Fixes [EMQX-14254](https://emqx.atlassian.net/browse/EMQX-14254)
Release version: 5.10
Also slightly improved tests: HTTP client now makes actual requests (although to a mock HTTP service).
[EMQX-14254]: https://emqx.atlassian.net/browse/EMQX-14254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ai_completion): add custom base url for providers

.ci/docker-compose-file/docker-compose-elastic-search-tls.yaml, .ci/docker-compose-file/docker-compose-iceberg.yaml, apps/emqx_bridge_s3tables/test/emqx_bridge_s3tables_SUITE.erl, scripts/ct/run.sh
Timeout:
https://github.com/emqx/emqx/actions/runs/14999708850/job/42143821170?pr=15174#step:4:609
Random 500 error when container gets corrupt (missing `iceberg_tables` sqlite3 table?):
https://github.com/emqx/emqx/actions/runs/14999819267/job/42144202460?pr=15203#step:4:491
`nxdomain` error:
https://github.com/emqx/emqx/actions/runs/15002015015/job/42151747559?pr=15205#step:4:308
=> test(iceberg/s3tables): attempt to fix flaky test

apps/emqx/rebar.config, apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft.app.src, apps/emqx_durable_storage/src/emqx_durable_storage.app.src, apps/emqx_prometheus/src/emqx_prometheus.app.src, changes/ee/fix-15180.en.md, mix.exs, rebar.config
Fixes [EMQX-14261](https://emqx.atlassian.net/browse/EMQX-14261)
bring in https://github.com/emqx/ekka/pull/252, test is covered in ekka.
[EMQX-14261]: https://emqx.atlassian.net/browse/EMQX-14261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: mitigate the chance of getting channel registration deadlock.

.github/workflows/build_and_push_docker_images.yaml, apps/emqx_ds_builtin_raft/src/emqx_ds_builtin_raft.app.src, apps/emqx_durable_storage/src/emqx_durable_storage.app.src, apps/emqx_prometheus/src/emqx_prometheus.app.src, build, scripts/semver.sh, scripts/shelltest/semver.test
Fixes [EMQX-14235](https://emqx.atlassian.net/browse/EMQX-14235)
Build docker images workflow run: https://github.com/emqx/emqx/actions/runs/15021741499/job/42213267293
[EMQX-14235]: https://emqx.atlassian.net/browse/EMQX-14235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> publish enterprise docker image to emqx/emqx

apps/emqx_conf/src/emqx_conf_app.erl, apps/emqx_connector/src/schema/emqx_connector_schema.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, apps/emqx_schema_registry/mix.exs, apps/emqx_schema_registry/src/emqx_schema_registry.erl, apps/emqx_schema_registry/src/emqx_schema_registry_config.erl, apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl, apps/emqx_schema_registry/src/emqx_schema_registry_schema.erl, apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl, apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl, apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl, apps/emqx_schema_registry/test/protobuf_data/a.proto, apps/emqx_schema_registry/test/protobuf_data/b.proto, apps/emqx_schema_registry/test/protobuf_data/c.proto, apps/emqx_schema_registry/test/protobuf_data/c1.proto, apps/emqx_schema_registry/test/protobuf_data/missing.proto, apps/emqx_schema_registry/test/protobuf_data/traversal_attack.proto, changes/ee/feat-15174.en.md, rel/i18n/emqx_schema_registry_http_api.hocon, rel/i18n/emqx_schema_registry_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14089
=> feat(schema registry): support protobuf source bundles

apps/emqx_bridge_s3/test/emqx_bridge_s3_SUITE.erl, apps/emqx_bridge_s3/test/emqx_bridge_s3_aggreg_upload_SUITE.erl, apps/emqx_bridge_s3tables/src/emqx_bridge_s3tables_connector_schema.erl, apps/emqx_bridge_s3tables/test/emqx_bridge_s3tables_SUITE.erl, apps/emqx_connector/src/emqx_connector_schema_lib.erl, apps/emqx_ft/test/emqx_ft_conf_SUITE.erl, apps/emqx_s3/src/emqx_s3_schema.erl, apps/emqx_s3/test/emqx_s3_schema_SUITE.erl, apps/emqx_s3/test/emqx_s3_test_helpers.erl, rel/i18n/emqx_bridge_s3tables_connector_schema.hocon
- [na] For internal contributor: there is a jira ticket to track this change
=> fix(iceberg/s3tables): fix schema overrides and change default TLS

apps/emqx_ft/src/emqx_ft.app.src, apps/emqx_ft/src/emqx_ft_storage_fs_gc.erl, apps/emqx_ft/test/emqx_ft_storage_fs_gc_SUITE.erl
See https://github.com/emqx/emqx/pull/14994#discussion_r2033167363
=> test(ft): attempt to fix flaky test case

.ci/docker-compose-file/docker-compose-mongo-replicaset-tcp.yaml, .ci/docker-compose-file/docker-compose-mongo-sharded-tcp.yaml, scripts/ct/run.sh
https://github.com/emqx/emqx/actions/runs/15072605727/job/42373003340?pr=15222#step:4:119
=> ci(mongo): attempt to fix flaky container

apps/emqx/src/emqx_node_dump.erl, bin/node_dump
- make it compatible with Darwin
- filter out cowboy_swagger global_spec from app_env
=> chore: improve node_dump tool

apps/emqx_bridge_s3tables/src/emqx_bridge_s3tables_connector_info.erl, apps/emqx_bridge_s3tables/src/emqx_bridge_s3tables_connector_schema.erl, apps/emqx_bridge_s3tables/test/emqx_bridge_s3tables_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14289
=> fix(s3tables/iceberg): convert TLS certificates

apps/emqx/include/emqx_release.hrl, apps/emqx/src/emqx.app.src, deploy/charts/emqx-enterprise/Chart.yaml, deploy/charts/emqx/Chart.yaml
For https://emqx.atlassian.net/browse/EMQX-14276
=> chore: prepare to tag `e5.8.6-patch.14276`

apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14290
- [na] The changes are covered with new or existing tests (tested manually)
=> fix(schema registry api): fix nit about swagger request body format

apps/emqx_mt/src/emqx_mt_schema.erl, apps/emqx_mt/test/emqx_mt_schema_tests.erl, changes/ee/breaking-15239.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14291
=> fix(mt): `default_max_sessions` must be positive

.github/workflows/_push-entrypoint.yaml, .github/workflows/update-emqx-docs.yaml
=> ci: trigger update-emqx-docs workflow when docker images are ready

apps/emqx/src/emqx_hooks.erl, apps/emqx_mt/src/emqx_mt_app.erl, apps/emqx_mt/src/emqx_mt_config.erl, apps/emqx_mt/test/emqx_mt_SUITE.erl, changes/ee/fix-15242.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14270
=> fix(mt): load config and create limiter groups when (re)starting

apps/emqx/test/emqx_broker_SUITE.erl
emqx_broker_SUITE:connected_client_count_group.quic.t_connected_client_count_transient_takeover
snabbkaffe should look back for the events.
=> test: fix flaky:  broker t_connected_client_count_transient_takeover

apps/emqx/src/emqx_config_handler.erl, apps/emqx_dashboard_sso/src/emqx_dashboard_sso_manager.erl, apps/emqx_dashboard_sso/test/emqx_dashboard_sso_cli_SUITE.erl, changes/ee/fix-15247.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14296
=> fix(sso): handle config deletes

apps/emqx_schema_registry/src/emqx_schema_registry_schema.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14302
=> fix(schema registry api): hide protobuf bundle type from old endpoints

apps/emqx_mt/src/emqx_mt.erl, apps/emqx_mt/src/emqx_mt_api.erl, apps/emqx_mt/src/emqx_mt_state.erl, apps/emqx_mt/test/emqx_mt_api_SUITE.erl, changes/ee/feat-15253.en.md, rel/i18n/emqx_mt_api.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14271
=> feat(mt): add `created_at` info for namespaces

.ci/docker-compose-file/docker-compose-iceberg.yaml, apps/emqx/test/emqx_common_test_helpers.erl, apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge_s3tables/test/emqx_bridge_s3tables_SUITE.erl
Now using special wrapper process that allows restarting server on demand.
=> test: yet another attempt to work around flaky iceberg container

apps/emqx/rebar.config, mix.exs, rebar.config
Fixes [EMQX-14030](https://emqx.atlassian.net/browse/EMQX-14030)
[EMQX-14030]: https://emqx.atlassian.net/browse/EMQX-14030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bump ekka 0.22.1

mix.exs, rebar.config
Pin dependency to avoid conflict
=> chore(deps): pin unicode_util_compat

.ci/fvt_tests/http_server/rebar.config, apps/emqx_dashboard/mix.exs, apps/emqx_dashboard/src/emqx_dashboard.app.src, apps/emqx_dashboard/src/emqx_dashboard.erl, apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_mgmt_auth.erl, apps/emqx_management/test/emqx_mgmt_api_api_keys_SUITE.erl, mix.exs, rebar.config
Fixes [EMQX-14277](https://emqx.atlassian.net/browse/EMQX-14277)
Release version: 5.10
**Change minirest repo before merge**
[EMQX-14277]: https://emqx.atlassian.net/browse/EMQX-14277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(rbac): discard api actions based on handler, not HTTP path

apps/emqx/test/emqx_cm_SUITE.erl
=> test: do not fail the test for known bug EMQX-14081

apps/emqx_ai_completion/src/emqx_ai_completion_api.erl, apps/emqx_ai_completion/src/emqx_ai_completion_config.erl, apps/emqx_ai_completion/src/emqx_ai_completion_schema.erl, apps/emqx_ai_completion/test/emqx_ai_completion_api_SUITE.erl, apps/emqx_utils/src/emqx_utils_redact.erl
Fixes [EMQX-14328](https://emqx.atlassian.net/browse/EMQX-14328)
Release version: 5.10
[EMQX-14328]: https://emqx.atlassian.net/browse/EMQX-14328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ai_completion): allow updating provider without providing api_key

apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
Fix flaky schema registry test
=> chore: reduce test flakyness

.ci/docker-compose-file/otel/.gitignore, .ci/docker-compose-file/otel/otel-collector-config-tls.yaml, .ci/docker-compose-file/otel/otel-collector-config.yaml, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src, apps/emqx_opentelemetry/src/emqx_otel_metrics.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl, changes/ee/fix-15299.en.md
Fixes [EMQX-14335](https://emqx.atlassian.net/browse/EMQX-14335)
Release version: e5.8.x+
[EMQX-14335]: https://emqx.atlassian.net/browse/EMQX-14335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: otel metrics name trans badarg

apps/emqx_schema_registry/src/emqx_schema_registry.app.src, apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl, apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl, changes/ee/fix-15224.en.md
=> fix(external schema registry): deobfuscate passwords when updating (release-58)

apps/emqx_mt/src/emqx_mt_api.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14334
- [na] The changes are covered with new or existing tests
=> fix(mt api): fix swagger return type

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_schema.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_consumer_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14352
- [na] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files
=> fix: add `health_check_timeout` to gcp pubsub consumer

apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb.app.src, apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl, apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_SUITE.erl, changes/ee/fix-15331.en.md
Fixes [EMQX-14336](https://emqx.atlassian.net/browse/EMQX-14336)
Release version: 5.8.x+
[EMQX-14336]: https://emqx.atlassian.net/browse/EMQX-14336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: influxdb action without timestamp field

apps/emqx_gateway_nats/src/emqx_nats_channel.erl, apps/emqx_gateway_nats/test/emqx_nats_protocol_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14349
- ~Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files~
- ~Schema changes are backward compatible or intentionally breaking (describe the changes and the reasoning in the summary)~
=> fix(nats): Avoid to override an empty clientid

apps/emqx/src/emqx_schema.erl, apps/emqx_auth/src/emqx_authn/emqx_authn_password_hashing.erl, apps/emqx_auth_http/src/emqx_authz_http_schema.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl, apps/emqx_cluster_link/src/emqx_cluster_link_schema.erl, apps/emqx_management/src/emqx_mgmt_api_stats.erl, rel/i18n/emqx_authn_password_hashing.hocon, rel/i18n/emqx_bridge_mqtt_connector_schema.hocon, rel/i18n/emqx_cluster_link_schema.hocon, rel/i18n/emqx_mgmt_api_stats.hocon, rel/i18n/emqx_schema.hocon
=> 250603 i18n vol7

apps/emqx/src/emqx_schema.erl, apps/emqx/src/emqx_tls_lib.erl, apps/emqx_bridge_doris/src/emqx_bridge_doris_connector_schema.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl, apps/emqx_mysql/src/emqx_mysql.erl, changes/ee/feat-15348.en.md, rel/i18n/emqx_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14374
=> fix(doris tls): disable middlebox comp mode by default

.github/workflows/performance_test.yaml, .github/workflows/release.yaml, .github/workflows/update-emqx-docs.yaml, apps/emqx_auth_ldap/src/emqx_auth_ldap.app.src
* fix update-emqx-docs workflow
* fix snap packages upload in release workflow
* update performance test workflow to use latest framework version and to make it more reliable
=> fix ci issues

apps/emqx/include/emqx_release.hrl, deploy/charts/emqx-enterprise/Chart.yaml, deploy/charts/emqx/Chart.yaml
=> chore: bump version to 5.9.1-alpha.1

apps/emqx_bridge/src/emqx_bridge_v2_api.erl, apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl, changes/ee/feat-15371.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14373
=> feat(action api): add tags to summary and to individual action fallback actions

apps/emqx_resource/test/emqx_resource_SUITE.erl
https://github.com/emqx/emqx/actions/runs/15612435228/job/43977124576?pr=15374#step:5:808
```
%%% emqx_resource_SUITE ==> t_delete_and_re_create_with_same_name: FAILED
%%% emqx_resource_SUITE ==> {{panic,
#{msg => "Unexpected result",
result =>
{run_stage_failed,error,
{badmatch,
{timeout,
[#{msg => buffer_worker_enter_blocked,
'~meta' =>
#{node => 'test@127.0.0.1',pid => <0.257882.0>,
time => -576460601346891,gl => <0.254273.0>,
location =>
#Fun<emqx_resource_buffer_worker.11.119902237>},
buffer_worker => <0.257882.0>}]}},
[{emqx_resource_SUITE,
'-t_delete_and_re_create_with_same_name/1-fun-19-',0,
[{file,
"/__w/emqx/emqx/apps/emqx_resource/test/emqx_resource_SUITE.erl"},
{line,2234}]},
{emqx_resource_SUITE,t_delete_and_re_create_with_same_name,1,
[{file, …
```
=> test(resource): attempt to fix flaky test

apps/emqx_resource/src/emqx_resource_buffer_worker.erl, apps/emqx_resource/test/emqx_connector_demo.erl, apps/emqx_resource/test/emqx_resource_SUITE.erl, changes/ee/fix-15394.en.md
Caught by flaky test
https://github.com/emqx/emqx/actions/runs/15682826185/job/44179039749?pr=15387#step:5:15660
```
%%% emqx_resource_SUITE ==> t_async_reply_multi_eval: FAILED
%%% emqx_resource_SUITE ==>
Failure/Error: ?assertEqual(16, Success + Dropped + LateReply + Failed)
expected: 16
got: 19
line: 2607
comment: #{counters =>
#{success => 10,dropped => 0,matched => 16,failed => 9,
received => 0,retried => 3,'retried.success' => 0,
'retried.failed' => 3,late_reply => 0,
'dropped.expired' => 0,'dropped.queue_full' => 0,
'dropped.resource_not_found' => 0,
'dropped.resource_stopped' => 0,'dropped.other' => 0}}
```
Fixes https://emqx.atlassian.net/browse/EMQX-14395
=> fix(resource): do not bump counters if an unknown async reply is received

apps/emqx_gateway_nats/src/emqx_gateway_nats.app.src, apps/emqx_gateway_nats/src/emqx_nats_channel.erl, apps/emqx_gateway_nats/test/emqx_nats_protocol_SUITE.erl, changes/ee/fix-15342.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14366
Release version: 5.10.x or later versions
=> fix(nats): update feedvar to return binary for undefined values

apps/emqx_durable_storage/src/emqx_ds_lts.erl
Fixes [EMQX-14431](https://emqx.atlassian.net/browse/EMQX-14431)
Release version: 6.0
1. Only call threshold callback when inserting a new node
2. Handle a special case where threshold is 0: insert wildcard token immediately.
[EMQX-14431]: https://emqx.atlassian.net/browse/EMQX-14431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ds): Optimize LTS trie

apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
https://github.com/emqx/emqx/actions/runs/15827428159/job/44611902164?pr=15401#step:4:1280
=> test(kafka consumer): attempt to stabilize flaky test

Makefile
=> [5.8.7] bump emqx enterprise dashboard version

Makefile
=> [5.9.1] bump emqx enterprise dashboard version

apps/emqx_exhook/mix.exs, apps/emqx_mix_utils/lib/mix/tasks/compile.grpc.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.dialyzer.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.xref.ex, mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-14421
Release version: 6.0.?
- [na] The changes are covered with new or existing tests (manually tested)
- [na] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files
=> feat(new mix build): port xref check to mix task

apps/emqx_bridge_redis/test/emqx_bridge_redis_SUITE.erl
https://github.com/emqx/emqx/actions/runs/15931997140/job/44943621584?pr=15438#step:4:650
=> test(redis bridge): attempt to fix flaky test

apps/emqx_mix_utils/lib/mix/tasks/emqx.proper.ex, apps/emqx_retainer/mix.exs, mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-14417
=> feat(new mix build): make `mix proper` export coverage data

Makefile
=> chore: bump emqx-enterprise-dashboard version to e1.9.1

apps/emqx/test/emqx_limiter_shared_SUITE.erl, apps/emqx_auth/test/emqx_authn/emqx_authn_init_SUITE.erl, apps/emqx_auth_kerberos/mix.exs, apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl, apps/emqx_mix_utils/lib/mix/tasks/emqx.ct.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.static_checks.ex, apps/emqx_prometheus/mix.exs, mix, scripts/check-mix-exs-discrepancies.exs
Part of https://emqx.atlassian.net/browse/EMQX-10365
=> chore(new mix build): more fixes

apps/emqx_ai_completion/mix.exs, apps/emqx_ai_completion/src/emqx_ai_completion.app.src, apps/emqx_ai_completion/src/emqx_ai_completion_client.erl, apps/emqx_ai_completion/src/emqx_ai_completion_config.erl, apps/emqx_ai_completion/src/emqx_ai_completion_provider.erl, apps/emqx_ai_completion/src/emqx_ai_completion_schema.erl, apps/emqx_ai_completion/src/emqx_ai_completions/emqx_ai_completion_anthropic.erl, apps/emqx_ai_completion/src/emqx_ai_completions/emqx_ai_completion_openai.erl, apps/emqx_ai_completion/test/emqx_ai_completion_SUITE.erl, changes/ee/feat-15467.en.md, rel/i18n/emqx_ai_completion_schema.hocon
Fixes [EMQX-14316](https://emqx.atlassian.net/browse/EMQX-14316)
[EMQX-14316]: https://emqx.atlassian.net/browse/EMQX-14316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ai_completion): expose transport options

deploy/charts/emqx-enterprise/templates/_helpers.tpl, deploy/charts/emqx-enterprise/templates/configmap.yaml
=> fix: fix https://github.com/emqx/emqx/issues/15472

apps/emqx_bridge_bigquery/src/emqx_bridge_bigquery_impl.erl, apps/emqx_bridge_bigquery/test/emqx_bridge_bigquery_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14475
=> feat(bigquery): check for table/dataset access on each health check

apps/emqx_bridge/src/emqx_bridge_v2_api.erl, apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14373
Release version: 6.0.0-M1.202507
=> fix(actions api): correctly fetch fallback action tags

apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl, changes/ee/fix-15522.en.md
Fix elicited by https://emqx.atlassian.net/browse/EMQX-14499
Release version: 6.0.0-M1.202507
=> fix(snowflake): username is optional

.ci/docker-compose-file/docker-compose-otel.yaml, .ci/docker-compose-file/otel/otel-collector-config-tls.yaml, .ci/docker-compose-file/otel/otel-collector-config.yaml, apps/emqx_opentelemetry/src/emqx_otel_api.erl, apps/emqx_opentelemetry/src/emqx_otel_config.erl, apps/emqx_opentelemetry/src/emqx_otel_schema.erl, apps/emqx_opentelemetry/test/emqx_otel_SUITE.erl, changes/ee/feat-15364.en.md, rel/i18n/emqx_otel_schema.hocon
Pick #15364 to release-60.
fix Schema conflicts
```
2025-07-18T03:18:08.975195+00:00 [error] #{reason => unknown_fields,path => "opentelemetry.exporter",unknown => "headers",kind => validation_error,unmatched => "protocol"}
```
6.0.0-M1.202507
6.0.0-M2.202508
6.0.0
=> feat(otel): headers support in grpc request

apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl, apps/emqx_schema_registry/mix.exs, apps/emqx_schema_registry/src/emqx_schema_registry.app.src, apps/emqx_schema_registry/src/emqx_schema_registry_config.erl, apps/emqx_schema_registry/src/emqx_schema_registry_http_api.erl, apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl, apps/emqx_schema_validation/mix.exs, apps/emqx_schema_validation/src/emqx_schema_validation.app.src, apps/emqx_schema_validation/src/emqx_schema_validation.erl, changes/ee/feat-15525.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14443
=> feat(schema registry): forbid removal of serde if referenced

apps/emqx_conf/src/emqx_conf.app.src, apps/emqx_conf/src/emqx_conf_schema.erl, changes/ce/perf-15536.en.md, rel/i18n/emqx_conf_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14521
=> perf: disable global gc by default

.ci/fvt_tests/http_server/rebar.config, changes/ce/fix-15543.en.md, mix.exs, rebar.config
Fixes [EMQX-14524](https://emqx.atlassian.net/browse/EMQX-14524)
Release version: 5.10.x
[EMQX-14524]: https://emqx.atlassian.net/browse/EMQX-14524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(api): update minirest

apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_mgmt_data_backup.erl
Fixes [EMQX-14442](https://emqx.atlassian.net/browse/EMQX-14442)
Release version: 5.8.7, 5.9.1
- [na] The changes are covered with new or existing tests
- [na] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files (visible but  IMO not significant to mention).
[EMQX-14442]: https://emqx.atlassian.net/browse/EMQX-14442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(backup): reduce log level

apps/emqx/test/emqx_takeover_SUITE.erl
=> test(cm): simplify and stabilize `emqx_takeover_SUITE` testcases

apps/emqx/test/emqx_router_helper_SUITE.erl, mix.exs
=> test(route-helper): fix testcase flakiness

mix.exs
=> chore: update hackney

apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
Port of https://github.com/emqx/emqx/pull/15477
=> test(kafka consumer): greatly speed up test suite (r58)

apps/emqx_bridge_azure_event_hub/rebar.config, apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.app.src, apps/emqx_bridge_confluent/rebar.config, apps/emqx_bridge_kafka/rebar.config, changes/ee/feat-15585.en.md, mix.exs
Port of https://github.com/emqx/emqx/pull/15583
Fixes https://emqx.atlassian.net/browse/EMQX-14502
=> chore: bump brod -> 4.4.4 (release-58)

apps/emqx_ds_shared_sub/mix.exs, apps/emqx_eviction_agent/mix.exs
=> chore(mix): fix dependencies to avoid warnings

apps/emqx/rebar.config, apps/emqx_retainer/rebar.config, changes/ee/fix-15603.en.md, mix.exs, rebar.config
Fixes [EMQX-14540](https://emqx.atlassian.net/browse/EMQX-14540)
Release version: 6.0.0, 5.10.x
[EMQX-14540]: https://emqx.atlassian.net/browse/EMQX-14540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mqtt_bridge): update emqtt

.github/workflows/build_packages.yaml, .github/workflows/release.yaml, changes/ee/breaking-15613.en.md
Fixes [EMQX-14546](https://emqx.atlassian.net/browse/EMQX-14546)
[EMQX-14546]: https://emqx.atlassian.net/browse/EMQX-14546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> stop releasing Debian 10 packages

apps/emqx_bridge_kinesis/test/emqx_bridge_kinesis_v2_SUITE.erl
https://github.com/emqx/emqx/actions/runs/16630330733/job/47058470156#step:4:266
=> test(kinesis): attempt to stabilize flaky tests

apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_hookpoints.erl, apps/emqx_dashboard/src/emqx_dashboard_admin.erl, apps/emqx_dashboard/test/emqx_dashboard_admin_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_api_keys.erl, apps/emqx_management/src/emqx_mgmt_auth.erl, apps/emqx_mt/mix.exs, apps/emqx_mt/src/emqx_mt_hookcb.erl, apps/emqx_mt/test/emqx_mt_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14485
- [na] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files (part of a bigger epic)
=> chore(namespaces): check that managed namespaces exist when creating api actors

apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_management/src/emqx_mgmt_api_cluster.erl, apps/emqx_management/test/emqx_mgmt_api_cluster_SUITE.erl, changes/ee/feat-15600.en.md, rel/i18n/emqx_mgmt_api_cluster.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14516
=> feat: add cluster description

apps/emqx/src/emqx_trace/emqx_trace.erl, apps/emqx/src/emqx_trace/emqx_trace_handler.erl, apps/emqx/test/emqx_trace_SUITE.erl, apps/emqx/test/emqx_trace_handler_SUITE.erl, apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_trace.erl, apps/emqx_management/src/emqx_mgmt_cli.erl, apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
Part of [EMQX-14468](https://emqx.atlassian.net/browse/EMQX-14468).
Followup to #15594.
[EMQX-14468]: https://emqx.atlassian.net/browse/EMQX-14468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(trace): better separate trace concepts + make more consistent

apps/emqx/src/emqx_hookpoints.erl, apps/emqx_dashboard/src/emqx_dashboard_admin.erl, apps/emqx_dashboard/test/emqx_dashboard_admin_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_api_keys.erl, apps/emqx_management/src/emqx_mgmt_auth.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14549
- [na] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files (part of larger epic)
=> fix(namespaces): forbid changing namespace of existing users/api keys

apps/emqx_mix_utils/lib/mix/tasks/emqx.cover.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.ct.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.dialyzer.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.eunit.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.proper.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.static_checks.ex, apps/emqx_mix_utils/lib/mix/tasks/emqx.xref.ex, mix.exs
```
mix dialyzer           # Alias for emqx.dialyzer
mix do                 # Executes the tasks separated by plus
mix emqx.cover         # Run cover analysis
mix emqx.ct            # Run common tests
mix emqx.dialyzer      # Run dialyzer analysis
mix emqx.eunit         # Run eunit tests
mix emqx.proper        # Run proper tests
mix emqx.static_checks # Run static checks (xref, dialyzer, bpapi checks)
mix emqx.xref          # Run xref analysis
```
=> docs: add mix task docs

apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
https://github.com/emqx/emqx/actions/runs/16732854465/job/47365400521#step:5:302
```
%%% emqx_dashboard_monitor_SUITE ==> common.t_pmap_nodes: FAILED
%%% emqx_dashboard_monitor_SUITE ==>
Failure/Error: ?assertEqual(18, maps : get ( sent , lists : last ( Data ) ))
expected: 18
got: 30
line: 162
```
=> test(dashboard monitor): attempt to fix flaky test

apps/emqx/test/emqx_router_helper_SUITE.erl
=> test(router-helper): attempt to fix flakiness

apps/emqx_management/src/emqx_mgmt_cli.erl, apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
Fixes [EMQX-14564](https://emqx.atlassian.net/browse/EMQX-14564)
[EMQX-14564]: https://emqx.atlassian.net/browse/EMQX-14564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mgmt-cli): fix local trace listing

apps/emqx_mix_utils/lib/mix/tasks/emqx.eunit.ex
`eunit` is buggy when enumerating modules: the docs says that `{application, _}` uses the application's `.app` file to discover modules.  However, if we use just that, `eunit` sees both `mod` and `mod_test` in `.app`, and then decides to also add `mod_test` _again_, duplicating the tests being run.  So, as a workaround to this bug, we need to explicitly enumerate all modules.
Also, just enumerating all modules yield the same behavior.  We need to check if both `mod` and `mod_tests` exist, and remove the latter, since `eunit` will **always** add `mod_tests` given `mod`.
=> ci(eunit): workaround `eunit`'s duplication of modules

apps/emqx_bridge/test/emqx_bridge_testlib.erl, apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_connector.erl, apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_pubsub_schema.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_connector_SUITE.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_test_utils.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v1_SUITE.erl, apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl, changes/ee/feat-15637.en.md, rel/i18n/emqx_bridge_rabbitmq_pubsub_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-14480
=> feat(rabbitmq): add support for templating message headers and properties

apps/emqx/src/emqx_alarm.erl, apps/emqx_management/src/emqx_mgmt_api_alarms.erl, apps/emqx_management/test/emqx_mgmt_api_alarms_SUITE.erl, changes/ce/feat-15499.en.md, rel/i18n/emqx_mgmt_api_alarms.hocon
Fixes https://emqx.atlassian.net/browse/EEC-1217
Release version: e5.10.?
=> feat: Add a new HTTP API to deactivate alarms

apps/emqx/include/emqx_release.hrl, apps/emqx/src/emqx_alarm.erl, apps/emqx/src/emqx_metrics.erl, apps/emqx/test/emqx_metrics_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_alarms.erl, apps/emqx_management/test/emqx_mgmt_api_alarms_SUITE.erl, changes/ce/feat-15499.en.md, changes/ce/fix-15639.en.md, changes/ee/fix-15616.en.md, deploy/charts/emqx-enterprise/Chart.yaml, rel/i18n/emqx_metrics.hocon, rel/i18n/emqx_mgmt_api_alarms.hocon
prep for release `5.10.1-beta.1`
=> 280811 sync release-59

scripts/gen-elp-build-info.sh
~Release version:~
Like https://github.com/emqx/emqx/tree/master/scripts/gen-erlang-ls-config.sh
generate `build_info.json` for elp: https://github.com/WhatsApp/erlang-language-platform
See also: https://whatsapp.github.io/erlang-language-platform/docs/get-started/configure-project/custom-project/
=> chore: generate elp build_info.json file

.ci/docker-compose-file/docker-compose-toxiproxy.yaml
=> chore: rm toxiproxy export ports

apps/emqx_exhook/src/emqx_exhook.app.src, apps/emqx_exhook/src/emqx_exhook_server.erl, changes/ee/fix-15683.en.md
=> fix(exhook): grpc_client SSl options

apps/emqx/priv/bpapi.versions, apps/emqx/src/emqx.erl, apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_config_handler.erl, apps/emqx/test/emqx_config_handler_SUITE.erl, apps/emqx_auth_mnesia/test/emqx_authz_mnesia_SUITE.erl, apps/emqx_bridge/src/emqx_bridge_v2.erl, apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl, apps/emqx_conf/src/emqx_conf.erl, apps/emqx_conf/src/emqx_conf_app.erl, apps/emqx_conf/src/emqx_conf_cli.erl, apps/emqx_conf/src/proto/emqx_conf_proto_v5.erl, apps/emqx_conf/test/emqx_conf_cli_SUITE.erl, apps/emqx_conf/test/emqx_conf_cluster_sync_SUITE.erl, apps/emqx_connector/test/emqx_connector_SUITE.erl, apps/emqx_gateway_lwm2m/test/emqx_lwm2m_SUITE.erl, apps/emqx_gateway_lwm2m/test/emqx_lwm2m_api_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_configs.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl, apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl, apps/emqx_rule_engine/src/emqx_rule_engine_config.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_engine_cli_SUITE.erl, apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl, apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14382
Adds support for specifying namespaces when performing CLI operations such as config load/remove/show, as well as rule engine CLI ops.
- [na] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files (part of a bigger epic)
=> feat(conf cli): support namespace in configuration load/remove/show operations

apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src, apps/emqx_opentelemetry/src/emqx_otel_api.erl
Fixes [EMQX-14399](https://emqx.atlassian.net/browse/EMQX-14399)
[EMQX-14399]: https://emqx.atlassian.net/browse/EMQX-14399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: otel config api swagger example

scripts/gen-elp-build-info.sh
=> fix: output of `make test-compile` should not be include into json

changes/ee/fix-15614.en.md, mix.exs
- SSLKEYLOGFILE will also be updated for failed connection if sslkeylogfile is enabled
- fix prebuild nif lib for el7
- reduce the size of emqx quicer release package
Fixes [EMQX-14602](https://emqx.atlassian.net/browse/EMQX-14602)
6.0.0
[EMQX-14602]: https://emqx.atlassian.net/browse/EMQX-14602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quic): quicer 0.2.9

apps/emqx_bridge_cockroachdb/src/emqx_bridge_cockroachdb_action_schema.erl, apps/emqx_bridge_redshift/src/emqx_bridge_redshift_action_schema.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14599
=> docs(redshift & cockroachdb): change example sql

apps/emqx/src/emqx_config_handler.erl
Forgot to remove it in https://github.com/emqx/emqx/pull/15687
=> chore(namespace): rm unneeded dialyzer directive

apps/emqx_message_transformation/src/emqx_message_transformation.app.src, apps/emqx_message_transformation/src/emqx_message_transformation_config.erl, apps/emqx_message_transformation/test/emqx_message_transformation_http_api_SUITE.erl, apps/emqx_schema_validation/src/emqx_schema_validation.app.src, apps/emqx_schema_validation/src/emqx_schema_validation_config.erl, apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl, changes/ee/fix-15706.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14604
=> fix(schema validation & message transformation): reindex when deleting

apps/emqx_schema_registry/src/emqx_schema_registry.app.src, apps/emqx_schema_registry/src/emqx_schema_registry.erl, apps/emqx_schema_registry/src/emqx_schema_registry_external.erl, apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl, changes/ee/fix-15708.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14605
=> fix(external schema registry): load external schema registries on startup

apps/emqx_ai_completion/src/emqx_ai_completion.erl, apps/emqx_ai_completion/src/emqx_ai_completion_config.erl, apps/emqx_ai_completion/src/emqx_ai_completion_schema.erl, apps/emqx_ai_completion/src/emqx_ai_completions/emqx_ai_completion_anthropic.erl, apps/emqx_ai_completion/src/emqx_ai_completions/emqx_ai_completion_openai_response.erl, apps/emqx_ai_completion/test/emqx_ai_completion_SUITE.erl, apps/emqx_ai_completion/test/emqx_ai_completion_provider_mock.erl, changes/ee/feat-15724.en.md, rel/i18n/emqx_ai_completion_schema.hocon
Fixes [ED-2083](https://emqx.atlassian.net/browse/ED-2083)
On top of https://github.com/emqx/emqx/pull/15724, see the last commit.
[ED-2083]: https://emqx.atlassian.net/browse/ED-2083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ai_completion): correctly extract text from /response result

apps/emqx/src/emqx_persistent_message.erl, apps/emqx/src/emqx_persistent_session_ds/emqx_persistent_session_ds_state_v2.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/test/emqx_config_SUITE.erl, apps/emqx_durable_storage/src/emqx_ds_optimistic_tx.erl, apps/emqx_durable_timer/src/emqx_durable_timer.erl, apps/emqx_durable_timer/src/emqx_durable_timer_sup.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14074
- Make durable sessions' metadata transaction retry configurable
- Improve exit signal handling in several modules
=> Fix log spam by emqx_durable_timer

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl
https://github.com/emqx/emqx/actions/runs/17128294858/job/48586554675#step:4:102
=> test(gcp pubsub consumer): attempt to stabilize flaky test

apps/emqx/src/emqx_congestion.erl
```
2025-08-19T09:55:39.227861+00:00 [warning] clientid: f25899f5-1166-444b-bd46-5fdad28daffd, msg: unclean_terminate, peername: 192.168.2.3:37220, username: 矿卡#11, context: badarg, stacktrace: [{erlang,list_to_binary,[[99,111,110,110,95,99,111,110,103,101,115,116,105,111,110,47,“f25899f5-1166-444b-bd46-5fdad28daffd”,47,“矿卡#11”]],[{error_info,#{module => erl_erts_errors}}]},{emqx_congestion,do_cancel_alarm_congestion,4,[{file,“emqx_congestion.erl”},{line,106}]},{lists,foreach_1,2,[{file,“lists.erl”},{line,2310}]},{emqx_connection,terminate,2,[{file,“emqx_connection.erl”},{line,621}]},{proc_lib,wake_up,3,[{file,“proc_lib.erl”},{line,340}]}], exception: error
2025-08-19T09:55:39.228662+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: …
```
=> fix: crash congestion when username is unicode char

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_worker.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl
https://github.com/emqx/emqx/actions/runs/17307909920/job/49136279535?pr=15786#step:4:82
=> test(gcp pubsub consumer): attempt to fix flaky test

Makefile
=> chore: bump emqx-enterprise-dashboard version to e1.8.8

mix.exs, rebar.config
=ERROR REPORT==== 26-Aug-2025::07:04:52.865898 ===
Error in process <12319.11917364.0> on node 'emqx@192.168.96.46' with exit value:
{{case_clause,{port,#Port<12319.5349432>}},
[{observer_cli_process,'-render_link_monitor/3-lc$^1/1-1-',1,
[{file,"observer_cli_process.erl"},{line,294}]},
{observer_cli_process,render_link_monitor,3,
[{file,"observer_cli_process.erl"},{line,301}]},
{observer_cli_process,render_worker,7,
[{file,"observer_cli_process.erl"},{line,98}]}]}
Release version: 5.9.2
=> chore: update observer_cli dependency version to 1.8.4

.ci/docker-compose-file/docker-compose-kafka.yaml, .ci/docker-compose-file/kafka/jaas.conf, .ci/docker-compose-file/kafka/jaas2.conf, apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl, changes/ee/fix-15826.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14668
- [na] The changes are covered with new or existing tests
- tested manually; didn't add automated tests just yet to avoid conflicts with bridge v1 refactorings in master
=> fix(kafka consumer/source): treat group acl denied as healthy connection

apps/emqx/rebar.config, changes/ee/fix-15788.en.md, mix.exs, rebar.config
https://github.com/emqx/ekka/pull/258
=> update: bump ekka dependency version to 0.23.1 

apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_SUITE.erl
https://github.com/emqx/emqx/actions/runs/17472259934/job/49624282534?pr=15846#step:4:381
=> test(iotdb): stabilize flaky test

README.md
=> docs: rolling upgrade path from 5.8 to 5.9 or 5.10

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_oracle/src/emqx_oracle.erl, changes/ee/fix-15848.en.md
Part of https://emqx.atlassian.net/browse/EMQX-14024
Release version: 6.1.0
=> chore(oracle): improve disconnect reason

Makefile, apps/emqx_bpapi/test/emqx_bpapi_static_checks.erl, apps/emqx_management/src/emqx_mgmt_api_trace.erl, mix.exs
=> build: remove `include` dirs from release

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_publisher_SUITE.erl, apps/emqx_connector/src/emqx_connector.app.src, apps/emqx_connector/src/emqx_connector_api.erl
Fixes https://emqx.atlassian.net/browse/EMQX-14685
Fixes https://emqx.atlassian.net/browse/EMQX-14687
Release version: 5.8.9, 5.9.2, 5.10.1, 6.0.0
- [na] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files (unreleased new feature)
=> fix(mqtt connector): deobfuscate array with secrets, make validator accept atom keys

apps/emqx_durable_storage/src/emqx_ds_optimistic_tx.erl
Fixes [EMQX-14696](https://emqx.atlassian.net/browse/EMQX-14696)
[EMQX-14696]: https://emqx.atlassian.net/browse/EMQX-14696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: reduce tx flush debug logging

apps/emqx_durable_storage/src/emqx_ds_optimistic_tx.erl
Backport https://github.com/emqx/emqx/pull/15888 to release-60
=> feat: reduce debug logging

apps/emqx_durable_storage/src/emqx_ds.erl, apps/emqx_mq/src/emqx_mq_message_db.erl
Fixes [EMQX-14699](https://emqx.atlassian.net/browse/EMQX-14699)
[EMQX-14699]: https://emqx.atlassian.net/browse/EMQX-14699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mq): use parallel transactions for data removal

apps/emqx/rebar.config, apps/emqx_retainer/rebar.config, changes/ee/fix-15902.en.md, mix.exs, rebar.config
This included fixes for MQTT client to address issues in mqtt bridges.
- Respect PINGRESP timeout
- Fix hanging connection when TLS alert happens during `mqtt_connect`.
- Fix hanging connection when TLS disconnect happens during `mqtt_connect`
Release version: 5.8.9
=> upgrade to emqtt 1.13.8

apps/emqx_mq/src/emqx_mq_message_db.erl, apps/emqx_mq/test/emqx_mq_gc_SUITE.erl
Fixes [EMQX-14711](https://emqx.atlassian.net/browse/EMQX-14711)
[EMQX-14711]: https://emqx.atlassian.net/browse/EMQX-14711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mq): fix gc crash

apps/emqx_mq/src/emqx_mq_api.erl, apps/emqx_mq/src/emqx_mq_registry.erl, apps/emqx_mq/test/emqx_mq_api_SUITE.erl, apps/emqx_mq/test/emqx_mq_registry_SUITE.erl, apps/emqx_mq/test/emqx_mq_test_utils.erl
Fixes [EMQX-14708](https://emqx.atlassian.net/browse/EMQX-14708)
Release version:  6.0.0
[EMQX-14708]: https://emqx.atlassian.net/browse/EMQX-14708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mq): cleanup MQ index on unsuccessful queue state creation

apps/emqx/test/emqx_listeners_limits_SUITE.erl
Part of [EMQX-14720](https://emqx.atlassian.net/browse/EMQX-14720).
This PR adds a testcase that verifies message rate limit set on the listener level works as intended.
[EMQX-14720]: https://emqx.atlassian.net/browse/EMQX-14720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(listener): verify message rate limit works as intended

apps/emqx_auth_jwt/src/emqx_auth_jwt.app.src, apps/emqx_auth_jwt/src/emqx_authn_jwks_connector.erl, apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra_connector.erl, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl, apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl, apps/emqx_bridge_dynamo/test/emqx_bridge_dynamo_SUITE.erl, apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_consumer.erl, apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src, apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl, apps/emqx_bridge_snowflake/src/emqx_bridge_snowflake_connector.erl, apps/emqx_bridge_snowflake/test/emqx_bridge_snowflake_SUITE.erl, apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl, apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper.app.src, apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_client.erl, apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_connector.erl, apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector.erl, apps/emqx_bridge_tdengine/test/emqx_bridge_tdengine_SUITE.erl, apps/emqx_ldap/src/emqx_ldap.app.src, apps/emqx_ldap/src/emqx_ldap.erl, apps/emqx_mysql/src/emqx_mysql.erl, apps/emqx_oracle/src/emqx_oracle.erl, apps/emqx_postgresql/src/emqx_postgresql.erl, apps/emqx_resource/src/emqx_resource_pool.erl, changes/ee/feat-15944.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14024
Release version: 5.8.9, 5.9.2, 5.10.1, 6.0.0
=> feat(resources): improve errors returned by health check failures

apps/emqx_mq/src/emqx_mq_schema.erl, rel/i18n/emqx_mq_schema.hocon
Fixes [EMQX-14738](https://emqx.atlassian.net/browse/EMQX-14738)
[EMQX-14738]: https://emqx.atlassian.net/browse/EMQX-14738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(mq): unhide find_queue_retry_interval

apps/emqx/src/emqx_ds_schema.erl, apps/emqx_mq/README.md, apps/emqx_mq/src/emqx_mq_config.erl, apps/emqx_mq/src/emqx_mq_message_db.erl, apps/emqx_mq/src/emqx_mq_schema.erl, apps/emqx_mq/src/emqx_mq_state_storage.erl, apps/emqx_mq/test/emqx_mq_SUITE.erl, apps/emqx_mq/test/emqx_mq_api_SUITE.erl, apps/emqx_mq/test/emqx_mq_cluster_SUITE.erl, apps/emqx_mq/test/emqx_mq_consumer_SUITE.erl, apps/emqx_mq/test/emqx_mq_consumer_dispatchq_SUITE.erl, apps/emqx_mq/test/emqx_mq_gc_SUITE.erl, apps/emqx_mq/test/emqx_mq_registry_SUITE.erl, apps/emqx_mq/test/emqx_mq_test_utils.erl, rel/i18n/emqx_ds_schema.hocon, rel/i18n/emqx_mq_schema.hocon
Fixes [EMQX-14733](https://emqx.atlassian.net/browse/EMQX-14733)
~~- [ ] Schema changes are backward compatible or intentionally breaking (describe the changes and the reasoning in the summary)~~ Not, but the feature is not released
[EMQX-14733]: https://emqx.atlassian.net/browse/EMQX-14733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mq): move mq ds db configuration to the common durable_storage section

apps/emqx_license/src/emqx_license_resources.erl
Followup fix for PR https://github.com/emqx/emqx/pull/15921
In order NOT to reactivate alarm after manually deactivated, we should not take the history max as current TPS.
=> fix(license): allow manually deactivate max-tps alarm

.github/workflows/generate-changelog.yaml, scripts/generate-changelog.sh
Follow up on action in retrospective.
=> ci: add generate-changelog workflow

apps/emqx_mq/src/emqx_mq_api.erl, apps/emqx_mq/src/emqx_mq_message_db.erl, apps/emqx_mq/src/emqx_mq_registry.erl, apps/emqx_mq/src/emqx_mq_state_storage.erl, apps/emqx_mq/test/emqx_mq_SUITE.erl
Fixes [EMQX-14751](https://emqx.atlassian.net/browse/EMQX-14751)
[EMQX-14751]: https://emqx.atlassian.net/browse/EMQX-14751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mq): made deletions more robust

apps/emqx/src/emqx_schema.erl
Fixes [EMQX-14782](https://emqx.atlassian.net/browse/EMQX-14782)
- [~] The changes are covered with new or existing tests
[EMQX-14782]: https://emqx.atlassian.net/browse/EMQX-14782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(schema): add back deleted config fields as deprecated

.github/workflows/build_packages.yaml, .github/workflows/release.yaml, changes/ee/fix-16050.en.md
Fixes [EMQX-14791](https://emqx.atlassian.net/browse/EMQX-14791)
[EMQX-14791]: https://emqx.atlassian.net/browse/EMQX-14791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: stop releasing amzn2 packages

apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl, apps/emqx_bridge_rocketmq/test/emqx_bridge_rocketmq_SUITE.erl, changes/ee/breaking-16061.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14792
Release version: 6.0.1, 6.1.0
=> fix(rocketmq): use payload template (r60)

apps/emqx_mq/src/emqx_mq_consumer/emqx_mq_consumer_server.erl, apps/emqx_mq/test/emqx_mq_consumer_SUITE.erl
Fixes [EMQX-14796](https://emqx.atlassian.net/browse/EMQX-14796)
Release version: 6.0.1
[EMQX-14796]: https://emqx.atlassian.net/browse/EMQX-14796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mq): ignore late acks and pings from disconnected clients

apps/emqx_mq/src/emqx_mq_api.erl, apps/emqx_mq/src/emqx_mq_app.erl, apps/emqx_mq/src/emqx_mq_config.erl, apps/emqx_mq/src/emqx_mq_schema.erl, apps/emqx_mq/test/emqx_mq_api_SUITE.erl, apps/emqx_mq/test/emqx_mq_api_delayed_start_SUITE.erl, apps/emqx_mq/test/emqx_mq_api_helpers.erl, apps/emqx_mq/test/emqx_mq_consumer_SUITE.erl, rel/i18n/emqx_mq_schema.hocon
Fixes [EMQX-14794](https://emqx.atlassian.net/browse/EMQX-14794)
Release version: 6.0.1
[EMQX-14794]: https://emqx.atlassian.net/browse/EMQX-14794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mq): add configuration switch for disabling MQ

Makefile
=> chore: improve clean-all command

apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_hookpoints.erl, apps/emqx/src/emqx_metrics.erl, apps/emqx_rule_engine/src/emqx_rule_api_schema.erl, apps/emqx_rule_engine/src/emqx_rule_events.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl, changes/ee/feat-16099.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-14633
Release version: 6.1.0
=> feat(rule events): add `$events/client/ping` event for received `PINGREQ`s
