emqx/emqx

- CHANGES-5.0.md
- apps/emqx_exhook/rebar.config
- apps/emqx_exhook/src/emqx_exhook.app.src
- apps/emqx_exhook/src/emqx_exhook_server.erl
- apps/emqx_gateway/rebar.config
- mix.exs
- rebar.config
porting by: https://github.com/emqx/emqx/pull/8311
> fix(exhook): ensuring that exhook dispatches the client events are sequential

- CHANGES-5.0.md
- apps/emqx/src/emqx_logger_jsonfmt.erl
- apps/emqx_conf/i18n/emqx_conf_schema.conf
The formatter configuration parameter is always ignored when using json schema.
However, restrict char limiter if used for JSON mode, it will get a truncated incomplete json data, which is not practical and not recommended.
> fix: logger json formatter's config not working

- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
Github is dropping support for macos 10.15 in its CI at 2022-08-30.
> ci(mac): drop macos 10.15

- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
Accumulator becomes unusable after a `badrpc` error.
```
2022-07-21T15:22:17.825688-03:00 [warning] exception: error, line: 116, mfa: minirest_handler:apply_callback/3, path: /monitor_current, reason: {badmap,{badrpc,{'emqx@emqx-17.int.thales',{'emqx@emqx-17.int.thales',timeout}}}}, stacktrace: [{maps,get,[connections,{badrpc,{'emqx@emqx-17.int.thales',{'emqx@emqx-17.int.thales',timeout}}},0],[{file,"maps.erl"},{line,517},{error_info,#{module => erl_stdlib_errors}}]},{emqx_dashboard_monitor,'-merge_cluster_rate/2-fun-0-',3,[{file,"/emqx/apps/emqx_dashboard/src/emqx_dashboard_monitor.erl"},{line,259}]},{maps,fold_1,3,[{file,"maps.erl"},{line,410}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{emqx_dashboard_monitor,current_rate,0,[{file,"/emqx/apps/emqx_dashboard/src/emqx_dashboard_mon …
```
> fix: dashboard monitor crash after badrpc

- pkg-vsn.sh
Since upstream refuses to fix this issue:
https://github.com/elixir-lang/elixir/issues/12000
On rare occasions, our pre-release version, which is the prefix
of the git hash, might consist only of digits.  Even more rarely, it
might start with a `0`.  When that happens, Elixir will refuse to
parse that as a valid pre-release version (it wants it to be an
integer without a leading 0).
When that happens, we load our patched version that ignores this
check, since we want to interpret it as a string, not a number.
> chore(mix): patch mix version parser when it fails

- CHANGES-5.0.md
- apps/emqx/src/emqx_listeners.erl
- apps/emqx_dashboard/etc/emqx_dashboard.conf
- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_gateway/i18n/emqx_gateway_api_listeners_i18n.conf
- apps/emqx_gateway/src/emqx_gateway_api_listeners.erl
- apps/emqx_gateway/src/emqx_gateway_conf.erl
- apps/emqx_gateway/src/emqx_gateway_utils.erl
- apps/emqx_gateway/src/exproto/emqx_exproto_impl.erl
- apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_listeners.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/src/emqx_mgmt_util.erl
There are some an incompatible changes, but we had to fix the incorrect API formatting as soon as possible. A summary changes:
1. Using the standard `status` and `node_status` data format for `GET /listeners` and `GET /gateway/<name>/listeners`.
Before this changes, the MQTT  listener APIs returned these fields as:
```json
"status": {
"current_connections": 0,
"max_connections": 4096000
},
"node_status": {
"emqx@emqx-core-2.emqx-headless.default.svc.cluster.local": {
"current_connections": 0,
"max_connections": 512000
}
}
```
The Gateway listener API returned as:
```json
"node_status": [
{ "current_connections": 0,
"max_connections": 1024000,
"node": "emqx@emqx-core-2.emqx-headless.default.svc.cluster.local"
},
]
// No `status` field
```
In this PR, we unify these fields both listeners …
> Format the listeners API fields

- CHANGES-5.0.md
- apps/emqx_bridge/i18n/emqx_bridge_webhook_schema.conf
- apps/emqx_bridge/src/emqx_bridge.app.src
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/src/emqx_bridge_webhook_schema.erl
- apps/emqx_connector/i18n/emqx_connector_http.conf
- apps/emqx_connector/src/emqx_connector_http.erl
- mix.exs
- rebar.config
- scripts/relup-test/relup.lux
- the underlying ehttpc (0.3.0) not support the **connection max retry times** any more: it always set `retry = 0`.
- we use max_retries to indicate the **request max retry times** after failed.
The following warning logs keeping printed if before this fix:
```
022-07-27T09:10:14.719369+08:00 [warning] ehttpc: ehttpc unexpected_info: {gun_up,<0.3117.0>,http}
2022-07-27T09:10:14.731366+08:00 [warning] ehttpc: ehttpc unexpected_info: {gun_up,<0.3114.0>,http}
2022-07-27T09:10:14.735190+08:00 [warning] ehttpc: ehttpc unexpected_info: {gun_up,<0.3116.0>,http}
2022-07-27T09:10:14.735160+08:00 [warning] ehttpc: ehttpc unexpected_info: {gun_up,<0.3115.0>,http}
2022-07-27T09:10:19.649932+08:00 [warning] ehttpc: ehttpc unexpected_info: {gun_down,<0.3242.0>,http,closed,[],[]} …
```
> fix(webhook): the 'max_retries' opt means request retry times

- apps/emqx/priv/bpapi.versions
- apps/emqx/test/emqx_common_test_helpers.erl
- bin/emqx
- bin/nodetool
- lib-ee/emqx_license/etc/emqx_license.conf
- lib-ee/emqx_license/src/emqx_license.app.src
- lib-ee/emqx_license/src/emqx_license.erl
- lib-ee/emqx_license/src/emqx_license_resources.erl
- lib-ee/emqx_license/src/emqx_license_schema.erl
- lib-ee/emqx_license/src/proto/emqx_license_proto_v2.erl
- lib-ee/emqx_license/test/emqx_license_SUITE.erl
- lib-ee/emqx_license/test/emqx_license_checker_SUITE.erl
- lib-ee/emqx_license/test/emqx_license_cli_SUITE.erl
- lib-ee/emqx_license/test/emqx_license_installer_SUITE.erl
- lib-ee/emqx_license/test/emqx_license_parser_SUITE.erl
- lib-ee/emqx_license/test/emqx_license_parser_legacy_SUITE.erl
- lib-ee/emqx_license/test/emqx_license_resources_SUITE.erl
- Changed license schema to allow changing the type. Before this
change, if a license in `emqx.conf` was of type `key`/`file` and then
changed to the opposite type, such change would be saved to
`{cluster,local}-overrides.conf`.  When the node restarts after that,
the configs are merged naively and becomes invalid, as it contains
both the `key` and `file` keys, and crashes.
- Now, when (re)loading a license, it'll be copied to all nodes in the
cluster and set to a common path relative to the data dir (ex: if
data dir is `data`, the common path will be
`data/licenses/emqx.lic`).  Before, (re)loading a license file would
only update the license in the node issuing the command.
> license fixes (5.0)

- rebar.config
In order to print the stacktrace of the killed process by holding ekka_locker too long
diffs: https://github.com/emqx/ekka/commit/41618485655a13de8af16f48d0f193477df9b1dd
> chore: update ekka to 0.7.11

- .github/workflows/build_packages.yaml
- bin/emqx
- build
- deploy/docker/Dockerfile
- rebar.config.erl
- scripts/emqx_rel_otp_app_overwrite.escript
- scripts/rel_otp_apps.eterm
rpm/deb: build packages with two tracks: 23.2 and 23.3
- Track 1: Add 23.3, bring in fix of https://github.com/erlang/otp/issues/5346
- Track 2: Keep 23.2 for the test
The `relup` file generated by 23.3 & 23.2 should be identical. 
docker:
Default to 23.3
> [WIP] ci: [4.3 only] release with OTP 23.3

- apps/emqx_dashboard/src/emqx_dashboard_listener.erl
- apps/emqx_dashboard/src/emqx_dashboard_middleware.erl
- mix.exs
- rebar.config
fix:
2022-07-29T05:45:39.832860+00:00 [error] crasher: initial call: cowboy_stream_h:request_process/3, pid: <0.2724.0>,
registered_name: [], exit: {{{timeout,{gen_server,call,[emqx_dashboard_listener,is_ready,15000]}},[{gen_server,call,3,
[{file,"gen_server.erl"},{line,247}]},{emqx_dashboard_listener,is_ready,1,[{file,"emqx_dashboard_listener.erl"},{line,41}]},
{emqx_dashboard_middleware,execute,2,[{file,"emqx_dashboard_middleware.erl"},{line,24}]},
{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,
[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},[{gen_server,call,3,
[{file,"gen_server.erl"},{line,247}]},{emqx_dashboard_listener,is_ready,1,[{file,"emqx_dashboard_listener.erl …
> fix: return 503 instead of crash when dashboard generate router timeout

- CHANGES-5.0.md
- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/src/emqx_mgmt_api_nodes.erl
`/gateway`'s status is all lowercase. `running/unloaded`.
but `/nodes/`'s status is `Running/Stopped`.
To make all APIs more standardized.
we should keep the status enum as lowercase.
> chore: update Running/Stopped to running/stopped

- build
- scripts/emqx_rel_otp_app_overwrite.escript
- scripts/fail-on-old-otp-version.escript
the rel file name is always emqx.rel, has nothing to do with profile
> build: fix relup app overwrite escript

- scripts/emqx_rel_otp_app_overwrite.escript
- scripts/fail-on-old-otp-version.escript
- scripts/update_appup.escript
On some systems, like `centos7`, `env` does not have a `-S` option.
> fix: rm non-portable `env` option

- CHANGES-5.0.md
- apps/emqx/i18n/emqx_schema_i18n.conf
- apps/emqx/rebar.config
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_schema_tests.erl
- mix.exs
- rebar.config
Connecting 1000 `emqtt-bench` subscribers with SSL.  Computing the difference of results of `erlang:memory()` before and after all clients are connected.
|  | `processes_used` | `total` |
|--|------------------|---------|
| mem increase without gc after handshake (bytes) | `177894208` | `190032440` |
| mem increase with gc after handshake (bytes) | `108428752` | `113740224` |
| `mem(with gc) / mem(without gc)` | `0.662` | `0.728` |
> feat: add option to gc after TLS/SSL handshake

- CHANGES-4.3.md
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.appup.src
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia_api.erl
- apps/emqx_auth_mnesia/test/emqx_auth_mnesia_SUITE.erl
- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_api.erl
The `emqx_user` table integrates 2 types of user information, `client_id` and `username`,  the count is not correct when looking for one of these types.
So we use the custom count function to support `ets:select_count/2`.
> fix: support custom count function

- CHANGES-4.4.md
- apps/emqx_plugin_libs/src/emqx_plugin_libs.app.src
- apps/emqx_plugin_libs/src/emqx_plugin_libs.appup.src
- apps/emqx_plugin_libs/src/emqx_trace/emqx_trace.erl
- apps/emqx_plugin_libs/src/emqx_trace/emqx_trace_api.erl
We allow `emqx_mod_trace` to be enabled on only some nodes in the cluster on 4.4.x
When the module is disabled, we need to correctly indicate that the module is not turned on.
> fix: check if trace is enabled when the file is not found

- apps/emqx/src/emqx_connection.erl
- apps/emqx/test/emqx_connection_SUITE.erl
According to MQTT spec, MQTT Server should check a complete MQTT message
recv in last keep-alive time frame instead of the number of received bytes
from the socket.
This commit change to check the recv pkt counter from process dict
instead.
Also it could save some calls to erlang port.
> fix: keep alive check

- CHANGES-5.0.md
- apps/emqx_gateway/src/emqx_gateway.app.src
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_cmd.erl
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_message.erl
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_xml_object.erl
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_xml_object_db.erl
- apps/emqx_gateway/test/emqx_lwm2m_SUITE.erl
Prior to this change, unknown object IDs would result in a tuple
{error, no_xml_definition}, and this tuple is passed down to xmerl
lib to get XML node data and eventually crash with function_clause.
With this fix, the unknown object ID exception is caught and logged
properly.
port from: https://github.com/emqx/emqx/pull/8654
> fix(lwm2m): better logging for unknown object IDs

- .github/workflows/build_packages.yaml
only EMQX 5.0 image can update latest tag
> ci: cancel latest tag for docker image

- CHANGES-4.3.md
- apps/emqx_exproto/src/emqx_exproto.app.src
- apps/emqx_exproto/src/emqx_exproto.appup.src
- apps/emqx_exproto/src/emqx_exproto_channel.erl
- chore(exproto): start idle timer for udp clients
- chore: update app.src & appup.src
> Fix(exproto): start idle timer to avoid client leaking

- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_msg.erl
fix https://github.com/emqx/emqx/issues/8494
> fix: count all msg size of `event_message` for mqtt bridge

- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_cli_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_ct_helper.erl
- apps/emqx_retainer/test/mqtt_protocol_v5_SUITE.erl
- src/emqx_plugins.erl
- test/emqx_plugins_SUITE.erl
emqx_modules is not a plugin, but a permanent application when emqx boots. emqx_retainer is a normal plugin.
So we don't need to start emqx_modules as plugins, setting `{emqx_modules, false}` in `data/load_plugins`
emqx_modules is a plugin, it manages all modules, so it must enable when emqx boots, otherwise all modules are abnormal. 
We must make sure `{emqx_modules, true}` in `data/load_plugins`.
the `emqx_retainer` is a normal module, we should set  `{emqx_retainer, false}` in `data/load_plugins` and make sure
it is enabled at `data/load_modules`.
So `emqx_modules` and `emqx_retainer` need diff default values between EE and CE.
BTW: we can see diff default in EE's `rebar.config.erl`
> fix: bad default plugins

- apps/emqx/src/emqx_schema.erl
HOCON type reference is actually a child-struct's struct name
not necessarily the same name as the parent-sutrct's field name
This commit changes the variable name for more clarity
> refactor: rename Field to Struct for ref type create function

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_data_backup.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.app.src
- apps/emqx_rule_engine/src/emqx_rule_engine.appup.src
- bin/install_upgrade.escript
- include/emqx_release.hrl
- src/emqx.app.src
- src/emqx.appup.src
When upgrading from 4.4.X, the `install_upgrade` script from 4.4.X
is used, which forbids such transition.
The problem is that the `install_upgrade.escript` for the older versions are already released.  So, a new 4.4.FIX release containing this fix would need to be cut to allow upgrading 4.4.X -> 4.4.FIX -> 4.5.0.
> feat: enable upgrading release from 4.4.X to 4.5.Y

- apps/emqx/rebar.config
- mix.exs
- rebar.config
ZSTD fix for RocksDB.
https://github.com/emqx/mnesia_rocksdb/pull/6
> chore: bump ekka -> `0.13.4`

- apps/emqx/src/emqx_schema.erl
- apps/emqx_connector/src/emqx_connector_schema_lib.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_resource/i18n/emqx_resource_schema_i18n.conf
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_worker_sup.erl
- apps/emqx_resource/src/schema/emqx_resource_schema.erl
- lib-ee/emqx_ee_connector/i18n/emqx_ee_connector_influxdb.conf
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
* `password` format.
* Hide `pool_size` opt for users, use `worker_pool_size` instead.
* Hide `start_after_created` and `start_timeout` opts. They are internal opts now.
* Fix resource `auto_retry` in `disconnected` state.
> Fix resource opts

- src/emqx_plugins.erl
Remove `emqx_telemetry` from default plugins, it does not exist in the enterprise version.
Otherwise, it will report a WARNING when starting emqx.
```
2022-08-22T09:34:57.619825+08:00 [alert] [Plugins] cannot_find_plugins: [emqx_telemetry]
```
> fix: remove emqx_telemetry from ee's default plugins

- CHANGES-5.0.md
- Makefile
- apps/emqx/include/emqx_release.hrl
- apps/emqx/src/emqx.app.src
Due to we changed the `node_status` of `/nodes` API in #8642,
however, we did not update the correct dashboard version in v5.0.5.
So, we release v5.0.6 to fix this issue
> Release v5.0.6: fix node_status dispaly error in Dashboard

- test/emqx_shared_sub_SUITE.erl
```
%%% emqx_shared_sub_SUITE ==> t_local_fallback: FAILED
%%% emqx_shared_sub_SUITE ==> {{badmatch,[{share,<<"local_foo/bar">>,{ok,1}},
{share,<<"local_foo/bar">>,{error,no_subscribers}}]},
[{emqx_shared_sub_SUITE,t_local_fallback,1,
[{file,"/emqx/test/emqx_shared_sub_SUITE.erl"},
{line,411}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1783}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1292}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1224}]}]}
```
> test: attempt to fix flaky shared sub test

- rebar.config
`4.x ce` is using gun 1.3.7, but `4.x ee` is using gun 1.3.4
1.3.7 fix undef erlang:get_stacktrace/0. we should pin 1.3.7
https://github.com/emqx/gun/compare/1.3.4...emqx:gun:1.3.7
compile warning is EE
```bash
, Evaluated Version: "1.3.4"
, Deps versions: [
{<<"grpc">>,
{gun,{git,"https://github.com/emqx/gun",{tag,"1.3.7"}}}},
{<<"emqtt">>,
{gun,{git,"https://github.com/emqx/gun",{tag,"1.3.4"}}}},
{<<"ehttpc">>,
{gun,{git,"https://github.com/emqx/gun",{tag,"1.3.7"}}}}]
```
link: also pin 1.3.7 on emqtt(1.6.0) https://github.com/emqx/emqtt/pull/167
> chore: pin gun 1.3.7

- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- scripts/buildx.sh
- scripts/relup-base-vsns.escript
`relup-base-versions.escript` needs to know the system the package is
being built for to correctly enumerate the base versions for relup.
> ci: pass down `$SYSTEM` for relup base versions escript

- .github/workflows/build_packages.yaml
Avoid triggering package cross build when repo is not CE.
> ci: disable cross build outside ce repo

- apps/emqx_exhook/src/emqx_exhook.app.src
- apps/emqx_exhook/src/emqx_exhook_server.erl
Now if there is an unknown hookpoint, the error message is actually `{unknown_hookpoint,{error,badarg}}`,
the hookpoint name information is lost
> fix(exhook): fix the error message of unknown hookpoint

- .github/workflows/build_slim_packages.yaml
- .github/workflows/run_test_cases.yaml
- let main-4.x branch use hosted runners
- use self-hosted runners only when repo owner is `emqx`
> main 4.x use self hosted runner

- CHANGES-4.3.md
- bin/emqx
When installed from RPM or DEB, In case EMQX in started by root,
the boot script changes user to emqx and then re-enter with the
same args.
Prior to this change, the Erlang start check is done before
su, causing it to be checked twice.
This commit moves the Erlang start check to after th su
> fix(emqx): Check Erlang start after su command

- CHANGES-5.0.md
- apps/emqx/src/emqx_access_control.erl
- apps/emqx/test/emqx_proper_types.erl
- apps/emqx_authz/src/emqx_authz.app.src
- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_exhook/src/emqx_exhook_handler.erl
- apps/emqx_exhook/test/emqx_exhook_SUITE.erl
- apps/emqx_exhook/test/props/prop_exhook_hooks.erl
see: https://github.com/emqx/emqx/issues/8779
> fix: exhook client.authorize never be execauted

- CHANGES-5.0.md
- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_authn/test/emqx_authn_jwt_SUITE.erl
> fix(jwt): support non-integer timestamp claims

- Makefile
without semicolon `rm` considers all tokens on line 136 as separate files
> buid: fix make clean

- CHANGES-5.0.md
- apps/emqx/src/emqx_channel.erl
- apps/emqx_authn/test/emqx_authn_SUITE.erl
> bugfix: do not publish last will when authentication failed

- CHANGES-5.0.md
- apps/emqx_conf/etc/emqx_conf.conf
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- rel/emqx_vars
Fix: can't override etc_dir  via ENV:
`RUNNER_LOG_DIR="/test/log" ./bin/emqx console`
> feat: don't override RUNNER_LOG_DIR env in emqx_vars

- apps/emqx/src/emqx_release.erl
- apps/emqx_machine/src/emqx_machine.app.src
- apps/emqx_machine/src/emqx_restricted_shell.erl
- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/src/emqx_mgmt_api_nodes.erl
- apps/emqx_management/test/emqx_mgmt_api_nodes_SUITE.erl
Add `{edition: opensource|enterprise}` to /nodes API
We have returned edition information in the dashboard's  POST `/login` API, 
Now we return the edition for each node.
> feat: add edition info to /nodes api

- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_dashboard/test/emqx_dashboard_api_test_helpers.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- `DELETE http://127.0.0.1:18083/api/v5/bridges/{id}` will fail if there's any action dependents on this data-bridge.
- `DELETE http://127.0.0.1:18083/api/v5/bridges/{id}?also_delete_dep_actions` will success and remove the dependent actions from all rules.
> Check dependent actions before removing a data-bridge

- CHANGES-5.0.md
- apps/emqx_conf/etc/emqx_conf.conf
- apps/emqx_conf/src/emqx_conf_schema.erl
- bin/emqx
- build
- mix.exs
- rebar.config.erl
- rel/emqx_vars
- scripts/get-dashboard.sh
```
$ env EMQX_NODE_COOKIE='' ./_build/emqx/rel/emqx/bin/emqx console
!!!!!!
WARNING: Default (insecure) Erlang cookie is in use.
WARNING: Configure node.cookie in /mnt/code/src/emqx/0/_build/emqx/rel/emqx/etc/emqx.conf or override from environment variable EMQX_NODE__COOKIE
NOTE: Use the same config value for all nodes in the cluster.
!!!!!!
log.file_handlers.default.enable = EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE = false
log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
```
> refactor(cookie): Warning message when boot with default Erlang cookie

- CHANGES-5.0.md
- apps/emqx_conf/src/emqx_cluster_rpc.erl
The `cluster-rpc` calls should quickly filter out the down nodes.
> feat: cluster-rpc failed fast when some nodes is down

- bin/emqx
realpath works the same way in GNU and BSD systems
> build: use realpath instead of readlink

- CHANGES-5.0.md
- apps/emqx_retainer/src/emqx_retainer.app.src
- apps/emqx_retainer/src/emqx_retainer.erl
- apps/emqx_retainer/src/emqx_retainer_app.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
Reproduce steps:
1. Start an emqx and disable the Retainer
2. Restarting emqx will report the following error
> fix(retainer): fix that EMQX can't start when the retainer is disabled

- Makefile
- build
- mix.exs
Avoid downloading enterprise-only dependencies in community edition.
> chore(mix): guard enterprise-only dependencies

- apps/emqx_exproto/src/emqx_exproto_channel.erl
revert one part of 
https://github.com/emqx/emqx/pull/8820
> fix: revert 'accepted' state of exproto plugin

- CHANGES-5.0.md
- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_modules/src/emqx_delayed.erl
- apps/emqx_modules/src/emqx_modules.app.src
Avoid the problem of inaccurate timers caused by mixing erlang:system_time/0-1 and os:system_time/0-1
---
port https://github.com/emqx/emqx/pull/8908
> fix(time): replace os:system_time with erlang:system_time

- CHANGES-4.3.md
- apps/emqx_auth_mnesia/test/emqx_auth_mnesia_SUITE.erl
- src/emqx_channel.erl
4.3 was not affected in the first place, but this test can help prevent a regression.
Related issue: #8886
> test: add test case for not publishing will msg when not authorized

- mix.exs
- rebar.config.erl
- scripts/merge-config.escript
- Rename `emqx_enterprise.conf` to `emqx-enterprise.conf`.
- Only append `include emqx-enterprise.conf` in enterprise's `emqx.conf`.
> feat: don't include emqx-entriprise.conf in opensource

- apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl
- apps/emqx_authn/test/emqx_authn_redis_SUITE.erl
fix #8800
when the key not-existing, redis may return a list that all elements are `undefined`
> fix(authn_redis): Add new clause for non-existent key check

- apps/emqx_authz/src/emqx_authz_api_sources.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_connector/src/emqx_connector_ssl.erl
- apps/emqx_exhook/src/emqx_exhook_api.erl
revert parts of #8872. remove useless code.
> fix(bridge/authz/exhook): no need to drop invalid certs

- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_worker.erl
- apps/emqx_resource/src/schema/emqx_resource_schema.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_influxdb.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_mysql.erl
1. setup an egress MQTT Bridge on local broker B, to a remote broker A.
2. restart the remote broker A.
3. send message to the MQTT Bridge.
4. the bridge hangs, all messages will be queued in the mailbox of `emqx_resource_worker`.
```
ee-5.0.0-beta.3-g477d4b0b(emqx@127.0.0.1)57> process_info(<0.3403.0>).
[{registered_name,'emqx_resource_worker:bridge:mqtt:mqtt_example:1'},
{current_function,{gen,do_call,4}},
{initial_call,{proc_lib,init_p,5}},
{status,waiting},
{message_queue_len,205},
{links,[<0.2411.0>]},
{dictionary,[{'$initial_call',{emqx_resource_worker,init,1}},
{'$ancestors',[emqx_resource_worker_sup,emqx_resource_sup,
<0.2407.0>]}]},
{trap_exit,true},
{error_handler,error_handler},
{priority,normal},
{group_leader,<0.2406.0>},
{total_heap_size,17731},
{heap_size,17731}, …
```
> Fix mqtt bridge hangs on msg sending

- scripts/relup-base-packages.sh
- scripts/relup-base-vsns.sh
do not skip downloading only because of curl error.
for known missing base packages, we should list them in the script
> build: do not skip downloading relup base package

- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_plugin_libs/src/emqx_plugin_libs_pool.erl
- lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_influxdb.conf
- for connectors using ecpool, parse connect error `Reason` when start pool failed.
- Refine InfluxDB bridge desc.
> Fix bridge api

- apps/emqx_authz/src/emqx_authz_http.erl
- apps/emqx_authz/src/emqx_authz_mongodb.erl
- apps/emqx_authz/test/emqx_authz_http_SUITE.erl
- apps/emqx_authz/test/emqx_authz_mongodb_SUITE.erl
Add `cert_common_name` and  `cert_subject` placeholder support for authz_http and authz_mongo, authz_mysql authz_redis authz_postgre already has supported
> feat(authz): Support `cert_common_name` and `cert_subject` in Authz

- apps/emqx_connector/src/emqx_connector_mqtt.erl
for non configured `username` and `password`, default values `<<>>` should be used. emqtt needs the values.
> fix(bridge): mqtt bridge client info `username` & `password`

- apps/emqx_auth_mongo/test/emqx_auth_mongo_SUITE.erl
This test runs most of the time fine in CI.  But, if run alone locally, will fail consistently because the default `acl.conf` has a catch-all `{allow, all}` clause.  Probably another suite that runs before this in CI unloads that and everything seems fine.
> test: avoid inter-suite flakiness

- apps/emqx_auth_jwt/src/emqx_auth_jwt.erl
- apps/emqx_auth_jwt/test/emqx_auth_jwt_SUITE.erl
This issue has been fixed in 4.4 by @savonarola in this commit: ddc06e8bcd but was not ported back to 4.3
> chore: avoid generating crash logs for hook execution

- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_worker.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
If inflight window is full, the resource worker will be blocked.
Before this change, the resource worker will be resumed (unblocked) only when the timer is triggered every 'resume_interval'. After this change, we resume the resource worker as soon as we received an ACK.
Now the `retried` counter increases only when a request in the inflight window is resent. Note that the requests queued in the replayq will not take into account because they have never been sent.
I also added 2 counters under the `retried` counter:
- `retried.success`
- `retried.failed`
> Fast resume from inflight full

- mix.exs
- rebar.config
```
dependency :gpb is using Rebar 2, which is no longer maintained and no longer works in recent Erlang/OTP versions. Remove the :manager option or set it to :rebar3 instead
```
> chore: use `:rebar3` as `:gpb`'s manager

- .github/workflows/build_slim_packages.yaml
- .github/workflows/run_test_cases.yaml
- rebar.config.erl
An attempt to make Coveralls bot to identify and report coverage
changes in `main-v4.{3,4}`-based PRs.
Currently, `master`-based PRs get their reports correctly.  When one
checks such a report, e.g.: https://coveralls.io/builds/52535695 , it
identifies if coverage increased or decreased relative to the base
branch.
`main-v4.x`-based PRs, however, always seem to report as "first
builds", so it doesn't report if coverage increased or
decreased. E.g.: https://coveralls.io/builds/52541065 .
The reason _could be_ that, currently, `main-v4.x` branches do not
build themselves.  That is, PRs run the test + cover analysis, as
usual, but once they're merged, tests (and thus coverage analysis) do
not run.  And that _could be_ why the tool can't see if coverage
increased or decreased with such PR.
> ci: enable running test cases and cover for main-v4.x

- .github/actions/package-macos/action.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
Not sure what is the reason to export `EMQX_NAME` and `BUILD_WITH_QUIC=1` in build_slim_packages but not in build_packages. If it should be the same in both, we can move these to the action too.
> build: extract macos packaging into reusable workflow

- CHANGES-4.3.md
- etc/emqx.conf
Without using default values, sockets will be opened with OS default buffer sizes. OS default is set by linux aligning to the host memory size that large memory has larger OS default.
Now more and more user run EMQX in container which has large OS memory but the container max memory is limited by cgroup that could be very small amount compared to the OS total memory size.
To eliminate uncertainty, it is better to have the default value set.
> perf(TLS): set default sndbuf and recbuf to 4K

- CHANGES-5.0.md
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_conf/src/emqx_conf_app.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
Fix GET /listeners API crashes when some nodes are still in init configuration.
```
{"code":"INTERNAL_ERROR","message":"error, {badmatch,{error,{'EXIT',{{badkey,<<\"listeners\">>},
[{erlang,map_get,[<<\"listeners\">>,#{}],[{error_info,#{module => erl_erts_errors}}]},{emqx_config,get_schema_mod,1,
[{file,\"emqx_config.erl\"},{line,505}]},{emqx_listeners,do_list_raw,0,[{file,\"emqx_listeners.erl\"},{line,92}]},
{emqx_listeners,list_raw,0,[{file,\"emqx_listeners.erl\"},{line,71}]},{emqx_mgmt_api_listeners,do_list_listeners,0,
[{file,\"emqx_mgmt_api_listeners.erl\"},{line,519}]}]}}}}, [{emqx_mgmt_api_listeners,listener_status_by_id,2,
[{file,\"emqx_mgmt_api_listeners.erl\"},{line,496}]},{emqx_mgmt_api_listeners,listener_status_by_id,1, …
```
> fix: /listeners API crash when there are nodes still in initial conf

- mix.exs
- rebar.config
To avoid the MQTT bridge blocked once the inflight window fulled
see: https://github.com/emqx/emqtt/pull/171
> chore: update emqtt to 1.7.0-rc.2

- apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
- apps/emqx_rule_engine/src/emqx_rule_engine.app.src
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- mix.exs
- rebar.config.erl
- scripts/spellcheck/dicts/emqx.txt
This commit adds a rule engine configuration option for changing the implementation module used for the rule engine function jq. The two options are `jq_port` (uses Erlang port programs to interact with jq) and `jq_nif` (uses an Erlang NIF library to interact with jq).
**Things needed before merge:**
* Chinese translation for the description of the config option
* Bump the jq library version after [this PR](https://github.com/emqx/jq/pull/36) has been merged (the config option has no effect before that PR)
> Add rule engine configuration option for changing the implementation of the jq function

- CHANGES-5.0.md
- apps/emqx/src/emqx_session.erl
- apps/emqx_slow_subs/src/emqx_slow_subs.app.src
- apps/emqx_slow_subs/src/emqx_slow_subs.erl
- apps/emqx_slow_subs/test/emqx_slow_subs_SUITE.erl
1. The unit of `deliver_begin_at` is incorrectly used the `seconds`, the resulting is incorrect when `stats_type` is `internal` or `response`
2. The config update doesn't actually take effect, the `load` function always used the old config
> fix(slow_subs): fix timestamp unit error and update config not work

- apps/emqx/src/emqx_channel.erl
1. we already have client info (id and source IP) in logging metadata.
2. the payload can be potentially very large to log.
```
2022-09-26T15:51:30.981831-03:00 [warning] clientid: myclient, ipaddr: {127,0,0,1}, line: 356, mfa: emqx_authz:authorize_non_superuser/5, msg: authorization_permission_denied, peername: 127.0.0.1:35228, source: file, topic: some/topic, username: undefined
2022-09-26T15:51:30.981934-03:00 [warning] clientid: myclient, line: 662, mfa: emqx_channel:process_publish/2, msg: cannot_publish_to_topic, peername: 127.0.0.1:35228, reason: not_authorized, topic: some/topic
2022-09-26T15:51:30.982029-03:00 [warning] clientid: myclient, ipaddr: {127,0,0,1}, line: 356, mfa: emqx_authz:authorize_non_superuser/5, msg: authorization_permission_denied, peername: 127.0.0.1:35228, …
```
> chore: remove extra information from denied lwt log

- apps/emqx_auth_mongo/test/emqx_auth_mongo_SUITE.erl
Ex:
https://github.com/emqx/emqx-enterprise/actions/runs/3124750818/jobs/5068407612#step:7:769
```
%%% undefined ==> end_per_suite: FAILED
%%% undefined ==> {{badmatch,{error,enoent}},
[{emqx_auth_mongo_SUITE,end_per_suite,1,
[{file,"/emqx/apps/emqx_auth_mongo/test/emqx_auth_mongo_SUITE.erl"},
{line,62}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1784}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1381}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1225}]}]}
Testing lib.emqx_auth_mongo: TEST COMPLETE, 3 ok, 0 failed of 3 test cases
```
> test: attempt to fix inter-suite flakiness

- build
Log before:
```
2022-09-26T15:51:30.982183-03:00 [warning] '$kind': last_will_testament_publish_denied, clientid: myclient, line: 2132, mfa: emqx_channel:publish_will_msg/2, peername: 127.0.0.1:35228, topic: $SYS/lwt
```
Log after:
```
2022-09-26T16:25:50.799914-03:00 [warning] clientid: myclient, line: 2132, mfa: emqx_channel:publish_will_msg/2, msg: last_will_testament_publish_denied, peername: 127.0.0.1:47080, topic: $SYS/lwt
```
> feat(mix): set `snk_kind` from `$kind` to `msg` in Mix build

- scripts/check-apps-vsn.sh
This quote in 4.3 seem to have already been changed to a double quote.
But that change was maybe lost during conflict resolution.
> build: fix git diff exclude pattern in app version check script

- scripts/update-appup.sh
In case tags are force pushed, the local close (in `/tmp/_w`) may still have the tag on a stale commit.
> chore: force fetch upstream tags before appup updates

- .github/workflows/build_slim_packages.yaml
- bin/emqx
Prior to this fix, space was already allowed in root path for 'start' 'console' etc. (the boot commands).
However the non-boot commands such as 'ping' still had trouble.
> fix(bin/emqx): allow space in root path

- CHANGES-5.0.md
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx/test/emqx_schema_tests.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/emqx_connector_mongo.erl
- apps/emqx_connector/src/emqx_connector_mysql.erl
- apps/emqx_connector/src/emqx_connector_pgsql.erl
- apps/emqx_connector/src/emqx_connector_redis.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard.app.src
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_gateway/src/emqx_gateway.app.src
- apps/emqx_gateway/src/emqx_gateway_schema.erl
- apps/emqx_statsd/src/emqx_statsd.app.src
- apps/emqx_statsd/src/emqx_statsd_schema.erl
- rel/emqx_conf.template.en.md
- rel/emqx_conf.template.zh.md
In the https://github.com/emqx/emqx/pull/8571, we add a colon before the port.
In this PR, we add some comments to explain how we made this decision. And get the following improvements.
- If it configured as `0.0.0.0:1883` and `:::1883`
- both are formatted as `:1883` before
- now it is formatted as `0.0.0.0:1883` and  `[::]:1883`
- Don't add ipv4 address automatically in `emqx_schema:to_ip_port/1`
> Improve the `ip_port()` definition and `bind` print format

- test/emqx_node_helpers.erl
- test/emqx_shared_sub_SUITE.erl
Mainly to start emqx_modules application in ct-slave tests.
This is due to enterprise edition needs emqx_modules to be running since https://github.com/emqx/emqx-enterprise/pull/1400/commits/f5d5b41e0116b977a3a217a6088e81caadbaddd9
Some more fixes for flakyness:
* ekka join match `ok` otherwise error get silently ignored, no way to know what went wrong
* for some reason, ct slave start may return `started_not_connected`, we allow it, and the `ping` in the next line should make sure the nodes are connected
* make sure slave node is stopped at the end of each test case.
> test: fix more flaky test in share sub SUITE

- bin/emqx
```
man stat
...
-f format
Display information using the specified format.  See the Formats section for a description of
valid formats.
...
R       The absolute pathname corresponding to the file.
...
```
GNU stat and BSD stat are different again, GNU stat uses `-c` to specify format.
For the history, here is list of links I went through while trying to find a portable solution (none of them worked):
* https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x
* https://unix.stackexchange.com/questions/136494/whats-the-difference-between-realpath-and-readlink-f/136527#136527
* https://stackoverflow.com/questions/284662/how-do-you-normalize-a-file-path-in-bash
* https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
* …
> chore: stat to resolve script dir on macos and readlink -f otherwise

- pkg-vsn.sh
No changes in logic. Right now the same happens on line #110 in the current version: if `PKG_VSN` is set, and `--long` is not given, we just return `PKG_VSN`.
In the current version though, even if you set `PKG_VSN`, the script will still attempt to extract version from git. This fails to produce correct version if one tries to build emqx from source code archive (with no `.git`), and consequently fails the build.
> chore: respect PKG_VSN in pkg-vsn.sh

- scripts/rel/cut4x.sh
It happened to v4.3.20 and e4.3.15
some of the commits were not synced to enterprise before creating the e4.3.15 tag.
you may inspect the diff with command:
`git diff --name-only v4.3.20...e4.3.15 -- "src/" -- "apps/" -- ":(exclude)apps/emqx_management"`
This caused some troubles in appup generation.
lucky that there were no complex appup instructions, so the workaround is to add more `load_module`
for some unchanged modules in the next release (i.e. the union of changed modules from both ce and ee).
With the `scripts/rel/cut4x.sh`, it will force sync the remotes before creating the tag,
however there may still be divergence due to for example merge conflict resolution
-- which should ideally never happen if all changes are always made to the ce repo first, but we are humans, we make …
> build: support additional checks before cutting a release tag

- scripts/rel/cut4x.sh
- scripts/rel/sync-remotes.sh
BSD's (macos) version of echo does not support -e flag
Found out when testing https://github.com/emqx/emqx/pull/9108
The output looks like this (verbatim)
```
\e[33mINFO: Fetching from remote=emqx (force tag sync).\e[39m
```
Corresponding article: https://www.codequoi.com/en/coloring-terminal-text-tput-and-ansi-escape-sequences/
> chore: portable stdout coloring in scripts

- scripts/macos-sign-binaries.sh
Since building quicer on macos was disabled in d49a75ae287ab00ac057184f47b23f12450454e2, build_packages is failing
> build: check if quicer binary present before trying to sign it

- CHANGES-5.0.md
- apps/emqx_modules/src/emqx_delayed.erl
- apps/emqx_modules/src/emqx_modules.app.src
- apps/emqx_modules/test/emqx_delayed_SUITE.erl
Use milliseconds internally in emqx_delayed to store the publish time, improving precision
> fix(delayed): Improve time precision of delayed messages

- CHANGES-5.0.md
- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_mqueue.erl
- apps/emqx/src/emqx_session.erl
- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
when session terminates (not due to take over)
shared delivery should be re-dispatched to other members in the group
This is the fix https://github.com/emqx/emqx/pull/9094 ported to 5.0
> fix(shared): re-dispatch inflight (QoS1) and mqueue messages

- .github/workflows/run_cts_tests.yaml
- .github/workflows/run_test_cases.yaml
An attempt to prevent updated container definitions clashing in CI GH runners between different branches.
> ci(test): stop containers at the beginning of the run

- src/emqx.erl
- src/emqx_misc.erl
When the call is issued from an rpc call of ekka:join(PeerNode), the logging to a remote group leader is very confusing when inviting a node to join
```
2022-10-04T10:18:57.304492+00:00 [critical] [EMQ X] emqx shutdown for join
2022-10-04T10:18:57.305534+00:00 [info] Importing modules from 'emqx@node1.emqx.io': internal_acl, presence, recon, retainer
2022-10-04T10:18:57.310668+00:00 [info] [Plugins] Stop plugin emqx_management successfully
2022-10-04T10:18:57.313849+00:00 [info] [Plugins] Stop plugin emqx_dashboard successfully
2022-10-04T10:18:57.316450+00:00 [info] [Plugins] Stop plugin emqx_modules successfully
2022-10-04T10:18:57.319311+00:00 [info] [Plugins] Stop plugin emqx_rule_engine successfully
2022-10-04T10:18:57.367801+00:00 [info] Ekka(Membership): Mnesia emqx@node2.emqx.io …
```
> fix(emqx): emqx:shutdown should not log to remote node

- apps/emqx_rule_engine/src/emqx_rule_metrics.erl
Porting some changes have been included in See https://github.com/emqx/emqx/pull/9079.
Change logs should have been included in the branch main-v4.3 (for 4.3.22).
> fix: reset rule metrics crashed under certain conditions

- .tool-versions
- CHANGES-5.0.md
- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx_authentication_config.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_trace/emqx_trace.erl
- apps/emqx_authn/src/emqx_authn.erl
- apps/emqx_authn/src/emqx_authn_app.erl
- apps/emqx_management/src/emqx_mgmt_api_publish.erl
- apps/emqx_management/src/emqx_mgmt_api_trace.erl
- apps/emqx_management/src/proto/emqx_mgmt_trace_proto_v2.erl
- apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
When users view the trace logs in the cluster, 
they generally look directly at the files on the nodes that have been updated recently, 
so we need a new API to return the trace file's size and modification times.
> get trace file's detail via /trace/:name/log_detail

- apps/emqx/src/emqx_session.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
when the session terminate by `takenover` or `kicked`, it shouldn't redispatch the shared message
> fix(shared_sub): kick session should not cause session message redispatch

- src/emqx_session.erl
- test/emqx_shared_sub_SUITE.erl
For takeover, there should be no message re-dispatch because the messages will be retried by the new session.
For kick, messages should not be re-dispatched for security reason. i.e. if admin has identified that there are malicious messages stored in persisted sessions, killing the session should not cause messages to be re-dispatched
There was a lack of test coverage for session shutdown reasons.
The compare to `shutdown` reason never succeeded before.
This was never noticed before the latest release,
maybe because only inflight QoS1 inflight messages were re-dispatched,
so nobody complained because it's at-least once delivery.
> fix(shared): do not redispatch shared messages for certain shutdown

- apps/emqx/src/emqx_message.erl
- apps/emqx_management/i18n/emqx_mgmt_api_publish_i18n.conf
- apps/emqx_management/src/emqx_mgmt_api_publish.erl
- apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
Prior to this change, the publish API returns 200 in most of the cases.
This change provides more insights to the publish result.
The 400 code schema is the same as before.
in case of e.g. QoS out of range.
For single message publish endpoint (`publish/`):
HTTP error codes are:
200: Everything is OK
202: No subscriber for the topic
503: Failed to dispatch the message. e.g. during EMQX restart.
The response body is a JSON object with two fields `message_id`, and `publish_result`.
The `message_id` is a globally unique ID for tracing. `publish_result` is `"OK"` when the message is delivered to at least one subscriber.
Otherwise `"no_subscriber"`.
`publish_result` may also be some other informative message to hint the failure result, the content of which may change in the future.
For …
> feat(api/publish): return detailed publish results

- apps/emqx/test/emqx_shared_sub_SUITE.erl
- mix.exs
- rebar.config
gun 1.3.7 had a bug which discards `ssl_passive` message.
chnagelog update will be sent in another PR where I split the change log into small files.
> 1020 chore upgrade gun 1.3.9

- .github/CODEOWNERS
From [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax):
```
/build/logs/ @doctocat
docs/*  docs@example.com
```
> chore: add leading slash for paths in codeowners

- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_prometheus/i18n/emqx_prometheus_schema_i18n.conf
- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
- apps/emqx_prometheus/src/emqx_prometheus_schema.erl
- apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl
Now we can turn off `vm_dist_collector/vm_dist_collector/mnesia_collector/vm_statistics_collector/vm_system_info_collector/vm_memory_collector/vm_msacc_collector` metrics.
These metrics are very slow to return after a single node exceeds 2.7M connections, causing fetching the prometheus/status API timeout. So add switches to turn them off.
> feat: add prometheus collectors config

- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/test/emqx_rule_events_SUITE.erl
- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
the converted message is for JSON encoding, keeping the tuple-values will lead to encoding error.
> fix(emqx_rule_events): do not keep tuple-value message headers

- CHANGES-4.4.md
- apps/emqx_plugin_libs/src/emqx_plugin_libs.app.src
- apps/emqx_plugin_libs/src/emqx_plugin_libs.appup.src
- apps/emqx_plugin_libs/src/emqx_trace/emqx_trace.erl
- apps/emqx_plugin_libs/src/emqx_trace/emqx_trace_api.erl
- changes/v4.4.11-en.md
- changes/v4.4.11-zh.md
- We should not crash when the trace module is not initialized, return empty list instead.
- Sometimes erlang:system_time will have a big gap with the OS time(the os time is from the dashboard)…
Replacing it with os time would also fix the inconsistency.
> fix: get trace list crash when trace not initialized

- apps/emqx_prometheus/include/emqx_prometheus.hrl
- apps/emqx_prometheus/src/emqx_prometheus.erl
- apps/emqx_prometheus/src/emqx_prometheus_api.erl
- apps/emqx_prometheus/src/emqx_prometheus_app.erl
- apps/emqx_prometheus/src/emqx_prometheus_config.erl
- apps/emqx_prometheus/src/emqx_prometheus_schema.erl
- apps/emqx_prometheus/src/emqx_prometheus_sup.erl
- apps/emqx_prometheus/src/proto/emqx_prometheus_proto_v1.erl
- apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl
- apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl
- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
- Don‘t store config in emqx_prometheus processes, so we don't need to manage the diff between config and process state, it's simpler and clearer.
- Using emqx_config_handler's callback to make sure emqx_prometheus's alive status in the cluster.
- Add error log when pushing to push_gateway failed.
NONE
> refactor: update emqx_prometheus via emqx_config_handler

- apps/emqx_rule_engine/src/emqx_rule_utils.erl
- apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl
- apps/emqx_web_hook/src/emqx_web_hook.app.src
- apps/emqx_web_hook/src/emqx_web_hook.appup.src
- apps/emqx_web_hook/src/emqx_web_hook_actions.erl
- apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl
- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
Support to use placeholders as http headers in webhook actions.
> feat: support to use placeholders as http headers in webhook actions

- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx_rpc.erl
- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/src/proto/emqx_management_proto_v3.erl
- apps/emqx_management/test/emqx_mgmt_api_nodes_SUITE.erl
- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
Getting all nodes' info API is too slow when there are many nodes in the cluster.
So replace `rpc:call` with `erpc:multicall`
> refactor: multicall node_info to improve /node speed

- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_test_lib.erl
- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
`rule_id` and `resource_id` could be any unicode character now.
EMQX Dashboard limited `rule_id` and `resource_id` with re `^([0-9a-zA-Z:_])*$`.
But user can still create rules/resources with any unicode character as id by manually request HTTP API.
> fix(rule_engine): rule id in path urlencoded

- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/test/emqx_rule_events_SUITE.erl
- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
the message headers are fed to a JSON ecnoder which may crash if the header value is a tuple
> fix(emqx_rule_events): drop tuple-value from message headers

- apps/emqx_auth_mnesia/src/emqx_acl_mnesia_cli.erl
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src
- apps/emqx_auth_mnesia/src/emqx_auth_mnesia.appup.src
- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
- lib-ce/emqx_dashboard/etc/emqx_dashboard.conf
- lib-ce/emqx_dashboard/priv/emqx_dashboard.schema
- lib-ce/emqx_dashboard/src/emqx_dashboard.app.src
- lib-ce/emqx_dashboard/src/emqx_dashboard_admin.erl
- lib-ce/emqx_dashboard/test/emqx_dashboard_admin_bootstrap_user.erl
Add `dashboard.bootstrp_user_file ="etc/bootstrap_user_file.txt"` to bulk import default user&password when EMQX first starts
- emqx_dashboard start failed when importing bootstrap users error.
- Don't import any bootstrap users when there is invalid data in the file.
> feat: bootstrap dashboard users from dashboard.bootstrap_users_file

- apps/emqx_coap/src/emqx_coap.app.src
- apps/emqx_coap/src/emqx_coap.appup.src
- apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl
- apps/emqx_coap/src/emqx_coap_pubsub_resource.erl
- apps/emqx_coap/src/emqx_coap_resource.erl
- apps/emqx_coap/test/emqx_coap_SUITE.erl
- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
We now trigger the `'message.acked'` hook after the CoAP gateway sends a message to the device and receives the ACK from the device.
With this change, the CoAP gateway can be combined with the offline message caching function (in the
emqx enterprise), so that CoAP devices are able to read the missed messages from the database when
it is online again.
> fix: run the 'message.acked' hook when ACK received from CoAP devices

- apps/emqx_gateway/src/coap/emqx_coap_api.erl
- apps/emqx_gateway/src/emqx_gateway_api.erl
- apps/emqx_gateway/src/emqx_gateway_api_authn.erl
- apps/emqx_gateway/src/emqx_gateway_api_authn_user_import.erl
- apps/emqx_gateway/src/emqx_gateway_api_clients.erl
- apps/emqx_gateway/src/emqx_gateway_api_listeners.erl
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_api.erl
Changed the API tags to align with the manual changes made in emqx-docs.git
* CoAP APIs -> `Coap Gateway`
* Lwm2m APIs - > `LwM2M Gateway`
New changes:
* Authe related APIs: Changed from `Gateways` to `Gateway Authentication`
* Listener related APIs: changed from `Gateways` to `Gateway Listeners`
> docs: re-group api tags for gateway apps

- apps/emqx_management/i18n/emqx_mgmt_api_status_i18n.conf
- apps/emqx_management/src/emqx_mgmt_api_status.erl
- apps/emqx_management/test/emqx_mgmt_api_status_SUITE.erl
This allow use to reference `/status` in the API documentation without
manually editing the `swagger.json` file.
> feat(mgmt): add alias endpoint for health check 

- apps/emqx_management/etc/emqx_management.conf
- apps/emqx_management/priv/emqx_management.schema
- apps/emqx_management/src/emqx_mgmt_app.erl
- apps/emqx_management/src/emqx_mgmt_auth.erl
- apps/emqx_management/test/emqx_mgmt_bootstrap_app_SUITE.erl
- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
Add `management.bootstrap_user_file ="etc/bootstrap_apps_file.txt"` to bulk import app#secret when EMQX first starts
emqx_mangement start failed when importing bootstrap apps error.
Don't import any bootstrap apps when there is invalid data in the file.
NONE
> feat: bootstrap app/secret from management.bootstrap_apps_file

- .gitignore
- Makefile
Our default and main build targets depend on `$(REBAR)`, which is real file ./rebar3, but `$(REBAR)` target in turn depends on the phony target `prepare`. Accordingly, make executes `prepare` each time you run, e.g., `make emqx`. And it does not matter how many ages ago you installed dependencies.
This PR changes phony `prepare` target to real `.prepare` file to mark that the `prepare` has been run on this machine and to not run it again.
Wins:
- local repetitive builds should run a little faster (on macos especially)
- `make emqx` will work when installing emqx as homebrew package (right now it's impossible because when homebrew installs a package, `brew` command is not available and `prepare-build-deps.sh` script fails)
**If your build fails** due to your commit message not passing the …
> build: stop running prepare on each build

- apps/emqx/src/emqx_misc.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_connector/src/emqx_connector.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- apps/emqx_gateway/src/coap/handler/emqx_coap_pubsub_handler.erl
- apps/emqx_gateway/src/emqx_gateway_api_clients.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
1.  emqx_bridge_resource
After investigation, it was confirmed that there was no need to convert the bridge name to atom.
We can keep it binary, whether the API, configuration or emqx_bridge all of these are supports names in binary format
2. emqx_bridge_api
When we use one API to send a request to a Node, it means that the Node is known, so it is better to use the `binary_to_existing_atom`
And due to the maximum limit of the nested of the elvis, I had to adjust the function indent
3. emqx_connector
After investigation, it was confirmed that there was no need to convert the bridge name to atom.
We can keep it binary, whether the API, configuration both of these are supports names in binary format
4. Ensure that the node name is known
- emqx_dashboard_monitor_api
- emqx_gateway_api_clients …
> fix: use binary_to_existing_atom to replace some risky binary_to_atom

- apps/emqx_gateway/src/emqx_gateway_api.erl
- apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl
- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
> Fix unexpected 400

- .github/actions/detect-profiles/action.yaml
- .github/actions/package-macos/action.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/release.yaml
- build otp manually instead of kerl
- bump versions on some actions
- fix deprecated way of setting step output in some cases
> ci: fix packages build for ee releases

- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_misc.erl
- apps/emqx_gateway/src/coap/handler/emqx_coap_pubsub_handler.erl
- apps/emqx_gateway/src/emqx_gateway_utils.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
1. emqx_listeners  emqx_gateway_utils
esockd rules only use words 'allow' and 'deny', both are existing,
so it is better to restrict the conversion and print a log when errors
2. emqx_misc  emqx_coap_pubsub_handler
Fix the comments in #9279 
3. emqx_mgmt_cli
The log level, the log handler id and the listener id  all of them already exist,
so it's better to avoid the user creating a useless atom by mistake input
~~- [ ] Added tests for the changes~~
~~- [ ] Change log has been added to `changes/` dir~~
~~- [ ] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)~~
EMQX-8021
> fix: use list_to_existing_atom to replace some risky list_to_atom

- .github/workflows/build_packages.yaml
the upload-artifacts action does not allow relative paths
> ci: fix artifact upload path

- .github/workflows/release.yaml
emqx/push-helm-action requires access to charts in the source tree, but we do not run checkout in the main job
Fixes #8953
> ci: fix helm chart upload on releases

- .github/workflows/release.yaml
Follow-up to [ci(actions): update git actions to latest versions](https://github.com/emqx/emqx/pull/9247), as the corresponding git action was updated for node16.
> chore(actions): update version for leftover action

- apps/emqx/src/emqx_access_control.erl
- apps/emqx/test/emqx_access_control_SUITE.erl
- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
We need to check the true topic of the delayed message correctly, the cheapest way to do this is to extract the true topic from the raw topic when doing ACL check
~~- [ ] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)~~
EMQX-7963
> fix(acl): Check the real topic in delayed messages

- .github/workflows/build_packages.yaml
Fix environmental variable reference in upload-artifact action.
> fix: env variable reference in upload-artifact@v3

- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_monitor.erl
- apps/emqx_rule_engine/test/emqx_rule_monitor_SUITE.erl
- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
This was not in the release scope of v4.3.22 and v4.4.4,
however it's a blocking issue for enterprise test cases.
The in case of resource creation failure, e.g. when failed to connect to a remote webhook endpoint,
the retry loop is started immediately, causing it to log failures immediately.
This fix is to add the sleep to the beginning of the loop.
Example logs after the fix:
```
(emqx@127.0.0.1)1> 2022-11-05T17:59:30.209407+01:00 [error] check http_connectivity failed: <<"http://locahost:1111">>
2022-11-05T17:59:30.209626+01:00 [warning] create_resource failed: [#{func => init_resource,node => 'emqx@127.0.0.1',result => {throw,{init_resource,check_http_connectivity_failed}},rpc_type => multicall}]
(emqx@127.0.0.1)1>
(emqx@127.0.0.1)1> 2022-11-05T18:00:30.213588+01:00 [error] check …
```
> fix(emqx_rule_monitor): sleep before retry but not after

- .github/workflows/build_packages.yaml
- build
> fix: remove outdated cert store from packages

- apps/emqx_authz/src/emqx_authz.app.src
- apps/emqx_authz/src/emqx_authz_api_sources.erl
- apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
Fixes [EMQX-7870](https://emqx.atlassian.net/browse/EMQX-7870)
Fixes [EMQX-7981](https://emqx.atlassian.net/browse/EMQX-7981)
> Authz API fixes

- .ci/docker-compose-file/docker-compose.yaml
- .github/workflows/build_and_push_docker_images.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/check_deps_integrity.yaml
- .github/workflows/code_style_check.yaml
- .github/workflows/elixir_apps_check.yaml
- .github/workflows/elixir_deps_check.yaml
- .github/workflows/elixir_release.yml
- .github/workflows/release.yaml
- .github/workflows/run_emqx_app_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_relup_tests.yaml
- .github/workflows/run_test_cases.yaml
- scripts/ct/run.sh
upgrade the OTP version for security reasons
EMQX-7683
> chore: bump OTP version

- apps/emqx_rule_engine/src/emqx_rule_engine.erl
The return value and failure pattern of init_resource_with_retrier/4 should be the same as init_resource/4.
The issue was introduced by this one: https://github.com/emqx/emqx/pull/9199
> fix: make init_resource_with_retrier/4 only 'throw' when failed

- src/emqx_crl_cache.erl
- src/emqx_listeners.erl
Will be used for hot-configuration (EE downstream) as well.
> feat(crl): register CRL URLs when starting TLS listeners

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_crl_cache.erl
- src/emqx_listeners.erl
- test/emqx_crl_cache_SUITE.erl
To avoid some confusion that may arise from the `enable_crl_cache` name.  Enabling this option is actually the way to enable the CRL check itself, and caching should always be on in that case.
> refactor(crl): rename `s/enable_crl_cache/enable_crl_check/g`

- .github/workflows/build_packages.yaml
- build
Reverts emqx/emqx#9321
The cert file is copied again to rel dir at the `tar` step.
> Revert "fix: remove outdated cert store from packages"

- Makefile
the `ct` command's default (when `--readable` option is not provided) is `true`
> test: change CT_READABLE default value to true

- apps/emqx/test/emqx_trace_SUITE.erl
- apps/emqx_authn/src/emqx_authn.app.src
- apps/emqx_authn/src/emqx_authn_api.erl
- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
This also makes sure we call the same code everytime we access an authenticator. Moreover we return a 500 in case a remote call fails due to technical issues.
Fixes [EMQX-7821](https://emqx.atlassian.net/browse/EMQX-7821)
> fix(emqx_authn_api): return 404 for status of unknown authenticator

- etc/emqx.conf
- priv/emqx.schema
- src/emqx_crl_cache.erl
- test/emqx_crl_cache_SUITE.erl
We make the CRL HTTP timeout the same for all listeners for simplicity
of understanding and implementation.
Based on top of #9347 
> fix(crl): make http timeout global for all listeners

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
We should use the `binary_to_atom` in what we really need. This PR filters out the subscription options from the swagger body first, so we can reduce the redundantly convert
EMQX-7977
>  fix(mgmt_api): Convert only what is needed when parsing subscription information

- changes/v4.3.22-en.md
- changes/v4.3.22-zh.md
- priv/emqx.schema
Make sure listener's tls_versions is `[tlsv1,tlsv1.1,tlsv1.2,tlsv1.3]`
> feat: validate tls_versions value

- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_authz/test/emqx_authz_jwt_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
Fix #9217 
According to [the spec](https://www.rfc-editor.org/rfc/rfc7519.html), the `exp` should be optional
[ EMQX-7924](https://emqx.atlassian.net/browse/EMQX-7924)
> fix(JWT): make the `exp` to be optional claim

- apps/emqx_auth_jwt/src/emqx_auth_jwt.erl
- apps/emqx_auth_jwt/test/emqx_auth_jwt_SUITE.erl
- changes/v4.3.23-en.md
- changes/v4.3.23-zh.md
The jwt ACL will return `deny` when the token is expired but it should return the `{stop, deny}` actually
EMQX-8051
> fix(jwt): fix the jwt ACL will return a wrong result when the token is expired

- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_banned.erl
- apps/emqx/test/emqx_banned_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
A banned client shouldn't continue to publish/receive, so it's better to kick its session when it is banned.
[EMQX-8109](https://emqx.atlassian.net/browse/EMQX-8109)
> feat(banned): kick session when it is banned by clientid

- priv/emqx.schema
- src/emqx_app.erl
- src/emqx_channel.erl
Addresses
https://github.com/emqx/emqx-enterprise/pull/1535#discussion_r1022132136
Since it enriches client information with more than just clientid alias.
> refactor(alias_enrichment): rename `enrich_clientid_alias` -> `enrich_with_aliases` and `clientid_enrichment_module` ->`alias_enrichment_module`

- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
fix: generating alarm name for utf8 resource id failed
> fix: generating alarm name for utf8 resource id failed

- bin/emqx
- bin/nodetool
The remsh node name is generated to be unique, this may cause atom leakage, so we need to change the generation rule to limit the total of these names
[EMQX-8221](https://emqx.atlassian.net/browse/EMQX-8221)
> chore: make remsh node name away from the atom DOS attack

- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_access_control.erl
- apps/emqx/test/emqx_access_control_SUITE.erl
Fix `emqx_access_control_SUITE` test for delayed topics
> chore(acl): fix acl test

- .github/workflows/build_packages.yaml
- pkg-vsn.sh
https://emqx.atlassian.net/browse/EMQX-8239
We no longer need to 'flavour' the packages with otp or elixir version numbers since we found a way forward for hot-upgrading 
Based this on v5.0.10 because we want to merge it to e5.0.0-beta.5
Will add release note change in the next PR after merge.
~~- [ ] Added tests for the changes~~
~~- [ ] Changed lines covered in coverage report~~
~~- [ ] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)~~
~~- [ ] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up~~
~~- [ ] In case of non-backward compatible changes, reviewer should check …
> ci: release only the default packages

- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
[Fixes 9210](https://github.com/emqx/emqx/issues/9201)
If we define mqtt in emqx.conf as:
```
mqtt {
max_qos_allowed = 1 
}
```
then GET `/configs/global_zones` will return `...mqtt {max_qos_allowed: 1}...`, the mqtt's other field is missing.
This PR tries to get the disappearing defaults back.
```
mqtt {
await_rel_timeout = "300s"
exclusive_subscription = false
idle_timeout = "15s"
ignore_loop_deliver = false
keepalive_backoff = 0.75
max_awaiting_rel = 100
max_clientid_len = 65535
max_inflight = 32
max_mqueue_len = 2000
max_packet_size = "11MB"
max_qos_allowed = 1
max_subscriptions = "infinity"
max_topic_alias = 65535
max_topic_levels = 65535
mqueue_default_priority = "lowest"
mqueue_priorities = "disabled"
"mqueue_store_qos0" = true
peer_cert_as_clientid = "disabled" …
```
> fix: Config API can't get the default values from raw config

- apps/emqx_statsd/i18n/emqx_statsd_schema_i18n.conf
- apps/emqx_statsd/include/emqx_statsd.hrl
- apps/emqx_statsd/src/emqx_statsd.app.src
- apps/emqx_statsd/src/emqx_statsd.erl
- apps/emqx_statsd/src/emqx_statsd_api.erl
- apps/emqx_statsd/src/emqx_statsd_app.erl
- apps/emqx_statsd/src/emqx_statsd_config.erl
- apps/emqx_statsd/src/emqx_statsd_schema.erl
- apps/emqx_statsd/src/emqx_statsd_sup.erl
- apps/emqx_statsd/test/emqx_statsd_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
Refactor emqx_statsd server
- Add `statsd.tags` config.
- Replace state record with map.
- Fix duplicate prefix keys.
- Improve test coverage > 90%.
- Use `emqx_config_handler` callback to hot update config.
> refactor: emqx_statsd hot update

- changes/v5.0.10-en.md
- changes/v5.0.10-zh.md
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
In fact, this bug fix merged into the v5.0.11
> chore: fix the bad change logs introduced in #9307

- apps/emqx/src/emqx_schema.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
This default value in v4.x is 128 but 65535 in v5. If the value is too large then the memory may be run out when parsing topic
[ EMQX-8120](https://emqx.atlassian.net/browse/EMQX-8120)
> fix: change the defualt value of `max_topic_levels` to 128

- apps/emqx_bridge/src/emqx_bridge.app.src
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_dashboard/src/emqx_dashboard.app.src
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
I just found some new unsafe `binary_to_atom` when I was investigating another issue. 
Maybe this PR doesn't need an update desc
> fix: fix newly found unsafe `binary_to_atom`

- apps/emqx/src/emqx_misc.erl
- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_msg.erl
- apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
- apps/emqx_rule_engine/src/emqx_rule_actions.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.app.src
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
this is a follow up for https://github.com/emqx/emqx/pull/9240
> 1121 rule bridge properties

- apps/emqx/src/emqx_connection.erl
- apps/emqx_gateway/src/bhvrs/emqx_gateway_impl.erl
**Previous:**  Always update ets twice.
**Now         :** Only insert ets once.
> chore: set channel info once

- apps/emqx_management/i18n/emqx_mgmt_api_publish_i18n.conf
- apps/emqx_management/src/emqx_mgmt_api_publish.erl
- apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
Fixes [EMQX-7751](https://emqx.atlassian.net/browse/EMQX-7751)
> EMQX 7751 support message properties

- apps/emqx/src/emqx_alarm.erl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/test/emqx_bpapi_static_checks.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_authn/src/enhanced_authn/emqx_enhanced_authn_scram_mnesia.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_mnesia.erl
- apps/emqx_authn/test/emqx_authn_mnesia_SUITE.erl
- apps/emqx_authn/test/emqx_enhanced_authn_scram_mnesia_SUITE.erl
- apps/emqx_authz/src/emqx_authz.app.src
- apps/emqx_authz/src/emqx_authz_api_mnesia.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_gateway/src/emqx_gateway_api_clients.erl
- apps/emqx_management/src/emqx_mgmt_api.erl
- apps/emqx_management/src/emqx_mgmt_api_alarms.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
- apps/emqx_management/src/emqx_mgmt_api_topics.erl
- apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl
- apps/emqx_modules/src/emqx_delayed.erl
- apps/emqx_modules/src/emqx_modules.app.src
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_SUITE.erl
- changes/v5.0.11-en.md
- changes/v5.0.11-zh.md
Fixes https://github.com/emqx/emqx/issues/9341
1. When performing a fuzzy search, `count` is always returned as `#{meta => #{count := 0}}`, because if we want to get the total number of results, We have to query all rows out and perform a fuzzy matching function each of rows. It's maybe more expensive.
2. Change the `emqx_channel_info` ets table type from `set` to `ordered_set`
This PR contains 2 fixes:
1. Fix incorrect Swagger Schema for `GET ../clients` and `GET ../subscriptions`.
3. …
> Improve Clients query performance

- apps/emqx/include/emqx.hrl
- apps/emqx/src/emqx_topic.erl
- apps/emqx/test/emqx_proper_types.erl
- apps/emqx/test/emqx_topic_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
This PR removes support for setting shared subscriptions with the non-standard $queue feature. Shared subscriptions is now part of the MQTT spec (using $share) and we will only support that from now on.
Fixes EMQX-8010.
PR to docs repo: https://github.com/emqx/emqx-docs/pull/1510
> feat: remove $queue in favor of $share

- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/emqx_connector_ssl.erl
There was an error in the try_clear_certs2/3 clause that the argument isn't the ssl field but including it.
> fix(connector): fix previous incorrectly fixes

- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
This adds missing error codes in the Swagger schema for the `/subscriptions` endpoint.
Fixes EMQX-7997.
> fix(mgmt_api): add missing error codes in schema

- apps/emqx_authn/i18n/emqx_authn_api_i18n.conf
- apps/emqx_authn/src/emqx_authn.app.src
- apps/emqx_authn/src/emqx_authn_api.erl
- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
Fixes [EMQX-7863](https://emqx.atlassian.net/browse/EMQX-7863)
> refactor: use PUT on `/position` to move authenticator

- apps/emqx_conf/src/emqx_conf_app.erl
- apps/emqx_conf/test/emqx_conf_app_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
Fixes [<9402>](https://github.com/emqx/emqx/issues/9402)
Make the data.zip file only in memory, don't need to save this on disk.
> fix: don't save cert/authz zip on disk when emqx start

- apps/emqx_authn/src/emqx_authn_api.erl
- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- apps/emqx_authn/test/emqx_authn_jwt_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
Fixes [EMQX-7982](https://emqx.atlassian.net/browse/EMQX-7982)
> refactor: return `204` instead of `200` for `PUT /authenticator/:id`

- apps/emqx_modules/src/emqx_modules.app.src
- apps/emqx_modules/src/emqx_telemetry_api.erl
- apps/emqx_modules/test/emqx_telemetry_api_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
Fixes [EMQX-7984](https://emqx.atlassian.net/browse/EMQX-7984)
> fix: return 404 for /telemetry/data in case it's disabled

- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_auth.erl
- apps/emqx_management/test/emqx_mgmt_bootstrap_app_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- changes/v4.4.12-en.md
- changes/v4.4.12-zh.md
When doing a hot upgrade or rolling upgrade, the `mqtt_app` table is not empty, Leading to skip import bootstrap users.
> fix: load bootstrap file when no bootstrap user

- apps/emqx_connector/test/emqx_connector_api_SUITE.erl
- apps/emqx_rule_engine/i18n/emqx_rule_engine_api.conf
- apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
Fixes [EMQX-7988](https://emqx.atlassian.net/browse/EMQX-7988)
Summary: 
* you have to query `GET /rules/:id/metrics` explicitly in order to get metrics to a given rule. To reset metrics of a given you resource you `PUT /rules/:id/metrics/reset`. 
* `/rules/:id/metrics/reset` now returns `204` instead of `200` to comply with rest of API
* for all queries that include `:id` a `404` is returned in case rule does not exist
> refactor: move metrics out of /rules(/:id) to /rules/:id/metrics

- apps/emqx/src/emqx_tls_lib.erl
- apps/emqx_psk/test/emqx_psk_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
There are some PSK ciphers both supported by OpenSSL and Erlang, but hidden in the `ssl:cipher_suites` so We need manually add them.
[EMQX-7235](https://emqx.atlassian.net/browse/EMQX-7235)
> fix(psk): Add more PSK ciphers support

- apps/emqx/priv/bpapi.versions
- apps/emqx/rebar.config
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_trace_SUITE.erl
- apps/emqx_retainer/src/emqx_retainer.app.src
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia_cli.erl
- apps/emqx_retainer/src/proto/emqx_retainer_proto_v2.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
- mix.exs
- rebar.config
Get rid of cluster-wide transactions on saving retained messages.
> chore(retainer): optimize index writes

- apps/emqx/src/emqx_access_control.erl
- apps/emqx/src/emqx_authentication.erl
- apps/emqx/test/emqx_authentication_SUITE.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
Fix `emqx_authenticator` cooperation with other `'client.authenticate'` hooks.
Also refactor authn metrics, because  there can be authenticators other than `emqx_authentication`.
Now authn/authz metrics look uniformly.
Fixes https://askemq.com/t/topic/2742/32
> Fix `emqx_authentication` hook cooperation with other hooks

- changes/v4.4.12-en.md
- changes/v4.4.12-zh.md
- deploy/charts/emqx/templates/configmap.env.yaml
- deploy/charts/emqx/values.yaml
Fixed EMQX Helm Chart can not set json type value for EMQX configuration items
> fix(helm): fix helm value explain error

- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_api.erl
- apps/emqx_gateway/test/emqx_lwm2m_api_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- changes/v5.0.12-en.md
- changes/v5.0.12-zh.md
Doing a HTTP POST to `/gateway/lwm2m/clients/{clientid}/read` returned 200 without a response body. This PR changes this so that `read`, `write` and `observe` all return 204 - No Content since they all share the same semantics.
Fixes EMQX-7983.
> Fix status code for lwm2m clients in api

- apps/emqx_dashboard/src/emqx_dashboard_api.erl
- apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
- changes/v5.0.13-en.md
- changes/v5.0.13-zh.md
Fixes [EMQX-8373](https://emqx.atlassian.net/browse/EMQX-8373)
> refactor: use POST not PUT for `/users/{name}/change_pwd`

- apps/emqx_machine/src/emqx_restricted_shell.erl
Reason: 'ce' (Community Edition) is only for internal use, when it comes to user/customer facing descriptions, we should use Opensource edition and Enterprise edition.
Similary, for user/customer facing shell prompt,
use `v` for Opensource edition and `e` for Enterprise
> refactor: change ce | ee to v | prefix for shell prompt

- build
- scripts/get-distro.sh
- scripts/relup-base-vsns.escript
```
$ ./scripts/buildx.sh --profile emqx --pkgtype zip --arch arm64 --builder ghcr.io/emqx/emqx-builder/4.4-23:24.3.4.2-1-amzn2
...
$ ls _packages/emqx
emqx-4.4.12-alpha.1-efc98147-otp24.3.4.2-1-amzn2-arm64.zip
emqx-4.4.12-alpha.1-efc98147-otp24.3.4.2-1-amzn2-arm64.zip.sha256
```
> build: fix relup on amzn2

- .github/workflows/run_test_cases.yaml
`matrix.profile` is useless, the `app` dimension is is an array, [0] is the app name, [1] is the profile.
> ci: no need to run ct with static profile matrix

- apps/emqx/rebar.config
- apps/emqx/src/emqx_config.erl
- apps/emqx_authn/src/emqx_authn.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- lib-ee/emqx_ee_bridge/rebar.config
- mix.exs
- rebar.config
this is a follow up fix for https://github.com/emqx/emqx/pull/9437
verified with:
```
env EMQX_AUTHENTICATION__1='{mechanism="password_based",backend="mysql",server="localhost:3306",database="emqx",username="emqx",password="******",query="SELECT password_hash, salt, is_superuser FROM mqtt_user WHERE username = ${username} LIMIT 1",password_hash_algorithm={name=sha256,salt_position=prefix},enable=true}' \
EMQX_AUTHENTICATION__1__server='"localhost:3333"' \
./_build/emqx/rel/emqx/bin/emqx consol
```
```
v5.0.11-g375e3de0(emqx@127.0.0.1)1> emqx:get_config([authentication]).
[#{backend => <<"mysql">>,database => <<"emqx">>,
enable => true,mechanism => <<"password_based">>,
password => <<"******">>,
password_hash_algorithm =>
#{name => <<"sha256">>,salt_position => <<"prefix">>},
query => …
```
> 1214 upgrade to hocon 0.32.0

- bin/emqx
Fixes `stat: %R: bad format` on MacOS <= 11 when running emqx.
> chore: fix RUNNER_ROOT_DIR detection on MacOS

- .github/PULL_REQUEST_TEMPLATE/ci.md
- .github/PULL_REQUEST_TEMPLATE/doc.md
- .github/PULL_REQUEST_TEMPLATE/v4.md
- .github/PULL_REQUEST_TEMPLATE/v5.md
Now there are 4 different kinds of PRs
* doc, nothing to fill
* ci, two check boxes
* v4, the old template
* v5, slightly different from v4 (no appup)
> chore: Add more PR templates

- mix.exs
- rebar.config.erl
The jq function in the rule engine uses the jq NIF implementation by default so there is often no need to start any jq port programs. Before this commit jq port programs were started anyway. This is fixed by not starting the jq application (the jq application is started automatically when the jq port implementation is activated).
> fix: do not start jq port programs when they are not needed

- apps/emqx/i18n/emqx_schema_i18n.conf
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_shared_sub.erl
- apps/emqx/test/emqx_session_SUITE.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- apps/emqx_connector/src/emqx_connector_jwt.erl
- apps/emqx_connector/src/emqx_connector_jwt_sup.erl
- changes/v5.0.13-en.md
- changes/v5.0.13-zh.md
Fixes [EMQX-7741](https://emqx.atlassian.net/browse/EMQX-7741)
- [n/a] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)
- [n/a] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [n/a] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section
> 1219 fix shared sub sticky

- .github/workflows/apps_version_check.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/check_deps_integrity.yaml
- .github/workflows/release.yaml
- .github/workflows/run_acl_migration_tests.yaml
- .github/workflows/run_automate_tests.yaml
- .github/workflows/run_cts_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_gitlint.yaml
- .github/workflows/shellcheck.yaml
GIT actions upgraded to their current latest versions, to mitigate [node12 support dro](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
> chore(actions): v4.4 update git actions versions

- bin/emqx
Fixes [EMQX-8577](https://emqx.atlassian.net/browse/EMQX-8577)
```
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
WARNING: Default (insecure) Erlang cookie is in use.
```
> chore: fix logging in bin/emqx on non-tty

- apps/emqx/src/emqx_map_lib.erl
- apps/emqx_bridge/i18n/emqx_bridge_api.conf
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- changes/v5.0.13-en.md
- changes/v5.0.13-zh.md
Fixes [EMQX-8571](https://emqx.atlassian.net/browse/EMQX-8571)
> feat(emqx_bridge): add /bridges_probe API endpoint

- apps/emqx_connector/src/emqx_connector_mysql.erl
- changes/v5.0.13-en.md
- changes/v5.0.13-zh.md
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_mysql_SUITE.erl
This is a continuation of EMQX-7923 and implements further EE mysql bridge tests covering:
- prepared statements
- batching
- driver behavior with timeout failures
A bug was found while implementing tests regarding prepared statements. An infinite loop was triggered in the mysql connector when a query used a prepared statement key that was not among the defined prepared statements on start. We now check that the key is defined among the prepared statements before recursing. It seems that this bug was never
triggered in any production code.
Fixes EMQX-8414.
> fix: infinite recursion in mysql connector and improve mysql EE bridge tests

- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_connector/i18n/emqx_connector_mqtt_schema.conf
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- changes/v5.0.13-en.md
- changes/v5.0.13-zh.md
https://emqx.atlassian.net/browse/EMQX-8445
Currently the bridge client’s client ID is prefixed with the resource ID.
Sometimes it’s useful for users to have control of this prefix, e.g. prefix based ACL rules in the target broker.
> feat(mqtt): add option to customize clientid prefix for egress bridges

- apps/emqx/src/emqx_banned.erl
- apps/emqx_management/test/emqx_mgmt_api_banned_SUITE.erl
- changes/v5.0.13-en.md
- changes/v5.0.13-zh.md
fix [EMQX-8460](https://emqx.atlassian.net/browse/EMQX-8460)
> fix(banned): ensure the default expiration time of `banned` is large enough

- build
* the edge edition is completely dropped in v5
* typically reboot is acceptable for edge brokers
* we do not know how many users are using it
* we never really seriously tested relup for edge edition
* now there is an issue in relup which will fail edge edition not worth the investment to fix
> build: drop relup for edge edition

- .github/workflows/build_packages.yaml
- mix.exs
- rebar.config.erl
This should heal OTP-25 package builds targeting `amzn2`.
---
[EMQX-8617](https://emqx.atlassian.net/browse/EMQX-8617)
> fix(ci): bump to jq v0.3.9 with OTP-25 prebuilt binaries

- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_logger_jsonfmt.erl
before:
```
./bin/emqx_ctl cluster status --json
{
"running_nodes": [
"emqx1@127.0.0.1"
],
"stopped_nodes": [91,93]
}
```
after:
```
./bin/emqx_ctl cluster status --json
{
"running_nodes": [
"emqx1@127.0.0.1"
],
"stopped_nodes": []
}
```
> fix: bad best fmt json []

- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/emqx_connector_jwt.erl
- apps/emqx_connector/src/emqx_connector_jwt_sup.erl
- apps/emqx_connector/src/emqx_connector_jwt_worker.erl
- apps/emqx_connector/test/emqx_connector_jwt_SUITE.erl
- apps/emqx_connector/test/emqx_connector_jwt_worker_SUITE.erl
- changes/v5.0.14-en.md
- changes/v5.0.14-zh.md
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_gcp_pubsub_SUITE.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector.app.src
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_gcp_pubsub.erl
https://emqx.atlassian.net/browse/EMQX-8653
Related:
- https://emqx.atlassian.net/browse/EEC-737
- https://emqx.atlassian.net/browse/EMQX-8652
Since the rule resource testing mechanism creates a new resource to test the configuration, a new JWT associated with an unique temporary resource was being created and left in the JWT table, leaking it.
Also, a wrong case clause when setting the new refresh timer for the JWT worker was preventing it from refreshing from the 2nd refresh onward.
> fix(gcp_pubsub): fix potential jwt accumulation and lack of refresh (v5.0)

- bin/emqx
- bin/install_upgrade.escript
https://emqx.atlassian.net/browse/EMQX-6978
[Related EIP](https://github.com/emqx/eip/blob/c4864eeccb4f2897f42e5c9e2917133a0d3215bd/active/0022-forward-check-install-upgrade-script.md)
Currently, when performing a hot upgrade, the scripts that are run are those from the currently installed EMQX version. It has a validation that prevents upgrade between different minor versions. If we want to allow an upgrade from, say, 5.0.x to 5.1.y, then the scripts in already released packages will deny such operation. Also, if an upgrade installation script contains a bug in the current, it will never be able to execute properly without manual patching.
By attempting to execute the scripts from the target version, we may add fixes and new validations to new EMQX versions and have them executed by …
> feat(upgrade): add forward version check for upgrade script

- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_metrics_worker.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx/test/emqx_metrics_worker_SUITE.erl
- apps/emqx/test/emqx_test_janitor.erl
- apps/emqx_bridge/i18n/emqx_bridge_schema.conf
- apps/emqx_bridge/src/emqx_bridge.app.src
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_metrics.erl
- apps/emqx_resource/src/emqx_resource_worker.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- lib-ee/emqx_ee_bridge/rebar.config
- lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl
- lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_producer_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_gcp_pubsub_SUITE.erl
- mix.exs
- scripts/merge-i18n.escript
https://emqx.atlassian.net/browse/EMQX-8548
Currently, we face several issues trying to keep resource metrics
reasonable.  For example, when a resource is re-created and has its
metrics reset, but then its durable queue resumes its previous work
and leads to strange (often negative) metrics.
Instead using `counters` that are shared by more than one worker to
manage gauges, we introduce an ETS table whose key is not only scoped
by the Resource ID as before, but also by the worker ID.  This way,
when a worker starts/terminates, they should set their own gauges to
their values (often 0 or `replayq:count` when resuming off a queue).
With this scoping and initialization procedure, we'll hopefully avoid
hitting those strange metrics scenarios and have better control over
the gauges.
> refactor(metrics): use absolute gauge values rather than deltas (v5.0)

- apps/emqx_connector/src/emqx_connector_mysql.erl
- changes/v5.0.14-en.md
- changes/v5.0.14-zh.md
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_mysql_SUITE.erl
fix [EMQX-8467](https://emqx.atlassian.net/browse/EMQX-8467)
~~1. fix incorrect metrics, including `Matched` `Sent Successfully` `Queuing` `Retried`~~
2. fix data loss issues
~~3. fix the problem that a message will be duplicated `batch size` times in `batch` mode~~
~~4.  simplify some data structure~~
>  fix(mysql): fix the problem of data loss and bad match when mysql is disconnected

- apps/emqx/src/emqx_misc.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- changes/v5.0.14-en.md
- changes/v5.0.14-zh.md
port `redact` from 4.3 to master, and obfuscate sensitive data in the response when querying `bridges` information by API
fix [EMQX-8374](https://emqx.atlassian.net/browse/EMQX-8374)
> fix(bridges): obfuscate the password in bridges API responses

- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_metrics.erl
The module `emqx_resource_metrics` is the new way to handle resource metrics.
The received counter is still being bumped using an one-off function, `emqx_resource:inc_received/1`, bypassing emqx_resource_metrics module APIs. This code path is removed in this PR and replaced with new functions in `emqx_resource_metrics`.
Fixes EMQX-8501.
> refactor(emqx_resource): ingress bridge counter

- apps/emqx_rule_engine/src/emqx_rule_engine.app.src
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_api_SUITE.erl
- changes/v5.0.14-en.md
- changes/v5.0.14-zh.md
https://emqx.atlassian.net/browse/EMQX-8502
When a bridge is disabled, its metrics are reset.  With this change, we make rule actions behave like that: disabling a rule will reset its metrics.
> chore(rule_engine): reset metrics when disabling a rule

- changes/v4.4.14-en.md
- changes/v4.4.14-zh.md
- lib-ce/emqx_dashboard/src/emqx_dashboard_admin.erl
- lib-ce/emqx_dashboard/test/emqx_dashboard_SUITE.erl
- scripts/get-dashboard.sh
Fix dashboard password validator is too simple. Now dashboard password must contain at least two different kind of characters from groups of letters, numbers and special characters.
> fix: update dashboard password validator

- apps/emqx_connector/rebar.config
- changes/v5.0.14/feat-9675.en.md
- changes/v5.0.14/feat-9675.zh.md
- mix.exs
- rebar.config
* https://github.com/emqx/ehttpc/compare/0.4.2...0.4.3
* https://github.com/emqx/eredis_cluster/compare/0.7.1...0.7.5
* https://github.com/emqx/eredis/compare/1.2.6...1.2.10 (transient)
Everything looks safe to upgrade except for [the missing `reconnect_loop/2` in `eredis`](https://github.com/emqx/eredis/compare/1.2.6...1.2.10#diff-4b609475abd2a5723f7d745ffa7048ae246ce6e385622aab08d328ff021aab3aL475) where some processes might be spinning during an upgrade (admittedly that's highly unlikely because it implies unstable redis cluster during an upgrade).
---
[EMQX-8562](https://emqx.atlassian.net/browse/EMQX-8562)
> chore: bump deps versions with full OTP-25 compat

- apps/emqx_connector/rebar.config
- changes/v5.0.14/feat-8329.en.md
- changes/v5.0.14/feat-8329.zh.md
Question: Since the enterprise branch has other apps that depends on MongoDB, I guess the enterprise branch has to be updated as well, right?
> feat: upgrade MongoDB library to support MongoDB 5.1+

- apps/emqx_authz/src/emqx_authz.app.src
- apps/emqx_authz/src/emqx_authz.erl
- apps/emqx_authz/src/emqx_authz_http.erl
- apps/emqx_authz/test/emqx_authz_http_SUITE.erl
- changes/v5.0.14/fix-9689.en.md
- changes/v5.0.14/fix-9689.zh.md
Related issue: https://github.com/emqx/emqx/issues/9683
When the HTTP request for authz fails (e.g.: resource is down or server is down), then the HTTP authorizer returns `ignore`, which was not handled correctly by the authorization callback.
> fix(authz_http): handle `ignore` results (request failures)

- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- changes/v5.0.14/fix-9703.en.md
- changes/v5.0.14/fix-9703.zh.md
Set the default value of qos to 0, which is the default value of the API `/mqtt/subscribe` and `/mqtt/subscribe_batch` in emqx 4.x.
> fix: missing default value for qos field of API /clients/:clientid/subscribe

- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- changes/v5.0.14/fix-9712.en.md
- changes/v5.0.14/fix-9712.zh.md
When bulk subscribing topics using HTTP API (`/clients/:clientid/subscribe/bulk`) in the `client.connected` hook (e.g. in an webhook action listen on the `client.connected` event), the subscription will fail because the `emqx_channel_info` has not yet populated with the clientid.
But the HTTP API subscribing a single topic (`/clients/:clientid/subscribe`) works.
> fix: bulk subscribe topics failed in the client.connected hook

- apps/emqx_bridge/i18n/emqx_bridge_webhook_schema.conf
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/src/schema/emqx_bridge_webhook_schema.erl
- apps/emqx_connector/src/emqx_connector_http.erl
- changes/v5.0.14/fix-9705.en.md
- changes/v5.0.14/fix-9705.zh.md
- if the default value is set to "", then we send "" as the http body.
- if the default value is not set, then we send all the available fields as the http body.
> fix: remove the default value of webhook body field

- .github/workflows/run_jmeter_tests.yaml
- apps/emqx_authz/i18n/emqx_authz_api_mnesia_i18n.conf
- apps/emqx_authz/src/emqx_authz.app.src
- apps/emqx_authz/src/emqx_authz_api_mnesia.erl
- apps/emqx_authz/test/emqx_authz_api_mnesia_SUITE.erl
- changes/v5.0.13-en.md
- changes/v5.0.13-zh.md
Fixes [EMQX-8372](https://emqx.atlassian.net/browse/EMQX-8372)
> refactor: move to /authorization/sources/built_in_database/rules

- apps/emqx_management/i18n/emqx_mgmt_api_publish_i18n.conf
- apps/emqx_management/src/emqx_mgmt_api_publish.erl
- changes/v5.0.14/fix-9667.en.md
- changes/v5.0.14/fix-9667.zh.md
To avoid security confusion, we remove the possibility to specify the client ID in the request body for `/publish` and `/publish/bulk`.
Fixes EMQX-8385.
> fix(mgmt_api): remove possibility to set clientid in /publish API

- apps/emqx_auto_subscribe/src/emqx_auto_subscribe.app.src
- apps/emqx_auto_subscribe/src/emqx_auto_subscribe.erl
- apps/emqx_auto_subscribe/src/emqx_auto_subscribe_api.erl
- apps/emqx_auto_subscribe/test/emqx_auto_subscribe_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl
- changes/v5.0.14/fix-9714.en.md
- changes/v5.0.14/fix-9714.zh.md
Fix: `/mqtt/auto_subscribe` API
1.  Bad swagger schema format. 
2. We should always check schema in swagger with `#{check_schema => true}`.
3. QoS is an integer (not a string).
Before:
After:
> fix: bad auto_subscribe api schema

- apps/emqx_connector/rebar.config
This upgrades mongodb-erlang from v3.0.18 to v3.0.19. This fixes a bug that occurred when one issued a command specified as a map*. This fix should not affect present EMQX as this functionality is currently not used by EMQX. However, I think it is good to do the upgrade anyway in case we will use the fixed functionality in the future. There is no need to update the changelog.
* https://github.com/emqx/mongodb-erlang/pull/36
> chore: upgrade mongodb-erlang to v3.0.19

- lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_mongodb.conf
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_mongodb.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_mongodb_SUITE.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_mongodb.erl
https://emqx.atlassian.net/browse/EMQX-8705
Adds a `payload_template` fields that allows users to customize the payload to publish to MongoDB.
> feat(mongodb): add `payload_template` field for bridge (e5.0)

- apps/emqx_authz/README.md
- apps/emqx_connector/README.md
- apps/emqx_connector/i18n/emqx_connector_schema_lib.conf
- apps/emqx_connector/include/emqx_connector.hrl
- apps/emqx_connector/src/emqx_connector_ldap.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/emqx_connector_mysql.erl
- apps/emqx_connector/src/emqx_connector_pgsql.erl
- apps/emqx_connector/src/emqx_connector_redis.erl
- apps/emqx_connector/src/emqx_connector_schema_lib.erl
- changes/v5.0.15/feat-9725.en.md
- changes/v5.0.15/feat-9725.zh.md
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_mysql.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_pgsql.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_redis.erl
- mix.exs
- rebar.config
Remove the `auto_reconnect` config as we already have the `resource_opts.auto_restart_interval`.
We force the `auto_reconnect` to true (2s) for all the resources that use ecpool.
> refactor: remove the auto_reconnect field

- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_prometheus/i18n/emqx_prometheus_schema_i18n.conf
- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
- apps/emqx_prometheus/src/emqx_prometheus_api.erl
- apps/emqx_prometheus/src/emqx_prometheus_schema.erl
- apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl
- changes/v5.0.15/feat-9722.en.md
- changes/v5.0.15/feat-9722.zh.md
Add the following configuration options for Pushing metrics to Prometheus Push Gateway:
- `headers`: Allows custom HTTP request headers.
- `job_name`: allows to customize the name of the Job pushed to Push Gateway.
> feat: more confs for prometheus pushing

- apps/emqx_authn/test/emqx_authn_mnesia_SUITE.erl
- apps/emqx_authn/test/emqx_enhanced_authn_scram_mnesia_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_mnesia_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_management/src/emqx_mgmt_api.erl
- apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
This flag indicates whether there are more results available on the next pages. It is needed in cases when the total number of search results is not known in advance (e.g. when client requests fuzzy search).
Also, in such cases there's no `count` field in responses anymore because responding with `0` was confusing for clients: it's not possible to differentiate between "there are no results" and "we don't know how much".
---
[EMQX-8702](https://emqx.atlassian.net/browse/EMQX-8702)
> fix(api): augment paged search responses with `hasnext` flag

- apps/emqx_connector/src/emqx_connector_http.erl
- apps/emqx_connector/src/emqx_connector_ldap.erl
- apps/emqx_connector/src/emqx_connector_mongo.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/emqx_connector_mysql.erl
- apps/emqx_connector/src/emqx_connector_pgsql.erl
- apps/emqx_connector/src/emqx_connector_redis.erl
- changes/v5.0.15/fix-8718-en.md
- changes/v5.0.15/fix-8718-zh.md
Information log messages for several connectors contained sensitive password information. This commit fixes this by hiding the sensitive information from the log messages.
Fixes: https://emqx.atlassian.net/browse/EMQX-8718
> fix: remove password from info logs

- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_jmeter_tests.yaml
- apps/emqx/include/http_api.hrl
- apps/emqx/test/emqx_common_test_http.erl
- apps/emqx_authn/test/emqx_authn_api_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_cache_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_mnesia_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_settings_SUITE.erl
- apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
- apps/emqx_auto_subscribe/test/emqx_auto_subscribe_SUITE.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_dashboard/src/emqx_dashboard_api.erl
- apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
- apps/emqx_dashboard/test/emqx_dashboard_bad_api_SUITE.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- apps/emqx_exhook/test/emqx_exhook_api_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_test_utils.erl
- apps/emqx_management/src/emqx_mgmt_auth.erl
- apps/emqx_management/test/emqx_mgmt_api_api_keys_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
- apps/emqx_modules/test/emqx_delayed_api_SUITE.erl
- apps/emqx_modules/test/emqx_rewrite_api_SUITE.erl
- apps/emqx_modules/test/emqx_telemetry_api_SUITE.erl
- apps/emqx_modules/test/emqx_topic_metrics_api_SUITE.erl
- apps/emqx_slow_subs/test/emqx_slow_subs_api_SUITE.erl
- changes/v5.0.15/feat-9586.en.md
- changes/v5.0.15/feat-9586.zh.md
From: [EMQX-8376](https://emqx.atlassian.net/browse/EMQX-8376)
Goal: ensure the API only can be called with the API key or use the bearer token
> fix: disable basic auth for HTTP API

- apps/emqx_plugin_libs/src/emqx_plugin_libs.app.src
- apps/emqx_plugin_libs/src/emqx_plugin_libs_rule.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_influxdb.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
- lib-ee/emqx_ee_connector/rebar.config
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
- mix.exs
Remove the default value of timestamp field of the influxdb data-bridge.
Before this change, the `timestamp` defaults to `${timestamp}`, but this requires the Rule has a `timestamp` field in its output.
I removed the default value so that if the `timestamp` is not provided, it will use the current time according to the `precision` field.
> refactor: remove default value of timestamp field of influxdb

- apps/emqx/src/emqx_schema.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
- changes/v5.0.15/fix-9748-en.md
- changes/v5.0.15/fix-9748-zh.md
Fix: https://github.com/emqx/emqx/issues/9733
When we don't set the `max_connections` of the listener, he will use the default value.
```
listeners.tcp.demo {
bind = "0.0.0.0:2883"
}
```
we fill the raw config with the default value in `emqx_listener:do_list_raw/0`.
```erlang
Key = <<"listeners">>,
Raw = emqx_config:get_raw([Key], #{}),
SchemaMod = emqx_config:get_schema_mod(Key),
#{Key := RawWithDefault} = emqx_config:fill_defaults(SchemaMod, #{Key => Raw}, #{}),
```
The default value should not be an atom, but binary.
> fix: default max_connections in raw config should be binary not atom

- .gitignore
- apps/emqx/src/config/emqx_config_logger.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_conf_app_SUITE.erl
- apps/emqx_resource/src/emqx_resource.app.src
If we configure `logger` and `prometheus`  in `cluster-override.conf`
```
log {
file_handlers {
default {
burst_limit {
enable = true
max_count = 10000
window_time = "1s"
...
}
prometheus {
enable = true
interval = "151s"
job_name = "${name}/instance/${name}~${host}"
mnesia_collector = "enabled"
push_gateway_server = "http://127.0.0.1:9091"
vm_dist_collector = "enabled"
vm_memory_collector = "enabled"
vm_msacc_collector = "enabled"
vm_statistics_collector = "enabled"
vm_system_info_collector = "enabled"
}
```
These configurations will have no effect. This is because `log` is an environment variable for `kernal` applications.
`*_collector` are the environment variable for the `prometheus` application.
we need to save those two applications' env after init_load.
close …
> fix: save app's env when bootstrapping and reloading

- apps/emqx/src/emqx_packet.erl
to keep it a consistent behaviour comparing when logging username
> fix(emqx_packet): log empty string if password value is missing

- bin/emqx
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_redis_SUITE.erl
```
docker run --rm -it -v /tmp:/opt/emqx/etc emqx/emqx:5.0.14-g91c5a899
ERROR: emqx.conf is not found in /opt/emqx/etc
```
```
docker run --rm -it -v /tmp:/opt/emqx/etc emqx/emqx:5.0.14
escript: exception throw: {emqx_conf_schema,[#{kind => validation_error,
path => "node.cookie",
reason => required_field,
value => undefined},
#{kind => validation_error,
path => "node.data_dir",
reason => required_field,
value => undefined}]}
in function  hocon_tconf:assert/2 (hocon_tconf.erl, line 1171)
in call from hocon_tconf:map/4 (hocon_tconf.erl, line 308)
in call from hocon_cli:get_values/3 (hocon_cli.erl, line 194)
in call from hocon_cli:multi_get/2 (hocon_cli.erl, line 182)
in call from escript:run/2 (escript.erl, line 750)
in call from escript:start/1 (escript.erl, line 277)
in call from …
```
> 0114 boot log emqx.conf missing

- Makefile
- apps/emqx/include/emqx_placeholder.hrl
- apps/emqx_plugin_libs/src/emqx_placeholder.erl
- apps/emqx_rule_engine/src/emqx_rule_maps.erl
- lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_kafka.conf
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_kafka.erl
- lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl
- lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_producer_SUITE.erl
Prior to this change there is no way to express 'the root' in value templates.
Now a hidden `this` is introduced, and `.` is allowed in front of each var (path)
`${.client}` means the same thing as `${client}` (for compatibility reasons).
most importantly `${.}` means `this`.
With `${.}` supported, there is no longer the ambiguity of configs like:
"if this template is left empty, then it means send the whole thing",
for which, the template parsing and rendering both need special function clauses.
e.g. https://github.com/emqx/emqx/pull/9705
Edit:
Prior to this change, "${.}" is a 'valid' placeholder, but it can never work as it's parsed into empty path segments like below.
so there is no compatibility issue introduced in this change.
```
> emqx_placeholder:preproc_tmpl("${.}"). …
```
> feat: introduce 'this' concept for placeholder, and use it in Kafka bridge

- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_gcp_pubsub.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_gcp_pubsub_SUITE.erl
Bridges that don't have an ssl conf in their schema (like `gcp_pubsub`) cause a crash.
Fixes [EMQX-8754](https://emqx.atlassian.net/browse/EMQX-8754).
> EMQX 8754 test function return 500 of data integration google pubsub

- apps/emqx/etc/vm.args.cloud
- apps/emqx_conf/i18n/emqx_conf_schema.conf
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_machine/src/emqx_machine.app.src
- apps/emqx_machine/src/user_default.erl
- Fix bad `node.crash_dump_file` default value in rpm.
- More detail about `node.crash_dump_seconds` and `node_crash_dump_bytes`. we can set this to 0 to prevent the generation of crash-dump file.
- Remove `ERL_CRASH_DUMP` from `vm.args.cloud`. we configure this from `node.crash_dump_file`.  so we remove this comment from `vm.args.cloud`.
- Remove `-kernel net_ticktime` from `vm.args.cloud`. we configure this from `node.dist_net_ticktime`.If the user modifies both(`node.dist_net_ticktime` and `etc/vm.args`), this can be confusing as to which one is in effect. so we remove it from vm.args.
- Add some alias trace fun to user_default.
> chore: more detail about crash dump config

- apps/emqx_dashboard/i18n/emqx_dashboard_api_i18n.conf
- apps/emqx_dashboard/i18n/emqx_dashboard_i18n.conf
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
1. Change `send_timeout`'s default from `5s` to `10s`  to improve concurrency.
2. Change `num_acceptors`'s default from 4 to `erlang:system_info(schedulers_online)`.
3. Improve the dashboard's document.
> chore: improve the dashboard's configuration

- .github/CODEOWNERS
- deploy/charts/emqx/README.md
- deploy/docker/Dockerfile
- deploy/docker/Dockerfile.alpine
- deploy/docker/README.md
Fixes [EMQX-8523](https://emqx.atlassian.net/browse/EMQX-8523).
- loaded plugins and loaded modules are not applicable in 5.0
- add information on how to correctly persist configuration in `/etc/`
- remove --platform arg from Dockerfile
- update documentation links in charts readme
> docs: update docker documentation

- apps/emqx/src/emqx_alarm.erl
- apps/emqx/src/emqx_broker.erl
- apps/emqx_authn/src/enhanced_authn/emqx_enhanced_authn_scram_mnesia.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_mnesia.erl
- apps/emqx_auto_subscribe/test/emqx_auto_subscribe_SUITE.erl
- apps/emqx_gateway/src/emqx_gateway_cm.erl
- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_app.erl
This is needed to ensure more or less consistent client experience for the new planned cursor-based search APIs.
Notably, the [route table](https://github.com/emqx/emqx/blob/677265bec2190fde5110a9cb5017f468b310fbc8/apps/emqx_management/src/emqx_mgmt_api_topics.erl#L113) is currently left out of scope, that one's being a `bag` is critically important for the router logic. It might be simpler to implement cursor-based search in `emqx_mgmt_api_topics` (which currently relies on the route table) on top of another table / data structure.
---
[EMQX-8738](https://emqx.atlassian.net/browse/EMQX-8738)
> feat: turn tables queried with search APIs into ordered sets

- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_schema_tests.erl
- apps/emqx_authn/test/emqx_authn_SUITE.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_connector/src/emqx_connector_schema_lib.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard_schema.erl
- apps/emqx_gateway/src/emqx_gateway_schema.erl
- changes/v5.0.15/fix-9765.en.md
- changes/v5.0.15/fix-9765.zh.md
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_kafka.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
fixes #9400
Now `EMQX_DASHBOARD__DEFAULT_PASSWORD=1234` is allowed.
With `EMQX_DASHBOARD__DEFAULT_PASSWORD='{a:1}'`
You get 
[error] #{kind => validation_error,path => "dashboard.default_password",reason => "must_quote"}
```
> fix(schema): add password converter to ensure its binary() type

- lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_redis.conf
Add more helpful descriptions for `command_template` option of Redis bridge.
> chore(bridges): add more helpful descriptions

- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker_sup.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_sup.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_mysql.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_pgsql.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_mysql_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_pgsql_SUITE.erl
Renaming `emqx_resource_worker` to `emqx_resource_buffer_worker` for clarity of purpose.
> buffer work refactoring follow up (part 1)

- deploy/charts/emqx-enterprise/README.md
- deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
- deploy/charts/emqx-enterprise/templates/_helpers.tpl
- deploy/charts/emqx-enterprise/templates/rbac.yaml
- deploy/charts/emqx-enterprise/values.yaml
- deploy/charts/emqx/README.md
- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/templates/_helpers.tpl
- deploy/charts/emqx/templates/rbac.yaml
- deploy/charts/emqx/values.yaml
Sometimes, in order to use certain secrets and provide access to the kubernetes cluster user need to provide specifies service account to the EMQX deployment
> feat(helm): user can define service account by userself

- deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
- deploy/charts/emqx-enterprise/templates/service.yaml
- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/templates/service.yaml
Right now internal MQTT port using the default listener which is not good because we want to have two different port for internal and external services.
> Correct `internalmqtt` port configuration in chart

- apps/emqx_ft/src/emqx_ft.app.src
- apps/emqx_ft/src/emqx_ft.erl
- apps/emqx_ft/src/emqx_ft_assembler.erl
- apps/emqx_ft/src/emqx_ft_assembler_sup.erl
- apps/emqx_ft/src/emqx_ft_assembly.erl
- apps/emqx_ft/src/emqx_ft_storage_fs.erl
Right now no context provided to the frontend.
Assembling of a single file is done in 4 general steps:
1. Ask local node for known fragments of the file.
2. If local node doesn't have enough fragments, ask **all other nodes** for known fragments.
3. If it's still not enough, bail out.
4. Read file segments from coverage nodes sequentially, one-by-one, writing them down to the local file, bailing out on any failure.
Open questions.
* Process naming.
* Configuration.
* Need for retries / recovery.
* Communication with the channel process (e.g. how to say _file assembled_ or _we failed we're very sorry_).
---
[EMQX-8265](https://emqx.atlassian.net/browse/EMQX-8265)
> feat(ft): introduce simple filesystem storage backend + assembler

- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
Also unwrap singleton `gen_statem` actions, so that the code would be easier to follow and harder to break.
Also drop a couple of unused macrodefs.
> fix(mqtt_bridge): use correct gen_statem reply action

- apps/emqx/src/emqx_config.erl
- apps/emqx_authz/test/emqx_authz_redis_SUITE.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_gcp_pubsub_SUITE.erl
fixes:
https://emqx.atlassian.net/browse/EMQX-8782
For calls discarded due to buffer overflow, an error should replied immediately instead of waiting for timeout.
> 0126 reply caller for buffer overflow queue items

- apps/emqx_connector/src/emqx_connector_redis.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_redis.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_redis_SUITE.erl
Batching will inevitably fail otherwise: it's not generally possible to update different keys through the same cluster connection, one or more update will fail with `MOVED` status.
> feat(redis): disable batching in redis_cluster bridges

- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_resource/src/emqx_resource_manager.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
Several places exposed InfluxDB tokens in log messages. These are now redacted. Some log messages were also reported on the `error` log level for connection failures. These should be warnings instead.
Fixes EMQX-8787 and EMQX-8788.
> fix: redact influxdb tokens in logs and reduce log level

- apps/emqx/include/logger.hrl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_logger_textfmt.erl
- apps/emqx/src/emqx_packet.erl
- apps/emqx/src/emqx_ws_connection.erl
- apps/emqx/test/emqx_mqtt_SUITE.erl
- Don't log CONNECT packet twice.
- Make the log output format order fixed. `msg, mfa, line, peername,clientid,topic`.
- Use brackets to wrap the MQTT packet when logging.
```
2023-01-30T16:39:24.889009+08:00 [debug] msg: raw_bin_received, mfa: emqx_connection:when_bytes_in/3, line: 740, peername: 127.0.0.1:62119, bin: 101E00044D51545405C2003C000004746573740003666F6F0006313233343536, size: 32, type: hex
2023-01-30T16:39:24.889361+08:00 [debug] msg: mqtt_packet_received, mfa: emqx_channel:handle_in/2, line: 356, peername: 127.0.0.1:62119, clientid: test, packet: CONNECT(Q0, R0, D0, ClientId=test, ProtoName=MQTT, ProtoVsn=5, CleanStart=true, KeepAlive=60, Username=foo, Password=******), tag: MQTT
2023-01-30T16:39:24.889922+08:00 [debug] msg: insert_channel_info, mfa: …
```
> feat: optimize the log output format

- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
prior to this change, the Request body is kept in the async reply callback args,
the args are passed down to the async API handers (bridge driver).
The Request, which can be potentially very large,
is actually not needed (except for when testing) when the async callback is evaluated.
this PR is to replace this term with en empty list `[]`.
> 0127 refactor buffer worker no need to keep request for reply callback

- apps/emqx_coap/rebar.config
- changes/v4.4.15-en.md
- changes/v4.4.15-zh.md
Avoid crash logs in CoAP gateway when receiving liveness checking packets from Load Balancer
see: https://github.com/emqx/gen_coap/pull/20
> Upgrade gen coap to v0.4.3

- apps/emqx/src/config/emqx_config_logger.erl
- apps/emqx/src/emqx_app.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
fixes: https://emqx.atlassian.net/browse/EMQX-8804
Prior to this fix, whatever configured for loggers are persisted to cluster-override.conf.
This may cause troulbe for users who changes boot mode.
For example if the node is once started in console mode,
the logging config is persisted, with console enabled, but file disabled.
Then if the user decide to start in daemon mode, all the logs
will silently go to erlang.log.N and emqx.log.N will be empty.
After this fix, only changes really made into cluter-override.conf will take effect.
new `foreground` boot logs:
```
EMQX_dashboard__default_password [dashboard.default_password]: ******
EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE [log.file_handlers.default.enable]: false
EMQX_LOG__CONSOLE_HANDLER__ENABLE [log.console_handler.enable]: true …
```
> 0131 avoid persisting logging configs if no change

- apps/emqx/src/config/emqx_config_logger.erl
- apps/emqx/src/emqx_app.erl
- apps/emqx_conf/src/emqx_conf_app.erl
- deploy/packages/emqx.service
1. Refresh log-config as soon as you get the `override.conf` configuration.
2. Update the primary log level when refreshing log-config.
3. Don't crash if add_handler failed.
This PR is related https://github.com/emqx/emqx/pull/9876, so it doesn't have the relevant tickets.
> fix: primary logger level not update

- apps/emqx/rebar.config
- apps/emqx_authn/test/emqx_authn_pgsql_SUITE.erl
- apps/emqx_authz/test/emqx_authz_redis_SUITE.erl
- apps/emqx_connector/i18n/emqx_connector_http.conf
- apps/emqx_connector/src/emqx_connector_http.erl
- mix.exs
- rebar.config
fixes: https://emqx.atlassian.net/browse/EMQX-8847
> fix(ehttpc): fix crash when webhook bridge uses `hash` pool type.

- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
So the code is easier to follow. Also add more tests to have better coverage of recent changes.
Followup to #9870, #9879.
---
[EMQX-8798](https://emqx.atlassian.net/browse/EMQX-8798)
> refactor(mqtt-worker): avoid unnecessary abstraction

- apps/emqx/src/emqx_misc.erl
- apps/emqx_connector/src/emqx_connector_http.erl
- changes/v5.0.16/fix-9839.en.md
- changes/v5.0.16/fix-9839.zh.md
The Authorization header contains sensitive information (e.g., password) so one typically don't want to print this to log files. This PR makes sure that the content of a Authorization header that users have specified for a webhook bridge is not printed to log files.
Jira issue: https://emqx.atlassian.net/browse/EMQX-8791
I don't know if release-50 is the right branch for this to be merged to so let me know if another branch is better and I will rebase it to that branch instead.
> fix: Authorization header leak in log entries for webhook

- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
We are ignoring the user configuration because there's currently no reliable way to ensure proper session recovery according to the MQTT spec.
---
[EMQX-8857](https://emqx.atlassian.net/browse/EMQX-8857)
> fix(mqtt-bridge): stop respecting `clean_start` config parameter

- Makefile
- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
The test case which appends new config to the end of emqx.conf.all might contaminate other test cases after it.
This PR changes to use "include" derivative from HOCON which can tolerate files to be included being missing -- this allows us to safely delete the temp config file after the test, so it won't contaminate other tests even when the "include" is left behind.
> 0202 fix flaky tests

- deploy/charts/emqx-enterprise/templates/configmap.yaml
- deploy/charts/emqx-enterprise/values.yaml
- deploy/charts/emqx/templates/configmap.yaml
- deploy/charts/emqx/values.yaml
It's not uncommon to use another clusterDomain in Kubernetes.
With this new config value, it's possible to avoid manually overriding some environment variables.
> fix: add clusterDomain in values

- apps/emqx_dashboard/src/emqx_dashboard_api.erl
Before:
2023-02-03T16:56:23.087811+08:00 [error] msg: Dashboard change password, mfa: emqx_dashboard_api:change_pwd/2, line: 344, reason: error old pwd, result: failed, username: <<"admin">>
After:
2023-02-03T16:57:24.081831+08:00 [error] msg: Dashboard change password, mfa: emqx_dashboard_api:change_pwd/2, line: 344, reason: error old pwd, result: failed, username: admin
> chore: remove <<>> when logging username

- apps/emqx_ft/i18n/emqx_ft_api_i18n.conf
- apps/emqx_ft/src/emqx_ft.erl
- apps/emqx_ft/src/emqx_ft_api.erl
- apps/emqx_ft/src/emqx_ft_storage.erl
- apps/emqx_ft/src/emqx_ft_storage_dummy.erl
- apps/emqx_ft/src/emqx_ft_storage_fs.erl
- apps/emqx_ft/src/proto/emqx_ft_storage_fs_proto_v1.erl
```
>cat test-file.txt
aaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccc
dddddddddddddddddddd
eeeeeeeeeeeeeeeeeeee
ffffffffffffffffffff
gggggggggggggggggggg
hhhhhhhhhhhhhhhhhhhh
>emqx-ft --file test-file.txt --file-id f1 --client-id cl1
DEBUG:root:Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'cl1'
DEBUG:root:Sending PUBLISH (d0, q1, r0, m1), 'b'$file/f1/init'', ... (38 bytes)
DEBUG:root:Sending PUBLISH (d0, q1, r0, m2), 'b'$file/f1/0'', ... (168 bytes)
DEBUG:root:Sending PUBLISH (d0, q1, r0, m3), 'b'$file/f1/fin'' (NULL payload)
DEBUG:root:Received CONNACK (0, 0)
DEBUG:root:Received PUBACK (Mid: 1)
DEBUG:root:Received PUBACK (Mid: 2)
DEBUG:root:Received PUBACK (Mid: 3)
^CDEBUG:root:Sending DISCONNECT
Disconnected
>curl -s -u 'key:secret' …
```
> feat(ft): add API

- apps/emqx_management/src/emqx_mgmt_api.erl
- changes/v4.4.15-en.md
- changes/v4.4.15-zh.md
The returned client lists of HTTP query `GET /api/v4/clients?_page=2&_limit=20` to different nodes are inconsistent.
We should rpc_call to emqx nodes in a determined order.
> fix(http-api): using a fixed order when cluster query nodes

- apps/emqx/src/emqx_authentication.erl
- apps/emqx/src/emqx_authentication_config.erl
- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_hocon.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_authentication_SUITE.erl
- apps/emqx_authn/src/emqx_authn.app.src
- apps/emqx_authn/src/emqx_authn.erl
- apps/emqx_authn/src/emqx_authn_api.erl
- apps/emqx_authn/src/emqx_authn_app.erl
- apps/emqx_authn/src/emqx_authn_password_hashing.erl
- apps/emqx_authn/src/emqx_authn_schema.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_http.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_mongodb.erl
- apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl
- apps/emqx_authn/test/emqx_authn_SUITE.erl
- apps/emqx_authn/test/emqx_authn_mnesia_SUITE.erl
- apps/emqx_authn/test/emqx_authn_pgsql_SUITE.erl
- apps/emqx_authn/test/emqx_authn_redis_SUITE.erl
- apps/emqx_authn/test/emqx_authn_schema_SUITE.erl
- apps/emqx_authn/test/emqx_authn_schema_tests.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- bin/emqx
https://emqx.atlassian.net/browse/EMQX-8657
Also got rid of the `lazy` type which forced us to validate the config during node boot sequence, but not before.
Verified with below test script:
```
env EMQX_AUTHENTICATION__1='{mechanism="password_based",backend="mysql",server="localhost:3306",database="emqx",username="emqx",password="emqx",query="SELECT password_hash, salt, is_superuser FROM mqtt_user WHERE username = ${username} LIMIT 1",password_hash_algorithm={name=sha256,salt_position=prefix},enable=true}' \
EMQX_DASHBOARD__default_password='ppp***' \
EMQX_AUTHENTICATION__1__backend=yoursql \
EMQX_NODE__COOKIE=foobar \
./_build/emqx/rel/emqx/bin/emqx check_config
```
`check_config` command does not find the error,
instead, it will crash when starting with quite a few lines of  rather big …
> 0108 refactor authn schema union member selector

- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
- changes/v5.0.17/feat-9930.en.md
- changes/v5.0.17/feat-9930.zh.md
This PR exposes the stats live_connections.count and live_connections.max to Prometheus.
Sister to https://github.com/emqx/emqx/pull/9929 for v4.4.
Fixes EMQX-8852.
> feat(emqx_prometheus): expose live_connections stats to prometheus

- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_connector/i18n/emqx_connector_mqtt_schema.conf
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
- apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
- changes/v5.0.17/fix-9952.en.md
- changes/v5.0.17/fix-9952.zh.md
Also bring back the ability to configure `clean_start`, but only for subscriptions to the ingresses.
---
[EMQX-8934](https://emqx.atlassian.net/browse/EMQX-8934)
> fix(mqtt-bridge): disallow QoS 2 on ingress bridges

- scripts/ct/run.sh
If one runs a test suite for an EE app using `scripts/ct/run.sh` without setting the EE profile, the test suite seems to just get stuck. This commit ensures that this will not happen and can hopefully save someone some time.
> build: make sure run.sh with EE app is used with EE profile

- bin/emqx
Fixes [8948](https://emqx.atlassian.net/browse/EMQX-8948)
The original issue reporter complained that when a node is already running, there should be no need to check and warn the cookie being not-secure.
Prior to this PR, the check of whether node is running is to issue a command `emqx ping` to probe its liveness.
This PR changes to use the `ps -ef` command output.
- [~] Change log has been added to `changes/<version>/(feat|fix)-<PR-id>.en.md` and `.zh.md` files
> Refactor: Check node already started before cookie warning

- .ci/docker-compose-file/pgsql/Dockerfile
- .ci/docker-compose-file/pgsql/pg_hba_tls.conf
- apps/emqx_connector/src/emqx_connector_pgsql.erl
- changes/v5.0.18/fix-9978.en.md
- changes/v5.0.18/fix-9978.zh.md
Fixes https://github.com/emqx/emqx/issues/9907
At v5.0.14, we changed the `ssl` option for the Postgres connector from `true` to `required`, but there was another transformation in `conn_opts/2` that led to an incorrect configuration.  This change ended up preventing users from connecting to Postgres with their previous configurations after upgrading EMQX.
> fix(pgsql): fix ssl option for pgsql connector to match previous behavior (5.0)

- apps/emqx_ft/src/emqx_ft.erl
- apps/emqx_ft/src/emqx_ft_assembler.erl
- apps/emqx_ft/src/emqx_ft_assembler_sup.erl
- apps/emqx_ft/src/emqx_ft_responder.erl
- apps/emqx_ft/src/emqx_ft_responder_sup.erl
- apps/emqx_ft/src/emqx_ft_storage.erl
- apps/emqx_ft/src/emqx_ft_storage_fs.erl
- apps/emqx_ft/src/emqx_ft_sup.erl
- apps/emqx_ft/test/emqx_ft_SUITE.erl
- apps/emqx_ft/test/emqx_ft_assembler_SUITE.erl
- apps/emqx_ft/test/emqx_ft_responder_SUITE.erl
Introduce an ad-hoc concept of tasks that need to be kicked off manually. Rework filesystem backend to accommodate for this change. Adapt responder logic for that "kickoff" protocol.
---
[EMQX-8913](https://emqx.atlassian.net/browse/EMQX-8913)
> feat(ft): make storage backend fully async-aware

- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
This PR adds a regression test for recursive flushing in `emqx_resource_buffer_worker`. The actual crash was fixed earlier in #9835.
Fixes EMQX-8784.
> Add regression test for resource buffer worker flush

- apps/emqx/src/emqx_kernel_sup.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_ctl/README.md
- apps/emqx_ctl/rebar.config
- apps/emqx_ctl/src/emqx_ctl.app.src
- apps/emqx_ctl/src/emqx_ctl.erl
- apps/emqx_ctl/src/emqx_ctl_app.erl
- apps/emqx_ctl/src/emqx_ctl_sup.erl
- apps/emqx_ctl/test/emqx_ctl_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard.app.src
- apps/emqx_gateway/src/emqx_gateway.app.src
- apps/emqx_machine/src/emqx_machine.app.src
- apps/emqx_machine/src/emqx_machine.erl
- apps/emqx_management/src/emqx_management.app.src
- apps/emqx_management/src/emqx_mgmt_app.erl
- apps/emqx_modules/src/emqx_modules.app.src
- apps/emqx_retainer/src/emqx_retainer.app.src
- apps/emqx_rule_engine/src/emqx_rule_engine.app.src
- lib-ee/emqx_license/src/emqx_license.app.src
Start `emqx_ctl` process before `emqx_machine` application, to get the CLI working, even if the rest of the EMQX is down. It may happen when on replicant node when it can't join to any core node.
Sadly, because emqx bootstrapping is done in a separate application, and because `apps/emqx` may be used standalone, I had no other way, but to split emqx_ctl module to a separate app to make all static checks happy. This is, admittedly, a pretty hacky solution, since this new repo is useless on its own.
> Mria replicant manual join

- Makefile
For Opensource edition:
https://github.com/emqx/emqx-dashboard-web-new/releases/tag/v1.1.8
For Entperprise edition:
https://github.com/emqx/emqx-dashboard-web-new/releases/tag/e1.0.4-beta.3
> chore: upgrade dashboards

- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_ft/test/emqx_ft_SUITE.erl
- apps/emqx_ft/test/emqx_ft_api_SUITE.erl
- apps/emqx_ft/test/emqx_ft_conf_SUITE.erl
- apps/emqx_ft/test/emqx_ft_storage_fs_SUITE.erl
- apps/emqx_ft/test/emqx_ft_storage_fs_reader_SUITE.erl
- apps/emqx_ft/test/emqx_ft_test_helpers.erl
`emqx` test helpers start some apps "manually" (like `ekka`, `mria`, `gen_rpc`) before all the other apps.
So when we start `emqx_conf`, its rendered and loaded configs do not influence already started things (like `gen_rpc` servers), but influence newly started things (like `gen_rpc` discovery and clients). 
So when we start `emqx_conf` we should sync some settings back.
> Simplify `emqx_conf` and `gen_rpc` cooperation

- apps/emqx/src/emqx_maybe.erl
- apps/emqx_ft/src/emqx_ft.erl
- apps/emqx_ft/src/emqx_ft_assembler.erl
- apps/emqx_ft/src/emqx_ft_assembler_sup.erl
- apps/emqx_ft/src/emqx_ft_assembly.erl
- apps/emqx_ft/src/emqx_ft_storage.erl
- apps/emqx_ft/src/emqx_ft_storage_fs.erl
- apps/emqx_ft/test/emqx_ft_SUITE.erl
- apps/emqx_ft/test/emqx_ft_api_SUITE.erl
- apps/emqx_ft/test/emqx_ft_assembler_SUITE.erl
- apps/emqx_ft/test/emqx_ft_storage_fs_SUITE.erl
- apps/emqx_ft/test/emqx_ft_test_helpers.erl
Otherwise there are situations when it's not entirely clear if a transfer is really ready to be assembled. Since the `size` field in a filemeta is not required (and rightly so), we need client to tell us the final transfer size at the end of the process.
Also synthesize a testcase to show why it's needed.
Also worth noting that right now `fin` packets require final size, even if a client already told us the size through filemeta. The latter is regarded as serving informational purposes only (which means that, for example, it might differ from the final size, or some tranfer progress might show >100% somewhere because of that).
---
[EMQX-8916](https://emqx.atlassian.net/browse/EMQX-8916)
> fix(ft): require final size in `fin` packet

- deploy/charts/emqx/templates/pdb.yaml
- deploy/charts/emqx/values.yaml
Now it is possible to define the pod disruption budget.
Closes: #8222
> feat: Add pod disruption budget to helm chart

- apps/emqx_management/src/emqx_mgmt_api_trace.erl
- apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
- changes/ce/fix-10009.en.md
- changes/ce/fix-10009.zh.md
Fixes [EMQX-7994](https://emqx.atlassian.net/browse/EMQX-7994)
> get trace name log bytes xxx does not do input validation

- apps/emqx_gateway/src/emqx_gateway_api_clients.erl
Fixes [EMQX-7820](https://emqx.atlassian.net/browse/EMQX-7820)
- ~[ ] Change log has been added to `changes/<version>/(feat|fix)-<PR-id>.en.md` and `.zh.md` files~
> fix: schema for `/gateways/:name/clients` was missing top-level structure

- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_dashboard/test/emqx_swagger_requestBody_SUITE.erl
- apps/emqx_modules/test/emqx_telemetry_SUITE.erl
- changes/ce/fix-9997.en.md
- changes/ce/fix-9997.zh.md
Swagger says `deprecated` metadata field should always be boolean https://swagger.io/specification/
But in `hocon` we also support values like`{since, "4.3.0"}`, which result in `"deprecated": "since(\"4.3.0\")"` metadata.
This incompatibility breaks some API client generators.
> fix(dashboard): fix swagger spec generation

- apps/emqx_ctl/src/emqx_ctl.erl
- bin/emqx
- changes/ce/fix-10015.en.md
- changes/ce/fix-10015.zh.md
A follow up improvement for [EMQX-8936](https://emqx.atlassian.net/browse/EMQX-8936)
When running more than one node in the host, one will need to set `EMQX_NODE__NAME` and `EMQX_NODE__COOKIE` to run the non-boot commands.
If the provided node name or cookie is obviously wrong, we should print out meaningful logs instead of just "Node xxx not responding to pings"
> 0220 fail fast if cookie is obviously wrong

- apps/emqx/src/emqx_maybe.erl
- apps/emqx/src/emqx_wdgraph.erl
- apps/emqx/test/emqx_proper_types.erl
- apps/emqx/test/emqx_wdgraph_tests.erl
- apps/emqx_ft/src/emqx_ft_assembly.erl
- apps/emqx_ft/test/props/prop_emqx_ft_assembly.erl
The current algorithm's complexity proved to be unacceptable with sufficiently large inputs (e.g. GiBs-worth files split into 100 KiB sized segments for example). Express and reimplement it as the shortest path problem on graph where nodes are offsets and edges are Erlang nodes' segments.
---
[EMQX-8916](https://emqx.atlassian.net/browse/EMQX-8916)
> perf(ft-asm): express coverage through shortest path on graph

- bin/emqx
- changes/ce/fix-10043.en.md
- changes/ce/fix-10043.zh.md
- scripts/test/start-two-nodes-in-docker.sh
Fixes [EMQX-9046](https://emqx.atlassian.net/browse/EMQX-9046)
This PR fixes two issues, both introduced in v5.0.18
1. 
```
+ docker exec node2.emqx.io emqx ctl status
/usr/local/bin/emqx: line 592: SSL_DIST_OPTFILE: unbound variable
```
2.
when cookie is only set from environment variable, the boot command is unable to start the node
and complain that the set cookie is different from configured (the default).
> 0228 fix ssl dist optfile

- apps/emqx_bridge/src/emqx_bridge_api.erl
Fixes: https://emqx.atlassian.net/browse/EMQX-9031
Examples:
**"test"** bridge exists, so bridge_prob with a hidden password is going to work:
```
curl -s http://localhost:18083/api/v5/bridges_probe -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc3MDAyNTIyNDksImlzcyI6IkVNUVgifQ.sN-8TBTLisuQvllmbSk2qei6jnAhWkgmg0BOwlauVIE'  -H 'Content-Type: application/json'  --data-binary '{"name":"test","type":"pgsql","database":"emqx","enable":true,"password":"******","pool_size":8,"resource_opts":{"auto_restart_interval":"60s","batch_size":1,"batch_time":"20ms","health_check_interval":"15s","max_queue_bytes":"100MB","query_mode":"sync","request_timeout":"15s","start_after_created":"true","start_timeout":"5s","worker_pool_size":16},"server":"127.0.0.1","sql":"insert into …
```
> fix: Handle obfuscated fields in bridges_probe API

- lib-ce/emqx_telemetry/src/emqx_telemetry.app.src
- lib-ce/emqx_telemetry/src/emqx_telemetry.appup.src
- lib-ce/emqx_telemetry/src/emqx_telemetry.erl
- lib-ce/emqx_telemetry/test/emqx_telemetry_SUITE.erl
The CI failed if telemetry spent too much time on sending HTTP request. So I changed the timeout of the gen_server:call to infinity.
> fix: change timeout of gen_server:calls for emqx_telemetry to infinity

- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
Sometimes, this test fails because the metrics are still in the inflight phase.
> test: fix flaky mqtt bridge test

- apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
- apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
- apps/emqx_bridge/test/emqx_bridge_compatible_config_tests.erl
- apps/emqx_resource/i18n/emqx_resource_schema_i18n.conf
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_gcp_pubsub.conf
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.app.src
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_gcp_pubsub.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_gcp_pubsub_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_redis_SUITE.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_gcp_pubsub.erl
Related ticket: https://emqx.atlassian.net/browse/EMQX-9029
To avoid message loss due to misconfigurations, we adjust `batch_time`
based on `request_timeout`.  If `batch_time` > `request_timeout`, all
requests will timeout before being sent if the message rate is low.
Even worse if `pool_size` is high.  We cap `batch_time` at
`request_timeout div 2` as a rule of thumb.
Also:
- Small refactoring: we now avoid starting timers when `batch_time` = 0.  If the user sets `batch_time = 0`, it's analogous to `TCP_NODELAY`: we don't perform (time-based) batching.  Batching might still occur if the concurrent message rate is high enough.
- Removed potentially confusing `request_timeout` from the root of the GCP PubSub bridge (affects the frontend @ysfscream @Kinplemelon )
- I tried to do it here: …
> fix(buffer_worker): add batch time automatic adjustment 

- apps/emqx/src/emqx_schema.erl
- changes/ce/fix-10058.en.md
- changes/ce/fix-10058.zh.md
The idea was to remove unsupp QUIC TLS options to avoid confusion.
But removing fields can cause schema backward compatible issues, so we decide to mark them deprecated. 
Manually checked that the Swagger spec file has these fields deprecated.
> fix: deprecate unsupp quic TLS options

- apps/emqx/src/emqx_cm.erl
- apps/emqx/src/emqx_session.erl
- apps/emqx/test/emqx_channel_SUITE.erl
- apps/emqx/test/emqx_connection_SUITE.erl
- apps/emqx/test/emqx_session_SUITE.erl
- apps/emqx/test/emqx_ws_connection_SUITE.erl
- apps/emqx_gateway/src/mqttsn/emqx_sn_channel.erl
- changes/ce/fix-10055.en.md
- changes/ce/fix-10055.zh.md
FIx: https://emqx.atlassian.net/browse/EMQX-9057 
update max_awaiting_rel in session.
close https://github.com/emqx/emqx/issues/10025
> fix: update max_awaiting_rel in session

- apps/emqx/i18n/emqx_schema_i18n.conf
- changes/ce/fix-10079.en.md
- changes/ce/fix-10079.zh.md
Fix: EMQX-9007
I just fetched the description from old commits. 
~~Added tests for the changes~~
~~Changed lines covered in coverage report~~
~~If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up~~
~~Schema changes are backward compatible~~
> fix: i18n desc of broker_shared_subscription_strategy

- changes/ce/fix-10086.en.md
- changes/ce/fix-10086.zh.md
- mix.exs
- rebar.config
Fixes [EMQX-8974](https://emqx.atlassian.net/browse/EMQX-8974)
> chore: upgrade to ehttpc 0.4.7

- apps/emqx_conf/src/emqx_conf.erl
- build
- mix.exs
- rebar.config.erl
Fixes [EMQX-8999](https://emqx.atlassian.net/browse/EMQX-8999)
Saying goodbye to the possibility of building self-contained releases which include the configuration documents.
We'll continue to generate the schema artifacts,
but not as a part of the `www/static` dir  of the web server (dashboard).
Find the new schema dump in `_build/docgen/{emqx,emqx-enterprise}`
this PR only removes some unused artifacts, which impacts no user experience.
- [~] If there should be document …
> 0308 stop releasing schema.json in rel package

- apps/emqx_machine/src/emqx_machine_boot.erl
- apps/emqx_machine/src/emqx_machine_terminator.erl
- changes/ce/fix-10132.en.md
- changes/ce/fix-10132.zh.md
Fix: `systemctl stop emqx ` don't stop port apps.
```
2023-03-14T02:37:36.935887+00:00 [error] Generic server disksup terminating. Reason: {port_died,normal}. Last message: {'EXIT',#Port<0.7>,normal}. State: [{data,[{"OS",{unix,linux}},{"Timeout",1800000},{"Threshold",80},{"DiskData",[{"/dev",470372,0},{"/run",100004,1},{"/",20464340,24},{"/dev/shm",500000,0},{"/run/lock",5120,0},{"/sys/fs/cgroup",500000,0},{"/run/user/1000",100000,0}]}]}].
2023-03-14T02:37:36.936066+00:00 [error] Generic server memsup terminating. Reason: {port_died,normal}. Last message: {'EXIT',<0.1816.0>,{port_died,normal}}. State: [{data,[{"Timeout",60000}]},{items,{"Memory Usage",[{"Allocated",903290880},{"Total",1024004096}]}},{items,{"Worst Memory User",[{"Pid",<0.1731.0>},{"Memory",5091856}]}}]. …
```
> fix: stop port apps when emqx_machine_terminator shutdown

- apps/emqx/rebar.config
- mix.exs
- rebar.config
hocon 0.37.0 introduced schema field aliases
this change does not impact anything until we start using aliases
> chore: upgrade to hocon 0.37.0

- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_ft/i18n/emqx_ft_schema_i18n.conf
- apps/emqx_ft/include/emqx_ft_storage_fs.hrl
- apps/emqx_ft/src/emqx_ft_assembler.erl
- apps/emqx_ft/src/emqx_ft_conf.erl
- apps/emqx_ft/src/emqx_ft_schema.erl
- apps/emqx_ft/src/emqx_ft_storage.erl
- apps/emqx_ft/src/emqx_ft_storage_fs.erl
- apps/emqx_ft/src/emqx_ft_storage_fs_gc.erl
- apps/emqx_ft/src/emqx_ft_sup.erl
- apps/emqx_ft/test/emqx_ft_SUITE.erl
- apps/emqx_ft/test/emqx_ft_api_SUITE.erl
- apps/emqx_ft/test/emqx_ft_assembler_SUITE.erl
- apps/emqx_ft/test/emqx_ft_content_gen.erl
- apps/emqx_ft/test/emqx_ft_storage_fs_SUITE.erl
- apps/emqx_ft/test/emqx_ft_storage_fs_gc_SUITE.erl
- apps/emqx_ft/test/emqx_ft_test_helpers.erl
Implementation is straightforward, and is probably prone to some race conditions (e.g. collecting an incomplete transfer while there's another incoming segment). These conditions demand thorough testing.
Rough TODOs.
---
[EMQX-8271](https://emqx.atlassian.net/browse/EMQX-8271)
> feat(ft): add GC logic and process for the FS storage backend

- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_plugins/src/emqx_plugins_sup.erl
- changes/ce/fix-10130.en.md
- changes/ce/fix-10130.zh.md
Fix: https://emqx.atlassian.net/browse/EMQX-9154
https://github.com/emqx/hocon/pull/234
> fix: replace env value string to binary

- bin/emqx
- changes/ce/fix-10144.en.md
> fix: ensure cookie for emqx ctl

- apps/emqx/priv/bpapi.versions
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/proto/emqx_bridge_proto_v3.erl
- apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
Also make sure to reply `emqx_resource:get_instance/1` from cache.
The resource manager may be busy at times, so this change ensures that getting resource instance state will not block. Currently, no users of `emqx_resource:get_instance/1` do seem to be relying on resource state being "as-actual-as-possible" guarantee it was providing.
---
[EMQX-9136](https://emqx.atlassian.net/browse/EMQX-9136)
> perf(bridge-api): ask nodes' bridge listings in parallel

- apps/emqx_connector/src/emqx_connector_mongo.erl
This complements PR https://github.com/emqx/emqx/pull/10124. The default values for duration_ms() fields needs to be formatted as a binary string with unit to show up correctly in the dashboard UI.
No changelog entry needed since this is provided with https://github.com/emqx/emqx/pull/10124
> fix: schema default value so that it shows up correctly in UI

- apps/emqx/src/emqx_limiter/src/emqx_limiter.app.src
- apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl
- apps/emqx/src/emqx_schema.erl
Fixes [EMQX-9214](https://emqx.atlassian.net/browse/EMQX-9214)
Newly created listeners have no limiter restrictions
1. Create a new listener(demo) on the dashboard.
2. Check the listener's limiter connection status as 
```
6> emqx_config:get([listeners,tcp,demo,limiter,connection]).
#{capacity => 1099511627776,initial => 0,rate => infinity}
```
3. The default limiter status is
```
7> emqx_config:get([listeners,tcp,default,limiter,connection]).
#{capacity => 1000,initial => 0,rate => 100.0}
```
4. Restart EMQX, the new listener with the same limiter as the default one.
```
1> emqx_config:get([listeners,tcp,default,limiter,connection]).
#{capacity => 1000,initial => 0,rate => 100.0}
2> emqx_config:get([listeners,tcp,demo,limiter,connection]).
#{capacity => 1000,initial => 0,rate => 100.0} …
```
> fix: newly created listeners have no limiter restrictions

- changes/ee/feat-10165.en.md
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_influxdb.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_tests.erl
Closes: EMQX-7834
Fixes https://emqx.atlassian.net/browse/EMQX-7834
> feat: handle escaped characters in InfluxDB data bridge write_syntax

- Makefile
- apps/emqx/rebar.config
- apps/emqx/rebar.config.script
- build
- mix.exs
Fixes [EMQX-9223](https://emqx.atlassian.net/browse/EMQX-9223)
The targeted issues were discovered when I tried to experiment with building some Elixir things that used `emqx` as a dependency.
* Make `mix` not fetch (and build) quicer dependencies if it is not enabled.
* Make the project "buildable" with `mix` only. After some updates emqx gradually lost its ability to be built as a "mix project". E.g. we can't simply add it as a mix dependancy for code reuse, like
```
{:emqx_mix, github: "emqx/emqx", env: :emqx, runtime: false}
```
We have to rely only on shell scripts that build the whole distribution artifact to build the code:
```
{:emqx_mix, github: "emqx/emqx", env: :emqx, compile: "make emqx-elixir", runtime: false}
```
This involves many unnecessary steps.
* (chore): try to avoid …
> chore(mix): fix mix builds

- lib-ce/emqx_dashboard/src/emqx_dashboard.app.src
- rebar.config
- src/emqx.app.src
Use a fork of base16 dependency which has no non-permissive license.
The original repo had test code in non-permissive license which caused some unnecessary concerns.
Absolutely no code change at all.
> chore: use zmstone/base16 fork

- apps/emqx/rebar.config.script
- apps/emqx/test/emqx_common_test_helpers.erl
- mix.exs
- rebar.config.erl
Fixes [EMQX-9270](https://emqx.atlassian.net/browse/EMQX-9270)
- Support fetching binary for macOS M1
- Fix includes of testlib for passing CI of emqtt lib
> chore(build): Support fetching binary for macOS M1 [quicer 0.0.114]

- .github/workflows/geen_master.yaml
- scripts/rerun-failed-checks.py
example run:
https://github.com/emqx/emqx/actions/runs/4477786641/jobs/7869749635
Just to be clear, this is not trying to hide the issue, next PR would be to find all the flaky TCs from history reruns on master branch.
~If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)~
~Change log has been added to `changes/` dir for user-facing artifacts update~
> ci: add job to keep master green

- apps/emqx_bridge/src/emqx_bridge_api.erl
- changes/ce/fix-10190.en.md
Bridge lists were erroneously flattened in cad6492c. This causes bridge listing fail in emqx clusters consisting of more than 1 node.
Fixes [EMQX-9269](https://emqx.atlassian.net/browse/EMQX-9269)
> fix(bridge-api): unflatten nodes' bridge lists back

- apps/emqx_resource/src/emqx_resource_manager.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_dynamo_SUITE.erl
Those tests in the `flaky` test are really flaky and require lots of CI retries.
Apparently, the flakiness comes from race conditions from restarting bridges with the same name too fast between test cases.  Previously, all test cases were sharing the same bridge name (the module name).
Fixes https://emqx.atlassian.net/browse/EMQX-9287
> test(dynamo): attempt to fix flaky dynamo tests

- apps/emqx/src/emqx_channel.erl
- apps/emqx_authz/test/emqx_authz_SUITE.erl
- changes/ce/fix-10209.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-9288
Related issue:
https://github.com/emqx/emqx/issues/10192#issuecomment-1478809900
> fix(last_will_testament): don't publish LWT if client is banned when kicked out

- .ci/docker-compose-file/docker-compose-kafka.yaml
- .ci/docker-compose-file/docker-compose.yaml
- .github/workflows/build_and_push_docker_images.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/check_deps_integrity.yaml
- .github/workflows/code_style_check.yaml
- .github/workflows/elixir_apps_check.yaml
- .github/workflows/elixir_deps_check.yaml
- .github/workflows/elixir_release.yml
- .github/workflows/release.yaml
- .github/workflows/run_emqx_app_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_relup_tests.yaml
- .github/workflows/run_test_cases.yaml
- .tool-versions
- apps/emqx/rebar.config
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- changes/ce/feat-10210.en.md
- deploy/docker/Dockerfile
- mix.exs
- rebar.config
- scripts/relup-test/run-relup-lux.sh
- scripts/relup-test/start-relup-test-cluster.sh
Fixes https://emqx.atlassian.net/browse/EMQX-9101
> EMQX-9101 mnesia unregister hook

- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_exhook/i18n/emqx_exhook_api_i18n.conf
- apps/emqx_management/i18n/emqx_mgmt_api_publish_i18n.conf
- apps/emqx_management/i18n/emqx_mgmt_api_status_i18n.conf
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/src/emqx_mgmt_api_publish.erl
- changes/ce/fix-10195.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-8982
- [-] Added tests for the changes
- [-] Changed lines covered in coverage report
- [-] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [-] Change log has been added to `changes/` dir for user-facing artifacts update
> fix: add summary to schemas where description has html

- rel/emqx_conf.template.en.md
- rel/emqx_conf.template.zh.md
The config overriding order is subject to a refactoring.
Here is what going to happen somewhere in v5.0.x or v5.1.0
* There will be a `cluster.hocon` added to data dir, and it will become the bottom of the overlaying order.
* For backward compatibility reasons `cluster-override.conf` will stay (if it exists) but will not be documented.
> docs: delete local-override.conf from config template

- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl
- changes/ce/fix-10225.en.md
Allow installing a plugin if its name matches the beginning of another (already installed) plugin name. 
For example: if plugin "emqx_plugin_template_a" is installed, it must not block installing plugin "emqx_plugin_template".
Fixes #10213, EMQX-9290
> fix(emqx_management): resolve plugin name clashes

- apps/emqx/rebar.config
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_ocsp_cache_SUITE.erl
- mix.exs
- rebar.config
We're going to release it in a later version.  So, for now, we'll just hide it.
- [~] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [~] Change log has been added to `changes/` dir for user-facing …
> chore(ocsp): hide ocsp from schema for now

- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- changes/ce/feat-10206.en.md
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_dynamo_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_gcp_pubsub_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
- lib-ee/emqx_ee_connector/test/emqx_ee_connector_influxdb_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-9129
Currently, if an user configures a bridge with query mode sync, then all calls to the underlying driver/connector ("inner calls") will always be synchronous, regardless of its support for async calls.
Since buffer workers always support async queries ("outer calls"), we should decouple those two call modes (inner and outer), and avoid exposing the inner call configuration to user to avoid complexity.
There are two situations when we want to force synchronous calls to the underlying connector even if it supports async:
1) When using `simple_sync_query`, since we are bypassing the buffer workers;
2) When retrying the inflight window, to avoid overwhelming the driver.
Please convert it to a draft if any of the following conditions are not …
> feat(buffer_worker): decouple query mode from underlying connector call mode

- apps/emqx_plugin_libs/src/emqx_plugin_libs_pool.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_dynamo.erl
let it be same with `ecpool:pick_and_do/3` for checkfun use format as {M,F,A}
~- [ ] Changed lines covered in coverage report~
~- [ ] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` and `.zh.md` files~
~- [ ] For internal contributor: there is a jira ticket to track this change~
~- [ ] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up~
~- [ ] Schema changes are backward compatible~
~- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)~
~- [ ] Change log has been added to …
> fix: for connection used ecpool, let worker do health check fun

- apps/emqx/include/emqx_api_lib.hrl
- apps/emqx/src/emqx_api_lib.erl
- apps/emqx/test/emqx_api_lib_SUITE.erl
- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- apps/emqx_management/src/emqx_mgmt_api_nodes.erl
- apps/emqx_management/test/emqx_mgmt_api_nodes_SUITE.erl
- changes/ce/fix-10237.en.md
Fixes [EMQX-9138](https://emqx.atlassian.net/browse/EMQX-9138)
> fix: create consistent interface 'with_node' for API access

- apps/emqx/src/emqx_channel.erl
- apps/emqx/test/emqx_client_SUITE.erl
Port https://github.com/emqx/emqx/pull/10221 from e4.4
> chore: remove peercert from the state of connection processes

- deploy/docker/Dockerfile
- lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_kafka.conf
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.app.src
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_kafka.erl
- lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_consumer.erl
- lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_consumer_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_kafka_tests.erl
Fixes https://emqx.atlassian.net/browse/EMQX-9354
To make the configuration more intuitive and avoid exposing more parameters to the user, we should:
1. Remove reset_by_subscriber as an enum constructor for offset_reset_policy, as that might make the consumer hang indefinitely without manual action.
2. Set the begin_offset brod_consumer parameter to earliest or latest depending on the value of offset_reset_policy, as that’s probably the user’s intention. 
- [~] If there should be document changes, a PR to …
> feat(kafka_consumer): tie `offset_reset_policy` and `begin_offset` together (rv5.0)

- apps/emqx_bridge/include/emqx_bridge_resource.hrl
- apps/emqx_bridge/src/emqx_bridge_resource.erl
- apps/emqx_bridge/test/emqx_bridge_resource_tests.erl
- apps/emqx_rule_engine/src/emqx_rule_engine.erl
- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- changes/ce/fix-10251.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-9325
Currently, ingress bridges referenced in the `FROM` clause of rules are not being accounted as dependencies.
When we try to delete an ingress bridge that's referenced in a rule like `select * from "$bridges/mqtt:ingress"`, that bridge does not trigger an UI warning about dependent actions.
> fix(rule_engine): count referenced bridges in `from` clauses as dependencies (rv5.0)

- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_cmd.erl
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_session.erl
- apps/emqx_gateway/src/lwm2m/emqx_lwm2m_xml_object_db.erl
- apps/emqx_gateway/src/lwm2m/include/emqx_lwm2m.hrl
- apps/emqx_gateway/test/emqx_lwm2m_SUITE.erl
- changes/ce/fix-10257.en.md
- changes/ce/fix-10257.zh.md
Fixes https://emqx.atlassian.net/browse/EMQX-9362
- ~If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up~
> Fixed the issue where `auto_observe` was not working in LwM2M Gateway

- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/schema/emqx_bridge_compatible_config.erl
- apps/emqx_bridge/test/emqx_bridge_webhook_SUITE.erl
- apps/emqx_resource/i18n/emqx_resource_schema_i18n.conf
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/src/schema/emqx_resource_schema.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_clickhouse.erl
- scripts/test/influx/influx-bridge.conf
This PR makes sure the inflight window setting is present for the clickhouse bridge. It also changes emqx_resource_schema that previously removed the inflight window setting from resources with query mode `always_sync`. We don't need to do that because all bridges that uses the buffer worker queue will get async call handling even if the bridge don't support the async callback.
@thalesmg: maybe this should be merged after async support for bridges with `always_sync` has been added to the `emqx_resource_buffer_worker` module?
> fix: add inflight window setting to the clickhouse bridge

- bin/emqx
- changes/ce/feat-10263.en.md
Currently, Elixir expressions are evaluated on an EMQX node using the 'eval' command, which works for both Erlang and Elixir expressions. This commit adds the new command 'eval-ex' exclusively for evaluating Elixir expressions on Elixir nodes, similar to 'eval-erl' for Erlang.
Fixes https://emqx.atlassian.net/browse/EMQX-8947
- [~] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual …
> feat: add new command for Elixir expression evaluation

- .ci/docker-compose-file/docker-compose.yaml
- lib-ee/emqx_ee_connector/src/emqx_ee_connector.app.src
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_tdengine.erl
Fixes https://emqx.atlassian.net/browse/EMQX-9395
```
2023-03-29T09:59:02.655495+00:00 [warning] msg: start_resource_failed, mfa: emqx_resource_manager:start_resource/2, line: 524, id: <<"bridge:tdengine:jimmoen-test-trigger">>, reason: {error,function_clause,[{emqx_ee_connector_tdengine,on_start,[<<"bridge:tdengine:jimmoen-test-trigger:1076">>,#{database => <<"db">>,enable => true,pool_size => 8,resource_opts => #{auto_restart_interval => 60000,batch_size => 1,batch_time => 0,health_check_interval => 15000,max_queue_bytes => 104857600,query_mode => sync,request_timeout => 15000,start_after_created => true,start_timeout => 5000,worker_pool_size => 16},server => "127.0.0.1",sql => <<"insert into mqtt.t_mqtt_msg(ts, msgid, mqtt_topic, qos, payload, arrived) values (${ts}, ${id}, ${topic}, …
```
> fix(tdengine): make password a required field (rv5.0)

- apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
- apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
Before this fix, if there were any subscriptions made with `emqx:subscribe`, they would break the list subscriptions API as they don't have a clientid.
> fix: handle subscription list api when there are `emqx:subscribe` internal subscriptions

- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/emqx_connector_redis.erl
Since there's a default value, this field shouldn't be marked as required.
This makes the frontend display it as required:
> fix(redis): remove `required` meta from schema

- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
```
2023-03-30T13:15:30.8273178Z "check stage" failed: error
2023-03-30T13:15:30.8273446Z {assert,[{module,emqx_ee_bridge_influxdb_SUITE},
2023-03-30T13:15:30.8273704Z          {line,995},
2023-03-30T13:15:30.8273956Z          {comment,#{got => {error,{recoverable_error,noproc}}}},
2023-03-30T13:15:30.8274426Z          {expression,"{ error , { error , { closed , \"The connection was lost.\" } } } =:= Result orelse { error , { error , closed } } =:= Result orelse { error , { recoverable_error , econnrefused } } =:= Result"},
2023-03-30T13:15:30.8274917Z          {expected,true},
2023-03-30T13:15:30.8275134Z          {value,false}]}
2023-03-30T13:15:30.8275507Z Stacktrace: [{emqx_ee_bridge_influxdb_SUITE,'-t_write_failure/1-fun-4-',2,
2023-03-30T13:15:30.8275791Z                  [{file, …
```
> test: fix flaky influxdb test

- lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_clickhouse.conf
- lib-ee/emqx_ee_connector/i18n/emqx_ee_connector_clickhouse.conf
As the title says. This is just a small documentation change so I don't think a change log entry is needed.
> docs: make clickhouse config label for Server URL more concise

- .ci/docker-compose-file/scripts/run-emqx.sh
- bin/emqx
- bin/node_dump
- changes/ce/fix-10297.en.md
Keeps "eval" command evaluating only Erlang expressions, even on Elixir node.
Fixes https://emqx.atlassian.net/browse/EMQX-8947
Make sure to target release-50 branch if this PR is intended to fix the issues for the release candidate.
> fix: keep eval command backward compatible with v4

- apps/emqx_resource/src/emqx_resource.app.src
- apps/emqx_resource/src/emqx_resource.erl
- lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_consumer.erl
- lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl
- lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_producer_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-9392
The returned information does not allow to diagnose the issue (i.e.: a connection issue due to the wrong host and port, the wrong password failing authn).  However, such information is printed to the logs.
This changes the returned error to the API so that the user is hinted at looking at the logs for further investigation of the error.
When probing:
> fix: return friendly message when kafka producer and consumer fails to start (rv5.0)

- apps/emqx_management/src/emqx_mgmt_api_plugins.erl
- changes/ce/fix-10300.en.md
- mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-9434
Fixes https://github.com/emqx/emqx-elixir-plugin/issues/23
> fix(plugins): create directory before uploading

- apps/emqx_replay/src/emqx_replay.erl
- apps/emqx_replay/src/emqx_replay_local_store.erl
- apps/emqx_replay/src/emqx_replay_message_storage.erl
- apps/emqx_replay/test/emqx_replay_local_store_SUITE.erl
- apps/emqx_replay/test/props/emqx_replay_message_storage_shim.erl
- apps/emqx_replay/test/props/prop_replay_message_storage.erl
So that we could guarantee replay consistency / availability under the assumption that nodes may be restarted or even lost occasionally.
---
[EMQX-8744](https://emqx.atlassian.net/browse/EMQX-8744)
> feat(replay): allow to preserve / restore iterators in the db

- .github/workflows/build_and_push_docker_images.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/check_deps_integrity.yaml
- .github/workflows/code_style_check.yaml
- .github/workflows/elixir_apps_check.yaml
- .github/workflows/elixir_deps_check.yaml
- .github/workflows/elixir_release.yml
- .github/workflows/run_emqx_app_tests.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_relup_tests.yaml
- .github/workflows/run_test_cases.yaml
Fixing https://github.com/emqx/emqx/actions/runs/4723753605/jobs/8380181371
```
===> Application needed for release not found: odbc
make: *** [Makefile:209: emqx-enterprise-tgz] Error 1
Error: Process completed with exit code 2.
```
> ci: bump emqx-builder to 5.0-34 to fix el9 build

- apps/emqx/src/emqx_schema.erl
- apps/emqx_authz/src/emqx_authz_schema.erl
- apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_exhook/src/emqx_exhook_schema.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
- changes/ce/feat-10391.en.md
- rel/emqx_conf.template.en.md
- rel/emqx_conf.template.zh.md
Partially reverts: https://github.com/emqx/emqx/pull/10391
and ports https://github.com/emqx/emqx/pull/10426 over to release-50
A few schema changes from importance level high to low were too aggressive.
This PR brings back `exhook`, `rule_engine`, `bridges`, `authentication` and `authorization.sources` back to light.
> 0418 cherry pick fixes for e503

- .gitignore
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_sqlserver.erl
Fixes https://emqx.atlassian.net/browse/EMQX-9724
For sqlserver, support only sync mode at connector level.
Prior to this change, the connector was making use of the ecpool's `handover_async` feature which does not return the agent pid for bridge buffer worker to monitor.
Without a monitor, if the agent (client) process crashed while some requests are inflight, the requests are doomed to expire without any chance to get retried.
- [~] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` files
- [~] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to …
> 0426 sqlserver no async connector

- apps/emqx/src/emqx_maybe.erl
- apps/emqx_ft/src/emqx_ft.erl
- apps/emqx_ft/src/emqx_ft_app.erl
- apps/emqx_ft/src/emqx_ft_assembler.erl
- apps/emqx_ft/src/emqx_ft_conf.erl
- apps/emqx_ft/src/emqx_ft_schema.erl
- apps/emqx_ft/src/emqx_ft_storage.erl
- apps/emqx_ft/src/emqx_ft_storage_exporter.erl
- apps/emqx_ft/src/emqx_ft_storage_fs.erl
- apps/emqx_ft/src/emqx_ft_storage_fs_gc.erl
- apps/emqx_ft/src/emqx_ft_sup.erl
- apps/emqx_ft/test/emqx_ft_SUITE.erl
- apps/emqx_ft/test/emqx_ft_api_SUITE.erl
- apps/emqx_ft/test/emqx_ft_assembler_SUITE.erl
- apps/emqx_ft/test/emqx_ft_conf_SUITE.erl
- apps/emqx_ft/test/emqx_ft_storage_fs_SUITE.erl
- apps/emqx_ft/test/emqx_ft_storage_fs_gc_SUITE.erl
- apps/emqx_ft/test/emqx_ft_test_helpers.erl
- apps/emqx_s3/src/emqx_s3_client.erl
- apps/emqx_s3/src/emqx_s3_schema.erl
- apps/emqx_s3/test/emqx_s3_schema_SUITE.erl
- rel/i18n/emqx_ft_schema.hocon
Fixes [EMQX-9521](https://emqx.atlassian.net/browse/EMQX-9521).
Ensure that:
* Storage config might be removed.
* Local FS GC process is set up when Local FS storage is configured.
* Local FS GC process gets its timer reset on config updates.
* Storage / exporter gets chosen based on `type` only.
* Exporter config updates propagated as before.
Also employ `emqx_ft_schema:translate/1` instead of duplicating defaults where applicable.
> feat(ft): properly propagate config updates

- build
- rebar.config
- rebar.config.erl
prior to this change, 'make run' has to wait for the release tar ball to be created.
now it just builds the release and run from the `rel` dir.
relup helper plugin isn't quite ready to work with the rebar3 `release` command yet, so it's commented out for now.
> build: imporove speed to local run

- Makefile
- bin/emqx
- build
- dev
now you can run
`./dev ` to start EMQX dev node
or
`./dev -p ee` to start enterprise edition
it boots the node from app compilation, but not release dir.
Future work: add live-reload.
> 0430 add dev run

- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_connector.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl
- apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_impl_producer.erl
- apps/emqx_connector/src/emqx_connector.app.src
- apps/emqx_connector/src/emqx_connector_mqtt.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker_sup.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/src/emqx_resource_manager_sup.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
- lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector.app.src
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_rocketmq.erl
- lib-ee/emqx_ee_connector/src/emqx_ee_connector_sqlserver.erl
Fixes [EMQX-9257](https://emqx.atlassian.net/browse/EMQX-9257)
Before this change, a separate `manager_id` / `instance_id` was used as a resource manager id, which made connector interface somewhat inconsistent: part of function calls to connector implementation used instance id as first argument while the rest used resource id itself.
> feat(resource): stop adding uniqueness to manager ids

- scripts/git-hook-pre-commit.sh
I am working with a emqx repo locally with many work trees from different branches (5.0, 4.4).
The commit hook is shared by all the work trees. 
It is inconvenient to force local env to have mix format check.
This PR skip mix format checks if the mix is not present.
> chore(git-hook): don't fail commit hook when no mix

- .github/workflows/build_packages.yaml
- .github/workflows/build_packages_cron.yaml
- scripts/buildx.sh
source.zip was need in v4 enterprise because the rebar3 deps
fetch had to be done in the github runner host, but not inside
the runner docker containers.
now that all dependencies are opensource, there is no need for
this step any more.
tested here: https://github.com/emqx/emqx/actions/runs/4897488610
latest commit verified here: https://github.com/emqx/emqx/actions/runs/4897871592
> 0505 ci no need for source zip

- apps/emqx_ft/src/emqx_ft_assembler.erl
- apps/emqx_ft/test/emqx_ft_SUITE.erl
Fixes [EMQX-9573](https://emqx.atlassian.net/browse/EMQX-9573)
This PR fixes the testcase for the `emqx_ft` application, and adds a new clause to handle repeated `kickoff` events in the `emqx_ft_assembler` module.
> fix(ft): anticipate repeated `kickoff`s + fix testcase

- apps/emqx_rule_engine/include/rule_engine.hrl
- apps/emqx_rule_engine/src/emqx_rule_runtime.erl
- apps/emqx_rule_engine/src/emqx_rule_sqlparser.erl
- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_demo.erl
Often there are community users wish for functions that are hard to get prioritized.
This 'eval' func should allow them to hook in their functions in a patch module.
So far, there is no plan to widely announce this feature,
we'll try to see if it is helpful before documenting it.
> Add an experimental feature: support external rule-engine SQL functions

- apps/emqx/src/emqx_schema.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_conf_schema_tests.erl
- rel/i18n/emqx_schema.hocon
- rel/i18n/zh/emqx_schema.hocon
this pr reverts part of https://github.com/emqx/emqx/pull/10607
file path should allow space, ':' and maybe even unicode. the validator certainly will cause complains.
> chore: allow special chars in log dir

- changes/v4.4.19-en.md
- changes/v4.4.19-zh.md
- priv/emqx.schema
- src/emqx_tls_lib.erl
- test/emqx_listener_tls_verify_partial_chain_SUITE.erl
followup review comments in #10673 
Since we now support cacert refresh and makes the logic a little complicated, 
detailed description of the feature is moved to emqx-docs PR:  https://github.com/emqx/emqx-docs/pull/1893
> feat(tls-partial-chains): update schema

- apps/emqx/rebar.config
- changes/ce/fix-10809.en.md
- mix.exs
- rebar.config
Fixes EMQX-9807
Fix 
```
** ERROR ** Mnesia post_commit hook failed: error:badarg, Stacktrace:[{erlang,send,['$mria_meta_shard',
```
errors happening during node restart due to cluster join. 
> chore(ekka): Bump version to 0.15.2

- apps/emqx_conf/src/emqx_conf_app.erl
Fixes EMQX-10384
Issue was introduced in https://github.com/emqx/emqx/pull/10902
versions earlier than e5.0.3 does not have `release` field in the rpc return value.
- [~] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` files
> fix(emqx_conf_app): fix release version detect during cluster conf sync

- .github/workflows/run_test_cases.yaml
- Makefile
- scripts/ct/run.sh
- scripts/find-apps.sh
- scripts/find-suites.sh
Split common test run for `apps/emqx` into chunks for better concurrency and smaller retries.
> ci: split apps/emqx common test suites into chunks

- deploy/charts/emqx-enterprise/README.md
- deploy/charts/emqx-enterprise/templates/certificate.yaml
- deploy/charts/emqx-enterprise/values.yaml
- deploy/charts/emqx/README.md
- deploy/charts/emqx/templates/certificate.yaml
- deploy/charts/emqx/values.yaml
template, documentation, default values.yaml for value ssl.Commonname to support vault-issuer
vault-issuer (k8s clusterIssuer) requires CN to be set by default
closes: emqx#11199
> feat: enable setting ssl common name

- scripts/dev-cluster-host.sh
A script to bring up a cluster with configurable number of core and replicant nodes locally from local binaries.
It's a generalization of `./scripts/test/start-two-nodes-in-host.sh`, although without the option to use different boot scripts for each node (not sure if it's needed).
Tested on macOS only so far.
> chore: add scripts/dev-cluster-host.sh

- deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
- deploy/charts/emqx-enterprise/values.yaml
- deploy/charts/emqx/README.md
- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/values.yaml
Fixes none
Add support for field topologySpreadConstraints (https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) on the StatefulSet in the Helm chart. All non-beta fields are included and the labelSelector is overridden.
> feat(helm-chart): add support for topologySpreadConstraints

- deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
- deploy/charts/emqx-enterprise/values.yaml
- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/values.yaml
This change allows to set the `minReadySeconds` for the StatefulSet. This allow to add a gap between the restarts of each pod by upgrade or restart command. 
Our use case is, that some of our mqtt-clients can't handle it well when they are disconnected multiple times in a short amount of time. But this can happen when they are disconnected for the pod restart and are connected to the next pod that will restart next.
Due to this feature is only available for kubernetes <= 1.25, the tag is not added with a default value but insead only added if it is set in the values configuration.
see: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#minimum-ready-seconds
> feat(helm): possibility to add `minReadySeconds` in helm chart for the stateful set

- .github/workflows/upload-helm-charts.yaml
- apps/emqx/src/emqx.app.src
- deploy/charts/emqx/Chart.yaml
- pkg-vsn.sh
- scripts/rel/check-chart-vsn.sh
- scripts/rel/cut.sh
Fixes:
- issue when helm charts are not uploaded if emqx release version contains modifiers like `-build.3`, for example
- `cut.sh` not enforcing strict version match in `emqx_release.hrl` and `Chart.yaml`
> ci: upgrade emqx/push-helm-action to v1.1

- .github/workflows/run_test_cases.yaml
- .github/workflows/static_checks.yaml
Right now check names are auto-generated by github based on all matrix dimensions. This patch overrides this for especially hairy cases in run_test_cases workflow.
Other improvements:
- override check names in static_checks workflow so that we do not have references to OTP or builder version and can use these checks consistently in required checks (otherwise we will have to update required checks each time we bump builder version)
- add a no-op "tests_passed" job for test cases to be used as required check instead of make_cover (it takes ~10 min)
> ci: use more sensible name for checks

- apps/emqx_ctl/src/emqx_ctl.erl
- apps/emqx_ctl/test/emqx_ctl_SUITE.erl
- bin/nodetool
- dev
a follow up fix for https://github.com/emqx/emqx/pull/11599
e.g.
```
2023-09-22T12:06:31.853870+02:00 [info] eval_erl {"result":"ok","node":"emqx@127.0.0.1","msg":"from_cli","duration_ms":3,"cmd":"eval_erl","args":["1+1"]}
```
> fix(audit): make emqx eval command auditable

- bin/nodetool
- scripts/test/emqx-boot.bats
follow up fix for https://github.com/emqx/emqx/pull/11660
only made `dev eval` command working in #11660 missed `emqx eval`
> fix(audit): make 'emqx eval' command auditable

- apps/emqx_dashboard_sso/src/emqx_dashboard_sso_ldap.erl
- apps/emqx_ldap/src/emqx_ldap.erl
- apps/emqx_ldap/src/emqx_ldap_authn_bind.erl
- apps/emqx_ldap/src/emqx_ldap_bind_worker.erl
Avoid using `base_dn` template in LDAP bind query.
Prior to this change, `base_dn` is a template which can be rendered then used in LDAP search argument, and also used to render the DN in bind query.
Such implementation forces the DN to contain values which are template-able in EMQX. e.g. `uid=${username}`
However, often there are requirements to search user in LDAP using other information such as `email` which is not a part of DN.
After this change, the filter condition will need to be specific enough to find only one user, then use the DN from the query result for binding.
> fix(ldap): use the search result as bind target

- .ci/docker-compose-file/docker-compose-ldap.yaml
- .ci/docker-compose-file/openldap/Dockerfile
- .ci/docker-compose-file/openldap/slapd.conf
- apps/emqx/include/emqx_release.hrl
- apps/emqx_dashboard_sso/src/emqx_dashboard_sso_ldap.erl
- apps/emqx_dashboard_sso/test/emqx_dashboard_sso_ldap_SUITE.erl
- apps/emqx_ldap/src/emqx_ldap.erl
- apps/emqx_ldap/src/emqx_ldap_authn.erl
- apps/emqx_ldap/src/emqx_ldap_authn_bind.erl
- apps/emqx_ldap/src/emqx_ldap_authz.erl
- apps/emqx_ldap/src/emqx_ldap_bind_worker.erl
- apps/emqx_ldap/test/data/emqx.io.ldif
- apps/emqx_ldap/test/data/emqx.schema
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- deploy/charts/emqx-enterprise/Chart.yaml
- deploy/charts/emqx/Chart.yaml
fixing issues for ldap sso, targeting `release-53`
* Do not log error level if LDAP sso login credential is invalid
* Do not proceed with authentication when multiple matched entries are found from ldap query
> 0928 fix ldap sso logging level and reject muti-match results

- scripts/ensure-rebar3.sh
This version supports REBAR3_GIT_CACHE_DIR option to make use of local repos as clone reference to reduced the number of clones
> build: upgrade to rebar3 3.19.0-emqx-8

- .ci/docker-compose-file/docker-compose-pgsql-tls.yaml
- .github/workflows/_pr_entrypoint.yaml
- .github/workflows/_push-entrypoint.yaml
- .github/workflows/build_and_push_docker_images.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/build_packages_cron.yaml
- .github/workflows/build_slim_packages.yaml
- .github/workflows/run_jmeter_tests.yaml
- scripts/test/start-two-nodes-in-docker.sh
Both amd64 and arm64 runners have "self-hosted", "ephemeral" and "linux" labels. Not all of our workflows can run seamlessly on both architectures.
> ci: explicitly specify architecture in runner labels

- bin/nodetool
- changes/ce/feat-11787.en.md
Fixes [EMQX-11191](https://emqx.atlassian.net/browse/EMQX-11191)
The `nodetool` command is started in a temp `remsh` node which mostly issues RPC to the running EMQX node.
For example, `ctl`, `ping` and `status`
However, `hocon` and `check_license_key` commands are executed locally (meaning there is no need for a running EMQX node in order to execute the command), so it needs to load all the apps before executing the command.
Prior to this fix, the loading of the emqx apps is unconditional, the apps are loaded even if it's just a plain RPC call.
The fix is to only load apps for `hocon` and `check_license_key`.
> refactor(nodetool): only add libs when necessary

- Makefile
- scripts/find-suites.sh
Most of the cases, the time spent executing `find-apps.sh` and `find-suites.sh` are wasted.
The only benefit is maybe `make` command target auto-completion.
After this PR, we no longer pre-generate all the `-ct` and `-prop` targets, rather generate only the one that is in the specified build target.
> build: refactor Makefile -ct and -prop target generation

- Makefile
These two variables are set when we had elixir and otp version in package file names.
Now they are stale.
> refactor: OTP_VSN and ELIXIR_VSN are no longer needed in Makefile

- .github/workflows/run_test_cases.yaml
- Makefile
- scripts/ct/run.sh
so the ad-hoc `make apps/appname-ct` run can be faster.
cover-compile is quite time-consuming.
> ci: only enable cover-compile by default in CI

- apps/emqx_machine/src/emqx_restricted_shell.erl
- changes/ce/fix-11861.en.md
[EMQX-11300](https://emqx.atlassian.net/browse/EMQX-11300)
While testing, I found out that the shell is quite not usable when a variable in shell is a long list.
For example, if I evaluate `length/1` N times, there would be N warnings.
```
L = lists:seq(1,10000). %% exceeded size limit
lists:foreach(fun(_) -> length(L) end, lists:seq(1,10)). %% warning 10 times
```
Same applies to the heap size limit.
> fix(shell): do not repeat print shell warnings

- apps/emqx/src/emqx_shared_sub.erl
For instance, `emqx_session_mem` will push almost all of the messages that are still in the state to `emqx_shared_sub:redispatch/1` on terminate. After this commit, the session will no longer crash during channel terminate.
This was causing error reports in `emqx_persistent_session_SUITE` test suite that look like this:
```
*** System report during emqx_persistent_session_SUITE:t_process_dies_session_expires/1 in tcp 2023-11-20 05:43:13.294 ***
=WARNING REPORT==== 20-Nov-2023::05:43:13.293710 ===
context: function_clause
exception: error
msg: unclean_terminate
stacktrace: [{emqx_shared_sub,is_redispatch_needed,
[{message,
<<0,6,10,142,246,48,214,74,212,14,0,0,30,68,0,2>>,
2,<<"ps_SUITE_publisher">>,
#{dup => false,retain => false},
#{peerhost => {127,0,0,1},
properties => #{},proto_ver => …
```
> fix(sharesub): anticipate messages w/o redispatch header

- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/src/emqx_persistent_message.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_session.erl
- apps/emqx/test/emqx_persistent_messages_SUITE.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx/test/emqx_persistent_session_ds_router_SUITE.erl
- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_management/src/emqx_mgmt_data_backup.erl
- rel/i18n/emqx_schema.hocon
This PR introduces separate configuration schema root for new session persistence implementation. The old, no longer supported root `persistent_session_store` is marked as deprecated. There are also some knobs to choose a storage backend, with only support for the builtin RocksDB-based backend with minimal configuration.
Fixes [EMQX-11222](https://emqx.atlassian.net/browse/EMQX-11222).
> feat(schema): introduce separate root for new session persistence

- apps/emqx_bridge/src/emqx_action_info.erl
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub_action_info.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_action_info.erl
- apps/emqx_connector/src/schema/emqx_connector_schema.erl
- apps/emqx_utils/src/emqx_utils_maps.erl
This commit adds upgrade and downgrade hooks that are called when upgrading from a bridge V1 to connector and action or the other way around. The automatic translation is used if the callback is not defined.
NOTE: Backported from master as this will be needed for a bug fix
> fix(action): upgrade and downgrade strategy

- .github/workflows/build_packages.yaml
- changes/ce/breaking-11994.en.md
- changes/ce/breaking-11998.en.md
macOS 11 (Big Sur) is unsupported as of September 26, 2023.
> ci: stop building packages for macos-11

- apps/emqx_bridge/src/emqx_action_info.erl
- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/test/emqx_bridge_testlib.erl
- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_azure_event_hub/test/emqx_bridge_azure_event_hub_v2_SUITE.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11412
- The wrong type was being used in a list lookup function, resulting in the automatic transformation being called erroneously and mangling the config.
- There was a left-over workaround still around which could still mangle the config.
> fix(bridge_api): don't mangle configs, use correct type as argument

- apps/emqx/src/emqx_cm.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
Make sure to wait until client disconnect propagates to the channel state on the broker side in `emqx_persistent_session_SUITE` test suite.
> test(sessds): wait client disconnect propagates to broker

- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx/test/emqx_cth_cluster.erl
- apps/emqx/test/emqx_shared_sub_SUITE.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl
- apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_impl_producer_SUITE.erl
- apps/emqx_conf/test/emqx_conf_app_SUITE.erl
- apps/emqx_eviction_agent/test/emqx_eviction_agent_SUITE.erl
- apps/emqx_license/test/emqx_license_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_cluster_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_nodes_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl
- apps/emqx_node_rebalance/test/emqx_node_rebalance_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_SUITE.erl
- apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl
- apps/emqx_telemetry/test/emqx_telemetry_SUITE.erl
- rel/i18n/emqx_schema.hocon
Release version: `v/e5.4.0`
Use only `peer` module for all cluster tests.
i.e. no more `slave` and `ct_slave` in the codebase.
> test: replace 'slave' and 'ct_slave' with 'peer'

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_session.erl
In rare situations, it's possible to arrive at `handle_info({sock_closed, ...` clause in `emqx_channel` with no session. This PR fixes connection crashes in such cases.
> fix(channel): expect there's no session yet on disconnect

- apps/emqx/src/emqx_topic.erl
- apps/emqx/test/emqx_persistent_messages_SUITE.erl
- apps/emqx/test/emqx_topic_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_utils/src/emqx_utils_maps.erl
- apps/emqx_utils/test/emqx_utils_maps_tests.erl
Fixes [EMQX-11520](https://emqx.atlassian.net/browse/EMQX-11520).
We need to pass persisted messages topics through `emqx_topic:words/1`, so that empty levels in topics will be properly mapped into `''` atoms before being fed to the LTS tree.
> fix(ds): pass topics to emqx_topic:words/1 before feeding LTS tree

- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
Internally in `emqx_resource_manager`, there seems to be many points where the `gen_statem` states are conflated with resource status, since their names coincide.  While that works for now, introducing a new `gen_statem` state, an internal state, shouldn't necessarily imply a new, externally facing resource status.
Here we also introduce the usage of some macros to avoid the pitfalls of making a typo in a state/status name.
> refactor(resource_manager): use macros and better differentiate status from state

- .gitignore
- rebar.config.erl
[emqx_persistent_session_ds_gc_worker.erl#L109-L126](https://github.com/emqx/emqx/blob/e5.4.0-alpha.1/apps/emqx/src/emqx_persistent_session_ds_gc_worker.erl#L109-L126)
See line 119:
```
109   │ zombie_session_ms() ->
110   │     NowMS = now_ms(),
111   │     GCInterval = emqx_config:get([session_persistence, session_gc_interval]),
112   │     BumpInterval = emqx_config:get([session_persistence, last_alive_update_interval]),
113   │     TimeThreshold = max(GCInterval, BumpInterval) * 3,
114   │     ets:fun2ms(
115   │         fun(
116   │             #session{
117   │                 id = DSSessionId,
118   │                 last_alive_at = LastAliveAt,
119   │                 conninfo = #{expiry_interval := EI}
120   │             } …
```
> build: bump oldest otp vsn to OTP-25

- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- changes/ce/breaking-12112.en.md
- rel/i18n/emqx_conf_schema.hocon
- scripts/spellcheck/dicts/emqx.txt
Fixes [EMQX-11546](https://emqx.atlassian.net/browse/EMQX-11546)
`mcast` clustering strategy was announced deprecated since 5.1, now it's the time to finally drop the support from codebase.
Schema change is NOT backward compatible. 
> refactor: delete UDP multicast clustering strategy

- apps/emqx/test/emqx_cth_peer.erl
- apps/emqx_management/test/emqx_mgmt_api_plugins_SUITE.erl
Attempt to fix flaky `t_cluster_update_order` test from plugin management api.
> test(cth_peer): use an exclusive current dir for each peer

- apps/emqx_dashboard/src/emqx_dashboard_admin.erl
- apps/emqx_dashboard/src/emqx_dashboard_token.erl
- apps/emqx_management/src/emqx_mgmt_auth.erl
- changes/ce/fix-12111.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-10699
Use the sync_transaction to synchronize all updates to the replica node. 
btw: we use ro_transaction to read admin/token.
> fix: use sync_transaction when update admin/token

- .ci/docker-compose-file/docker-compose-greptimedb.yaml
- apps/emqx_bridge_greptimedb/rebar.config
- apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb_connector.erl
- apps/emqx_bridge_greptimedb/test/emqx_bridge_greptimedb_SUITE.erl
- changes/ee/feat-12072.en.md
- mix.exs
Main changes:
* Upgrade greptimedb to version 0.4.4 in CI workflow. 
* Upgrade greptimedb Erlang client to version 0.1.6 which supports asynchronous writing and fixes some bugs.
* Supports asynchronous query mode for emqx_bridge_greptimedb, which will have better performance.
> feat: implements async query mode for GreptimeDB data bridge

- apps/emqx_opentelemetry/rebar.config
A small fix for changing otel logger config, e.g. via EMQX CLI (all commands are now supported):
```
bin/emqx ctl log handlers stop opentelemetry_handler
bin/emqx ctl log handlers start opentelemetry_handler
bin/emqx ctl log handlers set-level opentelemetry_handler info
```
> Upgrade otel 1.4.7

- apps/emqx/src/emqx_persistent_message_ds_replayer.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds.hrl
- apps/emqx/test/emqx_persistent_messages_SUITE.erl
Also avoid accumulating QoS0-only ranges in memory.
> fix(sessds): stop overwriting QoS0-only pubrange checkpoints

- apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11494 
Even after this fix, the frontend seems to need some adjustment.  Apparently, it's reading from `failed` when rendering the failed metrics for the action, but it should consider `actions.failed`.
> fix(actions): increment rule statistics even if channel is not installed

- apps/emqx_audit/test/emqx_audit_api_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-10733
Make sure  put `/configs`  return readable msg.
```
curl -X 'PUT' \
'http://127.0.0.1:28083/api/v5/configs?mode=merge' \
-H 'accept: */*' \
-H 'Content-Type: text/plain' \
-d 'log.console.level=badwarning'
```
before:
```
": {\"log\":{\"kind\":\"validation_error\",\"matched_type\":[98,114,111,107,101,114,58,109,113,116,116,95,119,115,115,95,108,105,115,116,101,110,101,114],\"path\":[108,105,115,116,101,110,101,114,115,46,119,115,115,46,100,101,102,97,117,108,116,46,115,115,108,95,111,112,116,105,111,110,115],\"reason\":\"unknown_fields\",\"unknown\":[103,99,95,97,102,116,101,114,95,104,97,110,100,115,104,97,107,101],\"unmatched\":[99,105,112,104,101,114,115,44,99,108,105,101,110,116,95,114,101,110,101,103,111,116,105,97,116,105,111,110,44, …
```
> fix: ensure config update error text is readable

- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx_audit/src/emqx_audit.erl
- apps/emqx_audit/src/emqx_audit_api.erl
- apps/emqx_audit/test/emqx_audit_api_SUITE.erl
- apps/emqx_conf/src/emqx_conf_schema_types.erl
- apps/emqx_utils/src/emqx_utils_calendar.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11543
In the previous PR(https://github.com/emqx/emqx/pull/12150/files#diff-c584e250931fb265270c35f788dc5ccd73d34e45fa173cc1dec8bac697db616bL122), I changed the primary key of the audit log from millisecond to microsecond. However, this led to log overwrites when inserting logs in batches simultaneously. Therefore, I have reverted the precision back to **microsecond** here.
For HTTP API queries, microsecond precision is not required. When providing milliseconds, we automatically convert them to microseconds for compatibility and ease of use.
The precision change also addressed the frequent failures in the **t_max_size** CI, as it was a root cause of those issues.
Please convert it to a draft if any of the following …
> fix: use microsecond precision as the primary key for audit logs 

- apps/emqx_gateway_mqttsn/src/emqx_mqttsn_channel.erl
- apps/emqx_gateway_mqttsn/test/emqx_sn_protocol_SUITE.erl
- changes/ce/fix-12176.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11557
> fix(mqttsn): ack the DISCONNECT packet even if it is not connected

- apps/emqx/rebar.config
- apps/emqx/rebar.config.script
- apps/emqx/src/emqx.app.src
- apps/emqx_gateway/src/emqx_gateway_conf.erl
- apps/emqx_gateway_exproto/src/emqx_gateway_exproto.erl
- apps/emqx_gateway_ocpp/src/emqx_ocpp_connection.erl
- mix.exs
- rebar.config
- rebar.config.erl
A follow up fix for https://github.com/emqx/emqx/pull/12085#discussion_r1427735997
The static listing of `bcrypt` app in `emqx.app.src` also lead to a larger scope refactoring of `rebar.config.erl` and `mix.exs`
> 1215 chore fix app src for emqx app

- apps/emqx_gateway_jt808/doc/Data_Exchange_Guide_CN.md
- apps/emqx_gateway_jt808/src/emqx_jt808_auth.erl
- apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl
- apps/emqx_gateway_jt808/src/emqx_jt808_schema.erl
- apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl
Fixes [EMQX-11526](https://emqx.atlassian.net/browse/EMQX-11526)
@Kinplemelon gw_jt808 schema struct changed.
see `gateway.jt808.proto`
before:
```hocon
gateway.jt808 {
enable = true
enable_stats = true
xxx = xxx...
proto {
allow_anonymous = false
registry = "http://127.0.0.1:8991/jt808/auth"
authentication = "http://127.0.0.1:8991/jt808/registry"
dn_topic = "jt808/${clientid}/${phone}/dn"
up_topic = "jt808/${clientid}/${phone}/up"
}
}
```
after:
```hocon
gateway.jt808 {
enable = true
enable_stats = true
xxx = xxx...
proto {
auth {
allow_anonymous = true
registry = "http://127.0.0.1:8991/jt808/auth" ## NOT required when `allow_anonymous = ture`
authentication = "http://127.0.0.1:8991/jt808/registry" ## NOT required when `allow_anonymous = ture`
}
dn_topic = "jt808/${clientid}/${phone}/dn" …
```
> EMQX 11526 jt808 auth init function caluse

- apps/emqx/include/emqx_access_control.hrl
- apps/emqx/src/emqx_access_control.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz_rule_raw.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_SUITE.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_file_SUITE.erl
- apps/emqx_auth/test/emqx_authz/emqx_authz_rule_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_util.erl
- apps/emqx_rule_engine/src/emqx_rule_events.erl
- apps/emqx_utils/src/emqx_utils.erl
A part of change for https://github.com/emqx/emqx/issues/12187 and [EMQX-11372](https://emqx.atlassian.net/browse/EMQX-11372)
Move authz result logging to common place.
Prior to this change, the final result is not logged when
fallback to the default authorization.no_match config value.
Aso, if the result is provided by a hook callback,
it's also not logged.
After this change, only the final result is logged.
The authz chain resutls can be traced (or logged at debug level).
> 1217 improve authz logging

- apps/emqx_bridge_redis/src/emqx_bridge_redis.erl
- apps/emqx_bridge_redis/src/emqx_bridge_redis_schema.erl
- apps/emqx_bridge_redis/test/emqx_bridge_v2_redis_SUITE.erl
- rel/i18n/emqx_bridge_redis.hocon
- rel/i18n/emqx_bridge_redis_schema.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-11616
Change 
```
{
type : redis,
redis_type: single,
parameters : { command_template": ["LPUSH","MSGS","${payload}"]}
}
```
To:
```
{
type : redis
parameters : {redis_type: single, command_template": ["LPUSH","MSGS","${payload}"]}
}
```
> chore: move redis_type into parameters in actions

- apps/emqx/rebar.config
- changes/ce/fix-12081.en.md
- mix.exs
- rebar.config
Fixes https://emqx.atlassian.net/browse/EMQX-11595
Release version: `v/e5.4.0`
> fix: upgrade to gen_rpc 3.3.1 which does not log cast args only arity

- apps/emqx/include/asserts.hrl
- apps/emqx/rebar.config
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- apps/emqx_gateway_exproto/test/emqx_exproto_SUITE.erl
- changes/ce/feat-12201.en.md
- mix.exs
- rebar.config
Part of [EMQX-11527](https://emqx.atlassian.net/browse/EMQX-11527).
Part of [EMQX-11528](https://emqx.atlassian.net/browse/EMQX-11528).
1. No hot-update support for QUIC listeners.
2. No hot-update support for gateway listeners.
3. [TCP/SSL] Some changes will still cause full listener restart, which shuts down live connections.
* `bind`
* `tcp_options.backlog`
* `tcp_options.reuseaddr`
5. [WS/WSS] Most of the changes will cause listener socket to be reopened, yet unaccepted connections will be lost.
> feat(listen): support hot config update of MQTT listeners

- apps/emqx_conf/src/emqx_conf_schema.erl
> refactor: change mria default shard transport from 'gen_rpc' to 'distr'

- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_client.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
- mix.exs
- rebar.config
- gun from 1.3.9 to 1.3.10 for otp 26 type spec fix
- ehttpc from 0.4.11 to 0.4.12 for error handling improvements
> chore: upgrade gun and ehttpc

- apps/emqx_conf/src/emqx_cluster_rpc.erl
- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_management/src/emqx_mgmt_cli.erl
- apps/emqx_management/test/emqx_mgmt_cli_SUITE.erl
- changes/ce/fix-12232.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11649
> fix: remove rpc commit info when force_leave cluster

- apps/emqx_conf/src/emqx_conf.app.src
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src
- apps/emqx_opentelemetry/src/emqx_otel_schema.erl
- apps/emqx_opentelemetry/test/emqx_otel_schema_SUITE.erl
- changes/ce/fix-12234.en.md
HOCON converter is cleaner and safer option,
that will also work for configurations defined in emqx.conf. Previously used `upgrade_raw_conf/1` is currently not supported in hocon_cli (used in bin/emqx).
Fixes EMQX-11643
Release version: v/e5.4.1
> fix(emqx_opentelemetry): use converter to convert legacy metrics config

- apps/emqx_s3/src/emqx_s3.app.src
- apps/emqx_s3/src/emqx_s3_client.erl
- apps/emqx_s3/test/emqx_s3_client_SUITE.erl
- changes/ee/fix-12241.en.md
Fixes [EMQX-11665](https://emqx.atlassian.net/browse/EMQX-11665)
* Header names in config become atoms.
Probably because of blanket `unsafe_atom_key_map/1` in `emqx_config`.
* Header names should be normalized to lowercase.
Otherwise signature will be incorrect.
> fix(s3): handle extra configured headers correctly

- apps/emqx/include/emqx_release.hrl
- apps/emqx/src/emqx.app.src
- apps/emqx/src/emqx_passwd.erl
- apps/emqx_bridge_mqtt/rebar.config
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_egress.erl
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_ingress.erl
- apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_lib.erl
- apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_SUITE.erl
- changes/ce/fix-12236.en.md
Fixes [EMQX-11662](https://emqx.atlassian.net/browse/EMQX-11662)
Release version: `v/e5.4.1`
According to MQTT 3.1 spec, client ID should not exceed 23 bytes length.
Although most brokers actually allow longer client IDs, some actually implements this strict limitation.
Prior to this change, EMQX MQTT bridge generates client ID from bridge name (assigned by user) concatenated with node name. This concatenation is often longer than 23 bytes.
This PR makes a best effort to keep the possibility to correlate client IDs with bridge name (assigned by user).
- ClientID is prefixed with bridge name
- Concatenated with first 8 bytes from the node name's SHA hash
- Concatenated with the pool member ID
In most cases, this is not longer than 23 bytes.
However, if it still exceeds 23 bytes, SHA hash + …
> fix(bridge/mqtt): ensure short clientid

- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_router.erl
- apps/emqx/test/emqx_routing_SUITE.erl
- changes/ce/fix-12243.en.md
Instead of (potentially lagging) global table state itself. Local state should be the only source of truth anyway. Moreover,
synchronize parts of local state update logic through the broker pool to ensure consistency.
The problem was that `emqx_router:has_route/2` check may observe a stale route, which deletion is not yet replicated from the core node to the local replicant node.
For example:
1. The only one subscriber per a given topic A unsubscribes from a replicant node.
2. The route to A is deleted by the `emqx_broker`.
3. Mria makes RPC to a core node, it succeeds and returns.
4. The client resubscribes or another client subscribes to the same topic A.
5. emqx_broker tries to add a route again: `emqx_router:do_add_route(Topic)`.
6. `emqx_router` checks if the route is present.
7. The …
> fix(router): rely on local sync state updates to propagate routes

- deploy/charts/emqx/templates/StatefulSet.yaml
permits specifying ports such as :::18083, a somewhat strange but needed
syntax when trying to make emqx listen on IPv6 addresses
The solution here is to split by colon `:` and to only keep the last
entry, which will corespond to the actual number for the port.
can be tested by using following values.yaml config:
```yaml
emqxConfig:
EMQX_CLUSTER__DISCOVERY_STRATEGY: "dns"
EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
EMQX_DASHBOARD__DEFAULT_PASSWORD: "public"
EMQX_LISTENERS__TCP__DEFAULT__BIND: ":::1234"
EMQX_LISTENERS__TCP__INTERNAL__BIND: ":::3456"
EMQX_DASHBOARD__LISTENERS__HTTP__BIND: ":::31415"
EMQX_DASHBOARD__LISTENERS__HTTPS__BIND: ":::65432
```
> feat(helm): only keep last digits for ipv6 ports

- apps/emqx_ft/src/emqx_ft.app.src
- apps/emqx_ft/src/emqx_ft_api.erl
- apps/emqx_ft/src/emqx_ft_conf.erl
- apps/emqx_ft/test/emqx_ft_api_SUITE.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
Modified the `/file_transfer` API to return the file transfer configuration in raw format rather than converting time units like "1h" to seconds, providing callers with the original configured values for consistency with other getter APIs 
> fix: ft config update api return raw config

- apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_sup.erl
- apps/emqx_durable_storage/src/emqx_durable_storage.app.src
- apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
Fixes [EMQX-11692](https://emqx.atlassian.net/browse/EMQX-11692)
Release version: `v/e5.4.1`
> fix(ds): Don't start the supervision tree when feature is off

- bin/emqx
Prior to this change, 'true=emqx:is_running().' Erlang assertion is evaluated before 'emqx start' command gives up waiting.
The Erlang assertion would result in a error level crash log which can be confusing.
This commit changes the equals to 'true' check to bash script instead.
Fixes [EMQX-11701](https://emqx.atlassian.net/browse/EMQX-11701)
> fix(bin/emqx): check app status in bash script

- apps/emqx_bridge/src/emqx_action_info.erl
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl
- apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
- apps/emqx_bridge_redis/src/emqx_bridge_redis.app.src
- apps/emqx_bridge_redis/src/emqx_bridge_redis.erl
- apps/emqx_bridge_redis/src/emqx_bridge_redis_action_info.erl
- apps/emqx_bridge_redis/src/emqx_bridge_redis_schema.erl
- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_connector/src/emqx_connector.erl
- apps/emqx_connector/src/emqx_connector_resource.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11695
Two major changes have been made:
1. Redis actions no longer require the `redis_type` parameter. It can be inferred by the connector being used.
This parameter has caused some confusion in the prev version. When users configure the `redis_type` of actions as "sentinel," the corresponding connector should ideally be set as "sentinel" as well. However, it was observed that the actions could still run even if the connector was set as "single."
2. We will make the following improvements to the code for bulk importing connectors and actions:
If a connector is referenced by an action, it cannot be deleted successfully. Therefore, we will prioritize deleting actions before updating connectors.
While creating an action, if the corresponding …
> fix: remove redis_type from redis action

- apps/emqx_retainer/src/emqx_retainer.app.src
- apps/emqx_retainer/src/emqx_retainer_api.erl
- apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl
- changes/ce/feat-12272.en.md
- rel/i18n/emqx_retainer_api.hocon
Fixes [EMQX-11668](https://emqx.atlassian.net/browse/EMQX-11668)
> feat(retain): add two new endpoints for retain API

- apps/emqx_management/src/emqx_mgmt_api.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- changes/ce/fix-12269.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11624
> chore: improve the error message if the parameter invalid

- apps/emqx/rebar.config.script
- apps/emqx/src/emqx_listeners.erl
- apps/emqx/src/emqx_quic_stream.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
- changes/feat-12274.en.md
- mix.exs
- rebar.config.erl
Fixes [EMQX-11608](https://emqx.atlassian.net/browse/EMQX-11608)
Release version: v5.5
- Bump to quicer 0.0.311
- Quicer Listener support hot config with new TLS params
- Config quicer listener with map() (switch from proplist())
- Reuse funs in  emqx_tls module
> feat: quic listener conf reload

- apps/emqx_bridge/test/emqx_bridge_testlib.erl
- apps/emqx_bridge_mysql/src/emqx_bridge_mysql.app.src
- apps/emqx_bridge_mysql/src/emqx_bridge_mysql_connector.erl
- apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl
- changes/ee/fix-12281.en.md
- changes/ee/fix-12282.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11655
Fixes https://emqx.atlassian.net/browse/EMQX-11648
> fix(mysql_bridge): allow deleting bridge when sql contains undefined fields

- apps/emqx/rebar.config
- apps/emqx_ft/test/emqx_ft_api_SUITE.erl
- changes/ee/fix-12291.en.md
- mix.exs
- rebar.config
Fixes [EMQX-11636](https://emqx.atlassian.net/browse/EMQX-11636).
Release version: `e5.5.0`
Which includes a bugfix ensuring that undefined sensitive values does not turn into `******` after `hocon_tconf:check_plain/4`.
> fix(conf): bump to hocon 0.40.4

- apps/emqx_retainer/src/emqx_retainer.erl
- apps/emqx_retainer/src/emqx_retainer_api.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
[EMQX-11709](https://emqx.atlassian.net/browse/EMQX-11709)
> fix(retain): add `hasnext` into the meta data for the `GET /retain/messages`

- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_producer_schema.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11703
> fix(gcp_pubsub_producer): mark connector resource opts fields as deprecated

- apps/emqx_retainer/src/emqx_retainer_index.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_index_SUITE.erl
- apps/emqx_retainer/test/props/prop_emqx_retainer_index.erl
- changes/ce/fix-12303.en.md
Fixes 
[EMQX-11710](https://emqx.atlassian.net/browse/EMQX-11710)
[EMQX-11711](https://emqx.atlassian.net/browse/EMQX-11711)
Release version: v/e5.4.2
> fix(retainer): fix topic search by index

- apps/emqx/src/emqx_broker.erl
- apps/emqx/src/emqx_broker_sup.erl
- apps/emqx/src/emqx_router.erl
- apps/emqx/src/emqx_router_syncer.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_cth_suite.erl
- apps/emqx/test/emqx_routing_SUITE.erl
- apps/emqx_utils/src/emqx_utils_stream.erl
- apps/emqx_utils/test/emqx_utils_stream_tests.erl
- rel/i18n/emqx_schema.hocon
Fixes [EMQX-11483](https://emqx.atlassian.net/browse/EMQX-11483).
Dedicated to synchronizing local state updates with the global view of the routing state. This should help with:
* Free `emqx_broker` pool from doing global routing updates.
* Minimize roundtrips over high-latency links to core nodes.
* ~~Make it much harder to reach inconsistent routing state~~ Split into #12243.
> feat(routing): add route sync process pool

- apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl
- apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.app.src
- apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.erl
- changes/ee/fix-12317.en.md
Fixes https://emqx.atlassian.net/browse/ED-1171
The old bridge schema already had this override, but it had not been ported to actions.
> fix(mongodb_action): make `batch_size` hidden and fixed in the API

- apps/emqx_bridge_influxdb/rebar.config
- apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb.erl
- apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl
- apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_SUITE.erl
- apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_tests.erl
- changes/ee/feat-12247.en.md
- changes/ee/fix-12301.en.md
- mix.exs
Fixes https://emqx.atlassian.net/browse/EMQX-11637
Release version: e5.5
> fix: cannot write literal numbers to influxdb

- apps/emqx/src/emqx_access_control.erl
- apps/emqx/src/emqx_logger_textfmt.erl
Fixes [EMQX-11726](https://emqx.atlassian.net/browse/EMQX-11726)
This is a follow up fix for https://github.com/emqx/emqx/pull/12191 which used the default `no_match` action as final check result.
> 0116 fix authz logging

- apps/emqx/include/emqx_cm.hrl
- apps/emqx/src/emqx_cm.erl
- apps/emqx/src/emqx_cm_sup.erl
- apps/emqx/src/emqx_pool.erl
- apps/emqx/test/emqx_cm_SUITE.erl
- changes/ce/perf-12336.en.md
This is to isolate channels cleanup from other async tasks (like routes cleanup), as channels cleanup can be quite slow under high network latency conditions.
Fixes EMQX-11743
> perf(emqx_cm): use a dedicated pool for channel cleanup

- apps/emqx/src/emqx_access_control.erl
- apps/emqx/src/emqx_authz_cache.erl
- apps/emqx/src/emqx_metrics.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
Fixes [EMQX-11734](https://emqx.atlassian.net/browse/EMQX-11734)
This is s a follow-up fix for https://github.com/emqx/emqx/pull/12289 (not released yet)
Also added a `cache_miss` counter (exported to prometheus)
> 0118 fix authz cache excludes type

- .gitignore
For some reason, some tools like [ripgrep](https://github.com/BurntSushi/ripgrep) will search `.git` when using the `-.`/`--hidden` flag, even when not using `--no-ignore-vcs`. This leads to several unwanted results.
> ci(dev): add `.git/` to `.gitignore`

- apps/emqx/priv/bpapi.versions
- apps/emqx/src/emqx_stats.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
- apps/emqx_license/src/emqx_license.app.src
- apps/emqx_license/src/emqx_license_checker.erl
- apps/emqx_prometheus/include/emqx_prometheus.hrl
- apps/emqx_prometheus/rebar.config
- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
- apps/emqx_prometheus/src/emqx_prometheus_api.erl
- apps/emqx_prometheus/src/emqx_prometheus_auth.erl
- apps/emqx_prometheus/src/emqx_prometheus_cluster.erl
- apps/emqx_prometheus/src/emqx_prometheus_config.erl
- apps/emqx_prometheus/src/emqx_prometheus_data_integration.erl
- apps/emqx_prometheus/src/emqx_prometheus_sup.erl
- apps/emqx_prometheus/src/emqx_prometheus_utils.erl
- apps/emqx_prometheus/src/proto/emqx_prometheus_proto_v2.erl
- apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl
- apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl
- apps/emqx_retainer/src/emqx_retainer_api.erl
- changes/ce/feat-12299.en.md
- changes/ee/feat-12299.en.md
- rel/i18n/emqx_prometheus_api.hocon
Fixes [EMQX-9700](https://emqx.atlassian.net/browse/EMQX-9700)
> EMQX-9700 improve observability

- apps/emqx_bridge/src/emqx_bridge.erl
- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
- apps/emqx_connector/src/emqx_connector.erl
- apps/emqx_utils/src/emqx_utils.erl
- changes/ce/perf-12354.en.md
Fixes EMQX-11751
Each bridge creation can take signficant time. 
For example, if `start_after_created = true` (which is default), and the bridge connector implementation doesn't set `disconnected` state but only uses `connected` or `connecting`,  the bridge creation can be blocked for up to `start_timeout` (defaults to 5s) if the data sink is not reachable/healthy. 
When the batch of bridges is being updated/created, there no need to wait for a bridge creation before proceeding to the next one.
We can create all of them in parallel and wait for results/errors. 
This can greatly improve config load / backup file import performance, when there are many bridges and some/all data sinks are not reachable/healthy. 
Please convert it to a draft if any of the following …
> Apply brdige post config changes in parallel

- apps/emqx/src/emqx_persistent_message.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
The storage expectations for the RocksDB DB may be different from our usual data directory.  Also, it may consume a lot more storage than other data.
This allows customizing the data directory for the builtin DS storage backend.
Note: if the cluster was already initialized using a directory path, changing that config will have no effect.  This path is currently persisted in mnesia and used when reopening the DB.
> feat(ds): allow customizing the data directory

- apps/emqx/include/http_api.hrl
- apps/emqx_dashboard/src/emqx_dashboard.erl
- apps/emqx_dashboard/src/emqx_dashboard_api.erl
- apps/emqx_management/src/emqx_mgmt_api_api_keys.erl
- apps/emqx_management/src/emqx_mgmt_auth.erl
- apps/emqx_management/test/emqx_mgmt_api_api_keys_SUITE.erl
- rel/i18n/emqx_mgmt_api_api_keys.hocon
Fixes https://emqx.atlassian.net/browse/EMQX-11594
This is just a documentation update and does not require a changelog.
> chore: document api-key path api only support bearerAuth

- apps/emqx/test/emqx_persistent_messages_SUITE.erl
- apps/emqx_durable_storage/src/emqx_ds_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
Fixes https://github.com/emqx/emqx/pull/12338#discussion_r1462139499
> perf(ds): inherit only LTS paths containing wildcards when adding a new generation

- apps/emqx_bridge_es/src/emqx_bridge_es.app.src
- apps/emqx_bridge_http/src/emqx_bridge_http.app.src
- apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src
- apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.app.src
- apps/emqx_bridge_mysql/src/emqx_bridge_mysql.app.src
- apps/emqx_bridge_redis/src/emqx_bridge_redis.app.src
- apps/emqx_machine/src/emqx_machine_boot.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
- apps/emqx_mongodb/src/emqx_mongodb.app.src
- apps/emqx_mysql/src/emqx_mysql.app.src
- apps/emqx_postgresql/src/emqx_postgresql.app.src
- apps/emqx_redis/src/emqx_redis.app.src
- changes/ce/fix-12359.en.md
For the same reasons as we inject `emqx_bridge_*` applications as dependencies to `emqx_bridge` when starting the node.  Already configured connectors are started when `emqx_connector` application starts, and may lead to crashes and noise in the logs.  One example is to configure a mongodb bridge and restart the node.
Thanks to @SergeTupchiy for noticing this.  :beers: 
Fixes https://emqx.atlassian.net/browse/EMQX-11771
> fix(machine_boot): inject connector/bridge apps as dependencies to `emqx_connector` app

- Makefile
- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
- apps/emqx_prometheus/rebar.config
- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
- apps/emqx_prometheus/src/emqx_prometheus_auth.erl
- apps/emqx_prometheus/src/emqx_prometheus_cluster.erl
- apps/emqx_prometheus/src/emqx_prometheus_data_integration.erl
Contains some fixes for #12299
Includes
- Some metric types are incorrect.
- The problem of cluster aggregation failure and no node label.
- The problem of incorrect connector indicators.
- The problem of missing action indicator.
BUG found and marked TODO:
`emqx_bridge_v2_api:format_metrics/1` havs missing metrics: `'retried.success'` and `'retried.failed'`
See also for detials:
Fixes [EMQX-11794](https://emqx.atlassian.net/browse/EMQX-11794) [EMQX-11795](https://emqx.atlassian.net/browse/EMQX-11795) [EMQX-11789](https://emqx.atlassian.net/browse/EMQX-11789) [EMQX-11799](https://emqx.atlassian.net/browse/EMQX-11799) [EMQX-11800](https://emqx.atlassian.net/browse/EMQX-11800) [EMQX-11801](https://emqx.atlassian.net/browse/EMQX-11801) …
> Follow up #12299

- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- changes/ee/feat-12381.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-10970
port https://github.com/emqx/emqx-enterprise/pull/1892
> feat: port emqx/emqx-enterprise#1892, add some SQL functions

- apps/emqx_machine/src/emqx_machine_boot.erl
- apps/emqx_machine/test/emqx_machine_SUITE.erl
- changes/ee/fix-12390.en.md
```
2024-01-25T09:41:46.391446+08:00 [warning] mfa: minirest_handler:apply_callback/3(142), exception: exit, path: /license, reason: {noproc,{gen_server,call,[emqx_license_checker,dump,infinity]}}, stacktrace: [{gen_server,call,3,[{file,"gen_server.erl"},{line,385}]},{emqx_license_http_api,'/license',2,[{file,"emqx_license_http_api.erl"},{line,126}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,137}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,56}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,27}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"} …
```
> fix: reboot emqx_dashboard after emqx_licencse

- apps/emqx/src/emqx_persistent_message.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
The data directory was ending up being persisted in the database schema.  This led to issues when opening the DB on different nodes.
> fix(ds): don't make data dir part of the schema

- apps/emqx_bridge/src/emqx_action_info.erl
- apps/emqx_bridge_greptimedb/rebar.config
- apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb.app.src
- apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb.erl
- apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb_action_info.erl
- apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb_connector.erl
- apps/emqx_bridge_greptimedb/test/emqx_bridge_greptimedb_SUITE.erl
- apps/emqx_bridge_greptimedb/test/emqx_bridge_greptimedb_connector_SUITE.erl
- apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_action_info.erl
- apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
- apps/emqx_connector/src/schema/emqx_connector_schema.erl
- changes/ee/feat-12386.en.md
- mix.exs
- rel/i18n/emqx_bridge_greptimedb.hocon
> refactor greptimedb bridge (split to actions and connectors)

- rebar.config.erl
Since we use coveralls' [parallel webhook API](https://docs.coveralls.io/api-parallel-build-webhook), it seems we should also set it in our [plugin config](https://github.com/emqx/coveralls-erl/blob/02daa4e5f157ff16d10b41ce00b829bc8734a9e1/src/rebar3_coveralls.erl#L132).
> ci: enable coveralls parallel send

- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_ws_connection.erl
- changes/perf-12392.en.md
- rel/i18n/emqx_schema.hocon
> perf: new ws listener option to disable UTF-8 validation

- apps/emqx_durable_storage/src/emqx_ds.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
Attempt to mitigate this frequent source of flakiness:
```
=CRASH REPORT==== 31-Jan-2024::17:30:15.025404 ===
crasher:
initial call: emqx_ds_replication_layer_egress:init/1
pid: <0.11312.0>
registered_name: []
exception error: no match of right hand side value {error,
no_leader_for_shard}
in function  emqx_ds_replication_layer_egress:init/1 (/emqx/apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl, line 93)
in call from gen_server:init_it/2 (gen_server.erl, line 980)
in call from gen_server:init_it/6 (gen_server.erl, line 935)
ancestors: [<0.11310.0>,<0.11304.0>,emqx_ds_builtin_databases_sup,
emqx_ds_builtin_sup,emqx_ds_sup,<0.11236.0>]
message_queue_len: 0
messages: []
links: [<0.11310.0>]
dictionary: []
trap_exit: true
status: running
heap_size: 376
stack_size: 28 …
```
> fix(ds): reduce egress start flakiness

- apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
- apps/emqx_connector/test/emqx_connector_SUITE.erl
- apps/emqx_resource/src/emqx_resource_manager.erl
If we change one action/source's to `enable=false`,  
then **restart emqx**
It's will auto add this disable action/source  to connector's channel.
```erlang
emqx_resource_manager:list_all().
[#{error => undefined,id => <<"connector:http:adfasdfd">>,
status => connected,
state =>
#{port => 28083,
request =>
#{path => [<<>>],
body => undefined,
headers => [{[<<"content-type">>],[<<"application/json">>]}],
method => [<<"undefined">>],
max_retries => 2,request_timeout => 30000},
host => {127,0,0,1},
connect_timeout => 15000,pool_type => random,
pool_name => <<"connector:http:adfasdfd">>,base_path => "/",
installed_actions =>
#{<<"action:http:dafdafd:connector:http:adfasdfd">> =>
#{path => [<<>>],
body => [<<"ldkfadkfd">>],
headers => …
```
> fix: don't add disable bridge to connector's channel

- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/src/emqx_broker.erl
- apps/emqx_bridge_azure_event_hub/rebar.config
- apps/emqx_bridge_confluent/rebar.config
- apps/emqx_bridge_kafka/rebar.config
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
- changes/ee/feat-12427.en.md
- mix.exs
- rel/i18n/emqx_bridge_azure_event_hub.hocon
- rel/i18n/emqx_bridge_confluent_producer.hocon
- rel/i18n/emqx_bridge_kafka.hocon
Fixes [EMQX-11297](https://emqx.atlassian.net/browse/EMQX-11297)
> 0130 limit kafka partitions

- apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
> kafka-bridge: dont stacktrace when no partition count

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds_state.erl
- apps/emqx/test/emqx_cth_suite.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/test/emqx_mgmt_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11644
List subscriptions of the persistent session in the REST API
> feat(sessds): Expose subscriptions in the REST API

- .github/workflows/build_packages.yaml
We need to use v3 actions family in `build_packages` because v4 is on NodeJS 20, and NodeJS 20 is not supported on older platforms.
There was a messed up change when `actions/upload-artifacts` in `macos` job used v4 family, `linux` job v3 family, and `actions/download-artifacts` was v4 family. Since v4 and v3 are incompatible (i.e., v4 cannot download v3 artifcats, and vice versa), when we published latest release, it only got macos artifacts.
> ci: use v3 artifacts actions in build packages

- apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
- apps/emqx_management/src/emqx_mgmt_cli.erl
Add `emqx_ctl ds info` CLI command to inspect the state of DS shards and sites.
> feat(ds): Add a CLI interface to inspect status of DS databases

- apps/emqx_conf/src/emqx_conf_schema.erl
- changes/ce/feat-12467.en.md
Ekka autocluster DNS already supports AAAA records, so it's only needed to update enum in schema.
Fixes #12448 
> feat(emqx_conf): support AAAA cluster dns record type

- deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
- deploy/charts/emqx-enterprise/values.yaml
- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/values.yaml
Fixes https://github.com/emqx/emqx/issues/12378
An optional parameter `priorityClassName` for setting the priority of the pods would help for running the broker more stable.
> feat(helm): possibility to add `priorityClassName` in helm chart for pods

- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
- apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl
- changes/ce/fix-12472.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11834
> fix(bridge_v2_api): avoid calling nodes that do not support minimum bpapi

- apps/emqx_conf/src/emqx_conf_cli.erl
- changes/ce/feat-12483.en.md
- rel/i18n/emqx_auto_subscribe_schema.hocon
Minor improvements following up some support quitestions.
* Change `emqx ctl conf cluster_sync tnxid <ID>` to `emqx ctl conf cluster_sync inspect<ID>`
* Refine the `help` info for `emqx ctl conf cluster_sync`
> Improve emqx ctl conf cluster_sync CLI and help text

- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds.hrl
- apps/emqx/src/emqx_persistent_session_ds_stream_scheduler.erl
- apps/emqx/src/emqx_persistent_session_ds_subs.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11537
Postpone deletion of UNSUBSCRIBE until all in-flight packets are processed by the client. 
> fix(ds): Fix unsubscribe logic related to the replay

- apps/emqx/src/emqx_channel.erl
- apps/emqx/test/emqx_client_SUITE.erl
- changes/ce/fix-12492.en.md
Fixes  https://github.com/emqx/emqx/issues/3648
> fix(emqx_channel): return Receive-Maximum in CONNACK when no error

- apps/emqx_mongodb/rebar.config
- apps/emqx_mongodb/src/emqx_mongodb.app.src
- apps/emqx_mongodb/src/emqx_mongodb.erl
- changes/ee/perf-12497.en.md
Fixes EMQX-11825
Release version: `e5.5.1`
> mongodb connector perf (release-55)

- apps/emqx_bridge/src/emqx_action_info.erl
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq.app.src
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq.erl
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_action_info.erl
- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl
- apps/emqx_bridge_rocketmq/test/emqx_bridge_rocketmq_SUITE.erl
- apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
- apps/emqx_connector/src/schema/emqx_connector_schema.erl
- changes/ee/feat-12488.en.md
- rel/i18n/emqx_bridge_rocketmq.hocon
Fixes:
https://emqx.atlassian.net/browse/EMQX-11467
> feat: refactor RocketMQ bridge to connector and action

- apps/emqx/src/emqx_access_control.erl
- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_session_events.erl
- apps/emqx_license/src/emqx_license.erl
- changes/ce/fix-12513.en.md
Temporary fix for EMQX-11530, while I'm working on a log throttling feature
Release version: v/e5.
> fix: set `info` level for potentially flooding log events

- .github/workflows/_pr_entrypoint.yaml
- .github/workflows/_push-entrypoint.yaml
- .github/workflows/build_and_push_docker_images.yaml
- .github/workflows/build_docker_for_test.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/run_docker_tests.yaml
- build
- deploy/docker/Dockerfile
- deploy/docker/docker-entrypoint.sh
- scripts/ui-tests/docker-compose.yaml
To speed up the build process, we build the binaries for multi-arch docker image on the instances with corresponding architecture first, then assemble the final docker image.
Resulting docker image is now the same as the one produced by https://github.com/emqx/emqx-docker, and is slightly less in size than before.
As a side effect, now one can also build a docker image locally quickly out of .tar.gz release package.
Reference build_and_push_docker_images runs: 
- https://github.com/emqx/emqx/actions/runs/7900235217
- https://github.com/emqx/emqx/actions/runs/7900454766
Images on docker hub: https://hub.docker.com/repository/docker/dyachkov/emqx/tags?page=1&ordering=last_updated
Release version: v/e5.5.x
Please convert it to a draft if any of the following conditions are not met. Reviewers …
> ci: build binaries for each arch of docker image separately

- apps/emqx_gateway/src/emqx_gateway_utils.erl
- apps/emqx_gateway/test/emqx_gateway_SUITE.erl
- apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl
- apps/emqx_gateway_jt808/src/emqx_jt808_schema.erl
- apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl
- rel/i18n/emqx_jt808_schema.hocon
Since the set of known gateways is already predefined in `emqx_gateway_utils` it makes no sense to scan over all modules just to find out the same set of modules. Cutting out this scanning saves few seconds per each `emqx_conf` application startup, which is especially noticeable when running tests.
> fix(gateway): avoid scanning modules of known gateway apps

- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_persistent_session_ds_inflight.erl
- apps/emqx/test/emqx_persistent_session_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11854
- Add more sophisticated mechanism for seqno tracking that tolerates gaps in the sequence number series
- This enables durable sessions to process "transient" messages that are not stored in any DS DB
- This allows durable sessions to forward `deliver`s from the retainer to the clients.  
> Durable sessions support retained messages 

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_frame.erl
- apps/emqx/src/emqx_packet.erl
- apps/emqx/test/emqx_channel_SUITE.erl
- apps/emqx/test/emqx_frame_SUITE.erl
- apps/emqx/test/emqx_ws_connection_SUITE.erl
- changes/ce/fix-12530.en.md
* Log parsed bytes and bytes limit for `frame_too_large` error
* Refactored connect packet parse failures to include more details
example trace:
```
2024-02-18T19:40:28.241495+01:00 [MQTT] test@127.0.0.1:47552 msg: mqtt_packet_received, packet: {frame_error,#{limit => 100,cause => frame_too_large,received => 143}}
2024-02-18T19:40:28.241765+01:00 [SOCKET] test@127.0.0.1:47552 msg: socket_force_closed, reason: frame_too_large
2024-02-18T19:40:28.242150+01:00 [SOCKET] test@127.0.0.1:47552 msg: emqx_connection_terminated, reason: {shutdown,frame_too_large}
```
> 0217 improve frame too large logging context

- apps/emqx_retainer/src/emqx_retainer.erl
So far the retainer backend type is always `built_in_database`. The slightly over-engineered pre-implementation to support another backend is likely not going to fly as the EMQX resource framework is mostly for auth and data integration. i.e. not generic enough for retained messages.
> refactor: delete non-prod code

- apps/emqx/include/logger.hrl
- apps/emqx/src/emqx_access_control.erl
- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_kernel_sup.erl
- apps/emqx/src/emqx_log_throttler.erl
- apps/emqx/src/emqx_session_events.erl
- apps/emqx/test/emqx_log_throttler_SUITE.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_conf_logger_SUITE.erl
- apps/emqx_enterprise/test/emqx_enterprise_schema_SUITE.erl
- apps/emqx_license/src/emqx_license.erl
- changes/ce/feat-12520.en.md
- rel/i18n/emqx_conf_schema.hocon
Fixes EMQX-11530
Short demo:
3000 subscribers to EMQX Enterprise with the default trial license:
`emqtt_bench sub -t t/test  -p 1883 -c 3000 -R 1000`
```
2024-02-20T13:15:20.890612+02:00 [error] msg: connection_rejected_due_to_license_limit_reached, mfa: emqx_license:check/2(90), peername: 127.0.0.1:39654
2024-02-20T13:15:25.359433+02:00 [warning] msg: alarm_is_activated, mfa: emqx_alarm:do_actions/3(416), message: <<"License: live connection number exceeds 80%">>, name: license_quota
2024-02-20T13:16:05.176869+02:00 [warning] msg: log_events_throttled_during_last_period, mfa: emqx_log_throttler:maybe_log_dropped/2(141), period: 1 minutes, 0 seconds, dropped: #{"connection_rejected_due_to_license_limit_reached" => 2970}
```
Please convert it to a draft if any of …
> feat: implement log throttling

- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_conf/test/emqx_conf_schema_tests.erl
- changes/ce/fix-12541.en.md
- dev
Fixes https://github.com/emqx/emqx/issues/12484
Added a schema validation to fail fast if the host part of node name is not IP but cluster strategy is `dns` with `a` or `aaaa` record type.
Example log:
```
2024-02-20T16:07:47.733469+01:00 [error] #{reason => integrity_validation_failure,result => #{domain => "local.host",explain => "Node name must be of name@IP format for DNS cluster discovery strategy with 'a' record type."},kind => validation_error,validation_name => check_node_name_and_discovery_strategy}
```
> Fail fast if node host is not IP address but cluster strategy is `dns` with `a` or `aaaa` record type

- apps/emqx_bridge/src/emqx_bridge_v2.erl
- apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl
RabbitMQ's source only have v2 version. It's should not show in bridge_v1_list. otherwise it's will crash.
```
{
"code": "INTERNAL_ERROR",
"message": "throw, {emqx_bridge_schema,[#{kind => validation_error,path => \"bridges.rabbitmq.foo\",reason => unknown_fields,unknown => \"no_ack,queue\",unmatched => \"delivery_mode,exchange,...\"}]}, [{hocon_tconf,assert,2,[{file,\"hocon_tconf.erl\"},{line,1230}]},{hocon_tconf,map,4,[{file,\"hocon_tconf.erl\"},{line,303}]},{hocon_tconf,do_check,4,[{file,\"hocon_tconf.erl\"},{line,267}]},{emqx_bridge_api,fill_defaults,2,[{file,\"emqx_bridge_api.erl\"},{line,1013}]},{emqx_bridge_api,format_resource,2,[{file,\"emqx_bridge_api.erl\"},{line,924}]},{emqx_bridge_api,'-/bridges/2-lc$^1/1-1-',2,[{file,\"emq …
```
> fix: bridge_v1 http api crash when create rabbitmq source

- apps/emqx/src/emqx_persistent_session_ds_state.erl
- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/src/emqx_mgmt_api.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_test_util.erl
- changes/ce/fix-12500.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11540
Note that not all information provided by disconnected in-memory sessions is available to
disconnected persistent sessions, nor does all of them make sense.
> feat(ds): list disconnected persistent sessions in clients API

- .github/workflows/build_packages.yaml
Fixes issue when "Cross build packages" workflow fails if triggered manually without setting profile.
https://github.com/emqx/emqx/actions/runs/7987441219
Release version: v/e5.5.?
> ci: make profile required field when triggering build packages manually

- apps/emqx_bridge/src/emqx_action_info.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo.app.src
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_action_info.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl
- apps/emqx_bridge_dynamo/test/emqx_bridge_dynamo_SUITE.erl
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src
- apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
- apps/emqx_connector/src/schema/emqx_connector_schema.erl
- changes/ee/feat-12543.en.md
- rel/i18n/emqx_bridge_dynamo.hocon
Fixes:
https://emqx.atlassian.net/browse/EMQX-11456
> feat: refactor DynamoDB bridge to connector and action

- apps/emqx/src/bpapi/emqx_bpapi.erl
- apps/emqx/test/emqx_bpapi_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11886
Mira‘s transaction only run on core node. we can't run node() on transaction. otherwise The replicant node never write bpapi version.
https://github.com/emqx/emqx/commit/76d242df9bb034ab1401b3e45652c2b577125908#diff-cca246fd249ba536867e4912365801199feab54d2fd5c3d2ba56473002c1c16fR1061-R1070
the front of 550 was fixed call as `running_node`, and this commit tried to ignore the nodes that couldn't be upgraded.However, the replicant nodes have never updated their status correctly and have always been in the nodes that cannot be upgraded.
> fix: bpapi announce's bad node name

- apps/emqx_conf/src/emqx_conf_cli.erl
- apps/emqx_conf/test/emqx_conf_cli_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11684 and https://emqx.atlassian.net/browse/EMQX-11833
Prohibit updating read-only configuration items and point out which key cannot be updated.
Replace `"update_readonly_keys_prohibited"` with
`"Cannot update read-only key 'cluster'."`
> fix(api): more detail error when don't allow update readonly key

- apps/emqx/src/emqx_persistent_session_ds_inflight.erl
- apps/emqx_resource/include/emqx_resource.hrl
- apps/emqx_resource/src/emqx_resource.erl
- apps/emqx_resource/src/emqx_resource_buffer_worker.erl
- apps/emqx_resource/test/emqx_connector_demo.erl
- apps/emqx_resource/test/emqx_resource_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11892
This allows callers of batching resources to receive results specific to their requests,
rather than a broad success or failure for the whole batch.
> feat(resource): allow `on_batch_query{,_async}` to return a list of individual results

- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/src/emqx_zone_schema.erl
- apps/emqx/test/emqx_message_SUITE.erl
- apps/emqx_auth/src/emqx_authz/emqx_authz_schema.erl
- apps/emqx_conf/src/emqx_conf_schema.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_enterprise/src/emqx_enterprise.app.src
- apps/emqx_enterprise/src/emqx_enterprise_schema.erl
- apps/emqx_management/src/emqx_mgmt_api_configs.erl
- apps/emqx_management/src/emqx_mgmt_api_listeners.erl
- apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
- apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
Part 1/N
The goal is to use atom for all schema fields so there is no need to create atoms when checking configs.
Map fields is another topic, not included in this scope.
> refactor: use atoms for root config fields

- apps/emqx_conf/src/emqx_conf_schema_types.erl
To help dashboard render duration_s better -- so there is no need to provide "milliseconds" unit.
> chore: for dashboad add a 'minimum' attribute for duration_s type

- apps/emqx/include/emqx_release.hrl
EMQX_API_VERSION is no longer in use since 5.2.0
> chore: delete stale macro

- rel/i18n/emqx_conf_schema.hocon
just enhance a doc,
throttled log is for v5.6.0, which is not released yet.
> docs: refine throttled log time_window description

- apps/emqx_audit/test/emqx_audit_api_SUITE.erl
- apps/emqx_utils/src/emqx_utils.app.src
- apps/emqx_utils/src/emqx_utils.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11904
Since headers are usually used for authentication and the headers used for that are very flexible, we redact all headers from logs to avoid leaking anything.
> fix: redact all headers from logs

- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.erl
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_client.erl
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_consumer.erl
- apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_consumer_SUITE.erl
- apps/emqx_conf/src/emqx_conf_schema_types.erl
- apps/emqx_enterprise/src/emqx_enterprise_schema.erl
- changes/ee/feat-12577.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11384
Today, service_account_json config field is an embedded object (map()).
This requires user to embed a JSON object into the config file instead of embedding it as a string.
We should support binary() type as input, but keep supporting map() for backward compatibility.
> feat(gcp_pubsub_bridges): make service account json a binary

- apps/emqx_prometheus/src/emqx_prometheus.app.src
- apps/emqx_prometheus/src/emqx_prometheus.erl
- changes/ce/fix-12606.en.md
Fixes [EMQX-11914](https://emqx.atlassian.net/browse/EMQX-11914)
Fixes #12603 
The prom data of `emqx_cert_expiry_at` will be `0` for non-existed cert.
> fix(prom): api crash when tls cert file non existed

- apps/emqx_ldap/src/emqx_ldap.erl
- apps/emqx_ldap/src/emqx_ldap_bind_worker.erl
- changes/ee/fix-12610.en.md
Fixes [EMQX-11916](https://emqx.atlassian.net/browse/EMQX-11916)
> fix(ldap): fixed that the connection to the LDAP connector could be disconnected after a period of time

- apps/emqx/rebar.config
- apps/emqx/test/emqx_cth_cluster.erl
- apps/emqx/test/emqx_cth_peer.erl
- apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_impl_producer_SUITE.erl
- apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
- apps/emqx_conf/test/emqx_conf_app_SUITE.erl
- apps/emqx_plugins/test/emqx_plugins_SUITE.erl
- apps/emqx_utils/src/emqx_utils_fs.erl
- apps/emqx_utils/test/emqx_utils_fs_SUITE.erl
- mix.exs
- rebar.config
Running initial mnesia boot phase as part of ekka startup should not be required anymore since #12508 was merged. However, it's important to have in mind that the order of table management operations is now wildly different from what it was before, and that could in theory break some well-hidden implicit assumptions.
> refactor: bump ekka to 0.19.0 w/o mnesia boot phase

- apps/emqx/src/emqx_listeners.erl
- apps/emqx/test/emqx_listeners_SUITE.erl
Fixes https://emqx.atlassian.net/browse/EMQX-11829
Log a warning msg when wait time > 9s.
> chore: wait_for cowboy listener release sock when stop_listener

- apps/emqx_retainer/include/emqx_retainer.hrl
- apps/emqx_retainer/src/emqx_retainer.erl
- apps/emqx_retainer/src/emqx_retainer_api.erl
- apps/emqx_retainer/src/emqx_retainer_app.erl
- apps/emqx_retainer/src/emqx_retainer_cli.erl
- apps/emqx_retainer/src/emqx_retainer_dispatcher.erl
- apps/emqx_retainer/src/emqx_retainer_mnesia.erl
- apps/emqx_retainer/src/emqx_retainer_schema.erl
- apps/emqx_retainer/test/emqx_retainer_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_backend_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_cli_SUITE.erl
- apps/emqx_retainer/test/emqx_retainer_dummy.erl
- apps/emqx_telemetry/test/emqx_telemetry_SUITE.erl
- rel/i18n/emqx_retainer_schema.hocon
Fixes [EMQX-11837](https://emqx.atlassian.net/browse/EMQX-11837)
1. removes any direct usages of retainer backends; code is refactored a bit
2. schema is extended to support alternative backend. 
Changing schema is the most challenging part.
For a long time, for retainer backend options, we had the following config
```
backend {
type = built_in_database
storage_type = ram
...
}
```
with the intention to change the type and the set of options for an alternative backend:
```
backend {
type = some_new_backend
new_option = some_value
...
}
```
However, we discouraged this approach many times because it led to inconsistent configurations after the change. When the bootstrap config is again merged with the cluster config, we obtain something like
```
backend {
type = some_new_backend …
```
> Make retainer pluggable

- apps/emqx_durable_storage/src/emqx_ds.erl
Fixes [EMQX-11837](https://emqx.atlassian.net/browse/EMQX-11837)
Update interfaces required for platform retainer (still unused in master), follow up to https://github.com/emqx/emqx/pull/12611
> feat(ds): export types

- apps/emqx/src/emqx_config.erl
- apps/emqx/src/emqx_ds_schema.erl
- apps/emqx/src/emqx_persistent_message.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_schema.erl
- apps/emqx/test/emqx_persistent_messages_SUITE.erl
- changes/ce/fix-12562.en.md
- rel/i18n/emqx_ds_schema.hocon
- rel/i18n/emqx_schema.hocon
- scripts/spellcheck/dicts/emqx.txt
Fixes https://emqx.atlassian.net/browse/EMQX-11862
- Reduce configuration nesting 
- Allow to change storage layout
- Add dynamic dispatching of the DS configuration handler 
> Refactor schema for the durable storage

- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- apps/emqx_utils/src/emqx_utils_calendar.erl
- changes/ce/fix-12632.en.md
Fixes [EMQX-11929](https://emqx.atlassian.net/browse/EMQX-11929)
Only fixes leap year bug.
Q: Should issues with unchecked boundary values keep existing behavior bug-to-bug?
> fix(calendar): leap year time to unix timestamp

- .github/workflows/build_packages.yaml
Fixes an issue introduced when we moved to new major version of upload/download artifact actions.
- failing build: https://github.com/emqx/emqx/actions/runs/8144379104/job/22260407298
- successful build: https://github.com/emqx/emqx/actions/runs/8145249625/job/22262287678
> ci: fix sha256 task in build packages

- apps/emqx/src/emqx_connection.erl
- apps/emqx/src/emqx_logger_textfmt.erl
- apps/emqx/src/emqx_ws_connection.erl
- changes/ce/feat-12641.en.md
Fixes EMQX-11907
Reorder log fields.
`tag` > `clientid` > `msg` > `peername` > `username` > `topic` > [Other Fields]
> 0304 improve text log formatter

- apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl
- apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_consumer_SUITE.erl
Checks that, if a migrated bridge originally has a `topic_mapping` and is later updated with V2 APIs (without topic mapping in the input), then the new V2 `topic` field prevails.
> test(gcp_pubsub_consumer): add test case for updating topic when there is a topic mapping

- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- apps/emqx_utils/src/emqx_utils_calendar.erl
- changes/ce/fix-12646.en.md
> fix(rule_func): time zone shift at wrong precision

- apps/emqx/src/emqx_channel.erl
- apps/emqx/src/emqx_inflight.erl
- apps/emqx/src/emqx_mqueue.erl
- apps/emqx/src/emqx_session.erl
- apps/emqx/src/emqx_session_mem.erl
- apps/emqx/test/emqx_inflight_SUITE.erl
- apps/emqx/test/emqx_mqueue_SUITE.erl
- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_management/src/emqx_mgmt.erl
- apps/emqx_management/src/emqx_mgmt_api.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- changes/ce/feat-12561.en.md
- rel/i18n/emqx_mgmt_api_clients.hocon
Fixes EMQX-11861
NOTE: session_mem only implementation, persistent_session is planned to be addressed in a separate PR.
> feat: add client mqueue/inflight messages API

- apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
- changes/ce/fix-12657.en.md
- mix.exs
- rebar.config
This PR upgrades the rulesql library to allow using expressions as array literal elements in the rule engine SQL like language. 
Fixes:
https://github.com/emqx/emqx/issues/12465
https://emqx.atlassian.net/browse/EMQX-11953
> fix(rule SQL): allow expressions as array items

- apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.hrl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
- apps/emqx_durable_storage/src/proto/emqx_ds_proto_v4.erl
- apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
Part of https://emqx.atlassian.net/browse/EMQX-11841
> feat(ds): implement `get_delete_streams`, `make_delete_iterator` and `delete_next` callbacks for builtin storage

- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- changes/ce/feat-12671.en.md
The added `unescape` function unescapes escape sequences, transforming them back to their represented characters. The following escape sequences are supported:
- Standard C escape sequences:
- `\n` for newline (LF)
- `\t` for horizontal tab (HT)
- `\r` for carriage return (CR)
- `\b` for backspace (BS)
- `\f` for formfeed (FF)
- `\v` for vertical tab (VT)
- `\'` for single quote (')
- `\"` for double quote (")
- `\\` for backslash (\)
- `\?` for question mark (?)
- `\a` for alert (bell, BEL)
- Hexadecimal escape codes:
- `\xH...` where `H...` is one or more hexadecimal digits (0-9, A-F, a-f), allowing for the encoding of arbitrary utf32 characters.
If an escape sequence is not recognized, or if the hexadecimal escape does not form a valid Unicode character, the function generates an …
> feat(rule engine SQL): add an `unescape` function

- apps/emqx_management/include/emqx_mgmt.hrl
- apps/emqx_management/src/emqx_mgmt_api.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
The /2 APIs from `base64` module are not available in otp 25
Fixes and issue local to release-56 (not released yet)
> fix(mgmt): avoid using base64:decode/2 and encode/2

- apps/emqx/include/asserts.hrl
- apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
- apps/emqx/src/emqx_persistent_session_ds.erl
- apps/emqx/src/emqx_rpc.erl
- apps/emqx/test/emqx_common_test_helpers.erl
- apps/emqx_durable_storage/src/emqx_ds.erl
- apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
- apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
- apps/emqx_durable_storage/src/proto/emqx_ds_proto_v4.erl
- apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
- apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl
Fixes [EMQX-11901](https://emqx.atlassian.net/browse/EMQX-11901).
Release version: v5.6.0
Introduce error classes in critical API functions. For now, only recoverable / unrecoverable errors are introduced. Use them to decide when it's possible to retry session replays.
> feat(sessds): handle recoverable errors during replay

- apps/emqx_rule_engine/src/emqx_rule_funcs.erl
- apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
- apps/emqx_utils/src/emqx_utils_calendar.erl
- changes/ce/fix-12668.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11929
Port changes from https://github.com/emqx/emqx-enterprise/pull/1982.
> fix: port the changes for date_to_unix_ts SQL fun from 4.4

- apps/emqx/src/emqx_cpu_sup_worker.erl
- apps/emqx/src/emqx_os_mon.erl
- apps/emqx/src/emqx_sys_mon.erl
- apps/emqx/src/emqx_sys_sup.erl
- apps/emqx/src/emqx_vm.erl
- apps/emqx/test/emqx_os_mon_SUITE.erl
- apps/emqx/test/emqx_vm_SUITE.erl
- apps/emqx_management/src/emqx_mgmt.erl
- changes/ce/fix-12663.en.md
Fixes [https://emqx.atlassian.net/browse/EMQX-11897](https://emqx.atlassian.net/browse/EMQX-11897)
> fix(vm): cpu usage/idle handled by single worker

- bin/emqx
- dev
Fixes [EMQX-10893](https://emqx.atlassian.net/browse/EMQX-10893)
Prior to this change, cluster.hocon was not loaded to generate app.\<time>.config,
because it might change after boot.
This behavior lead to an issue for logging behaviour since logger has to be configured before the node boot.
> 0308 load cluster hocon to generate app.config

- apps/emqx_dashboard/include/emqx_dashboard.hrl
- apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
- apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
- changes/ce/feat-12670.en.md
Fixes [https://emqx.atlassian.net/browse/EMQX-11994](https://emqx.atlassian.net/browse/EMQX-11994)
> feat(api): field `shared_subscriptions` in endpoint `/monitor_current`

- apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl
- changes/ee/fix-12681.en.md
Fixes:
https://emqx.atlassian.net/browse/EMQX-11987
> fix: redact secrets from RocketMQ debug log

- apps/emqx_bridge_hstreamdb/src/emqx_bridge_hstreamdb.erl
This PR restricts a few HStreamDB bridge/action parameters from being any integer to being integers greater than 0. Lower values than 1 for these parameters resulted in runtime errors.
I don't think a change log entry is necessary for this PR as the changed config parameters did not exist in the previous release.
Fixes:
https://emqx.atlassian.net/browse/EMQX-11939
- [] Created PR to …
> fix(HStreamDB bridge/action): restrict configuration parameters

- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl
- changes/ee/fix-12678.en.md
Fixes:
https://emqx.atlassian.net/browse/EMQX-11934
> fix: return error reason from dynamo connector status check

- apps/emqx/rebar.config
- changes/ce/feat-12700.en.md
- mix.exs
- rebar.config
hocon 0.42.1 allows to use "b" or "B" (byte) unit in bytesize fields.
hocon PR: https://github.com/emqx/hocon/pull/292
Fixes EMQX-11973
> chore: upgrade hocon to 0.42.1

- apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.erl
Make sure that the Amazon Kinesis action has the same batch size restriction as the Amazon Kinesis bridge.
Fixes:
https://emqx.atlassian.net/browse/EMQX-11983
I don't think a change log entry is needed because the fixed code has not been released.
- …
> fix(Amazon Kinesis Action): batch size restriction

- apps/emqx_bridge/src/emqx_bridge_api.erl
- apps/emqx_bridge/src/emqx_bridge_v2_api.erl
- apps/emqx_connector/src/emqx_connector_api.erl
- changes/ce/fix-12696.en.md
Fixes https://emqx.atlassian.net/browse/EMQX-11999
Although the frontend doesn't send `enable` when creating a bridge/action/connector, the default value in the schema is `true`, so when attempting to fetch it from the raw config we should adhere to that default.
> fix(bridges): fix default value for `enable` when attempting operations

- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl
- apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector_client.erl
- apps/emqx_bridge_dynamo/test/emqx_bridge_dynamo_SUITE.erl
The DynamoDB connector status checks takes very long when the server is unavailable which makes the resource manager blocked for a long time. This causes calls to update the Bridge config with the Bridge V1 API fail due to a timeout when it calls the resource manager to remove the channel.
A better fix would be to change the resource manager so that the status check cannot block it for a long time. However, this is more complicated so it needs to be done in a later commit. A new ticket has been created for this task https://emqx.atlassian.net/browse/EMQX-12015 .
Fixes:
https://emqx.atlassian.net/browse/EMQX-11984
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are …
> fix: DynamoDB connector status check takes too long

- .github/workflows/build_and_push_docker_images.yaml
`docker push` does not work reliably when multi arch image is loaded via buildx.
Here we just re-run the same buildx command with push enabled after tests. Since everything is cached, second run is very fast.
> ci(docker): invoke buildx again to push multiarch images

- apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src
- apps/emqx_opentelemetry/src/emqx_otel_metrics.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12040
```
2024-03-19T01:51:52.161276+00:00 [error] crasher: initial call: emqx_otel_metrics:init/1, pid: <0.4962.0>, registered_name: emqx_otel_metrics, error: {badarg,[{erlang,list_to_existing_atom,["cpu.use"],[{error_info,#{module => erl_erts_errors}}]},{emqx_otel_metrics,normalize_name,1,[{file,"emqx_otel_metrics.erl"},{line,258}]},{emqx_otel_metrics,'-create_metric_views/0-fun-0-',1,[{file,"emqx_otel_metrics.erl"},{line,115}]},{lists,map,2,[{file,"lists.erl"},{line,1315}]},{emqx_otel_metrics,create_metric_views,0,[{file,"emqx_otel_metrics.erl"},{line,115}]},{emqx_otel_metrics,handle_continue,2,[{file,"emqx_otel_metrics.erl"},{line,53}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,1123}]},{gen_server,lo …
```
> fix: otel metrics create view crash

- apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
- apps/emqx_management/src/emqx_mgmt_api.erl
- apps/emqx_management/src/emqx_mgmt_api_clients.erl
- apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
- apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
- changes/ce/feat-12719.en.md
- mix.exs
- rebar.config
> Support multiple clientid/username Qs params in clients API
