go
=> fix go script

src/emqttd_vm.erl
=> get_system_info

.travis.yml
See http://docs.travis-ci.com/user/migrating-from-legacy/ for details.
=> Update travis to use new infrastructure

rel/files/emqttd.cmd, rel/files/start_erl.cmd
=> plugins cmd space in filename

src/emqttd_pubsub.erl, src/emqttd_router.erl
Changes:
- topic table changed to mqtt_topic
- dispatch/2 exported for rpc call
=> Fixing issues in cluster mode.

docs/source/cluster.rst
=> Fixed a typo

src/emqttd_pmon.erl
=> Copyright (c) 2016-2017

Makefile, src/emqttd_app.erl, src/emqttd_ws_client_sup.erl
=> Add lager syslog

priv/emq.schema, src/emqttd_ws_client.erl, test/emqttd_SUITE.erl
1.syslog handlers emqttd
2.fix issue #963
=> V2.1.0-rc.2

src/emqttd_cli_config.erl
=> Fix string:split undefined issue

src/emqttd_session.erl
=> Fix issue #1216

src/emqttd_session.erl
Should be an `info` level log.
=> #1590 error log when change CleanSession

priv/emq.schema
I assume that this fix should be merged into master branch before emqtt v2.3.11 release .
=> fix bugs about rest api which getting config lists cause errors

src/emqx_mqueue.erl
This is a minor update of the module doc which I notice a bit outdated when reading the code.
It is based on my superficial understanding of the code logic which of course likely to be inaccurate.
Please help to clarify if anything should is not clear enough.
=> Update & clarify module doc for emqx_mqueue.erl

src/emqx_connection.erl, test/emqx_SUITE.erl
=> Fix issue#1811

Makefile, etc/emqx.conf, priv/emqx.schema, src/emqx_connection.erl, src/emqx_keepalive.erl, src/emqx_protocol.erl, src/emqx_ws_connection.erl, test/emqx_net_SUITE.erl
=> Revert "Calculate the 1.5 keep alive time exactly"

priv/emqx.schema, src/emqx_protocol.erl, src/emqx_session.erl, test/emqx_mock_client.erl, test/emqx_sm_SUITE.erl
https://github.com/emqx/emqx/issues/1833
https://github.com/emqx/emqx/issues/1834
=> Fix issue#1833 and #1834

etc/emqx.conf
https://github.com/emqx/emqx/issues/1835
=> Fix wrong description of max_alias

src/emqx_tracer.erl
This PR added an option `level` to the tracer CLI. See https://github.com/emqx/emqx-management/pull/9
=> Improve CLI for log tracer

priv/emqx.schema, src/emqx_app.erl, src/emqx_logger.erl
For CLI controlling the log level, see https://github.com/emqx/emqx-management/pull/12
=> Add CLI for log level

src/emqx_access_rule.erl, src/emqx_acl_internal.erl, src/emqx_banned.erl, test/emqx_access_SUITE.erl
More: https://github.com/emqx/emqx/issues/1983
=> Record logs for malformed acl configuration file and rules

src/emqx_connection.erl
Rename 'publish_limit' to 'pub_limit'
'try ... of ... catch' to replace 'case catch'
=> Improve the emqx_connection module

Makefile, src/emqx_connection.erl, src/emqx_pd.erl, test/emqx_cm_SUITE.erl, test/emqx_pd_SUITE.erl, test/emqx_sm_SUITE.erl
Add utility functions for erlang process dictionary
Add test cases for emqx_pd
=> Add the 'emqx_pd' module

src/emqx_cli.erl
Add format output for test print in the 'emqx_cli'  module
=> Add format output for test print

src/emqx_client.erl
Prior to this fix, we would get the following crash if we connected to
another emqx broker but got refused because of wrong username or password.
```shell
➜  ./bin/emqx_ctl bridges start aws
RPC to emqx2@127.0.0.1 error: {{{shutdown,tcp_closed},
{gen_statem,call,
[<10637.1997.0>,connect,infinity]}},
{gen_server,call,
[emqx_bridge_aws,start_bridge]}}
```
=> Fix crash if peer closed the connection

src/emqx_kernel_sup.erl, src/emqx_pool.erl, src/emqx_pool_sup.erl, test/emqx_pool_SUITE.erl
- Move 'emqx_pool:start_link/0' to emqx_pool_sup module
- Use the new log macros
- Add more test cases
=> Improve the pool design

src/emqx_client.erl, src/emqx_protocol.erl, src/emqx_session.erl, test/emqx_access_SUITE_data/acl_deny_action.conf, test/emqx_ct_broker_helpers.erl, test/emqx_mod_sup_SUITE.erl, test/emqx_pool_SUITE.erl, test/emqx_protocol_SUITE.erl, test/emqx_sm_SUITE.erl, test/emqx_sys_mon_SUITE.erl, test/emqx_tracer_SUITE.erl
Fix the `EXIT` outputs in Travis CI.
=> Fix the EXIT outputs in Travis CI

src/emqx.erl
=> Revert "Reload config when restarting emqx"

src/emqx_ws_connection.erl
Websocket protocol defines its own ping/pong keep alive mechanism in the
spec. Once connected, either end may send a ping, and must receive a
pong. Cowboy responds to pings with pongs automatically, but if a pong
is received, it does nothing.
A pong should only be received in response to a ping, and it isn't clear
where the pings are originating, but failing to handle the pongs causes
this:
```
2019-02-08 08:15:24.201 [error] mqttjs_526dcabe@10.107.155.142:37778 crasher:
initial call: cowboy_clear:connection_process/5
pid: <0.36.4>
registered_name: []
exception error: no function clause matching
emqx_ws_connection:websocket_handle(pong,
{state,undefined,
undefined,
%% <snip>: trimmed error message
```
This commit adds handlers for ping and pong messages to prevent crashes.
Spec requires a …
=> fix emqx_ws_connection: prevent crashes on pong

src/emqx_shared_sub.erl, src/emqx_topic.erl
- Fix 'drpped' typo
- Add specs for exported functions
- Add 'group()' type in emqx_topic module
=> Fix 'drpped' typo

Makefile, src/emqx_message.erl
- Optimize unset_flag/2
- Add some function specs
- Add emqx_message_SUITE to Makefile
=> Optimize unset_flag/2 and add some specs

Makefile, test/emqx_message_SUITE.erl
Increasing coverage for emqx_message
=> Increase code coverage of emqx_message module

src/emqx_batch.erl, src/emqx_frame.erl, src/emqx_gc.erl, src/emqx_inflight.erl, src/emqx_keepalive.erl, src/emqx_protocol.erl, src/emqx_topic.erl
- Define 'GCS(St)' macro to improve emqx_gc module
- Define 'Inflight(MaxSize, Tree)' macro to improve emqx_inflight module
=> Change some '-type' attrs to '-opaque' and improve emqx_gc, emqx_inflight modules

src/emqx_protocol.erl, src/emqx_session.erl, test/emqx_session_SUITE.erl, test/emqx_shared_sub_SUITE.erl
- Upgrade the emqx_session module to support batch delivery
- Update emqx_protocol:deliver/2 to support batch delivery
- Update some test cases
=> Support batch delivery

etc/emqx.conf, priv/emqx.schema, rebar.config
Prior to this change, there are some config entry which is not parsed
correctly. So if user modify config such as reconnect_interval for
bridge, the new config can not be taken into effect.
=> Fix conf parse bug

priv/emqx.schema, src/emqx_bridge.erl, src/emqx_message.erl
=> Fix issue #2312

Makefile, src/emqx_rpc.erl, test/emqx_rpc_SUITE.erl
=> Modify emqx_rpc

src/emqx_message.erl, src/emqx_protocol.erl, src/emqx_topic.erl, test/emqx_message_SUITE.erl
- Adopt new 'export' style
- Add some functions for rule engine
=> Add some functions for rule engine

src/emqx_alarm_handler.erl, src/emqx_protocol.erl
For the #2307, we improve the authentication parameters, It can use CN/DN of client cert now!
=> Put cn/dn of client cert into credentials

etc/emqx.conf, priv/emqx.schema
Add etcd client certificate configuration
=> Add etcd client certificate configuration

src/emqx_session.erl
For to resolve #2366.
The session process will crash at handling many messages `{dispatch, Topic, Msgs}` in a moment:
```
** Reason for termination ==
** {function_clause,
[{emqx_session,'-maybe_ack_shared/2-fun-0-',
[{message,
<<0,5,133,6,74,242,172,20,244,67,1,0,125,135,5,249>>,
0,<<"some_client_id">>,
#{dup => false,retain => true},
#{allow_publish => true,retained => true,
username => <<"username">>},
<<"topic">>, <<"payload_data_on_there">>,
{1553,636957,269012}},
[]],
[{file,"src/emqx_session.erl"},{line,851}]},
{emqx_session,'-maybe_ack_shared/2-fun-0-',3,
[{file,"src/emqx_session.erl"},{line,852}]},
{lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
{emqx_session,handle_dispatch,2,
[{file,"src/emqx_session.erl"},{line,819}]}, …
```
=> Fix drain the session process mailbox handling error

src/emqx_message.erl, test/emqx_message_SUITE.erl
- Add id/1, topic/1, from/1, payload/1 and timestamp/1 functions
- Improve the test cases
=> Add more functions to read fields of 'message' record

src/emqx_plugins.erl
This is to simplify config templating
=> Allow boolean flag for loaded plugins

src/emqx_session.erl
https://github.com/emqx/emqx/issues/2418
=> Update metrics when session process terminates

etc/emqx.conf, priv/emqx.schema
=> Fix typo round_robbin -> round_robin in emqx.schema

src/emqx_protocol.erl
=> Enable cert_as_username to pass value to username_as_clientid

src/emqx_zone.erl
- Don't reload the zone options for updating persistent_term is
expensive
- Use `{?MODULE, Zone, Key}` as the key to avoid name collision
=> Optimize the emqx_zone module using persistent_term

src/emqx_protocol.erl
Return CONNACK that reason code is 0x9A when the server don't support retain message receive the will message that will retain is 1.
=> Fix retain in will message

src/emqx_ws_connection.erl
=> Revert "Fix websocket bug."

src/emqx_protocol.erl
https://github.com/emqx/emqx/issues/2679
=> Fix the check_subacl bug when enable_acl is set to false

src/emqx_mod_subscription.erl, src/emqx_mqtt_caps.erl, src/emqx_protocol.erl, src/emqx_session.erl, test/emqx_protocol_SUITE.erl
- Add `emqx_session:info/2` for unit tests
- Add `emqx_protocol:set/3` for unit tests
- Fix the `check_sub/3` of emqx_mqtt_caps
=> Add test cases for emqx_protocol module

test/emqx_config_SUITE.erl
Associated PR: https://github.com/emqx/emqx-recon/pull/67
=> Remove redundant code and add test case

src/emqx_ws_connection.erl
Rename `reason` field to `stop_reason`
=> Improve emqx_ws_connection module

src/emqx_connection.erl, src/emqx_frame.erl, src/emqx_ws_connection.erl, test/emqx_frame_SUITE.erl
- Introduce the 'strict_mode' option
- Validate the flags of MQTT header
- Add more test cases
=> Introduce the 'strict_mode' option and validate MQTT header

.travis.yml, Makefile, src/emqx_misc.erl, src/emqx_zone.erl, test/emqx_os_mon_SUITE.erl, test/emqx_stats_SUITE.erl, test/emqx_sys_mon_SUITE.erl, test/emqx_ws_connection_SUITE.erl, test/emqx_zone_SUITE.erl
Add more test cases for emqx_stats, emqx_os_mon and emqx_sys_mon
=> Add more test cases

src/emqx_channel.erl, src/emqx_types.erl
Fix for https://github.com/emqx/emqx/issues/3118
=> Add sockport to ClientInfo

src/emqx_access_control.erl, src/emqx_channel.erl, src/emqx_metrics.erl
- client.connect
- client.connack
- client.connected
- client.authenticate
- client.check_acl
- client.subscribe
- client.unsubscribe
- client.disconnected
=> Add more metrics for client's lifecircle

src/emqx_cm.erl, src/emqx_session.erl
- session.created
- session.resumed
- session.takeovered
- session.discarded
- session.terminated
=> Add metrics for session's lifecircle

rebar.config
- Upgrade esockd to 5.6.1
- Upgrade ekka to 0.7.2
=> Upgrade esockd and ekka deps

src/emqx_connection.erl, src/emqx_packet.erl, test/mqtt_protocol_v5_SUITE.erl
+ Add more test case for mqtt protocol
+ Add check will_qos  when connection
=> Mqtt protocol tests

src/emqx_cm.erl
=> Ignore some discarded exceptions

etc/emqx.conf, priv/emqx.schema, src/emqx_access_control.erl, test/emqx_access_control_SUITE.erl, test/emqx_logger_formatter_SUITE.erl
=> Add an option to allow client bypass auth plugins

src/emqx_connection.erl, src/emqx_ws_connection.erl
change the logs for rate limit pausing to warning level.
=> Warning rate limit pause

priv/emqx.schema, test/mqtt_protocol_v5_SUITE.erl
=> Fix mountpoint data type error

src/emqx_channel.erl, test/emqx_client_SUITE.erl
=> Fix `peer_cert_as_username` option not working

src/emqx_json.erl
Fix the issue https://github.com/emqx/emqx/issues/3287
=> Force utf8 json encoding by default #3287

src/emqx_channel.erl, test/emqx_channel_SUITE.erl, test/mqtt_protocol_v5_SUITE.erl
For fixing: https://github.com/emqx/emqx/issues/3304
=> Remove the CONNACK's `Maximum-QoS` key if it equal to 2

src/emqx_channel.erl, src/emqx_types.erl, test/emqx_channel_SUITE.erl, test/mqtt_protocol_v5_SUITE.erl
Supports broker-to-client topic aliases
=> Supports broker-to-client topic aliases

etc/emqx.conf, include/emqx.hrl, src/emqx_cm_registry.erl, src/emqx_plugins.erl, test/emqx_cm_registry_SUITE.erl, test/emqx_plugins_SUITE.erl
- Remove enable_session_registry configuration item from emqx.conf
- Read new configuration items when plugins is loaded
- Remove version field from plugin information
=> Read new configuration items when plugins is loaded

src/emqx_channel.erl, src/emqx_connection.erl, src/emqx_reason_codes.erl, test/emqx_channel_SUITE.erl
=> Auth packet

src/emqx_listeners.erl, test/emqx_listeners_SUITE.erl
Fix https://github.com/emqx/emqx/issues/3293
=> EMQX failed to start when the listening port was occupied

rebar.config
=> Update jiffy to 1.0.4

src/emqx_cm.erl, src/emqx_cm_registry.erl, src/emqx_mod_acl_internal.erl, test/emqx_acl_cache_SUITE.erl, test/emqx_cm_SUITE.erl, test/emqx_cm_registry_SUITE.erl, test/emqx_modules_SUITE.erl
Reference [Is there need a APIs to empty all ACL caches #3292](https://github.com/emqx/emqx/issues/3292)
=> Fix reload acl module and clean acl caches

src/emqx_channel.erl, src/emqx_types.erl
For fixing: https://github.com/emqx/emqx-auth-http/issues/185
=> Replace peercert with cn/dn feilds in ClientInfo

.github/weekly-digest.yml
chore(weekly-digest): update weekly-digest configure
=> chore(weekly-digest): update weekly-digest configure

src/emqx_cm.erl, test/emqx_cm_SUITE.erl
- Remove the register_channel/1,2 functions
=> fix(connect): fix the race condition when opening session

src/emqx_channel.erl, test/emqx_channel_SUITE.erl
Fix https://github.com/emqx/emqx/issues/3614
=> fix(emqx_channel)

src/emqx_channel.erl, test/emqx_channel_SUITE.erl
Fix https://github.com/emqx/emqx/issues/3614
=> fix(emqx_channel): fix error for properties

src/emqx_logger.erl, src/emqx_tracer.erl, test/emqx_logger_SUITE.erl
https://github.com/emqx/emqx-management/pull/259
=> V4.2 rc.2 logger cli

etc/emqx.conf, priv/emqx.schema
=> Revert "fix(force-shutdown-policy): default to enable force_shutdown_policy"

apps/emqx/src/emqx_mod_topic_metrics.erl, apps/emqx/test/emqx_mod_topic_metrics_SUITE.erl
this PR fixes (partially)  https://github.com/emqx/emqx/issues/3788
=> refactor(metrics): Use modified moving average for topic metrics speed

.gitignore, data/emqx_vars, data/loaded_modules.tmpl, data/loaded_plugins.tmpl
This is a copy from emqx-rel project
=> fix(boot): Add data dir

rebar.config.erl
=> chore(build): remove emqtt deps from test profile

.gitignore, etc/emqx.conf, priv/emqx.schema, test/emqx_limiter_SUITE.erl
For: https://github.com/emqx/emqx-rel/issues/617#issue-754020545
=> Add more SSL configuration

etc/emqx.conf, priv/emqx.schema, test/emqx_limiter_SUITE.erl
=> Add more SSL configurations

apps/emqx_auth_redis/.ci/docker-compose-cluster-tls.yml, apps/emqx_auth_redis/.ci/docker-compose-sentinel.yml, apps/emqx_auth_redis/.ci/redis/redis-tls.conf, apps/emqx_auth_redis/.ci/redis/redis.conf, apps/emqx_auth_redis/.ci/redis/redis.sh, apps/emqx_auth_redis/.ci/redis/sentinel.conf, apps/emqx_auth_redis/test/emqx_auth_redis_SUITE.erl
https://github.com/emqx/emqx-auth-redis/pull/192
=> test(emqx_auth_redis): add test cases for sentinel

apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl
Fixes:
https://github.com/emqx/emqx/issues/3813
https://github.com/emqx/emqx/issues/3813#issuecomment-722242952
add test cases
=> feat(coap): use emqx_access_control:check_acl before pub/sub

apps/emqx_rule_engine/src/emqx_rule_engine_api.erl, apps/emqx_rule_engine/src/emqx_rule_funcs.erl, apps/emqx_rule_engine/src/emqx_rule_maps.erl, apps/emqx_rule_engine/src/emqx_rule_metrics.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_maps_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_metrics_SUITE.erl
Migrate the bug fixes and features for emqx_rule_engine  from enterprise e4.2.3
=> Migrate rule engine code from e4.2.3

.github/workflows/build_packages.yaml
remove unnecessary steps from the workflow for building a package
=> test(CI): update build packages

.github/workflows/build_packages.yaml
=> test(CI): update matrix for build packages

apps/emqx_auth_http/etc/emqx_auth_http.conf, apps/emqx_auth_http/src/emqx_auth_http_cli.erl, apps/emqx_auth_http/test/emqx_auth_http_SUITE.erl, src/emqx_types.erl
=> Revert "feat(auth_http): support for getting websocket cookies"

etc/emqx.conf, priv/emqx.schema, src/emqx_ws_connection.erl
Prevent EMQX from CSWSH (Cross-Site Web-Socket Hijack)
=> feat(emqx_ws_connection): Prevent EMQX from CSWSH

src/emqx_vm.erl, test/emqx_vm_SUITE.erl
The port binary format is no longer compatible in OTP 23
=> chore(emqx_vm): delete stale code

apps/emqx_auth_mnesia/src/emqx_auth_mnesia.erl, apps/emqx_auth_pgsql/etc/emqx_auth_pgsql.conf, apps/emqx_auth_pgsql/priv/emqx_auth_pgsql.schema, apps/emqx_lwm2m/README.md, apps/emqx_prometheus/README.md, sync-apps.sh
These are the updates in plugin repos which are not synced to `dev/v4.3.0`
=> chore(sync-apps): resync plugin apps from their 4.2.6 tag

apps/emqx_coap/src/emqx_coap_ps_resource.erl
This http_uri:decode/1 has been deprecated.
=> refactor(emqx_coap): use url_string module to decode url encoded topic

apps/emqx_auth_redis/rebar.config
Upgrade eredis_cluster to 0.6.4 and eredis to 1.2.2.
see: https://github.com/emqx/eredis/pull/7
=> chore(redis): upgrade eredis_cluster to 0.6.4

apps/emqx_recon/rebar.config, rebar.config, src/emqx_vm.erl
Fixes #3832
recon has the fix in this commit:
https://github.com/ferd/recon/commit/58071e37599a8154a3a32dc282209357cdbafdd9
=> fix emqx_vm allocator info otp 23 compatibility

deploy/docker/docker-entrypoint.sh
remove useless environmental variables
update the key of the environment variable
fix issue #4011
=> fix(docker): fix docker entryponit script

apps/emqx_rule_engine/src/emqx_rule_utils.erl, apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl
=> fix(rulesql): proc_sql_param_str incorrect with apostrophes #4135

apps/emqx_rule_engine/src/emqx_rule_utils.erl, apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl
https://github.com/emqx/emqx/issues/4148
=> fix(rulesql): proc Cassandra cql with apostrophes failed

src/emqx_access_rule.erl, src/emqx_connection.erl, src/emqx_os_mon.erl, test/emqx_connection_SUITE.erl
=> Chore sytle fix elvis

src/emqx_shared_sub.erl
=> improve(shared-sub): Randomise the startpoint for round-robin

apps/emqx_auth_http/src/emqx_auth_http_app.erl, apps/emqx_auth_mnesia/src/emqx_acl_mnesia_api.erl, apps/emqx_auth_mnesia/src/emqx_auth_mnesia_cli.erl
=> fix dialyzer warnings

apps/emqx_lwm2m/etc/emqx_lwm2m.conf, apps/emqx_lwm2m/priv/emqx_lwm2m.schema, apps/emqx_lwm2m/src/emqx_lwm2m_coap_server.erl, apps/emqx_lwm2m/src/emqx_lwm2m_protocol.erl
Fixes https://github.com/emqx/emqx-lwm2m/issues/90
Add configurations to always publish messages for UPDATE LwM2M messages.
=> feat(lwm2m): always publish update message

apps/emqx_auth_jwt/etc/emqx_auth_jwt.conf
=> chore(jwt): clearer explanation for verify_claims

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> docs: format contributing

elvis-check.sh
=> chore(elvis): add filter for elvis

docker.mk
Fix https://github.com/emqx/emqx-rel/issues/643
=> build(docker): fix docker build error when image name neq emqx

.github/workflows/run_test_cases.yaml, Makefile, apps/emqx_exhook/src/emqx_exhook.app.src, rebar.config.erl
=> chore(ci): run eunit test in github action

Makefile, scripts/fail-on-old-otp-version.escript
=> chore(build): Fail fast on old version OTP

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_actions.erl
=> fix(emqx_bridge_mqtt_actions): string -> password

src/emqx_channel.erl
=> fix(emqx_channel): fix bug when publish deny

apps/emqx_management/src/emqx_mgmt_http.erl, lib-ce/emqx_modules/src/emqx_modules_app.erl, rebar.config.erl
=> chore(emqx_modules): enable-emqx-modules-by-default

bin/emqx, bin/emqx_ctl, data/emqx_vars
Fixes https://github.com/emqx/emqx/issues/4243
The regression test should verify this new flag will not break anything.
Manual test is required to verify it actually fixes the tracking issue as we do not have macos in our test environments.
=> fix(scripts): Ensure ekka in ERL_LIBS for remote nodes

bin/emqx, etc/emqx.conf, priv/emqx.schema
Log to file by default.
Log to console when start in console or foreground mode
Log to file for package builds
=> chore(config): Change default log_to config

apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
No we lack of integrated tests for REST apis.
=> fix(rule-engin-api): transform input config for update requests

.github/workflows/check_deps_integrity.yaml, apps/emqx_sasl/rebar.config, apps/emqx_telemetry/rebar.config, rebar.config, rebar.config.erl, scripts/check-deps-integrity.escript
Use the same version as for enterprise.
=> chore(deps): upgrade replayq to version 0.3.2

Makefile, rebar.config.erl, scripts/get-dashboard.sh
=> chore(build): use only mark file to tell apart ce ee

.github/workflows/build_packages.yaml, pkg-vsn.sh, scripts/elvis-check.sh, scripts/ensure-rebar3.sh, scripts/get-dashboard.sh, scripts/shellcheck.sh, scripts/start-two-nodes-in-docker.sh
=> build(CI): fix build error on windows in github actions

.github/workflows/build_packages.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/run_cts_tests.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_test_cases.yaml
=> chore(CI): update events that trigger workflows

.github/workflows/run_dialyzer.yaml
=> test(.github): run dialyzer on pull request

apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> fix(mgmt): typo in ifdef macro

.gitignore, deploy/docker/Dockerfile, scripts/get-dashboard.sh
=> build(dashboard): get dashboard script support enterprise

include/emqx_release.hrl, pkg-vsn.sh, rebar.config.erl, src/emqx.app.src, src/emqx_app.erl
This Pr has no tracking issue.
=> Fix versioning

Makefile, scripts/get-dashboard.sh
=> chore(build): Use different env variable for dashboard version

.github/workflows/build_packages.yaml, .github/workflows/git_sync.yaml
=> chore(CI): add git sync workflow

.github/workflows/run_test_cases.yaml, lib-extra/emqx_plugin_template, lib-extra/plugins, rebar.config.erl
check also https://github.com/emqx/emqx-plugin-template/pull/98
=> feat(rebar.config.erl): allow community plugins

.ci/build_packages/tests.sh, .github/workflows/build_slim_packages.yaml, include/emqx_release.hrl
=> chore(script): remove the prefix of pkg-vsn.sh

Makefile, build, scripts/git-hook-pre-push.sh, scripts/git-hooks-init.sh, src/emqx.app.src, src/emqx.app.src.script
=> Githook and EMQX_DESC

include/emqx_release.hrl, pkg-vsn.sh, rebar.config.erl, src/emqx_app.erl
=> chore(build) add more enterprise build support

.github/workflows/run_test_cases.yaml, Makefile, lib-extra/README.md, lib-extra/plugins
=> Chore makefile clean target

bin/emqx, data/emqx_vars, data/loaded_plugins.tmpl, lib-ce/emqx_dashboard/src/emqx_dashboard.erl, rebar.config.erl, vars/vars-cloud.config, vars/vars-edge.config
=> chore(build): add more enterprise build support

Makefile
=> Chore build update rebar3 version

apps/emqx_exhook/docs/design-cn.md, apps/emqx_exhook/priv/protos/exhook.proto, apps/emqx_exhook/rebar.config, apps/emqx_exhook/src/emqx_exhook_app.erl, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/src/emqx_exhook_server.erl, apps/emqx_exproto/rebar.config, apps/emqx_exproto/src/emqx_exproto_conn.erl
=> Enhance the emqx-exhook and emqx-exporoto application

etc/emqx.conf
=> chore(configuration): fix the configuration example in the comment

.gitignore, etc/emqx.conf, rebar.config.erl, scripts/split-config.escript
=> Feat config segmentation

rebar.config.erl
=> chore(test): Add snabbkaffe

Makefile, rebar.config, rebar.config.erl
=> chore(test): enable cover only when necessary

rebar.config.erl
=> chore(build): Pin a tag of relup_helper plugin

apps/emqx_rule_engine/include/rule_engine.hrl, apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_engine_api.erl, apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl, apps/emqx_rule_engine/src/emqx_rule_registry.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
=> feat(rule-engine): list rule support order by timestamp

rebar.config, rebar.config.erl
=> feat(observer_cli): Add observer_cli

src/emqx.appup.src, src/emqx_congestion.erl, src/emqx_connection.erl, src/emqx_frame.erl, test/emqx_frame_SUITE.erl
=> Too frequently alarm

Makefile, scripts/git-hook-pre-push.sh, scripts/git-hooks-init.sh
=> chore(CI): fix build error on windows

apps/emqx_telemetry/src/emqx_telemetry.erl
=> fi(telemetry): get release version, not eqmx app version

etc/emqx.conf
=> fix(subprotocol): fix bad configuration item name for subprotocol

.ci/apps_tests/docker-compose.yaml, .ci/compatibility_tests/docker-compose-mysql.yaml
=> chore(CI): update docker compose file for mysql

apps/emqx_web_hook/src/emqx_web_hook.erl, apps/emqx_web_hook/test/http_server.erl
=> fix(log): fix web hook print error

Windows.md, apps/emqx_management/src/emqx_mgmt_cli.erl, bin/emqx.cmd
=> Env for windows cmd

etc/emqx.conf, priv/emqx.schema
=> fix(config): delete needless config

etc/emqx.conf
=> fix(conf): fix split modules conf error

test/emqx_ws_connection_SUITE.erl
Add test cases for:
https://github.com/emqx/emqx/pull/4099
https://github.com/emqx/emqx/pull/4327
=> fix(test): add testcases for ws subprotocols

apps/emqx_auth_mnesia/src/emqx_acl_mnesia_cli.erl, apps/emqx_auth_mnesia/src/emqx_auth_mnesia_cli.erl
+ change the contents of the command prompt from del to delete, keeping it in the same style as other commands
+ both support the delete and del commands
=> chore(auth-mnesia): update cli

apps/emqx_management/test/emqx_mgmt_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
=> fix(test): Ensure emqx_modules loaded for emqx_management test

deploy/charts/emqx/templates/StatefulSet.yaml
Fixes [Issue](https://github.com/emqx/emqx-rel/issues/648)
=> Move pullSecrets up to pod level

src/emqx_acl_cache.erl, test/emqx_acl_cache_SUITE.erl
Docs are not added yet, will be discussed in followup PRs for restapi / cli changes.
=> feat: acl cache discard

.ci/apps_tests/docker-compose.yaml, .ci/build_packages/Dockerfile, .ci/compatibility_tests/docker-compose-ldap.yaml, .ci/compatibility_tests/docker-compose-mongo-tls.yaml, .ci/compatibility_tests/docker-compose-mongo.yaml, .ci/compatibility_tests/docker-compose-mysql-tls.yaml, .ci/compatibility_tests/docker-compose-mysql.yaml, .ci/compatibility_tests/docker-compose-pgsql-tls.yaml, .ci/compatibility_tests/docker-compose-pgsql.yaml, .ci/compatibility_tests/docker-compose-redis-cluster-tls.yaml, .ci/compatibility_tests/docker-compose-redis-cluster.yaml, .ci/compatibility_tests/docker-compose-redis-sentinel.yaml, .ci/compatibility_tests/docker-compose-redis-single-tls.yaml, .ci/compatibility_tests/docker-compose-redis-single.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_test_cases.yaml, deploy/docker/Dockerfile, docker.mk
=> chore(build): bump to OTP-23.2.7

rebar.config.erl
if EMQX_COMPILE_SECRET_FILE is set, debug_info of beam files would be
encrypted.
EMQX_COMPILE_SECRET_FILE contains secret string.
=> feat(compile): support debug_info encryption

apps/emqx_rule_engine/include/rule_engine.hrl
=> fix(rule-engine): add 'undefined' type for create time

apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_apps.erl, apps/emqx_management/src/emqx_mgmt_api_banned.erl, apps/emqx_management/src/emqx_mgmt_api_brokers.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_data.erl, apps/emqx_management/src/emqx_mgmt_api_listeners.erl, apps/emqx_management/src/emqx_mgmt_api_metrics.erl, apps/emqx_management/src/emqx_mgmt_api_nodes.erl, apps/emqx_management/src/emqx_mgmt_api_plugins.erl, apps/emqx_management/src/emqx_mgmt_api_pubsub.erl, apps/emqx_management/src/emqx_mgmt_api_routes.erl, apps/emqx_management/src/emqx_mgmt_api_stats.erl, apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl, apps/emqx_management/src/emqx_mgmt_http.erl
=> style(api): imports removed

test/emqx_ws_connection_SUITE.erl
Associated PR: https://github.com/emqx/emqx/pull/4000
=> chore(test-cswsh): add test case for cswsh

src/emqx_channel.erl, test/emqx_channel_SUITE.erl
Fixes https://github.com/emqx/emqx/issues/4200
=> fix(channel): fix the wrong acl check order

apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> fix(backup): fix bridge-mqtt import problem

.github/workflows/run_test_cases.yaml, Makefile, bin/emqx, lib-extra/plugins, rebar.config.erl
=> Elixir plugin

src/emqx_app.erl, src/emqx_listeners.erl, src/emqx_tls_lib.erl
=> Feat no tlsv1.3 for otp 22

apps/emqx_auth_mnesia/test/emqx_acl_mnesia_SUITE.erl, apps/emqx_auth_mnesia/test/emqx_auth_mnesia_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_SUITE.erl, lib-ce/emqx_dashboard/test/emqx_dashboard_SUITE.erl
ensure emqx_modues loaded before emqx_management in test cases
=> fix(test cases): fix test case error

src/emqx.erl
=> feat(emqx.erl): Add a help function to load debug secret

Makefile, README.md, scripts/find-apps.sh, scripts/find-suites.sh
=> chore(test): make app-ct run easier

rebar.config.erl
=> chore(build): always include debug_info

apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_acl.erl, apps/emqx_management/src/emqx_mgmt_cli.erl, rebar.config
references https://github.com/emqx/emqx/issues/4215
=> feat(acl): CLI and REST handlers for removing acl cache

apps/emqx_lwm2m/src/emqx_lwm2m_coap_server.erl
These functions are used by enterprise.
=> fix(lwm2m): export functions for starting and stopping listeners

README.md, lib-extra/README.md, scripts/find-apps.sh
=> Docs update readme

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_actions.erl, apps/emqx_plugin_libs/src/emqx_plugin_libs_ssl.erl, apps/emqx_web_hook/src/emqx_web_hook_actions.erl
=> Fix type inf cert upload path

apps/emqx_exhook/src/emqx_exhook_cli.erl, elvis.config, scripts/elvis-check.sh
=> Upgrade elvis version

apps/emqx_plugin_libs/src/emqx_plugin_libs_ssl.erl
=> feat(ssl): Export a lib function to save key/cert file

scripts/find-apps.sh
=> chore(build): exclude broken symlinks in find-apps.sh

etc/emqx.conf
Adds Documentation for CSWSH in config.
=> docs(config): CSWSH(Cross-Site Web-Socket Hijack) Documentation

apps/emqx_management/include/emqx_mgmt.hrl, apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> fix(import): add bridge_mqtt compatible <4.2.x

.github/workflows/build_packages.yaml, .github/workflows/run_fvt_tests.yaml, deploy/packages/rpm/Makefile
=> chore(CI): fix windows build error

bin/emqx, bin/emqx_ctl
=> chore(boot): Do not ps -ef inspect node name

apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> fix(import): fix import error

bin/emqx_ctl
=> chore(script): make emqx_ctl work with docker entrypoint

src/emqx_connection.erl, src/emqx_ws_connection.erl, test/emqx_connection_SUITE.erl
=> fix(ping): deny pingreq when mqtt not connected

apps/emqx_rule_engine/src/emqx_rule_funcs.erl, src/emqx_guid.erl, src/emqx_misc.erl, src/emqx_tracer.erl
=> chore(rule-engine): compatible with the lower case hash string

apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> fix(mgmt): expose 2 functions to ce

.ci/fvt_tests/docker-compose.yaml, .ci/fvt_tests/scripts/pytest.sh, .github/workflows/run_fvt_tests.yaml
=> chore(ci): inspect docker logs after pytest failure

.github/workflows/run_fvt_tests.yaml
=> chore(ci): Ensure exit 1 at test failure

bin/emqx, bin/emqx_ctl
=> chore(scripts): ensure no space in cookie

.ci/build_packages/tests.sh
echo exit 1 when emqx start failed
=> chore(CI): update test script on after build packages

apps/emqx_sn/include/emqx_sn.hrl, apps/emqx_sn/src/emqx_sn_gateway.erl, apps/emqx_sn/test/emqx_sn_protocol_SUITE.erl, src/emqx_channel.erl, src/emqx_session.erl
Fixes https://github.com/emqx/emqx/issues/4434
=> fix(mqtt-sn): sleep mode not working #4434

src/emqx_channel.erl
=> fix(channel): fix `keep-alive` problem

rebar.config, rebar.config.erl, src/emqx_connection.erl, test/emqx_connection_SUITE.erl
Fixes #4399 
Also optimise `emqx_connection` main receive loop performance.
=> `emqx_connection` oom quick kill

apps/emqx_coap/README.md, apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl, apps/emqx_coap/src/emqx_coap_pubsub_resource.erl, apps/emqx_coap/src/emqx_coap_resource.erl, apps/emqx_coap/test/emqx_coap_SUITE.erl
https://github.com/emqx/emqx/issues/4456
=> fix(emqx_coap): return error code forbidden on ACL denied #4456

.ci/docker-compose-file/docker-compose-ldap-tcp.yaml, .ci/docker-compose-file/docker-compose-mongo-tcp.yaml, .ci/docker-compose-file/docker-compose-mongo-tls.yaml, .ci/docker-compose-file/docker-compose-mysql-tcp.yaml, .ci/docker-compose-file/docker-compose-mysql-tls.yaml, .ci/docker-compose-file/docker-compose-pgsql-tcp.yaml, .ci/docker-compose-file/docker-compose-pgsql-tls.yaml, .ci/docker-compose-file/docker-compose-redis-cluster-tcp.yaml, .ci/docker-compose-file/docker-compose-redis-cluster-tls.yaml, .ci/docker-compose-file/docker-compose-redis-sentinel-tcp.yaml, .ci/docker-compose-file/docker-compose-redis-single-tcp.yaml, .ci/docker-compose-file/docker-compose-redis-single-tls.yaml, .github/workflows/run_cts_tests.yaml, .github/workflows/run_test_cases.yaml
=> chore(CI): add ssl user for mysql

bin/emqx, rebar.config
=> refactor(bin/emqx): use cuttlefish `get` to get values from .conf

bin/emqx
=> chore(bin/emqx): Fix typo

priv/emqx.schema, rebar.config
=> refactor(emqx.schema): use override_env to support alternative env

apps/emqx_exhook/include/emqx_exhook.hrl, apps/emqx_exhook/src/emqx_exhook_app.erl, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/src/emqx_exhook_server.erl
=> refactor(exhook): remove hook registray

apps/emqx_management/src/emqx_mgmt.erl
=> fix(mgmt): exclude telemetry related lines from enterprise

src/emqx.appup.src, src/emqx_channel.erl, src/emqx_session.erl
Please merge this along with:
https://github.com/emqx/emqx-sn/pull/181
=> Fix MQTT-SN sleep mode not working - e4.2.6

apps/emqx_auth_mnesia/src/emqx_acl_mnesia.erl, apps/emqx_auth_mnesia/src/emqx_acl_mnesia_cli.erl, apps/emqx_auth_mnesia/test/emqx_acl_mnesia_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_data.erl, apps/emqx_management/src/emqx_mgmt_cli.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.1.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.2.json
=> fix(emqx_auth_mnesia): add missing combinations of permissions

apps/emqx_coap/test/emqx_coap_pubsub_SUITE.erl
=> test(coap): take a nap for cast operation

README-JP.md
https://github.com/emqx/emqx/pull/4492
=> docs(README-JP): sync jp readme

apps/emqx_auth_mongo/rebar.config, apps/emqx_auth_redis/rebar.config, rebar.config
=> Pin poolboy

apps/emqx_auth_mongo/priv/emqx_auth_mongo.schema, apps/emqx_auth_mysql/priv/emqx_auth_mysql.schema, apps/emqx_auth_pgsql/priv/emqx_auth_pgsql.schema, apps/emqx_auth_redis/priv/emqx_auth_redis.schema, test/emqx_sys_mon_SUITE.erl
=> fix(flase): false

Makefile
=> chore(dashboard): upgrade front-page version

apps/emqx_sn/src/emqx_sn_frame.erl, apps/emqx_sn/src/emqx_sn_gateway.erl, apps/emqx_sn/test/emqx_sn_protocol_SUITE.erl
Fixes https://github.com/emqx/emqx/issues/4506
=> Handle disconnect msg in asleep state

bin/emqx, rebar.config, src/emqx_plugins.erl
https://github.com/emqx/emqx/issues/4459
=> print override env

apps/emqx_sn/src/emqx_sn_gateway.erl, apps/emqx_sn/test/emqx_sn_protocol_SUITE.erl, src/emqx_channel.erl
Fixes https://github.com/emqx/emqx/issues/4507
=> fix(mqtt_sn): send pingresp until all pubacks received

src/emqx_channel.erl
=> fix(emqx): export do_deliver/2 for emqx_sn

bin/emqx, rebar.config
=> fix(bin/emqx): print cuttlefish error

apps/emqx_rule_engine/src/emqx_rule_funcs.erl
some calls are for enterprise only
=> fix(emqx_rule_engine): missing calls

apps/emqx_management/src/emqx_mgmt_api_acl.erl
Fixes https://github.com/emqx/emqx/issues/4472
=> fix(http api): fix badarg caused by acl cache api

apps/emqx_lwm2m/src/emqx_lwm2m_message.erl
Fixes https://github.com/emqx/emqx/issues/4499
=> fix(lwm2m): decode/encode data as signed integer

apps/emqx_rule_engine/include/rule_engine.hrl, apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_engine_api.erl, apps/emqx_rule_engine/src/emqx_rule_registry.erl
Fixes https://github.com/emqx/emqx/issues/4487
=> fix(rule_engine): load hooks to all the nodes in cluster

apps/emqx_auth_pgsql/test/emqx_auth_pgsql_SUITE.erl, apps/emqx_auth_redis/test/emqx_auth_redis_SUITE.erl, apps/emqx_web_hook/test/props/prop_webhook_hooks.erl, lib-ce/emqx_telemetry/src/emqx_telemetry.app.src, src/emqx.erl, test/emqx_ws_connection_SUITE.erl
Fixes https://github.com/emqx/emqx/issues/4511
=> Start emqx-modules application by default

etc/zones.conf, priv/emqx.schema, src/emqx.appup.src, src/emqx_alarm.erl, src/emqx_congestion.erl, src/emqx_connection.erl
Porting following PR to e4.2.6:
#4462
=> Porting code for congestion alarms from 4.3.0 to e4.2.6

.github/workflows/run_test_cases.yaml, rebar.config.erl
=> chore(build): optional observer release

rebar.config
=> chore(rebar.config): bump cuttlefish

rebar.config.erl
=> chore(build): no deterministic compile flag for non-prod profiles

apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> test(mgmt): remove unused ct log

lib-ce/emqx_modules/test/emqx_mod_sup_SUITE.erl, lib-ce/emqx_modules/test/emqx_modules_SUITE.erl, src/emqx_app.erl
=> Fix modules started by default

apps/emqx_exhook/include/emqx_exhook.hrl, apps/emqx_exhook/src/emqx_exhook_app.erl, apps/emqx_exhook/src/emqx_exhook_handler.erl
=> fix(exhook): fix module name & wrong variable name

rebar.config
=> chore(build): pin ekka 0.8.1

etc/emqx.conf, priv/emqx.schema, src/emqx_logger_formatter.erl, test/emqx_logger_formatter_SUITE.erl
e.g. default: `2021-04-09T22:53:50.183617+02:00`
=> feat(log): rfc3339 date-time format in logs

etc/emqx.conf, priv/emqx.schema, src/emqx_ws_connection.erl, test/emqx_ws_connection_SUITE.erl
=> feat(emqx_ws_connection): #4184 check http header to know real IP/port

apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/make_data.sh, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.0.11.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.2.10-no-auth.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.2.10.json, apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl
=> fix(emqx_management): Don't fix broken emqx_auth_mnesia data

.github/workflows/run_test_cases.yaml, apps/emqx_exhook/test/props/prop_exhook_hooks.erl, apps/emqx_web_hook/src/emqx_web_hook.erl, apps/emqx_web_hook/test/props/prop_webhook_confs.erl, apps/emqx_web_hook/test/props/prop_webhook_hooks.erl, rebar.config.erl, test/props/prop_emqx_json.erl, test/props/prop_emqx_rpc.erl
=> Add proper testing to Github Action

apps/emqx_exhook/src/emqx_exhook.erl, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/test/emqx_exhook_demo_svr.erl, apps/emqx_exhook/test/props/prop_exhook_hooks.erl
=> Add props for exhook

test/props/prop_emqx_rpc.erl
=> test(proper): wait tcp port closed

apps/emqx_coap/README.md, apps/emqx_coap/src/emqx_coap_pubsub_resource.erl, apps/emqx_coap/src/emqx_coap_resource.erl
Issues found during review session.
=> fix(emqx_coap): return unauthorized when username/password error

apps/emqx_auth_http/rebar.config, apps/emqx_web_hook/rebar.config, rebar.config
=> chore(ehttpc): update tag of ehttpc

apps/emqx_exhook/src/emqx_exhook.erl, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/src/emqx_exhook_server.erl, apps/emqx_exhook/test/emqx_exhook_SUITE.erl
1. fix the match pattern
2. correct the exhook server anme
=> Fix exhook some bugs

apps/emqx_web_hook/test/props/prop_webhook_hooks.erl
Avoid generating a large number of atoms leading to atom overflow
=> test(proper): avoid to generate any term

apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE.erl, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/420.json, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/ee4010.json, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/ee410.json, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/ee411.json, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/ee420.json, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/ee425.json, apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE_data/ee430.json, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE.erl, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/ee4010.json, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/ee410.json, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/ee411.json, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/ee420.json, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/ee425.json, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE_data/ee430.json, apps/emqx_management/test/test_utils.erl
=> test(mgmt): add data im/export tests for EE

test/emqx_cm_SUITE.erl
=> fix(emqx): meck emqx_connection:call/3 in testcase

apps/emqx_sn/src/emqx_sn_registry.erl
=> fix(emqx_sn): dialyzer problems

apps/emqx_management/include/emqx_mgmt.hrl, apps/emqx_management/src/emqx_mgmt_api_data.erl, apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.0.11-no-auth.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.0.13.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.1.5.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.2.10-no-auth.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/v4.2.11.json
This is a problem with the data exported from version 4.2 and 4.0. We will release corresponding repaired versions for them.
=> fix(backup): support minimum version number when import

apps/emqx_prometheus/src/emqx_prometheus.erl
=> feat: cluster info available in metrics

apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/e4.0.10.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/e4.1.1.json, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE_data/e4.2.9.json
=> fix(tests): fix ee import auth mnesia fail

apps/emqx_auth_mnesia/src/emqx_acl_mnesia_api.erl, apps/emqx_auth_mnesia/src/emqx_auth_mnesia_api.erl, apps/emqx_management/src/emqx_mgmt_util.erl, apps/emqx_sasl/src/emqx_sasl_api.erl, src/emqx_http_lib.erl
=> feat(uri): support decoding uri in string

etc/emqx.conf
=> fix: ws proxy port config

.ci/build_packages/Dockerfile, .ci/docker-compose-file/docker-compose.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_test_cases.yaml, deploy/docker/Dockerfile, docker.mk
=> chore(build): Pin Erlang/OTP 23.2.7.1-emqx-1

lib-ce/emqx_telemetry/src/emqx_telemetry.erl, lib-ce/emqx_telemetry/test/emqx_telemetry_SUITE.erl
=> Telemetry first report after emqx started

test/props/prop_emqx_rpc.erl
=> test(proper): fix cant_generate error

apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl, apps/emqx_web_hook/test/http_server.erl
=> test(webhook): test ipv6 for real

apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl
=> test(webhook): ignore messages from other clients

apps/emqx_bridge_mqtt/test/emqx_bridge_stub_conn.erl, apps/emqx_bridge_mqtt/test/emqx_bridge_worker_SUITE.erl
=> test(emqx_bridge_mqtt): fix race condition

apps/emqx_management/src/emqx_mgmt_data_backup.erl, apps/emqx_management/test/test_utils.erl
=> test(mgmt): remove macro switch

rebar.config
=> fix(ekka): allow remote_console

etc/logger.conf
=> chore(conf): log only to file by default

apps/emqx_rule_engine/src/emqx_rule_funcs.erl, apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl, apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
Fixes https://github.com/emqx/emqx/issues/4638
=> feat(rule_engine): add rule sql functions for datetime rfc3339

apps/emqx_rule_engine/src/emqx_rule_engine.erl
Fixes https://github.com/emqx/emqx/issues/4642
=> fix: disable rule if build fail

.github/workflows/build_packages.yaml
Fixes https://github.com/emqx/emqx/issues/4663
=> chore(CI): fix packages version error for windows

apps/emqx_sn/src/emqx_sn_gateway.erl, apps/emqx_sn/test/emqx_sn_protocol_SUITE.erl
Fixes https://github.com/emqx/emqx/issues/4599
=> Mqtt sn willmsg

src/emqx_connection.erl
emqx_connection does not report the right stack in case of `throw` or `exit` exceptions.
e.g.
old log is like:
```
2021-04-22 23:13:18.609 [error] <<"clientnadff">>@172.30.128.13:17007   crasher:
initial call: emqx_connection:init/4
pid: <0.13850.19>
registered_name: []
exception exit: {timeout,
{gen_server,call,
[<0.2942.0>,
{subscribe,<<"t/b">>}]}}
in function  emqx_connection:terminate/2 (/emqx-enterprise-rel/_checkouts/emqx/src/emqx_connection.erl, line 433)
ancestors: [<0.2983.0>,<0.2982.0>,esockd_sup,<0.2852.0>]
message_queue_len: 3
```
after this fix, the new log looks like below (single line)
```
2021-04-23T17:32:35.195284+02:00 [error] clietnadff@127.0.0.1:49990 crasher: initial call: emqx_connection:init/4, pid: <0.1966.0>, registered_name: [], exit: …
```
=> fix(emqx_connection): log true stacktrace

rebar.config
=> fix(deps): update ecpool to 0.5.2

apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_engine_app.erl
fix: add rule engine resources wait time, ensure rule will build success
=> Fix rule engine build fail

deploy/docker/Dockerfile, deploy/docker/docker-entrypoint.sh
=> chore: move docker env var from Dockerfile to entrypoints

etc/emqx.conf, priv/emqx.schema, src/emqx_tracer.erl
=> chore(logging): default to multi-line logging

rebar.config
=> chore(snabbkaffe): Update version to 0.12.0

rebar.config.erl, src/emqx_broker_bench.erl
=> chore: add emqx_broker_bench.erl

apps/emqx_exhook/priv/protos/exhook.proto, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/test/props/prop_exhook_hooks.erl
Add ssl client certificate info (cn and dn) to exhook proto.
=> feat(exhook): add ssl cert info to ClientInfo

apps/emqx_rule_engine/include/rule_engine.hrl, apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_engine_api.erl, apps/emqx_rule_engine/src/emqx_rule_engine_app.erl, apps/emqx_rule_engine/src/emqx_rule_monitor.erl, apps/emqx_rule_engine/src/emqx_rule_registry.erl
Fixes https://github.com/emqx/emqx/issues/4642
=> Enable rules after resource init

apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_monitor.erl
=> fix(rule_engine): refresh rules and then re-enable it

apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE.erl
=> fix(deps): increase time sleep

apps/emqx_auth_mnesia/src/emqx_auth_mnesia_app.erl, apps/emqx_auth_mnesia/test/emqx_auth_mnesia_SUITE.erl
Fix https://github.com/emqx/emqx-auth-mnesia/issues/58
=> Fix hash type typos

.ci/build_packages/Dockerfile, .ci/docker-compose-file/docker-compose.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_test_cases.yaml, .tool-versions, deploy/docker/Dockerfile, docker.mk
=> build: pin erl23.2.7.2-emqx-1

rebar.config
=> fix(deps): change ecpool to 0.5.1

src/emqx.appup.src
=> chore(appup): supply appup instructions for ws-connetion

apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> fix(deps): fix function clause at apply_new_config

etc/emqx.conf, priv/emqx.schema
=> chore(config): Add new configs to emqx.conf

apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl
=> chore(coap): use ~0p to print peername

Makefile, apps/emqx_management/src/emqx_mgmt.erl, src/emqx_vm.erl
=> Chore dashbaord pin 4.3.0

apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE.erl
=> fix(test): fix ee430 problem when remove resources

rebar.config
=> chore(deps): upgrade to ekka 0.7.7

rebar.config
=> core(deps): pin ekka 0.7.7

include/emqx_mqtt.hrl, src/emqx_packet.erl
=> fix(emqx_packet): list element index out of range

src/emqx_frame.erl, src/emqx_packet.erl, test/emqx_packet_SUITE.erl
=> fix(emqx_packet): no crash if publish packet has no data

src/emqx_router.erl
=> perf(router): receive-mark optimise for short-lived transaction process

src/emqx_router.erl
=> perf(emqx_router): optimise trans result receive

apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl, etc/emqx.conf, priv/emqx.schema, src/emqx_logger_jsonfmt.erl, src/emqx_logger_textfmt.erl
this feature is intended for 5.0
However since it has been made configurable, merging to master branch (and getting released in 4.3 should be fine)
@k32 this is also why I try not to change a lot of the old logging behavior 
=> feat(logger): structured logging (JSON)

apps/emqx_sn/src/emqx_sn_gateway.erl, apps/emqx_sn/test/emqx_sn_protocol_SUITE.erl
=> fix(sn): fix clean_session=false willmsgs not sent

bin/node_dump, rebar.config.erl, src/emqx_node_dump.erl
Add a script that collects information needed for the investigation of the average issue
=> feat(node_dump): Create a node dump script

src/emqx_logger_jsonfmt.erl
=> fix(logger): fix json formatter

.ci/build_packages/Dockerfile, .ci/docker-compose-file/docker-compose.yaml, .github/workflows/build_packages.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_test_cases.yaml, deploy/docker/Dockerfile, docker.mk, include/emqx_release.hrl
=> Release 4.3.0

apps/emqx_auth_http/etc/emqx_auth_http.conf, apps/emqx_auth_http/src/emqx_auth_http_app.erl, src/emqx_http_lib.erl, test/emqx_http_lib_tests.erl
=> fix(auth-http): headers config support env override

Makefile, build
=> build: fix build order of release and relup

rebar.config
=> chore(rebar.config): cuttlefish 3.3.3 -> 3.3.4

rebar.config
=> build: fix relup hook point name

.github/workflows/build_packages.yaml, .gitignore, Makefile, build, rebar.config, src/emqx_logger_jsonfmt.erl
to make it easy, added a environment variable to pass upgrade base to relx: https://github.com/emqx/relx/commit/f901949fe8b638320c2ab33d15131795d72f3484
=> build(relup): update build script for support relup

build
=> build: zip for macos

apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE.erl
=> fix(import): fix import bridge mqtt test cases

apps/emqx_rule_engine/src/emqx_rule_funcs.erl, apps/emqx_rule_engine/src/emqx_rule_utils.erl
=> feat(rule_engine): rule sql add null function

.github/workflows/build_slim_packages.yaml
=> chore(slim): fix build silm macosx fail

src/emqx.app.src, src/emqx.appup.src, src/emqx_logger_jsonfmt.erl
=> fix(logging): add line-break after each JSON log

etc/emqx.conf, priv/emqx.schema
=> chore(config): do not expose manual rpc peer port config

apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt_data_backup.erl
=> fix(mgmt): fix diylazer warning for function return

apps/emqx_lwm2m/etc/emqx_lwm2m.conf, apps/emqx_lwm2m/priv/emqx_lwm2m.schema, apps/emqx_lwm2m/src/emqx_lwm2m.appup.src, apps/emqx_lwm2m/src/emqx_lwm2m_protocol.erl
=> Support auto_observer to specified resources

apps/emqx_lwm2m/src/emqx_lwm2m.app.src
=> fix(lwm2m): fix check emqx-lwm2m version

bin/nodetool
=> fix(nodetool): add path from RELEASES file

bin/nodetool, src/emqx_metrics.erl
=> chore(metrics): update ets table in the metrics proc

priv/emqx.schema
=> fix(emqx): Add new shared_subscription_strategy atoms to the schema

scripts/apps-version-check.sh
chore(CI): ignore changes to the etc directory when checking the app version
=> chore(CI): update app vsn check

src/emqx.appup.src, src/emqx_broker_bench.erl, src/emqx_trie.erl, test/emqx_trie_SUITE.erl
Embarrassing bug: the old implementation was a O(2^n)
=> Fix trie compaction performance when many levels

apps/emqx_web_hook/src/emqx_web_hook.erl, rebar.config
=> chore(update dep): update dep of ehttpc

apps/emqx_management/test/emqx_bridge_mqtt_data_export_import_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_SUITE.erl, apps/emqx_management/test/emqx_webhook_data_export_import_SUITE.erl
=> chore(optimize): optimize MGMT test cases

src/emqx.app.src, src/emqx.appup.src, src/emqx_node_dump.erl
found at least two:
`default_application_secret`
`default_user_passwd`
=> fix(node_dump): obfuscate more secrets

src/emqx.appup.src, src/emqx_congestion.erl
Fixes https://github.com/emqx/emqx/issues/4823
=> fix(emqx): check if the congestion alarm was sent before clearing

bin/emqx.cmd
=> fix(emqx.cmd): windows boot

apps/emqx_auth_jwt/test/emqx_auth_jwt_SUITE.erl
=> test(auth-jwt): fix verify_claims not being covered

.ci/build_packages/tests.sh, apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt_cli.erl, apps/emqx_management/test/emqx_mgmt_SUITE.erl
=> chore(emqx_ctl): do not print application

apps/emqx_sn/src/emqx_sn.app.src, apps/emqx_sn/src/emqx_sn.appup.src, apps/emqx_sn/src/emqx_sn_asleep_timer.erl, apps/emqx_sn/src/emqx_sn_gateway.erl, apps/emqx_sn/test/emqx_sn_protocol_SUITE.erl, src/emqx.appup.src, src/emqx_channel.erl
=> fix(mqtt-sn): Fix stop due to keepAlive at sleep mode

.github/workflows/run_fvt_tests.yaml
=> test: ensure erlang 23 in github action

.github/workflows/run_fvt_tests.yaml
=> test: ensure erlang 23 in more github actions

src/emqx.appup.src
=> chore: make sure emqx_app is reloaded

apps/emqx_rule_engine/src/emqx_rule_runtime.erl
=> chore(rule_engine): Don't import alias/1 BIF

apps/emqx_coap/test/emqx_coap_SUITE.erl, apps/emqx_coap/test/emqx_coap_pubsub_SUITE.erl, apps/emqx_exproto/test/emqx_exproto_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_SUITE.erl, lib-ce/emqx_modules/test/emqx_modules_SUITE.erl, rebar.config.erl, src/emqx.appup.src, src/emqx_plugins.erl, test/emqx_plugins_SUITE.erl, test/emqx_plugins_SUITE_data/emqx_mini_plugin/Makefile, test/emqx_plugins_SUITE_data/emqx_mini_plugin/rebar.config
=> External plugin lib

.tool-versions, rebar.config
=> Fix upgrade cuttlefish

src/emqx_cm.erl, src/emqx_connection.erl, test/emqx_mqtt_SUITE.erl
=> feat: async API to support tcp keepalive inet options

src/emqx_node_dump.erl
=> fix(emqx_node_dump): call atom_to_binary/2

lib-ce/emqx_modules/src/emqx_mod_api_topic_metrics.erl, lib-ce/emqx_modules/src/emqx_modules.app.src, lib-ce/emqx_modules/src/emqx_modules.appup.src
=> fix(topic metrics): export mandatory functions to support cluster calls

src/emqx_plugins.erl
=> fix: external plugin load all

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.appup.src, lib-ce/emqx_telemetry/src/emqx_telemetry.app.src, lib-ce/emqx_telemetry/src/emqx_telemetry.appup.src, src/emqx.appup.src
=> fix(appup): update appup

.github/workflows/build_slim_packages.yaml, scripts/get-dashboard.sh, src/emqx_connection.erl
=> feat(emqx_connection): async_set_keepalive defaults to self()

.github/workflows/build_packages.yaml
=> build: ensure rebar3 in PATH for build_packages action

rebar.config
=> build: pin gpb 4.11.2

apps/emqx_exhook/priv/protos/exhook.proto
Fixes https://github.com/emqx/emqx/issues/4871
=> fix(exhook): change default value to CONTINUE

priv/emqx.schema
=> fix(schema): fix locking strategy typos

apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt.erl
=> fix(API): fix get used memory error

pkg-vsn.sh
=> chore(pkg-vsn.sh): add some comments

etc/emqx.conf, priv/emqx.schema, rebar.config
=> chore: ekka support etcd v3

rebar.config.erl
=> build: use base rebar.conf when emqx.git is as dependency

.github/workflows/run_test_cases.yaml, apps/emqx_coap/test/emqx_coap_SUITE.erl, apps/emqx_coap/test/emqx_coap_pubsub_SUITE.erl, apps/emqx_exhook/src/emqx_exhook.app.src, apps/emqx_exhook/src/emqx_exhook.appup.src, apps/emqx_lwm2m/test/emqx_lwm2m_SUITE.erl, src/emqx.app.src, src/emqx.appup.src, src/emqx_http_lib.erl, test/emqx_http_lib_tests.erl
=> chore(action): fix syntax error

apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt_api_data.erl, apps/emqx_management/test/emqx_mgmt_api_SUITE.erl
=> feat(emqx_management): Import content of the HTTP request

apps/emqx_sn/src/emqx_sn.app.src, apps/emqx_sn/src/emqx_sn.appup.src, apps/emqx_sn/src/emqx_sn_gateway.erl, apps/emqx_sn/src/emqx_sn_registry.erl
=> fix(mqtt-sn): fix clean session false reconnect topic-id badmatch

apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt_api.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl
Fixes: https://github.com/emqx/emqx/issues/4902
=> fix(mgmt): return type conversion error instead a 500 error

rebar.config
=> fix: emqtt performance

apps/emqx_web_hook/src/emqx_web_hook.app.src, apps/emqx_web_hook/src/emqx_web_hook.appup.src, apps/emqx_web_hook/src/emqx_web_hook_actions.erl
=> fix(webhook): fix bad ssl options

rebar.config
=> chore(rebar.config): bump hocon; no more unused import

rebar.config
=> chore: pin cuttlefish 4.0.1

scripts/update_appup.escript
=> feat(scripts): Add an appup helper script

apps/emqx_resource/include/emqx_resource.hrl, apps/emqx_resource/rebar.config, apps/emqx_resource/src/emqx_resource.app.src, apps/emqx_resource/src/emqx_resource.erl, apps/emqx_resource/src/emqx_resource_api.erl, apps/emqx_resource/src/emqx_resource_instance.erl, apps/emqx_resource/src/emqx_resource_transform.erl
=> fix(emqx_resource): HTTP APIs for emqx_resource not working

apps/emqx_auth_jwt/src/emqx_auth_jwt.app.src, apps/emqx_auth_jwt/src/emqx_auth_jwt.appup.src, apps/emqx_auth_jwt/src/emqx_auth_jwt_svr.erl, apps/emqx_auth_jwt/test/emqx_auth_jwt_SUITE.erl
=> fix(svr): avoid crashed on undefined remote jwks server

bin/emqx, rebar.config
=> chore(bin/emqx): use hocon get

apps/emqx_sn/test/emqx_sn_protocol_SUITE.erl
=> fix(mqtt-sn): fix mqtt-sn test cases

apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt_http.erl
=> fix(api): fix ee call module api 404

src/emqx_plugins.erl
=> fix(relup): fix relup badfun

etc/emqx.conf
=> chore(config): add log.max_depth example config

apps/emqx_auth_ldap/src/emqx_auth_ldap.app.src, apps/emqx_auth_mongo/src/emqx_auth_mongo.app.src, apps/emqx_auth_mysql/src/emqx_auth_mysql.app.src, apps/emqx_auth_pgsql/src/emqx_auth_pgsql.app.src, apps/emqx_auth_redis/src/emqx_auth_redis.app.src, apps/emqx_exproto/src/emqx_exproto.app.src, apps/emqx_management/src/emqx_management.app.src, apps/emqx_recon/src/emqx_recon.app.src, apps/emqx_stomp/src/emqx_stomp.app.src, lib-ce/emqx_dashboard/src/emqx_dashboard.app.src, scripts/apps-version-check.sh
=> chore: fix app versions and check script

.github/workflows/build_packages.yaml, test/emqx_cm_SUITE.erl
=> Fix build and test case

src/emqx.appup.src, src/emqx_channel.erl
=> chore: export function

apps/emqx_connector/src/emqx_connector_mysql.erl, apps/emqx_data_bridge/src/emqx_data_bridge_api.erl, apps/emqx_data_bridge/src/emqx_data_bridge_config_handler.erl, apps/emqx_data_bridge/src/emqx_data_bridge_monitor.erl, apps/emqx_resource/README.md, apps/emqx_resource/examples/demo.md, apps/emqx_resource/examples/log_tracer.erl, apps/emqx_resource/src/emqx_resource.erl, apps/emqx_resource/src/emqx_resource_schema.erl, apps/emqx_resource/src/emqx_resource_transform.erl
=> feat(emqx_resource): remove the schema sugar from parse transformed code

rebar.config
=> fix(ehttpc): update ehttpc tag to fix bad log

priv/emqx.schema
=> chore: remove lager schema info

.ci/fvt_tests/http_server/rebar.config, rebar.config
Fixes https://github.com/emqx/emqx/issues/4962
=> fix(minirest): encode response message failed

etc/emqx.conf, priv/emqx.schema
=> chore(conf): change default number of gen_rpc connections to 1

apps/emqx_auth_ldap/src/emqx_acl_ldap.erl, apps/emqx_auth_ldap/src/emqx_auth_ldap.app.src, apps/emqx_auth_ldap/src/emqx_auth_ldap.appup.src
=> fix(auth_ldap): Handle missing attributes

src/emqx.appup.src, src/emqx_ws_connection.erl
=> fix(ws): avoid funcation_clause for un-initiated websocket

.gitignore, apps/emqx/rebar.config, apps/emqx/src/emqx_app.erl, apps/emqx/src/emqx_schema.erl, rebar.config
=> feat(rlog): Add RLOG to EMQX

.ci/build_packages/tests.sh, .github/workflows/run_cts_tests.yaml, .github/workflows/run_fvt_tests.yaml, apps/emqx/rebar.config, apps/emqx/src/emqx_schema.erl, apps/emqx_connector/src/emqx_connector_mysql.erl, apps/emqx_dashboard/priv/emqx_dashboard.schema, apps/emqx_resource/src/emqx_resource_schema.erl, bin/emqx, bin/emqx_ctl, deploy/docker/README.md, rebar.config
=> fix(hocon): pin hocon 0.5.1

apps/emqx_exhook/src/emqx_exhook.app.src, apps/emqx_exhook/src/emqx_exhook.appup.src, apps/emqx_exhook/src/emqx_exhook_server.erl
=> fix(modules): fix start/stop exhook module failure

apps/emqx_data_bridge/etc/emqx_data_bridge.conf, apps/emqx_plugin_libs/src/emqx_plugin_libs_ssl.erl
=> fix(data_bridge): comment out all the connector-config

rebar.config
=> chore: update ekka tag

apps/emqx_auth_http/src/emqx_auth_http.app.src, apps/emqx_auth_http/src/emqx_auth_http.appup.src, apps/emqx_auth_http/src/emqx_auth_http_app.erl, apps/emqx_web_hook/src/emqx_web_hook.app.src, apps/emqx_web_hook/src/emqx_web_hook.appup.src, apps/emqx_web_hook/src/emqx_web_hook_actions.erl, apps/emqx_web_hook/src/emqx_web_hook_app.erl
=> fix(query string): support query string in path

apps/emqx_rule_engine/src/emqx_rule_engine.app.src, apps/emqx_rule_engine/src/emqx_rule_engine.appup.src, apps/emqx_rule_engine/src/emqx_rule_registry.erl
=> Delete resource failed when searching dependent rules

apps/emqx_management/src/emqx_mgmt_api_nodes.erl
=> chore: more node info

apps/emqx/include/emqx.hrl, apps/emqx/rebar.config, apps/emqx/src/emqx_app.erl, apps/emqx/src/emqx_cm_registry.erl, apps/emqx/src/emqx_router.erl, apps/emqx/src/emqx_router_helper.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/src/emqx_trie.erl, rebar.config
=> feat(rlog): Introduce routing RLOG shard

apps/emqx/rebar.config, apps/emqx/src/emqx_schema.erl, bin/emqx, rebar.config
example
```
EMQX_NODE_COOKIE = "*******" -> node.cookie
EMQX_LOG__TO = "console" -> log.to
EMQX_LOG__SINGLE_LINE = "false" -> log.single_line
```
=> Use hocon 0.6.0

apps/emqx/rebar.config, apps/emqx/src/emqx_plugins.erl, apps/emqx/test/emqx_plugins_SUITE.erl, apps/emqx/test/emqx_plugins_SUITE_data/emqx_hocon_plugin/Makefile, apps/emqx/test/emqx_plugins_SUITE_data/emqx_hocon_plugin/etc/emqx_hocon_plugin.conf, apps/emqx/test/emqx_plugins_SUITE_data/emqx_hocon_plugin/rebar.config, apps/emqx/test/emqx_plugins_SUITE_data/emqx_hocon_plugin/src/emqx_hocon_plugin.app.src, apps/emqx/test/emqx_plugins_SUITE_data/emqx_hocon_plugin/src/emqx_hocon_plugin_app.erl, apps/emqx/test/emqx_plugins_SUITE_data/emqx_hocon_plugin/src/emqx_hocon_plugin_schema.erl
=> feat(plugins): Support load plugins of hocon configuration format

apps/emqx/src/emqx_plugins.erl
=> fix(plugins): fix load plugin generate hocon configs fail

apps/emqx_rule_engine/src/emqx_rule_engine.appup.src, apps/emqx_rule_engine/src/emqx_rule_registry.erl
These stats are never used but will fail when hot code upgrade because of the anonymous function.
=> feat(rules): remove stats update from rule_engine_registry

apps/emqx_rule_engine/src/emqx_rule_engine.appup.src
=> fix(appup): relup for emqx_rule_registry failed

apps/emqx_lwm2m/src/emqx_lwm2m.appup.src, apps/emqx_lwm2m/src/emqx_lwm2m_api.erl, apps/emqx_lwm2m/src/emqx_lwm2m_cm.erl, apps/emqx_lwm2m/src/emqx_lwm2m_cm_sup.erl, apps/emqx_lwm2m/src/emqx_lwm2m_xml_object.erl, apps/emqx_lwm2m/src/emqx_lwm2m_xml_object_db.erl
=> feat(lwm2m): add emqx_lwm2m http API

.ci/fvt_tests/relup.lux, lib-ce/emqx_dashboard/src/emqx_dashboard.app.src, lib-ce/emqx_dashboard/src/emqx_dashboard.appup.src, rebar.config.erl, scripts/inject-deps.escript
=> chore(relup): add relup dependency injection

apps/emqx_lwm2m/rebar.config, apps/emqx_lwm2m/src/emqx_lwm2m_coap_resource.erl
Fixe: https://github.com/emqx/emqx/issues/5062
Pre-PR: https://github.com/emqx/lwm2m-coap/pull/19
=> Fix coap uri format

src/emqx.appup.src, src/emqx_cm.erl
=> fix(emqx_cm): catch noproc exception from rpc_call

apps/emqx_lwm2m/src/emqx_lwm2m_cmd_handler.erl, apps/emqx_lwm2m/src/emqx_lwm2m_protocol.erl
=> feat(lwm2m): register lwm2m channel to emqx_lwm2m_cm

apps/emqx_auth_ldap/src/emqx_auth_ldap.appup.src, src/emqx.appup.src
=> chore(review): review 4.3.4

scripts/inject-deps.escript
=> chore: fix inject deps notfound emqx_reloader

scripts/inject-deps.escript
=> chore: add more info in error message

scripts/inject-deps.escript
=> fix(script): exclude non-edge apps in relup dependency

apps/emqx/rebar.config, apps/emqx_management/include/emqx_mgmt.hrl, apps/emqx_management/src/emqx_mgmt_app.erl, apps/emqx_management/src/emqx_mgmt_auth.erl, apps/emqx_management/test/emqx_auth_mnesia_migration_SUITE.erl, apps/emqx_management/test/emqx_mgmt_SUITE.erl, rebar.config
=> feat(emqx_management): mqtt_app shard

apps/emqx_dashboard/include/emqx_dashboard.hrl, apps/emqx_dashboard/src/emqx_dashboard_admin.erl, apps/emqx_dashboard/src/emqx_dashboard_app.erl, apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
=> feat(dashboard): Introduce dashboard RLOG shard

apps/emqx/src/emqx_config_handler.erl, apps/emqx/src/emqx_schema.erl, apps/emqx_data_bridge/src/emqx_data_bridge.erl, apps/emqx_data_bridge/src/emqx_data_bridge_schema.erl, apps/emqx_telemetry/src/emqx_telemetry.erl, apps/emqx_telemetry/src/emqx_telemetry_schema.erl
=> Reference to foreign schema definitions in emqx_schema

apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_config_handler.erl, apps/emqx_data_bridge/src/emqx_data_bridge.erl
=> Add some APIs for emqx_config

.github/workflows/apps_version_check.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/check_deps_integrity.yaml, .github/workflows/elvis_lint.yaml, .github/workflows/run_cts_tests.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_gitlint.yaml, .github/workflows/run_test_cases.yaml, .github/workflows/shellcheck.yaml
This reverts commit 002cbb6d8bce61fbbf1b174284ac78e539598062
=> revert: chore(CI): update events that trigger workflows

src/emqx.appup.src, src/emqx_shared_sub.erl
=> Clean emqx shared subscription 4.2.13

src/emqx_shared_sub.erl
=> fix(shared_sub): discard all unexpected msgs

apps/emqx/src/emqx_cm_registry.erl, apps/emqx_authentication/include/emqx_authentication.hrl, apps/emqx_authentication/src/emqx_authentication.erl, apps/emqx_authentication/src/emqx_authentication_app.erl, apps/emqx_authentication/src/emqx_authentication_mnesia.erl, apps/emqx_authentication/test/emqx_authentication_SUITE.erl
=> Create authN shard

apps/emqx_retainer/include/emqx_retainer.hrl, apps/emqx_retainer/src/emqx_retainer.erl, apps/emqx_retainer/src/emqx_retainer_cli.erl
=> chore(retainer): Add RLOG shard

apps/emqx/include/emqx.hrl, apps/emqx/src/emqx_app.erl, apps/emqx_rule_engine/src/emqx_rule_registry.erl
=> chore(rule_engine): Add an RLOG shard

apps/emqx/include/emqx.hrl, apps/emqx/src/emqx_app.erl, apps/emqx_modules/src/emqx_mod_delayed.erl, rebar.config
=> chore(mod_delayed): Add RLOG shard

apps/emqx_authn/src/simple_authn/emqx_authn_mysql.erl, apps/emqx_authn/src/simple_authn/emqx_authn_pgsql.erl
=> feat(authn): update schema for mysql and postgresql

apps/emqx_exhook/src/emqx_exhook.app.src, apps/emqx_exhook/src/emqx_exhook.appup.src, apps/emqx_exhook/src/emqx_exhook_app.erl
=> fix(exhook): catch the badarg error

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/support-needed.md
=> chore: disable auto assignee for github issues.

apps/emqx/etc/emqx.conf
=> feat(hocon): convert config format of rpc and log to hocon

apps/emqx/etc/emqx.conf, apps/emqx/src/emqx_schema.erl
=> feat:(conf):  emqx.conf to hocon format

apps/emqx/etc/emqx.conf, apps/emqx/src/emqx.erl, apps/emqx/src/emqx_schema.erl, rebar.config.erl, scripts/merge-config.escript
=> chore: delete plugins related configuration

apps/emqx/src/emqx.erl, apps/emqx_gateway/src/emqx_gateway_app.erl
=> fix(gw): start emqx-gateway after emqx restarted

README-CN.md, README-JP.md, README-RU.md, README.md
=> docs(README): Modify invalid links

apps/emqx/src/emqx.app.src
=> chore: start jiffy by emqx

apps/emqx_coap/src/emqx_coap_mqtt_adapter.erl
=> chore(coap): Fix debug logs

apps/emqx_connector/src/emqx_connector_mongo.erl
rename login to username
rename auth_source to authentication_database
=> chore(connector): rename mongo config key

apps/emqx_authz/test/emqx_authz_api_SUITE.erl, apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl, apps/emqx_management/etc/emqx_management.conf, apps/emqx_management/src/emqx_management_schema.erl, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_acl.erl, apps/emqx_management/src/emqx_mgmt_api_alarms.erl, apps/emqx_management/src/emqx_mgmt_api_apps.erl, apps/emqx_management/src/emqx_mgmt_api_banned.erl, apps/emqx_management/src/emqx_mgmt_api_brokers.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_listeners.erl, apps/emqx_management/src/emqx_mgmt_api_metrics.erl, apps/emqx_management/src/emqx_mgmt_api_nodes.erl, apps/emqx_management/src/emqx_mgmt_api_plugins.erl, apps/emqx_management/src/emqx_mgmt_api_pubsub.erl, apps/emqx_management/src/emqx_mgmt_api_routes.erl, apps/emqx_management/src/emqx_mgmt_api_stats.erl, apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl, apps/emqx_management/src/emqx_mgmt_auth.erl, apps/emqx_management/src/emqx_mgmt_http.erl, apps/emqx_management/test/emqx_mgmt_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_SUITE.erl, apps/emqx_management/test/etc/emqx_management.conf, apps/emqx_modules/test/emqx_modules_SUITE.erl, apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl
=> fix: mgmt conf & schema; prepare minirest

etc/emqx.conf
=> fix(conf): change wss.external.max_connections from 16 to 102400

apps/emqx/rebar.config, bin/emqx, rebar.config
=> Fix boot exit on config error

apps/emqx_authn/src/simple_authn/emqx_authn_http.erl, apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl, apps/emqx_authn/src/simple_authn/emqx_authn_mysql.erl, apps/emqx_connector/src/emqx_connector_http.erl, rebar.config
Not sure if ehttpc will continue to modify, so temporarily use the branch to get the code
=> feat(http connector): support http connector

apps/emqx_authn/src/simple_authn/emqx_authn_http.erl, apps/emqx_connector/src/emqx_connector_http.erl
=> chore(auhtn): keep one ssl opts checking func

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_clients_api_SUITE.erl
=> test: add clients api SUITE & add api [delete sub]

apps/emqx_management/src/emqx_mgmt_api_nodes.erl, apps/emqx_management/src/emqx_mgmt_util.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, apps/emqx_management/test/emqx_mgmt_clients_api_SUITE.erl, apps/emqx_management/test/emqx_mgmt_nodes_api_SUITE.erl
=> refactor: nodes api ; add: api test util module

apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt_cli.erl
=> Fix the dump function aborted by print function crash

src/emqx.app.src, src/emqx.appup.src, src/emqx_cm.erl
See: https://emqx.atlassian.net/browse/EE-529
=> Add a timeout for rpc_call

apps/emqx_auth_ldap/src/emqx_auth_ldap.app.src, apps/emqx_auth_ldap/src/emqx_auth_ldap.appup.src, apps/emqx_auth_ldap/src/emqx_auth_ldap_cli.erl
=> chore: bind_as_user set default value

apps/emqx_management/src/emqx_mgmt_http.erl
=> fix: api auth header support

apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_metrics.erl, apps/emqx_management/src/emqx_mgmt_api_nodes.erl, apps/emqx_management/src/emqx_mgmt_api_stats.erl, apps/emqx_management/test/emqx_mgmt_metrics_api_SUITE.erl, apps/emqx_management/test/emqx_mgmt_stats_api_SUITE.erl
=> refactor: stats api & metrics api; fix: clients api parameter type lose

apps/emqx_management/src/emqx_mgmt_api_publish.erl, apps/emqx_management/src/emqx_mgmt_util.erl, apps/emqx_management/test/emqx_mgmt_publish_api_SUITE.erl
=> refactor: publish api; add: batch schema util function

apps/emqx/rebar.config, rebar.config
=> chore(ekka): Bump version to 0.10.3

lib-ce/emqx_dashboard/src/emqx_dashboard.app.src, lib-ce/emqx_dashboard/src/emqx_dashboard.appup.src, src/emqx.appup.src
=> chore(relup): update emqx appup

bin/emqx
=> fix(script): emqx die if call_hocon failed

apps/emqx_retainer/src/emqx_retainer.erl, apps/emqx_retainer/test/emqx_retainer_SUITE.erl
=> fix(emqx_retainer): fix remaining quota check error

apps/emqx_management/src/emqx_mgmt_http.erl
=> improve: add mgmt start listener log

apps/emqx_management/src/emqx_mgmt_api_routes.erl, apps/emqx_management/test/emqx_mgmt_routes_api_SUITE.erl
=> refactor: routes api

apps/emqx_exproto/src/emqx_exproto.app.src, apps/emqx_exproto/src/emqx_exproto.appup.src, apps/emqx_exproto/src/emqx_exproto_conn.erl
=> Fix exproto bad socktype

apps/emqx_management/src/emqx_mgmt_api_apps.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_nodes.erl, apps/emqx_management/src/emqx_mgmt_util.erl, apps/emqx_management/test/emqx_mgmt_apps_api_SUITE.erl
=> refactor: apps api; rename: error response util function

apps/emqx_management/src/emqx_mgmt_api_routes.erl
=> fix: routes api function cause

apps/emqx/src/emqx_cm.erl, apps/emqx/src/emqx_session.erl, apps/emqx/test/emqx_channel_SUITE.erl, apps/emqx/test/emqx_connection_SUITE.erl, apps/emqx/test/emqx_session_SUITE.erl, apps/emqx/test/emqx_ws_connection_SUITE.erl
=> refactor(emqx): strip the side effects of emqx_session module

apps/emqx_exproto/src/emqx_exproto.appup.src, apps/emqx_exproto/src/emqx_exproto_channel.erl, apps/emqx_exproto/src/emqx_exproto_conn.erl
=> fix(exproto): get peername after esockd_wait/1

apps/emqx/etc/emqx.conf, apps/emqx/src/emqx_app.erl, apps/emqx/src/emqx_boot.erl, apps/emqx/src/emqx_listeners.erl, apps/emqx/src/emqx_router.erl, apps/emqx/src/emqx_router_sup.erl, apps/emqx/src/emqx_rpc.erl, apps/emqx/src/emqx_schema.erl
=> fix(configs): correct the default value of some configs

.ci/build_packages/tests.sh, .gitignore, apps/emqx/etc/emqx.conf, apps/emqx/rebar.config.script, apps/emqx/src/emqx_listeners.erl, apps/emqx/src/emqx_schema.erl
=> fix(ci):  fix build pipelines add ‘enable’ toggle for quic listener

apps/emqx_gateway/src/emqx_gateway_registry.erl, apps/emqx_gateway/src/exproto/emqx_exproto_channel.erl, apps/emqx_gateway/src/exproto/emqx_exproto_conn.erl, apps/emqx_gateway/src/mqttsn/emqx_sn_conn.erl, apps/emqx_gateway/src/stomp/emqx_stomp_channel.erl, apps/emqx_gateway/src/stomp/emqx_stomp_connection.erl, apps/emqx_gateway/src/stomp/emqx_stomp_frame.erl, apps/emqx_gateway/src/stomp/emqx_stomp_impl.erl, apps/emqx_gateway/src/stomp/include/emqx_stomp.hrl
=> chore(gw): fix dialyzer warnings

apps/emqx_management/src/emqx_mgmt_api.erl, apps/emqx_management/src/emqx_mgmt_api_apps.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_routes.erl, apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl, apps/emqx_management/src/emqx_mgmt_util.erl, apps/emqx_management/test/emqx_mgmt_subscription_api_SUITE.erl
=> refactor: sub api; fix: fuzzy function

apps/emqx/src/emqx_listeners.erl, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_listeners.erl, apps/emqx_management/test/emqx_mgmt_listeners_api_SUITE.erl
=> refactor: listeners api; add: listeners list function; fix: listener

apps/emqx/src/emqx_alarm.erl, apps/emqx_management/src/emqx_mgmt_api_alarms.erl, apps/emqx_management/test/emqx_mgmt_alarms_api_SUITE.erl
=> refactor: alarms api; add: alarms format function

rebar.config
=> chore: upgrade minirest to 1.1.5

apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_config_handler.erl, apps/emqx/src/emqx_map_lib.erl
=> feat(config): support deleting a config entry

apps/emqx_dashboard/src/emqx_dashboard.erl, apps/emqx_management/src/emqx_mgmt_http.erl, rebar.config
=> feat(mgmt): ignore emqx_dashboard API and apps API

apps/emqx/src/emqx_schema.erl, apps/emqx_prometheus/etc/emqx_prometheus.conf, apps/emqx_prometheus/include/emqx_prometheus.hrl, apps/emqx_prometheus/src/emqx_prometheus.erl, apps/emqx_prometheus/src/emqx_prometheus_api.erl, apps/emqx_prometheus/src/emqx_prometheus_app.erl, apps/emqx_prometheus/src/emqx_prometheus_schema.erl, apps/emqx_prometheus/src/emqx_prometheus_sup.erl, apps/emqx_statsd/src/emqx_statsd_api.erl, apps/emqx_statsd/src/emqx_statsd_app.erl, rebar.config.erl
=> feat(prometheus): Support swagger API prometheus

apps/emqx/src/emqx_os_mon.erl, apps/emqx/test/emqx_os_mon_SUITE.erl
also reply error for unexpected gen_server call
and refine log message for unexpected gen_server cast
=> fix(emqx_os_mon): log info level for unexpected message

apps/emqx/rebar.config, apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_config_handler.erl, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/test/emqx_authz_api_SUITE.erl, apps/emqx_modules/test/emqx_rewrite_SUITE.erl, rebar.config
This will be helpful for tests
=> feat(emqx_config): allow loading configs from binary

apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_config_handler.erl, apps/emqx_authz/src/emqx_authz.erl
=> refactor(emqx_config): call MOD:post_config_update/3 after checking hocon schema

src/emqx.appup.src, src/emqx_ctl.erl, test/emqx_ctl_SUITE.erl
=> fix(auth mnesia): fix ctl print error

.github/workflows/run_fvt_tests.yaml, deploy/charts/emqx/README.md, deploy/charts/emqx/templates/service.yaml, deploy/charts/emqx/values.yaml
Same as https://github.com/emqx/emqx/pull/5201
=> feat(helm): add externalIPs to chart

apps/emqx/src/emqx_sys.erl, apps/emqx/test/emqx_sys_SUITE.erl, apps/emqx/test/props/prop_emqx_sys.erl, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_nodes.erl
=> chore: sys uptime by millisecond

.github/workflows/build_packages.yaml
=> chore(CI): using docker official actions for build packages workflow

.github/workflows/run_fvt_tests.yaml, .github/workflows/run_relup_tests.yaml, build
1. Splitting the release upground test into a new yaml file
2. Use minikube instead of k3s in helm tests
=> chore(CI): update workflows

apps/emqx_authz/src/emqx_authz_api_schema.erl, apps/emqx_authz/src/emqx_authz_api_settings.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_authz/test/emqx_authz_api_settings_SUITE.erl, apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
+ support '/authorization/settings' api 
+ update swagger schema
=> feat(authz api): support '/authorization/settings' api

rebar.config
Fix https://github.com/emqx/emqx/issues/5565
=> fix(issue): 5565

src/emqx.app.src, src/emqx.appup.src, src/emqx_mqueue.erl, src/emqx_pqueue.erl, test/emqx_mqueue_SUITE.erl
[v] Write the code that updates mqueue structure during hot upgrade.
=> feat(mqueue): Interleave messages with different priorities

apps/emqx_gateway/etc/emqx_gateway.conf, apps/emqx_gateway/src/coap/emqx_coap_api.erl, apps/emqx_gateway/src/coap/emqx_coap_channel.erl, apps/emqx_gateway/src/coap/emqx_coap_session.erl, apps/emqx_gateway/src/coap/emqx_coap_tm.erl, apps/emqx_gateway/src/coap/emqx_coap_transport.erl, apps/emqx_gateway/src/coap/handler/emqx_coap_pubsub_handler.erl, apps/emqx_gateway/src/emqx_gateway_app.erl, apps/emqx_gateway/src/emqx_gateway_metrics.erl, apps/emqx_gateway/test/emqx_coap_api_SUITE.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl
1. add a request api for emqx_coap
2. fix some emqx_coap logic error
=> feat(emqx_coap): add emqx_coap_api

apps/emqx/rebar.config, apps/emqx/src/emqx_schema.erl, apps/emqx_data_bridge/src/emqx_data_bridge_schema.erl, apps/emqx_gateway/src/emqx_gateway_schema.erl, apps/emqx_machine/src/emqx_machine_schema.erl, bin/emqx, bin/nodetool, build, rebar.config
also generate html doc as a part of the release
=> refactor: hocon map type replace wildcard

apps/emqx_authz/etc/emqx_authz.conf, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/src/emqx_authz_api_schema.erl, apps/emqx_authz/src/emqx_authz_mongo.erl, apps/emqx_authz/src/emqx_authz_mysql.erl, apps/emqx_authz/src/emqx_authz_pgsql.erl, apps/emqx_authz/src/emqx_authz_schema.erl, apps/emqx_authz/test/emqx_authz_SUITE.erl, apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl, apps/emqx_authz/test/emqx_authz_mongo_SUITE.erl, apps/emqx_authz/test/emqx_authz_mysql_SUITE.erl, apps/emqx_authz/test/emqx_authz_pgsql_SUITE.erl
rename sql to query for mysql and pgsql
rename find to selector for mongo
=> chore(emqx_authz): rename config item

deploy/charts/emqx/Chart.yaml, deploy/charts/emqx/README.md, deploy/charts/emqx/templates/ingress.yaml, deploy/charts/emqx/values.yaml
=> feat(helm): add support for networking.k8s.io/v1

rebar.config.erl
=> chore(build): pin rebar_mix plugin version v0.4.0

apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_clients_api_SUITE.erl
=> api_clients time supports both rfc3339 and epoch(millisecond).

deploy/charts/emqx/templates/StatefulSet.yaml
Including this fix to 4.3 release: https://github.com/emqx/emqx/pull/5471
=> Backporting https://github.com/emqx/emqx/pull/5471 to main-v4.3

apps/emqx_authz/README.md, apps/emqx_authz/etc/emqx_authz.conf, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/src/emqx_authz_api_schema.erl, apps/emqx_authz/src/emqx_authz_postgresql.erl, apps/emqx_authz/src/emqx_authz_schema.erl, apps/emqx_authz/test/emqx_authz_SUITE.erl, apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl, apps/emqx_authz/test/emqx_authz_postgresql_SUITE.erl
=> chore(authz): rename pgsql to postgresql

apps/emqx/rebar.config, apps/emqx/src/emqx_authentication.erl, apps/emqx/test/emqx_authentication_SUITE.erl, apps/emqx_authn/include/emqx_authn.hrl, apps/emqx_authn/src/emqx_authn_app.erl, rebar.config
some minor coding style and naming refactoring.
slightly more important changes:
1. register providers in one call instead of doing gen_server:call in a foreach loop
2. pitfall: gen_server:call default timeout is 5 seconds
=> refactor(authn): minor refactors

apps/emqx/src/emqx.erl, apps/emqx/src/emqx_authz_cache.erl, apps/emqx/src/emqx_broker.erl, apps/emqx/src/emqx_broker_helper.erl, apps/emqx/src/emqx_message.erl, apps/emqx/src/emqx_mqtt_caps.erl, apps/emqx/src/emqx_mqueue.erl, apps/emqx/src/emqx_router.erl, apps/emqx/src/emqx_shared_sub.erl, apps/emqx/src/emqx_trie.erl, apps/emqx/src/emqx_types.erl, apps/emqx/test/emqx_request_handler.erl, apps/emqx_authz/include/emqx_authz.hrl, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl, apps/emqx_rule_engine/src/emqx_rule_funcs.erl
Fix ref a doesn't file `emqx_mqtt_types.erl`.
Ref `emqx_types.erl` instead of referencing `emqx_topic.erl` directly.
=> Type Spec fix

README-CN.md, README-RU.md, README.md
=> fix(README): fix command to run in build instructions

deploy/charts/emqx/README.md, deploy/charts/emqx/templates/StatefulSet.yaml, deploy/charts/emqx/values.yaml
Add secrets values as environment variables
=> Add envFromSecret

apps/emqx_modules/src/emqx_delayed.erl, apps/emqx_modules/src/emqx_delayed_api.erl
Add schema check and returns 400.
Delete with a doesn't exist msgid returns 404.
=> fix(delayed): delete with worong msgid return 200.

apps/emqx/src/emqx_listeners.erl, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_listeners.erl
Instead Undocumented 500 error.
=> mgmt_api_listeners bugfix.

README.md
=> chore(readme): Fix typo

bin/emqx, build, etc/BUILT_ON, rebar.config.erl, scripts/get-distro.sh
to make zip packages portable, we try to collect dynamic libs (.so files) for zip packages.
=> best-effort portable for zip packages

.github/workflows/run_fvt_tests.yaml
=> ci(relup): fix old vsn error

apps/emqx/src/emqx_connection.erl
=> fix(emqx_connection): Add backpressure to TCP connections

bin/emqx, build
=> build: copy dynamic libs for zip package

apps/emqx/test/emqx_mqtt_SUITE.erl
The mqtt QOS = 1  `Message-Expiry-Interval` test case failed occasionally.
If the broker stores  the 'Message-Expiry-Interval' message for almost the same time as when subscribe comes online again, the message expiration time sent to subscribe should remain the same, in other words, the time should always be **less than or equal** to the initial setting value.
```erlang
*** CT Error Notification 2021-09-27 00:43:43.726 ***
emqx_mqtt_SUITE:message_expiry_interval_not_exipred failed on line 133
Reason: {test_case_failed,{incorrect_publish,
{publish,
#{client_pid => <0.5148.3>,dup => false,
packet_id => 1,
payload => <<"this will be purged in 1s">>,
properties => #{'Message-Expiry-Interval' => 20},
qos => 1,retain => false,topic => <<"t/a">>}}}}
Full error description and stacktrace
=== …
```
=> fix(test): flaky mqtt expiry test case.

src/emqx.appup.src, src/emqx_channel.erl, src/emqx_cm.erl, test/emqx_cm_SUITE.erl
related pr: https://github.com/emqx/emqx-management/pull/331
=> Fix force kill after kick or discard timeout

apps/emqx_authz/include/emqx_authz.hrl, apps/emqx_authz/src/emqx_authz_api_mnesia.erl, apps/emqx_authz/test/emqx_authz_api_mnesia_SUITE.erl
use honconsc for authz-api-mnesia-refactor
=> Authz api mnesia refactor

bin/emqx
* set -o
* removed customisable boot file support
* removed customisable sys.config support
* refined usage info print-out
=> refactor bin/emqx

etc/emqx.conf, priv/emqx.schema
=> chore(cluster): add new type for dns auto cluster

apps/emqx_plugin_libs/src/emqx_trace/emqx_trace_api.erl, apps/emqx_plugin_libs/test/emqx_trace_SUITE.erl, lib-ce/emqx_modules/src/emqx_mod_trace_api.erl
=> fix: there should not be multiple layers of directories when download zip files.

.github/workflows/run_api_tests.yaml, .gitignore, apps/emqx_authn/src/emqx_authn_api.erl, apps/emqx_authz/src/emqx_authz_api_mnesia.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_bridge/src/emqx_bridge_api.erl, apps/emqx_dashboard/src/emqx_dashboard_api.erl, apps/emqx_management/src/emqx_mgmt_api_alarms.erl, apps/emqx_management/src/emqx_mgmt_api_banned.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_listeners.erl, apps/emqx_management/test/emqx_mgmt_api_test_util.erl, apps/emqx_modules/src/emqx_delayed_api.erl, apps/emqx_modules/src/emqx_topic_metrics_api.erl, apps/emqx_retainer/src/emqx_retainer_api.erl, apps/emqx_rule_engine/src/emqx_rule_engine_api.erl, apps/emqx_rule_engine/test/emqx_rule_engine_api_SUITE.erl
wrongly returned 200 => better code 204
=> Delete api status code

apps/emqx/src/emqx_cm.erl, apps/emqx/test/emqx_cm_SUITE.erl
Found while investigating https://emqx.atlassian.net/browse/EMQX-1834
=> Fix takeover race

apps/emqx/src/emqx_config.erl
if we don't define the field in emqx_exhook.conf
```
exhooks{
}
```
define schema as:
```erlang
roots() -> [exhook].
fields(exhook) ->
[ {request_failed_action,
sc(hoconsc:enum([deny, ignore]),
#{default => deny})}
```
the we can't get default field by emqx.
```erlang
> emqx:get_config([exhooks]).
* exception error: {config_not_found,[exhook]}
in function  emqx_config:do_get/2 (emqx_config.erl, line 401)
```
after the PR change:
```erlang
emqx:get_config([exhook]).
#{request_failed_action => deny}
```
=> fix: can't get default key if all key if default

.github/workflows/build_packages.yaml
=> ci: cancel otp vsn for docker image tag

apps/emqx/test/emqx_persistent_session_SUITE.erl
Fixes:
https://emqx.atlassian.net/browse/EMQX-1827
https://emqx.atlassian.net/browse/EMQX-1834
https://emqx.atlassian.net/browse/EMQX-1984
=> Fix flaky tests for persistent sessions

apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_keepalive.erl, apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/test/emqx_mgmt_clients_api_SUITE.erl
Port https://github.com/emqx/emqx/pull/6143
=> feat: set keepalive via http api

.ci/build_packages/tests.sh, deploy/packages/rpm/emqx.spec
port https://github.com/emqx/emqx/pull/5652 to 4.3
=> build: ensure openssl11

apps/emqx/src/emqx_authentication.erl
So that we do not have to transfer it
=> fix(authn): create chain tab in start_link

bin/emqx, build
=> build: copy only libcrypto and libtinfo

apps/emqx/test/emqx_trace_SUITE.erl, apps/emqx/test/emqx_trace_handler_SUITE.erl, apps/emqx_authn/src/emqx_authn_api.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl, apps/emqx_dashboard/test/emqx_swagger_requestBody_SUITE.erl, apps/emqx_dashboard/test/emqx_swagger_response_SUITE.erl, bin/emqx
1. `./bin/emqx ping` should pong on success.
2. Change HTTP API's max limit from 100 to 1000.
3. fix authn api return 500 when config format error.
=> Fix ping not return pong

apps/emqx/test/emqx_sys_mon_SUITE.erl
If the spawned process doesn't have enough time to be properly set up,
the returned stacktrace may be empty, making the test fail.  By
synchronizing the startup, we know that the process will have a proper
stacktrace by the time of the assertion.
=> test(flakiness): prevent possible flakiness in test

scripts/update_appup.escript
Currently, the update_appup.escript outputs as an error the full appup
file for external dependencies, even if all the changes are already
contained in the depency.  Here, we make it only output the missing
actions to be inserted, to aid in seeing what are the differences.
<details>
<summary> Output before: </summary>
```
ERROR: Appup file for the external dependency 'ekka' is not complete.
Missing changes: [{"0.8.1.4",
[{load_module,ekka_cluster_dns,brutal_purge,
soft_purge,[]},
{load_module,ekka_node_monitor,brutal_purge,
soft_purge,[]}]},
{"0.8.1.3",
[{load_module,ekka_node_monitor,brutal_purge,
soft_purge,[]},
{load_module,ekka_autocluster,brutal_purge,
soft_purge,[]},
{load_module,ekka_autoheal,brutal_purge,
soft_purge,[]},
{load_module,ekka_locker,brutal_purge,soft_purge,
[]}, …
```
=> chore(appup): make update_appup.escript output only differences for external dependencies

rebar.config
This version introduces rocksdb backend, and contains some little optimizations
=> chore(mria): Update dependency to 0.1.3

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.appup.src, apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_actions.erl, rebar.config
https://github.com/emqx/ecpool/pull/36
=> MQTT bridge hangs

apps/emqx_sn/src/emqx_sn.app.src, apps/emqx_sn/src/emqx_sn.appup.src, apps/emqx_sn/src/emqx_sn_registry.erl, apps/emqx_sn/test/emqx_sn_registry_SUITE.erl
create `emqx_sn_registry` table at runtime.
=> fix: e4.4.0 failed to join e4.3.0 cluster

apps/emqx/rebar.config, apps/emqx/test/emqx_persistent_session_SUITE.erl, rebar.config
Increase timeout on message receive and ensure more info when the test fails.
=> test(flaky_tests): fix persistent_session_SUITE

apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt.erl, src/emqx_vm.erl
=> fix(vm_mem): info calc and display

apps/emqx_plugin_libs/src/emqx_trace/emqx_trace.erl, apps/emqx_plugin_libs/src/emqx_trace/emqx_trace_api.erl, apps/emqx_plugin_libs/test/emqx_trace_SUITE.erl
When the start time of the trace is equal to the current time, it will cause it to fail to start directly, and then the trace file cannot be generated.
So I refactor the `find_closest_time/2` function.
=> fix: trace handler start time not correct

apps/emqx_plugin_libs/src/emqx_slow_subs/emqx_slow_subs.erl, lib-ce/emqx_modules/src/emqx_mod_slow_subs.erl, src/emqx_slow_subs/emqx_message_latency_stats.erl
1. limit the interval between calling hooks
2. improve the code of update threshold
=> fix(emqx_slow_subs): fix threshold related bugs

src/emqx_channel.erl
Sessions must not enqueue messages when another process is taking over
the client id, since it already passed on the message queue in the
session state.
Without this fix, messages arriving after `{takeover, 'begin'} to a
channel with no connection (i.e., a persistent session) would be lost.
(Backport of https://github.com/emqx/emqx/pull/6393)
=> fix(emqx_channel): fix race condition in session takeover

apps/emqx/src/emqx_types.erl, apps/emqx_exhook/etc/emqx_exhook.conf, apps/emqx_exhook/priv/protos/exhook.proto, apps/emqx_exhook/rebar.config, apps/emqx_exhook/src/emqx_exhook_handler.erl, apps/emqx_exhook/src/emqx_exhook_mngr.erl, apps/emqx_exhook/src/emqx_exhook_schema.erl, apps/emqx_exhook/src/emqx_exhook_server.erl, apps/emqx_exhook/src/emqx_exhook_sup.erl, apps/emqx_exhook/test/emqx_exhook_demo_svr.erl, apps/emqx_exhook/test/props/prop_exhook_hooks.erl, apps/emqx_gateway/rebar.config
4.4: https://github.com/emqx/emqx/pull/6076
=> Port exhook 4.4 features

etc/emqx.conf
revert part of changes in 289415b5aac36b1229b5fa3feccec90d2cf54e8e
=> revert(emqx_conf): zone.external.max_topic_levels

rebar.config, test/emqx_listeners_SUITE.erl
Do not merge, we'll change savonarola/cowboy to emqx/cowboy before merge.
=> [4.4] fix(wss): update cowboy & ranch for OTP24 compatibility

apps/emqx_authz/include/emqx_authz.hrl, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/src/emqx_authz_app.erl, apps/emqx_authz/src/emqx_authz_file.erl, apps/emqx_authz/src/emqx_authz_http.erl, apps/emqx_authz/src/emqx_authz_mnesia.erl, apps/emqx_authz/src/emqx_authz_mongodb.erl, apps/emqx_authz/src/emqx_authz_mysql.erl, apps/emqx_authz/src/emqx_authz_postgresql.erl, apps/emqx_authz/src/emqx_authz_redis.erl, apps/emqx_authz/src/emqx_authz_rule.erl, apps/emqx_authz/src/emqx_authz_utils.erl, apps/emqx_authz/test/emqx_authz_SUITE.erl
* Make behaviour for authz backends
* Hide all backend specific logic behind behaviour
=> chore(authz): encapsulate authz backend logic

apps/emqx_plugin_libs/src/emqx_trace/emqx_trace.erl, apps/emqx_plugin_libs/test/emqx_trace_SUITE.erl
Normal we create a topic trace by `[{<<"name", <<"test">>}, {<<"type", <<"topic">>}, {<<"topic", <<"test/#">>}]`
But if we add an extra clientid field:
`[{<<"name", <<"test">>}, {<<"type", <<"topic">>}, {<<"topic", <<"test/#">>}, {<<"clientid">>, <<"dev001">>}]`
it will create a topic filter by **clientid** `<<"dev001">>`.  we should filter by **topic**, not **clientid**.
So we should always get filter by type first.
=> fix(trace): create trace validate type and filter more strictly

src/emqx_trace_handler.erl, test/emqx_trace_handler_SUITE.erl
1. The clientid trace handler's filter is `binary_to_list(ClientId)`.
if the clientid is <<"abcd 漢字編碼"/utf8>> (not latin), the filter will become 
```
[97,98,99,100,32,230,188,162,229,173,151,231,183,168,231,162,188]
```
we should make utf8 list by `unicode:characters_to_list(ClientId)`:
```
[97,98,99,100,32,28450,23383,32232,30908]
```
so that the clientid inside the log meta can be matched successfully.
2. Don't record clientid if we filter by clientid.
=> fix: trace not work if clientid is utf8

apps/emqx_rule_engine/src/emqx_rule_events.erl
The pull request for doc changes is here: https://github.com/emqx/emqx-docs/pull/940
=> fix(rules): add SQL test examples for user properties

Makefile, apps/emqx_dashboard/src/emqx_dashboard.erl
=> fix(dashboard): enable dashboard by default

apps/emqx/src/emqx.erl, apps/emqx/src/emqx_broker.erl
=> fix(broker): Check broker status before dispatch

apps/emqx_modules/src/emqx_telemetry.erl
=> fix(telemetry): use required fields, rolling distro use PRETTY_NAME

apps/emqx_gateway/src/coap/emqx_coap_channel.erl, apps/emqx_gateway/src/emqx_gateway_api.erl, apps/emqx_gateway/src/emqx_gateway_api_clients.erl, apps/emqx_gateway/src/emqx_gateway_conf.erl, apps/emqx_gateway/src/emqx_gateway_http.erl, apps/emqx_gateway/src/emqx_gateway_insta_sup.erl, apps/emqx_gateway/src/emqx_gateway_schema.erl, apps/emqx_gateway/src/emqx_gateway_utils.erl, apps/emqx_gateway/src/exproto/emqx_exproto_impl.erl, apps/emqx_gateway/src/lwm2m/emqx_lwm2m_impl.erl, apps/emqx_gateway/src/lwm2m/emqx_lwm2m_xml_object_db.erl, apps/emqx_gateway/test/emqx_gateway_conf_SUITE.erl
- More precise HTTP error code
- Fix CoAP client info unsaved error
- Change some configurations to required
=> Gateway bug fixes

apps/emqx_authn/src/emqx_authn_api.erl
=> fix(authn): attempt to convert certificate content only when TLS is enabled

apps/emqx_bridge/src/emqx_bridge_http_schema.erl, apps/emqx_bridge/src/emqx_bridge_schema.erl, apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl, apps/emqx_connector/src/emqx_connector_http.erl, apps/emqx_connector/src/emqx_connector_mqtt.erl, apps/emqx_connector/src/mqtt/emqx_connector_mqtt_msg.erl
- fix(bridge): make direction defaults to egress if not provided
=> Bug fixes for data bridges

apps/emqx/rebar.config, apps/emqx_modules/src/emqx_rewrite_api.erl, rebar.config
I tried to rewrite a topic to an UTF8 topic using HTTP API, the request (`PUT /mqtt/topic_rewrite`) failed with following errors:
```
2021-12-27T14:15:37.515019+08:00 [error] crasher: initial call: cowboy_stream_h:request_process/3, pid: <0.3292.0>, registered_name: [], error: {#{exception => badarg,field => source_topic,path => "root.1",reason => failed_to_check_field},[{erlang,list_to_binary,[[47,20320,22909]],[]},{typerefl,'-binary/0-fun-0-',1,[{file,"/Users/liuxy/code/emqx50/_build/default/lib/typerefl/src/typerefl.erl"},{line,239}]},{hocon_schema_builtin,convert,2,[{file,"/Users/liuxy/code/emqx50/_build/default/lib/hocon/src/hocon_schema_builtin.erl"},{line,52}]},{hocon_schema,map_field,4,[{file,"/Users/liuxy/code/emqx50/_build/default/lib/hocon/src/hocon_schema.erl"},{line,703}]},{ho …
```
=> Fix utf8 topic rewrite

apps/emqx/rebar.config, apps/emqx/src/emqx_config.erl, rebar.config
the inlcude_dirs should be a dir list, not filename list.
=> fix(conf): can't include local/overide-conf file

apps/emqx_retainer/src/emqx_retainer.app.src, apps/emqx_retainer/src/emqx_retainer.appup.src, apps/emqx_retainer/src/emqx_retainer_cli.erl, apps/emqx_retainer/test/emqx_retainer_cli_SUITE.erl
=> fix(retainer): Fix topic printing

apps/emqx_retainer/src/emqx_retainer.erl
This reverts commit b80a01554b14442d777a7972aeac519d0afeb90e.
=> fix: Revert "fix(emqx_retainer): add support for RAP falg"

apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_management.appup.src, apps/emqx_management/src/emqx_mgmt_api_nodes.erl
fix(mgmt): fix node info format for specific node
=> fix(mgmt): fix node info format for specific node

apps/emqx/src/emqx_tls_lib.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_authz/src/emqx_authz_http.erl, apps/emqx_authz/src/emqx_authz_mongodb.erl, apps/emqx_authz/src/emqx_authz_schema.erl, apps/emqx_authz/test/emqx_authz_SUITE.erl, apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl, apps/emqx_authz/test/emqx_authz_http_SUITE.erl, apps/emqx_authz/test/emqx_authz_mongodb_SUITE.erl
=> chore(authz): increase coverage

.github/workflows/run_api_tests.yaml
=> chore(test): update api test script version

apps/emqx/rebar.config, apps/emqx_authz/src/emqx_authz_http.erl, apps/emqx_authz/src/emqx_authz_schema.erl, apps/emqx_connector/src/emqx_connector_http.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, rebar.config
Make sure http headers is a [{<<"content-type">>, <<"application/json">>}] proplist.
---------
don't use map('#{<<"content-type">>, <<"application/json">>}` because hocon always covert buildin map key as atom,
=> fix: make sure authz headers is binary.

apps/emqx_gateway/src/emqx_gateway_conf.erl, apps/emqx_gateway/src/emqx_gateway_utils.erl, apps/emqx_gateway/src/exproto/emqx_exproto_impl.erl, apps/emqx_gateway/src/lwm2m/emqx_lwm2m_impl.erl, apps/emqx_gateway/test/emqx_exproto_SUITE.erl, apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_app.erl, apps/emqx_management/src/emqx_mgmt_api_trace.erl, apps/emqx_management/src/emqx_mgmt_auth.erl, apps/emqx_management/test/emqx_mgmt_auth_api_SUITE.erl, apps/emqx_retainer/README.md, apps/emqx_retainer/etc/emqx_retainer.conf, apps/emqx_retainer/src/emqx_retainer_mnesia.erl, apps/emqx_retainer/src/emqx_retainer_schema.erl, apps/emqx_statsd/src/emqx_statsd_api.erl, apps/emqx_statsd/src/emqx_statsd_app.erl, apps/emqx_statsd/src/emqx_statsd_sup.erl
=> Merge 5.0 beta.3 to master

.github/workflows/run_test_cases.yaml
The static check is performed at regular intervals on the master branch, check [this PR](https://github.com/emqx/emqx/pull/6640)
=> ci(static checks): do not run static check

Makefile, rebar.config.erl
=> chore: add light dialyzer make target

.github/workflows/build_packages.yaml, .github/workflows/build_slim_packages.yaml, scripts/get-dep-refs.sh
speedup the cross_build_package job with build caches (quicer and rocksdb)
=> build cache for cross build packages

apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_management.appup.src, apps/emqx_retainer/src/emqx_retainer.app.src, apps/emqx_retainer/src/emqx_retainer.appup.src, apps/emqx_rule_engine/src/emqx_rule_engine.app.src, apps/emqx_rule_engine/src/emqx_rule_engine.appup.src, apps/emqx_rule_engine/src/emqx_rule_metrics.erl, src/emqx.app.src, src/emqx.appup.src
Based on v4.4-beta.1, this PR contains all the applications that need to be upgraded
=> chore: fix the app vsn and appup.src

README-CN.md, README-JP.md, README-RU.md, README.md
- Fixed Label of Badges image so that it shows all words starting with uppercase.
- Fixed an issue where the percentage shown for coverall was incorrect (**previously it showed 92%, but it should actually be 72%**)
=> chore(README): modify some badges

apps/emqx_rule_engine/src/emqx_rule_engine.appup.src, apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
https://askemq.com/t/topic/1486
=> fix(rule): deny POST rules or resources with empty ids

apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl
=> fix(emqx_mgmt): Fix formatting of client stats

apps/emqx_statsd/src/emqx_statsd_api.erl, apps/emqx_statsd/src/emqx_statsd_schema.erl
~~func refactor:~~
~~`emqx_dashboard_swagger:schema_with_example/2` and `emqx_dashboard_swagger:schema_with_examples/2`~~
~~=>~~
~~`emqx_dashboard_swagger:schema_with_meta/2`~~
`emqx_dashboard_swagger:schema_with_example(s)/2` refactor in later PR
=> refactor(api): statsd api swagger spec

src/emqx.appup.src, src/emqx_alarm.erl, src/emqx_app.erl, src/emqx_os_mon.erl, test/emqx_os_mon_SUITE.erl
Port: https://github.com/emqx/emqx/pull/6846/files to 4.2.11
=> fix: sys_mem alarm is not triggered after reboot.

.github/workflows/build_packages.yaml, .github/workflows/run_fvt_tests.yaml, scripts/relup-base-vsns.sh
=> ci: find relup base version using script scripts/relup-base-vsns.sh

apps/emqx/rebar.config, mix.exs, rebar.config
This ekka tag contains the core node discovery callback feature.
=> chore(ekka): update ekka -> 0.11.3

apps/emqx/etc/emqx.conf, apps/emqx/src/emqx_channel.erl, apps/emqx/src/emqx_keepalive.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/test/emqx_keepalive_SUITE.erl
1. Improve keepalive_backoff desc.
2. Transport mqtt desc from emqx.conf to emqx_schema.erl
=> fix(keepalive): keepalive desc improvement.

.github/workflows/run_api_tests.yaml, .github/workflows/run_broker_tests.yaml, .github/workflows/run_emqx_app_tests.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_relup_tests.yaml, .github/workflows/run_test_cases.yaml
https://github.com/emqx/emqx/actions/runs/1772855696/workflow
=> fix(ci): fix branch wildcard syntax

apps/emqx/src/emqx_schema.erl, apps/emqx_machine/src/emqx_machine.erl, mix.exs, rebar.config
Almost a full rewrite of the application. Reduced memory usage by about 10 times, added some features like "Very Important Processes", that are always collected.
=> feat(system_monitor): Bump version to 3.0.0

mix.exs, rebar.config
This version optimizes inserts into the postgres database
=> chore(system_monitor): Bump version to 3.0.2

apps/emqx/src/emqx_access_control.erl, apps/emqx/src/emqx_metrics.erl
Port from v4.3: https://github.com/emqx/emqx/pull/6811
=> feat(metrics): add acl metrics statistics

.github/workflows/build_packages.yaml
=> ci(build_packages): push muilt arch image for aws ecr

bin/emqx, bin/nodetool, lib-ee/emqx_license/src/emqx_license.erl, mix.exs, rebar.config.erl, rel/emqx_vars
Check license before node starts so that it does not crash.
=> feature(license): check license before node start

CHANGES-4.3.md, apps/emqx_management/src/emqx_management.app.src, apps/emqx_management/src/emqx_mgmt.erl, apps/emqx_management/src/emqx_mgmt_cli.erl, lib-ce/emqx_dashboard/src/emqx_dashboard.app.src
so that the pem files are reloaded immediately when a new TLS handshake is triggered.
=> feat: add cli to clean pem cache

scripts/apps-version-check.sh
https://github.com/emqx/emqx/pull/7005/commits/22ae8985c62db03554e4687b06c06ce8bcca7c5a
=> chore: exclude alpha beta and rc tags when checking app.src vsn bump

lib-ce/emqx_dashboard/src/emqx_dashboard.app.src, scripts/apps-version-check.sh
port https://github.com/emqx/emqx/pull/5879
=> Force appup for dashboard

apps/emqx/include/emqx.hrl, apps/emqx/include/emqx_mqtt.hrl, apps/emqx/include/emqx_placeholder.hrl, apps/emqx/src/emqx_release.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/test/emqx_proper_types.erl, apps/emqx_authn/src/emqx_authn_schema.erl, apps/emqx_authz/src/emqx_authz_schema.erl, apps/emqx_conf/include/emqx_conf.hrl, apps/emqx_conf/src/emqx_conf.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_dashboard/src/emqx_dashboard.erl, apps/emqx_dashboard/src/emqx_dashboard_token.erl, apps/emqx_gateway/src/emqx_gateway_api_clients.erl, apps/emqx_gateway/src/emqx_gateway_schema.erl, apps/emqx_machine/src/emqx_machine.erl, apps/emqx_management/src/emqx_mgmt_api_alarms.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_metrics.erl, apps/emqx_management/src/emqx_mgmt_api_nodes.erl, apps/emqx_management/src/emqx_mgmt_api_routes.erl, apps/emqx_management/src/emqx_mgmt_api_stats.erl, apps/emqx_modules/src/emqx_telemetry_api.erl, apps/emqx_plugin_libs/src/emqx_plugin_libs_ssl.erl, apps/emqx_plugins/src/emqx_plugins_schema.erl, lib-ee/emqx_license/src/emqx_license_app.erl, lib-ee/emqx_license/src/emqx_license_parser.erl, lib-ee/emqx_license/src/emqx_license_sup.erl
This should be the last PR for the EMQX (no space) epic, on `master` branch.
=> chore: EMQ X -> EMQX in source code

apps/emqx/rebar.config, mix.exs, rebar.config
print lock owner status before killing it
=> fix(ekka): pin version 0.12.1

scripts/pkg-tests.sh
`ARCH` is always set, so the `-z ${ARC}` condition will never be true.
=> chore(pkg-tests.sh): delete dead code

apps/emqx/src/emqx_cm.erl, apps/emqx/test/emqx_cm_SUITE.erl
=> refactor(cm): force kill the proc that failed to response takover call

apps/emqx_conf/etc/emqx_conf.conf, apps/emqx_conf/etc/emqx_conf.md, apps/emqx_conf/src/emqx_conf.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_conf/test/emqx_conf_schema_tests.erl, bin/emqx, lib-ee/emqx_enterprise_conf/test/emqx_enterprise_conf_schema_tests.erl, rel/emqx_vars
now data_dir config is respected by boot script as well as
EMQX application after booted
=> fix(data_dir): get data_dir config in the right way

deploy/charts/emqx/templates/configmap.env.yaml
=> fix(helm): fix configmap.env template

bin/install_upgrade.escript
If the target vsn is in `unpacked` state, but the release dir `releases/<vsn>` is removed, then installing the target vsn
again will fail with error `{error,enoent}`.
In this case we should extract the tar ball again and then continue to install the release.
=> fix(relup): release upgrade failed if release dir is removed

apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_config_handler.erl, apps/emqx/src/emqx_map_lib.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/test/emqx_authentication_SUITE.erl, apps/emqx/test/emqx_config_handler_SUITE.erl, apps/emqx_authz/src/emqx_authz_api_schema.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_bridge/src/emqx_bridge_app.erl, apps/emqx_conf/src/emqx_conf_schema.erl, apps/emqx_connector/test/emqx_connector_api_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_configs.erl, apps/emqx_modules/test/emqx_rewrite_SUITE.erl, apps/emqx_plugins/src/emqx_plugins_schema.erl, apps/emqx_slow_subs/src/emqx_slow_subs.erl
- fix jsonable_map's value is not correct whenit is an array.
- make emqx_config_handler's coverage > 90%.
- don't use hocon local_ref in config hocon schema.
=> chore: add more test for emqx_config_handler

apps/emqx_auth_mongo/rebar.config, scripts/update_appup.escript
Updates the mongodb client version to include the deadloop fix.
=> fix: update mongodb client to include deadloop fix

deploy/charts/emqx/templates/StatefulSet.yaml
=> build(helm): add preStop command for container

.github/workflows/spelling.yml
Just a test, not sure if this is the correct way forward.
=> ci(spellcheck): Use a different action

CHANGES-4.3.md, lib-ce/emqx_dashboard/src/emqx_dashboard_admin.erl
https://github.com/emqx/emqx/issues/7259
=> chore: Prompt user how to change the dashboard default password when emqx start

.github/workflows/build_packages.yaml, .github/workflows/build_slim_packages.yaml, .github/workflows/run_emqx_app_tests.yaml, .github/workflows/run_fvt_tests.yaml, .github/workflows/run_relup_tests.yaml, .github/workflows/run_test_cases.yaml, mix.exs, rebar.config, scripts/get-dep-refs.sh
for fast pre-built binary download of rocksdb nif
=> chore: pin mria 0.2.1

apps/emqx/include/emqx_authentication.hrl, apps/emqx/src/emqx_authentication.erl, apps/emqx/src/emqx_authentication_config.erl, apps/emqx/test/emqx_authentication_SUITE.erl, apps/emqx_authn/src/emqx_authn_api.erl, apps/emqx_authn/test/emqx_authn_api_SUITE.erl, apps/emqx_authz/include/emqx_authz.hrl, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/src/emqx_authz_api_schema.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_authz/test/emqx_authz_SUITE.erl, apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl, apps/emqx_exhook/include/emqx_exhook.hrl, apps/emqx_exhook/src/emqx_exhook_api.erl, apps/emqx_exhook/src/emqx_exhook_mgr.erl, apps/emqx_exhook/test/emqx_exhook_api_SUITE.erl, apps/emqx_management/src/emqx_mgmt_api_plugins.erl
Move api now use the follow style
```
{"position": "top"}
{"position": "bottom"}
{"position": "before|after:[mechanism]:[id]"} # authn
{"position": "before|after:[type]"}           # authz
{"position": "before|after:[name]"}           # exhook
```
=> Unified move api

apps/emqx/rebar.config, apps/emqx_connector/rebar.config, apps/emqx_retainer/rebar.config, mix.exs, rebar.config
emqtt 1.4.8 changed to structured logging.
=> chore: update emqtt to 1.4.8

.github/workflows/run_test_cases.yaml, Makefile, apps/emqx_auto_subscribe/test/emqx_auto_subscribe_SUITE.erl, apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl, scripts/docker-ct-apps, scripts/find-apps.sh
=> ci: run ct in concurrent jobs

apps/emqx/src/emqx_limiter/etc/emqx_limiter.conf, apps/emqx/src/emqx_limiter/src/emqx_htb_limiter.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_app.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_container.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_manager.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_server.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_server_sup.erl, apps/emqx/src/emqx_schema.erl, apps/emqx/test/emqx_channel_SUITE.erl, apps/emqx/test/emqx_ratelimiter_SUITE.erl, apps/emqx/test/emqx_ws_connection_SUITE.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, apps/emqx_retainer/etc/emqx_retainer.conf, apps/emqx_retainer/src/emqx_retainer_dispatcher.erl, apps/emqx_retainer/src/emqx_retainer_schema.erl, apps/emqx_retainer/test/emqx_retainer_SUITE.erl
1. simplify the config schema
2. simplify the implementation and remove the group(zone) level
3. improve test case
=> feat(limiter): simplify the implementation and configuration

CHANGES-4.3.md, src/emqx_channel.erl, test/emqx_channel_SUITE.erl
fix https://github.com/emqx/emqx/issues/7241
=> fix(channel): send DISCONNECT packet if connection has been kicked

apps/emqx_psk/src/emqx_psk.erl, apps/emqx_psk/src/emqx_psk_schema.erl, apps/emqx_psk/test/emqx_psk_SUITE.erl
=> test(psk): improve test coverage

apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
There are some bugs when hocon parses escape characters.
example:
Input
``` erlang
rule_engine {
ignore_sys_message = true
rules {
"122940d3" {
description = "aa"
enable = true
name = "rule:ibah"
outputs = [
{
args {}
function = "console"
}
]
sql = "SELECT * \n  FROM \"t/1\""
}
}
}
```
output
``` erlang
{ok,#{<<"rule_engine">> =>
#{<<"ignore_sys_message">> => true,
<<"rules">> =>
#{<<"122940d3">> =>
#{<<"description">> => <<"aa">>,<<"enable">> => true,
<<"name">> => <<"rule:ibah">>,
<<"outputs">> => [#{<<"function">> => <<"console">>}],
<<"sql">> => <<"SELECT * \\n  FROM \"t/1\"">>}}}}}
```
bug: \n ->\\\n
This bug is temporarily bypassed here, and the next version will fix it.
=> fix(rule): replace sql crlf with spaces

apps/emqx_management/test/emqx_mgmt_api_test_util.erl, apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl, apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl
=> test(prometheus): improve test coverage to 88%

apps/emqx/src/emqx_schema.erl, apps/emqx_exhook/src/emqx_exhook_schema.erl, apps/emqx_gateway/src/emqx_gateway_schema.erl
=> docs: add more schema desc

apps/emqx_modules/src/emqx_modules.erl, apps/emqx_modules/src/emqx_modules_app.erl, apps/emqx_modules/src/emqx_telemetry.erl, apps/emqx_modules/test/emqx_telemetry_SUITE.erl
Adds to telemetry:
- MQTT runtime insights
- Advanced MQTT features
=> Telemetry revamp part2

scripts/update-appup.sh
so it can handle switch between tags
=> chore: fix appup update script

apps/emqx_authn/src/emqx_authn_api.erl, apps/emqx_connector/rebar.config
Do NOT merge it before https://github.com/emqx/eredis/pull/12 and https://github.com/emqx/eredis_cluster/pull/19 merged and taged
=> fix authn redis api and eredis_cluster version

.ci/build_packages/tests.sh, scripts/update-appup.sh
=> chore(appup): fix update-appup.sh

apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_authz/src/emqx_authz_file.erl, apps/emqx_authz/src/emqx_authz_http.erl, apps/emqx_authz/src/emqx_authz_mnesia.erl, apps/emqx_authz/src/emqx_authz_mongodb.erl, apps/emqx_authz/src/emqx_authz_mysql.erl, apps/emqx_authz/src/emqx_authz_postgresql.erl, apps/emqx_authz/src/emqx_authz_redis.erl, apps/emqx_authz/test/emqx_authz_SUITE.erl, apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl, apps/emqx_authz/test/emqx_authz_http_SUITE.erl
We should add `Test Data Resource Connection` for authn/authz.
Just like rule-engine
https://github.com/emqx/emqx/blob/d72da3ecf6bab8258c972678900515dda5b3cb39/apps/emqx_connector/src/emqx_connector_api.erl#L202-L208
==>
https://github.com/emqx/emqx/blob/d72da3ecf6bab8258c972678900515dda5b3cb39/apps/emqx_connector/src/emqx_connector.erl#L97-L98
==>
https://github.com/emqx/emqx/blob/d72da3ecf6bab8258c972678900515dda5b3cb39/apps/emqx_bridge/src/emqx_bridge.erl#L277-L284
=> fix(authz): rm authz source update dry_run

apps/emqx_modules/rebar.config, apps/emqx_modules/src/emqx_modules_app.erl, apps/emqx_modules/src/emqx_modules_conf.erl, apps/emqx_modules/src/emqx_telemetry.erl, apps/emqx_modules/src/emqx_telemetry_api.erl, apps/emqx_modules/src/proto/emqx_telemetry_proto_v1.erl, apps/emqx_modules/test/emqx_delayed_SUITE.erl, apps/emqx_modules/test/emqx_rewrite_SUITE.erl, apps/emqx_modules/test/emqx_rewrite_api_SUITE.erl, apps/emqx_modules/test/emqx_telemetry_SUITE.erl, apps/emqx_modules/test/emqx_telemetry_api_SUITE.erl, apps/emqx_modules/test/emqx_topic_metrics_SUITE.erl, apps/emqx_modules/test/emqx_topic_metrics_api_SUITE.erl
* improve `emqx_rewrite_api` coverage
* improve `emqx_telemetry_api` coverage
* refactor `emqx_telemetry` to use config clustering for settings
=> chore(emqx_modules): improve emqx_rewrite_api and emqx_telemetry_api coverage

apps/emqx_plugin_libs/src/emqx_plugin_libs.app.src, apps/emqx_plugin_libs/src/emqx_plugin_libs.appup.src, apps/emqx_plugin_libs/src/emqx_plugin_libs_ssl.erl, apps/emqx_plugin_libs/test/emqx_plugin_libs_ssl_tests.erl, apps/emqx_rule_engine/src/emqx_rule_engine.erl, bin/install_upgrade.escript
The GUI has "etc/certx/..." hard coded as defaults.
However this relative path only works when it's a zip package
or when running in docker.
The other possible abs path is the upload dir
=> fix(ssl): try to guess cert file paths

apps/emqx/rebar.config, apps/emqx_connector/rebar.config, apps/emqx_retainer/rebar.config, mix.exs, rebar.config
=> chore: update dependency app versions

CHANGES-4.3.md, rebar.config
=> feat: mnesia wait_for_table diagnosis logging

mix.exs, rebar.config
=> feat: diagnostic logging for mnesia wait_for_table

include/emqx_release.hrl
We will tag v4.4.3-rc.1 after this PR merged
=> Release v4.4.3-rc.1: bump vsn

priv/emqx.schema
Fixes issue with string being used instead of binary
=> Per group sub fix

priv/emqx.schema, src/emqx.appup.src, src/emqx_limiter.erl, src/emqx_listeners.erl, src/emqx_sys.erl, test/emqx_sys_SUITE.erl
Port :https://github.com/emqx/emqx/pull/7443/files and https://github.com/emqx/emqx/pull/7137/files
=> fix: add update_conf function for emqx_conf.

apps/emqx/src/emqx_schema.erl, apps/emqx/src/emqx_tls_lib.erl, apps/emqx_authn/src/emqx_authn_api.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
For authn/authz, do not show certs content in HTTP api response.
=> 5.0 provide defaults for ssl files

apps/emqx/include/emqx_access_control.hrl, apps/emqx/src/emqx_schema.erl, apps/emqx_authn/src/emqx_authn.erl, apps/emqx_authn/src/emqx_authn_api.erl, apps/emqx_authn/src/emqx_authn_password_hashing.erl, apps/emqx_authn/src/simple_authn/emqx_authn_http.erl, apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl, apps/emqx_authn/src/simple_authn/emqx_authn_mnesia.erl, apps/emqx_authn/src/simple_authn/emqx_authn_mongodb.erl, apps/emqx_authn/src/simple_authn/emqx_authn_mysql.erl, apps/emqx_authn/src/simple_authn/emqx_authn_pgsql.erl, apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl, apps/emqx_authz/include/emqx_authz.hrl, apps/emqx_authz/src/emqx_authz_api_mnesia.erl, apps/emqx_authz/src/emqx_authz_api_schema.erl, apps/emqx_authz/src/emqx_authz_schema.erl, apps/emqx_connector/src/emqx_connector_mongo.erl, apps/emqx_connector/src/emqx_connector_redis.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, apps/emqx_management/src/emqx_mgmt_api_alarms.erl, apps/emqx_management/src/emqx_mgmt_api_banned.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl, apps/emqx_management/src/emqx_mgmt_api_configs.erl, apps/emqx_management/src/emqx_mgmt_api_topics.erl, git-blame-ignore-revs, scripts/check-format.sh
- refined authn/authz api fields required attribute.
- fix authz-http fill default `headers` behavior same with authn-http
=> refine authn/authz api fields

deploy/charts/emqx/README.md, deploy/charts/emqx/templates/secret.yaml, deploy/charts/emqx/templates/service-monitor.yaml, deploy/charts/emqx/values.yaml
same to https://github.com/emqx/emqx/pull/5948, but update api path to v5
=> feat(helm): add service monitor for prometheus

bin/emqx.cmd, bin/emqx_ctl.cmd
Otherwise it's impossible to troubleshoot when werl fail to start
=> fix(windows): boot console and remote_console from erl not werl

mix.exs, rebar.config
Diff: https://github.com/ieQu1/system_monitor/commit/95db1792e2763ba2af1cf79484cac383ebec8192
=> chore(system_monitor): Bump version to 3.0.3

apps/emqx/rebar.config, apps/emqx/src/emqx_config.erl, apps/emqx/src/emqx_limiter/src/emqx_limiter_schema.erl, apps/emqx/src/emqx_listeners.erl, apps/emqx_bridge/src/emqx_bridge_api.erl, apps/emqx_dashboard/i18n/emqx_dashboard_i18n.conf, apps/emqx_dashboard/src/emqx_dashboard.erl, apps/emqx_dashboard/src/emqx_dashboard_config.erl, apps/emqx_dashboard/src/emqx_dashboard_monitor.erl, apps/emqx_dashboard/src/emqx_dashboard_schema.erl, apps/emqx_dashboard/src/emqx_dashboard_sup.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl, apps/emqx_dashboard/test/emqx_dashboard_api_test_helpers.erl, apps/emqx_dashboard/test/emqx_dashboard_bad_api_SUITE.erl, apps/emqx_dashboard/test/emqx_dashboard_error_code_SUITE.erl, apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl, apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl, apps/emqx_dashboard/test/emqx_swagger_remote_schema.erl, apps/emqx_dashboard/test/emqx_swagger_requestBody_SUITE.erl, apps/emqx_dashboard/test/emqx_swagger_response_SUITE.erl, apps/emqx_machine/src/emqx_restricted_shell.erl, apps/emqx_management/src/emqx_mgmt_api_configs.erl, apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl, apps/emqx_prometheus/rebar.config, mix.exs, rebar.config, scripts/merge-i18n.escript
obfuscate sensitive data as "******"
=> feat: obfuscate sensitive values default_password

apps/emqx/src/emqx_logger_jsonfmt.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
Make error messages more readable.
=> fix: imporve hocon check failed error

apps/emqx/i18n/emqx_limiter_i18n.conf, apps/emqx/i18n/emqx_schema_i18n.conf, apps/emqx/src/emqx_schema.erl, apps/emqx_authn/i18n/emqx_authn_jwt_i18n.conf, apps/emqx_authn/i18n/emqx_authn_mysql_i18n.conf, apps/emqx_dashboard/i18n/emqx_dashboard_i18n.conf, apps/emqx_psk/i18n/emqx_psk_i18n.conf, apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
Since we are converting the desc of `*_schema.erl` to an i18n conf file. This PR will continue to handle spellcheck errors until after rc.2 is released
=> Make spellcheck happy

.github/workflows/build_slim_packages.yaml
testing the runners at here:
~~https://github.com/emqx/emqx/actions/runs/2232128780~~
https://github.com/emqx/emqx/runs/6191222595?check_suite_focus=true
=> ci: build slim packages on self-hosted runners

CHANGES-4.3.md, rebar.config
Continuation of
https://github.com/emqx/eredis_cluster/pull/20
=> chore(eredis_cluster): bump

apps/emqx_management/src/emqx_mgmt_api_plugins.erl, apps/emqx_plugins/src/emqx_plugins.erl
2022-04-28T14:13:01.397070+08:00 [warning] exception: error, line: 111, mfa: minirest_handler:apply_callback/3, path: /plugins/install, reason: {badmatch,{"test.key",[]}}, stacktrace: [{emqx_plugins,parse_name_vsn,1,[{file,"emqx_plugins.erl"},{line,689}]},{emqx_mgmt_api_plugins,upload_install,2,[{file,"emqx_mgmt_api_plugins.erl"},{line,322}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,106}]},{minirest_handler,handle,2,[{file,"minirest_handler.erl"},{line,39}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,26}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"cowboy_stream_h.erl"},{line,318}]},{cowboy_stream_h,request_process,3,[{file,"cowboy_stream_h.erl"},{line,302}]},{proc_lib,init_p_do_app …
=> fix: bad plugin file upload crash

apps/emqx_gateway/src/emqx_gateway_conf.erl, apps/emqx_gateway/src/emqx_gateway_schema.erl, apps/emqx_gateway/src/exproto/emqx_exproto_impl.erl, apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl, apps/emqx_gateway/test/emqx_gateway_test_utils.erl, git-blame-ignore-revs
- chore(gw): add default value for lwm2m gateway
- chore(ignore-file): delete error commit hash
- feat(gw-exproto): save ssl files for server&handler option
=> exproto save ssl files

apps/emqx/src/emqx_tls_lib.erl, apps/emqx/test/emqx_tls_lib_tests.erl, apps/emqx_conf/i18n/emqx_conf_schema.conf, apps/emqx_dashboard/src/emqx_dashboard_config.erl, apps/emqx_dashboard/test/emqx_dashboard_api_test_helpers.erl, apps/emqx_management/src/emqx_mgmt_api_configs.erl, apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
add required_keys option to ssl key options.
=> fix: dashboard https without deafult pem/keyfile

apps/emqx/src/emqx_authentication.erl, apps/emqx/src/emqx_authn_authz_metrics_sup.erl, apps/emqx/src/emqx_metrics.erl, apps/emqx/src/emqx_metrics_worker.erl, apps/emqx/test/emqx_metrics_SUITE.erl, apps/emqx/test/emqx_metrics_worker_SUITE.erl, apps/emqx_authn/src/emqx_authn_api.erl, apps/emqx_authn/test/emqx_authn_http_SUITE.erl, apps/emqx_authn/test/emqx_authn_https_SUITE.erl, apps/emqx_authn/test/emqx_authn_jwt_SUITE.erl, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_plugin_libs/src/proto/emqx_plugin_libs_proto_v1.erl, apps/emqx_resource/include/emqx_resource.hrl, apps/emqx_resource/src/emqx_resource.erl, apps/emqx_resource/src/emqx_resource_instance.erl, apps/emqx_resource/src/emqx_resource_sup.erl, apps/emqx_rule_engine/src/emqx_rule_engine.erl, apps/emqx_rule_engine/src/emqx_rule_engine_sup.erl, apps/emqx_rule_engine/src/emqx_rule_runtime.erl, scripts/git-hook-pre-commit.sh
execute `./[scripts/git-hook-pre-commit.sh -w` to reformat changed `.erl` files.
=> test: ensure emqx_metrics gen_server stopped after each test

deploy/packages/emqx.service
fixes: https://github.com/emqx/emqx/issues/7825
Otherwise ubuntu may have trouble to boot
=> fix: use /bin/bash in systemd service file

.github/workflows/run_test_cases.yaml
also see: https://github.com/emqx/emqx-cdk-int/pull/5
tests with the new runners.
https://github.com/qzhuyan/emqx/runs/6216207654?check_suite_focus=true
=> cI: ct self-hosted pull image from docker proxy instead 

apps/emqx/src/emqx_listeners.erl, apps/emqx/src/emqx_tls_lib.erl, apps/emqx/test/emqx_tls_lib_tests.erl, apps/emqx_gateway/i18n/emqx_gateway_api_clients_i18n.conf, apps/emqx_gateway/src/coap/emqx_coap_channel.erl, apps/emqx_gateway/src/emqx_gateway_api_clients.erl, apps/emqx_gateway/src/emqx_gateway_http.erl, apps/emqx_gateway/src/mqttsn/emqx_sn_channel.erl, apps/emqx_gateway/src/stomp/emqx_stomp_channel.erl, apps/emqx_management/src/emqx_mgmt_api_clients.erl
- fix(gw): fix bad conn property type
- fix(gw): fix bad_ssl_config bad match
=> Fix gateway listener API return 500

apps/emqx_exhook/src/emqx_exhook_api.erl, apps/emqx_exhook/src/emqx_exhook_mgr.erl, apps/emqx_exhook/test/emqx_exhook_SUITE.erl, apps/emqx_exhook/test/emqx_exhook_api_SUITE.erl
Refine status code.
Fix ssl ciphers raw list.
Make sure config update error be thrown.
=> Fix exhook api

apps/emqx_conf/i18n/emqx_conf_schema.conf, apps/emqx_plugins/src/emqx_plugins.erl
Make logging more friendly if we can't stop plugins.
=> docs: more clear about stop plugins error.

mix.exs, rebar.config
In ehttpc v0.2.0, we have optimized the implementation for request collection
to reduce resource consumption. see: emqx/ehttpc#31
=> chore: update ehttpc to 0.2.0

apps/emqx_authn/src/emqx_authn_utils.erl, apps/emqx_authn/src/simple_authn/emqx_authn_http.erl, apps/emqx_authn/src/simple_authn/emqx_authn_mongodb.erl, apps/emqx_authn/src/simple_authn/emqx_authn_mysql.erl, apps/emqx_authn/src/simple_authn/emqx_authn_pgsql.erl, apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl, apps/emqx_authn/test/emqx_authn_redis_SUITE.erl, apps/emqx_authz/src/emqx_authz.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_authz/src/emqx_authz_file.erl, apps/emqx_authz/src/emqx_authz_http.erl, apps/emqx_authz/src/emqx_authz_jwt.erl, apps/emqx_authz/src/emqx_authz_mnesia.erl, apps/emqx_authz/src/emqx_authz_mongodb.erl, apps/emqx_authz/src/emqx_authz_mysql.erl, apps/emqx_authz/src/emqx_authz_postgresql.erl, apps/emqx_authz/src/emqx_authz_redis.erl, apps/emqx_authz/src/emqx_authz_utils.erl, apps/emqx_gateway/test/emqx_gateway_authz_SUITE.erl, apps/emqx_resource/src/emqx_resource.erl
Force stop resource (maybe disconnect) when authn/authz config updating with `enable = false`.
And use emqx_resource:recreate/3 to prvent delete resource metrics.
=> Refactor authn authz resource

apps/emqx_rule_engine/src/emqx_rule_events.erl
ported: https://github.com/emqx/emqx/pull/7962
=> feat(rule-engine): add proto_name/proto_ver for $event/client_disconnected event

CHANGES-4.3.md, apps/emqx_management/src/emqx_management.appup.src
Update changes.md and appup.src for https://github.com/emqx/emqx/pull/8005
=> chore: update changes and appup.src for emqx_management

apps/emqx/src/emqx_trace/emqx_trace.erl
Get rid of `-mnesia(boot)` callback (my end goal is to eliminate them eventually), optimize read access.
=> fix(emqx_trace): Read the data locally

apps/emqx_modules/src/emqx_telemetry.erl, apps/emqx_modules/test/emqx_telemetry_SUITE.erl
In order for the node and cluster UUIDs used by telemetry to survive
database purges, we'll save the generated UUIDs to files in EMQX's
data directory as well.
=> feat(telemetry): save uuids to files

apps/emqx/src/emqx_session.erl, apps/emqx/src/emqx_shared_sub.erl, apps/emqx/test/emqx_shared_sub_SUITE.erl
https://github.com/emqx/emqx/pull/7807 but for 5.0
=> Shared redispatch for 5.0

apps/emqx_modules/src/emqx_rewrite.erl, apps/emqx_modules/test/emqx_rewrite_SUITE.erl
=> feat(rewrite): Support %u and %c placeholders in topic rewrite rules

bin/emqx
* Turn off debug print when need to capture stderr output
* Turn off debug print for error messages before exit
=> fix(bin/emqx): turn off debug print when need to capture stderror

apps/emqx/rebar.config, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, apps/emqx_prometheus/rebar.config, apps/emqx_retainer/src/emqx_retainer_schema.erl, mix.exs, rebar.config
delete stacktrace from message.
```erlang
{"code": "BAD_REQUEST", "message": "#{path => \"backend.index_specs\",
reason => {list_index_spec_limited,#{default => [[1,2,3],[1,3],[2,3],[3]]}},
type => validation_error,value => tdd}" }
--
```
=> chore: better hocon validate msg

.github/workflows/elixir_apps_check.yaml, apps/emqx_conf/etc/emqx_conf.conf, apps/emqx_machine/src/emqx_machine_boot.erl, mix.exs, rebar.config.erl
Hide `node.applicaitons` in the `emqx.conf` file to be able to provide a clean configuration.
=> feat: change node.applications default to []

deploy/charts/emqx/templates/ingress.dashboard.yaml, deploy/charts/emqx/templates/ingress.mgmt.yaml, deploy/charts/emqx/templates/ingress.wss.yaml
Fix https://github.com/emqx/emqx/issues/8131
=> fix: fix helm install failed when enable ingress

apps/emqx/test/emqx_common_test_helpers.erl, apps/emqx/test/emqx_router_helper_SUITE.erl, apps/emqx_conf/test/emqx_conf_app_SUITE.erl, apps/emqx_modules/test/emqx_telemetry_SUITE.erl
Helper for testing on multiple nodes
=> Multinode helper

apps/emqx/src/emqx_sys.erl, apps/emqx_management/src/emqx_mgmt_util.erl
This impacts:
* CLI printout
* REST API nodes info
* sys-message publish to `$SYS/brokers/node()/datetime` topic
=> refactor: expose rfc3339 datetime string

apps/emqx_rule_engine/src/emqx_rule_engine_app.erl, apps/emqx_rule_engine/src/emqx_rule_engine_cli.erl
Shows rules in this format:
```
Id:
3a0ad970
Name:
rule_qdet
Description:
foo bar
Enabled:
true
SQL:
SELECT   * 
FROM   "t/#"
Created at:
2022-06-13T15:15:42.896+02:00
Updated at:
2022-06-13T15:15:42.896+02:00
Actions:
Function:
republish
Args:
#{payload => <<>>,qos => 0,retain => <<"${retain}">>,topic => <<"fdfd">>}
```
=> feat(rule_engine): CLI to list rules

apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl, apps/emqx_authn/test/emqx_authn_jwt_SUITE.erl
=> chore(jwt authn): improve tests

.gitignore, apps/emqx_conf/etc/emqx_conf.conf, apps/emqx_conf/src/emqx_conf.erl, mix.exs, rebar.config.erl
https://github.com/emqx/hocon/pull/202
=> chore: add emqx-example-en.conf in release

apps/emqx/src/emqx_hocon.erl
Sorry, the other PR was merged too soon.
=> chore: fix typos

deploy/charts/emqx/README.md, deploy/charts/emqx/templates/StatefulSet.yaml, deploy/charts/emqx/values.yaml
Fix https://github.com/emqx/emqx/issues/8144
=> chore(helm): add pod annotation

src/emqx.appup.src, src/emqx_access_rule.erl
Port of https://github.com/emqx/emqx/pull/8280
=> fix(acl): do not leave placeholders unreplaced (4.2)

CHANGES-4.3.md, apps/emqx_exhook/src/emqx_exhook.appup.src, apps/emqx_exhook/src/emqx_exhook_server.erl, rebar.config
see: https://github.com/emqx/emqx/issues/7569
=>  Ensuring that exhook dispatches the client events are sequential

apps/emqx/src/emqx.appup.src, apps/emqx/src/emqx_channel.erl, apps/emqx/test/emqx_broker_SUITE.erl
Port of https://github.com/emqx/emqx/pull/8288
=> fix(hooks): allow `client.subscribe` hook to reject subscriptions

scripts/get-dashboard.sh
chore: update dashboard version
=> merge main-v4.3 into main-v4.4

CHANGES-4.3.md, apps/emqx_auth_jwt/src/emqx_auth_jwt.app.src, apps/emqx_auth_jwt/src/emqx_auth_jwt.appup.src, apps/emqx_auth_jwt/src/emqx_auth_jwt_svr.erl, apps/emqx_auth_jwt/test/emqx_auth_jwt_SUITE.erl
* fix timer renewal for jwks update, currently jwks client crashes on timer update
* do not crash on `nbf` and `iat` negative validation result
* added tests for these cases
=> Fix JWT handling

mix.exs, rebar.config.erl
build error with jq on _**[gcc 12.1.0]**_, _**[OTP 24.3.2]**_
=> build: conditionally build jq

apps/emqx_authn/src/emqx_authn_utils.erl, apps/emqx_authz/src/emqx_authz_utils.erl, apps/emqx_resource/src/emqx_resource.app.src, apps/emqx_resource/src/emqx_resource.appup.src, apps/emqx_resource/src/emqx_resource_manager.erl
- chore: auto retry disconnected authn/authz resources
- chore: using standard log format
=> AuthN/Z: automaticly re-connect to disconnected resources

CHANGES-4.3.md, apps/emqx_management/src/emqx_mgmt_http.erl
```erlang
1> [a, b, c] ++ [d] -- [a].
[a,b,c,d]
2> ([a, b, c] ++ [d]) -- [a].
[b,c,d]
```
=> fix: fix list difference precedence

rebar.config
see https://github.com/emqx/ekka/pull/169
=> chore: update ekka version

Makefile, apps/emqx_prometheus/i18n/emqx_prometheus_schema_i18n.conf, apps/emqx_statsd/i18n/emqx_statsd_schema_i18n.conf
1. statsd => [StatsD](https://github.com/statsd/statsd), and delete milliseconds desc.
2. upgrade dashboard to v1.0.3
3. https://github.com/emqx/emqx-docs/pull/1310
=> chore: improve metrics desc

CHANGES-5.0.md, apps/emqx_authn/src/emqx_authn_user_import_api.erl, apps/emqx_authz/src/emqx_authz_api_sources.erl, apps/emqx_dashboard/src/emqx_dashboard_api.erl, apps/emqx_dashboard/src/emqx_dashboard_swagger.erl, apps/emqx_gateway/src/emqx_gateway.app.src, apps/emqx_gateway/src/emqx_gateway_api_authn_user_import.erl
=> fix: fix bad swagger format

.github/workflows/run_fvt_tests.yaml, deploy/charts/emqx/Chart.yaml, deploy/charts/emqx/values.yaml, deploy/docker/docker-entrypoint.sh
Change default cluster.discovery_strategy = dns in helm chart
=> chore: update docker entry point, support dns cluster in k8s

apps/emqx/rebar.config, mix.exs, rebar.config
Mainly: https://github.com/emqx/erlang-rocksdb/pull/7
=> chore: bump ekka -> 0.13.3

.github/workflows/release.yaml
Before release the version, need to update the version and appVerison of the helm chart, the version just `[0-9].[0-9].[0-9]`
In OpenSource, file in `deploy/charts/emqx/Chart.yaml`
In Enterprise, file in `deploy/charts/emqx-ee/Chart.yaml`
=> ci: use action to update helm repo

deploy/charts/emqx/README.md, deploy/charts/emqx/templates/StatefulSet.yaml, deploy/charts/emqx/templates/certificate.yaml, deploy/charts/emqx/values.yaml
see: https://github.com/emqx/emqx/pull/8544
=> feat(helm): add ssl support for helm chart

CHANGES-4.3.md, apps/emqx_sn/rebar.config, etc/emqx.conf, priv/emqx.schema, rebar.config
Port of https://github.com/emqx/emqx/pull/8637
=> feat: add option to gc after TLS/SSL handshake (4.3)

apps/emqx_gateway/test/emqx_gateway_auth_ct.erl, apps/emqx_gateway/test/emqx_sn_protocol_SUITE.erl, lib-ee/emqx_license/i18n/emqx_license_http_api.conf, lib-ee/emqx_license/src/emqx_license.erl, lib-ee/emqx_license/src/emqx_license_http_api.erl, lib-ee/emqx_license/src/emqx_license_parser.erl, lib-ee/emqx_license/src/emqx_license_schema.erl, lib-ee/emqx_license/test/emqx_license_SUITE.erl, lib-ee/emqx_license/test/emqx_license_http_api_SUITE.erl
Improving the HTTP API for license after PR feedback.
=> chore(license): treat license file API as an upload (5.0)

src/emqx.app.src
the description is used at runtime, not ready to change yet.
=> chore: revert EMQX to EMQ X in emqx app desc

CHANGES-5.0.md, apps/emqx/rebar.config, apps/emqx_connector/src/emqx_connector.app.src, apps/emqx_connector/src/emqx_connector_http.erl, apps/emqx_prometheus/rebar.config, mix.exs, rebar.config
fixes: https://github.com/emqx/emqx/issues/8672
=> make http connector schema backward compatible

CHANGES-4.3.md, deploy/docker/Dockerfile
fixes https://github.com/emqx/emqx/issues/8052
=> chore: add tzdata to alpine docker image

lib-ee/emqx_license/i18n/emqx_license_schema_i18n.conf, lib-ee/emqx_license/src/emqx_license_schema.erl
Fixes https://github.com/emqx/emqx/pull/8723#issuecomment-1214747053
=> docs: add missing descriptions for license schema fields
