emqx/emqx

apps/emqx/src/emqx_secret.erl
apps/emqx_connector/src/emqx_connector_pgsql.erl

fix(connector_psql): Wrap password in a fun

---

.ci/fvt_tests/http_server/rebar.config
apps/emqx_gateway/src/coap/emqx_coap_api.erl
apps/emqx_gateway/src/lwm2m/emqx_lwm2m_api.erl
apps/emqx_management/src/emqx_mgmt_api_configs.erl
apps/emqx_modules/include/emqx_modules.hrl
apps/emqx_modules/src/emqx_modules.app.src
mix.exs
rebar.config

1. Bump minirest to 1.3.7 to make sure all tags are titlecase.
2. Improve tags
- Mqtt → MQTT
- Lwm2m → LwM2M
- CoAP gateway → CoAP
- Conf → Configs

chore: swagger tag titlecase

---

CHANGES-5.0.md
apps/emqx/src/emqx_schema.erl
apps/emqx_management/src/emqx_mgmt_api_listeners.erl

see: https://github.com/emqx/emqx/pull/8571

chore: bind option support `:1883` style config

---

.github/workflows/run_test_cases.yaml
Makefile
apps/emqx_authn/docker-ct
apps/emqx_authz/docker-ct
apps/emqx_connector/docker-ct
scripts/apps-version-check.sh
scripts/ct/run.sh
scripts/docker-ct-apps
scripts/find-apps.sh

Added a `scripts/ct/run.sh` to support selective starts of required docker containers for each app.

only start required docker for integration tests

---

.github/workflows/build_packages.yaml
.github/workflows/build_slim_packages.yaml
bin/emqx
build
scripts/macos-sign-binaries.sh

Works on my machine™.
Need to setup secrets and try it out here.

build: sign binary files in macos package

---

apps/emqx_authn/src/emqx_authn_utils.erl
apps/emqx_authn/test/emqx_authn_mysql_SUITE.erl
apps/emqx_authn/test/emqx_authn_pgsql_SUITE.erl
apps/emqx_authz/src/emqx_authz_utils.erl
apps/emqx_authz/test/emqx_authz_mysql_SUITE.erl
apps/emqx_authz/test/emqx_authz_postgresql_SUITE.erl
apps/emqx_plugin_libs/src/emqx_placeholder.erl
apps/emqx_plugin_libs/test/emqx_placeholder_SUITE.erl

more compatibility for https://github.com/emqx/emqx/pull/8827

chore: support strip double quote in authn/authz

---

apps/emqx_management/src/emqx_mgmt.erl

https://emqx.atlassian.net/browse/EMQX-7350

fix: add ip to dashboard listener_on

---

CHANGES-5.0.md
apps/emqx/src/emqx_channel.erl
apps/emqx_authz/test/emqx_authz_SUITE.erl

Related:
- #8886 
- #8887 
- #8894 
- https://github.com/emqx/emqx/pull/8894#discussion_r964334474
- #8978

fix: check conn state before sending will message

---

bin/emqx
rel/emqx_vars

move mkdir to after change user.

0915 ensure log dir created by runner

---

.gitignore
CHANGES-5.0.md
apps/emqx_authn/include/emqx_authn.hrl
apps/emqx_authn/src/emqx_authn_utils.erl
apps/emqx_authn/src/simple_authn/emqx_authn_http.erl
apps/emqx_authn/src/simple_authn/emqx_authn_mongodb.erl
apps/emqx_authn/src/simple_authn/emqx_authn_mysql.erl
apps/emqx_authn/src/simple_authn/emqx_authn_pgsql.erl
apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl
apps/emqx_authn/test/emqx_authn_http_SUITE.erl
apps/emqx_authn/test/emqx_authn_mongo_SUITE.erl
apps/emqx_authn/test/emqx_authn_mysql_SUITE.erl
apps/emqx_authn/test/emqx_authn_pgsql_SUITE.erl
apps/emqx_authn/test/emqx_authn_redis_SUITE.erl
apps/emqx_authz/src/emqx_authz.erl
apps/emqx_authz/src/emqx_authz_utils.erl
apps/emqx_authz/test/emqx_authz_http_SUITE.erl

fix(auth): use empty strings for absent placeholder values

---

apps/emqx_resource/src/emqx_resource_worker.erl

Before this change, the `emqx_resource_worker` resumes messages from queue and inflight window synchronously one-by-one. 
Now it resumes messages from queue sync/async/batching according to the configuration.
But it still resumes messages from inflight window sync one-by-one for easier implementation. This cannot be a problem as  usually it will not be too long.

refactor(resource): resume from queue/inflight-window with async-sending and batching

---

apps/emqx_bridge/src/emqx_bridge.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl

We will rm influxdb bridge after discussion with @wivwiv

Hide influxdb udp bridge.

---

.ci/docker-compose-file/redis/.gitignore
scripts/git-hook-post-commit.sh
scripts/git-hooks-init.sh

chore: add git commit hook for git-blame-ignore-revs

---

apps/emqx_psk_file/include/emqx_psk_file.hrl
apps/emqx_psk_file/src/emqx_psk_file.app.src
apps/emqx_psk_file/src/emqx_psk_file.appup.src
apps/emqx_psk_file/src/emqx_psk_file.erl

Sync release-e43's `apps/emqx_psk_files` changes
see: https://github.com/emqx/emqx-enterprise/pull/876

refactor(psk): create the ets table in supervisor process

---

scripts/update_appup.escript

Prior to this change, the external app's vsn parser only accepts `Major.Minor.Patch` format (strict semver).
This is causing trouble for some external apps such as `kafka_protocol` which have 4th version number.

build(update_appup.escript): allow external app non-semver

---

apps/emqx_auth_mnesia/test/emqx_acl_mnesia_SUITE.erl
src/emqx_channel.erl

fix(acl): check ACL before publishing last will testament (lwt) message (4.3)

---

CHANGES-4.3.md
rebar.config

included changes:
https://github.com/emqx/eredis/pull/19
https://github.com/emqx/eredis_cluster/pull/22

chore: upgrade eredist to 1.2.9

---

scripts/test-node-discovery-dns.sh

fixes https://github.com/emqx/emqx/issues/9054

chore: supprot DNS discovery test for 4.x

---

deploy/docker/Dockerfile

chore: don't keep tar.gz in the docker image

---

src/emqx_channel.erl
test/emqx_acl_cache_SUITE.erl

Port of https://github.com/emqx/emqx/pull/9050

fix(acl): check ACL before publishing last will testament (lwt) message (4.2)

---

src/emqx_misc.erl
test/emqx_misc_SUITE.erl
test/emqx_node_helpers.erl
test/emqx_shared_sub_SUITE.erl

the route replication is async, added a function to wait for it

test: fix flaky shared sub tests

---

test/emqx_node_helpers.erl

This is to test/inspect states before/after join

test: allow starting ct-slave without join cluster

---

CHANGES-4.3.md
apps/emqx_exproto/src/emqx_exproto_conn.erl
apps/emqx_stomp/src/emqx_stomp_connection.erl
src/emqx_connection.erl
src/emqx_ws_connection.erl

fix: demote rate limit log level to notice

---

CHANGES-4.3.md
include/emqx_release.hrl
rebar.config

fix ssl_pssive message handling

fix: upgrade to gun 1.3.8

---

CHANGES-5.0.md
apps/emqx/src/emqx_channel.erl
apps/emqx/test/emqx_channel_SUITE.erl

port: https://github.com/emqx/emqx/pull/9045/files

refactor: enhance the flapping detect accuracy

---

CHANGES-5.0.md
apps/emqx_management/src/emqx_mgmt_api_publish.erl
apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl

fix(api): publish API only returns message ID

---

.github/workflows/build_packages.yaml

See: [Run workflow Failed](https://github.com/emqx/emqx/actions/runs/3265399016
seem to be introduced in: 5c2edaec7

chore: workflow steps with path

---

deploy/charts/emqx/templates/certificate.yaml

Typo in if statement that prevented creation of Certificate resource.

chore(charts): fix typos

---

CHANGES-4.3.md
changes/v4.3.22-en.md
changes/v4.3.22-zh.md

We will start collecting change logs and release notes using scripts.

docs: split change logs

---

apps/emqx_rule_engine/src/emqx_rule_engine.erl

this change was made only in enterprise edition,
now the module is diverged, this is to bring the fix back to ce, to keep the files identical.

chore: sync changes back from ee to ce

---

apps/emqx/rebar.config
changes/v5.0.10-en.md
changes/v5.0.10-zh.md
mix.exs
rebar.config

chore(ekka): Bump version to 0.13.6

---

apps/emqx/i18n/emqx_limiter_i18n.conf
apps/emqx/i18n/emqx_schema_i18n.conf
apps/emqx_authn/i18n/emqx_authn_jwt_i18n.conf
apps/emqx_authz/i18n/emqx_authz_api_cache_i18n.conf
apps/emqx_authz/i18n/emqx_authz_api_schema_i18n.conf
apps/emqx_authz/i18n/emqx_authz_api_settings_i18n.conf
apps/emqx_authz/i18n/emqx_authz_api_sources_i18n.conf
apps/emqx_authz/i18n/emqx_authz_schema_i18n.conf
apps/emqx_auto_subscribe/i18n/emqx_auto_subscribe_i18n.conf
apps/emqx_conf/i18n/emqx_conf_schema.conf
apps/emqx_connector/i18n/emqx_connector_mqtt_schema.conf
apps/emqx_gateway/i18n/emqx_gateway_schema_i18n.conf
apps/emqx_plugins/i18n/emqx_plugins_schema.conf
apps/emqx_psk/i18n/emqx_psk_i18n.conf
apps/emqx_rule_engine/src/emqx_rule_engine.app.src
apps/emqx_rule_engine/src/emqx_rule_events.erl
rel/emqx_conf.template.en.md
rel/emqx_conf.template.zh.md

docs: fix zh punctuations

---

mix.exs

chore: update jq version in mix

---

apps/emqx_auth_http/src/emqx_acl_http.erl
apps/emqx_auth_http/src/emqx_auth_http.erl

Fixes https://github.com/emqx/emqx/pull/9046#discussion_r1006539149

chore(auth-http): using warning level instead of error

---

apps/emqx_rule_engine/src/emqx_rule_utils.erl
apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl
apps/emqx_web_hook/src/emqx_web_hook.app.src
apps/emqx_web_hook/src/emqx_web_hook.appup.src
apps/emqx_web_hook/src/emqx_web_hook_actions.erl
apps/emqx_web_hook/test/emqx_web_hook_SUITE.erl
changes/v4.3.22-en.md
changes/v4.3.22-zh.md

Port https://github.com/emqx/emqx/pull/9239 to release-v43

feat: support to use placeholders as http headers in webhook actions

---

.github/workflows/build_slim_packages.yaml

chore: fix ci typo

---

apps/emqx_dashboard/src/emqx_dashboard.erl

fix: typo in http error code

---

.github/actions/package-macos/action.yaml
.github/workflows/apps_version_check.yaml
.github/workflows/build_and_push_docker_images.yaml
.github/workflows/build_packages.yaml
.github/workflows/build_slim_packages.yaml
.github/workflows/check_deps_integrity.yaml
.github/workflows/code_style_check.yaml
.github/workflows/elixir_apps_check.yaml
.github/workflows/elixir_deps_check.yaml
.github/workflows/elixir_release.yml
.github/workflows/release.yaml
.github/workflows/run_emqx_app_tests.yaml
.github/workflows/run_fvt_tests.yaml
.github/workflows/run_gitlint.yaml
.github/workflows/run_jmeter_tests.yaml
.github/workflows/run_relup_tests.yaml
.github/workflows/run_test_cases.yaml
.github/workflows/shellcheck.yaml
.github/workflows/stale.yaml

All actions upgraded to their current latest versions that run on node16.

ci(actions): update git actions to latest versions

---

apps/emqx_rule_engine/src/emqx_rule_engine.erl
apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl

test: improve the test cases for t_if_contains_placeholder

---

apps/emqx_management/etc/emqx_management.conf

chore: update management.bootstrap_apps_file's document

---

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_actions.erl
apps/emqx_rule_engine/src/emqx_rule_actions.erl
changes/v4.3.22-en.md
changes/v4.3.22-zh.md

fix: mqtt_bridge and republish validate msg topic

---

.github/actions/docker-meta/action.yaml
.github/workflows/build_and_push_docker_images.yaml
scripts/docker-create-push-manifests.sh

ci: build elixir images for ce only

---

CHANGES-4.3.md
apps/emqx_management/src/emqx_mgmt_http.erl
changes/v4.3.22-en.md
changes/v4.3.22-zh.md
lib-ce/emqx_dashboard/src/emqx_dashboard.erl

fix(prometheus): disable auth for prometheus endpoint on mgmt listener

---

.github/workflows/run_test_cases.yaml
Makefile
scripts/find-apps.sh

This PR ports the changes from master branch for parallel CT runs.
Group the CT apps to two groups:
* fast_ct: run ct without external dependency
* docker_ct: run ct in a docker-compose container which has all the dependencies started

1105 ci improve actions

---

apps/emqx_stomp/test/emqx_stomp_SUITE.erl

Fixes [flaky tests](https://github.com/emqx/emqx/actions/runs/3408483183/jobs/5669188967)

test(stomp): fix flaky tests

---

apps/emqx_management/src/emqx_mgmt_api_configs.erl
apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_test_util.erl
changes/v5.0.10-en.md
changes/v5.0.10-zh.md

Fixes [EMQX-7989](https://emqx.atlassian.net/browse/EMQX-7989)

fix(emqx_mgmt_api_configs): use 'node' query paramter if given

---

apps/emqx/src/emqx_channel.erl
apps/emqx/test/emqx_takeover_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl

fix(channel): session takenover & discarded maybe call disconnect hook

---

apps/emqx_rule_engine/src/emqx_rule_engine.erl

Fixes typos in this PR: https://github.com/emqx/emqx/pull/9229

fix: typos in the RAISE macro of rule_engine

---

src/emqx_crl_cache.erl

fix(crl): correct return for `handle_cast(refresh_config)`

---

.github/workflows/run_test_cases.yaml

prepare, proper, eunit, ct and cover

ci: use self-hosted for all Erlang tests

---

bin/emqx
changes/v4.3.23-en.md
changes/v4.3.23-zh.md
data/emqx_vars
rebar.config.erl

 refactor(cookie): Warning message when boot with default Erlang cookie

---

etc/emqx.conf
priv/emqx.schema

this is a follow up fix for https://github.com/emqx/emqx-enterprise/pull/1535

fix(conf): add crl related config default values in conf

---

scripts/macos-sign-binaries.sh

chore: sign crc32cer nif on macos when packaging ee

---

apps/emqx_rule_engine/src/emqx_rule_engine.erl
rebar.config

Some resources may take very long time to get connected, 5s is not enough in this cases.

Enlarge resource alive timeout

---

.ci/docker-compose-file/docker-compose-influxdb-tcp.yaml
.ci/docker-compose-file/docker-compose-influxdb-tls.yaml
.ci/docker-compose-file/docker-compose-toxiproxy.yaml
.ci/docker-compose-file/influxdb/setup-v1.sh
.ci/docker-compose-file/toxiproxy.json
.github/workflows/run_test_cases.yaml
Makefile
apps/emqx/test/emqx_common_test_helpers.erl
apps/emqx/test/emqx_shared_sub_SUITE.erl
lib-ee/emqx_ee_bridge/docker-ct
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
rebar.config.erl
scripts/ct/run.sh

test(influxdb): increase influxdb bridge/connector coverage (ee5.0)

---

lib-ce/emqx_modules/test/emqx_mod_delayed_SUITE.erl

https://github.com/emqx/emqx/actions/runs/3479575153/jobs/5818370291#step:8:309
```
%%% emqx_mod_delayed_SUITE ==> init_per_suite: FAILED
%%% emqx_mod_delayed_SUITE ==> {{failed_to_start_app,emqx_modules,
{emqx_modules,
{bad_return,
{{emqx_modules_app,start,[normal,[]]},
{'EXIT',
{function_clause,
[{proplists,get_value,
[acl_file,undefined,undefined],
[{file,"proplists.erl"},{line,216}]},
{emqx_mod_acl_internal,load,1,
[{file,
"/__w/emqx/emqx/source/lib-ce/emqx_modules/src/emqx_mod_acl_internal.erl"},
{line,46}]},
{emqx_modules,load_module,2,
[{file,
"/__w/emqx/emqx/source/lib-ce/emqx_modules/src/emqx_modules.erl"},
{line,157}]},
{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},
{emqx_modules_app,start,2,
[{file,
"/__w/emqx/emqx/source/lib-ce/emqx_modules/src/emqx_modules_app.erl"}, …
```

test: fix broken mod delayed test

---

scripts/macos-sign-binaries.sh

chore: sign extra files on macos when packaging ee

---

apps/emqx_gateway/i18n/emqx_gateway_api_i18n.conf
apps/emqx_gateway/src/emqx_gateway.app.src
apps/emqx_gateway/src/emqx_gateway_api.erl
apps/emqx_gateway/src/emqx_gateway_api_authn.erl
apps/emqx_gateway/test/emqx_gateway_api_SUITE.erl
apps/emqx_gateway/test/emqx_gateway_test_utils.erl
apps/emqx_gateway/test/emqx_stomp_SUITE.erl
changes/v5.0.11-en.md
changes/v5.0.11-zh.md

Fixes [EMQX-7818](https://emqx.atlassian.net/browse/EMQX-7818)

Redesign api gateway enable

---

apps/emqx_rule_engine/src/emqx_rule_engine.erl
apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
rebar.config

Sync v43 to v44

---

apps/emqx/test/emqx_banned_SUITE.erl

since this suite has changed its start method to the `emqx_common_test_helpers:start_apps/1`, the `emqx_banned` server will never stop (its restart type is permanent), thus there is no need to manually start or stops it.

test: fix flaky banned case

---

changes/v5.0.11-en.md
changes/v5.0.11-zh.md

commit the missing change descriptions

chore: update changes

---

.github/workflows/release.yaml

ci: fix version for push-helm-action

---

bin/emqx
bin/nodetool
changes/v4.3.23-en.md
changes/v4.3.23-zh.md

chore: make remsh node name away from the atom table overflow

---

apps/emqx/src/emqx_ws_connection.erl

fix(typo): typo in code

---

.github/actions/package-macos/action.yaml
.github/workflows/build_slim_packages.yaml
scripts/macos-sign-binaries.sh

ci: build slim packages on macos arm64

---

.github/workflows/build_packages.yaml
changes/v5.0.11-en.md
changes/v5.0.12-en.md
changes/v5.0.12-zh.md

ci: build macos release packages for apple silicon (arm64)

---

changes/v4.4.11-en.md
changes/v4.4.11-zh.md
deploy/charts/emqx/templates/configmap.env.yaml
deploy/charts/emqx/values.yaml

Do not use `Release name`, should use `Full name`
Fixes:  EEC-693

fix: helm chart headless service name error

---

.github/workflows/release.yaml
.github/workflows/upload-helm-charts.yaml

ci: add separate manual workflow to upload charts

---

deploy/docker/README.md

Fixes EMQX-8283
Sync with:
- https://github.com/emqx/emqx-docker/pull/15
- https://github.com/docker-library/docs/pull/2240

docs: fix minor issues in docker readme

---

apps/emqx/rebar.config
apps/emqx_bridge/src/emqx_bridge.erl
apps/emqx_bridge/src/schema/emqx_bridge_mqtt_config.erl
apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_bridge/src/schema/emqx_bridge_webhook_schema.erl
apps/emqx_bridge/test/emqx_bridge_mqtt_config_tests.erl
apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
lib-ee/emqx_ee_bridge/rebar.config
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.erl
mix.exs
rebar.config

- [n/a] Change log has been added to `changes/` dir
- [n/a] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)
- [n/a] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [n/a] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

1128 fix upgrade pre ee confg

---

.github/workflows/build_and_push_docker_images.yaml

ci: automatically update emqx/emqx:latest on releases

---

.ci/docker-compose-file/docker-compose-toxiproxy.yaml
.ci/docker-compose-file/toxiproxy.json
apps/emqx_connector/src/emqx_connector_mysql.erl
lib-ee/emqx_ee_bridge/docker-ct
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_mysql_SUITE.erl
scripts/ct/run.sh

test: add basic mysql bridge test (ee5.0)

---

scripts/rel/check-chart-vsn.sh
scripts/rel/cut.sh
scripts/rel/sync-remotes.sh

build: add release helper scripts

---

apps/emqx_management/src/emqx_mgmt_api_trace.erl
changes/v5.0.12-en.md
changes/v5.0.12-zh.md

Fixes [EMQX-7993](https://emqx.atlassian.net/browse/EMQX-7993) and [EMQX-7995](https://emqx.atlassian.net/browse/EMQX-7995) and [EMQX-7991](https://emqx.atlassian.net/browse/EMQX-7991)

Various doc fixes for /trace API

---

apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
apps/emqx_rule_engine/src/emqx_rule_engine.app.src
apps/emqx_rule_engine/src/emqx_rule_events.erl
apps/emqx_rule_engine/test/emqx_rule_events_SUITE.erl

[EMQX-8303](https://emqx.atlassian.net/browse/EMQX-8303)

refactor: use static function references

---

README-CN.md
README-JP.md
README-RU.md
README.md

chore: fix README.md(s) picture link

---

.ci/docker-compose-file/Makefile.local
.ci/docker-compose-file/docker-compose-redis-cluster-tcp.yaml
.ci/docker-compose-file/docker-compose-redis-cluster-tls.yaml
.ci/docker-compose-file/redis/.gitignore
.ci/docker-compose-file/redis/redis-tls.conf
.ci/docker-compose-file/redis/redis.conf
.ci/docker-compose-file/redis/redis.sh
.ci/docker-compose-file/toxiproxy.json
apps/emqx/test/emqx_common_test_helpers.erl
apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
apps/emqx_bridge/include/emqx_bridge.hrl
apps/emqx_bridge/src/emqx_bridge.erl
apps/emqx_connector/src/emqx_connector_redis.erl
apps/emqx_connector/test/emqx_connector_redis_SUITE.erl
lib-ee/emqx_ee_bridge/docker-ct
lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_redis.conf
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_redis.erl
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_redis_SUITE.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_redis.erl
scripts/ct/run.sh

feat(bridge): add Redis bridge

---

apps/emqx/src/emqx_frame.erl
apps/emqx/test/emqx_frame_SUITE.erl

some of the tests were not added to the test groups, so they were not run.
also fixed a typo in emqx_frame.erl

test: fix emqx_frame_SUITE

---

.github/workflows/build_and_push_docker_images.yaml
Makefile

Dev/william/bump ee dashboard e1.0.1 beta.7

---

test/emqx_crl_cache_SUITE.erl

```
%%% emqx_crl_cache_SUITE ==> t_empty_cache: FAILED
%%% emqx_crl_cache_SUITE ==> {{badmatch,{error,econnrefused}},
[{emqx_crl_cache_SUITE,t_empty_cache,1,
[{file,"/home/thales/dev/emqx/emqx2/test/emqx_crl_cache_SUITE.erl"},
{line,450}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1783}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1292}]},
{test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1224}]}]}
```

test(flaky): fix flaky test

---

bin/emqx

fix warnings in bin emqx

---

apps/emqx_management/src/emqx_mgmt_api_trace.erl
apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
changes/v5.0.12-en.md
changes/v5.0.12-zh.md

Fixes [EMQX-7996](https://emqx.atlassian.net/browse/EMQX-7996)

fix: return 400 if node in query doesn't look like a known node

---

apps/emqx_management/src/emqx_mgmt_api_trace.erl
apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl
changes/v5.0.12-en.md
changes/v5.0.12-zh.md

Fixes [EMQX-7992](https://emqx.atlassian.net/browse/EMQX-7992)

fix: return 409 in case of duplicate

---

changes/v4.4.12-en.md
changes/v4.4.12-zh.md
deploy/charts/emqx/templates/secret.yaml

Same https://github.com/emqx/emqx/pull/9467

fix(helm): chart using incorrect secret values with custom credentials

---

apps/emqx/src/emqx_schema.erl
apps/emqx/test/emqx_schema_tests.erl
changes/v5.0.12-en.md
changes/v5.0.12-zh.md

fixes #9459 
- [n/a] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)
- [n/a] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [n/a] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in

fix(emqx_schema): handshake_timeout is common for all listeners

---

.github/workflows/run_test_cases.yaml
scripts/find-apps.sh

Fixes [EMQX-8484](https://emqx.atlassian.net/browse/EMQX-8484)

ci: fix logs artefact name

---

.github/workflows/build_and_push_docker_images.yaml
deploy/docker/README.md

Fixes [EMQX-8481](https://emqx.atlassian.net/browse/EMQX-8481)

docs: update docker readme

---

changes/v5.0.12-en.md
changes/v5.0.12-zh.md
deploy/charts/emqx-enterprise/README.md
deploy/charts/emqx-enterprise/templates/service.yaml
deploy/charts/emqx-enterprise/values.yaml
deploy/charts/emqx/README.md
deploy/charts/emqx/templates/service.yaml
deploy/charts/emqx/values.yaml

Fix https://github.com/emqx/emqx/issues/9515

chore: helm chart support externalTrafficPolicy

---

.github/workflows/build_and_push_docker_images.yaml
.github/workflows/build_packages.yaml
.github/workflows/build_slim_packages.yaml
.github/workflows/check_deps_integrity.yaml
.github/workflows/code_style_check.yaml
.github/workflows/elixir_apps_check.yaml
.github/workflows/elixir_deps_check.yaml
.github/workflows/elixir_release.yml
.github/workflows/run_emqx_app_tests.yaml
.github/workflows/run_fvt_tests.yaml
.github/workflows/run_relup_tests.yaml
.github/workflows/run_test_cases.yaml
changes/v5.0.12-en.md
changes/v5.0.12-zh.md
scripts/pkg-tests.sh

Fixes [EMQX-8449](https://emqx.atlassian.net/browse/EMQX-8449)

build amzn2 packages

---

.github/workflows/apps_version_check.yaml
.github/workflows/build_packages.yaml
.github/workflows/build_slim_packages.yaml
.github/workflows/check_deps_integrity.yaml
.github/workflows/release.yaml
.github/workflows/run_acl_migration_tests.yaml
.github/workflows/run_fvt_tests.yaml
.github/workflows/run_test_cases.yaml

Fixes [EMQX-8449](https://emqx.atlassian.net/browse/EMQX-8449)
Also changed default slim package build from el8 to el7 since vast majority of our users use that one.

ci: build amzn2 packages

---

.github/workflows/build_and_push_docker_images.yaml

Fixes [EMQX-8481](https://emqx.atlassian.net/browse/EMQX-8481)

ci: update short description on docker hub page for emqx/emqx

---

.github/workflows/run_jmeter_tests.yaml

Fixes [EMQX-7982](https://emqx.atlassian.net/browse/EMQX-7982)
Prep for https://github.com/emqx/emqx/pull/9531

ci: use ref to tag rather than raw branch for emqx-fvt in jmeter suite

---

apps/emqx/src/emqx_channel.erl
apps/emqx/src/emqx_session.erl
apps/emqx/test/emqx_session_SUITE.erl
changes/v5.0.10-en.md
changes/v5.0.10-zh.md
changes/v5.0.13-en.md
changes/v5.0.13-zh.md

Fix message dropped event v50

---

build

Fixes [EMQX-8555](https://emqx.atlassian.net/browse/EMQX-8555)

chore: fail build if apple notarization failed

---

apps/emqx_rule_engine/src/emqx_rule_engine.app.src
apps/emqx_rule_engine/src/emqx_rule_funcs.erl
apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
changes/v5.0.13-en.md
changes/v5.0.13-zh.md

__It a simply code sync from v4.x__

Feat zip functions

---

.github/workflows/build_packages.yaml
.github/workflows/build_slim_packages.yaml
changes/v4.4.12-en.md
changes/v4.4.12-zh.md

Fixes [EMQX-8528](https://emqx.atlassian.net/browse/EMQX-8528)

ci: build macos arm64 packages

---

.github/actions/package-macos/action.yaml
.github/workflows/build_slim_packages.yaml
build
scripts/macos-sign-binaries.sh
scripts/relup-base-vsns.escript

Fixes [EMQX-8555](https://emqx.atlassian.net/browse/EMQX-8555)

chore: fail build if apple notarytool failed

---

lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl

Related Issue: https://emqx.atlassian.net/browse/EMQX-8461
Currently, the InfluxDB client raises an error if an empty `fields` map is passed to it for pushing data.
```
14:03:35.563 [error] [InfluxDB] Encode [
%{
fields: %{},
measurement: "t/topic",
tags: %{},
timestamp: 1670864615563
}
] failed: :error :missing_field [
{:influxdb_line, :encode_fields, 1,
[
file: '/home/thales/dev/emqx/emqx/deps/influxdb/src/influxdb_line.erl',
line: 60
]},
{:influxdb_line, :encode_, 1,
[
file: '/home/thales/dev/emqx/emqx/deps/influxdb/src/influxdb_line.erl',
line: 44
]},
{:influxdb_line, :"-encode_/1-fun-0-", 2,
[
file: '/home/thales/dev/emqx/emqx/deps/influxdb/src/influxdb_line.erl',
line: 38
]},
{:influxdb, :write, 2,
[file: '/home/thales/dev/emqx/emqx/deps/influxdb/src/influxdb.erl', line: 79]}, …
```

fix(influxdb): check if fields are empty before sending

---

apps/emqx_bridge/src/schema/emqx_bridge_mqtt_config.erl
apps/emqx_connector/src/mqtt/emqx_connector_mqtt_schema.erl
apps/emqx_resource/i18n/emqx_resource_schema_i18n.conf
apps/emqx_resource/include/emqx_resource.hrl
apps/emqx_resource/src/emqx_resource_worker.erl
apps/emqx_resource/src/schema/emqx_resource_schema.erl

Fixes [EMQX-8462](https://emqx.atlassian.net/browse/EMQX-8462)
- [n/a] Change log has been added to `changes/` dir
- [n/a] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)
- [n/a] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [n/a] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

1219 fix mqtt bridge config

---

apps/emqx/src/emqx_connection.erl

fix(limiter): change limiter `cache` to `buffer`

---

scripts/start-two-nodes-in-docker.sh
src/emqx_misc.erl
test/emqx_misc_SUITE.erl

fixes [EMQX-8581](https://emqx.atlassian.net/browse/EMQX-8581)

1221 fix io format error when rpc from remsh

---

.github/actions/package-macos/action.yaml
scripts/macos-sign-binaries.sh

This patch already exists in e44

ci fix self hosted macos runners

---

apps/emqx_rule_engine/src/emqx_rule_engine.erl
apps/emqx_rule_engine/test/emqx_rule_monitor_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_utils_SUITE.erl

port https://github.com/emqx/emqx-enterprise/pull/1652 to v4.4

chore: sometimes the alarm resource down cannot be cleared

---

apps/emqx/rebar.config
apps/emqx/src/emqx_config.erl
apps/emqx/src/emqx_schema.erl
apps/emqx_authn/src/emqx_authn_api.erl
apps/emqx_authz/src/emqx_authz.app.src
apps/emqx_authz/src/emqx_authz_api_sources.erl
apps/emqx_authz/test/emqx_authz_redis_SUITE.erl
apps/emqx_connector/src/emqx_connector_schema_lib.erl
apps/emqx_exhook/src/emqx_exhook.app.src
apps/emqx_exhook/src/emqx_exhook_api.erl
apps/emqx_resource/src/emqx_resource_validator.erl
changes/v5.0.13-en.md
changes/v5.0.13-zh.md
lib-ee/emqx_ee_bridge/rebar.config
mix.exs
rebar.config

fixes: https://github.com/emqx/emqx/issues/9589
```
dashboard.default_password = EMQX_dashboard__default_password = ******
log.file_handlers.default.enable = EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE = false
log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
node.cookie = EMQX_NODE__COOKIE = ******
authorization.sources.2.query = EMQX_AUTHORIZATION__SOURCES__2__QUERY = "SELECT permission, action, topic FROM mqtt_acl WHERE username = ${username}"
authorization.sources.2.password = EMQX_AUTHORIZATION__SOURCES__2__PASSWORD = ******
authorization.sources.2.username = EMQX_AUTHORIZATION__SOURCES__2__USERNAME = doadmin
authorization.sources.2.database = EMQX_AUTHORIZATION__SOURCES__2__DATABASE = emqx
authorization.sources.2.server = EMQX_AUTHORIZATION__SOURCES__2__SERVER = …
```

1123 pin hocon 0.33.0

---

lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl
lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_producer_SUITE.erl

https://emqx.atlassian.net/browse/EMQX-8547
If a Kafka Producer bridge is given bad configuration (e.g.: bad authn credentials), the Wolff client process is started successfully, as it does not attempt to connect, but when the producer process is attempted to be started, it fails (only then the client tries to connect to Kafka).  At this point, an error was thrown, but the supervised client process remained running.
If the configuration was later fixed and the bridge updated, which prompted its removal and recreation, the Wolff client would report to be "already started", so it would never pick up the new (fixed) configuration, and the producers would perpetually fail to start until the node would be restarted.
We simply ensure the client is stopped before throwing the error, unrolling …

fix(kafka_producer): cleanup client after failing to start producers

---

bin/install_upgrade.escript

Related: https://github.com/emqx/emqx/pull/9611

fix(upgrade): fix start script existence check (v4.3)

---

.ci/docker-compose-file/docker-compose-kafka.yaml
.ci/docker-compose-file/kafka/kafka-entrypoint.sh
.github/workflows/run_test_cases.yaml
apps/emqx/test/emqx_listeners_SUITE.erl
apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
lib-ee/emqx_ee_connector/rebar.config
scripts/ct/run.sh

to lower the chance of eaddrinuse

test: add a 2 seconds sleep between listener sotp and restart

---

.gitignore
rebar.config
scripts/pre-compile.sh
scripts/update-bom.sh

feat(bom): import rebar_sbom for generating bom files

---

apps/emqx_connector/test/emqx_connector_jwt_worker_SUITE.erl
lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl

Fixes https://emqx.atlassian.net/browse/EMQX-8615

fix(kafka): detect connectivity in on_get_status

---

scripts/update_appup.escript

All the listed modules with qlc.hrl included, qlc is the only header.
so check git diff of the module is safe.
https://emqx.atlassian.net/browse/EMQX-8655

build: skip qlc modules if there were no git diff

---

.github/CODEOWNERS

Team members according to https://emqx.atlassian.net/wiki/spaces/EMQX/overview#Code-Review-Board.
One approval from any of that team members should be enough for any PR.

chore: use @emqx/emqx-review-board team in codeowners

---

apps/emqx_retainer/src/emqx_retainer.app.src
apps/emqx_retainer/src/emqx_retainer.erl
apps/emqx_retainer/src/emqx_retainer_mnesia.erl
apps/emqx_retainer/test/emqx_retainer_api_SUITE.erl
changes/v5.0.14-en.md
changes/v5.0.14-zh.md

https://emqx.atlassian.net/browse/EMQX-8650

fix(retainer): change mnesia table storage types during update

---

.ci/docker-compose-file/docker-compose-toxiproxy.yaml
.ci/docker-compose-file/toxiproxy.json
apps/emqx_connector/src/emqx_connector_pgsql.erl
lib-ee/emqx_ee_bridge/docker-ct
lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_pgsql.conf
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_pgsql.erl
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_pgsql_SUITE.erl

support both simple and batch query

feat(bridges): integrate PostgreSQL into bridges

---

apps/emqx_management/src/emqx_mgmt_api_configs.erl
lib-ee/emqx_license/i18n/emqx_license_schema_i18n.conf
lib-ee/emqx_license/src/emqx_license_schema.erl

* Changing from 1000 to 100 is a requested from CS team, approved by Product team.
* License has its own APIs, can be excluded from `/configs/license`

0109 update default lic, exclude license from config api

---

test/emqx_node_helpers.erl

Some tests use the `slave` module for better readability.  But, when shutting those nodes down, if one uses `ct_slave` on them, they will hang.  This'll make CT wait until the timetrap (default 30 min) before failing `end_per_testcase`.

test: fix hang when calling `ct_slave:stop` on a `slave` started node

---

lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_matrix.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_pgsql.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_timescale.erl
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_pgsql_SUITE.erl

- add timescale && matrix bridges
- fixed some issues of the pgsql bridge

 feat(bridges): add timescale && matrix bridges

---

apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
apps/emqx_resource/src/emqx_resource_manager.erl

Ticket: https://emqx.atlassian.net/browse/EMQX-8588

EMQX 8588 refactor emqx resource manager

---

apps/emqx_resource/i18n/emqx_resource_schema_i18n.conf

Fixes [EMQX-8731](https://emqx.atlassian.net/browse/EMQX-8731)

fix: remove time unit from duration fields description

---

apps/emqx_connector/src/emqx_connector_http.erl
apps/emqx_connector/src/emqx_connector_mysql.erl

https://emqx.atlassian.net/browse/EMQX-8625

EMQX-8625: add bridges probe api for kafka and mysql

---

apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
apps/emqx_bridge/test/emqx_bridge_mqtt_SUITE.erl
apps/emqx_connector/src/emqx_connector_http.erl
apps/emqx_connector/src/emqx_connector_mysql.erl

Fixing minor issues with past PRs that are merged already.

EMQX 8625 follow up

---

apps/emqx_connector/rebar.config
mix.exs

[EMQX-8562](https://emqx.atlassian.net/browse/EMQX-8562)

chore: update epgsql to 4.7.0.1 with full OTP-25 compat

---

apps/emqx/src/emqx_authentication.erl
apps/emqx/test/emqx_authentication_SUITE.erl
changes/v5.0.15/fix-9785.en.md
changes/v5.0.15/fix-9785.zh.md

fixes: https://github.com/emqx/emqx/issues/9693

fix(authn): stop authn handling when emqx_authentication provides a result

---

lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl
lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_producer_SUITE.erl
scripts/ct/run.sh

fixes: https://emqx.atlassian.net/browse/EMQX-8762

0118 fix key dispatch kafka produce strategy

---

.ci/docker-compose-file/Makefile.local
apps/emqx_resource/include/emqx_resource.hrl
apps/emqx_resource/src/emqx_resource_manager.erl
apps/emqx_resource/src/schema/emqx_resource_schema.erl
changes/v5.0.15/feat-9628.en.md
changes/v5.0.15/feat-9628.zh.md
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_redis_SUITE.erl

chore(ee bridge): fix Redis bridge test flakyness

---

lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl

A new atom was created every time one did a dry run of a Kafka bridge (that is, clicking the Test button in the settings dialog for the bridge).
After this fix, we will only create a new atom when a bridge with a new name is created. This should be acceptable as bridges with new names are created relatively rarely and it seems to be useful to have an unique atom for every Wolff producer.
Fixes: https://emqx.atlassian.net/browse/EMQX-8739

fix: atom leak when doing Kafka bridge dry-run

---

apps/emqx/i18n/emqx_schema_i18n.conf
apps/emqx/src/emqx.app.src
apps/emqx/src/emqx_connection.erl
apps/emqx/test/emqx_client_SUITE.erl
changes/v5.0.16/fix-9834.en.md
changes/v5.0.16/fix-9834.zh.md

Fixes https://github.com/emqx/emqx/issues/9829

fix(emqx_connection): crash when idle_timeout is set to infinity

---

.github/workflows/build_and_push_docker_images.yaml
.github/workflows/build_packages.yaml
.github/workflows/build_slim_packages.yaml
.github/workflows/check_deps_integrity.yaml
.github/workflows/code_style_check.yaml
.github/workflows/elixir_apps_check.yaml
.github/workflows/elixir_deps_check.yaml
.github/workflows/elixir_release.yml
.github/workflows/run_emqx_app_tests.yaml
.github/workflows/run_fvt_tests.yaml
.github/workflows/run_relup_tests.yaml
.github/workflows/run_test_cases.yaml

Fixes [EMQX-8757](https://emqx.atlassian.net/browse/EMQX-8757)

ci: build ubuntu 22.04 packages

---

build
lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl

https://emqx.atlassian.net/browse/EMQX-8780

0123 fix resource worker leak influxdb

---

apps/emqx_resource/src/emqx_resource_buffer_worker.erl

Turned the `From = {Pid, Ref}` to `{fun gen_statem:reply/2, [Ref]}`
so we can unify the code to only having to deal with callbacks when reply async callers.

0127 refactor buffer worker simplify caller reply

---

apps/emqx_resource/src/emqx_resource_buffer_worker.erl

Fixes [EMQX-8812](https://emqx.atlassian.net/browse/EMQX-8812)

fix: increase dropped.queue_full by number of messages

---

apps/emqx_authz/src/emqx_authz.app.src
apps/emqx_authz/src/emqx_authz_rule.erl
apps/emqx_authz/test/emqx_authz_rule_SUITE.erl
changes/v5.0.16/feat-9871.en.md
changes/v5.0.16/feat-9871.zh.md

[EMQX-6203](https://emqx.atlassian.net/browse/EMQX-6203)

feat(authz): allow the placeholder to be anywhere in the topic for authz rules

---

apps/emqx_resource/test/emqx_resource_SUITE.erl

[EMQX-8798](https://emqx.atlassian.net/browse/EMQX-8798)

test(bufworker): fix testcase flapping due to data races

---

apps/emqx_resource/i18n/emqx_resource_schema_i18n.conf
lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_kafka.conf

Fix: https://emqx.atlassian.net/browse/EMQX-8845

chore: correct the documentation description

---

apps/emqx_resource/src/emqx_resource.erl
apps/emqx_resource/src/emqx_resource_buffer_worker.erl
lib-ee/emqx_ee_bridge/rebar.config
lib-ee/emqx_ee_bridge/src/kafka/emqx_bridge_impl_kafka_producer.erl
mix.exs

fixes: [EMQX-8858](https://emqx.atlassian.net/browse/EMQX-8858)

0202 fix kafka status check

---

apps/emqx_resource/i18n/emqx_resource_schema_i18n.conf
apps/emqx_resource/src/schema/emqx_resource_schema.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_mongodb.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_mysql.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_pgsql.erl
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_redis.erl
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_redis_SUITE.erl

mongodb/mysql/pgsql/redis bridges only support sync
Fix: https://emqx.atlassian.net/browse/EMQX-8845

fix: remove async mode from mongodb/redis/mysql/pgsql bridge

---

.github/workflows/build_slim_packages.yaml
.github/workflows/run_test_cases.yaml
Makefile
apps/emqx/test/emqx_bpapi_static_checks.erl
apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_connector/src/mqtt/emqx_connector_mqtt_worker.erl
apps/emqx_management/src/emqx_mgmt_cache.erl
apps/emqx_resource/include/emqx_resource.hrl
apps/emqx_resource/src/emqx_resource_manager.erl
mix.exs
rebar.config

[EMQX-8841](https://emqx.atlassian.net/browse/EMQX-8841)

ci: always run static_checks

---

.github/workflows/build_packages.yaml
.github/workflows/release.yaml

Fixes [EMQX-8792](https://emqx.atlassian.net/browse/EMQX-8792)

Ci push to packagecloud

---

apps/emqx_ft/src/emqx_ft.erl
apps/emqx_ft/src/emqx_ft_assembler.erl
apps/emqx_ft/src/emqx_ft_schema.erl
apps/emqx_ft/src/emqx_ft_storage.erl
apps/emqx_ft/src/emqx_ft_storage_fs.erl
apps/emqx_ft/src/proto/emqx_ft_storage_fs_proto_v1.erl
apps/emqx_ft/test/emqx_ft_assembler_SUITE.erl

And ensure local happy path is working now.
---
[EMQX-8265](https://emqx.atlassian.net/browse/EMQX-8265)

test(ft): add some basic assembler tests

---

changes/v4.4.15-en.md
changes/v4.4.15-zh.md
src/emqx_banned.erl
test/emqx_banned_SUITE.erl

feat(banned): session will be kicked when client is banned by `clientid`

---

.github/CODEOWNERS

also remove redundant overrides as @thalesmg and @id are included in @emqx/emqx-review-board

chore: update CODEOWNERS to allow anyone to approve changelog

---

apps/emqx_prometheus/src/emqx_prometheus_schema.erl
apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl

fix: add push_gateway_server's  validator

---

apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
changes/v5.0.17/fix-9951.en.md
changes/v5.0.17/fix-9951.zh.md

Fixes [EMQX-8929](https://emqx.atlassian.net/browse/EMQX-8929)

fix(emqx_bridge): unwrap rpc multicall result

---

deploy/packages/rpm/Makefile
deploy/packages/rpm/emqx.spec

Fixes https://emqx.atlassian.net/browse/EMQX-8145

chore: remove otp version from rpm package name

---

apps/emqx_management/src/emqx_management.app.src
apps/emqx_management/src/emqx_mgmt_api.erl
apps/emqx_management/test/emqx_mgmt_api_SUITE.erl

Fixes [EMQX-3689](https://emqx.atlassian.net/browse/EMQX-3689)

EMQX 3689 emqx mgmt api

---

bin/emqx
bin/nodetool
etc/emqx_cloud/vm.args
etc/emqx_edge/vm.args
etc/ssl_dist.conf
scripts/start-two-nodes-in-docker.sh

Port from https://github.com/emqx/emqx/pull/8309

chore: fix Erlang distribution over TLS

---

lib-ee/emqx_ee_bridge/src/emqx_ee_bridge.app.src
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_influxdb.erl
lib-ee/emqx_ee_connector/docker-ct
lib-ee/emqx_ee_connector/i18n/emqx_ee_connector_influxdb.conf
lib-ee/emqx_ee_connector/src/emqx_ee_connector.app.src
lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
lib-ee/emqx_ee_connector/test/emqx_ee_connector_influxdb_SUITE.erl

This adds a test suite for the emqx_ee_connector_influxdb. We add it so that SSL transport options are properly tested.
Fixes EMQX-8783.

test(emqx_ee_connector): add basic tests for influxdb incl. SSL opts

---

apps/emqx_ft/src/emqx_ft.erl
apps/emqx_ft/src/emqx_ft_assembler.erl
apps/emqx_ft/src/emqx_ft_assembly.erl
apps/emqx_ft/src/emqx_ft_storage_fs.erl
apps/emqx_ft/test/emqx_ft_SUITE.erl
apps/emqx_ft/test/emqx_ft_assembler_SUITE.erl

Also downgrade validation errors to mere info messages.
---
[EMQX-8916](https://emqx.atlassian.net/browse/EMQX-8916)

feat(ft): add segment checksum validation

---

build

Fixes https://emqx.atlassian.net/browse/EMQX-8779
Verified on a windows vm.

feat: release windows binaries as zip

---

apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl

Fixes [EMQX-7822](https://emqx.atlassian.net/browse/EMQX-7822)

fix: return `404` for unknown node names

---

deploy/charts/emqx-enterprise/values.yaml
deploy/charts/emqx/values.yaml

Chore charts fix object to list

---

deploy/charts/emqx-enterprise/README.md
deploy/charts/emqx-enterprise/templates/ingress.yaml
deploy/charts/emqx-enterprise/values.yaml
deploy/charts/emqx/README.md
deploy/charts/emqx/templates/ingress.yaml
deploy/charts/emqx/values.yaml

Easier to expose the MQTT service through an ingress controller.

Add MQTT ingress and remove mgmt references

---

apps/emqx/test/emqx_common_test_helpers.erl
apps/emqx_management/include/emqx_mgmt.hrl
apps/emqx_management/src/emqx_mgmt.erl
apps/emqx_management/src/emqx_mgmt_api.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/src/emqx_mgmt_util.erl
apps/emqx_management/test/emqx_mgmt_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_alarms_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl
apps/emqx_retainer/src/emqx_retainer_api.erl

Fixes [EMQX-3688](https://emqx.atlassian.net/browse/EMQX-3688)

 emqx mgmt code coverage and cleanup

---

apps/emqx/test/emqx_olp_SUITE.erl

Now we have more powerful runners with more cores.
This PR leaves only one scheduler online to make test results stable.

test: fix flaky olp tc

---

Makefile
apps/emqx_bridge/i18n/emqx_bridge_schema.conf
apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
scripts/test/start-two-nodes-in-docker.sh

fix bridge status descriptions.

0210 docs: fix bridge status

---

changes/ce/fix-10041.en.md
changes/ce/fix-10041.zh.md
lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_influxdb.conf
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_influxdb_SUITE.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_influxdb.erl
scripts/test/influx/README.md
scripts/test/influx/influx-bridge.conf

Fixes [EMQX-9036](https://emqx.atlassian.net/browse/EMQX-9036)

0228 add influx line protocol desc

---

.github/workflows/build_packages.yaml

https://emqx.atlassian.net/browse/EMQX-9076

ci: release packages for raspbian

---

apps/emqx_authz/src/emqx_authz_api_sources.erl
apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
changes/ce/fix-10074.en.md
changes/ce/fix-10074.zh.md

Fixes [EMQX-8550](https://emqx.atlassian.net/browse/EMQX-8550)

fix(emqx_authz): check if type param matches type in body

---

apps/emqx_authz/src/emqx_authz_api_sources.erl
apps/emqx_authz/test/emqx_authz_api_sources_SUITE.erl
changes/ce/fix-10085.en.md
changes/ce/fix-10085.zh.md

Fixes [EMQX-8552](https://emqx.atlassian.net/browse/EMQX-8552)

emqx_authz API: return 404 for all requests on non existent source

---

apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
changes/ce/fix-10107.en.md
changes/ce/fix-10107.zh.md

Fixes [EMQX-9147](https://emqx.atlassian.net/browse/EMQX-9147)
- [-] Schema changes are backward compatible

Bridges API: fix handling unknown bridge-id

---

deploy/charts/emqx-enterprise/templates/service-monitor.yaml
deploy/charts/emqx-enterprise/templates/service.yaml
deploy/charts/emqx/templates/service-monitor.yaml
deploy/charts/emqx/templates/service.yaml

Fix to support adding multiple service annotations

fix(helm-charts): fix for multiple service annotations

---

apps/emqx/priv/bpapi.versions
apps/emqx_management/src/emqx_mgmt_api_plugins.erl
apps/emqx_plugins/src/emqx_plugins.app.src
apps/emqx_plugins/src/emqx_plugins.erl
apps/emqx_plugins/src/proto/emqx_plugins_proto_v1.erl
apps/emqx_plugins/test/emqx_plugins_SUITE.erl
changes/ce/fix-10117.en.md

Closes: https://emqx.atlassian.net/browse/EMQX-8889

fix: copy plugins to a new node joining a cluster

---

.github/workflows/release.yaml

https://emqx.atlassian.net/browse/EMQX-9206

ci: do not post updates about enterprise releases to emqx.io

---

.github/workflows/build_slim_packages.yaml
apps/emqx_conf/src/emqx_conf.erl
apps/emqx_dashboard/src/emqx_dashboard.erl

Make it easier for doc team to get the schema dump.
- [~] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [~] Change log has been added to `changes/` dir …

build: generate per-lang schema dump

---

changes/ce/feat-10139.en.md
changes/ce/feat-10139.zh.md
deploy/charts/emqx-enterprise/README.md
deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
deploy/charts/emqx-enterprise/values.yaml
deploy/charts/emqx/README.md
deploy/charts/emqx/templates/StatefulSet.yaml
deploy/charts/emqx/values.yaml

Done of https://github.com/emqx/emqx/issues/10116

feat(helm): helm chart support extraVolumeMounts and extraVolumes

---

apps/emqx_conf/src/emqx_conf.erl
apps/emqx_dashboard/src/emqx_dashboard.erl
apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl

Fixes swagger api(http://127.0.0.1:18083/api-docs/swagger.json) crash 
It was introduced by https://github.com/emqx/emqx/pull/10155
```
[error] crasher: initial call: cowboy_stream_h:request_process/3, pid: <0.2710.0>, registered_name: [], error: {badarith,[{erlang,'*',[desc,1000000],[{error_info,#{module => erl_erts_errors}}]},{calendar,now_to_datetime,1,[{file,"calendar.erl"},{line,329}]},{jsx_parser,value,4,[{file,"jsx_parser.erl"},{line,113}]},{cowboy_swagger_json_handler,handle_get,2,[{file,"/Users/zhongwen/github/emqx/emqx-v5/_build/default/lib/cowboy_swagger/src/cowboy_swagger_json_handler.erl"},{line,52}]},{cowboy_rest,call,3,[{file,"cowboy_rest.erl"},{line,1576}]},{cowboy_rest,set_resp_body,2,[{file,"cowboy_rest.erl"},{line,1466}]},{cowboy_rest,upgrade,4,[{file,"cowboy_rest.erl"}, …
```

fix: swagger doc 500 crash

---

.github/workflows/build_slim_packages.yaml
.github/workflows/git_sync.yaml
.github/workflows/run_automate_tests.yaml
.github/workflows/run_fvt_tests.yaml

Fixes https://emqx.atlassian.net/browse/EEC-769

Ci export docker image in slim packages

---

changes/v4.4.17-en.md
changes/v4.4.17-zh.md
rebar.config

chore: update esockd to 5.8.9

---

apps/emqx/src/emqx_misc.erl
apps/emqx_bridge/i18n/emqx_bridge_schema.conf
apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
apps/emqx_resource/include/emqx_resource.hrl
apps/emqx_resource/src/emqx_resource_manager.erl
changes/ce/fix-10145.en.md

Fixes [EMQX-8930](https://emqx.atlassian.net/browse/EMQX-8930)

fix reporting errors in failing bridges

---

deploy/charts/emqx-enterprise/templates/StatefulSet.yaml
deploy/charts/emqx/templates/StatefulSet.yaml

Fixes indentation issue introduced by https://github.com/emqx/emqx/pull/10139 and fixes [10116](https://github.com/emqx/emqx/issues/10116) 

fix(helm): helm chart extraVolumeMounts and extraVolumes indentation

---

changes/ce/fix-10190.en.md

[EMQX-9269](https://emqx.atlassian.net/browse/EMQX-9269)
Followup to #10190.

chore: remove irrelevant changelog entry

---

lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_rocketmq.erl

Metrics are no longer returned in `GET` bridge requests. 

fix: remove metrics from rocketmq example

---

lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_consumer_SUITE.erl

It might need some time for the metrics to be set.

test: attempt to fix flaky kafka consumer test

---

src/emqx_cm.erl
test/emqx_client_SUITE.erl
test/emqx_cm_SUITE.erl

Just add a test case which subscribes to a non-utf8 topic. The code it self works as expected.

chore: add a testcase for subscribe non-utf8 topics

---

apps/emqx_rule_engine/README.md

This commit adds more content to the readme file of the `emqx_rule_engine` app. The aim of the changes are to make it easier to understand what the rule engine is and what it does.
Fixes https://emqx.atlassian.net/browse/EMQX-9229

docs: refine README.md for the emqx_rule_engine app

---

apps/emqx/include/emqx_release.hrl

chore: e5.0.2-rc.1

---

lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_kafka.conf
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_kafka.erl

https://emqx.atlassian.net/browse/EMQX-9304
https://emqx.atlassian.net/browse/EMQX-9312
- [~] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [~] Change log has been added to `changes/` dir for user-facing artifacts update

docs(kafka_consumer): make specific labels for key/value encoding modes

---

src/emqx_channel.erl
test/emqx_client_SUITE.erl

chore: remove peercert from the state of connection processes

---

apps/emqx_plugin_libs/src/emqx_plugin_libs.app.src

chore: bump emqx_plugin_libs.app.src

---

apps/emqx/test/emqx_common_test_helpers.erl
apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
apps/emqx_dashboard/src/emqx_dashboard.erl
apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
apps/emqx_dashboard/test/emqx_dashboard_admin_SUITE.erl
apps/emqx_dashboard/test/emqx_dashboard_bad_api_SUITE.erl
apps/emqx_dashboard/test/emqx_dashboard_error_code_SUITE.erl
apps/emqx_dashboard/test/emqx_dashboard_haproxy_SUITE.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl
apps/emqx_dashboard/test/emqx_swagger_response_SUITE.erl

Fixes [EMQX-9269](https://emqx.atlassian.net/browse/EMQX-9269)
Also see #10212.

test(bridge-api): also run testcases in cluster environment

---

.github/workflows/build_slim_packages.yaml
scripts/test/start-two-nodes-in-docker.sh

Fixes https://emqx.atlassian.net/browse/EMQX-8884

ci: run start-two-nodes-in-docker.sh test script in CI

---

.github/workflows/build_slim_packages.yaml
apps/emqx/rebar.config
apps/emqx/src/emqx_schema.erl
apps/emqx_conf/src/emqx_conf.app.src
apps/emqx_conf/src/emqx_conf.erl
apps/emqx_conf/src/emqx_conf_app.erl
apps/emqx_conf/src/emqx_conf_schema.erl
apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
apps/emqx_dashboard/test/emqx_swagger_requestBody_SUITE.erl
apps/emqx_dashboard/test/emqx_swagger_response_SUITE.erl
apps/emqx_prometheus/src/emqx_prometheus.app.src
apps/emqx_prometheus/src/emqx_prometheus_schema.erl
apps/emqx_resource/src/schema/emqx_resource_schema.erl
apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
changes/ce/fix-10211.en.md
changes/ce/fix-10211.zh.md
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_kafka.erl
mix.exs
rebar.config
scripts/test/emqx-smoke-test.sh

Fixes [EMQX-9272](https://emqx.atlassian.net/browse/EMQX-9272)
schema diff for review:
https://gist.github.com/zmstone/01ad5754b9beaeaf3f5b86d14d49a0b7/revisions

0321 hide broker perf configs

---

apps/emqx_bridge/src/emqx_bridge.app.src
apps/emqx_rule_engine/src/emqx_rule_engine.app.src
lib-ee/emqx_ee_bridge/test/emqx_bridge_impl_kafka_consumer_SUITE.erl

test: fix flaky kafka consumer test

---

README-CN.md
README-RU.md
README.md

Remove links of other language in readme
https://emqx.atlassian.net/browse/EMQX-9352

chore: update readme

---

apps/emqx_bridge/src/emqx_bridge.app.src
apps/emqx_rule_engine/src/emqx_rule_engine.app.src
apps/emqx_rule_engine/src/emqx_rule_engine.erl

Follow up to
https://github.com/emqx/emqx/pull/10251#discussion_r1150710899 and https://github.com/emqx/emqx/pull/10251#discussion_r1150720420

refactor(rule_engine): use more helper functions

---

lib-ee/emqx_ee_bridge/i18n/emqx_ee_bridge_kafka.conf
lib-ee/emqx_ee_bridge/src/emqx_ee_bridge_kafka.erl

fix: hide nodelay Kafka client socket option

---

apps/emqx_ft/src/emqx_ft_conf.erl
apps/emqx_ft/src/emqx_ft_storage_fs.erl
apps/emqx_ft/src/emqx_ft_storage_fs_gc.erl

This should unbreak assembler tests.
---
[EMQX-9061](https://emqx.atlassian.net/browse/EMQX-9061)

fix(ft-fs): move default config to the backend impl

---

bin/emqx

Fixes https://emqx.atlassian.net/browse/EMQX-9391

chore: show ulimit warning on start only

---

apps/emqx_dashboard/README.md

Fixes [EMQX-9256](https://emqx.atlassian.net/browse/EMQX-9256)
Make sure to target release-50 branch if this PR is intended to fix the issues for the release candidate.
- [-] Added tests for the changes
- [-] Changed lines covered in coverage report
- [-] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` files
- [-] Schema changes are backward compatible

README for EMQX Dashboard

---

README.md

https://emqx.atlassian.net/browse/EMQX-9387

docs (readme): update heading and add slack link to "Get Involved" section

---

apps/emqx/i18n/emqx_schema_i18n.conf

Fixes https://emqx.atlassian.net/browse/EMQX-9322
- ~Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` and `.zh.md` files~
- ~If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up~

docs: improve some mqtt options description

---

lib-ee/emqx_ee_connector/rebar.config
mix.exs
rebar.config

Fixes [EMQX-9249](https://emqx.atlassian.net/browse/EMQX-9249)

chore: bump hackney version

---

apps/emqx_management/README.md

Fixes [EMQX-9253](https://emqx.atlassian.net/browse/EMQX-9253)
Make sure to target release-50 branch if this PR is intended to fix the issues for the release candidate.
- [-] Added tests for the changes
- [-] Changed lines covered in coverage report
- [-] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` files
- [-] Schema changes are backward compatible

EMQX Management README

---

apps/emqx_gateway/src/emqx_gateway_app.erl
apps/emqx_gateway/src/emqx_gateway_schema.erl
apps/emqx_gateway/src/emqx_gateway_utils.erl
bin/nodetool
changes/ce/fix-10410.en.md

https://github.com/emqx/emqx/pull/10410

0417 port 10410 to e5.0.3

---

apps/emqx_authn/src/simple_authn/emqx_authn_jwks_connector.erl
apps/emqx_connector/src/emqx_connector_http.erl
apps/emqx_connector/src/emqx_connector_ldap.erl
apps/emqx_connector/src/emqx_connector_mongo.erl
apps/emqx_connector/src/emqx_connector_mysql.erl
apps/emqx_connector/src/emqx_connector_pgsql.erl
apps/emqx_connector/src/emqx_connector_redis.erl
apps/emqx_connector/test/emqx_connector_mongo_SUITE.erl
apps/emqx_connector/test/emqx_connector_mysql_SUITE.erl
apps/emqx_connector/test/emqx_connector_pgsql_SUITE.erl
apps/emqx_connector/test/emqx_connector_redis_SUITE.erl
apps/emqx_resource/src/emqx_resource_pool.erl
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_gcp_pubsub_SUITE.erl
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_mongodb_SUITE.erl
lib-ee/emqx_ee_bridge/test/emqx_ee_bridge_mysql_SUITE.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_cassa.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_clickhouse.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_dynamo.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_gcp_pubsub.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_sqlserver.erl
lib-ee/emqx_ee_connector/src/emqx_ee_connector_tdengine.erl
lib-ee/emqx_ee_connector/test/emqx_ee_connector_cassa_SUITE.erl
lib-ee/emqx_ee_connector/test/emqx_ee_connector_clickhouse_SUITE.erl

Fixes [EMQX-9257](https://emqx.atlassian.net/browse/EMQX-9257).
This module was previously known as `emqx_plugin_libs_pool`. This is part of the effort to get rid of `emqx_plugin_libs` application.
Also make naming across connectors / testsuites more consistent.

feat(respool): switch to `emqx_resource_pool`

---

.github/workflows/build_packages.yaml

Also remove `container: ` spec from the job as `buildx.sh` already does that

ci: build both ce and ee packages in scheduled builds

---

.github/workflows/build_packages_cron.yaml

fix: build_packages_cron.yaml workflow

---

apps/emqx/test/emqx_mqtt_caps_SUITE.erl

quick fix broken test suite on master

test: fix emqx_mqtt_caps_SUITE

---

.github/workflows/build_packages.yaml
scripts/buildx.sh

ci: port 10619 to release-50

---

.github/workflows/build_packages.yaml
.github/workflows/release.yaml

ci: move package upload to packagecloud.io to release workflow

---

.github/workflows/performance_test.yaml

- fix 1on1 scenario
- add 1m conns scenario
- use eu-west-1 region, and collect metrics for all runs in AWS managed prometheus
- use separate slack channel for notifications

0530 update perf test

---

.github/workflows/run_jmeter_tests.yaml
README.md

- update links to point to 5.1
- add info about homebrew package

docs: update Get Started section in README.md

---

.github/workflows/performance_test.yaml

Add 'Fan In' and 'Fan Out' scenarios, and make use of https://github.com/emqx/tf-emqx-performance-test/pull/5
Will replace `emqx/tf-emqx-performance-test` ref with appropriate tag as soon as the PR above is merged.

ci: update performance test

---

deploy/charts/emqx/templates/StatefulSet.yaml

Test the changes with my helm Deployment.

correct spelling mistakes

---

.github/workflows/release.yaml
scripts/rerun-apps-version-check.py

To address the issue when apps version check fails on new pull requests right after release.

ci: rerun apps version check on release

---

build
scripts/macos-sign-binaries.sh

https://github.com/emqx/emqx/actions/runs/5511660693/jobs/10047521834

fix: add ezstd_nif.so to macos signing

---

.github/workflows/release.yaml
scripts/rerun-apps-version-check.py

Verified on a test branch: https://github.com/emqx/emqx/actions/runs/5512788691/jobs/10050057360

ci: fix rerun apps check token scope and improve logging

---

apps/emqx_rule_engine/src/emqx_rule_engine.erl
apps/emqx_rule_engine/src/emqx_rule_index.erl
apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_index_SUITE.erl

Revert "Fix(topicidx): allow to return matches unique by record id"

---

apps/emqx/include/emqx_release.hrl
changes/e5.1.1.en.md

Changelog from https://github.com/emqx/emqx-docs/pull/2013

chore: e5.1.1

---

apps/emqx/include/emqx_release.hrl
changes/v5.1.4.en.md
deploy/charts/emqx/Chart.yaml

chore: v5.1.4

---

changes/ce/feat-10697.en.md

Add changelog entry for #10697

Add changelog entry

---

.github/workflows/build_packages_cron.yaml

ci: add daily build of emqx-enterprise for debian10 platform

---

deploy/charts/emqx-enterprise/README.md
deploy/charts/emqx-enterprise/templates/service.yaml
deploy/charts/emqx-enterprise/values.yaml
deploy/charts/emqx/README.md
deploy/charts/emqx/templates/service.yaml
deploy/charts/emqx/values.yaml

Fixes none
Insert loadBalancerClass in the service manifest. Required for clusters with multiple loadbalancers.

feat(helm-chart): add support for loadBalancerClass

---

bin/nodetool
deploy/packages/deb/debian/rules
deploy/packages/rpm/emqx.spec

follow up fix for https://github.com/emqx/emqx/pull/11550

fix(nodetool): ensure patches dir added for rpm/deb installs

---

apps/emqx/rebar.config
apps/emqx/test/emqx_crl_cache_SUITE.erl
apps/emqx_retainer/rebar.config
mix.exs
rebar.config

this PR only fixes flaky tests.

0918 upgrade emqtt to 1.8.7

---

apps/emqx/rebar.config
apps/emqx/src/emqx_cm_sup.erl
apps/emqx/test/emqx_flapping_SUITE.erl
apps/emqx/test/emqx_shared_sub_SUITE.erl
apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_producer_SUITE.erl
changes/ce/fix-11622.en.md
mix.exs
rebar.config

Fixes [EMQX-9749](https://emqx.atlassian.net/browse/EMQX-9749)

chore(gen_rpc): upgrade from 2.8.1 to 3.1.0

---

apps/emqx_authn/src/emqx_authn.app.src
apps/emqx_authn/src/emqx_authn_schema.erl

fixes [EMQX-11083](https://emqx.atlassian.net/browse/EMQX-11083)
Introduced since 5.2, the root level "authentication" config is marked as "hidden".
As a result, the schema dump did not include this root key.

fix(authn): "authentication" importance should not be "hidden"

---

dev

Supports _checkouts and short names for erlang node names (so you can connect from an IDE for instance)

some minor improvements to ./dev 

---

apps/emqx/src/emqx_hookpoints.erl
apps/emqx_plugins/test/emqx_plugins_SUITE.erl
changes/ce/fix-11886.en.md

Port of https://github.com/emqx/emqx/pull/11886 to the release branch

fix old plugin compatibility

---

apps/emqx_mongodb/rebar.config
changes/ce/fix-11955.en.md

Fixes EMQX-11350
https://github.com/emqx/emqx/pull/11955, but for release-53

fix deadlock while stopping mongodb resource

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge_confluent/BSL.txt
apps/emqx_bridge_confluent/README.md
apps/emqx_bridge_confluent/docker-ct
apps/emqx_bridge_confluent/rebar.config
apps/emqx_bridge_confluent/src/emqx_bridge_confluent.app.src
apps/emqx_bridge_confluent/src/emqx_bridge_confluent_producer.erl
apps/emqx_bridge_confluent/src/emqx_bridge_confluent_producer_action_info.erl
apps/emqx_bridge_confluent/test/emqx_bridge_confluent_producer_SUITE.erl
apps/emqx_bridge_confluent/test/emqx_bridge_confluent_tests.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_machine/priv/reboot_lists.eterm
mix.exs
rebar.config.erl
rel/i18n/emqx_bridge_confluent_producer.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-11044
See also: https://emqx.atlassian.net/wiki/spaces/EMQX/pages/712179934/Confluent+Integration

feat: add confluent connector/action

---

apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11394

fix(actions_api): don't crash on validation errors

---

apps/emqx/include/emqx_release.hrl
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml

chore: bump release version to e5.3.2-alpha.1

---

apps/emqx/src/emqx_persistent_message.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_schema.erl
apps/emqx_durable_storage/src/emqx_ds.erl
apps/emqx_durable_storage/src/emqx_ds_app.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
apps/emqx_durable_storage/src/emqx_ds_sup.erl
apps/emqx_durable_storage/src/proto/emqx_ds_proto_v1.erl
apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
rel/i18n/emqx_schema.hocon

Implement a prototype of durable message sharding

---

apps/emqx_gateway/src/emqx_gateway_schema.erl
apps/emqx_gateway_ocpp/src/emqx_ocpp_conf.erl
apps/emqx_gateway_ocpp/src/emqx_ocpp_schemas.erl

fix(ocpp): fix bad webscoket schema for HTTP API

---

apps/emqx/src/emqx_persistent_message.erl
apps/emqx/src/emqx_schema.erl
apps/emqx_durable_storage/src/emqx_ds.erl

Fixes [EMQX-11391](https://emqx.atlassian.net/browse/EMQX-11391)
- [na] Added tests for the changes (happy path is changed, fdb tests will follow)
- [na] Changed lines covered in coverage report
- [na] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files

feat(ds): allow fdb implementation for durable storage

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.app.src
apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src

feat(actions): allow multiple action info modules per application

---

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl

test(gcp_pubsub_consumer): fix flaky test

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_producer_schema.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl

fix(gcp_pubsub_producer): add missing references to api specs

---

apps/emqx_durable_storage/src/emqx_ds.erl

[EMQX-11391](https://emqx.atlassian.net/browse/EMQX-11391)

fix(ds): impose more flexible types for ds implementations

---

apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11224

feat(ds): Don't store #message record in the DB

---

apps/emqx/src/emqx_message.erl
apps/emqx/src/emqx_persistent_message.erl
apps/emqx/src/emqx_persistent_message_ds_replayer.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_schema.erl
apps/emqx/src/emqx_session.erl
apps/emqx/test/emqx_persistent_messages_SUITE.erl
apps/emqx_durable_storage/src/emqx_ds_lts.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11370

Support QoS0 messages in persistent_session_ds

---

apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_shared_sub.erl
apps/emqx/test/emqx_persistent_session_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11452

Discard sessions when client connects with clean start = true

---

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl

test: fix another flaky test

---

.github/pull_request_template.md

Ensure PR author is aware of the target release version.

chore: update pr request template

---

apps/emqx_license/src/emqx_license_checker.erl
apps/emqx_license/src/emqx_license_http_api.erl
apps/emqx_license/src/emqx_license_parser.erl
apps/emqx_license/src/emqx_license_parser_v20220101.erl
apps/emqx_license/src/emqx_license_schema.erl
apps/emqx_license/test/emqx_license_SUITE.erl
apps/emqx_license/test/emqx_license_checker_SUITE.erl
apps/emqx_license/test/emqx_license_cli_SUITE.erl
apps/emqx_license/test/emqx_license_http_api_SUITE.erl
apps/emqx_license/test/emqx_license_parser_SUITE.erl
apps/emqx_license/test/emqx_license_test_lib.erl
changes/ee/feat-12016.en.md
rel/i18n/emqx_license_schema.hocon

Fixes [EMQX-11397](https://emqx.atlassian.net/browse/EMQX-11397) and [EMQX-11147](https://emqx.atlassian.net/browse/EMQX-11147)

1122 load license file

---

apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge/src/proto/emqx_bridge_proto_v5.erl
apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11381
Release version: e5.4.0

feat: add `/actions/:id/metrics/`, `/actions/:id/metrics/reset` APIs

---

apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl
apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.erl
apps/emqx_bridge_confluent/src/emqx_bridge_confluent_producer.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_producer_schema.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
apps/emqx_bridge_matrix/src/emqx_bridge_matrix.erl
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.erl
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_connector.erl
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_proxy.erl
apps/emqx_bridge_timescale/src/emqx_bridge_timescale.erl
apps/emqx_connector/src/emqx_connector_api.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_connector/test/emqx_connector_api_SUITE.erl
apps/emqx_postgresql/src/schema/emqx_postgresql_connector_schema.erl
rel/i18n/emqx_connector_schema.hocon

Fixes [EMQX-11382](https://emqx.atlassian.net/browse/EMQX-11382)
Release version: v5.4.0

feat(emqx_connector): add field 'actions' in API response

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
apps/emqx/src/emqx_channel.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_persistent_session_ds.hrl
apps/emqx/src/emqx_schema.erl
apps/emqx/src/emqx_session.erl
apps/emqx/src/emqx_session_mem.erl
apps/emqx/test/emqx_persistent_session_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11048

feat(ds): session expiry

---

apps/emqx_license/src/emqx_license_schema.erl
apps/emqx_license/test/emqx_license_http_api_SUITE.erl

https://emqx.atlassian.net/browse/EMQX-11472
Release version: v/e5.3.2

fix: validate error when set license's watermark to 100%

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl

fix(ds): Persist shard table

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_worker.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl

test: attempting to stabilize more flaky tests

---

apps/emqx_redis/src/emqx_redis.app.src
changes/ce/fix-12044.en.md

Fixes [EMQX-11441](https://emqx.atlassian.net/browse/EMQX-11441)
Release version: v5.3.2
- [na] Added tests for the changes
- [na] Changed lines covered in coverage report

[5.3] Fix Redis connector

---

apps/emqx/rebar.config
apps/emqx/rebar.config.script
apps/emqx/src/emqx_quic_stream.erl
apps/emqx/test/emqx_quic_multistreams_SUITE.erl
changes/ce/feat-12040.en.md
mix.exs
rebar.config
rebar.config.erl

feat(quic): bump to quicer-0.0.303

---

apps/emqx/rebar.config
apps/emqx/src/emqx_channel.erl
apps/emqx/src/emqx_persistent_message_ds_replayer.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_persistent_session_ds.hrl
apps/emqx/test/emqx_persistent_messages_SUITE.erl
apps/emqx/test/emqx_persistent_session_SUITE.erl
apps/emqx_retainer/rebar.config
mix.exs
rebar.config

Fixes [EMQX-11049](https://emqx.atlassian.net/browse/EMQX-11049).

feat(sessds): provide QoS2 message replay support

---

.github/workflows/release.yaml

Fixes https://github.com/emqx/emqx/actions/runs/7021183518/job/19102622956#step:6:12
https://github.com/emqx/upload-assets/pull/1

ci: fix insufficient permissions for github token in release workflow

---

apps/emqx_management/src/emqx_mgmt_api_data_backup.erl

EMQX-11488 empty data file validation

---

apps/emqx_bridge_http/src/emqx_bridge_http_action_info.erl
apps/emqx_bridge_http/src/emqx_bridge_http_schema.erl
apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl
apps/emqx_bridge_http/test/emqx_bridge_http_v2_SUITE.erl

Fixes 
https://emqx.atlassian.net/browse/EMQX-11480
https://emqx.atlassian.net/browse/EMQX-11482
https://emqx.atlassian.net/browse/EMQX-11486
Release version: v/e5.3.2
- ~Change log has been added to `changes/` …

Fix http bridge bugs

---

.ci/docker-compose-file/redis/sentinel-tcp/sentinel-base.conf
.ci/docker-compose-file/redis/sentinel-tls/sentinel-base.conf
apps/emqx_auth_redis/src/emqx_authn_redis_schema.erl
apps/emqx_auth_redis/src/emqx_authz_redis_schema.erl
apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis.app.src
apps/emqx_bridge_redis/src/emqx_bridge_redis.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis_action_info.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis_connector.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis_schema.erl
apps/emqx_bridge_redis/test/emqx_bridge_redis_SUITE.erl
apps/emqx_connector/src/emqx_connector.app.src
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
apps/emqx_redis/src/emqx_redis.erl
apps/emqx_redis/test/emqx_redis_SUITE.erl
apps/emqx_rule_engine/src/emqx_rule_engine.app.src
rel/i18n/emqx_bridge_redis.hocon
rel/i18n/emqx_bridge_redis_schema.hocon
rel/i18n/emqx_connector_schema.hocon
rel/i18n/emqx_redis.hocon
scripts/pre-compile.sh

close https://github.com/emqx/emqx/pull/12007

Redis connector v2 540

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_worker.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl

test(flaky): more adjustments

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
apps/emqx/src/emqx_cm_sup.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_persistent_session_ds_gc_sup.erl
apps/emqx/src/emqx_persistent_session_ds_gc_worker.erl
apps/emqx/src/emqx_persistent_session_ds_sup.erl
apps/emqx/src/emqx_schema.erl
apps/emqx/test/emqx_persistent_session_SUITE.erl
rel/i18n/emqx_schema.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-9744

feat(ds): add session gc process

---

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_producer_SUITE.erl
apps/emqx_resource/src/emqx_resource_buffer_worker.erl
apps/emqx_resource/src/emqx_resource_manager.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11494

fix(kafka_producer): add `resource_opts` to connector schema, and check for client connectivity

---

rel/i18n/emqx_bridge_api.hocon
rel/i18n/emqx_bridge_azure_event_hub.hocon
rel/i18n/emqx_bridge_v2_api.hocon
rel/i18n/emqx_connector_api.hocon
rel/i18n/emqx_connector_schema.hocon
rel/i18n/emqx_limiter_schema.hocon
rel/i18n/emqx_resource_schema.hocon
rel/i18n/emqx_schema.hocon

NOTE: It's intended to be merged to `release-53` first.
Sync some doc changes made in emqx-i18n.git but not synced here.

1201 docs sync i18n changes

---

apps/emqx/src/emqx_persistent_message_ds_replayer.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_schema.erl
apps/emqx/src/emqx_session.erl
apps/emqx/test/emqx_takeover_SUITE.erl
apps/emqx_durable_storage/README.md
apps/emqx_durable_storage/src/proto/emqx_ds_proto_v1.erl
rel/i18n/emqx_schema.hocon

Various minor fixes

---

apps/emqx/rebar.config
changes/ce/fix-12081.en.md
mix.exs
rebar.config

chore(gen_rpc): Bump version to 3.3.0

---

apps/emqx/include/emqx_release.hrl
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml
mix.exs
rebar.config
scripts/pre-compile.sh
scripts/rel/cut.sh
scripts/rel/sync-remotes.sh

chore: 5.4.0-alpha.1

---

changes/ce/feat-12089.en.md

docs: Add a changelog entry for emqx_persistent_session_ds

---

apps/emqx_connector/src/emqx_connector_resource.erl
apps/emqx_connector/test/emqx_connector_SUITE.erl
apps/emqx_connector/test/emqx_connector_dummy_impl.erl
apps/emqx_resource/include/emqx_resource.hrl
apps/emqx_resource/src/emqx_resource_manager.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11448

fix(connector): don't start buffer workers for the connector itself

---

apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
apps/emqx_rule_engine/src/emqx_rule_sqltester.erl
apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11449

fix(rule_api): fix sql test when testing against events

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl

fix(bridge_gcp): Don't print config to the logs

---

.github/workflows/build_packages_cron.yaml
apps/emqx_gateway_coap/src/emqx_gateway_coap.app.src

Requested by QA.
Release version: v/e5.4.x

ci: run scheduled packages build of release-54

---

apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl
mix.exs
rebar.config

Fixes https://emqx.atlassian.net/browse/EMQX-11523

fix(api): return list of dependent rule ids when trying to delete bridge/action

---

apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_bridge/test/emqx_bridge_v1_compatibility_layer_SUITE.erl
apps/emqx_utils/src/emqx_utils.erl
apps/emqx_utils/test/emqx_utils_tests.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11533

fix(bridges/actions api): correctly deobfuscate passwords when probing

---

apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11405

chore: stop downgrading action id in rule API responses

---

apps/emqx_bridge_pgsql/test/emqx_bridge_pgsql_SUITE.erl
apps/emqx_postgresql/src/emqx_postgresql.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11490

chore(postgres): prettify logged errors

---

apps/emqx/rebar.config
mix.exs
rebar.config

fix: bump to esockd 8.9.9  improve robustness

---

apps/emqx_audit/src/emqx_audit.erl
apps/emqx_conf/src/emqx_conf_schema.erl
apps/emqx_ctl/src/emqx_ctl.app.src
apps/emqx_ctl/src/emqx_ctl.erl
apps/emqx_dashboard/src/emqx_dashboard_audit.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11535

fix: audit log format

---

apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl
apps/emqx_bridge/test/emqx_bridge_v2_tests.erl
apps/emqx_bridge_matrix/src/emqx_bridge_matrix.erl
apps/emqx_bridge_pgsql/src/emqx_bridge_pgsql.erl
apps/emqx_bridge_timescale/src/emqx_bridge_timescale.erl
apps/emqx_connector/test/emqx_connector_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11541

fix(actions_api): add missing fields to API spec and returned data

---

apps/emqx_connector/src/emqx_connector_api.erl
apps/emqx_connector/test/emqx_connector_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11562

fix(connectors_api): fill default raw config values before returning

---

apps/emqx_gateway_gbt32960/src/emqx_gbt32960_channel.erl

[EMQX-11559](https://emqx.atlassian.net/browse/EMQX-11559)

fix(gbt): Add unimplemented command call

---

apps/emqx/src/emqx_channel.erl
apps/emqx/test/emqx_channel_SUITE.erl
apps/emqx/test/emqx_proper_types.erl
apps/emqx_exhook/priv/protos/exhook.proto
apps/emqx_exhook/src/emqx_exhook_handler.erl
apps/emqx_exhook/test/emqx_exhook_SUITE.erl
apps/emqx_exhook/test/props/prop_exhook_hooks.erl
changes/feat-12114.en.md

Fixes [EMQX-10793](https://emqx.atlassian.net/browse/EMQX-10793)
Releated PR https://github.com/emqx/emqx-extension-examples/pull/36

EMQX-10793 exhook clientinfo peerport

---

apps/emqx_conf/src/emqx_cluster_rpc.erl
apps/emqx_conf/test/emqx_cluster_rpc_SUITE.erl
changes/ce/fix-12121.en.md

fix: occasionally return stale view when updating configurations 

---

apps/emqx_auth_ldap/src/emqx_authn_ldap_bind.erl
apps/emqx_auth_ldap/src/emqx_authn_ldap_schema.erl

[EMQX-11547](https://emqx.atlassian.net/browse/EMQX-11548)

 fix(authn_ldap): Improve the type inference of method union

---

apps/emqx_bridge_redis/src/emqx_bridge_redis_schema.erl

chore: update redis bridge example

---

apps/emqx_dashboard/src/emqx_dashboard_listener.erl
apps/emqx_prometheus/src/emqx_prometheus_api.erl
apps/emqx_prometheus/src/emqx_prometheus_config.erl
apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl
apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl

fix: only return recommend setting when get prometheus api

---

apps/emqx/src/emqx_connection.erl
apps/emqx/src/emqx_hocon.erl
apps/emqx/src/emqx_hookpoints.erl
apps/emqx/src/emqx_limiter/src/emqx_htb_limiter.erl
apps/emqx/src/emqx_limiter/src/emqx_limiter_bucket_ref.erl
apps/emqx/src/emqx_limiter/src/emqx_limiter_container.erl
apps/emqx/src/emqx_listeners.erl
apps/emqx/src/emqx_metrics.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_persistent_session_ds/emqx_ps_ds_int.hrl
apps/emqx/src/emqx_router.erl
apps/emqx/src/emqx_session.erl
apps/emqx/src/emqx_session_events.erl
apps/emqx/src/emqx_sup.erl
apps/emqx/src/emqx_tls_lib.erl
apps/emqx/src/emqx_tls_psk.erl
apps/emqx/src/emqx_topic_index.erl
apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
apps/emqx/src/emqx_trace/emqx_trace_handler.erl
apps/emqx_bridge_hstreamdb/test/emqx_bridge_hstreamdb_SUITE.erl
apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl
apps/emqx_dashboard/test/emqx_swagger_response_SUITE.erl
apps/emqx_durable_storage/src/emqx_ds.erl
apps/emqx_durable_storage/test/props/emqx_ds_message_storage_bitmask_shim.erl
apps/emqx_durable_storage/test/props/payload_gen.erl
apps/emqx_machine/src/emqx_machine.app.src
apps/emqx_telemetry/test/emqx_telemetry_SUITE.erl
rebar.config.erl

Release version: `v/e5.4.0`
last batch dialyzer fix for otp26

fix(dialyzer): batch 3

---

apps/emqx_auth_mysql/src/emqx_auth_mysql.app.src
apps/emqx_auth_mysql/src/emqx_authn_mysql_schema.erl
apps/emqx_auth_mysql/src/emqx_authz_mysql_schema.erl
apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.erl
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb_action_info.erl
apps/emqx_bridge_mysql/src/emqx_bridge_mysql.app.src
apps/emqx_bridge_mysql/src/emqx_bridge_mysql.erl
apps/emqx_bridge_mysql/src/emqx_bridge_mysql_action_info.erl
apps/emqx_bridge_mysql/src/emqx_bridge_mysql_connector.erl
apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_mysql/rebar.config
apps/emqx_mysql/src/emqx_mysql.erl
apps/emqx_utils/src/emqx_utils_maps.erl
apps/emqx_utils/test/emqx_utils_maps_tests.erl
mix.exs
rebar.config
rel/i18n/emqx_bridge_mysql.hocon

Fixes [EMQX-11154](https://emqx.atlassian.net/browse/EMQX-11154)

feat(emqx_bridge_mysql): port to shared connectors

---

apps/emqx/.gitignore
apps/emqx_management/src/emqx_mgmt_api_topics.erl
apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl
changes/fix-12141.en.md

Fixes [EMQX-11519](https://emqx.atlassian.net/browse/EMQX-11519)

Fix shared sub api internal error

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/emqx_bridge_lib.erl
apps/emqx_bridge/src/emqx_bridge_v2.erl
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb_action_info.erl
apps/emqx_bridge_mysql/src/emqx_bridge_mysql.erl
apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl
apps/emqx_utils/src/emqx_utils_maps.erl
apps/emqx_utils/test/emqx_utils_maps_tests.erl

Fixes [EMQX-11487](https://emqx.atlassian.net/browse/EMQX-11487)

mongodb test connection failed

---

apps/emqx_opentelemetry/src/emqx_otel_config.erl
apps/emqx_opentelemetry/src/emqx_otel_schema.erl
apps/emqx_opentelemetry/test/emqx_otel_schema_SUITE.erl
apps/emqx_opentelemetry/test/emqx_otel_trace_SUITE.erl

Small fixes requested by EMQX Dashboard team to facilitate UI development. 

OTEL API fix hidden fields and ssl opts

---

apps/emqx_connector/src/emqx_connector_api.erl
apps/emqx_connector/test/emqx_connector_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11583

feat(connector_api): list disabled channels too

---

apps/emqx_connector/src/emqx_connector_api.erl
apps/emqx_connector/test/emqx_connector_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11581

fix(connector_api): return status reason when status is inconsistent

---

apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11513

fix:add descriptions fields to bridge_v1

---

apps/emqx_bridge_http/src/emqx_bridge_http_action_info.erl
apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11560

fix: don't require path in http action(fill default path)

---

apps/emqx_ctl/src/emqx_ctl.erl
apps/emqx_machine/src/emqx_machine_terminator.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11542

fix: incorrect behavior in audit logs during stop and start of EMQX

---

apps/emqx/rebar.config
apps/emqx_license/test/emqx_license_http_api_SUITE.erl
mix.exs
rebar.config

Fixes https://emqx.atlassian.net/browse/EMQX-11485

fix: license watermark percent support float

---

apps/emqx_auth/src/emqx_authn/emqx_authn_utils.erl
apps/emqx_conf/test/emqx_conf_schema_tests.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11575

feat: don't merge default headers if user already setting

---

apps/emqx_audit/src/emqx_audit.erl
apps/emqx_audit/src/emqx_audit_api.erl
apps/emqx_audit/test/emqx_audit_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11543

fix: audit create_at/duration_ms filter not working

---

apps/emqx/rebar.config
apps/emqx/src/emqx_config.erl
apps/emqx/src/emqx_schema_secret.erl
apps/emqx_dashboard_sso/src/emqx_dashboard_sso_manager.erl
mix.exs
rebar.config

Fixes [EMQX-11580](https://emqx.atlassian.net/browse/EMQX-11580)

fix(sso): Correctly handle wrapped passwords when updating

---

apps/emqx/src/emqx_persistent_message_ds_replayer.erl

feat(ds): implemented the replayer scheduler

---

apps/emqx_audit/test/emqx_audit_api_SUITE.erl

test: audit max_size flaky test

---

apps/emqx/priv/bpapi.versions
apps/emqx/src/emqx_persistent_message_ds_replayer.erl
apps/emqx/test/emqx_persistent_messages_SUITE.erl
apps/emqx_durable_storage/src/emqx_ds.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
apps/emqx_durable_storage/src/proto/emqx_ds_proto_v1.erl
apps/emqx_durable_storage/src/proto/emqx_ds_proto_v2.erl
apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl

Part of https://emqx.atlassian.net/browse/EMQX-10943

chore(ds): return DS key from `next` and add `update_iterator` callback

---

apps/emqx_connector/test/emqx_connector_api_SUITE.erl
apps/emqx_resource/src/emqx_resource.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11586

fix(connector_api): avoid calling resource process to get channels

---

apps/emqx/test/emqx_bpapi_static_checks.erl
apps/emqx/test/emqx_static_checks.erl

fix(static_checks): Prepare for OTP26

---

apps/emqx_redis/rebar.config
changes/ce/fix-12158.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11434
Release version: v5.4.x

chore: update eredis_cluster to 0.8.3

---

apps/emqx_gateway/src/emqx_gateway_api.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11492

fix: ocpp swagger example broken

---

apps/emqx_auth_http/src/emqx_auth_http.app.src
apps/emqx_auth_http/src/emqx_authz_http_schema.erl

feat: don't merge authz default headers if user already setting

---

apps/emqx_gateway/src/emqx_gateway_utils.erl
apps/emqx_gateway_ocpp/src/emqx_ocpp_schemas.erl
apps/emqx_gateway_ocpp/test/emqx_ocpp_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11493
- ~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~ New feature for e5.4.0
- ~ Change log has been added to `changes/` dir for user-facing …

fix(ocpp): fix 500 return for `PUT ...gateway/ocpp/<listener_id>`

---

apps/emqx_gateway_ocpp/src/emqx_ocpp_channel.erl

Fixes [EMQX-11498](https://emqx.atlassian.net/browse/EMQX-11498)

fix(gw_ocpp): handle subscriptions call

---

apps/emqx_gateway_gbt32960/src/emqx_gbt32960_channel.erl
apps/emqx_gateway_jt808/src/emqx_jt808_channel.erl
apps/emqx_gateway_jt808/test/emqx_jt808_SUITE.erl

Fixes [EMQX-11525](https://emqx.atlassian.net/browse/EMQX-11525)
Release version: v/e5.4.0?

Emqx 11525 gw jt808 cannot list client

---

apps/emqx_bridge/test/emqx_bridge_v2_SUITE.erl
apps/emqx_rule_engine/src/emqx_rule_runtime.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11494

feat(rule_engine): also bump `unknown` counter for unrecoverable action errors

---

apps/emqx/src/emqx_external_trace.erl
apps/emqx_opentelemetry/src/emqx_otel_config.erl
apps/emqx_opentelemetry/src/emqx_otel_trace.erl
apps/emqx_opentelemetry/test/emqx_otel_api_SUITE.erl

EMQX-11596 convert otel exporter certs

---

Makefile
apps/emqx_gateway_ocpp/test/emqx_ocpp_SUITE.erl

Fixes [EMQX-11496](https://emqx.atlassian.net/browse/EMQX-11496) …

EMQX 11496 ocpp re enable failed

---

apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_bridge/src/schema/emqx_bridge_v2_schema.erl
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.erl
apps/emqx_bridge_mysql/src/emqx_bridge_mysql.erl

Fixes [EMQX-11587](https://emqx.atlassian.net/browse/EMQX-11587)

refactor(emqx_bridge): common api_fields fn for actions

---

apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/schema/emqx_bridge_enterprise.erl
apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_bridge/test/emqx_bridge_compatible_config_tests.erl
apps/emqx_bridge/test/emqx_bridge_v1_compatibility_layer_SUITE.erl
apps/emqx_bridge_kafka/test/emqx_bridge_kafka_tests.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis_action_info.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis_connector.erl
apps/emqx_bridge_redis/src/emqx_bridge_redis_schema.erl
apps/emqx_bridge_redis/test/emqx_bridge_redis_SUITE.erl
apps/emqx_redis/src/emqx_redis.erl
apps/emqx_resource/test/emqx_resource_schema_tests.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11593

fix(bridge_v1_api): fill defaults for v2 raw configs and fix redis connector schema

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_producer_schema.erl

fix(gcp_pubsub_producer): mark `local_topic` as hidden in action schema

---

apps/emqx_bridge_azure_event_hub/rebar.config
apps/emqx_bridge_confluent/rebar.config
apps/emqx_bridge_kafka/rebar.config
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
changes/ee/feat-12194.en.md
mix.exs

Fixes [EMQX-11297](https://emqx.atlassian.net/browse/EMQX-11297)
Upgrade from 1.8.0:
- wollf-1.9.0 has the global stats disabled by default
- wolff-1.9.1 improved client pid lookup performance

perf: upgrade to wolff 1.9.1 for better performance

---

apps/emqx_bridge_mysql/src/emqx_bridge_mysql_connector.erl
apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl
apps/emqx_mysql/src/emqx_mysql.erl
apps/emqx_utils/src/emqx_utils_sql.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11605

fix(mysql_bridge): forbid update statements with batch operations

---

apps/emqx_bridge_redis/src/emqx_bridge_redis_connector.erl
apps/emqx_bridge_redis/test/emqx_bridge_v2_redis_SUITE.erl

test(redis_action): add minimal smoke tests

---

apps/emqx_auth/src/emqx_authz/emqx_authz_rule_raw.erl
apps/emqx_auth/src/emqx_authz/sources/emqx_authz_client_info.erl
apps/emqx_auth_jwt/src/emqx_auth_jwt.app.src
apps/emqx_auth_jwt/src/emqx_authn_jwt.erl
apps/emqx_auth_jwt/test/emqx_authz_jwt_SUITE.erl
apps/emqx_auth_mnesia/test/emqx_authz_mnesia_SUITE.erl
changes/ce/feat-12189.en.md
rel/i18n/emqx_authn_jwt_schema.hocon

Fixes https://github.com/emqx/emqx/issues/12187 and [EMQX-11372](https://emqx.atlassian.net/browse/EMQX-11372)

feat: support regular raw acl rule in jwt acl claim

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_worker.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl

test(gcp_pubsub_consumer): another attempt to stabilize flaky tests

---

apps/emqx_gateway/src/emqx_gateway_api_clients.erl
apps/emqx_gateway/src/emqx_gateway_http.erl
apps/emqx_gateway_ocpp/src/emqx_ocpp_channel.erl
apps/emqx_gateway_ocpp/test/emqx_ocpp_SUITE.erl

Fixes [EMQX-11610](https://emqx.atlassian.net/browse/EMQX-11610) and [EMQX-11611](https://emqx.atlassian.net/browse/EMQX-11611)

EMQX 11610 gw ocpp subscription cnt

---

apps/emqx/src/emqx_config.erl
apps/emqx_conf/src/emqx_conf_cli.erl
apps/emqx_conf/test/emqx_conf_cli_SUITE.erl
apps/emqx_dashboard/test/emqx_swagger_requestBody_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_configs_SUITE_data/webhook_v1.conf

Fixes https://emqx.atlassian.net/browse/EMQX-11617

fix: support bridge v1 conf hocon-format in the put configs API.

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11618
The API return timestrap in rfc3339 way, but the default example is  `1640995200000`
Before:
```
{
"awaiting_rel_cnt": 0,
"awaiting_rel_max": 0,
"clean_start": true,
"clientid": "string",
"connected": true,
"connected_at": 1640995200000,
"created_at": 1640995200000,
"disconnected_at": 1640995200000,
"expiry_interval": 0,
"heap_size": 0,
"inflight_cnt": 0,
"inflight_max": 0,
"ip_address": "string",
"is_bridge": true,
"keepalive": 0,
"mailbox_len": 0,
"mqueue_dropped": 0,
"mqueue_len": 0,
"mqueue_max": 0,
"node": "string",
"port": 0,
"proto_name": "string",
"proto_ver": 0,
"recv_cnt": 0,
"recv_msg": 0,
"recv_msg.dropped": 0,
"recv_msg.dropped.await_pubrel_timeout": 0,
"recv_msg.qos0": 0,
"recv_msg.qos1": 0,
"recv_msg.qos2": 0,
"recv_oct": …
```

chore: add swagger example for clients http api

---

apps/emqx/include/emqx_release.hrl
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml

chore: prepare to tag `5.4.0-rc.1`

---

apps/emqx_conf/src/emqx_conf.erl

ci: fix typo in file name

---

apps/emqx_durable_storage/src/emqx_ds.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
apps/emqx_durable_storage/src/proto/emqx_ds_proto_v1.erl
apps/emqx_durable_storage/src/proto/emqx_ds_proto_v2.erl
apps/emqx_durable_storage/test/emqx_ds_SUITE.erl

Fixes [EMQX-11223](https://emqx.atlassian.net/browse/EMQX-11223)

feat(ds): add an API for making new generations

---

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl

Hopefully, should work better after https://github.com/emqx/emqx/pull/12197

test(gcp_pubsub_consumer): yet another attempt to stabilize tests

---

apps/emqx_bridge_redis/src/emqx_bridge_redis_action_info.erl
apps/emqx_management/src/emqx_mgmt_api_configs.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11621

fix: redis resource_opts not working

---

Makefile

- Supports backup
- Supports audit log
- Supports new action and connector in Webhook, KafkaProducer, AzureEventHubs, Confluent, PgSQL, TimescaleDB and MatrixDB, 
- Supports GBT32960, JT808 and OCPP in gateway
- Supports RBAC in API key
- New metrics
- Adapted the new prometheus API
- Supports monitoring integration OpenTelemetry
- Data integration new menu
- Supports LDAP bind method in authentication
- Supports file transfer configuration
- Supported reset license
- Fixed some issues

chore: upgrade dashboard to e1.4.0 for ee and v1.6.0 for ce

---

apps/emqx_bridge/src/emqx_bridge_v2.erl
apps/emqx_conf/src/emqx_conf_cli.erl
apps/emqx_connector/src/emqx_connector.erl
apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl

fix: emqx conf ctl load failed with connectors/actions

---

apps/emqx/include/emqx_release.hrl
changes/e5.4.0.en.md
changes/v5.4.0.en.md
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml

changelogs synced with https://github.com/emqx/emqx-docs/pull/2274

chore: prepare for release version 5.4.0

---

apps/emqx/src/emqx.app.src
apps/emqx_auth/src/emqx_auth.app.src
apps/emqx_auth_http/src/emqx_auth_http.app.src
apps/emqx_bridge/src/emqx_bridge.app.src
apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src
apps/emqx_bridge_greptimedb/src/emqx_bridge_greptimedb.app.src
apps/emqx_bridge_http/src/emqx_bridge_http.app.src
apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
apps/emqx_connector/src/emqx_connector.app.src
apps/emqx_connector/src/emqx_connector_api.erl
apps/emqx_durable_storage/src/emqx_durable_storage.app.src
apps/emqx_ft/src/emqx_ft.app.src
apps/emqx_ft/src/emqx_ft_api.erl
apps/emqx_ft/src/emqx_ft_conf.erl
apps/emqx_ft/test/emqx_ft_api_SUITE.erl
apps/emqx_gateway/src/emqx_gateway.app.src
apps/emqx_gateway_exproto/src/emqx_gateway_exproto.app.src
apps/emqx_gateway_ocpp/src/emqx_gateway_ocpp.app.src
apps/emqx_management/src/emqx_management.app.src
apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src
apps/emqx_rule_engine/src/emqx_rule_engine.app.src
apps/emqx_utils/src/emqx_utils.app.src
apps/emqx_utils/src/emqx_utils.erl

fix: FT deobfuscate secret key

---

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl

test: restore connect timeout for test case

---

apps/emqx/include/emqx_release.hrl
apps/emqx/src/emqx.app.src
apps/emqx_ft/test/emqx_ft_api_SUITE.erl
apps/emqx_management/src/emqx_management.app.src
apps/emqx_management/src/emqx_mgmt_api_configs.erl
deploy/charts/emqx-enterprise/Chart.yaml

1222 fix config update for ft

---

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl

test: reduce flakiness

---

apps/emqx_bridge_http/src/emqx_bridge_http.app.src
apps/emqx_bridge_http/src/emqx_bridge_http_schema.erl
apps/emqx_connector/src/emqx_connector.app.src
apps/emqx_connector/src/schema/emqx_connector_schema.erl
changes/ce/fix-12238.en.md
scripts/conf-test/old-confs/e5.3.2.conf

Fixes https://emqx.atlassian.net/browse/EMQX-11659
Release version: v/e5.4.1

fix(bridge-http): compatible conf with the error format introduced in 5.3.2

---

apps/emqx/src/emqx.app.src
apps/emqx_ft/src/emqx_ft.app.src
apps/emqx_ft/src/emqx_ft_api.erl
apps/emqx_ft/test/emqx_ft_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11664
related: https://github.com/emqx/emqx/pull/12235
Release version: v/e5.4.1

fix: return raw config when update ft's config

---

apps/emqx_durable_storage/src/emqx_ds.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
apps/emqx_durable_storage/test/emqx_ds_SUITE.erl

Little [EMQX-11223](https://emqx.atlassian.net/browse/EMQX-11223) follow-up.
- [na] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files

feat(ds): restore original add_generation/update_db_config callback semantics

---

apps/emqx_conf/src/emqx_conf_cli.erl
apps/emqx_conf/test/emqx_conf_cli_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl
changes/ee/fix-12240.en.md
changes/ee/fix-12249.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11675
Release version: v/e5.4.1

fix: the API prompt garbled characters for updating the configuration

---

apps/emqx_bridge_mysql/test/emqx_bridge_mysql_SUITE.erl
apps/emqx_mysql/src/emqx_mysql.app.src
apps/emqx_mysql/src/emqx_mysql.erl
apps/emqx_mysql/test/emqx_mysql_SUITE.erl
changes/ee/fix-12256.en.md

fix(mysql): expect password may be missing from config

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/emqx_bridge.app.src
apps/emqx_bridge_influxdb/rebar.config
apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb.app.src
apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb.erl
apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_action_info.erl
apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl
apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_SUITE.erl
apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_connector_SUITE.erl
apps/emqx_connector/src/emqx_connector.app.src
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
mix.exs
rel/i18n/emqx_bridge_influxdb.hocon
rel/i18n/emqx_bridge_influxdb_connector.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-11459
Release version: e5.5.0

refactor: split influxdb bridges to actions and connectors

---

Makefile

- Incorrect unsaved reminder in monitoring integration configuration page
- GB/T 32960 gateway default http authentication configuration value
- Added tips to JT/T 808 authentication configuration page
- Optimize search of audit log page
- Some typo on the audit log page
- Improve permission restrictions

chore: upgrade dashboard to e1.4.1 for ee

---

apps/emqx_gateway/src/emqx_gateway_cm.erl

Fixes 
judgment condition failure

fix:judgment condition failure

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/schema/emqx_bridge_enterprise.erl
apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.app.src
apps/emqx_bridge_azure_event_hub/src/emqx_bridge_azure_event_hub.erl
apps/emqx_bridge_confluent/src/emqx_bridge_confluent.app.src
apps/emqx_bridge_confluent/src/emqx_bridge_confluent_producer.erl
apps/emqx_bridge_http/src/emqx_bridge_http_schema.erl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_action_info.erl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl
apps/emqx_connector/src/emqx_connector_resource.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_resource/src/emqx_resource.app.src
apps/emqx_resource/src/schema/emqx_resource_schema.erl
changes/feat-12261.en.md
rel/i18n/emqx_bridge_iotdb.hocon
rel/i18n/emqx_bridge_iotdb_connector.hocon
scripts/spellcheck/dicts/emqx.txt

Fixes [EMQX-11460](https://emqx.atlassian.net/browse/EMQX-11460)

feat(iotdb): improve the IoTDB bridge to v2 style

---

Makefile

- The URL cannot be displayed in the webhook list page 

chore: upgrade dashboard to v1.6.1 for ce

---

Makefile
apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
apps/emqx_durable_storage/src/emqx_ds_sup.erl
apps/emqx_durable_storage/src/emqx_durable_storage.app.src
apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl
changes/e5.4.1.en.md
changes/v5.4.1.en.md

sync r54 into master

---

apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper.app.src
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper.erl
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_connector.erl
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_frame.erl
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_frame_v1.erl
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_proxy.erl
apps/emqx_bridge_syskeeper/test/emqx_bridge_syskeeper_SUITE.erl
rel/i18n/emqx_bridge_syskeeper.hocon

fix(sysk): improve the seakeeper schema

---

apps/emqx_modules/src/emqx_delayed.erl
apps/emqx_modules/src/emqx_delayed_api.erl
apps/emqx_modules/test/emqx_delayed_api_SUITE.erl
changes/ce/feat-12277.en.md
rel/i18n/emqx_delayed_api.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-11585

feat: support to delete delayed messages via topic name

---

apps/emqx_dashboard/src/emqx_dashboard.app.src
apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
apps/emqx_dashboard/test/emqx_swagger_parameter_SUITE.erl
changes/ce/feat-12278.en.md

fix(api): adjust the maximum limit of page query to 10,000

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
rel/i18n/emqx_bridge_iotdb.hocon

fix(iotdb): improve the schema for IotDB

---

.github/workflows/build_slim_packages.yaml

ci: bump ubuntu version for slim packages

---

apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper.erl
apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_proxy.erl

Fixes [EMQX-11705](https://emqx.atlassian.net/browse/EMQX-11705)

fix(sysk): fix errors of proxy schema

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_client.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_worker.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_consumer.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_producer_schema.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
changes/ee/breaking-12283.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11703

fix(gcp_pubsub_producer): fix connector `resource_opts` schema

---

apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_action_info.erl
apps/emqx_bridge_syskeeper/test/emqx_bridge_syskeeper_SUITE.erl
changes/ee/fix-12292.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11706

fix(syskeeper_bridge): mark syskeeper forwarder as a v2-only action

---

apps/emqx_gateway_coap/include/emqx_coap.hrl
apps/emqx_gateway_coap/src/emqx_coap_channel.erl
apps/emqx_gateway_coap/src/emqx_coap_message.erl
apps/emqx_gateway_coap/src/emqx_coap_pubsub_handler.erl
apps/emqx_gateway_coap/src/emqx_gateway_coap.app.src
apps/emqx_gateway_coap/test/emqx_coap_SUITE.erl
apps/emqx_gateway_coap/test/emqx_coap_message_tests.erl
changes/ce/fix-12285.en.md

see: https://github.com/emqx/emqx/issues/10089
Fixes https://emqx.atlassian.net/browse/EMQX-9144

feat(coap): support short param names

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl

Fixes [EMQX-11731](https://emqx.atlassian.net/browse/EMQX-11731)

fix(api): fix `api/v5/clients ` may crash when a client authenticate with JWT

---

apps/emqx/src/emqx_cm.erl
apps/emqx/src/emqx_connection.erl
apps/emqx/src/emqx_ws_connection.erl
apps/emqx/test/emqx_cm_SUITE.erl
apps/emqx/test/emqx_connection_conninfo_SUITE.erl
changes/ce/fix-12305.en.md

Fixes [EMQX-11729](https://emqx.atlassian.net/browse/EMQX-11729)
Release version: v/e5.4.2

fix(conn): avoid storing incomplete channel info

---

.github/workflows/build_packages_cron.yaml

ci: fix elixir version in cron build job

---

apps/emqx/priv/bpapi.versions
apps/emqx_modules/src/emqx_delayed.erl
apps/emqx_modules/src/emqx_delayed_api.erl
apps/emqx_modules/src/proto/emqx_delayed_proto_v3.erl
apps/emqx_modules/test/emqx_delayed_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11712
https://emqx.atlassian.net/browse/EMQX-11713
- ~Change log has been added to `changes/` dir …

fix(delayed): fix http 500 error

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl

[EMQX-11135](https://emqx.atlassian.net/browse/EMQX-11735)
[EMQX-11136](https://emqx.atlassian.net/browse/EMQX-11736)
[EMQX-11138](https://emqx.atlassian.net/browse/EMQX-11738)

fix(iotdb): move the iot_version into IoTDB connector

---

.github/workflows/build_packages_cron.yaml
.github/workflows/codeql.yaml
apps/emqx/include/emqx_release.hrl
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml
scripts/rel/cut.sh
scripts/rel/sync-remotes.sh

0112 prepare for release 55

---

Makefile

chore: upgrade dashboard to e1.5.0-beta.3 for ee

---

.github/workflows/build_packages_cron.yaml

Requested by QA.
Release version: v/e5.5.x

ci: run scheduled packages build of release-55

---

apps/emqx/rebar.config.script
apps/emqx/src/emqx_listeners.erl
apps/emqx/test/emqx_listeners_SUITE.erl
changes/feat-12325.en.md
mix.exs
rebar.config.erl

Fixes [EMQX-11747](https://emqx.atlassian.net/browse/EMQX-11747)
Release version: v5.5?

feat(quic): support reload with new binding port

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl

Fixes [EMQX-11742](https://emqx.atlassian.net/browse/EMQX-11742)

fix(iotdb): ensure the `data` field is `required`

---

changes/ce/feat-12329.en.md

Fixes [EMQX-11483](https://emqx.atlassian.net/browse/EMQX-11483).
Release version: v5.5
See #12237.

feat(routing): add route sync process pool

---

apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_connector.erl

Fixes [EMQX-11705](https://emqx.atlassian.net/browse/EMQX-11705)

fix(sysk): fix a update issue for the Syskeeper forwarder

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl

Fixes [EMQX-11736](https://emqx.atlassian.net/browse/EMQX-11736)

fix(iotdb): enhances type checking when converting value

---

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt.app.src
apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_msg.erl
apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_SUITE.erl
changes/ce/fix-12347.en.md

Fixes [EMQX-11757](https://emqx.atlassian.net/browse/EMQX-11757), fixes #12345 

fix(mqtt_bridge): render valid messages from incomplete rule data

---

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_ingress.erl
apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_pubsub_schema.erl
apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_subscriber_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11765

fix(mqtt_source): don't attempt local publish when legacy config is absent

---

apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/emqx_bridge_v2_api.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11767
The currently supported version for a node may not be available at the time it's probed.

fix(bridge_api): explicitly state bpapi version ranges

---

apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11717
Reduce some of the previous meaningless logs. And optimize readability. For example:
- ~If changed package build workflow, pass [this …

chore: improve http connector logs format

---

apps/emqx/src/emqx_broker.erl
apps/emqx/test/emqx_persistent_messages_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11539

fix(ds): do not count persistent session-only routed messages as dropped

---

apps/emqx_bridge_syskeeper/src/emqx_bridge_syskeeper_proxy_server.erl
apps/emqx_connector/src/emqx_connector_resource.erl
apps/emqx_resource/src/emqx_resource_manager.erl

Fixes [EMQX-11773](https://emqx.atlassian.net/browse/EMQX-11773)
[EMQX-11774](https://emqx.atlassian.net/browse/EMQX-11774)

fix(sysk): fix probe testing bugs for syskeeper

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge_opents/src/emqx_bridge_opents.app.src
apps/emqx_bridge_opents/src/emqx_bridge_opents.erl
apps/emqx_bridge_opents/src/emqx_bridge_opents_action_info.erl
apps/emqx_bridge_opents/src/emqx_bridge_opents_connector.erl
apps/emqx_bridge_opents/test/emqx_bridge_opents_SUITE.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
changes/ee/feat-12353.en.md
rel/i18n/emqx_bridge_opents.hocon
rel/i18n/emqx_bridge_opents_connector.hocon

Fixes [EMQX-11727](https://emqx.atlassian.net/browse/EMQX-11727)
[EMQX-11677](https://emqx.atlassian.net/browse/EMQX-11677)

feat(opents): improve the OpentsDB bridge to v2 style

---

.ci/docker-compose-file/docker-compose-toxiproxy.yaml
.ci/docker-compose-file/toxiproxy.json
apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge_cassandra/rebar.config
apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra.app.src
apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra.erl
apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra_action_info.erl
apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra_connector.erl
apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_SUITE.erl
apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_connector_SUITE.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
changes/ee/feat-12330.en.md
rel/i18n/emqx_bridge_cassandra.hocon
rel/i18n/emqx_bridge_cassandra_connector.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-11454

refactor: split cassandra bridges to actions and connectors

---

apps/emqx_bridge_es/src/emqx_bridge_es_connector.erl
apps/emqx_bridge_es/test/emqx_bridge_es_SUITE.erl
apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl
rel/i18n/emqx_bridge_es.hocon
rel/i18n/emqx_bridge_es_connector.hocon

chore: es's base_url to server

---

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_pubsub_schema.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11790

fix(mqtt_action): use overridden `resource_opts`

---

apps/emqx_bridge/src/emqx_bridge_v2.erl
apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11796

fix(actions_api): reset metrics on all nodes

---

Makefile

- erlfmt always try loop through files in the `--exclude-files` dir

build: direct paths to avoid wildcard traversal of the _build dir

---

apps/emqx/src/emqx_persistent_message.erl
apps/emqx/src/emqx_schema.erl

Fixes https://github.com/emqx/emqx/pull/12380

fix(ds): don't use env var for data dir default value

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl

fix(ds): Cache database metadata in RAM

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
apps/emqx/src/emqx_persistent_message.erl
apps/emqx/src/emqx_schema.erl
apps/emqx/test/emqx_persistent_messages_SUITE.erl
apps/emqx/test/emqx_persistent_session_SUITE.erl
apps/emqx_durable_storage/src/emqx_ds.erl
apps/emqx_durable_storage/src/emqx_ds_app.erl
apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
apps/emqx_durable_storage/src/emqx_ds_builtin_sup.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer.hrl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl
apps/emqx_durable_storage/src/emqx_ds_storage_layer_sup.erl
apps/emqx_durable_storage/src/emqx_ds_sup.erl
apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl

- Optimize storing of persistent messages
- Introduce a more sensible supervision tree for the builtin DB
- Add "egress" process for each shard that repackages the batches to a certain size 
Results: https://snapshots.raintank.io/dashboard/snapshot/BO51mW1MayqOrwZcBTkbaPgj0AZM0He2

feat(ds): Add egress proxies for the builtin backend

---

apps/emqx/rebar.config
apps/emqx_management/src/emqx_mgmt_cluster.erl
apps/emqx_management/test/emqx_mgmt_api_cluster_SUITE.erl
mix.exs
rebar.config

Fixes
https://emqx.atlassian.net/browse/EMQX-11809
https://emqx.atlassian.net/browse/EMQX-11810
- …

fix: upgrade ekka to 0.18.3 to ensure the leader correct

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl

Fixes [EMQX-11813](https://emqx.atlassian.net/browse/EMQX-11813)

fix(iotdb): change the `data` field to optional

---

scripts/gen-erlang-ls-config.sh

chore: update template for erlang_ls config

---

apps/emqx/rebar.config.script
apps/emqx/src/emqx_listeners.erl
changes/feat-12388.en.md
mix.exs
rebar.config.erl

feat: quic per listener conn count

---

apps/emqx_prometheus/src/emqx_prometheus.erl

Fixes [EMQX-11814](https://emqx.atlassian.net/browse/EMQX-11814)

fix(prom_stats): merge cl_consistented data into per nodes data

---

apps/emqx/rebar.config
mix.exs
rebar.config

Don't escalate the errors in etcd node discovery to the node level.
Fixes: #12255

chore(ekka): Bump version to 0.18.4

---

apps/emqx_prometheus/src/emqx_prometheus.erl

fix(prom_stats): compatibility with previous api format in json mode

---

apps/emqx_durable_storage/README.md

doc(ds): Update README

---

apps/emqx_bridge_cassandra/rebar.config
apps/emqx_bridge_cassandra/src/emqx_bridge_cassandra_connector.erl
apps/emqx_bridge_cassandra/test/emqx_bridge_cassandra_SUITE.erl
changes/ee/fix-12411.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11822

fix(cassandra_bridge): correctly insert null values into columns

---

apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl
apps/emqx_auth/src/emqx_authn/emqx_authn_provider.erl
apps/emqx_auth/src/emqx_authn/emqx_authn_user_import_api.erl
apps/emqx_auth/test/data/user-credentials-plain.csv
apps/emqx_auth/test/data/user-credentials-plain.json
apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src
apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl
apps/emqx_auth_mnesia/test/emqx_authn_api_mnesia_SUITE.erl
apps/emqx_auth_mnesia/test/emqx_authn_mnesia_SUITE.erl
apps/emqx_gateway/src/emqx_gateway_api_authn_user_import.erl
apps/emqx_utils/src/emqx_utils_stream.erl
apps/emqx_utils/test/emqx_utils_stream_tests.erl
changes/ce/feat-12396.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11768

feat(import_users): support user's password in plain text

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
apps/emqx/src/emqx_channel.erl
apps/emqx/src/emqx_message.erl
apps/emqx/src/emqx_schema.erl
apps/emqx/src/emqx_session_mem.erl
apps/emqx/test/emqx_config_SUITE.erl
apps/emqx/test/emqx_message_SUITE.erl
apps/emqx/test/emqx_session_mem_SUITE.erl
changes/ee/feat-12417.md
rel/config/examples/mqtt.conf.example
rel/i18n/emqx_schema.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-10972
port https://github.com/emqx/emqx-enterprise/pull/1888 from 4.4.x
Release version: e5.6.0?

feat: configurable server side message_expiry_interval

---

apps/emqx_auth/src/emqx_authn/emqx_authn_user_import_api.erl
apps/emqx_auth/test/data/user-credentials-plain-dup.csv
apps/emqx_auth/test/data/user-credentials-plain-dup.json
apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl
apps/emqx_auth_mnesia/test/emqx_authn_mnesia_SUITE.erl
apps/emqx_management/src/emqx_mgmt_api_cluster.erl

- ~Change log has been added to `changes/` dir for user-facing …

fix(user_import): ensure the last record overwrites previous one

---

apps/emqx_bridge_opents/src/emqx_bridge_opents.erl
apps/emqx_bridge_opents/src/emqx_bridge_opents_connector.erl
apps/emqx_bridge_opents/test/emqx_bridge_opents_SUITE.erl
rel/i18n/emqx_bridge_opents.hocon

feat(opentsdb): supports more flexible tags schema

---

Makefile

chore(dashboard): bump dashboard version to v1.7.0 & e1.5.0

---

apps/emqx/src/emqx_persistent_session_ds_stream_scheduler.erl

fix(sessds): Stream scheduler must ignore fully replayed streams

---

apps/emqx_auth/src/emqx_authn/emqx_authn_user_import_api.erl
apps/emqx_auth_mnesia/test/emqx_authn_api_mnesia_SUITE.erl

chore: compatible the contet-type sytanx

---

apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.erl

This PR fixes problems in schema found by @HJianBo here:
https://github.com/emqx/emqx/pull/12376#pullrequestreview-1848306286

fix: kinesis schema problems found by @HJianBo

---

apps/emqx_dashboard/src/emqx_dashboard.erl
apps/emqx_dashboard/src/emqx_dashboard_listener.erl
apps/emqx_dashboard/src/emqx_dashboard_schema.erl
apps/emqx_dashboard/test/emqx_dashboard_SUITE.erl
changes/ce/feat-12398.en.md
rel/i18n/emqx_dashboard_schema.hocon

feat(dashboard): expose the `swagger_support` option

---

apps/emqx_machine/src/emqx_machine_boot.erl
apps/emqx_machine/src/emqx_machine_boot_runtime_deps.erl

This small refactoring is a part of a private development branch; it allows loosely depending on apps that may not present in the current branch/profile.

chore(emqx_machine): refactor injecting runtime deps

---

apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.erl

fix(swagger): no-need call common_fields when `emqx_connector_schema:api_fields/3` used

---

apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.erl

Follow up #12455 
See also: https://github.com/emqx/emqx/actions/runs/7751017718/job/21138732922#step:6:2821

test: fix emqx_connector_schema eunit missing fields

---

apps/emqx_bridge_opents/src/emqx_bridge_opents.erl
apps/emqx_bridge_opents/src/emqx_bridge_opents_connector.erl
apps/emqx_bridge_opents/test/emqx_bridge_opents_SUITE.erl
rel/i18n/emqx_bridge_opents.hocon

fix(opents): change the schema of tags to object style

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge_opents/src/emqx_bridge_opents_connector.erl
apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine.app.src
apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine.erl
apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_action_info.erl
apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector.erl
apps/emqx_bridge_tdengine/test/emqx_bridge_tdengine_SUITE.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
changes/ee/feat-12449.en.md
rel/i18n/emqx_bridge_tdengine.hocon
rel/i18n/emqx_bridge_tdengine_connector.hocon

Fixes [EMQX-11470](https://emqx.atlassian.net/browse/EMQX-11470)

feat(tdengine): improve the TDengine bridge to v2 style

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge_oracle/src/emqx_bridge_oracle.app.src
apps/emqx_bridge_oracle/src/emqx_bridge_oracle.erl
apps/emqx_bridge_oracle/src/emqx_bridge_oracle_action_info.erl
apps/emqx_bridge_oracle/test/emqx_bridge_oracle_SUITE.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_oracle/src/emqx_oracle.app.src
apps/emqx_oracle/src/emqx_oracle.erl
changes/ee/feat-12439.en.md
rel/i18n/emqx_bridge_oracle.hocon

Fixes:
https://emqx.atlassian.net/browse/EMQX-11464

feat: refactor Oracle bridge to connector and action

---

apps/emqx_bridge_oracle/src/emqx_bridge_oracle.erl

fix(schema): bridge oracle connector schema

---

apps/emqx_dashboard/src/emqx_dashboard_swagger.erl

Fllow up https://github.com/emqx/emqx/pull/12477.

chore: add duplicated key assert in swagger.json

---

bin/emqx
bin/nodetool

fix(bin/emqx): maxium file descriptors 65536 for remote_console

---

apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector.erl

fix(tdengine): keep the bridge schema still compatible with v1

---

apps/emqx/src/emqx_config.erl
apps/emqx_bridge/test/emqx_bridge_v1_compatibility_layer_SUITE.erl
changes/ce/fix-12471.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11845
Fixes https://github.com/emqx/emqx/issues/12452

fix(config): apply config upgrade to deprecated configs

---

apps/emqx/src/emqx_persistent_session_ds_inflight.erl
apps/emqx_durable_storage/src/emqx_ds_bitmask.hrl
apps/emqx_durable_storage/src/emqx_ds_bitmask_keymapper.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11827
This PR reduces the CPU load introduced by persistent session idle-polling.

Optimize emqx_ds_bitmask_keymapper:make_filter function.

---

.ci/docker-compose-file/docker-compose-rabbitmq.yaml
apps/emqx/test/emqx_common_test_helpers.erl
apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/emqx_bridge_app.erl
apps/emqx_bridge_rabbitmq/rebar.config
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq.app.src
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_action_info.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_app.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_connector.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_connector_schema.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_pubsub_schema.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_source_sup.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_source_worker.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_sup.erl
apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_SUITE.erl
apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_connector_SUITE.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
bin/emqx
build
changes/ee/feat-12423.en.md
mix.exs
rebar.config
rel/i18n/emqx_bridge_rabbitmq_connector_schema.hocon
rel/i18n/emqx_bridge_rabbitmq_pubsub_schema.hocon

feat: rabbitmq bridge v2 integration

---

apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_action_info.erl

fix(tdengine): remove redundant codes

---

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_azure_event_hub/test/emqx_bridge_azure_event_hub_v2_SUITE.erl
apps/emqx_bridge_confluent/test/emqx_bridge_confluent_producer_SUITE.erl
apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl
apps/emqx_bridge_mongodb/test/emqx_bridge_v2_mongodb_SUITE.erl
apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl
apps/emqx_bridge_redis/test/emqx_bridge_v2_redis_SUITE.erl

test(bridge_v2): actually check schema

---

apps/emqx_mongodb/rebar.config
apps/emqx_mongodb/src/emqx_mongodb.erl
changes/ee/perf-12494.en.md

Fixes  EMQX-11825
Release version: e5.5.1

Improve mongodb connector performance

---

apps/emqx_bridge_azure_event_hub/rebar.config
apps/emqx_bridge_confluent/rebar.config
apps/emqx_bridge_kafka/rebar.config
changes/ce/fix-12505.en.md
mix.exs

Release version: `e5.6.0`
Wolff 1.10.2 added an enhancement which makes Kafka resource health checks more lightweight and lowers the chance of false resource alerts.
Wolff PR: https://github.com/kafka4beam/wolff/pull/61

chore: upgrade to wolff 1.10.2

---

apps/emqx/include/emqx.hrl
apps/emqx/src/emqx_banned.erl
apps/emqx/src/emqx_flapping.erl
apps/emqx/src/emqx_types.erl
apps/emqx/test/emqx_banned_SUITE.erl
apps/emqx_auth/test/emqx_authz/emqx_authz_SUITE.erl
apps/emqx_management/src/emqx_mgmt_api.erl
apps/emqx_management/src/emqx_mgmt_api_banned.erl
apps/emqx_management/test/emqx_mgmt_api_banned_SUITE.erl
apps/emqx_modules/test/emqx_delayed_SUITE.erl
apps/emqx_retainer/test/emqx_retainer_SUITE.erl
changes/ce/feat-12499.en.md
rel/i18n/emqx_mgmt_api_banned.hocon

Fixes [EMQX-11786](https://emqx.atlassian.net/browse/EMQX-11786), [EMQX-11769](https://emqx.atlassian.net/browse/EMQX-11769)

feat(banned): allow ban by clientid/username regexps, peerhost cidrs

---

apps/emqx_bridge_s3/src/emqx_bridge_s3_connector.erl
apps/emqx_bridge_s3/test/emqx_bridge_s3_SUITE.erl

Fixes [EMQX-11830](https://emqx.atlassian.net/browse/EMQX-11830).

fix(s3-bridge): handle recoverable AWS errors

---

apps/emqx_auth/include/emqx_authz.hrl
apps/emqx_auth/src/emqx_authn/emqx_authn_api.erl
apps/emqx_auth/src/emqx_authn/emqx_authn_config.erl
apps/emqx_auth/src/emqx_authz/emqx_authz.erl
apps/emqx_auth/src/emqx_authz/emqx_authz_api_sources.erl
apps/emqx_auth/test/emqx_authn/emqx_authn_api_SUITE.erl
apps/emqx_auth/test/emqx_authz/emqx_authz_api_sources_SUITE.erl
changes/ce/feat-12509.en.md
rel/i18n/emqx_authn_api.hocon
rel/i18n/emqx_authz_api_sources.hocon

feat(emqx_auth): implement API to re-order all authenticators/authz sources

---

.github/actions/prepare-jmeter/action.yaml
.github/workflows/_pr_entrypoint.yaml
.github/workflows/_push-entrypoint.yaml
.github/workflows/build_docker_for_test.yaml
.github/workflows/build_packages.yaml
.github/workflows/build_packages_cron.yaml
.github/workflows/build_slim_packages.yaml
.github/workflows/check_deps_integrity.yaml
.github/workflows/performance_test.yaml
.github/workflows/release.yaml
.github/workflows/run_conf_tests.yaml
.github/workflows/run_docker_tests.yaml
.github/workflows/run_emqx_app_tests.yaml
.github/workflows/run_helm_tests.yaml
.github/workflows/run_jmeter_tests.yaml
.github/workflows/run_relup_tests.yaml
.github/workflows/run_test_cases.yaml
.github/workflows/scorecard.yaml
.github/workflows/spellcheck.yaml
.github/workflows/static_checks.yaml
.github/workflows/upload-helm-charts.yaml
scripts/buildx.sh

Also switch back to using buidlx.sh in build_packages to be able to use NodeJS 20 actions there.
Release version: v/e5.5.*

bump actions versions

---

apps/emqx_bridge_azure_event_hub/rebar.config
apps/emqx_bridge_confluent/rebar.config
apps/emqx_bridge_kafka/rebar.config
changes/ee/fix-12522.en.md
mix.exs

chore: upgrade kafka_protocol from 4.1.3 to 4.1.5

---

apps/emqx_bridge_mqtt/test/emqx_bridge_mqtt_v2_subscriber_SUITE.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl

test(bridge_mqtt): Stop snabbkaffe servers

---

apps/emqx/test/emqx_listeners_SUITE.erl

- Reduce the `eaddrinuse` flakiness
- Use ?FUNCTION_NAME as listener name to avoid name clashing between tests
- Call emqx:remove_config for adhoc listeners created for testing tombestone is designed for default listeners
Release version: `v5.6.0`

test(listeners): try to stop all listeners after each test

---

apps/emqx_auth/src/emqx_authz/emqx_authz_schema.erl
apps/emqx_auth/test/emqx_authz/emqx_authz_SUITE.erl
apps/emqx_prometheus/src/emqx_prometheus_api.erl
apps/emqx_prometheus/test/emqx_prometheus_SUITE.erl
apps/emqx_prometheus/test/emqx_prometheus_api_SUITE.erl
apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl
scripts/pre-compile.sh

Fixes [EMQX-11784](https://emqx.atlassian.net/browse/EMQX-11784) …

Prom api test cases

---

Makefile

chore: upgrade dashboard to e1.5.1-s3-beta.1 for ee

---

apps/emqx_bridge_http/src/emqx_bridge_http.app.src
apps/emqx_bridge_http/src/emqx_bridge_http_schema.erl
rel/i18n/emqx_audit_api.hocon
rel/i18n/emqx_authn_ldap_schema.hocon
rel/i18n/emqx_auto_subscribe_schema.hocon
rel/i18n/emqx_bridge_azure_event_hub.hocon
rel/i18n/emqx_bridge_confluent_producer.hocon
rel/i18n/emqx_bridge_es.hocon
rel/i18n/emqx_bridge_gcp_pubsub.hocon
rel/i18n/emqx_bridge_greptimedb.hocon
rel/i18n/emqx_bridge_hstreamdb.hocon
rel/i18n/emqx_bridge_hstreamdb_connector.hocon
rel/i18n/emqx_bridge_http_connector.hocon
rel/i18n/emqx_bridge_http_schema.hocon
rel/i18n/emqx_bridge_iotdb.hocon
rel/i18n/emqx_bridge_kafka.hocon
rel/i18n/emqx_bridge_kinesis.hocon
rel/i18n/emqx_bridge_mongodb.hocon
rel/i18n/emqx_bridge_mqtt_schema.hocon
rel/i18n/emqx_bridge_mysql.hocon
rel/i18n/emqx_bridge_pulsar.hocon
rel/i18n/emqx_bridge_redis.hocon
rel/i18n/emqx_bridge_syskeeper.hocon
rel/i18n/emqx_bridge_syskeeper_proxy.hocon
rel/i18n/emqx_schema.hocon

Release version: `v/e5.5.1`
This is an attempt to sync the changes made in  https://github.com/emqx/emqx-i18n/tree/v55
Also tried to fix some doc bug found during this process.
* HStreamDB -> MySQL (copy-paste error)
* Bridge -> Action

docs: fix i18n

---

apps/emqx/src/emqx_tls_certfile_gc.erl

chore(emqx_tls_certfile_gc): fix typo

---

apps/emqx/priv/bpapi.versions
apps/emqx_bridge/test/emqx_bridge_v1_compatibility_layer_SUITE.erl
apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_producer_SUITE.erl
apps/emqx_dashboard/test/emqx_swagger_response_SUITE.erl
apps/emqx_resource/src/emqx_resource.erl
apps/emqx_resource/src/proto/emqx_resource_proto_v1.erl
apps/emqx_resource/src/proto/emqx_resource_proto_v2.erl
apps/emqx_resource/test/emqx_resource_SUITE.erl

0220 delete non prod code in emqx_resource.erl

---

apps/emqx/include/emqx_release.hrl
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml

chore: bump version to 5.5.1-rc.1

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub.app.src
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_connector.erl
apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11884 and https://emqx.atlassian.net/browse/EMQX-11885

Fix rabbitmq source metrics

---

apps/emqx/src/emqx_persistent_session_ds_state.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl

Follow up to https://github.com/emqx/emqx/pull/12500#discussion_r1496634087

refactor(mgmt): move persistent session counting function to mgmt module

---

apps/emqx/include/logger.hrl
apps/emqx/src/emqx_log_throttler.erl
apps/emqx/test/emqx_log_throttler_SUITE.erl
rel/i18n/emqx_conf_schema.hocon

fix: disable log throttling if primary log level is debug

---

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_action_info.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_consumer_worker.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_consumer_SUITE.erl
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.app.src
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb_action_info.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11891
Fixes https://emqx.atlassian.net/browse/EMQX-11893

fix(gcp_pubsub_consumer,mongodb_bridge): fix v1 config transformation for gcp pubsub consumer and mongodb bridges

---

apps/emqx_auth_http/src/emqx_auth_http.app.src
apps/emqx_auth_http/src/emqx_authz_http.erl
apps/emqx_bridge_mongodb/src/emqx_bridge_mongodb.erl
apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl

1. Check rocketmq's channel status.
2. [hidden batch_time for mongodb](https://github.com/emqx/emqx/commit/9639a977a3ab2a93e7bb40e0da0ab9537582335f)

fix: Rocketmq channel status

---

apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_connector.erl
apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11889

fix: rabbitmq action failed to increase dropped metrics

---

Makefile

chore: upgrade dashboard to e1.5.1-s3 for ee

---

apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_consumer_SUITE.erl
apps/emqx_bridge_http/test/emqx_bridge_http_SUITE.erl
apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
apps/emqx_bridge_mongodb/test/emqx_bridge_mongodb_SUITE.erl
apps/emqx_bridge_oracle/test/emqx_bridge_oracle_SUITE.erl

test(bridge_v1): delete repeat probe_bridge_api code

---

apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
apps/emqx_connector/src/emqx_connector.app.src
apps/emqx_connector/src/emqx_connector_resource.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11895

fix(connectors): redact authorization headers when creating/updating connectors

---

apps/emqx_bridge/src/schema/emqx_bridge_schema.erl
apps/emqx_dashboard/src/emqx_dashboard_schema_api.erl
changes/ce/breaking-12576.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11899

docs: stop generating schema doc for 'bridges' root

---

apps/emqx/include/logger.hrl
apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
changes/ce/feat-12520.en.md

trace throttled events

---

apps/emqx/include/logger.hrl
apps/emqx/src/emqx_logger_jsonfmt.erl
apps/emqx/src/emqx_logger_textfmt.erl
apps/emqx_utils/src/emqx_utils.erl
changes/ce/feat-12590.en.md

Partially fixes https://emqx.atlassian.net/browse/EMQX-11907
Deleted mfa from log metadata.

refactor: delete mfa from log metadata

---

apps/emqx_ldap/src/emqx_ldap.app.src
apps/emqx_ldap/src/emqx_ldap.erl

fix(ldap): fix that logs of eldap will never be logged

---

apps/emqx/src/emqx_topic.erl
apps/emqx_management/src/emqx_management.app.src
apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
changes/ce/fix-12598.en.md

Fixes [EMQX-11912](https://emqx.atlassian.net/browse/EMQX-11912)

fix(mgmt): sub/unsub a share subscription to the client via http api

---

apps/emqx_ldap/src/emqx_ldap.app.src
apps/emqx_ldap/src/emqx_ldap.erl
changes/ce/fix-12601.en.md

cherry-pick from master
Release version: `v/e5.5.1`

 fix(ldap): fix that logs of eldap will never be logged

---

apps/emqx_bridge/src/emqx_bridge.erl
apps/emqx_bridge/src/emqx_bridge_v2.erl
apps/emqx_resource/include/emqx_resource.hrl
apps/emqx_resource/src/emqx_resource.erl

Previously, using the wrong schema never returned an error.
cherry pick from https://github.com/emqx/emqx/pull/12540, to make PR smaller is better for review.
this change cover by https://github.com/emqx/emqx/pull/12540 's test case.

Fix bridge v2 and connector schema check

---

apps/emqx_bridge_hstreamdb/include/emqx_bridge_hstreamdb.hrl
apps/emqx_bridge_hstreamdb/src/emqx_bridge_hstreamdb.erl
apps/emqx_bridge_hstreamdb/src/emqx_bridge_hstreamdb_connector.erl

fix: get grpc_timeout from hstreamdb connector config failed

---

apps/emqx_management/src/emqx_mgmt_api.erl
apps/emqx_management/src/emqx_mgmt_api_topics.erl
apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl

Avoid doing full scans over router tables.

fix(api-topics): avoid doing full scans over router tables

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl
changes/ee/fix-12608.en.md

Fixes [EMQX-11918](https://emqx.atlassian.net/browse/EMQX-11918)

fix(iotdb): fix function clause error when there is no `payload` field

---

apps/emqx/etc/emqx.conf
apps/emqx_conf/src/emqx_conf_schema.erl
bin/emqx
mix.exs
rebar.config.erl
rel/i18n/emqx_conf_schema.hocon
scripts/spellcheck/dicts/emqx.txt

Fixes https://emqx.atlassian.net/browse/EMQX-11907
2/N of logging refactoring.
This hopefully makes logging configs less confusing.

docs: add log docs

---

apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
changes/ee/feat-12602.en.md

Fixes [EMQX-11741](https://emqx.atlassian.net/browse/EMQX-11741)

fix(iotdb): use the `ping` API to check the status of the IOTDB connections

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_bridge/src/emqx_bridge_v2.erl
apps/emqx_bridge/src/schema/emqx_bridge_enterprise.erl
apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector_schema.erl
apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_pubsub_schema.erl
apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.app.src
apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar.erl
apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_action_info.erl
apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector.erl
apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_connector_schema.erl
apps/emqx_bridge_pulsar/src/emqx_bridge_pulsar_pubsub_schema.erl
apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_connector_SUITE.erl
apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl
apps/emqx_bridge_rabbitmq/src/emqx_bridge_rabbitmq_pubsub_schema.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
rel/i18n/emqx_bridge_pulsar.hocon
rel/i18n/emqx_bridge_pulsar_pubsub_schema.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-11465

feat: pulsar bridge v2

---

apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge/src/emqx_bridge_v2.erl
apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka.app.src
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_action_info.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_schema.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl
apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl
apps/emqx_connector/src/emqx_connector_resource.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_connector/test/emqx_connector_SUITE.erl
changes/ee/feat-12595.en.md
rel/i18n/emqx_bridge_kafka_consumer_schema.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-11848

feat: migrate kafka consumer bridge to source + connector

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
apps/emqx_gateway_ocpp/rebar.config
apps/emqx_schema_registry/include/emqx_schema_registry.hrl
apps/emqx_schema_registry/rebar.config
apps/emqx_schema_registry/src/emqx_schema_registry.app.src
apps/emqx_schema_registry/src/emqx_schema_registry.erl
apps/emqx_schema_registry/src/emqx_schema_registry_schema.erl
apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl
apps/emqx_schema_registry/test/emqx_schema_registry_SUITE.erl
apps/emqx_schema_registry/test/emqx_schema_registry_http_api_SUITE.erl
apps/emqx_schema_registry/test/emqx_schema_registry_serde_SUITE.erl
changes/ee/feat-12581.en.md
rebar.config.erl
rel/i18n/emqx_schema_registry_schema.hocon
scripts/spellcheck/dicts/emqx.txt

Fixes https://emqx.atlassian.net/browse/EMQX-11881

feat: schema registry supports json schema

---

Makefile

chore: upgrade dashboard to e1.6.0-beta.1 for ee

---

apps/emqx_retainer/test/emqx_retainer_SUITE.erl

Part of https://emqx.atlassian.net/browse/EMQX-11922

test(retainer): extend test suite for usage by other backends

---

apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
apps/emqx_utils/src/emqx_utils_redact.erl

Fixes [EMQX-11856](https://emqx.atlassian.net/browse/EMQX-11856)

fix(http): fix that sensitive headers may be printed in log when querying

---

.github/workflows/build_and_push_docker_images.yaml
apps/emqx/include/emqx_release.hrl
build
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml

At the present, `public.ecr.aws/emqx/emqx-enterprise` does not exist.

fix docker repository enumeration and prepare `e5.6.0-alpha.2`

---

apps/emqx_conf/src/emqx_conf_schema.erl

fix(emqx_conf_schema): use `timeout_duration_s()` type for `log.throttling.time_window`

---

Makefile

- New Actions
- RabbitMQ
- GreptimeDB
- Kinesis
- TDengine
- Oracle
- OpenTSDB
- Cassandra
- RabbitMQ
- ClickHouse
- RocketMQ
- S3
- HStream
- DynamoDB
- Pulsar
- SQL Server
- New Sources
- GCP Consumer
- Kafka Consumer
- RabbitMQ
- Client
- Details page supports refreshing subscription list
- Details page supports viewing message queues and flight window message lists
- Rules
- Rules support JSON Schema message validation
- Test results are displayed directly in JSON
- Authentication import supports importing plain text passwords
- Optimized listener configuration, supports custom configuration
- Banned client supports pattern matching
- Log throttling configuration supported
- Quick search supported
- Page layout optimized
Please convert it to a draft if any of the following conditions …

chore: upgrade dashboard to e1.6.0-beta.2 for ee

---

.github/workflows/build_and_push_docker_images.yaml
.github/workflows/build_packages.yaml
apps/emqx/include/emqx_release.hrl
build
changes/e5.5.1.en.md
changes/v5.5.1.en.md
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml

- backport https://github.com/emqx/emqx/pull/12645
- backport https://github.com/emqx/emqx/pull/12644
- remove changelog entry for #12542 since #12620 is a more general fix for the same issue

prep 5.5.1 rc.3

---

.github/workflows/_pr_entrypoint.yaml
.github/workflows/_push-entrypoint.yaml
.github/workflows/build_and_push_docker_images.yaml
.github/workflows/build_docker_for_test.yaml
.github/workflows/build_packages.yaml
.github/workflows/run_docker_tests.yaml
apps/emqx/include/emqx_release.hrl
build
changes/e5.5.1.en.md
changes/v5.5.1.en.md
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml
deploy/docker/Dockerfile
deploy/docker/docker-entrypoint.sh
scripts/ui-tests/docker-compose.yaml

prep 5.5.1 rc.4

---

apps/emqx_durable_storage/src/emqx_ds.erl

This typespec fix will be used downstream by other backends.

fix(ds): fix `drop_generation` typespec

---

.github/workflows/build_and_push_docker_images.yaml
.github/workflows/build_packages.yaml
Makefile
apps/emqx/include/emqx_release.hrl
apps/emqx/rebar.config
apps/emqx_bridge/src/emqx_action_info.erl
apps/emqx_bridge_http/src/emqx_bridge_http_connector.erl
apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver.app.src
apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver.erl
apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_action_info.erl
apps/emqx_bridge_sqlserver/src/emqx_bridge_sqlserver_connector.erl
apps/emqx_bridge_sqlserver/test/emqx_bridge_sqlserver_SUITE.erl
apps/emqx_connector/src/schema/emqx_connector_ee_schema.erl
apps/emqx_connector/src/schema/emqx_connector_schema.erl
apps/emqx_management/src/emqx_mgmt_auth.erl
apps/emqx_resource/src/emqx_resource.erl
apps/emqx_utils/src/emqx_utils_redact.erl
build
changes/ce/breaking-12634.en.md
changes/ce/feat-12517.en.md
changes/e5.5.1.en.md
changes/ee/feat-12619.en.md
changes/v5.5.1.en.md
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml
mix.exs
rebar.config
rel/i18n/emqx_bridge_sqlserver.hocon

sync `release-56` to `master`

---

.ci/docker-compose-file/docker-compose-elastic-search-tls.yaml
apps/emqx_bridge_es/test/emqx_bridge_es_SUITE.erl

test(elastic_search): fix flaky test

---

apps/emqx_retainer/README.md

Fixes [EMQX-9230](https://emqx.atlassian.net/browse/EMQX-9230)

chore(retainer): actualize README

---

apps/emqx/src/emqx_cm.erl
apps/emqx/test/emqx_broker_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11933

test(emqx_broker_SUITE): fix flaky test case

---

.ci/docker-compose-file/docker-compose-elastic-search-tls.yaml
apps/emqx_bridge_es/test/emqx_bridge_es_SUITE.erl

test(elastic_search): fix flaky test (r56)

---

apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_client.erl
apps/emqx_bridge_gcp_pubsub/src/emqx_bridge_gcp_pubsub_impl_producer.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_gcp_pubsub_producer_SUITE.erl
apps/emqx_bridge_gcp_pubsub/test/emqx_bridge_v2_gcp_pubsub_producer_SUITE.erl
changes/ee/fix-12656.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11949

fix(gcp_pubsub_producer): check for topic existence when creating action

---

apps/emqx_bridge_pulsar/test/emqx_bridge_pulsar_v2_SUITE.erl

test(pulsar): fix flaky test

---

apps/emqx_durable_storage/src/emqx_ds.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl
apps/emqx_durable_storage/src/emqx_ds_storage_bitfield_lts.erl
apps/emqx_durable_storage/src/emqx_ds_storage_reference.erl
apps/emqx_durable_storage/test/emqx_ds_SUITE.erl
apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl

Part of https://emqx.atlassian.net/browse/EMQX-11841

feat(ds): add atomic store API

---

.github/workflows/build_and_push_docker_images.yaml
apps/emqx/src/emqx.app.src
apps/emqx/src/emqx_connection.erl
apps/emqx/src/emqx_logger_textfmt.erl
apps/emqx/src/emqx_ws_connection.erl
apps/emqx_bridge_http/src/emqx_bridge_http.app.src
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.app.src
apps/emqx_connector/src/emqx_connector.app.src
apps/emqx_management/src/emqx_management.app.src
apps/emqx_prometheus/src/emqx_prometheus.app.src
apps/emqx_rule_engine/test/emqx_rule_funcs_SUITE.erl
apps/emqx_utils/src/emqx_utils.app.src
apps/emqx_utils/src/emqx_utils_calendar.erl
build
changes/ce/feat-12641.en.md
changes/ce/fix-12646.en.md
changes/e5.5.1.en.md
changes/v5.5.1.en.md
scripts/git-hook-pre-commit.sh

merge both release-55 and release-56 to master.

Sync 5.5.1

---

apps/emqx_machine/test/emqx_machine_SUITE.erl

test(machine): attempt to stabilize flaky test

---

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_consumer.erl
apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl
apps/emqx_bridge_kafka/test/emqx_bridge_v2_kafka_consumer_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11945
- [na] ~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~ Kafka Consumer refactoring is not released yet

fix(kafka_consumer): check client connectivity

---

apps/emqx_conf/test/emqx_conf_app_SUITE.erl

Before the recent changes these testcases relied on the fact that peer nodes that are part of the test cluster are started one after the other. This is now not the case in general with `emqx_cth_cluster`, so now we need to additionally find the "longest running node" in the cluster before running test logic.

test(conf): fix flaky config sync testcases

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

fix(emqx_mgmt_api_clients): check that max_payload_bytes is higher than 0

---

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl

test: trigger hocon validators when checking schema

---

apps/emqx_bridge_tdengine/src/emqx_bridge_tdengine_connector.erl

Fixes [EMQX-11993](https://emqx.atlassian.net/browse/EMQX-11993)

fix(tdengine): enhanced health check result, make it more sense

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl

Fixes E[MQX-11988](https://emqx.atlassian.net/browse/EMQX-11988)

fix(iotdb): Fix function_clause when the convert value is null

---

apps/emqx_ldap/src/emqx_ldap.app.src
apps/emqx_ldap/src/emqx_ldap.erl

Fixes [EMQX-11986](https://emqx.atlassian.net/browse/EMQX-11986)

fix(ldap): lower the log level of LDAB to `debug`

---

apps/emqx_bridge_opents/src/emqx_bridge_opents_connector.erl

Fixes [EMQX-11964](https://emqx.atlassian.net/browse/EMQX-11964)

perf(opents): Improve the message processing efficiency of opentsdb

---

apps/emqx_conf/test/emqx_conf_app_SUITE.erl
bin/emqx
bin/nodetool
changes/ce/fix-12672.en.md

Release: v/e5.6.0
* Delete obsolete code
* Add a missing change log for PR #12672 
* Port a flaky test fix to `release-56`

0308 minor refactors

---

apps/emqx_bridge_kafka/src/emqx_bridge_kafka.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_consumer_schema.erl
apps/emqx_bridge_kafka/test/emqx_bridge_kafka_impl_consumer_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12008

fix(kafka_consumer): validate topic mapping in v2 schema

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl

fix(ds): use `infinity` timeout when storing batches

---

apps/emqx_durable_storage/test/emqx_ds_storage_bitfield_lts_SUITE.erl

test(ds): rm unused var warning

---

Makefile

- Support specifying language in query
ECP needs to debug this feature, so it needs to be updated to EMQX

chore: upgrade dashboard to e1.6.0-beta.5 for ee

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl

Fixes 1/2 [EMQX-11956](https://emqx.atlassian.net/browse/EMQX-11956)

fix(api/clients): drop expired sessions from durable storage

---

apps/emqx/priv/bpapi.versions
apps/emqx_management/src/emqx_mgmt.erl
apps/emqx_management/src/emqx_mgmt_api_configs.erl
apps/emqx_management/src/emqx_mgmt_api_listeners.erl
apps/emqx_management/src/proto/emqx_management_proto_v5.erl
apps/emqx_management/test/emqx_mgmt_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_configs_SUITE.erl

Refactor emqx mgmt call client

---

.github/workflows/build_and_push_docker_images.yaml
Makefile
build
changes/ce/feat-12679.en.md
deploy/docker/Dockerfile
deploy/docker/Dockerfile.msodbc
mix.exs
rebar.config
scripts/buildx.sh

Fixes [EMQX-11981](https://emqx.atlassian.net/browse/EMQX-11981).
Related PRs:
- https://github.com/emqx/erlang-bcrypt/pull/6

chore: switch default docker base to debian 12

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_persistent_session_ds.hrl
apps/emqx/src/emqx_persistent_session_ds_state.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl
changes/ce/fix-12707.en.md

Store peer name in the durable session metadata.

---

.gitignore
apps/emqx/src/emqx_shared_sub.erl
apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
apps/emqx_prometheus/src/emqx_prometheus.erl
apps/emqx_prometheus/src/emqx_prometheus_cluster.erl
apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl
changes/ce/fix-12714.en.md

0315 Fix `shared_subscriptions` counting error. followup #12670

---

apps/emqx_bridge/src/emqx_bridge_v2_api.erl
rel/i18n/emqx_bridge_v2_api.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-12037
- ~Change log …

Support to return the supported source types via `GET /source_types` endpoint

---

.github/workflows/build_and_push_docker_images.yaml
deploy/docker/Dockerfile

`chown` only mutable state directories

build(docker): optimize docker image layers

---

apps/emqx_bridge_rabbitmq/test/emqx_bridge_rabbitmq_v2_SUITE.erl
apps/emqx_conf/src/emqx_conf_cli.erl
apps/emqx_connector/src/emqx_connector.erl
changes/ce/fix-12715.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12016 and https://emqx.atlassian.net/browse/EMQX-12019

fix: cant replace source conf

---

apps/emqx_management/src/emqx_mgmt_api_banned.erl

Fixes https://emqx.atlassian.net/browse/EMQX-11936

fix: don't crash when ban ip error

---

rel/i18n/emqx_bridge_azure_event_hub.hocon
rel/i18n/emqx_bridge_confluent_producer.hocon
rel/i18n/emqx_bridge_kafka.hocon

docs: there is no need to escape quotes in triple-quotes

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl

test(ds): stabilize `t_session_replay_retry` testcase

---

apps/emqx/src/emqx_persistent_session_ds/emqx_ps_ds_int.hrl
apps/emqx/src/emqx_persistent_session_ds_router.erl
apps/emqx/src/emqx_router.erl
apps/emqx_management/src/emqx_mgmt_api_topics.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl

Fixes [EMQX-12038](https://emqx.atlassian.net/browse/EMQX-12038).

fix(api-topics): expose persistent session topics in APIs

---

apps/emqx_opentelemetry/src/emqx_otel_config.erl
apps/emqx_opentelemetry/src/emqx_otel_cpu_sup.erl
apps/emqx_opentelemetry/src/emqx_otel_metrics.erl
apps/emqx_opentelemetry/src/emqx_otel_sup.erl

Fixes [https://emqx.atlassian.net/browse/EMQX-12046](https://emqx.atlassian.net/browse/EMQX-12046)
followup #12663 (no change log )
- ~[ ] Change log has been added to `changes/` dir for user-facing …

fix(otel): cpu usage/idle metrics for opentelemetry

---

apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx_management/src/emqx_mgmt.erl

fix(mgmt): Fix bulk kickout of durable sessions

---

apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12049

fix(kafka-based bridges): avoid trying to get raw config for replayq dir

---

Makefile

chore(dashboard): bump dashboard version to v1.8.0 & e1.6.0

---

apps/emqx/integration_test/emqx_persistent_session_ds_SUITE.erl

test: attempt to stabilize flaky test

---

apps/emqx_management/src/emqx_mgmt_data_backup.erl
apps/emqx_management/test/emqx_mgmt_api_data_backup_SUITE.erl
changes/ce/fix-12759.en.md

fix(emqx_mgmt_data_backup): remove invalid uploaded backup files

---

apps/emqx/src/emqx_hookpoints.erl
apps/emqx_enterprise/src/emqx_enterprise_schema.erl
apps/emqx_message_validation/src/emqx_message_validation.erl
apps/emqx_message_validation/src/emqx_message_validation_http_api.erl
apps/emqx_message_validation/src/emqx_message_validation_registry.erl
apps/emqx_message_validation/src/emqx_message_validation_schema.erl
apps/emqx_message_validation/test/emqx_message_validation_http_api_SUITE.erl
apps/emqx_message_validation/test/emqx_message_validation_tests.erl
apps/emqx_rule_engine/src/emqx_rule_events.erl
rel/i18n/emqx_message_validation_http_api.hocon
rel/i18n/emqx_message_validation_schema.hocon

Continuation of #12711 .
Fixes https://emqx.atlassian.net/browse/EMQX-12054

Follow up features and fixes for message validation - part 1

---

apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl

test: fix flaky test

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl

fix(ds): add caller to pending replies before flushing and reply failures to sync callers

---

apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl

fix: return not_implemented error for mqueue/inflight msgs queries

---

apps/emqx_management/src/emqx_mgmt.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl

fix:(emqx_mgmt): handle client shutdown errors in call_client

---

apps/emqx/include/emqx_shared_sub.hrl
apps/emqx/src/emqx_broker.erl
apps/emqx/src/emqx_broker_helper.erl
apps/emqx/src/emqx_shared_sub.erl
apps/emqx/test/emqx_broker_SUITE.erl
apps/emqx/test/emqx_stats_SUITE.erl
apps/emqx_management/src/emqx_mgmt_api_metrics.erl
changes/ce/fix-12765.en.md

Fixes 
[https://emqx.atlassian.net/browse/EMQX-12043](https://emqx.atlassian.net/browse/EMQX-12043)
[https://emqx.atlassian.net/browse/EMQX-12056](https://emqx.atlassian.net/browse/EMQX-12056)

fix(stats): `'subscribers.count'` contains shared-subscriber

---

apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl

test: attempt to fix flaky test

---

apps/emqx/src/emqx_persistent_message.erl
apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_session.erl
apps/emqx/src/emqx_zone_schema.erl
apps/emqx/test/emqx_config_SUITE.erl
changes/ce/feat-12739.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-11928

feat(sessds): Add zone overrides for session durability settings

---

apps/emqx/src/bpapi/emqx_bpapi.erl

```
=====
===== LOGGING STARTED Tue Mar 26 03:37:45 UTC 2024
=====
EMQX_API_KEY__BOOTSTRAP_FILE [api_key.bootstrap_file]: /etc/eqa/apikey.conf
EMQX_PROMETHEUS__PUSH_GATEWAY_SERVER [prometheus.push_gateway_server]: http://monitor-0.hs.monitor.svc.cluster.local:9091
EMQX_NODE__ROLE [node.role]: replicant
EMQX_NODE__COOKIE [node.cookie]: ******
EMQX_NODE__NAME [node.name]: emqx@10.42.2.12
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx,{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{badmatch,{aborted,{undef,[{emqx_bpapi,announce_fun,['emqx@10.42.2.12',[{emqx,1},{emqx,2},{emqx_authn,1},{emqx_authz,1},{emqx_bridge,1},{emqx_bridge,2},{emqx_bridge,3},{emqx_bridge,4},{emqx_bridge,5},{emqx_bridge,6},{emqx_broker,1},{emqx_cm,1},{emqx_ …
```

fix: bpapi undef abort on old node

---

apps/emqx/priv/bpapi.versions
apps/emqx/src/emqx_metrics.erl
apps/emqx/src/proto/emqx_metrics_proto_v2.erl
apps/emqx_conf/src/emqx_conf_schema.erl
apps/emqx_dashboard/include/emqx_dashboard.hrl
apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
apps/emqx_enterprise/src/emqx_enterprise_schema.erl
apps/emqx_message_validation/src/emqx_message_validation.erl
apps/emqx_message_validation/src/emqx_message_validation_http_api.erl
apps/emqx_message_validation/src/emqx_message_validation_registry.erl
apps/emqx_message_validation/test/emqx_message_validation_http_api_SUITE.erl
apps/emqx_prometheus/include/emqx_prometheus.hrl
apps/emqx_prometheus/src/emqx_prometheus_api.erl
apps/emqx_prometheus/src/emqx_prometheus_config.erl
apps/emqx_prometheus/src/emqx_prometheus_message_validation.erl
apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl
apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
rel/i18n/emqx_message_validation_http_api.hocon
rel/i18n/emqx_prometheus_api.hocon
scripts/find-apps.sh

Fixes https://emqx.atlassian.net/browse/EMQX-12071

feat(message validation): implement metrics

---

.github/workflows/run_emqx_app_tests.yaml

ci: split emqx standalone app tests

---

scripts/spellcheck/spellcheck.sh

ci: concurrent spellcheck

---

apps/emqx/rebar.config
apps/emqx_machine/src/emqx_machine.erl
changes/ce/fix-12786.en.md
mix.exs
rebar.config

Fixes [EMQX-12099](https://emqx.atlassian.net/browse/EMQX-12099)

fix(mria): Strictly check compatibility of the replicant with core

---

apps/emqx/src/emqx_trace/emqx_trace_handler.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12104 that introduced by https://github.com/emqx/emqx/pull/12785
- ~f changed package build workflow, pass [this …

chore: remove the duplicated time field

---

apps/emqx_message_validation/src/emqx_message_validation_http_api.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12102

docs(message validation): add swagger API examples

---

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl

refactor: remove already bound variable

---

apps/emqx_management/src/emqx_mgmt.erl

Follow-up fix for https://github.com/emqx/emqx/pull/12814/files#r1544829624

fix(emqx_mgmt): do not attempt to get a stacktrace of a remote process

---

apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_persistent_session_ds_stream_scheduler.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer.erl
apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl

fix(dsrepl): handle RPC errors gracefully when storage is down

---

apps/emqx_bridge/test/emqx_bridge_api_SUITE.erl
apps/emqx_resource/src/emqx_resource.app.src
apps/emqx_resource/src/emqx_resource_manager.erl
apps/emqx_resource/test/emqx_connector_demo.erl
apps/emqx_resource/test/emqx_resource_SUITE.erl
apps/emqx_utils/src/emqx_utils_redact.erl
changes/ce/fix-12812.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12015

feat(resource manager): perform non-blocking health checks

---

apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
changes/ce/feat-12798.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12028

feat(client mgmt api): add cursor-based list API

---

apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12143

feat(ds): clear all checkpoints when (re)starting storage layer

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
apps/emqx_management/src/emqx_mgmt_api_ds.erl
apps/emqx_management/src/emqx_mgmt_cli.erl
apps/emqx_management/test/emqx_mgmt_api_ds_SUITE.erl

feat(ds): Add REST API for durable storage

---

changes/feat-12833.en.md

chore: Add changelog entry for #12833

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

Fixes https://github.com/emqx/emqx/pull/12798#discussion_r1555524603

fix(clients api): use alternative base64 function for OTP 25

---

apps/emqx_management/src/emqx_mgmt.erl
apps/emqx_opentelemetry/src/emqx_opentelemetry.app.src
apps/emqx_opentelemetry/src/emqx_otel_cpu_sup.erl
changes/fix-12844.en.md

- prometheus
- opentelemetry
Fixes https://emqx.atlassian.net/browse/EMQX-12012
- ~[ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) …

fix: cpu usage and idle use two decimal places

---

apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_shard.erl
apps/emqx_durable_storage/src/emqx_ds_replication_shard_allocator.erl
apps/emqx_durable_storage/test/emqx_ds_replication_SUITE.erl

Fixes [EMQX-12110](https://emqx.atlassian.net/browse/EMQX-12110).
TODOs
* Retrying failed transitions.
* More test cases.
* Chaotic `join`s and `leave`s do not cause divergence.
* Unresponsive nodes do not block rebalancing.
* Randomly crashing transitions retried sanely.

feat(dsrepl): implement membership changes and rebalancing

---

Makefile

chore(dashboard): bump dashboard version to v1.8.1 & e1.6.1

---

apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl

Fixes [EMQX-11988](https://emqx.atlassian.net/browse/EMQX-11988)
[EMQX-11988]: https://emqx.atlassian.net/browse/EMQX-11988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(iotdb): correctly handle undefined value of bool type

---

apps/emqx/include/emqx_mqtt.hrl
apps/emqx/src/emqx_sys.erl
apps/emqx/test/emqx_shared_sub_SUITE.erl
apps/emqx_management/src/emqx_mgmt_api_topics.erl
apps/emqx_management/test/emqx_mgmt_api_topics_SUITE.erl
changes/fix-12855.en.md

Fixes [EMQX-12130](https://emqx.atlassian.net/browse/EMQX-12130) [EMQX-12169](https://emqx.atlassian.net/browse/EMQX-12169)
[EMQX-12130]: https://emqx.atlassian.net/browse/EMQX-12130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

fix(mgmt): $queue shared topics format in mgmt topics api

---

apps/emqx_bridge_greptimedb/test/emqx_bridge_greptimedb_SUITE.erl

It's identical test as influxdb, but flaky for greptimedb
probably not worth the time investigating because the test mostly covers non-driver related logic: the buffer worker's return value assertions.

test: delete flaky test for now

---

apps/emqx_utils/src/emqx_variform.erl
apps/emqx_utils/src/emqx_variform_parser.yrl
apps/emqx_utils/src/emqx_variform_scan.xrl
apps/emqx_utils/test/emqx_variform_tests.erl

A follow up fix for PR #12851 where numbers are not handled correctly.

fix(variform): allow numbers to be numbers

---

apps/emqx_dashboard/src/emqx_dashboard_swagger.erl

Targeting release: 5.7.0
Originally the special message of format`$msgid:namespace.id.tag` was intended for dashboard to render the UI with a generic i18n lookup with the provided ID. However, frontend team have their own plan.
This means labels and descriptions are maintained in two different copies, however there is no plan to unify.
After this change, I18n is only used to generate docs:
1. runtime swagger spec at the path `/api-docs`, which is also generated during build time and exported as https://docs.emqx.com/en/enterprise/v5.6/admin/api-docs.html
2. build-time config manual doc generation, which is exported as https://docs.emqx.com/en/enterprise/v5.6.0/hocon/
Both result in the resolved i18n text, but not msgid
No release note because this only affects dashboard which does not use …

refactor: do not generate i18n msgid for dashboard schema json

---

apps/emqx_bridge_kafka/test/emqx_bridge_kafka_tests.erl
apps/emqx_conf/src/emqx_conf.erl
apps/emqx_dashboard/src/emqx_dashboard_schema_api.erl

move dashboard schema generation code to the right module

refactor: resolve some old TODOs

---

apps/emqx_durable_storage/src/emqx_ds_builtin_db_sup.erl
apps/emqx_durable_storage/src/emqx_ds_replication_layer_shard.erl
apps/emqx_durable_storage/test/emqx_ds_replication_SUITE.erl

fix(dsrepl): make replication-related tests more stable

---

changes/ce/fix-12887.en.md
mix.exs
rebar.config

Bump esasl to 0.2.1
Fixes #12860
Tests are covered in esasl. 

fix(mqtt): enhanced auth with scram

---

apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl
apps/emqx_bridge_influxdb/test/emqx_bridge_influxdb_SUITE.erl
changes/fix-12880.en.md

Fixes [EMQX-12147](https://emqx.atlassian.net/browse/EMQX-12147)
[EMQX-12147]: https://emqx.atlassian.net/browse/EMQX-12147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(influx): literal number values in tag set

---

apps/emqx_license/src/emqx_license.app.src
apps/emqx_license/src/emqx_license.erl
apps/emqx_license/test/emqx_license_SUITE.erl
changes/ee/fix-12888.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12183

fix(license): license file is not taking effect after importing backup files

---

apps/emqx_durable_storage/src/emqx_ds_storage_snapshot.erl

fix(dssnap): ensure idempotent write of empty chunks

---

apps/emqx_license/include/emqx_license.hrl
apps/emqx_license/src/emqx_license.erl
apps/emqx_license/src/emqx_license_checker.erl
apps/emqx_license/src/emqx_license_http_api.erl
apps/emqx_license/src/emqx_license_parser.erl
apps/emqx_license/src/emqx_license_schema.erl
apps/emqx_license/test/emqx_license_cli_SUITE.erl
apps/emqx_license/test/emqx_license_http_api_SUITE.erl
rel/i18n/emqx_license_schema.hocon

Fixes  https://emqx.atlassian.net/browse/EMQX-12205

feat(license): add business-critical customer type

---

.ci/docker-compose-file/docker-compose-iotdb.yaml
.ci/docker-compose-file/toxiproxy.json
apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_iotdb/include/emqx_bridge_iotdb.hrl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb.erl
apps/emqx_bridge_iotdb/src/emqx_bridge_iotdb_connector.erl
apps/emqx_bridge_iotdb/test/emqx_bridge_iotdb_impl_SUITE.erl
apps/emqx_resource/src/emqx_resource_buffer_worker.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12202
bug ref: https://github.com/apache/iotdb/issues/12375

feat: support iotdb 1.3.0

---

apps/emqx_gateway_stomp/src/emqx_gateway_stomp.app.src
apps/emqx_gateway_stomp/src/emqx_stomp_channel.erl
apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl
changes/ce/fix-12902.md

Fixes https://emqx.atlassian.net/browse/EMQX-11479

Pass the Content-type of MQTT message to the Stomp message

---

changes/ee/feat-12898.en.md

chore: add iotdb130 changelog

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_egress.erl

Fixes [EMQX-12215](https://emqx.atlassian.net/browse/EMQX-12215)
Egress buffering was broken in a subtle way: it would flush the buffer on every incoming message, leading to inefficiency.
Also this PR removes needless flushing of the empty buffer.
[EMQX-12215]: https://emqx.atlassian.net/browse/EMQX-12215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ds): Fix egress flush condition

---

apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq.erl
apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl
changes/ee/feat-12899.en.md
rel/i18n/emqx_bridge_rocketmq.hocon
rel/i18n/emqx_bridge_rocketmq_connector.hocon
scripts/spellcheck/dicts/emqx.txt

feat(rocketmq): add support for namespace and key dispatch strategy

---

apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo.erl
apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl
apps/emqx_bridge_dynamo/test/emqx_bridge_dynamo_SUITE.erl
changes/ee/fix-12895.en.md
rel/i18n/emqx_bridge_dynamo.hocon
rel/i18n/emqx_bridge_dynamo_connector.hocon

fix(dynamo): Added missing keys for DynamoDB

---

apps/emqx_resource/src/emqx_resource_buffer_worker.erl
apps/emqx_rule_engine/src/emqx_rule_runtime.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl

Fixes:
https://emqx.atlassian.net/browse/EMQX-12025

feat(rule tracing): add rule trigger time meta data field

---

apps/emqx_durable_storage/README.md

docs(ds): Update README with CLI and REST API endpoints

---

rel/i18n/emqx_bridge_pulsar.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-12219
Refine a config doc.

docs: improve doc for pulsar auth config fields

---

apps/emqx_auth_mnesia/src/emqx_auth_mnesia.app.src
apps/emqx_auth_mnesia/src/emqx_authn_mnesia.erl
apps/emqx_auth_mnesia/test/emqx_authn_mnesia_SUITE.erl
changes/ce/feat-12923.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12239

chore: provided more specific error for wrong import method

---

.github/workflows/run_conf_tests.yaml
apps/emqx/test/emqx_cth_peer.erl
apps/emqx_auth/src/emqx_authn/emqx_authn_utils.erl
apps/emqx_auth_jwt/src/emqx_authn_jwt.erl
apps/emqx_auth_jwt/src/emqx_authn_jwt_schema.erl
apps/emqx_auth_jwt/test/emqx_authn_jwt_SUITE.erl
changes/ce/feat-12418.en.md
rel/i18n/emqx_authn_jwt_schema.hocon

Fixes [EMQX-11084](https://emqx.atlassian.net/browse/EMQX-11084)
[EMQX-11084]: https://emqx.atlassian.net/browse/EMQX-11084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(jwt_auth): improve verify_claims handling and docs

---

apps/emqx_auth/src/emqx_authz/emqx_authz_rule.erl
apps/emqx_auth/src/emqx_authz/emqx_authz_rule_raw.erl
apps/emqx_auth/src/emqx_authz/sources/emqx_authz_client_info.erl
apps/emqx_auth_mnesia/src/emqx_authz_mnesia.erl

chore(authz): improve and clarify types

---

apps/emqx_bridge_dynamo/src/emqx_bridge_dynamo_connector.erl

fix(dynamo): fixed the keys checking for Dynamo

---

rel/i18n/emqx_schema.hocon
scripts/spellcheck/dicts/emqx.txt

Release version v/e5.7.0
Only a doc improvement.

docs: improve mqtt_path doc

---

apps/emqx/src/emqx_schema.erl
mix.exs
rebar.config
rel/i18n/emqx_schema.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-12162

docs: expose zone config in schema doc

---

apps/emqx_rule_engine/src/emqx_rule_funcs.erl
apps/emqx_utils/src/emqx_variform.erl
apps/emqx_utils/src/emqx_variform_bif.erl
apps/emqx_utils/test/emqx_variform_tests.erl

This is a follow up enhancement for https://github.com/emqx/emqx/pull/12872

feat: add conditions to variform expressions

---

apps/emqx/src/emqx_schema.erl

Fixes [EMQX-12252](https://emqx.atlassian.net/browse/EMQX-12252)
[EMQX-12252]: https://emqx.atlassian.net/browse/EMQX-12252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(schema): description should be in binary() type

---

apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_http/test/emqx_bridge_http_v2_SUITE.erl
apps/emqx_utils/src/emqx_utils_redact.erl
changes/ce/fix-12948.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12213

fix(http connector): deobfuscate sensitive headers

---

README-CN.md
README.md
apps/emqx_message_validation/src/emqx_message_validation_schema.erl
apps/emqx_message_validation/test/emqx_message_validation_tests.erl
changes/ee/fix-12950.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12254

fix(message validation): validate duplicated topics

---

apps/emqx_rule_engine/src/emqx_rule_events.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12284

fix(rule events): don't list validation failure event in CE API

---

.github/workflows/build_packages_cron.yaml

https://github.com/emqx/emqx/actions/runs/8928378542/job/24523826717#step:7:14

ci(cron packages): use unique upload names for different branches

---

apps/emqx_dashboard/src/emqx_dashboard_schema.erl
rel/i18n/emqx_dashboard_schema.hocon

chore: unhide dashboard default_password config

---

apps/emqx/src/emqx_listeners.erl
apps/emqx_dashboard/src/emqx_dashboard_api.erl

chore: fix typo

---

apps/emqx_license/src/emqx_license.erl

fix(emqx_license): don't crash if an imported backup file has no license config

---

apps/emqx_message_validation/src/emqx_message_validation.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12298

fix(message validation): apply config CRUD operations on whole cluster

---

apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx/src/emqx_persistent_session_ds.hrl
apps/emqx/src/emqx_persistent_session_ds_state.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12266

fix(mgmt clients api): hold channel info after client disconnects for display in API

---

apps/emqx_message_validation/src/emqx_message_validation_schema.erl
apps/emqx_message_validation/test/emqx_message_validation_tests.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12299

fix(message validation): limit the length of validation name

---

changes/ce/feat-11721.en.md
rel/i18n/emqx_schema.hocon
scripts/spellcheck/dicts/emqx.txt

followup review comments in https://github.com/emqx/emqx/pull/12955

chore: update doc for `partial_chain` and `verify_peer_ext_key_usage`

---

apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12268

fix(clients mgmt api): set `durable` flag for DS sessions and subscriptions, add `clientid` to subscriptions

---

apps/emqx/src/emqx_channel.erl
apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
changes/ce/fix-12976.md

Fixes https://emqx.atlassian.net/browse/EMQX-12246

Fix duplicated disconnect event

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_shard.erl

Assuming established Erlang distribution channel is a reliable way to tell whether a remote node is reachable.

feat(dsrepl): avoid contacting unreachable ra servers

---

apps/emqx/src/emqx_broker_helper.erl
apps/emqx/src/emqx_cm_sup.erl
apps/emqx/src/emqx_persistent_session_bookkeeper.erl
apps/emqx/src/emqx_persistent_session_ds_state.erl
apps/emqx/src/emqx_router_helper.erl
apps/emqx/src/emqx_schema.erl
apps/emqx/test/emqx_config_SUITE.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12267

fix(monitor api): count persistent routes and subscriptions

---

apps/emqx/src/config/emqx_config_zones.erl
apps/emqx/src/emqx_listeners.erl
apps/emqx_management/src/emqx_mgmt_api_listeners.erl
apps/emqx_management/test/emqx_mgmt_api_listeners_SUITE.erl
changes/ce/fix-12993.en.md

Fixes [EMQX-12321](https://emqx.atlassian.net/browse/EMQX-12321)
[EMQX-12321]: https://emqx.atlassian.net/browse/EMQX-12321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

0508 fix update listener zone from dashboard

---

apps/emqx/src/emqx_connection.erl
apps/emqx/src/emqx_frame.erl
apps/emqx/src/emqx_ws_connection.erl
apps/emqx/test/emqx_connection_SUITE.erl
apps/emqx/test/emqx_ws_connection_SUITE.erl
changes/ce/fix-12944.en.md

fix: non-utf8 clientid connect event case crash if strict_mod=false

---

apps/emqx_retainer/src/emqx_retainer.app.src
apps/emqx_retainer/src/emqx_retainer.erl
apps/emqx_retainer/src/emqx_retainer_dispatcher.erl
apps/emqx_retainer/src/emqx_retainer_mnesia.erl
apps/emqx_retainer/test/emqx_retainer_SUITE.erl
changes/ce/fix-12996.en.md

Fixes [EMQX-12319](https://emqx.atlassian.net/browse/EMQX-12319)
Release version: e5.7.0
[EMQX-12319]: https://emqx.atlassian.net/browse/EMQX-12319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(retainer): fix qlc cursor cleanup

---

apps/emqx/src/emqx_access_control.erl
apps/emqx/src/emqx_hookpoints.erl
apps/emqx_rule_engine/src/emqx_rule_api_schema.erl
apps/emqx_rule_engine/src/emqx_rule_events.erl
apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl
changes/ce/feat-12983.en.md
rel/i18n/emqx_rule_api_schema.hocon

feat(events): add new hook && event `client.check_authn_complete`

---

apps/emqx_bridge_s3/src/emqx_bridge_s3_connector.erl
apps/emqx_bridge_s3/test/emqx_bridge_s3_aggreg_upload_SUITE.erl
apps/emqx_connector_aggregator/src/emqx_connector_aggreg_delivery.erl

Otherwise, actions of different types but same names will clash when starting the aggregator supervision tree.

fix(aggregator): namespace aggregator ids with action type

---

.github/workflows/_pr_entrypoint.yaml
.github/workflows/_push-entrypoint.yaml
.github/workflows/run_test_cases.yaml
rebar.config.erl

also optimize cover reports - submit in parallel

ci: send data to coveralls from emqx/emqx only

---

apps/emqx_bridge_kinesis/src/emqx_bridge_kinesis.erl

Fixes  https://emqx.atlassian.net/browse/EMQX-12316
Release version: e5.7.0
this is a data field missed in pr https://github.com/emqx/emqx/pull/12893
- [n/a] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [n/a] Schema changes are backward compatible

fix(kinesis): partition_key should be of 'template' type

---

Makefile
apps/emqx_plugins/include/emqx_plugins.hrl
apps/emqx_plugins/src/emqx_plugins.erl
apps/emqx_plugins/src/emqx_plugins_serde.erl

fix(plugin): add a backup for the plugin config file

---

rel/i18n/emqx_bridge_rocketmq_connector.hocon

Fixes https://emqx.atlassian.net/browse/EMQX-12339

docs(rocketmq): add missing label

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12274

fix(client mgmt api): return expired durable sessions with `is_expired: true`

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12361

fix(client mgmt api): require authn for endpoint

---

apps/emqx_rule_engine/src/emqx_rule_engine_api.erl

Fixes:
https://emqx.atlassian.net/browse/EMQX-12325

fix: include ruleid parameter in swagger example for apply rule endpoint

---

apps/emqx/test/emqx_takeover_SUITE.erl
apps/emqx_durable_storage/src/emqx_ds_storage_layer.erl

Some failed test suites create tens of thousands of log messages. This PR removes much the spam.

tests: Reduce log spam in the failed test suites

---

apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

```
%%% emqx_mgmt_api_clients_SUITE ==> msgs_plain_encoding.t_mqueue_messages: FAILED
%%% emqx_mgmt_api_clients_SUITE ==>
Failure/Error: ?assertEqual(79, Count)
expected: 79
got: 100
line: 1303
```

test(client mgmt api): attempt to fix flaky test

---

apps/emqx/src/emqx_logger_jsonfmt.erl
apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
apps/emqx_management/test/emqx_mgmt_api_trace_SUITE.erl

Fixes:
https://emqx.atlassian.net/browse/EMQX-12344

fix: JSON trace formatter should handle report style log entries

---

apps/emqx_management/src/emqx_mgmt_api_subscriptions.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_subscription_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12294

fix(subs mgmt api): attempt to return mixed clients ds/non-ds in the same page

---

apps/emqx/src/emqx_persistent_session_ds.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12369

fix(ds clients mgmt api): add more fields to disconnected durable sessions

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
apps/emqx_durable_storage/test/emqx_ds_replication_SUITE.erl
apps/emqx_durable_storage/test/emqx_ds_test_helpers.erl
apps/emqx_management/src/emqx_mgmt_api_ds.erl
apps/emqx_management/src/emqx_mgmt_cli.erl
apps/emqx_management/test/emqx_mgmt_api_ds_SUITE.erl

Fixes [EMQX-12366](https://emqx.atlassian.net/browse/EMQX-12366).
[EMQX-12366]: https://emqx.atlassian.net/browse/EMQX-12366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api-ds): provide more information on nonexistent site leave

---

apps/emqx/test/emqx_channel_SUITE.erl
apps/emqx/test/emqx_config_SUITE.erl
apps/emqx_bridge_kafka/src/emqx_bridge_kafka_impl_producer.erl
apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl
apps/emqx_resource/src/emqx_resource_metrics.erl
apps/emqx_rule_engine/src/emqx_rule_events.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl

fix(rocketmq): fix a typo and a RocketMQ encoding error

---

apps/emqx/include/asserts.hrl
apps/emqx/test/emqx_takeover_SUITE.erl

Ex: https://github.com/emqx/emqx/actions/runs/9084293110/job/24967912514?pr=13050#step:6:18330

test: attempt to stabilize a couple flaky tests

---

apps/emqx/src/emqx_banned.erl
apps/emqx/src/emqx_session.erl
apps/emqx/test/emqx_banned_SUITE.erl
apps/emqx_modules/src/emqx_delayed.erl
apps/emqx_modules/src/emqx_modules.app.src
apps/emqx_modules/test/emqx_delayed_SUITE.erl
apps/emqx_retainer/src/emqx_retainer_dispatcher.erl
changes/ce/fix-13006.en.md

Fixes [EMQX-12322](https://emqx.atlassian.net/issues/EMQX-12322)
[EMQX-12322]: https://emqx.atlassian.net/browse/EMQX-12322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(banned): verify delayed/taken over/retained messages against clientid_re ban rules

---

apps/emqx/src/emqx_schema.erl
apps/emqx_auth/src/emqx_authn/emqx_authn_chains.erl
apps/emqx_auth_http/src/emqx_authn_http.erl
changes/ce/fix-13041.en.md

Fixes [EMQX-12377](https://emqx.atlassian.net/browse/EMQX-12377)
[EMQX-12377]: https://emqx.atlassian.net/browse/EMQX-12377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

0513 http authn header missing should result in meaningful error message

---

apps/emqx/src/emqx_logger_jsonfmt.erl
apps/emqx/src/emqx_logger_textfmt.erl
apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
apps/emqx/src/emqx_trace/emqx_trace_json_formatter.erl
apps/emqx/test/emqx_logger_fmt_SUITE.erl

Fixes:
https://emqx.atlassian.net/browse/EMQX-12380

fix: evaluate lazy values in normal log formatters when level is debug

---

apps/emqx/src/emqx_broker_helper.erl
apps/emqx/src/emqx_stats.erl
apps/emqx_dashboard/include/emqx_dashboard.hrl
apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
apps/emqx_management/src/emqx_mgmt.erl
apps/emqx_management/src/emqx_mgmt_api_nodes.erl
apps/emqx_management/src/emqx_mgmt_api_stats.erl
apps/emqx_management/test/emqx_mgmt_api_stats_SUITE.erl
apps/emqx_prometheus/src/emqx_prometheus.erl
apps/emqx_prometheus/test/emqx_prometheus_data_SUITE.erl
changes/ce/fix-13067.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12267

fix(dssubs): introduce separate gauge for subscriptions from durable sessions

---

apps/emqx_bridge_s3/src/emqx_bridge_s3_upload.erl
rel/i18n/emqx_bridge_s3_upload.hocon

chore(s3-bridge): decrease default aggregation settings

---

apps/emqx_dashboard/test/emqx_dashboard_api_test_helpers.erl
apps/emqx_license/src/emqx_license_checker.erl
apps/emqx_license/src/emqx_license_http_api.erl
apps/emqx_license/test/emqx_license_http_api_SUITE.erl

[EMQX-12205](https://emqx.atlassian.net/browse/EMQX-12205)
Release version: e5.7.0
- [~] ~~Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files~~ this not a GA feature
- [~] ~~Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket~~ this is not a GA feature
[EMQX-12205]: https://emqx.atlassian.net/browse/EMQX-12205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(license): show dynamic max_connections for bc

---

apps/emqx_bridge_influxdb/src/emqx_bridge_influxdb_connector.erl

Provide more detailed error message when connecting to InfluxDB fails.

chore: improved InfluxDB connection error messaging

---

apps/emqx/src/emqx_persistent_session_ds_router.erl
apps/emqx/src/emqx_router.erl

Minor routes fixes

---

apps/emqx/src/emqx_persistent_session_bookkeeper.erl
apps/emqx/src/emqx_schema.erl
apps/emqx/test/emqx_config_SUITE.erl
apps/emqx_dashboard/include/emqx_dashboard.hrl
apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
apps/emqx_management/src/emqx_mgmt_api_clients.erl
apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12396
Fixes https://emqx.atlassian.net/browse/EMQX-12423

fix(client mgmt api): cache disconnected durable session count for `/clients` api

---

apps/emqx_bridge/src/emqx_bridge_v2_api.erl
apps/emqx_bridge/test/emqx_bridge_v2_api_SUITE.erl
apps/emqx_bridge/test/emqx_bridge_v2_testlib.erl
apps/emqx_bridge_pgsql/test/emqx_bridge_v2_pgsql_SUITE.erl
changes/ce/fix-13090.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12435

fix(bridge v2 api): don't attempt to start disabled connector when starting action/source

---

apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12423 
Fixes https://emqx.atlassian.net/browse/EMQX-12267

fix(monitor api): add ds connections and subscriptions to old counters

---

apps/emqx_bridge_rocketmq/src/emqx_bridge_rocketmq_connector.erl

fix(rocketmq): fix namespace error for RocketMQ

---

apps/emqx/src/emqx_persistent_session_ds.erl

Fixes [EMQX-12404](https://emqx.atlassian.net/browse/EMQX-12404)
[EMQX-12404]: https://emqx.atlassian.net/browse/EMQX-12404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sessds): Handle unrecoverable errors

---

apps/emqx_durable_storage/src/emqx_ds_replication_layer_meta.erl
apps/emqx_durable_storage/src/emqx_ds_replication_shard_allocator.erl

Part of [EMQX-12415](https://emqx.atlassian.net/browse/EMQX-12415).
[EMQX-12415]: https://emqx.atlassian.net/browse/EMQX-12415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dsrepl): properly handle transaction abort during forget site

---

apps/emqx/test/emqx_cth_cluster.erl
apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
apps/emqx_dashboard/src/emqx_dashboard_monitor_api.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12423 
Fixes https://emqx.atlassian.net/browse/EMQX-12267

fix(monitor api): fix cluster metric aggregation

---

apps/emqx_prometheus/src/emqx_prometheus.erl

Fixes [EMQX-12399](https://emqx.atlassian.net/browse/EMQX-12399)
[EMQX-12399]: https://emqx.atlassian.net/browse/EMQX-12399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add ds metrics into prometheus zipper init acc

---

apps/emqx/src/emqx_schema.erl
apps/emqx/test/emqx_config_SUITE.erl

fix(sessds): Change the defaults to renew streams every 1 second

---

apps/emqx_management/src/emqx_mgmt_api_clients.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12427

fix(client mgmt api): hide unused return type

---

apps/emqx_management/src/emqx_mgmt_api_plugins.erl
apps/emqx_management/src/proto/emqx_mgmt_api_plugins_proto_v3.erl
apps/emqx_plugins/include/emqx_plugins.hrl
apps/emqx_plugins/src/emqx_plugins.erl

Fixes [EMQX-12444](https://emqx.atlassian.net/browse/EMQX-12444)
[EMQX-12444]: https://emqx.atlassian.net/browse/EMQX-12444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: allow put plugin config without schema

---

apps/emqx/include/emqx_release.hrl
deploy/charts/emqx-enterprise/Chart.yaml
deploy/charts/emqx/Chart.yaml

chore: prepare for release cut 5.7.0-rc.1

---

Makefile
apps/emqx_plugins/src/emqx_plugins.erl

fix: match decode plugin config map failed case

---

apps/emqx/include/http_api.hrl
apps/emqx_bridge/src/emqx_bridge_api.erl
apps/emqx_dashboard/src/emqx_dashboard_swagger.erl
apps/emqx_dashboard_sso/src/emqx_dashboard_sso.app.src
apps/emqx_dashboard_sso/src/emqx_dashboard_sso_saml_api.erl
apps/emqx_license/src/emqx_license_http_api.erl
apps/emqx_management/test/emqx_mgmt_api_banned_SUITE.erl
apps/emqx_management/test/emqx_mgmt_api_test_util.erl
apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
changes/ce/fix-13078.en.md
mix.exs
rebar.config

Fixes [12401](https://emqx.atlassian.net/browse/EMQX-12401)

feat: return 415 when UNSUPPORTED_MEDIA_TYPE

---

Makefile

chore(dashboard): bump dashboard version to v1.9.0 & e1.7.0

---

apps/emqx_authz/src/emqx_authz.app.src
apps/emqx_authz/src/emqx_authz_http.erl
apps/emqx_authz/test/emqx_authz_http_SUITE.erl
apps/emqx_bridge_dynamo/rebar.config
apps/emqx_bridge_hstreamdb/rebar.config
apps/emqx_bridge_kinesis/rebar.config
apps/emqx_s3/rebar.config

Fixes EMQX-12487
Release version: v/e5.2.1

fix(authz_http): fix content-type header in http request

---

deploy/packages/deb/debian/postrm
mix.exs
rebar.config
scripts/pkg-tests.sh
scripts/ui-tests/dashboard_test.py

fix(deb): fix apt purge when emqx service was still running

---

rel/config/ee-examples/file_transfer-with-local-exporter.conf.example
rel/config/ee-examples/file_transfer-with-s3-exporter.conf.example

refactor: hide 'enable' config from example when it's 'true' by default

---

apps/emqx_rule_engine/src/emqx_rule_engine.app.src
apps/emqx_rule_engine/src/emqx_rule_events.erl

fix: missing rule event i18n in zh_cn

---

apps/emqx_management/test/emqx_mgmt_api_status_SUITE.erl

See https://github.com/emqx/emqx-platform/pull/272.
The test may fail if it runs in CI independently.

chore(tests): improve test stability

---

Makefile

chore(dashboard): bump dashboard version to v1.9.1-beta.1 & e1.7.1-beta.1

---

apps/emqx_plugins/src/emqx_plugins.app.src
apps/emqx_plugins/src/emqx_plugins.erl

Fixes [EMQX-12479](https://emqx.atlassian.net/browse/EMQX-12479)
[EMQX-12479]: https://emqx.atlassian.net/browse/EMQX-12479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: get plugin app vsn from field `rel_apps`

---

apps/emqx_auth/src/emqx_authz/emqx_authz.erl
apps/emqx_auth/src/emqx_authz/emqx_authz_source.erl
apps/emqx_auth/src/emqx_authz/sources/emqx_authz_client_info.erl

https://askemq.com/t/topic/8529/4

chore: make authz's logs easier to understand

---

apps/emqx_conf/src/emqx_conf_schema.erl
apps/emqx_resource/src/emqx_resource.app.src
apps/emqx_resource/src/emqx_resource_buffer_worker.erl
changes/ce/feat-13144.en.md

Fixes [EMQX-12458](https://emqx.atlassian.net/browse/EMQX-12458)
Release version: e/v5.8.0
- [na] Added tests for the changes
[EMQX-12458]: https://emqx.atlassian.net/browse/EMQX-12458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(bridges): increase log level for bridge buffer overflow reports

---

.ci/fvt_tests/http_server/src/http_server.app.src
Makefile
elvis.config
git-blame-ignore-revs

~Fixes~
**NO** Production code changed.
~Release version: v/e5.?~

build: run erlfmt with files name by `$(FIND)`

---

apps/emqx_dashboard/src/emqx_dashboard_swagger.erl

Use case:
Request body schema is a list with a custom `validator`, e.g.:
```
?HOCON(?ARRAY(?R_REF("link")), Meta#{default => [], validator => fun links_validator/1})
```
```
#{default => [],
type => {array,{ref,emqx_cluster_link_schema,"link"}},
examples =>
#{<<"example">> =>
[#{<<"enable">> => true,<<"pool_size">> => 10,
<<"server">> => <<"emqxcl_b.host:1883">>,
<<"ssl">> => #{<<"enable">> => false},
<<"topics">> =>
[<<"t/topic-example">>,<<"t/topic-filter-example/1/#">>],
<<"upstream">> => <<"emqxcl_b">>},
#{<<"enable">> => true,<<"pool_size">> => 10,
<<"server">> => <<"emqxcl_c.host:1883">>,
<<"ssl">> => #{<<"enable">> => false},
<<"topics">> =>
[<<"t/topic-example">>,<<"t/topic-filter-example/1/#">>],
<<"upstream">> => <<"emqxcl_c">>}]},
validator => …
```

feat(emqx_dashboard_swagger): apply field validator in request body check

---

apps/emqx_rule_engine/src/emqx_rule_events.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_2_SUITE.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_test_SUITE.erl

fix: fix typos

---

apps/emqx_utils/src/emqx_utils_sql.erl
apps/emqx_utils/test/emqx_utils_sql_SUITE.erl
changes/ce/fix-13189.en.md

Fixes [EMQX-12504](https://emqx.atlassian.net/browse/EMQX-12504)
[EMQX-12504]: https://emqx.atlassian.net/browse/EMQX-12504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(utils_sql): improve insert sql regular expression

---

Makefile

ci: fix `make fmt` to take into account checkouts and elixir deps

---

apps/emqx/include/emqx_release.hrl
apps/emqx/src/emqx.app.src
apps/emqx_auth_jwt/src/emqx_auth_jwt.app.src
apps/emqx_auth_jwt/src/emqx_authn_jwks_client.erl
mix.exs

Fixes  EEC-1039
Release version: -

PATCH fix(emqx_authn_jwks) add a user-agent header to jwks HTTP request

---

apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl

chore: cosmetic changes

---

apps/emqx_dashboard/src/emqx_dashboard_monitor.erl
apps/emqx_dashboard/test/emqx_dashboard_monitor_SUITE.erl
changes/ce/fix-13156.en.md

Fixes [EMQX-12481](https://emqx.atlassian.net/browse/EMQX-12481), #13143 
[EMQX-12481]: https://emqx.atlassian.net/browse/EMQX-12481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dashboard_monitor): correctly merge old and new sample data

---

apps/emqx_bridge/src/emqx_bridge_v2.erl
apps/emqx_resource/src/emqx_resource_manager.erl

Fixes https://emqx.atlassian.net/browse/EMQX-12521

fix: remove another redundant health check

---

apps/emqx_schema_validation/src/emqx_schema_validation.app.src
apps/emqx_schema_validation/src/emqx_schema_validation.erl
apps/emqx_schema_validation/src/emqx_schema_validation_app.erl
apps/emqx_schema_validation/src/emqx_schema_validation_config.erl
apps/emqx_schema_validation/src/emqx_schema_validation_registry.erl

To conform to comment from another PR:
https://github.com/emqx/emqx/pull/13199#discussion_r1632658742
... since schema validation is the "inspiration" for message transformation.
Addresses https://github.com/emqx/emqx/pull/13199#discussion_r1633096025

refactor(schema validation): module organization and position indexing

---

apps/emqx_rule_engine/src/emqx_rule_actions.erl
apps/emqx_rule_engine/test/emqx_rule_engine_api_rule_apply_SUITE.erl
apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl
changes/ce/fix-13207.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12328

fix(rule actions): check `republish` action result for metrics

---

apps/emqx_schema_registry/include/emqx_schema_registry.hrl
apps/emqx_schema_registry/src/emqx_schema_registry.app.src
apps/emqx_schema_registry/src/emqx_schema_registry.erl
apps/emqx_schema_registry/src/emqx_schema_registry_serde.erl
apps/emqx_schema_registry/test/emqx_schema_registry_serde_SUITE.erl
apps/emqx_schema_validation/src/emqx_schema_validation.app.src
apps/emqx_schema_validation/src/emqx_schema_validation.erl
apps/emqx_schema_validation/src/emqx_schema_validation_config.erl
apps/emqx_schema_validation/test/emqx_schema_validation_http_api_SUITE.erl
changes/ee/feat-13210.en.md

Fixes https://emqx.atlassian.net/browse/EMQX-12368

feat(schema validation): check references schema names and types before changing config
